### ISSUE TITLE
bonk~ crashes Pd when reading template on Windows

### ISSUE THREAD

**Issue by jwmatthys** [pure-data/pure-data#1]
Using 0.46-6, bonk~ 1.5. Pd crashes completely if you try to read a template with bonk~. Help file is good test case. Works fine on OSX and Linux. Tested on Windows 7.

**Comment by claudeha** [comment]
This shouldn't have been closed, the commit that closed it was intending to close a separate Deken issue as far as I can tell.

**Comment by umlaeute** [comment]
at the cost of adding even more spam to this issue: @chr15m that's a good reason to use full issue-paths (`Closes https://github.com/pure-data/deken#1`) rather than just `Closes #1` in the commit messages...

**Comment by chr15m** [comment]
Ack, sorry.

**Comment by umlaeute** [comment]
confirmed with Pd-0.49-1 on W7/32bit and Win10/32bit.

the Win10/64bit binaries seem to work fine though.

i suspect this is a problem with the libc implementation.

IIRC:
The Win/64bit externals are (like Pd-vanilla) built with MSYS2/MinGW and autotools.
The Win/32bit externals (and Pd) are built somewhat differently (either MSVC or the olde `makefile.gnu`), which causes all kinds of troubles.

**Comment by umlaeute** [comment]
if i compile a Pd/Win32 binary (inluding bonk~) myself (using MSYS2/MinGW and autotools on a Win10 host), the crash is gone.

**Comment by Spacechild1** [comment]
I can reproduce this with Miller's Pd 0.49 32-bit binary, but not with later 32-bit binaries... I just go ahead and close this for now.
