### ISSUE TITLE
static code analysis

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#10]
i've configured [Travis CI](https://travis-ci.org/pure-data/pure-data) and [Coverity Scan](https://scan.coverity.com/projects/pure-data-pure-data) to automatically build and analyse the code-base of Pd.

Currently the configuration is only active in the `travis-ci` branch, but eventually i will create a pull-request to merge it into `master`.

If anybody wants access to the [Coverity Scan dashboard](https://scan.coverity.com/projects/pure-data-pure-data) to see the actual bugs/vulnerabilities/issues, drop me an email.

**Comment by danomatika** [comment]
This is working well so far. Thanks.

**Comment by danomatika** [comment]
Can Travis also run `make distcheck` in addition to `make`?

**Comment by umlaeute** [comment]
sure, see cdd8451

**Comment by danomatika** [comment]
Seems to be working now. Thanks!
