### ISSUE TITLE
atom boxes with width != 0 are 1 pixel shorter

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1017]
when you set an atom box to a width of 0, its height increases 1 pixel. They go back to being 1 pixel smaller if you set the width to something else.

It seems that width = 0 is the real intended height, as it is the same as the message and object box.

**Comment by porres** [comment]
It seems that width = 0 is the real intended height, as it is the same as the message and object box.

**Comment by porres** [comment]
ping @danomatika

**Comment by danomatika** [comment]
I think of this as a feature not a bug.

**Comment by porres** [comment]
ok, cool, but how? :)

**Comment by danomatika** [comment]
You can see which ones do not have a fixed width. I honestly am not bothered by this.

**Comment by porres** [comment]
I just thought it could have been unintentional, rather than being annoying or not. 

And it's quite subtle anyway to jump to the eye as annoying (it took ages for me to notice it). It's also subtle to the point that I find hard to judge its width setting by its look like that. Not to mention I also can't see the need to be able to judge its width setting by its look.

**Comment by danomatika** [comment]
Yeah, it doesn't have a huge *functional* use, but is it really that big of a deal s compared to many other bugs and maintenance which are frankly more important.

**Comment by porres** [comment]
this has been fixed
