### ISSUE TITLE
Issue using readsf~ and soundfile_info when reading too big files.

### ISSUE THREAD

**Issue by kaffeocigg** [pure-data/pure-data#1028]
I used the [writesf~] object to write a 48 channel .wav file. When I made it 9 minutes long it got about 2,5 gib. Then the [writesf~] object threw me an error: "soundfile_info_read: cannot open /home/pi/scene5.wav". Using the [env~] object I could also see that no audio was coming out of the [readsf~] object. Making another .wav 2.4 gib didn't work, but then writing one that was 1,8 gib worked fine. Is there a 2 gib limit somewhere? 

Running purr data on a rpi 4 with 4 gib RAM (3.3 gib RAM available when trying to read soundfile).

**Comment by umlaeute** [comment]
Purr Data is a separate project from Pure Data.
please use their tracker, to report issues that concern their fork.

> Is there a 2 gib limit somewhere?

yes of course. WAV has a 2GB limit.

**Comment by kaffeocigg** [comment]
Aha, thanks for the direction :)

**Comment by umlaeute** [comment]
there has been work on getting support for getting native support for a modern fileformat that allows large files (e.g. CAF); but it is somewhat stalled... #879
