### ISSUE TITLE
fftw on arm

### ISSUE THREAD

**Issue by mxa** [pure-data/pure-data#1035]
configuring with fftw fails on armv7/8 (RPi 3+, RPi 4) even though packages `fftw2` and `fftw-dev` are installed.

**Comment by umlaeute** [comment]
please attach the output of `./configure` (and probably the `config.log` file as well).

apart from that:
- does it work on amd64 resp. i386?
- have you tried with `libfft3-dev`?

i think the fftw codepath is pretty unused/untested.

**Comment by mxa** [comment]
Oh, obviously you are right. It's `libfftw3-dev` and it works. I blame it on Synaptics "Quick filter" search which doesn't show `libfftw` when searching for `fftw`.
