### ISSUE TITLE
request: atom box 'init' value for consistency

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1050]
an init parameter like iemguis

**Comment by umlaeute** [comment]
alternative request: remove the "init" from the iemguis

(people are probably using this, so it's hard to get rid of it; but it's really just feature bloat and shouldn't have been included in the first place)

**Comment by porres** [comment]
I'm not a fan of that either, neither of built in send/receive and labels (I think a spearate comment gui would be better). But yeah, it's there, people are using it and removing it would break stuff. BTW, this is a request from someone else that came up elsewhere and now I can't remember where.

**Comment by porres** [comment]
closing this, this should be moved to https://github.com/pure-data/pure-data/issues/1344 as a list of things we need to do so gatom boxes behave more like number boxes
