### ISSUE TITLE
GUIs drawing out of bounds in GOP

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1053]
Some GUI objects, like iemguis might draw in the parent patch even if outside the graphed range in a GOP, which is bad.

For instance, a radio button will draw on parent if you change its number of cells via a the number message.

See below.

<img width="254" alt="Screen Shot 2020-06-04 at 13 04 22" src="https://user-images.githubusercontent.com/5360142/83780796-05a71d80-a664-11ea-9709-0c734d8e3e38.png">

check the patch: 
[test-GOP.pd.zip](https://github.com/pure-data/pure-data/files/4731328/test-GOP.pd.zip)

Above, the radio button is not actually on the parent, but the subpatch - so you can't click on it or anything.

When setting sendreceive names to empty in iemguis, inlets/outlets will also get drawn.

A similar issue is if you have a GOP inside a GOP that is also outside the graphed range and you change its size via messages.

**Comment by porres** [comment]
I've fixed this for iemgui radios, but there should be more similar fixes to be done for other objects, I'll look through

**Comment by HenriAugusto** [comment]
Somewhat related: issue #752 and PR #627

**Comment by porres** [comment]
> Somewhat related¹: issue #752 and PR #627

Cool,  didn't know #627 would also take care of that... :) 

that looks like a much better way indeed to deal with the drawing issue of 'gop' abstractions nested in other 'gop' but outta bounds.

I can gladly revert the last commit of my PR ( https://github.com/pure-data/pure-data/pull/1079/commits/d6d2218853a7a5f60201bc68f3ec8ad7549f3651 ) in favor of that one!

**Comment by porres** [comment]
fixed in master
