### ISSUE TITLE
change INSTALL.txt to include build instructions for Pd double

### ISSUE THREAD

**Issue by hwkcgn** [pure-data/pure-data#1054]
now that its possible, the install.txt coming with the source should reflect this :-)
(has been discussed on list, so this is just to document it)

suggestion: add after line 100:
Also, if you want to build Pd with double-precision (using 64bit floats instead of 32) , you can specify here:
	
	# build double precision Pd
	./configure CPPFLAGS="-DPD_FLOATSIZE=64"

**Comment by porres** [comment]
why dont you make the change for us in a PR?

**Comment by hwkcgn** [comment]
see miller´s mail here: https://lists.puredata.info/pipermail/pd-list/2020-06/127515.html
i would only halfway know "what" to add, but no way "where".

**Comment by Spacechild1** [comment]
don't worry, I'lll do it.
