### ISSUE TITLE
Program not running after compiling on Ubuntu 20.04

### ISSUE THREAD

**Issue by ofefo** [pure-data/pure-data#1057]
I'm not able to run the binary file with ./pd after following the install instructions for Linux.

The only message i get on terminal is:

```
~/pd/pd-0.50-2/bin$ ./pd
sh: 1: wish: not found
```

And nothing happens. I got no errors on make, only warnings.

**Comment by Lucarda** [comment]
It seems Tk is not pre-installed on your OS.

On a terminal do:

```
sudo apt update
sudo apt install tk
```

this will install "wish".

**Comment by umlaeute** [comment]
btw, the `INSTALL.txt` mentions the dependency on Tcl/Tk explicitely (hence i'm closing this)

~~~
Core runtime requirements:

* Tcl/Tk: Tk wish shell
~~~
