### ISSUE TITLE
The context-sensitive custom mouse cursors are not Retina (HiDPI)

### ISSUE THREAD

**Issue by frou** [pure-data/pure-data#1076]
Pd in general looks wonderfully clean and crisp on Retina (HiDPI) displays.

One holdout seems to be the context-sensitive custom mouse cursors (e.g. the ring when making connections, the cross when selecting connections, the pointing hand a lot of the other time), which are rendered at the correct physical size, but in terms of fidelity look like non-HiDPI bitmaps being interpolated to 200%.

@danomatika @rnkn it looks like you did prior Retina work. What are your thoughts?

---

Pd 0.51.0
macOS 10.15.5

**Comment by rnkn** [comment]
All I did was make an icon (which I think was removed) so 🤷‍♂️

**Comment by danomatika** [comment]
The Pd "vanilla" GUI is mainly Tcl/Tk and the cursors are those included with Tk: http://www.tcl.tk/man/tcl8.6/TkCmd/cursors.htm

Judging form that doc, the ones which are rendered nicely are most likely native macOS cursors, while those that are pixelated are probably ones provided by Tk.

Some options:

1. Ignore it. It's a "paper cut" at most, plus it keeps those particular icons consistent between platforms.

2. Open an issue with the Tk devs about providing 2x and 3x size icons and/or re-rendering the cursor files for macOS with a higher DPI. It follows that Windows and Linux may have the same issue.

3. Propose alternative icons from the Tk icon list which are native to the platform as replacements. We'd probably need to choose different ones for each which could possibly be confusing.

4. Propose replacement icons which we'd need to format for each platform.

Also note: Pd uses Tk 8.5 for macOS so this is something that *may* be corrected in newer versions of Tk, but I have feeling it isn't.

**Comment by frou** [comment]
Dan, thank you very much for the comprehensive info.

After seeing from that linked page that Tk already has the concept of delegating to OS-native cursors, I'll refrain from bugging them about redrawing their standardised ones. There's a good chance that no vector assets existed in the first place!

I'll just patch that `.tcl` source locally to use some macOS native cursors, and maybe report back here in the future if I feel some change is particularly worth advocating.
