### ISSUE TITLE
Able to Crash Pd with Tiling Window Manager

### ISSUE THREAD

**Issue by brandflake11** [pure-data/pure-data#1077]
Hello all,

I use Artix Linux (Arch Linux without systemd) with i3 window manager, and am able to sometimes crash pd when fullscreening, and unfullscreening a pd window, a feature that is built into i3's tiling window management. 

I have found that I am able to sometimes crash pd, by just playing around with managing lots of pd windows. Now, I haven't found an exact reproducible method to crash pd every time, but it always crashes when doing the fullscreening/unfullscreening mentioned above, and only crashes when doing this (I haven't had any other pd crashes other than this). 

I wanted to report this, as I would like to help find the issue. Please let me know if there is anything I can do to help out with this.

**Comment by umlaeute** [comment]
possible dupe of #397 (and related to #358). if you agree, please close this one and add further information to the relevant ticket.

also, it would be great to give special consideration to https://github.com/pure-data/pure-data/issues/397#issuecomment-421400456

**Comment by brandflake11** [comment]
Ahh, this is the issue. Thanks.
