### ISSUE TITLE
allow float in iemguis labels but not their built in send/receive

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1081]
Checking the code of iemguis I realized you can set a float as a send/receive address. This is weird, because you cannot have floats inside [send]/[receive]. Nonetheless, at least you can set a send symbol via the 2nd inlet of [send] as a symbolic float.
Now, what's actually funny is that you can only have integers, and not decimal point floats! 
Since this is the same code that handles labels in iemguis (see https://github.com/pure-data/pure-data/blob/master/src/g_all_guis.c#L200 )

This also means that you cannot have floating point values in labels, which seems like an unnecessary restriction. Allowing decimal point floats seems useful for label display. As far as send/receive, I don't see the usefulness even for integer floats, but well, what are we gonna do? Remove that option? Make a separate code not to allow it?

And in a related discussion, would it be useful to allow receive and send to load floats as send symbols?

**Comment by Spacechild1** [comment]
> Checking the code of iemguis I realized you can set a float as a send/receive address. This is weird

Yes, it's weird indeed and I don't think we should extend this behavior to `[send]`/ `[receive]`. Is there a legitimate use case for using floats as send/receive names?

> This also means that you cannot have floating point values in labels

You can use `[makefilename %f]`, which also has the advantage that you can control the number of digits after the comma, e.g. `[makefilename %.2f]` for 2 digits.

**Comment by porres** [comment]
> You can use [makefilename %f], which also has the advantage that you can control the number of digits after the comma, e.g. [makefilename %.2f] for 2 digits.

the problem is that this cannot be saved or loaded, so you need to always take care of it in the patch

**Comment by Spacechild1** [comment]
Ah, yes, because it is parsed as a float on loading...

**Comment by porres** [comment]
> Is there a legitimate use case for using floats as send/receive names?

I don't think so and I would just prevent this from happening...

**Comment by Spacechild1** [comment]
The reason for not allowing actual floats as receive names is that printf specifiers like `%g` might give different results on different platforms, which is a problem when the receive names are saved and the patch is used on another system.

I can see why you would allow "proper" floats for labels, but please don't do it for send/receive names.

**Comment by porres** [comment]
> Ah, yes, because it is parsed as a float on loading...

so my fix just allows you to also input numbers with decimal points in the properties window, but also allows the label to get saved and loaded as such... the send/receive go along as is the same code.

> I can see why you would allow "proper" floats for labels, but please don't do it for send/receive names.

I could make a separate code section only for labels then

**Comment by porres** [comment]
should I prevent float at all in send/receive?

**Comment by porres** [comment]
I think I should prevent float at in send/receive names!

**Comment by porres** [comment]
closed with https://github.com/pure-data/pure-data/pull/1633
