### ISSUE TITLE
Font size not persistent

### ISSUE THREAD

**Issue by mxa** [pure-data/pure-data#1084]
Fontsize is minuscule when opening Pd with a 4k screen attached. Setting the fontsize makes it better, but when opening Pd again it doesn't remember the setting.
Pd 0.51 on Linux Kubuntu 20.04
Not sure if that's always been like this or a regression.

![Pd_fontsize](https://user-images.githubusercontent.com/1220707/87055000-11a67200-c204-11ea-8c52-6661056ebe4e.gif)

**Comment by umlaeute** [comment]
that's been fixed with 0.51-1

**Comment by mxa** [comment]
Two notes:
1. To change the GUI Fontsize, one has to go to the Font menu item in the Pd window. To change the patch font size one needs to do that in one of the Patch windows. The menu looks the same though. Not a foolproof and clean UX, but I get it.
2. With HiDPI screens the file chooser still has minuscule listings. I have to move my eyes ~10 cm from the screen to decipher something.

**Comment by umlaeute** [comment]
> The menu looks the same though. 

well, it *is* the same.

> Not a foolproof and clean UX, but I get it.

probably not, but what would be better?


> 2. With HiDPI screens the file chooser still has minuscule listings. I have to move my eyes ~10 cm from the screen to decipher something.

please report this as a separate issue (font-settings not effecting a subset of windows is something else as font-settings not being remembered)

**Comment by mxa** [comment]
> probably not, but what would be better?

I think the solution may be a tabbed properties window with all the settings in one place.
