### ISSUE TITLE
disconnect (control+k) not working

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1085]
I used to be able to select 2 objects and use control + k to connect them both, then I could also select them and hit control+k again to disconnect but this is not working anymore (macOS)

**Comment by umlaeute** [comment]
are you sure this ever worked?

i checked with 0.49 (which - iirc - introduced intelligent patching) and it didn't work back then.
i watched my intelligent patching videos again, and they never mention the possibility to disconnect two selected objects via <kbd>Control</kbd>+<kbd>k</kbd>.

however, what used to work (and still works) is to *completely disconnect a single object* by selecting a single object and pressing <kbd>Control</kbd>+<kbd>k</kbd>

see https://vimeo.com/279631360#t=30s
