### ISSUE TITLE
no foreign languages are supported in [cyclone/comment]

### ISSUE THREAD

**Issue by H-MLim** [pure-data/pure-data#1086]
I just tested [cyclone/comment] with very newest version of cyclone and it still crashes when I write any comments on any foreign languages except English. would it be fixed?
(but no problem at default comments via Ctrl+5)

(by the way I told to porres that Pd freezes when I grow up the font size but it didn't happen when tested today again.)

![COMMENTE](https://user-images.githubusercontent.com/68152553/87224513-d43b1380-c3c0-11ea-9003-bf0c6d72965f.JPG)

**Comment by umlaeute** [comment]
that's a problem with cyclone, you should report it there https://github.com/porres/pd-cyclone

**Comment by H-MLim** [comment]
oh. thank you for letting me know. sorry for inconvenience.

**Comment by porres** [comment]
some languages work just fine in Pd Vanilla's comment and stuff, but I tried japanese's katagana and it didn't work. Can you confirm that @H-MLim ? And what about korean? It seems I can only copy and paste... if there are issues with foreign alphabets in vanilla too we need to sort it out.

**Comment by umlaeute** [comment]
in any case, this is not the problem is **this** ticket, which is specific to cyclone/comment.
if there is an issue with katagana or similar, then please open another ticket.
