### ISSUE TITLE
Problem with "&". Not working as expected when changing argument 

### ISSUE THREAD

**Issue by shimanovsky** [pure-data/pure-data#1087]
Experiencing this problem after update. Standard counter with `[ f ] [+ 1] [& 15]` counting up to from 0 to 15 common case) I created _before_ update working as expected, they counting well. But after update I am tried to create new or modify old one it's behavior become weird. It stop counting on some I guess random value or stop on some value and starting counting back and forward. So it happens when I changing argument on existing counter or creating new one. Again previously created counters are ok. 

Tried to restart, create new file, all the same. 
Mac Book Pro 2015, macOS Catalina

**Comment by porres** [comment]
what version of pd are you on? which one did you upgrade to? Don't you mean "%" instead of "&"? Can you provide us a patch?

**Comment by shimanovsky** [comment]
I use just latest version that I have downloaded today.  So "&" I created before update (e.g. yesterday) working well. I found that problem when creating new one today. Also same problem when I changing arguments on "&" I created before. 
[Here is example ](https://app.box.com/s/q4r3477wwdp9scezkjx7unudjgq0lz4z) it's very basic counter

**Comment by porres** [comment]
> I use just latest version that I have downloaded today

where did you download it from? What is the version number?

**Comment by shimanovsky** [comment]
I downloaded from http://msp.ucsd.edu/software.html as usual. Version 0.51
I recorded my screen video [here](https://app.box.com/s/r01khdisac5n9zud0lno6l81az7tdzos)

**Comment by shimanovsky** [comment]
And everything else looks like ok. I didn't experienced any PD or system errors while running PD. 
![pd-test](https://user-images.githubusercontent.com/24951180/87470296-3c8a2f00-c625-11ea-8dae-4ada8726084a.gif)

**Comment by porres** [comment]
I tested your patch in both 0.51 and 0.50, the result is the same, now, I don't know what exactly you expect with [&], and my math is bad enough to not take a guess. All I know is that I don't see discrepancies and nothing weirder in the new version. Let's see who else has something to say here... Now, why don't you use '%' for the counter? I think this is what you want, a looping counter, right?

**Comment by porres** [comment]
> Mac Book Pro 2015, macOS Catalina

MacBook Pro 2016, macOS Mojave

**Comment by shimanovsky** [comment]
>Now, why don't you use '%' for the counter?
I tried and it works as expected. Yes, mostly I used this in looping counters and "&" was fine. I started creating counters this way with "&" since I found in the docs that "%" is old one and provided for back capability, so I used  "&", as operator for me looks more common. And a lot of patches I have explored in the community also used "&" so it worked well I didn't care before.

**Comment by porres** [comment]
>  I found in the docs that "%" is old one and provided for back capability, so I used "&"

it also says to use [mod] instead of '%' ;)

**Comment by Spacechild1** [comment]
@shimanovsky `%` and `&` do completely different things. The first is modulo, the second is bitwise AND.

`[% N]`, *where N is a power of 2*, can be written as `[& N-1]`. But never do this, unless you have a very good reason (e.g. high performance C code).

Your second example `[& 59]`, however, is broken because 60 is not a power of 2 and I'm sure it did not work as a modulo counter in earlier Pd versions ;-)
