### ISSUE TITLE
plot: no such field errors

### ISSUE THREAD

**Issue by derekxkwan** [pure-data/pure-data#1093]
I seem to be getting an abundance of plot: "no such field" (in this case: `plot: testarray: no such field`) errors in 0.51.0 even though things manage to get plotted properly (on ubuntu 18.04). see example patch

```
#N struct teststruct float a array testarray arraystruct;
#N struct arraystruct float b;
#N canvas 406 214 682 433 12;
#X obj 99 71 struct teststruct float a array testarray arraystruct
;
#X obj 195 173 struct arraystruct float b;
#X msg 193 242 \; pd-data clear \; pd-data read teststruct.txt;
#X obj 156 307 plot -y b(1:200)(200:0) testarray 0 1 0 10 30;
#N canvas 1101 347 450 300 data 1;
#X scalar teststruct 0 \; 1 \; 2 \; 3 \; 4 \; 5 \; 6 \; 50 \; 100 \;
200 \; \;;
#X restore 451 150 pd data;
```

reading in given teststruct.txt

```
data;
template teststruct;
float a;
array testarray arraystruct;
;
template arraystruct;
float b;
;
;
teststruct 0;
1;
2;
3;
4;
5;
6;
50;
100;
200;
;
```

**Comment by Spacechild1** [comment]
what happens in Pd 0.50?

**Comment by derekxkwan** [comment]
ah, don't have access to 0.50 atm but the errors went away after putting the struct declarations in different canvases (opened the patch in Purr Data which gave the error messages about canvases, maybe would be worthwhile to have a similar warning in vanilla?)

**Comment by porres** [comment]
> maybe would be worthwhile to have a similar warning in vanilla?

open a request for it here? :)
