### ISSUE TITLE
set nbx's default font size to the patch's size at creation

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1098]
this is what happens to an atom number box and it's quite useful

**Comment by porres** [comment]
just to clear, unlike atom boxes, we don't need to change nbx's size according to changes in the font size, that'd be bad... cause we can change and set whatever size to nbx so it should just stick to the size we leave it with.

**Comment by umlaeute** [comment]
shouldn't that apply to all iemguis? (not just nbx).

for the nbx, we probably want to adjust the default `height` as well.

**Comment by porres** [comment]
> shouldn't that apply to all iemguis? 

probably, I have to confess I was thinking about that too

**Comment by porres** [comment]
Ok, closing this as we now have a new discussion at  https://github.com/pure-data/pure-data/issues/1638
