### ISSUE TITLE
symbol box backspace doesn't work well for non ASCII characters

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1101]
Some characters take two bytes or more and Pd handles them nicely in comments, messages and object boxes. But in atom boxes if you try to delete one of these "special" characters you remove one of the bytes and not the character itself. Hence, trying to delete "ç" turns it into "Ã".

The same mechanism used in the other boxes should be used.

**Comment by porres** [comment]
> The same mechanism used in the other boxes should be used.

And what's that mechanism? 

It's the "u8_dec" function in https://github.com/pure-data/pure-data/blob/a92ad87194a3a82998acc7af7f0d4cb3b4460d57/src/g_rtext.c#L530 I believe

**Comment by danomatika** [comment]
Actually, sending characters when editing a float or symbol atom *does not* go through that code section, which is probably why there is an issue.

**Comment by danomatika** [comment]
This should be an easy fix. Looking into it now.

**Comment by danomatika** [comment]
@porres Here's a build with this fix and the key handling updates: http://docs.danomatika.com/pdbuilds/0.51/Pd-0.51-3-keyfix2.zip

**Comment by porres** [comment]
Works perfectly, it fixes this and https://github.com/pure-data/pure-data/issues/1138 !

thanks!

**Comment by porres** [comment]
But I'm testing 0.51-3-test-3 and this is not working there yet

**Comment by danomatika** [comment]
This fix is not in test3. Bug @millerpuckette.

**Comment by porres** [comment]
Oh, I see the fix is in  #1195 not merged yet. Please @millerpuckette merge this one and I think 0.51-3 s ready to go ;)

**Comment by umlaeute** [comment]
the fix is included in #1178 ("stable development branch") which I would prefer to get merged ;-)
