### ISSUE TITLE
Mac Travis CI is broken

### ISSUE THREAD

**Issue by mcclure** [pure-data/pure-data#1102]
If you look at any of the last few pull requests, for example #1082 or #1096, and look under the Travis CI test build, the Macintosh build fails 100% with the message

```
Error: libtool 2.4.6_1 is already installed
To upgrade to 2.4.6_2, run `brew upgrade libtool`.
==> `brew cleanup` has not been run in 30 days, running now...
```

[Console spam follows]

[An example](https://travis-ci.org/github/pure-data/pure-data/jobs/705588080).

**Comment by umlaeute** [comment]
PRs welcome.
also, could you elaborate on what is actually broken (obviously the build, but where is the bug?)

**Comment by umlaeute** [comment]
well, i probably have it fixed (in `devel`, pending merge into `master`)
