### ISSUE TITLE
Window resize crash

### ISSUE THREAD

**Issue by Totly-w** [pure-data/pure-data#1104]
Hello, I hope someone can help. I keep getting a crash when I try to resize any window in this file below including help windows. If I resize slowly smaller its ok but very laggy, as you resize larger the window goes black and unresponsive. Maybe a buffer issue? I'm using OSX 10.13.6. It also crashes on Win10.
It seems to be a problem that a file can 'catch' if you paste from a broken file. Thanks.

[_main.pd.zip](https://github.com/pure-data/pure-data/files/4995827/_main.pd.zip)

**Comment by porres** [comment]
the gui seems to be unresponsive because you're using too many bangs being triggered at a very high rate

**Comment by Totly-w** [comment]
Thanks so much that's better now. (I am a bit new!)

**Comment by umlaeute** [comment]
hmm, i don't get any problems, and can resize the window just fine. (that's on Debian GNU/Linux sid, with Xfce4/X11).

btw you should have a look into `[samphold~]` and build your entire patch in the signal-domain. it should be both faster and more precise (in your current patch you are triggering the `[snapshot~]` every 1ms, but it will only output data every 64samples (1.45ms)).

anyhow, even if the patch is suboptimal, it should never crash Pd.

**Comment by Totly-w** [comment]
Thanks very much Umlaeute I will have a look at [samphold~].

**Comment by Totly-w** [comment]
[samphold~] works great and 'suboptimal' is my middle name so all is well. thanks again both
