### ISSUE TITLE
Which header files should be shipped with Pd app?

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#1109]
Apparently, Pd doesn't ship the same set of Pd header files on all systems (see https://github.com/pure-data/pure-data/issues/1108). 

Generally, I think it should only ship Pd header files which contain `EXTERN` functions, which would rule out files like `s_utf8.h` and `s_net.h`.

**Comment by umlaeute** [comment]
Closing as completed (all apps now use `make install` to determine the files to be shipped, which gives a consistent set of files)
- https://github.com/pure-data/pure-data/issues/1992
