### ISSUE TITLE
get rid of inlet~s explicit "fwd" mode

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1114]
I think having to pass "fwd" as an argument to `[inlet~]` to get msg-forwarding is just confusing.

iirc (and I'm currently afk so I cannot check) the non-forwarding `[inlet~]` is a strict subset (from an API and functionality POV) of the forwarding `[inlet~]`.

as such, having to enable it explicitly is just tedious, cumbersome and unnecessary.

BTW, I haven't checked, but how does this play along with the resampling args?

**Comment by Spacechild1** [comment]
The only advantage I can think of is that you get an error message if you attempt to send a message to a signal inlet which doesn't have forwarding enabled (well, not in the current implementation, but with my PR https://github.com/pure-data/pure-data/pull/1112 :-)

Usually, you would only enable forwarding for the main signal inlet of an abstraction (to be consistent with externals).

**Comment by sebshader** [comment]
right now seems like you can't select a resampling method if you use "fwd" (and it just defaults to sample & hold) since only 1 symbol arg is passed

**Comment by porres** [comment]
> right now seems like you can't select a upsampling method if you use "fwd" (and it just defaults to sample & hold) since only 1 symbol is passed to the constructor

That's bad, and the workaround is to have another subpatch inside the subpatch...

I usually think 'fwd' is like a flag: "-fwd", which would make more sense to me. But as someone who requested this, I also thought it could have a separate outlet by default.
