### ISSUE TITLE
0.51-test1 issues (gray background and more)

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1118]
I see a new test release is out. I haven't received any email announcing it yet, but I already tested it and have some issues.

I see a grayish background (macOS mojave), which seems like an unintended change (aka bug).

For the sample rate buttons, it feels more intuitive to me that it starts with 44.1k and then goes higher to 48k and 96k, now maybe also add 88.2 and 192k? Those are also pretty common. Then it'd be better to have "Use Callbacks" and "block size" in a new level below or rearrange things differently.

Now, I see some changes/fixes were made to inlet/inlet~, perhaps we could also take care of this bug https://github.com/pure-data/pure-data/issues/1111

As for the release notes, I pointed a couple of issues here: https://github.com/pure-data/pure-data/commit/740212e66012d35ee14eb0fc3fb9a81841025be7#commitcomment-41393798

**Comment by umlaeute** [comment]
there are 4 unrelated topics in this post (e.g. the greyish background is clearly a macOS-only thing, whereas the rest affects all platforms), it's probably better to split them into 4 separate issues.
(alternatively, just write a single mail to the mailinglist  ;-))

**Comment by porres** [comment]
> (alternatively, just write a single mail to the mailinglist ;-))

I was waiting for @millerpuckette 's announce email to the list, but I guess I could do it before that :)

**Comment by Spacechild1** [comment]
> For the sample rate buttons, it feels more intuitive to me that it starts with 44.1k and then goes higher to 48k and 96k, now maybe also add 88.2 and 192k? Those are also pretty common.

I think the samplerates should really be a dropdown list... It takes less space and is more flexible (you can easily add/remove samplerates without having to change the layout).

**Comment by danomatika** [comment]
@umlaeute Didn't you have a commit somewhere which sets the explicit canvas background color to white? I somehow remember seeing it, maybe in the running "dev" branch. I think that is all that's needed, along with disabling dark mode to fix the macOS display issues.

**Comment by umlaeute** [comment]
that was just a quick hint on the mailinglist: https://lists.puredata.info/pipermail/pd-list/2020-07/127804.html
