### ISSUE TITLE
request: check for Pd updates

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1123]
A user on facebook mentioned how he'd think it'd be useful if Pd could check for existing updates.

How hard would it be?

**Comment by pierreguillot** [comment]
My 2 cents: The GitHub API can be used to get all the tags from this repository and if a tag number is higher to the Pd version, a popup window suggests to access the download page of Miller's website. This can be done manually and/or automatically at the startup of the application. And an option can be used to enable or disable the beta versions by checking if the tag name contains "test" in it.

**Comment by umlaeute** [comment]
urgh.
software that phones home without the user's explicit consent should be strictly prohibited in 2020.
software that calls unrelated corporate data kraken without the explicit consent of the user just because they offer a convenient service should be penalized.

apart from the privacy issues, it's just plain annoying if you get a popup at every startup.

its of course better if the user initiates a check.
but then, we could just add a menu entry that opens up miller's page ( or puredata.info, though the former is canonical), and the user can see for themselves...

**Comment by pierreguillot** [comment]
Of course this can be disable by default and the user can enable the it if he wants and the application should warn the user about the web request (perhaps there is something better than GitHub API?). In fact, it can be an add-on and not the main application and perhaps it can be done with a patch. There is no more than 2 or 3 releases per year so except if you only open Pd every 4 months, you should not get a warning at every startup ;)

**Comment by pierreguillot** [comment]
Of course this can be disable by default and the user can enable the it if he wants and the application should warn the user about the web request (perhaps there is something better than GitHub API?). In fact, it can be an add-on and not the main application and perhaps it can be done with a patch. There is no more than 2 or 3 releases per year so except if you only open Pd every 4 months, you should not get a warning at every startup ;)

**Comment by pierreguillot** [comment]
Of course this can be disable by default and the user can enable the it if he wants and the application should warn the user about the web request (perhaps there is something better than GitHub API?). In fact, it can be an add-on and not the main application and perhaps it can be done with a patch. There is no more than 2 or 3 releases per year so except if you only open Pd every 4 months, you should not get a warning at every startup ;)

**Comment by pierreguillot** [comment]
Of course this can be disable by default and the user can enable the it if he wants and the application should warn the user about the web request (perhaps there is something better than GitHub API?). In fact, it can be an add-on and not the main application and perhaps it can be done with a patch. There is no more than 2 or 3 releases per year so except if you only open Pd every 4 months, you should not get a warning at every startup ;)

**Comment by pierreguillot** [comment]
Of course this can be disable by default and the user can enable the it if he wants and the application should warn the user about the web request (perhaps there is something better than GitHub API?). In fact, it can be an add-on and not the main application and perhaps it can be done with a patch. There is no more than 2 or 3 releases per year so except if you only open Pd every 4 months, you should not get a warning at every startup ;)

**Comment by Spacechild1** [comment]
> but then, we could just add a menu entry that opens up miller's page ( or puredata.info, though the former is canonical), and the user can see for themselves...

+1

**Comment by porres** [comment]
> but then, we could just add a menu entry that opens up miller's page ( or puredata.info, though the former is canonical)

and puredata.info is usually outdated - by the way, there it is again still at 0.50-2 :)

**Comment by umlaeute** [comment]
> and puredata.info is usually outdated

i don't think this is generally true (that is: i think the time where it is not outdated is longer than the time where it is outdated).

and of course, *you* could always do something yourself if you notice that it is outdated.
