### ISSUE TITLE
request: resizing GUIs by mouse

### ISSUE THREAD

**Issue by H-MLim** [pure-data/pure-data#1130]
personally thinking, I just found much convenience a function of resizing GUIs (bang, toggle, etc.) by mouse without going property nor sending message on Purr-data (for example when you locate the corner of bang, the two headed arrow is appeared and can resizable). would it be also reflected in vanilla in the future?

**Comment by porres** [comment]
I already have the same request (that also includes atom boxes) here: https://github.com/pure-data/pure-data/issues/1010

**Comment by umlaeute** [comment]
closing this as it appears to be a duplicate of #1010
