### ISSUE TITLE
Rogue cord

### ISSUE THREAD

**Issue by paulspignon** [pure-data/pure-data#1132]
file:///home/paul/Dropbox/pd_stuff/Screenshot_haywire.png 
I have no idea how to make this screen dump image visible to the reader.

Put two number boxes, # 1, # 2 and  a multiplier 
Connect # 1 to input 0 of the multiplier
Connect # 2 to input 1 of the multiplier. 
Thereupon a third cord appears at the output of # 2, and cannot be removed. It follows the cursor everywhere, even in the menu bar.
It can only be removed by saving, closing and reopening the file. 
I have reproduced this behaviour a number of times, always the same.
[Note also that Ctrl+W does not close the file, it asks whether to save changes, but then does not close the file. Ctrl+W has to be done a second time.]
I am running pd-l2ork version 20200802. 
`uname -a 
Linux velikiHP 5.6.0-0.bpo.2-amd64 #1 SMP Debian 5.6.14-2~bpo10+1 (2020-06-09) x86_64 GNU/Linux`
KDE desktop

Paul Pignon

**Comment by Spacechild1** [comment]
Does this also happen with Pd vanilla 0.51.1? This is only the issue tracker for Pd vanilla. Pd l2ork (aka Purr Data) is a different program, with a different issue tracker (https://git.purrdata.net/jwilkes/purr-data/-/issues).

**Comment by paulspignon** [comment]
> Does this also happen with Pd vanilla 0.51.1? This is only the issue tracker for Pd vanilla. Pd l2ork (aka Purr Data) is a different program, with a different issue tracker (https://git.purrdata.net/jwilkes/purr-data/-/issues).

My bad, didn't realize this was for vanilla only (no longer have that, is it even maintained now?).

**Comment by umlaeute** [comment]
closing this as not-for-us.

**Comment by porres** [comment]
"is it even maintained now?"

@paulspignon , somehow you seem to confuse Pd-Extended, which is not maintained, with Vanilla.

Vanilla is something else and is and always has been the main and true and only Pd... and has never been on any hiatus - all the rest (like 'extended') are forks, and many have died on the way. Pd-l2ork is a fork from 'extended', and, unfortunately (at least to me), does not do a good job keeping up with the developments from vanilla, the main project (aka upstream).

**Comment by paulspignon** [comment]
It's true I didn't know Vanilla was still around, thanks for the heads-up. Just installed it to compare. Have to say it looks much uglier on my Debian 10 with KDE. But more to the point, I'm in the middle of trying to compose a piece (that's what this is all for, right?) and have a number of patches I've built in purrdata and lately l2-ork. I get, for example
ftos
... couldn't create
 glue
... couldn't create
 list-l2s
... couldn't create
 mindwarp~
... couldn't create
 glue
... couldn't create
 atoi
... couldn't create
sigmund~ version 0.07
bonk version 1.5
pd~ version 0.3
 freeverb~
... couldn't create
 dwt~ 1
... couldn't create
 freeverb~
... couldn't create
 grid grid1 695 0 1000 173 1 10000 1 1 1 30 20 81 720
... couldn't create

and some patches (where I use the wavelet transform dwt~) just open blank in Vanilla. 
So to get on with the real work I must stay with pd-l2ork now. 
Is there some kind of animosity between Vanilla and "offshoot pd" users/developers?

**Comment by Spacechild1** [comment]
With Pd vanilla you have to install externals yourself. It includes a package manager called "Deken" (->Help -> "find externals") which makes this quite  straightforward.

> Is there some kind of animosity between Vanilla and "offshoot pd" users/developers?

not really.

> have a number of patches I've built in purrdata and lately l2-ork

If you're happy with PurrData, then stick with it. One thing to consider is that Pd vanilla has been around for 25 years now and will continue to do so, while forks like "Pd extended" and "PurrData" come and go.

**Comment by paulspignon** [comment]
Yes, I went to "Find externals" right away, but didn't realize that no externals had been loaded by the apt installer. For now I need to crack on with the music, so no time to delve into what might or might no provide the missing modules. Thanks for the info.

**Comment by umlaeute** [comment]
btw, you can just do:

~~~
apt-get install multimedia-puredata
~~~

which will install practically all Pd-related packages (aka: externals) that are available natively in your distribution.

**Comment by paulspignon** [comment]
Thanks. Did that, but some lacunae remain:
mindwarp~
... couldn't create
 glue
... couldn't create
 atoi
... couldn't create
...
 dwt~ 1
... couldn't create

Have to crack on now, so back to pd-l2ork.

**Comment by porres** [comment]
> It's true I didn't know Vanilla was still around, thanks for the heads-up. Just installed it to compare. Have to say it looks much uglier on my Debian 10 with KDE.

yeah, I use mac and, for some reason, it looks very very nice, nicer than purr if you ask me (I like it cleaner).

> Is there some kind of animosity between Vanilla and "offshoot pd" users/developers?

what's "offshoot pd" users/developers?

I dont know what that is, but I'll say no as well :) 

And +1 for "if you're happy with PurrData, then stick with it". It does offer something different, like better looks and the convenience of having many preinstalled externals. I just think it is important to know that Pd Vanilla "still exists", and the differences between them.  

- mindwarp~ is from fftease, but I dont think the aithor put it in "find externals". But see http://disis.music.vt.edu/eric/main/fftease/ 

- "glue" and "atoi" is from 'zexy', developed by @umlaeute , it should be available for vanilla and you might have it already, you're probably just not loading the library right (try [declare -lib zexy])

- dwt~ is from "creb" and is available in "find externals". 

- list-l2s is from "list-abs" also available in "find externals". 

Even though Purr already offers them for convenience, it's important to note that virtually all externals and objects will run in vanilla, and in fact you get more (and more up to date) externals if you use vanilla.
