### ISSUE TITLE
weird issue with writesf~ & 'open' message in subpacth

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1135]
This gotta be the weirdest issue/bug I'll ever find in pd.

Check attached patch,  see also screenshot.

<img width="648" alt="Screen Shot 2020-08-25 at 12 10 22" src="https://user-images.githubusercontent.com/5360142/91192158-003dfa00-e6cc-11ea-8912-be09d2b6f67e.png">

the open message doesn't work if it's inside a subpatch that goes to a [writesf~] - I get a "writesf: start requested with no prior 'open'" error. The message needs to be directly connected to the [writesf~] (it also works if you have a [receive] connected to [writesf~].

I'm on Pd 0.51-1, macOS Mojave

[test-weirdness.pd.zip](https://github.com/pure-data/pure-data/files/5124599/test-weirdness.pd.zip)

**Comment by Spacechild1** [comment]
I can confirm this and I'm baffled as well. I checked the output of the subpatch and the messages come out fine. A similar thing happens with `[readsf~]`. Note that the objects actually work as expected, i.e. the soundfile is written/read correctly.

**Comment by umlaeute** [comment]
that's a variant of the fan-out problem.
use `[trigger]`.

:-)

**Comment by umlaeute** [comment]
that's a simple patch problem.

the subpatch is connected twice to the `[writesf~]` object, as can be seen by just triggerizing the entire patch or in the source code:

~~~
#X msg 222 60 \; pd dsp 1;
#X connect 1 0 0 0;
#X connect 1 0 0 0;
#X connect 2 0 0 0;
~~~

connecting a `[print]` to the subpatch doesn't help much, as you are just adding a third connection.
replacing the `[writesf~]` with `[print]` shows the wrong messages.

Pd mostly does a very good job in preventing the user to create such a mess.
the only way to make a double-connection that i can think of is by using dynamic patching (where i think it should be allowed: if people use dynamic patching they should be prepared to launch missiles).

the only other way i can think of is by editing the patch file in a text-editor (which is just a convenient form of (not-so-)dynamic patching.

**Comment by porres** [comment]
you're right, this was a product of dynamic patching, thanks!
