### ISSUE TITLE
[PD] Pd 0.48.0.test1 fails to create all the gop objects of an existing patch

### ISSUE THREAD

**Issue by BalwynVic** [pure-data/pure-data#114]
I uninstalled 0.47.1 and installed 0.48.0.test1 and tried to open a file of
seven placed abstractions but only two appear as the expected gop objects.
(the dark green canvas was moved manually). Screenshot 1
Uninstalled 0.48 and reinstalled 0.47.1 and the file opens correctly. Screenshot 2
Forgot to mention system is win 10 when I sent this to Pd-lists
Cheers
David Adams

![screenshot1 pd 0 48 0test1](https://user-images.githubusercontent.com/19323111/28370663-308b941c-6cde-11e7-853b-1de03f79f94f.png)
![screenshot2 pd 0 47 1](https://user-images.githubusercontent.com/19323111/28370662-308b7fae-6cde-11e7-8c68-560076d8cfa4.png)

**Comment by umlaeute** [comment]
is this still a problem with Pd-0.49? if so, can you share the `named-knob` abstraction?

**Comment by Spacechild1** [comment]
@BalwynVic is this still a problem? Otherwise I would go ahead and close this issue.

**Comment by Spacechild1** [comment]
Closing this after almost three years of inactivity and the OP not responding
