### ISSUE TITLE
request: Dynamic Patching

### ISSUE THREAD

**Issue by AydinHumphries** [pure-data/pure-data#1147]
hi,

I'm not really sure how to phrase these concerns, if it's alright to post several - albeit related - issues together or if these are duplicates or not since a lot of things get posted here. search results don't seem to return anything but I thought that of the last thing I posted also. I've used dynamic patching in several of my patches over the last year, found it both a very cool and useful - albeit, unintended - feature and I'm well aware the limitations with it are not unheard of. that said, I really do think as Pd advances with new updates it's highly advantageous to seriously consider the uses of dynamic patching as they present more live performance musical opportunities as well. 

yes, this is a long post but it lists a lot of related things I think it would be useful to address on Pd and I feel like I'd be doing a disservice to the relative urgency of this issue by breaking it into smaller individual issues not understood in context of the larger thing and could be simply dismissed as duplicates, minor concerns or something I could work a way around them. not that I'm saying anyone would do that here, I just think it's important to at least consider a holistic approach. I was also rushed through this post so I apologise if it is not entirely thorough. I can come back at a later stage though to provide more information, if requested.

for instance if I have a subpatch open with a multi-oscillator interface it's highly useful to click a bang that clears the page and replaces what's on it with say an acid-filter or a drumkit interface instead (I'm sure everyone here knows but graph abstractions let you do that without losing data). I have a few issues with the way dynamic patching currently works I noted from a facebook patch some years ago and somebody just said - albeit correctly - that Pd is not really intended for dynamic patching anyway. but again, I think we should seriously consider fixing it rather than moving it from future Pd versions.

firstly, in this first patch I was working on, I was able to create objects on the main page -"Built_On_Shifting_Sands.pd" until I started getting an error message place saying "location does not exist" or "object does not exist" or some such and I had to change my patch so I could send it to a sub-patch via the command "pd-Built_On_Shifting_Sands" instead. minor inconvenience, sure but an inconsistency with the way the patch works that should be considered all the same. if you're having a hard time figuring out what I mean, here is a screenshot with the code after I had to correct it:

![image](https://user-images.githubusercontent.com/48067862/93894314-7ee78080-fce6-11ea-934b-9c290aff6164.png)

before that though, I was able to write ";Built_On_Shifting_Sands.pd" just fine and not have to send the objects over to a subpatch but have them on the main page instead. so whether that is a bug or not, I have no idea what it is but sometimes it will work, sometimes it won't.

in this same patch, black dots would appear when I was removing objects on screen and not just that but none of the coding I was trying to use like "edit mode 0" I think it was to stop blue rectangles appearing on the page from my mouse - none of that would work. here is the screenshot with the black dots after clearing the screen through dynamic patching:

![image](https://user-images.githubusercontent.com/48067862/93895615-ec47e100-fce7-11ea-95b5-a8926bdfd0d1.png)

and here, the coding I used:

![image](https://user-images.githubusercontent.com/48067862/93895663-fbc72a00-fce7-11ea-91da-3e0066fc29f2.png)

around the time, I was investigating issues I was experiencing with dynamic patching, I wanted to know whether about an error message I kept getting in the Built_On_Shifting_Sands as well as see if there was something I could do about these black dots on page - maybe by changing the mouse parameters since I don't really know what the last two 0s after the first two co-ordinates are for. 

so, I created a few test patches. but I was hindered by the fact I was unable to clear these objects in one of my test patches that I was able to create very simply in Built_On_Shifting_Sands - another inconsistency with the way dynamic patching seems to work sometimes on Pd. below we have both the error message and the object that would not clear:

![image](https://user-images.githubusercontent.com/48067862/93896627-0afaa780-fce9-11ea-9b13-cf909d475134.png)

![image](https://user-images.githubusercontent.com/48067862/93896294-aa6b6a80-fce8-11ea-9910-ee7c1be5725c.png)

and to try and prove pd can be inconsistent in removing these objects or not, here is an images where it worked!

![image](https://user-images.githubusercontent.com/48067862/93896734-3087b100-fce9-11ea-865a-4a1fa365c654.png)

there's numerous other difficulties I was experiencing at the time but it's hard to remember all the little things or know that they were bugs and not user errors let alone prove this was happening. maybe updates in Pd have already fixed some of these things though, I really don't know. if this conversation blossoms and the thread stays open though, I will try to see if I can find more stuff related to dynamic patching issues. again, I can't stress enough though that is a beautiful and useful feature to be able to create objects on screen like that, not just an incidental bug that came about accidentally. I really think it should be worked to be improved - if at all possible - and not just removed from future versions of Pd.

something that may not have been an issue related to dynamic patching - but more to the way I messed up coding for receiving MIDI messages - was the way that musical loops I'd created seemed to be glitching every time I created new objects on screen through dynamic patching. if that is just because of the amount of processing, CPU or whichever it is that GUI takes up when you create new objects, I suppose that's not something easy to fix. but could maybe be considered at least. I've tried to open the cloud for Built_On_Shifting_Sands but mega.nz seems to be under maintenance right now. the link to my full portfolio is here: https://mega.nz/folder/XsRhBIRZ#UVTdj6IhhKdI9af7yjzTFg

that contains all my composition works from recent years and not just Pure Data stuff. I was going to link directly to the 2020 appendix subfolder where the full patch is located but right now I just can't access the link, as stated. it could take an hour to process all the patches and instructions for working the patch in that folder though so I am not trying to send anyone on a wild goose chase. just saying the information is there if you want to scrutinise more closely the issues I've described with that patch. if you want.

anyway, I've been having yet more issues with dynamic patching in my most recent patch. yeah, I did initially think "well maybe I should try and find a way without dynamic patching" but actually the way this patch works it's kind of difficult to find another solution to what I want. I have right now a pattern generator interface for acid-filter and another for multi-oscillator. there will be more but I have not built these yet. I figured if I just turn those into graph-on-parents then make the abstractions for them appear on page through dynamic patching, I could limit the amount of coding required and potential problems that come with that too - do it like how it is on automatonism, essentially. but it's not as straight-forward as that.

firstly here is the code I use to create different instances of abstractions on my new patch:

![image](https://user-images.githubusercontent.com/48067862/93898778-81000e00-fceb-11ea-92e6-1484a07e8838.png)

secondly, here are the dynamic patching related concerns I am currently experience with this patch:

1. [;pd-interface clear( ---> clears the subpatch, [pd interface] when used during performance but with [loadbang] wipes the entire patch "interface.pd" when you load the patch. that's an issue because I want the subpatches to be clear when I first open the patch but everything else I want to exist, obviously. sure I can get around that by renaming my subpatches [pd-multiosc] and [pd-af] - as I have done since I first noted this problem. I just think you should not necessarily have to do that.

2. [else/display] appears fine when [multi-osc] abstraction is already loaded (not cleared) on opening interface.pd but when it has been cleared before opening interface.pd, creating a new instance - [multi-osc 1] - results in [else/display] with darkened box: it's not possible for it to show floats or symbols. here's an example of what it looks like when I have saved all my instances and reloaded the patch:

![image](https://user-images.githubusercontent.com/48067862/93899912-b3f6d180-fcec-11ea-9012-a6ee44bee09b.png)

here's what it looks like when I create a new instance without saving and reloading the patch though:

![image](https://user-images.githubusercontent.com/48067862/93900186-ff10e480-fcec-11ea-9c09-a2e168fdde88.png)

of course, new instances of [multi-osc] abstractions appear fine when creating them in pd according - issue void: abstractions appear at "wrong" co-ordinates on reloading the patch because the counters have been reset but this has to happen because of issue number 2. this could also be an issue with the else library, rather than vanilla. I am just mentioning this in case. also I will need to find a way to clear individual objects at a later stage in the project, preferably without the black dots on screen.

github link to the patch I've recently been working on (interface.pd is the one you want to run): https://github.com/AydinHumphries/Interface_for_AcidFilter_and_MultiOsc 

thanks and also, really hope this information is useful to the developers.

**Comment by umlaeute** [comment]
please split this into actionable chunks and problems.

if you want to start a discussion about the larger vision, please use the pd-list (or some forum) rather than this issue-tracker (which is ill suited for replying to parts of a message).

**Comment by AydinHumphries** [comment]
would you like me to post all the individual topics?

**Comment by umlaeute** [comment]
> would you like me to post all the individual topics -- altogether, or one at a time?

i don't understand the question.
what does "altogether" mean (as opposed to what you already did)?

**Comment by umlaeute** [comment]
i'm going to close this ticket, as i don't think it's actionable in it's present form.

this shouldn't hinder anybody from posting further information (if the need arises), or re-open the issue if it ever becomes actionable.

**Comment by AydinHumphries** [comment]
> > would you like me to post all the individual topics -- altogether, or one at a time?
> 
> i don't understand the question.
> what does "altogether" mean (as opposed to what you already did)?

I meant, would you like me to post all of the topics right away, or do "part 1" (I have renamed the topic) - wait until correspondence has finished on that subject, then do part 2, etc., etc.

**Comment by umlaeute** [comment]
if the issues are orthogonal (and you should try making them orthogonal), then please post them all (separately, of course).
the issue tracker is a non-linear medium, there's no such things as a string of correspondences (aka: issues are tackled when/if somebody has time/is in the mood for doing them; this is also the reason why it is so important to get to the point soon: i need to know whether this issue actually interests me or not, before i spend time reading a lengthy article; and i need to be able to get back to the issue easily half a year later, when i finally find the time to work on it)

**Comment by AydinHumphries** [comment]
> if the issues are orthogonal (and you should try making them orthogonal), then please post them all right away (separately, of course).

I know you said post them all right away but I am going to look through the error with mouse dots more closely and try to see if there is a way to express it more succinctly (right now it is required for the developer to look through the code for Shifting Sands). I am about to post the consistency error check though.

**Comment by AydinHumphries** [comment]
> if the issues are orthogonal (and you should try making them orthogonal), then please post them all right away (separately, of course).
> 
> the issue tracker is a non-linear medium, there's no such things as a string of correspondences (aka: issues are tackled when/if somebody has time/is in the mood for doing them; this is also the reason why it is so important to get to the point soon: i need to know whether this issue actually interests me or not, before i spend time reading a lengthy article; and i need to be able to get back to the issue easily half a year later, when i finally find the time to work on it)

oh, and the final issue with else/display. I am not sure if that is a problem with dynamic patching/vanilla or if the issue is with else library. do you think I should post that anyway?

**Comment by porres** [comment]
it's a display issue, but i dont get it https://github.com/porres/pd-else/issues

**Comment by AydinHumphries** [comment]
> it's a [display] issue, but i dont get it (report it at: https://github.com/porres/pd-else/issues)

ok
