### ISSUE TITLE
request: error message with dynamic patching - "consistency check failed editor"

### ISSUE THREAD

**Issue by AydinHumphries** [pure-data/pure-data#1151]
**description:**

sometimes you are able to clear objects such as below:

![image](https://user-images.githubusercontent.com/48067862/94144861-9733d880-fe69-11ea-820f-2626c122e4ac.png)

sometimes you are not:

![image](https://user-images.githubusercontent.com/48067862/94144903-a6b32180-fe69-11ea-93cb-ac526c27eb3e.png)

**to recreate:** 

simply type the same code as I used in the screenshots above or access these patches from github to test yourself:

https://github.com/AydinHumphries/test

keep in mind, I don't know what it is that causes the code to work sometimes and other times not to. so you may be able to find it works now but doesn't work in say, a month. or the reverse. I'm not sure how else to prove this issue exists than to post the above screenshots.

**more details:**

the code for this needs to work without "consistency check failed editor" in order to test the issue with black dots appearing from the mouse locations when removing objects in Pd (see more context). in a patch I was working on, I was able to remove objects but also had "consistency check failed editor" so sometimes it is an error code that appears even when your patch behaves as intended. I am open to suggestions for solutions from externals library, I just think some users might not - and I might not - think it is worth downloading the bulk of a new library if there is only one benefit from it (to fix that particular issue).

**OS:**

windows 10, lenovo laptop

**urgency:**

medium - if a patch fails because of this consistency check failed editor thing, you could have to rework the whole thing. or if no solution on vanilla exists try to recreate the patch and just hope you don't run into this issue again.

**context:**
an individual issue from the longer thread about inconsistencies found with dynamic patching and the importance of addressing them: #1147

**Comment by umlaeute** [comment]
for the record, the patch is this:

~~~
#N canvas 820 215 450 300 12;
#N canvas 0 50 450 300 subpatch_a 0;
#X restore 106 85 pd subpatch_a;
#X msg 13 177 \; pd-subpatch_a editmode 1 \, mouse 10 10 0 0 \, cut
\, editmode 0 \;;
#X msg 15 114 \; pd-subpatch_a obj 10 10 bng \;;
~~~

**Comment by umlaeute** [comment]
this again seems to come from a wrong use of dynamic patching.

sending messages like `mouse` to a patch, is effectively hijacking a *private* API (for communication between Pd-core and Pd-GUI).
if you hijack this API, you have to play by its rules.
one of these rules is, that you must not do mouse-interactions on a closed subpatch.

so either follow the rules (make the canvas visible before sending "interactive" commands) or use another means of dynamic patching (`iemguts`, `dyn~`,...)
