### ISSUE TITLE
keyboard shortcuts doesn't works when CAPS LOCK ON / windows

### ISSUE THREAD

**Issue by jlquispec** [pure-data/pure-data#1152]
keyboard shortcuts doesn't works when CAPS LOCK is ON

Windows 10

**Comment by matthewbrandi** [comment]
On 25/09/2020 00:46, Jorge Quispe wrote:> keyboard shortcuts doesn't works when CAPS
LOCK is ON> Windows 10
Dear Jorge

What exactly are you seeing?

Over here on Linux & pd 0.51.2, it seems to be the case that when the caps lock is
on, Ctl+ keyboard commands don’t work (i.e. one doesn’t get the caps lock off
behaviour) but that Shift+Ctl+ keyboard commands do work (in the same way as with
caps lock off).

For example, with caps lock on:

	Ctl+s 		doesn’t save
	Shift+Ctl+s	does save as

	Ctl+n		doesn’t open a new patch window
	Shift+Ctl+n	does “put” a number box object

I cannot comment on whether this is expected/intended behaviour, but I cannot at the
drop of a hat think of a rationale for it.

Best

m

-- 
matthew brandi

**Comment by Spacechild1** [comment]
> For example, with caps lock on:
>
>	Ctl+s 		doesn’t save
>	Shift+Ctl+s	does save as
>
>	Ctl+n		doesn’t open a new patch window
>	Shift+Ctl+n	does “put” a number box object

Naturally, caps lock can't modify any shortcuts already containing `Shift`, that's why `Shift+Ctl+s` continues to work.

Anyway, this is certainly a bug. Caps lock shouldn't affect keyboard shortcuts. At least it doesn't do so in the apps I've checked. Imagine you're writing text in all caps in LibreOffice and couldn't do `Ctl + C` or `Ctl + V`...

**Comment by jlquispec** [comment]
Exactly, it's not a normal behaviour. Caps lock shouldn't affect keyboard shortcuts.

For example when I try to switch between Edit mode and Execute mode (Ctrl + e) while I'm writing a comment using Capital Letters

**Comment by AydinHumphries** [comment]
hmm I was repeatedly encountering that issue and just thought it was a normal behaviour. but no, other applications let you do keyboard shortcuts with caps lock on it seems.

**Comment by umlaeute** [comment]
the fun thing is, that we actually have been through this before.

i even seem to remember deleting a patch (as in: code change) that dealt with caps-lock-shortcuts during a routine cleanup of my harddisk only a few days before :thinking:
