### ISSUE TITLE
help file request: change colour properties in GUI helpfiles to change RGBWK / CYMWK, not just RGB

### ISSUE THREAD

**Issue by AydinHumphries** [pure-data/pure-data#1153]
**basic description:**

if you access the canvas help file then go through pd properties and then pd colours, you get to change RGB settings and looks like so:

![image](https://user-images.githubusercontent.com/48067862/94284487-595ab100-ff4a-11ea-934f-47761adffe1e.png)

obviously this is a useful feature if you want to copy/paste and incrementally change the colours of your canvas, as opposed to selecting from a limited range of options through the properties option on canvas. 

you could also have RGBWK and CYMWK however, which would give you more options in regards to tints and shades rather than just being able to change hues through RGB:

![image](https://user-images.githubusercontent.com/48067862/94285435-89ef1a80-ff4b-11ea-88df-ef7f835edd3d.png)

that screenshot's from a patch I made and can be accessed from my repository, here:

https://github.com/AydinHumphries/RGB-and-CYM/

developers might want to use that patch in the next Pd version's help files and tweak it a bit. or maybe they would prefer to build from scratch, I don't know. I have linked it as an option anyway.

**demos:**
I also did a demo of the patch to show adding white/black to RGB or CYM works:

https://youtu.be/3bmBvT58v3E

and I did another demo to show you can get less saturated colours and other options too:

https://youtu.be/20pFLYchSrE

**complimentary details:**
with RGBCYMWK, it can be a lot more convenient, e.g. if you have a red that you just want to be a little darker to have RGBWK, because then all you have to do is adjust the white or black settings rather than adding a little more green and a little more black. I have coded it so the white and black is a percentage of RGB - so adjusting that obviously you could get e.g. a 40-60% blue if you wanted a medium dark blue. 

or, if you want a light pastel green, you just start with a fully saturated green (100% green, 100% white) then add 80% red and 80% blue. RGBWK seems to me an improvement on the old system (I have coded it so you start with 80% white and if you decrease white it appears to increase black and vice versa) and I have managed to get Pd to translate that into hexadecimal, at least.

as for cyan yellow and magenta, again I don't know much about colour theory but as I understand it, CYM are the subtractive primaries as compared to RGB which are the additive primaries. physicists tend to prefer RGB because those colours represent the spectrum of light whereas CYM is more for painters I believe, for reasons I'm not really sure of. either way you can get RGB from CYM and reverse too (you can get CYM from RGB). 

one advantage I did spot was that whereas RGBWK will let you get pastel red, green or blue easily, you could switch to CYMWK to get pastel cyan, yellow or magenta without changing over too rapidly. I demonstrate this in a short video I did as a demo of a patch. the patch is an upgrade on the help file "colors" accessed through the canvas help file, and then properties. the patch you can access in my github repository (here's the link again: https://github.com/AydinHumphries/RGB-and-CYM/ ).

I'm not saying developers will want to simply substitute my help file for the old one - they may want to make some changes or build from scratch entirely - for example the vsliders on my version don't move up and down very smoothly, why I don't know. but it could be helpful to look at as some sort of template.

obviously you can get these colours from canvas --> properties on Pd. but doing it that way is not as powerful as it is if you can use sliders to incrementally change your colours - hues, tints, shades, tones, etc.

as for how useful it can be, I found my own system useful this morning as I was going through my patches, changing the colours of canvas to different tints as I intend to use them for the audiovisual display on a project I'm working on.

**Comment by porres** [comment]
Checking/experimenting with colors can easily be done via properties, which offers these and more options. The message method is to dynamically change colors because of a user interaction (like turning to red when "on" or something). So you should just save your preset setting in a message to set changes. This should preferably be done now with hex notation, but there's also a PR to allow RGB values as well, and this is one of the reasons the RGB setting is in place here already in the recent update I made to the iemguis help files (and also because it was always there before). My idea is when the PR gets accepted that the color setting is more straightforward without the need to convert to hex notation.

I don't really think the help file is the place to offer dynamic changes so you can experiment/choose colors, since, again, you can do it in the properties. For me, this seems more like a nice patch/tool to convert colors that can be part of an external library (like I have else/colors as a convenient tool to set/convert colors) - but that's me, let's see what others say...

**Comment by umlaeute** [comment]
i think i basically agree with @porres.
the suggested change doesn't fix an error in the help-file nor does it document anything that hasn't been documented before.
a help-patch is hardly the place to show all possible ways to generate messages that a given object understand.

otoh, i understand the usefulness of colour-selectors on the patch-level (as opposed to the properties).

rather than changing the help-files, i would therefore suggest to just start a library of such utility objects (ideally built as vanilla abstractions).

you could also open a PR to get such abstractions included into mainline Pd (though i seriously doubt they will be picked up: colour-selection is rather a secondary task in Pd; but of course i'm happy to be proven wrong).

**Comment by AydinHumphries** [comment]
> otoh, i understand the usefulness of colour-selectors on the patch-level (as opposed to the properties).

I understand the criticisms - you can do everything that you can with CYM that you can with RGB. CYM just happens to be a popular alternative to RGB especially with painters. like I said, I don't understand all the colour theory behind it, or why some people (non-physicists) like CYM better, they just do. and being able to copy/paste RGBWK or CYMWK coding from the help files is considerably practical for quickly/effectively changing your GUI objects on patch without having to headache your way through all the coding. for instance anyone could theoretically create the CYM graph I did, but personally I found it quite tricky how to hook it up to change RGB parameters since I don't know how to do the hex spelling directly from CYM. a developer - if they had the time - could probably add this feature to the GUI help files with relative ease, I think.

as for putting this feature into an external library, it's the kind of solution that get's advocated around here and for good reason as external libraries have lots of useful features. I just don't think it is always the most practical solution to install a new externals path or library for just one advantageous feature if it could have been in the vanilla library to begin with. building a new library for just that one feature seems even more difficult / less practical.

**Comment by porres** [comment]
The philosophy of Pd Vanilla is that it must be a quite minimal package and that you should heavily rely on externals. This is why Vanilla has always suffered some kind of resistance from users and why many flavours of Pd came around, offering more stuff - the main one being Pd Extended. As we see it, you want a utility object abstraction and you can propose that to be included in Pd, but I also doubt it'll be taken (and it's not up to me or umlaeute in the end).

**Comment by AydinHumphries** [comment]
> As we see it, you want a utility object abstraction and you can propose that to be included in Pd, but I also doubt it'll be taken (and it's not up to me or umlaeute in the end).

sorry no - that wasn't clear on my part - I don't think the CYM sliders should be an object included in the vanilla library. I think it would be nice to have a graph that does what the CYM slider I linked to in the OP does (RGBWK & CYMWK) included in the helpfiles for GUI. then if a user finds that convenient, they can just copy/paste from the help files. then, if somebody wants to make an external from it, there's nothing to prevent them.

**Comment by AydinHumphries** [comment]
> I don't really think the help file is the place to offer dynamic changes so you can experiment/choose colors, since, again, you can do it in the properties.

like I said in OP though, properties don't enable you to incrementally change colours like RGB or CYM do (I might have got CYM muddled up by the way as I looked it up online and it's cyan yellow magenta _key_ apparently, not CYM white and black). these two let you make small subtle changes to the colours to get the exact hex that you think looks nice on your canvas. properties only offer limited options for colours.

**Comment by AydinHumphries** [comment]
> you could also open a PR to get such abstractions included into mainline Pd (though i seriously doubt they will be picked up: colour-selection is rather a secondary task in Pd; but of course i'm happy to be proven wrong).

well, I mean Pd has many audiovisual features. seeing canvas colour change as harmony changes could be a very useful feature for composers who can't figure out GEM (as an example). or different coloured vsliders for different instrument parameters on your interface - that's another thing that's useful for audiovisual artists.

**Comment by porres** [comment]
Vanilla has 0 tools for visuals (as n 'audiovisual') and you're citing GEM, an external library, so yeah, Pd relies on external libraries for visuals and more, and you can set iemguis colors like you saïd as it is, just not directly from CMYK, neither HSB or grayscale (which could be yet other options, and there are also more, so where to stop? That's the point)

> it's cyan yellow magenta key apparently, not CYM white and black). 

"key" is black

> these two let you make small subtle changes to the colours to get the exact hex that you think looks nice on your canvas. properties only offer limited options for colours.

Sorry, been a mac user forever and the "compose color" button in properties lets me define a color in CMYK, but I see that's not the same for windows/linux now.

<img width="901" alt="Screen Shot 2020-09-26 at 13 11 12" src="https://user-images.githubusercontent.com/5360142/94345085-e0b32d80-fff9-11ea-8d8b-ab0ee35f267e.png">

 But that gives me yet another argument, RGB is the only setting consistently available in all platforms

**Comment by umlaeute** [comment]
> building a new library for just that one feature seems even more difficult / less practical.

well, make it a bigger library then.

there are dozens of colour models (RGB, CMYK, HSV, whatever) out there. maybe some people have a need to convert between them (e.g. Gem has `[hsv2rgb]` and vice-versa).

**Comment by umlaeute** [comment]
i'm closing this, as there is no problem to be fixed.
of course, you (or somebody else) can still create a PR that *solves* this issue if you think it is important (and i promise i will not close the PR, leaving that decision to the powers-to-be)

**Comment by porres** [comment]
> Gem has [hsv2rgb] and vice-versa

And I just added input for gray scale, CMYK, HSL and HSV in [else/colors]

**Comment by AydinHumphries** [comment]
> But that gives me yet another argument, RGB is the only setting consistently available in all platforms

I don't understand this argument: aren't CYM and HSV consistent cross-platform also? You can use RGB if you prefer or switch over to CYM and HSV. umlaeute points out there are numerous different systems, but RGB, CYM and HSV are the most common, I think.

**Comment by AydinHumphries** [comment]
> > Gem has [hsv2rgb] and vice-versa
> 
> And I just added input for gray scale, CMYK, HSL and HSV in [else/colors]

yeah, I noticed something peculiar about [else/colors] as I was testing it the other night. I will check to see if it's a user error or a legitimate glitch first though.

**Comment by AydinHumphries** [comment]
oh I had not noticed "compose colour". I suppose that makes things a bit more simpler even if you can't get CYM/HSV.
