### ISSUE TITLE
request: number atom glitch when working with illegal colour specifications

### ISSUE THREAD

**Issue by AydinHumphries** [pure-data/pure-data#1154]
**description**

I have noticed that number atoms glitch sometimes when working with hexadecimal. I have created both a demo vid and patch that shows how to recreate the error I found clearly however I should probably explain here too. when working through a logic chain with [makefilename %02x] to send hex values from 0 to 255 to [pack symbol symbol symbol] if you make the mistake of going over the 255 threshold the number atom shows some peculiar behaviour where it will no longer change value when you slide your mouse up and down but "freeze" until you click your mouse on the white screen and only then will it change. 

I should emphasise that _this happens regardless if you use a number atom connected to [makefile] or not_. additionally vsliders will no longer move up or down and I presume other GUI objects will demonstrate peculiar problems until you reload the patch.

![image](https://user-images.githubusercontent.com/48067862/94288678-96757200-ff4f-11ea-8a88-6cb82239583b.png)

obviously, it is easier to show what I mean than explain so I did a demo: 

https://youtu.be/eO2iCbxi7Y8

**steps to recreate:**

there are clear, simple steps listed in the patch how to recreate the error:

https://github.com/AydinHumphries/number-atom-glitch/

**more details:**

**OS:**

windows 10, lenovo laptop

**urgency:**

I would say this is at least a medium urgency problem because if you are working on a patch - ok, no big deal, reload the file work, set the relevant number atoms with a 255 limit, be careful not to do that again. and obviously, you should not be sending values larger than 255 when working with hexadecimal. but let's say you're in a live performance where you have an audiovisual display where some of your canvas change colours for instance. you have made a critical error and designed your patch to allow a value larger than 255 to send to one of these objects. it's no longer a question of "should have got it right the first time": your performance is ruined if you can no longer send floats to other parameters you have on your patch smoothly. you will have to restart the performance and reload the file.

**Comment by porres** [comment]
well, it seems Pd goers crazy if you try to set iemguis with hex notation over the bounds. The way to fix this is to have a bound check in the iemguis code to clip values.

As for preventing the error in your patch, limit your number boxes from 0 to 255

**Comment by umlaeute** [comment]
so this issue is not about a generic "number atom glitch when working with hexadecimal" but about "freezing  with illegal color-specifications"?
if so, please adjust the title.

**Comment by AydinHumphries** [comment]
> well, it seems Pd goers crazy if you try to set iemguis with hex notation over the bounds. The way to fix this is to have a bound check in the iemguis code to clip values.
> 
> As for preventing the error in your patch, limit your number boxes from 0 to 255

I agree, you shouldn't send a value over 255 for a patch like this one. I'm just pointing out if somebody did do something like that during some sort of performance it would cause a lot of problems and not just with the iemgui hooked up to the hex parts but any other iemgui on the patch. perhaps it's possible to code hex-related objects  so they simply don't accept values > 255. 

as for limiting number boxes, actually that was another issue on Pd I was going to post as limiting them stops you being able to slide beyond the upper or lower ranges specified but doesn't stop you from entering those numbers. you'd have to do something like

[number atom]
         |
[moses 255]
|                 |
|               255
|
[hex object]


I can't remember what it is


> so this issue is not about a generic "number atom glitch when working with hexadecimal" but about "freezing with illegal color-specifications"?

I did not use the latter title since as far as I know it could happen with other hex related objects besides the ones to do with colour. I haven't tested the error enough to know all the other places it might/might not occur.

**Comment by porres** [comment]
> limiting them stops you being able to slide beyond the upper or lower ranges specified but doesn't stop you from entering those numbers

this is intentional. Any number/slider will receive and pass values over its range, so typing them shouldn't be different

and you can use [clip 0 255] instead of moses

**Comment by AydinHumphries** [comment]
> this is intentional. Any number/slider will receive and pass values over its range, so typing them shouldn't be different
> 
> and you can use [clip 0 255] instead of moses

thanks for the suggesting [clip] - that will be useful - but I have to respectfully disagree with your first point: numbers/sliders only receive/pass on values out of range if they are connected to another GUI object. entering a value into a number box shouldn't be treated the same as connecting another number box to that one outside of it's range as the latter seems to be a lot more intentional.

**Comment by porres** [comment]
> entering a value into a number box shouldn't be treated the same as connecting another number box to that one outside of it's range as the latter seems to be a lot more intentional.

open an issue about it then, btw, nbx does clip, but I treat it as an inconsistency (aka bug), see https://github.com/pure-data/pure-data/issues/633

**Comment by AydinHumphries** [comment]
> > entering a value into a number box shouldn't be treated the same as connecting another number box to that one outside of it's range as the latter seems to be a lot more intentional.
> 
> open an issue about it then, btw, nbx does clip, but I treat it as an inconsistency (aka bug), see #633

I agree it is a good idea to open an issue about it. I would just point out what I said is also true about hex objects - there is no reason for them to receive values above 255, especially if it causes GUI objects to freeze on the patch. sending values above 255 by entering values with your keyboard using a number box that's limited to 255 or a number box hooked to that number box hardly seems intentional.

**Comment by umlaeute** [comment]
> I did not use the latter title since as far as I know it could happen with other hex related objects besides the ones to do with colour. I haven't tested the error enough to know all the other places it might/might not occur.

no it won't (i'm saying this knowing the Pd-code base for a long time; it's not your fault that you don't know that).

and even if that was true, that would be different bugs, and need be tackled separately.


in any case: i definitely do not see any bug with "number atoms when working with hexadecimal". numberboxes only deal with decimal representation. they have never heard of hexadecimal numbers, don't accept them as input and don't ever output them.
thus the title is factually wrong.

**Comment by umlaeute** [comment]
>  is also true about hex objects - there is no reason for them to receive values above 255

- there are no "hex objects" in Pd.
- hexadecimal numbers are well defined for values above 255 resp 0xFF, so why would you want to limit them?

**Comment by AydinHumphries** [comment]
> no it won't (i'm saying this knowing the Pd-code base for a long time; it's not your fault that you don't know that).

ok, I'll take your word for it

> in any case: i definitely do not see any bug with "number atoms when working with hexadecimal". numberboxes only deal with decimal representation. they have never heard of hexadecimal numbers, don't accept them as input and don't ever output them.

hexadecimal is binary converted into units as high as 15 rather than decimal which goes up to 9. after 9, it's a b c d e f. the computer only works with binary so there has to be a feature to convert to hex conveniently. colours change according to hex - so white is ffffff, black is 000000, red ff0000, green 00ff00, blue 0000ff.

I think you probably already know all this I'm just defining my terms so it's clear you know what I'm referring to or what I think I'm referring to.

> there are no "hex objects" in Pd.

I was being lazy. the way the [makefilename %02x] works in that patch to convert the three values into hex via [pack symbol symbol symbol] - that's the type of object I was referring to, or rather the logic chain itself was responsible for hex. I said "hex objects" because there might be other objects that work similarly.

**Comment by AydinHumphries** [comment]
> hexadecimal numbers are well defined for values above 255 resp 0xFF, so why would you want to limit them?

uh can't really answer that one, I had just noticed there wasn't really a reason (I could see of) why [makefilename %02x] would need to receive values above 255 for a logical colour-making chain. especially if it causes the number atom glitch but if there is some other reason for it, I must be wrong.

**Comment by Spacechild1** [comment]
> I  had just noticed there wasn't really a reason (I could see of) why [makefilename %02x] would need to receive values above 255 for a logical colour-making chain.

`[makefilename]` is basically a wrapper around `printf`. Here's a reference of the format specifiers: http://www.cplusplus.com/reference/cstdio/printf/

`%02x` does *not* clip hex numbers, it just adds leading zeros if the the number has fewer digits than the given width. Numbers that have equal or more digits are not affect, e.g. 256 will yield `100`.

You have to clip the invididual color components with `[clip 0 255]`, otherwise you end up constructing "wrong" hex numbers.

I think the actual bug is that passing out of range hex numbers to the `[color(` message causes a Tcl error. I'm closing this in favor of https://github.com/pure-data/pure-data/issues/1158

**Comment by AydinHumphries** [comment]
> Numbers that have equal or more digits are not affect, e.g. 256 will yield `100`.

sure, it would not be a problem if it just changed values > 255 but it seems to cause the number atom to glitch on the patch as well. 

some programmers might not know, or forget to clip the values in some place. in the middle of a performance that could ruin it if a value got sent > 255 to a "hex object".

**Comment by Spacechild1** [comment]
> some programmers might not know, or forget to clip the values in some place.

well, programmers should know...

Again, `%02x` doesn't say anything about the input range, only about zero padding! If you want to clip the component values, you have to use an object which is suited for this job, i.e. `[clip]`.
