### ISSUE TITLE
request - issue moving and editing objects with caps lock on or changing application windows in PD

### ISSUE THREAD

**Issue by AydinHumphries** [pure-data/pure-data#1156]
**description:**
I found this "issue" with my patch last night that has happened to me in the past where objects on the patch freeze when you click them to edit their text, won't move them and for object/comments, couldn't even see the text highlighted when you click on them in edit mode. additionally, the windows would not change very easily in Pd and I had to use windows + tab or alt + tab to change to a Pd window.

I did a demo first with a patch I was working on:

https://youtu.be/3Rf9Io7-L7g

I thought though, that patch is quite convoluted and there could be any number of things going wrong with it so I created a fresh patch to see if I could recreate the error and I could but some things worked slightly differently, like you could click on an object to highlight the text but it would not change anything when you type. the demo is here:

https://youtu.be/7eNsvUYIw1c

anyway, I nearly did not post this error report as I found out what was going wrong: I had my laptop hooked up to a keyboard I was using and the laptop keyboard itself had a wire pressing down on Caps Lock. I said I nearly did not post this error report but then I saw this issue posted on here - #1152 - about shortcuts don't work with Caps Lock on. I had thought that was a user error too until I noticed this problem does not exist on Chrome, and other applications, etc.

obviously, the user umlaeute posted a commit on that that dealt with the specific issue with shortcuts:

"use a helper-function to bind key-events regardless of CapsLock state"

I posted this thread as well as I'm not sure if the other issues mentioned in this thread have to do with shortcuts or not. it could be resolving the issue with shortcuts fixes all these others but I don't know as I'm not a programmer so I decided to mention regardless.

**steps to recreate**

just play around, editing the text in objects and comments and try moving them around the screen with caps lock on, then try changing between windows with a different patch maximised in Pd.

**OS:**

windows 10, lenovo laptop

**urgency:**

mild irritation if editing a patch - you've just got to figure out caps lock was on. if this happened in a performance and you couldn't figure out what was going wrong to quickly switch it off, caps lock might possibly interrupt the performance.

**Comment by AydinHumphries** [comment]
> **description:**
> I found this "issue" with my patch last night that has happened to me in the past where objects on the patch freeze when you click them to edit their text, won't move them and for object/comments, couldn't even see the text highlighted when you click on them in edit mode. additionally, the windows would not change very easily in Pd and I had to use windows + tab or alt + tab to change to a Pd window.
> 
> I did a demo first with a patch I was working on:
> 
> https://youtu.be/3Rf9Io7-L7g
> 
> I thought though, that patch is quite convoluted and there could be any number of things going wrong with it so I created a fresh patch to see if I could recreate the error and I could but some things worked slightly differently, like you could click on an object to highlight the text but it would not change anything when you type. the demo is here:
> 
> https://youtu.be/7eNsvUYIw1c
> 
> anyway, I nearly did not post this error report as I found out what was going wrong: I had my laptop hooked up to a keyboard I was using and the laptop keyboard itself had a wire pressing down on Caps Lock. I said I nearly did not post this error report but then I saw this issue posted on here - #1152 - about shortcuts don't work with Caps Lock on. I had thought that was a user error too until I noticed this problem does not exist on Chrome, and other applications, etc.
> 
> obviously, the user umlaute (sorry I cannot remember the spelling) posted a commit on that that dealt with the specific issue with shortcuts:
> 
> "use a helper-function to bind key-events regardless of CapsLock state"
> 
> I posted this thread as well as I'm not sure if the other issues mentioned in this thread have to do with shortcuts or not. it could be resolving the issue with shortcuts fixes all these others but I don't know as I'm not a programmer so I decided to mention regardless.
> 
> **steps to recreate**
> 
> just play around, editing the text in objects and comments and try moving them around the screen with caps lock on, then try changing between windows with a different patch maximised in Pd.
> 
> **OS:**
> 
> windows 10, lenovo laptop
> 
> **urgency:**
> 
> mild irritation if editing a patch - you've just got to figure out caps lock was on. if this happened in a performance and you couldn't figure out what was going wrong to quickly switch it off, caps lock might possibly interrupt the performance.

**Comment by umlaeute** [comment]
> just play around

hmm.
i've been "playing around, editing the text in objects and comments and try moving them around the screen" for more than 20 years now and i'm sure that occasionally the <kbd>CapsLock</kbd> was pressed, but i don't remember any such nuisance that i could relate to the <kbd>CapsLock</kbd>-key. (not that Pd never crashed nor stuck or froze; although - i'm lucky to say - never during a performance, at least not unintentionally).

it would be fabulous if the problem could be made reproducible (without watching youtube videos)


> and the laptop keyboard itself had a wire pressing down on Caps Lock

now that sounds a bit like *permanent* keypresses coming from the laptop keyboard that interfered with the user-interface - but this is something i would expect to happen in any software (so in order to prevent mild irritation while editing a patch, make sure that no monkey is typing on the same computer simultaneously  ∞ :monkey: :keyboard: :skull:)

**Comment by AydinHumphries** [comment]
> > just play around
> 
> hmm.
> i've been "playing around, editing the text in objects and comments and try moving them around the screen" for more than 20 years now and i'm sure that occasionally the CapsLock was pressed, but i don't remember any such nuisance that i could relate to the CapsLock-key. (not that Pd never crashed nor stuck or froze; although - i'm lucky to say - never during a performance, at least not unintentionally).
> 
> it would be fabulous if the problem could be made reproducible (without watching youtube videos)
> 
> > and the laptop keyboard itself had a wire pressing down on Caps Lock
> 
> now that sounds a bit like _permanent_ keypresses coming from the laptop keyboard that interfered with the user-interface - but this is something i would expect to happen in any software (so in order to prevent mild irritation while editing a patch, make sure that no monkey is typing on the same computer simultaneously ∞ 🐒 ⌨️ 💀)

maybe this is only an issue on windows 10, not mac. I can promise you I had this issue on both my windows laptops. the first laptop also had a sticky keys after I spilled coffee on it - namely the "2" (normal number, not numpad 2) and media play/pause button were constantly pressed down (not physically/literally but the computer was registering them both as pressed down). the second laptop I use now has no issues with it.

holding the caps lock button down will make it so you can't move the objects/comments on the patch with your mouse (arrow keys work after you highlighted the object though), can't edit the text on objects/comments very easily.

holding 2 down can make some things tricky too (like changing windows in Pd) - as it did on my old laptop with the coffee spill.

I am certain this happens on windows 10. as for creating a replicable patch for it, you can't really do that - it's just an empty patch then you create an object or comment on it and see what happens with caps lock on. it must be you have a mac if this issue doesn't happen on yours.

> so in order to prevent mild irritation while editing a patch, make sure that no monkey is typing on the same computer simultaneously

sure, I'm just pointing out this behaviour doesn't happen on say chrome or file explorer - you can still change windows with caps lock pressed down. it seems to be unique to Pd rather than a normal bug, even if it is at worst a minor inconvenience (though a worse irritation still if you happen to have spilled coffee on your laptop!).

**Comment by Spacechild1** [comment]
> holding the caps lock button down will make it so you can't move the objects/comments on the patch with your mouse (arrow keys work after you highlighted the object though), can't edit the text on objects/comments very easily.

I can confirm this on Windows 7. But the problem is not specific to the caps lock key, it happens with *any* key.

Steps to reproduce:
1) create a `[+ 1]` object
2) select and drag it
3) while dragging, press any key (e.g. `d`)
4) the object stops moving

@AydinHumphries A general tip: try to generalize your issues. If you find that "A" (here: the caps lock key) causes "Z" (here: can't drag objects), try to find out whether it only happens with "A" - or also with a super set "B" (here: all keys).

**Comment by AydinHumphries** [comment]
> > holding the caps lock button down will make it so you can't move the objects/comments on the patch with your mouse (arrow keys work after you highlighted the object though), can't edit the text on objects/comments very easily.
> 
> I can confirm this on Windows 7. But the problem is not specific to the caps lock key, it happens with _any_ key.
> 
> Steps to reproduce:
> 
> 1. create a `[+ 1]` object
> 2. select and drag it
> 3. while dragging, press any key (e.g. `d`)
> 4. the object stops moving
> 
> @AydinHumphries Try to generalize your issues. If you find that "A" (here: the caps lock key) causes "Z" (here: can't drag objects), try to find out whether it only happens with "A" - or also with a super set "B" (here: all keys).

sure, if I had realised straight away this happens with more than caps lock I would have posted. but a lot of these issues tend to be specific so it is hard to test all of them to find out if they are generalised, especially with my own relative inexperience using Pd. I did mention that 2 does something similar. it is not exactly the same thing though so that may be something to look into - the slightly different behaviours when holding down different keys.

**Comment by Spacechild1** [comment]
> especially with my own relative inexperience using Pd. 

No worries! Writing bug reports needs some practice and we're glad that people like you actually take their time and do it!

I have made a more concise bug report here: https://github.com/pure-data/pure-data/issues/1159
