### ISSUE TITLE
request: mouse dots appear when [loadbang] clears an empty canvas through dynamic patching

### ISSUE THREAD

**Issue by AydinHumphries** [pure-data/pure-data#1157]
**description:**
when you load a patch that has loadbang connected to a message to clear objects from the specified co-ordinates and no objects are at those co-ordinates what happens is three things

1. black dots appear at those co-ordinates
2. there is a black rectangle appears from the last co-ordinates (top right-coordinate) until the mouse location (bottom right location)
3. edit mode is turned on even if it says "editmode 0" at the end of your message

![image](https://user-images.githubusercontent.com/48067862/94368505-3fe96e80-00dc-11eb-9c67-a2a0dc687a12.png)

then, the only way to get rid of this is by turning editmode on once more, then you click and drag to make a new rectangle on screen and the black dots all disappear. if you create the same issue but with canvas objects instead of bangs, this happens:

![image](https://user-images.githubusercontent.com/48067862/94368542-6e674980-00dc-11eb-8be9-1fc3660d2f17.png)

(the left message says it's bangs but as I remember I created a bunch of canvases in those locations instead)

**extra details:**
obviously there is a simple answer to this: "don't clear objects where none exist" but there is more to this.

in an old patch of mine, Built On Shifting Sands, I had to use loadbang to clear the canvas in case there were any GUI objects from the last performance that I did not want to be there on reloading the patch for a new performance.

additionally, I had to clear objects from all possible locations on the canvas where objects might appear because for some of the messages I was sending to the patch, they had more objects being created that needed to be cleared to make room for other messages-to-canvas for dynamic patching (which would perhaps be creating less objects that would need to be cleared, causing the issue with mouse dots when I did, repeatedly clear all objects in all possible locations every time with the same patch). I had to patch to remove individual objects rather than clear the whole canvas because there were some objects on my patch I wanted to always remain.

I would argue it would be more aesthetic then to be able to clear objects without mouse dots when needing to clear objects in multiple locations that may not have objects for the two reasons above.

**steps to recreate:**
patch available for download: https://github.com/AydinHumphries/mousedots

**OS:**
windows 10, lenovo laptop

**urgency:**
a mild issue but could lower the aesthetic quality of an audiovisual performance unless the composer took the time to code many different "clear individual items on canvas" subpatches for different GUI created dynamically through different subpatches which could be a long job.

**context:**
see #1147 - it's the second issue listed there

**Comment by Spacechild1** [comment]
> patch available for download: 

Tip: you can directly upload the patch as a ZIP file with drag and drop. No need to create a GitHub repo or use some third party file sharing service.

**Comment by AydinHumphries** [comment]
> > patch available for download:
> 
> Tip: you can directly upload the patch as a ZIP file with drag and drop. No need to create a GitHub repo or use some third party file sharing service.

ok:

[mousedots.zip](https://github.com/pure-data/pure-data/files/5288621/mousedots.zip)

**Comment by umlaeute** [comment]
your method of dynamic patching (mimicking mouse-movements) is definitely unsupported.
the mouse-movements API is *reserved* for interacting with the GUI, and should not create events that are impossible to do via the GUI.

in your specific case you are creating selections with `mouse` events, but you never release the mouse (no `mouseup` event). if you send `mouseup` events, no dots appear (as the selection is properly terminated).


in any case: if you want to do dynamic patching *properly*, use the ["iemguts" library](https://git.iem.at/pd/iemguts/), or probably even the ["dyn~" library](http://puredata.info/Members/thomas/dynext)

**Comment by AydinHumphries** [comment]
> your method of dynamic patching (mimicking mouse-movements) is definitely unsupported.
> the mouse-movements API is _reserved_ for interacting with the GUI, and should not create events that are impossible to do via the GUI.
> 
> in your specific case you are creating selections with `mouse` events, but you never release the mouse (no `mouseup` event). if you send `mouseup` events, no dots appear (as the selection is properly terminated).

I don't understand this: I have put editmode 0 at the end of the messsages - surely that ought to turn edit mode off and be a non-issue when clearing objects at specific locations. in my opinion, the black dots and rectangle should not be appearing on the screen as I can't ever visualise a circumstance where that is an intentional behaviour.

**Comment by umlaeute** [comment]
what has `editmode 0` to do with your patching keeping the mouse clicked (aka missing `mouseup` events)?

**Comment by umlaeute** [comment]
oh, and the black dots and rectangle appear on the screen because you are telling Pd (via your messages) that you clicked the mouse (and you never tell Pd that you released it).

i fail to see what the usecase where it is undesired behaviour to see the selection rectangle when click-dragging.
am i missing something?

**Comment by AydinHumphries** [comment]
> what has `editmode 0` to do with your dynamic patching keeping the mouse clicked (aka missing `mouseup` events)?

I thought the rectangle was created with "editmode 1" so "editmode 0" would release the rectangle: you can create rectangles with edit mode on but not with it off. I did not realise however that if you create a rectangle with edit mode on, do not release the mouse then turn edit mode off, the rectangle is still there.

> oh, and the black dots and rectangle appear on the screen because you are telling Pd (via your messages) that you clicked the mouse (and you never tell Pd that you released it).

I didn't understand your solution that involved mouseup so I asked on facebook and I managed to fix the issue like so:

[;
pd-mousedots.pd editmode 1, mouse 50 50 0 0, mouseup 65 65 0 0, cut, mouse 100 50 0 0, mouseup 115 65 0 0, cut, mouse 150 50 0 0, mouseup 165 65 0 0, cut, mouse 200 50 0 0, mouseup 215 65 0 0, cut, mouse 250 50 0 0, mouseup 265 65 0 0, cut, editmode 0;{

thanks for the solution

> i fail to see the usecase, where it is undesired behaviour to see the selection rectangle when click-dragging.
am i missing something?

if you do it with the mouse rather than dynamic patching, yeah it is pretty intentional. in any case I resolved the issue so it doesn't matter now.

**Comment by umlaeute** [comment]
btw, a (imho) much nicer way to structure the patch would be:

~~~
[bang(
|
[t b          b                                         b]
|             |                                          |
|             [50, 100, 150, 200, 250(                   |
|             |                                          |
|             [mouse $1 50 0 0, mouseup $1 50 0 0, cut(  |
[editmode 0(  |                                          [editmode 1(
|             |                                          |
|+-----------/------------------------------------------/
|/
[s $0-canvas]

[namecanvas $0-canvas]
~~~

you can easily extend the patch to delete more items, and even rename it.

**Comment by AydinHumphries** [comment]
I am just curious: I understand the first two numbers are co-ordinates, but I do not know what the last two zeros are for.

**Comment by umlaeute** [comment]
check the source code? just search for `"mouse"` in [`src/`](https://github.com/pure-data/pure-data/tree/master/src)...

this might come through a bit snarky, but given that this is a private API and it doesn't look as if that was to change anytime soon, i think it's only fair that people who want to use it know what they are doing.

**Comment by AydinHumphries** [comment]
> check the source code? just search for `"mouse"` in [`src/`](https://github.com/pure-data/pure-data/tree/master/src)...
> 
> this might come through a bit snarky, but given that this is a private API and it doesn't look as if that was to change anytime soon, i think it's only fair that people who want to use it know what they are doing.

I can't interpret source code yet, I barely understand C/++ basics. otherwise it would be a fair comment.
