### ISSUE TITLE
Tcl error in IEM gui [color( message for out of range hex colors

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#1158]
The `[color(` message of various IEM GUI objects gives a Tcl error if you pass hex numbers that are out of range, e.g. `#1234567`:

```
(Tcl) UNHANDLED ERROR: invalid color name "#1234567"
    (processing "-fill" option)
    invoked from within
".x1c9e5f0.c itemconfigure 1ca1dd8BASE1 -fill #1234567"
    ("uplevel" body line 4)
    invoked from within
"uplevel #0 $docmds"
```

**Comment by AydinHumphries** [comment]
and also: number atom will glitch and freeze up after you sent a value >255. this is regardless if it is a number atom sending a hex value - it could happen anywhere else on the patch.

**Comment by Spacechild1** [comment]
> after you sent a value >255

nothing to do with > 255

> number atom will glitch and freeze

yes, that's probably a side effect of the Tcl error.
