### ISSUE TITLE
Segmentation fault if Jack server runs with a blocksize < 64

### ISSUE THREAD

**Issue by mxa** [pure-data/pure-data#1162]
When Jack runs with a blocksize of 32 or 16, launching Pd (or switching to jack if ALSA is set) fails with a segmentation fault.

```
Partial read
Partial read
Segmentation fault (core dumped)
$ pdsend errorname: >>error writing "sock55b8ac71cc30": broken pipe<<
pdsend errorname: >>error writing "sock55b8ac71cc30": broken pipe<<

```

**Comment by umlaeute** [comment]
confirmed.
compiling Pd with a different dacblocksize (e.g. `#define DEFDACBLKSIZE 16`) makes it better.
- the polling scheduler (default) no longer segfaults (but spits out "Partial read" messages on end)
- the callback scheduler seems to work fine (but hangs for me, when I try to quit Pd)
