### ISSUE TITLE
property dialogs convert spaces in labels to underscores.

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1165]
labels of GUI-objects (e.g. [bng], [tgl],...) can have spaces in them.

~~~
[label space\ cadet(
|
[bng]
~~~

since Pd-0.51, the labels are stored correctly in the patch file (so they are persistent), and the property dialogs open up (without an error), showing the label with spaces (in this example: `space cadet`).

however, when I click <kbd>Apply</kbd> in the properties, the spaces in the label get converted to underscores (e.g. `space_cadet`).
the displayed label gets updated accordingly, and re-opening the properties shows the underscored label.

this makes it impossible to set a label with spaces via the properties dialog (with plain ASCII `0x20` space).
while the iemguis provide a `[label(` method, the built-in numberboxes and symbolboxes don't - so the only way to have them use a label-with-spaces is by editing the patch file in your favourite text-editor.

**Comment by Ant1r** [comment]
I'd say it's a dup of https://github.com/pure-data/pure-data/issues/960.
Anyway it's fixed by https://github.com/pure-data/pure-data/pull/953.

**Comment by umlaeute** [comment]
:facepalm:

**Comment by matthewbrandi** [comment]
On 30/09/2020 07:47, umläute wrote:
> labels of GUI-objects (e.g. [bng], [tgl],...) can have spaces in them.
> |[label space\ cadet( | [bng] |
> since Pd-0.51, the labels are stored correctly in the patch file (so they are
> persistent), and the property dialogs open up (without an error), showing the label
> with spaces (in this example: |space cadet|).
This is seductive, but it is not the whole story, I think. Bear with me while I play
with the simple test patch (tested on Pd version 0.51.2 on Linux):


#N canvas 515 93 1400 981 12;
#X msg 116 85 label space\ cadet;
#X obj 116 152 bng 15 250 50 0 empty empty space\ cadet 17 7 0 10 -262144
-1 -1;
#X connect 0 0 1 0;


If I open that patch, I can indeed see the label with its space AND (if I haven’t
clicked the message box) I can open the properties dialogue without error. I can then
hit “cancel” to dismiss the dialogue without altering the label. So far, so good.

If I then click the message box and subsequently right click the [bng] and select
“properties” to try to open the [bng]’s properties dialogue, the properties dialogue
doesn’t appear & I get the TCL error:


(Tcl) UNHANDLED ERROR: wrong # args: should be "pdtk_iemgui_dialog mytoplevel
mainheader dim_header wdt min_wdt wdt_label hgt min_hgt hgt_label rng_header min_rng
min_rng_label max_rng max_rng_label rng_sched lin0_log1 lilo0_label lilo1_label
loadbang steady num_label num snd rcv gui_name gn_dx gn_dy gn_f gn_fs bcol fcol lcol"
    while executing
"pdtk_iemgui_dialog .gfxstub556630cc1820 |bang|
----------dimensions(pix):----------- 15 8 size: 0 0 empty
--------flash-time(m..."
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $docmds"


Right?

So whether the TCL error is produced seems not to be dependent solely on the contents
of the patch (the file hasn’t changed). But it seems that the TCL error can still be
evoked in Pd version 0.51.2.

Best

m

-- 
matthew brandi

**Comment by AydinHumphries** [comment]
I can get spaces in canvases, vsliders, bangs, etc. but can't get them in number boxes. for number boxes it goes to _ by default.

**Comment by AydinHumphries** [comment]
> I can get spaces in canvases, vsliders, bangs, etc. with the method "word\ word2" but can't get them in number boxes. for number boxes it goes to _ by default.

sorry, it doesn't work if you type it in the properties for the aforementioned objects. you need [message{ - [label $1{ - [send message]

**Comment by umlaeute** [comment]
@AydinHumphries well yes, *this* bug report is exactly about "dialogs converting spaces in labels to underscores", so i don't really understand your comment (apart from: i can confirm that i get the same behaviour).

@matthewbrandi well, the Tcl-error is **not** the problem reported here. please let us keep issues on-topic (even if the problem you describe is *somehow* related, as it is also about "labels" and "spaces" (but lacks the "underscores" part)).

in any case, this has all been fixed in #953
