### ISSUE TITLE
Deken should add to libs or print user help

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#118]
The major stumbling block for installing Gem via Deken is that Gem also needs to be added to the startup libs. Deken currently does not do this by default, so Gem is installed but not loaded, leading to confusion.

Two possible solutions:

1. Deken can add to the startup libs. It would need to do a string search to make sure Gem is not already there.
2. Deken can add the ability to print a library post-install message. In the case of Gem, a message could be printed telling users they need to add Gem to the startup libs.

**Comment by umlaeute** [comment]
closing this as a duplicate https://github.com/pure-data/deken/issues/142

**Comment by danomatika** [comment]
Cool. Figured this was something already under consideration. I just wanted to write it down.
