### ISSUE TITLE
startup paths should have precedence over preference paths

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1180]
paths added to the Pd-preferences (<kbd>File</kbd>-><kbd>Preferences</kbd>-><kbd>Path</kbd>) are searched *before* paths from the startup flags (`pd -path <...>`).

i think this is backwards: ephemeral settings (startup flags) should have precedence over persistent settings (preferences).

probably @danomatika has some background about the current behaviour (as the current behaviour is a direct result of #153)

- this came up in the discussion of #1179 
- also #510 is somewhat related

**Comment by danomatika** [comment]
Yes, the order should be switched. Simple as that. I expect anything supplied on the command line should override/add to existing settings.

**Comment by danomatika** [comment]
In re-visiting #153, it seems it just takes swapping the order in [s_path.c](https://github.com/pure-data/pure-data/blob/master/src/s_path.c#L377). I don't think [g_canvas.c](https://github.com/pure-data/pure-data/blob/master/src/g_canvas.c#L1647) needs any changes for this.

**Comment by umlaeute** [comment]
@millerpuckette any chance to get this fixed for 0.51-3 (ideally with PR#510)
