### ISSUE TITLE
no option to edit properties in gui with spaces in label

### ISSUE THREAD

**Issue by AydinHumphries** [pure-data/pure-data#1185]
this may or may not be a duplicate issue, but I think sometimes it is helpful to remind developers an issue exists.

if you try to edit properties on a nbox (and some other but not all gui) after you use the hack to get a label with spaces, the dialogue won't open:

![image](https://user-images.githubusercontent.com/48067862/96349424-6a10c980-10a7-11eb-84fa-24b86788fc9b.png)

for replicating the issue try editing properties in the gui on this patch

[label.zip](https://github.com/pure-data/pure-data/files/5396172/label.zip)

maybe it is an impracticality to change the source code on this object, or the object works as intended, I don't know. I'm just sharing what I see as an error.

using windows 10 on lenovo laptop.

**Comment by porres** [comment]
> this may or may not be a duplicate issue

it is, you can read about it in https://github.com/pure-data/pure-data/issues/960

there are fixes for it in line as well

**Comment by AydinHumphries** [comment]
> > this may or may not be a duplicate issue
> 
> it is, you can read about it in #960
> 
> there are fixes for it in line as well

ah right ok then.

**Comment by AydinHumphries** [comment]
> > this may or may not be a duplicate issue
> 
> it is, you can read about it in #960
> 
> there are fixes for it in line as well

as a detour to the OP, I personally think also that you should be able to get a label with spaces as well. I say this of course without knowing the logistics of such a thing.

**Comment by porres** [comment]
> I personally think also that you should be able to get a label with spaces as well 

we have PRs for that too
