### ISSUE TITLE
can't loadbang random values "effectively"

### ISSUE THREAD

**Issue by AydinHumphries** [pure-data/pure-data#1186]
another bug report I hope is not a duplicate:

when you loadbang random values, this will always send the lowest value in range only, so not exactly "random":

![image](https://user-images.githubusercontent.com/48067862/96372914-35614880-1161-11eb-9f31-a6d08287f9e5.png)

patch for replicating the issue:

[loadbang random values.zip](https://github.com/pure-data/pure-data/files/5397740/loadbang.random.values.zip)

n.b. this does not happen every time you load a patch, only when pd is **closed** and you open a patch

OS: windows 10, lenovo laptop

**Comment by AydinHumphries** [comment]
n.b. if you are wondering the solution before the source code is changed, this seems to work, if there might be circumstances sending two bangs is not good I don't know but otherwise:

![image](https://user-images.githubusercontent.com/48067862/96373356-df41d480-1163-11eb-8d6f-2c10367e3027.png)

**Comment by AydinHumphries** [comment]
wait that always seems to send out 60, I don't even know what is going on with this.

**Comment by AydinHumphries** [comment]
the problem seems to be that there will be established values the "random" expression order will feed out when loadbang is triggered, however an expression object that has already been created before opening the patch will not feed out these established files unless triggered with loadbang, even when there is a delay:
![image](https://user-images.githubusercontent.com/48067862/96373519-e4535380-1164-11eb-8854-e50bd7400228.png)

**Comment by porres** [comment]
This is known and happens because the seed value is fixed. But you can change it with the "seed" message for [random], for instance.

perhaps what we need in vanilla is a way to get the time/date value to generate a different seed every time you open your patch. This is what people do usually  but requires externals.

I'm also about to make this automatically happen for all my random objects in else.

**Comment by porres** [comment]
note ths has nothing to do with loadbang, you'll get the same value any time you bang for the first time when you open your patch. So your issue title is inaccurate. Maybe close this and open a new issue requesting a way to set unique seeds every time you open your patch.

**Comment by AydinHumphries** [comment]
> note ths has nothing to do with loadbang, you'll get the same value any time you bang for the first time when you open your patch. So your issue title is inaccurate. Maybe close this and open a new issue requesting a way to set unique seeds every time you open your patch.

I have closed, but I don't think this is correct unless I have missed something. look at the screenshot in the fourth comment. the two expression objects both send out a fixed sequence of values but they are different. I have to look into [seed{ properly before I open a new issue as I have not understood about that argument or even what it was meant for until now.

**Comment by AydinHumphries** [comment]
so maybe then you would be better to post a new issue as I do not properly understand about [seed{

**Comment by porres** [comment]
done https://github.com/pure-data/pure-data/issues/1187
