### ISSUE TITLE
Request: a way to set unique "seeds" for [random]

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1187]
Usually, when people want a random seed for [random] they use a hack like getting the system time. I wonder if we could have a way to do something like this in vanilla.

**Comment by Spacechild1** [comment]
I think `[seed(` without arguments could give a random seed.

On the other hand, I'm wondering why we don't start with a random seed (based on system time) in `makeseed()`. After all, if people need reproducable random numbers, they have to use `[seed(` anyway...

**Comment by porres** [comment]
I agree, I only did not propose that because of my fear to request any change whatsoever :)

**Comment by porres** [comment]
> I agree, I only did not propose that because of my fear to request any change whatsoever :)

which could lead to another compatibility flag ;)

**Comment by porres** [comment]
but if we're to change things (which I like), let's also think about changing the initial seed for [expr] as you can't even set its seed

**Comment by Spacechild1** [comment]
> which could lead to another compatibility flag ;)

Well, the only *documented* way to get a reproducable sequence of random number is to use the `[seed(` message. IMO, people should never rely on implementation details like the default seed value of a random number generator.

**Comment by porres** [comment]
closing in favor of https://github.com/pure-data/pure-data/issues/1717
