### ISSUE TITLE
Windows: Message boxes with escape characters don't save properly

### ISSUE THREAD

**Issue by jamshark70** [pure-data/pure-data#1189]
1. New patch.
2. New message box.
3. Contents = `string\ with\ escaped\ space`
4. Save.
5. Open the pd file in note pad. See: `#X msg x y string with escaped space`.
6. Open the pd file in pd. Escape characters are gone.

This breaks usage of [vstplugin~] for one thing.

Same steps in Linux, the file is saved correctly (and reopens correctly too).

**Comment by Lucarda** [comment]
Hi,

which Pd version?

I'm on Windows and **Pd 0.51.2** and I get `string\ with\ escaped\ space` after reopening the file or inspecting it with notpad.

**Comment by porres** [comment]
yeah, this has been fixed in earlier versions!

**Comment by jamshark70** [comment]
Good catch -- that machine was on 0.49. I'll update it next week. Thanks for the quick confirmation.
