### ISSUE TITLE
Pd doesn't print anymore

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#119]
Pd-0.48-0test3 doesn't produce any output with

~~~
[bang(
|
[print]
~~~~

the problem seems to be, that when upgrading from Pd<0.48-0test3, no *loglevel* settings are stored in the preferences, so Pd assumes a value of `0` (aka `fatal`); thus not showing the printout by default.

manually setting the loglevel to `2=normal` fixes this, but i think this is going to cause a lot of confusion.

**Comment by danomatika** [comment]
Hrm, ok. I was testing by wiping the preferences and checking what was there. I thought the catch line would fail when trying to grab the log level but it's not there, it must be setting 0 instead. The default of 2 is set, but I guess it's being overwritten.

**Comment by danomatika** [comment]
I can confirm that without the setting in the pref file, the log level combo not is empty and nothing prints. Looking into a fix.

**Comment by danomatika** [comment]
Fixed in 0a33703
