### ISSUE TITLE
array-object-help: misleading claim about median

### ISSUE THREAD

**Issue by jamshark70** [pure-data/pure-data#1200]
https://github.com/pure-data/pure-data/blob/master/doc/5.reference/array-object-help.pd#L335

> array - so for instance \, the 0.5 quantile is the median of the array.

In fact, 0.5 quantile returns the index into an array of positive numbers where half the sum is to the left of this index. This is a useful operation but it is not a median, at least not in the most commonly used definition.

"In statistics and probability theory, a median is a value separating the higher half from the lower half of a data sample, a population or a probability distribution. For a data set, it may be thought of as 'the middle' value."

A median is a value in the data set's domain -- not an index -- and median makes no assumption about the sign of the input values.

There may be another concept of median but if so, it is not as widely used as this definition. Hence it's misleading to use the term "median" here without further explanation.

**Comment by Spacechild1** [comment]
> In fact, 0.5 quantile returns the index into an array of positive numbers where half the sum is to the left of this index. 

The key point to understand is that each array *index* represents an item while its *value* indicates the frequency. Half the sum actually means half of the number of values - which turns out to be the median. Does that make sense?

Wikipedia agrees that the 0.5 quantile is indeed the median :-) https://en.wikipedia.org/wiki/Quantile

**Comment by jamshark70** [comment]
OK, so, the argument is "the documentation is fine because a specialist in statistics would understand how to use an 0.5 quantile to get the median."

Got it.

Most people reading the word "median" would think "sort the data and, if the data set size is odd, return the middle value, and if even, the average of the two middle values."

The way to use [array quantile] to get this value is:

1. Histogram the data set. (In the case of fractional values, first determine the LCM of the denominators and multiply every data point by this, so that you have integer bins.)

2. 0.5 quantile.

3. If the data set size is odd, then `median_index / lcm` is the answer. If it's even, then the median index overshoots, and you have to backtrack to find the previous non-zero element in the histogram, and average these two indices: e.g. dataset `0 1 2 5 6 7`, histogram `1 1 1 0 0 1 1 1`, array quantile 0.5 will return 5; from this, you would have to find the preceding nonzero index = 2 and the median would be (2+5) / 2 = 3.5.

From the help as given, I would estimate only a small minority of users would figure that out, and a smaller minority would bother to implement it.

So I still believe I'm correct to say that this point in the documentation is misleading.

**Comment by Spacechild1** [comment]
First, the 0.5 quantile is always the median by definition. I think we agree on that.

I think the misunderstanding is only about the array data. In the case of `[array quantile]`, the array is basically a histogram. Remember that `[array quantile]` is only meant as a generalizaton of `[array random]`. The documentation mentions that - but maybe not clearly enough?

If you just want to get the median of a bunch of values, you sort them and get the one in the middle. You don't need `[array quantile]` for that.

PS: we finally need a built-in `[array sort]` and `[list sort]` function...

**Comment by jamshark70** [comment]
I think it isn't clear enough.

Fully agreed that the lack of a built-in sort function is an unpleasant limitation. With that, it would be trivial to make a median abstraction. Actually, for lists, there are [zl sort] and [zl median] already in cyclone (pd would benefit by just importing cyclone into core IMO).

**Comment by Spacechild1** [comment]
> pd would benefit by just importing cyclone into core IMO

Certainly not. The philosophy of Pd is to have a small core while making it easy to install externals. Including lots of things in Pd makes it unmaintainable in the long run (see Pd extended).

**Comment by Spacechild1** [comment]
Reopening in case someone wants to improve the documentation. Maybe @porres? ;-)

**Comment by porres** [comment]
sure :) I can give it a try

> Certainly not. The philosophy of Pd is to have a small core while making it easy to install externals. Including lots of things in Pd makes it unmaintainable in the long run (see Pd extended).

yeah, that would be a very bad idea for different reasons.

> PS: we finally need a built-in [array sort] and [list sort] function...

Let's open an issue? I second that specially now that we got a "sort" function for [text]

**Comment by jamshark70** [comment]
> The philosophy of Pd is to have a small core while making it easy to install externals. Including lots of things in Pd makes it unmaintainable in the long run (see Pd extended).

This is now getting a bit far afield, maybe best to move further discussion of that off of github. It seems to me at times that the pd community's suspicion of externals at times goes beyond the matter of inclusion in core... but save that for another time.

Thanks all.

**Comment by porres** [comment]
> Reopening in case someone wants to improve the documentation. Maybe @porres? ;-)

I'm just not sure what to actually do here :) just tell me and I'll do it

**Comment by Spacechild1** [comment]
It's about clarifying the usage of the term "median" in the `[array quantile]` help patch. It's not the median of the array values but rather the median of the array when interpreted as a histogram. See also https://github.com/pure-data/pure-data/issues/1200#issuecomment-720367258
