### ISSUE TITLE
[writesf~] + invalid file path locks up Pd

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#1211]
If you pass an invalid file path to `[writesf~]`, e.g. `[open /tmp/foo.wav(` on Windows, and start recording, Pd will become unresponsive.

More specifically, it the console gets flooded with messages like:
```
writesf waiting for disk write..
(head 262016, tail 0, room 128, want 128)
... done waiting.
```

**Comment by umlaeute** [comment]
i can confirm that this also happens on Linux (where `/tmp/foo.wav` is a legal path): `[open /foo.wav(` (as non-root, so no write-permissions on `/`) locks Pd-0.51-2 while flooding the console.

just for the record: there was a report of a somewhat similar issue on [StackOverflow](https://stackoverflow.com/questions/64510543).

**Comment by mxa** [comment]
Maybe it would be wise to 

1. make Pd not lock up when the directory is write protected but give explicit user feedback about the problem
2. include that information in the help files of objects which are writing to disk, and - if possible - use a path in the examples which is writable on all systems (if such exists).

**Comment by Spacechild1** [comment]
> make Pd not lock up when the directory is write protected

It's not about write protection, it's about `write` failing (for whatever reason).

> include that information in the help files

Which information? That writing fails if the path doesn't exist or you don't have sufficient permissions? I thought people would already know that :-p

**Comment by umlaeute** [comment]
> Maybe it would be wise to
> 
>     1. make Pd not lock up when the directory is write protected but give explicit user feedback about the problem

apart from what @Spacechild1 already mentioned, i would also like to add that:
- we don't do explicit checks whether the target directory is writable. we don't even split the target into a "directory" and "basename" component. we just pass "everything" to the OS.
- even if we did perform a is-directory-writable check (and this made sense - which it doesn't necessarily do as @Spacechild1 pointed out), we would still be susceptible to race conditions.

> 
>     2. include that information in the help files of objects which are writing to disk, and - if possible - use a path in the examples which is writable on all systems (if such exists).

unfortunately such path does not exist.
(afaict, there's a common concept of user-writable directories (their home-directory; a tempdir) on all platforms; but they all look very different)

**Comment by Spacechild1** [comment]
> use a path in the examples which is writable on all systems (if such exists).

That is definitely something to consider, but as @umlaeute said, such path does not exist. Two possible solutions:
1) use bang + `[openpanel]` instead of a hardcoded path
2) use two paths: `/tmp/foo.wav` or Unix-like systems and `C:/Windows/Temp/foo.wav` for Windows.

@umlaeute I'll work on a fix for the lock up.

**Comment by mxa** [comment]
> Which information? That writing fails if the path doesn't exist or you don't have sufficient permissions? I thought people would already know that :-p

Apparently not, just look at the StackOverflow post.

**Comment by Spacechild1** [comment]
> Apparently not, just look at the StackOverflow post.

Well, if a user provides a bad filepath, `[writesf~]` *should* give a proper warning message (currently it just silently fails and lock up).

However, I don't think it is not necessary to tell users *in the help file* that a path has to be valid, because that is trivial information. Otherwise would have to do this in every place where an object supports writing to disk...
