### ISSUE TITLE
document list method of [text sequence]

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#1214]
`[text sequence]` has an undocumented list method, which is the same as the `[args(` + `[bang(` method, with the difference that the arguments are only set temporarily. Also note that it (temporarily) overrides any arguments previously set with `[args(`.

**Comment by Spacechild1** [comment]
ping @porres

**Comment by porres** [comment]
we can also ping @millerpuckette to see if he wanted this to be an actual feature or if it's a leftover ;)

**Comment by Spacechild1** [comment]
Judging from the code, it is highly unlikely that this is a left-over or not intended.

**Comment by porres** [comment]
please flag this as 'documentation' so it's in my radar.
