### ISSUE TITLE
Some key features disabled

### ISSUE THREAD

**Issue by SallarShayegan** [pure-data/pure-data#1217]
Hello, I just started learning to work with pd and installed it on my raspberry pi (OS: raspbian) via apt-get (pd should be the latest version) . But I found out that lots of the menu items are disabled (grayed out), such as the whole put menu, the edit mode from edit menu, etc. Then I installed pd-0.51-1 on my macbook and got the same problem. I cannot do anything with the program, because these are the key things that are disabled. I'd be glad if you could say how to fix this.

Best regards, Sallar Shayegan

**Comment by Spacechild1** [comment]
You have to actually create a patch (File -> New) before you can put any objects ;-)
