### ISSUE TITLE
ASIO DLLUnregisterServer unhandled exception on Quit

### ISSUE THREAD

**Issue by chainjazz** [pure-data/pure-data#1219]
```
Windows 7 x64 / Server 2008 R2 SP1
Pd 0.51-1 x86_64 and i386 (_clarification: 32-bit and 64-bit builds for intel_)
```

When using ASIO, pd always crashes after quitting (cleanly, presumably).

WinDbg output

`0:002> g`
`(1f78.1f70): Access violation - code c0000005 (first chance)`
`First chance exceptions are reported before any exception handling.`
`This exception may be expected and handled.`
`rig3asio64!DllUnregisterServer+0x608d4:`
`000007fe d83254c4 498b4308        mov     rax,qword ptr [r11+8] ds:00000000`00000008=????????????????`

**Comment by umlaeute** [comment]
please provide more information:

- which version of Pd is this?
- which version of Windows?
- which ASIO driver do you use for which soundcard?

**Comment by chainjazz** [comment]
Windows 7 x64 / Server 2008 R2 SP1
Pd 0.51-1 x64/i386

The driver is mentioned in the debug output.
It appears to be a "sleeping" driver installed by Native Instruments for their proprietary hardware brands (I'm guessing for software, in this case Guitar Rig)

**Comment by chainjazz** [comment]
I might have disabled the driver, or the driver service, because I don't use/own the hardware.

**Comment by umlaeute** [comment]
wtih " Pd 0.51-1 x64/i386" do you mean both x86_64 (aka x64 or amd64; or simply "64bit intel") **and** x86 (aka i386; or simply "32bit intel"); or is it a typo?

(just fix clarify it in your original post and let me know, that i can remove *this* comment)

**Comment by chainjazz** [comment]
The driver (i.e. drivers, Guitar Rig IO Session, Guitar Rig IO something, and Kontrol Rig Driver) are automatically installed as separate components, and removable through the uninstall  mechanism. After removal of the components, Pd no longer crashes on quit. 

(But what if you need those drivers...)

**Comment by Spacechild1** [comment]
I noticed that we never call `Pa_Terminate()`, although it is strongly recommended:

> Pa_Terminate() MUST be called before exiting a program which uses PortAudio. Failure to do so may result in serious resource leaks, such as audio devices not being available until the next reboot.

http://portaudio.com/docs/v19-doxydocs/portaudio_8h.html#a0db317604e916e8bd6098e60e6237221

This might be a possible explanation for the crashes you're experiencing. I'll make a PR and let's try if it fixes your issue.

**Comment by Spacechild1** [comment]
@chainjazz Can you try the following package (Windows 32-bit) and see if the crashes are gone? 
[pd-0.51.3-sys_audio_terminate.zip](https://github.com/pure-data/pure-data/files/5547180/pd-0.51.3-sys_audio_terminate.zip)

**Comment by Spacechild1** [comment]
ping @chainjazz

**Comment by chainjazz** [comment]
Hey, I have tried just now. I have reinstalled [Rig Kontrol 3 driver from Native Instruments](https://protected-cdn-ec.native-instruments.com/um/audiohardware/Rig_Kontrol_3_310_PC.zip?TaTEXto4r_uKCtjD9Oa6MSFz5TcqIxp11RRP0MMkpNXd189ugdxvjxifpwvgMoCKWnLdoPsDc6cA-Kb3QgbfsVNWP4Ouauibu80asSV8Fq83StC314DYt_xg1DxvihWJSEUiCHKxeHI&_ga=2.241869506.156934640.1605926437-1521476130.1597321536)

Both my build (official source) and your zip version (test5) crash in the same way as above.
When the driver is not present (i.e. deinstalled), there are no crashes.

1.  Closed Pd (crashes gone due to driver not being present)

**Comment by Spacechild1** [comment]
What is "51.3-test5"?

Two more things:
1. can you post the full backtrace of your build? Preferably use a debug build and debug with GDB (as Pd is usually build with MinGW).
2. can you try the same with a DAW (e.g. REAPER)? Start it with a debugger from the command line, select some ASIO device (to make sure that the ASIO drivers are loaded) and check if the program crashes on quit.

**Comment by chainjazz** [comment]
@Spacechild1 

`test5` is the suffix for the build name of Pd you linked to `(sys-audio-terminate)`.

I am using _Ableton Live_ with ASIO (Fast Track mark II) on a regular basis, never experienced crashes _of this kind_.

I have just tried running Ableton Live through WinDbg. Couple of exceptions, but no visible crashes, which leads me to believe we need more than WinDbg to get to the bottom of this. (No mention of the rig3 driver in the debug session).

As per your instruction, I'll try a debug build of Pd, tomorrow, if you don't mind. I'm finishing up on other stuff, and sleeptime is running away.

P.S. Get this
Ableton Live skips loading the driver, as far as WinDbg log is concerned.
However, Pd does.

`ModLoad: 00000000`54220000 00000000`54b5d000   c:\program files\native instruments\rig kontrol 3 driver\asio\rig3asio32.dll`

Sorry if not helpful now, it's late. Cheers.

**Comment by Spacechild1** [comment]
> Ableton Live skips loading the driver, as far as WinDbg log is concerned.

:-) Then I'm not surprised it doesn't crash. Can you try with another program, e. g. REAPER?

BTW, when you try with a debug build of Pd, maybe use my branch: https://github.com/Spacechild1/pure-data/tree/sys_audio_terminate

TBH, I don't think we can do much. If you also get the crash with my branch (which properly calls `Pa_Terminate()`, that is either a problem with the driver or with portaudio.

**Comment by chainjazz** [comment]
Yeah, I think you might be right with portaudio. But I think NI should chime on this as well. Installing unnecessary drivers is a no-no. I am closing this for now. Wish you all the best, and I'll see if I can concentrate my efforts on some real bugs. I would like to see Pd go 1.0. :)
