### ISSUE TITLE
[net objects] problem with Android

### ISSUE THREAD

**Issue by Ant1r** [pure-data/pure-data#1229]
Latest version of network objects `[netsend]` and `[netreceive]` don't work in Android (at least for me).
They signal the error `Invalid value for ai_flags`.

I discovered that removing the setting of `AI_ALL` and `AI_V4MAPPED` flags in:
https://github.com/pure-data/pure-data/blob/c8af32521e9c723bfb2c83fbdd798b30461876f7/src/s_net.c#L55-L65
was doing the job: the error is cleared and my patches work properly.

These flags seem not to be allowed for this platform, see for example https://stackoverflow.com/questions/39674147/getaddrinfo-on-android-returning-error-eai-badflags .

Not sure how it should be cleanly fixed however.

**Comment by Spacechild1** [comment]
Thanks for the report!

`The getaddrinfo function as implemented in	FreeBSD	currently does not
     support AI_ALL and	AI_V4MAPPED flags and returns EAI_BADFLAGS if one of
     them is specified.`

https://www.freebsd.org/cgi/man.cgi?query=getaddrinfo&sektion=3&manpath=FreeBSD+7.2-RELEASE

*Ugh*

So how can you send to an IPv4 address from an IPv6 socket if you can't obtain IPv4 mapped addresses!?

One thing we could do is catch `EAI_BADFLAGS` and simply default to IPv4...

@danomatika Any other ideas?

**Comment by danomatika** [comment]
>One thing we could do is catch EAI_BADFLAGS and simply default to IPv4...

Do this in a FREEBSD define as it's clearly a platform-specific limitation for now.

**Comment by danomatika** [comment]
Same for Android, if that's how the platform works as well. If they both do that in the same way, then maybe just do without without the defines.

**Comment by danomatika** [comment]
This is also *bad news* for libpd, great.

**Comment by Spacechild1** [comment]
yeah, it is certainly easier to simply disable IPv6 networking on BSDs and Android.

However, by catching the error, IPv6 support will magically work once the libc bug gets fixed.

> I wanted to release libpd 0.12 based on the 0.51-3 tag. :P

Yeah, bummer.

Anyway, I can make a PR and ask @Ant1r to test it. Maybe Miller is willing to make a 0.51-4 release. He wouldn't even need to create new packages, as the bug doesn't affect Windows and macOS. Also, there have been pettier reasons for bugfix releases in the past. :-)

**Comment by danomatika** [comment]
Yeah, sounds good. We need a good default work around for this and I agree it could just drop to IPV4 as that's Pd's current default. If you make a PR, we can bug Miller on the dev list for a 0.51-4 tag and source-only release for libpd.

**Comment by Ant1r** [comment]
> I wanted to release libpd 0.12 based on the 0.51-3 tag

yes what's I actually did in my project of course. Cause I'm testing a 2-pdthreads app setting, which starts to work well BTW! 

> I can make a PR and ask @Ant1r to test it

yes, with pleasure!

**Comment by Spacechild1** [comment]
@Ant1r Can you try the following branch? https://github.com/Spacechild1/pure-data/tree/ipv6-bsd-fix

**Comment by Ant1r** [comment]
yep thanks, it works just fine (for who doesn't care about ipv6, which is my case for now ;-)!

**Comment by Spacechild1** [comment]
Great, thanks for testing!
