### ISSUE TITLE
No scrollbars visible on macOS using tk 8.6.10

### ISSUE THREAD

**Issue by sebshader** [pure-data/pure-data#1237]
Using Pd-51.0-3 from miller's site on osx mojave 10.14.6 the scrollbars aren't visible. They can be dragged once found, and the page can still be scrolled with the scroll wheel. This doesn't occur with the current git core-8-6-branch from tk. (seems to have been fixed sometime before https://core.tcl-lang.org/tk/info/3fae4554efd427a2)
I thought I saw a report/discussion about this but couldn't find it..

**Comment by sebshader** [comment]
ok this is odd.. now when I compile tcl, tk and vanilla with the 8.6.10 release (not the git branch) the scrollbars work ok, yet miller's distribution of pd isn't working

**Comment by sebshader** [comment]
If I use a wish compiled with ./tcltk-wish 8.6.10 I get scrollbars, but they don't move with the mouse wheel.
If I use the wish app in mac/stuff then I don't get scrollbars at all, which is also the case with the .app on miller's website

**Comment by sebshader** [comment]
this seems to be the commit where the mousewheel issue is fixed https://core.tcl-lang.org/tk/info/71433282feea6ae9

**Comment by danomatika** [comment]
Ok, I will look into back porting this.

Note: I don't actively watch this repo so I don't get notifications unless explicitly added to a discussion. I only saw this now in relation to your other issue and when I checked the issues list.

**Comment by danomatika** [comment]
@sebshader To confirm, that commit fixes scrollbar updates for me on 10.14.

**Comment by danomatika** [comment]
Ok, fix is in #1242 and a test build using Tk 8.6.10 and our current patches applied. Please test and respond to the PR.
