### ISSUE TITLE
"Find" dialog permanently hides text cursor when editing messages

### ISSUE THREAD

**Issue by LamptonWorm** [pure-data/pure-data#1252]
Using PD 0.51.3 on Windows 10, 64-bit
- in edit mode
- double click into any message, you see the flashing cursor
- press CTRL + F to open find dialog
- cancel the find dialog
- double click back into any message, the cursor is invisible (if you type you can 'see' where it is supposed to be displayed)
- you have to close/re-open the patch to get it working again

**Comment by jyg** [comment]
could not reproduce on linux 64  pd 0.51.3, 
but could see same buggy behaviour with pd 0.51 32 bit on virtual machine windows7 32bits

**Comment by Lucarda** [comment]
I could reproduce on Win10 Pd-0.51-4 (64bit).

The prompt is invisible in messages and objects.

As a workaround you can get back the prompt if you do "Find again" (Ctrl+G) or "Find last error".

**Comment by umlaeute** [comment]
i *can* reproduce this with Pd-0.52-1 on Debian/amd64
