### ISSUE TITLE
[expr array1[1] = $f1] crashes pd

### ISSUE THREAD

**Issue by sinewave-sinewave** [pure-data/pure-data#1255]
When trying to interact with above mentioned object in the help patch crashes pd. 
Win 10 64 bit.

**Comment by sinewave-sinewave** [comment]
![pd-issue2](https://user-images.githubusercontent.com/73533352/103544058-c3ff7f00-4e9f-11eb-9595-3e28f56c52e8.gif)

**Comment by umlaeute** [comment]
works here (Pd-0.51.4 on Linux/amd64) without a problem.

**Comment by Spacechild1** [comment]
also works here on Windows 7 with Pd 0.51-4.

what's your Pd version? can you share the full test patch which triggers the crash?

**Comment by sinewave-sinewave** [comment]
Thank you for your feedback. Pd version is 0.51.4 and I've discovered possible bug in expr help patch (Pd\doc\5.reference)

**Comment by Spacechild1** [comment]
Strange, can't reproduce with Pd 0.51-4 64-bit on Windows 7. I might try later on my Windows 10 machine.

**Comment by umlaeute** [comment]
> and I've discovered possible bug in expr help patch (Pd\doc\5.reference)

well i tried with exactly this help patch (and i guess @Spacechild1 as well) without problems.

so the question is: what is different on your system from ours?
could you try to:
- make sure that you are not loading any libraries (or gui-plugins)
- create a minimal example that triggers the problem
  - according to your description, 3 objects (`[table foo 10]`, `[expr foo[1]=$f1]` and a numberbox) should be enough to trigger the problem.
- start Pd from the cmdline
  1. <kbd>⊞</kbd>+<kbd>r</kbd>, type `cmd` and hit <kbd>Return</kbd>
  2. in the cmdline, type `C:\Program Files\Pd\bin\pd.com -stderr -verbose -noprefs -nostdpath` and hit <kbd>Return</kbd>
     - (adjust the path to `pd.com` to your installation)
   3. load the (minimal) crasher patch
   4. interact with the patch to make it crash
   5. check if Pd printed something on the cmdline (and share it with us ;-))

**Comment by sinewave-sinewave** [comment]
> > and I've discovered possible bug in expr help patch (Pd\doc\5.reference)
> 
> well i tried with exactly this help patch (and i guess @Spacechild1 as well) without problems.
> 
> so the question is: what is different on your system from ours?
> could you try to:
> 
> * make sure that you are not loading any libraries (or gui-plugins)
> * create a minimal example that triggers the problem
>   
>   * according to your description, 3 objects (`[table foo 10]`, `[expr foo[1]=$f1]` and a numberbox) should be enough to trigger the problem.
> * start Pd from the cmdline
>   
>   1. ⊞+r, type `cmd` and hit Return
>   2. in the cmdline, type `C:\Program Files\Pd\bin\pd.com -stderr -verbose -noprefs -nostdpath` and hit Return
>      
>      * (adjust the path to `pd.com` to your installation)
>   3. load the (minimal) crasher patch
>   4. interact with the patch to make it crash
>   5. check if Pd printed something on the cmdline (and share it with us ;-))
Here's the video. Note how dragging the number box doesn't produce any problems, but doing the same with vslider crashes pd. I hope you'll find a clue from it.
![pd-issue4](https://user-images.githubusercontent.com/73533352/103586234-f67f9b00-4ee4-11eb-9e61-e86d80395c61.gif)

**Comment by umlaeute** [comment]
could you post the patch here?

**Comment by sinewave-sinewave** [comment]
Sure,
#N canvas 766 247 450 300 12;
#N canvas 0 50 450 300 (subpatch) 0;
#X array array1 10 float 0;
#X coords 0 10 9 0 220 130 1 0 0;
#X restore 537 143 graph;
#X floatatom 345 192 0 0 100 0 - - -;
#X obj 345 73 vsl 20 100 0 10 0 0 empty empty empty 0 -9 0 10 -262144
-1 -1 0 1;
#X obj 345 223 expr array1[1] = $f1;
#X connect 1 0 3 0;
#X connect 2 0 1 0;

**Comment by Lucarda** [comment]
Strange. I cant reproduce with the test patch or the help file.
Works Ok here.


Win10 Pd 0.51-4 (64bit).

**Comment by umlaeute** [comment]
i found an uninitialized value in the relevant code portion.

if the `optr->ex_type` happens to be `ET_VEC` (15), Pd crashes here.
i have no idea why such an unitialized value would trigger the crash for @sinewave-sinewave always, but never for the rest of us. but that's the joys of undefined behaviour.

anyhow 9aaa702 adds some initialisation code.
for now, I assume that this issue is fixed.
