### ISSUE TITLE
conflict issues with declare -lib/-path if both have the same name.

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1257]
My issue happens if ceammc is pre loaded via startup and I'm only using [declare] to load 'else', or if I load "ceammc" in one patch first with [declare] and then open a new patch that loads else (basically the same thing). With pd-ceammc I also get this issue, but that's because that distribution loads 'ceammc' by default via startup and that's not its fault, it's just like using pd with ceammc in the startup.

I get conflcits bascially anyway it comes, even if I'm loading else and ceammc in the same patch with [declare -path else -lib ceammc]. 

So, the thing is if I try to load an object that has the same name, like "[xfade~]" from ELSE, that just doens't happen, it always gets the one from ceammc instead. And in all the above cases I'd expect ELSE to have a priority. One because I was using a patch that just had [declare -path else], and 2 because [declare -path else] came first in the list.

This can be quite counter intuitive, specially when I open a new patch and just have [declare -path else], where I expect that objects from ELSE have a priority to be loaded.

I know there are workarounds, such as using else/xfade~ instead, but that takes [declare -path] out of the equation and the point here is to discuss [declare]'s functionality. I can also keep [declare -path] and use "./xfade~", which will force to load the one from else, but in practice that doesn't differ much having to specify "else/xfade~" so I don't count this as a separate alternative.

Anyway, the way things go is that when you load binaries, they have priority in the search process, that's what it seems. I wonder if we can change things and force priority on the search paths for these cases and, if not, we need to document this.

By the way, I'm using [declare -path else] in the abstractions from else as a way for this to work both in Pd Vanilla and in Camomile. Cause camomile cannot load compiled objects as "else/xafde~". Long story short, this now gives me a conflict between ELSE and other libraries and I was hoping it'd just work in all cases, so I woudn't need to have a set of abstractions just for camomille.

**Comment by umlaeute** [comment]
> Anyway, the way things go is that when you load binaries, they have priority in the search process, that's what it seems. I wonder can change things and force priority on the search paths for these cases and, if not, we need to document this.

currently it is practically impossible to change this, as we don't have a per-canvas (or per-patch) resolution of objectnames.
iirc, there has been attempts a couple of years ago to add per-canvas resolution of objectnames, but this requires a major rewrite of the object instantiating code, and afair didn't come to a proper solution.

so i'm pretty sure this is a "won't fix" for now.

i also thought that this is well documented (but you probably know better about that).

btw, i think the title (and parts of the issue description) are misleading.
the gist is (alternatively i completely failed to understand the issue at hand):
- as soon as any objectname is registered via `class_new` it takes precedence (and from then, `-path` is practically unused)
- objectnames registered via `class_new` are registered *globally*

**Comment by porres** [comment]
> btw, i think the title (and parts of the issue description) are misleading.

yeah, I think you just knew how to put it better, right to the point and with technical details right there in the end ;) I'm coming more from a user perspective.

> i also thought that this is well documented (but you probably know better about that).

Help file of declare doesn't touch this and I tried my best at the manual section but I didn't cover this and that whole thing could benefit from another round of reivision

**Comment by porres** [comment]
As far as just needing a better way to control what objects to load, this PR seems like a solution #630

**Comment by umlaeute** [comment]
while this helps in a way and is simple to implement, it should be noted that this is *not* a replacement for local classname resolution.

**Comment by Spacechild1** [comment]
I agree that local classname resolution and #630 are orthogonal, but they can work together. Generally, I think people should use the library prefix as much as possible (which requires #630 for multi-objects-per-binary libraries). It is not only safer, but also self-documenting. If someone is really too lazy to type those extra characters, then local classname resolution can help to avoid issues like we currently have. Personally, I think #630 is more important.

**Comment by porres** [comment]
since this is a won't fix, I'll close it. Will open a new one to talk about the documentation aspect of this.
