### ISSUE TITLE
Number boxes are uneditable, lock up, and don't propagate value

### ISSUE THREAD

**Issue by bmitc** [pure-data/pure-data#1263]
OS: Windows 10
Pure Data version: 0.51.3

Number boxes are unfortunately unusable. There are a few different issues.

- The majority of the time, number boxes are uneditable. The only way to edit them is to do a `Ctrl + drag` to get the value to change.
- However, many times the value doesn't seem to correctly propagate until the number is edited again (by doing a `Ctrl + drag`. For example, a square may have a size of 3, but until I change it from 3 to something else and back to 3, it doesn't actually have a size of 3.
-  Sometimes, the number box will just lock up and become completely uneditable by any means. It even becomes unmovable on the drawing canvas/diagram.

For now, the only work around is to use a message to get reliable numbers in the patch.

**Comment by Spacechild1** [comment]
> Number boxes are unfortunately unusable. 

If that was really the case, many people would have complained by now...

> The majority of the time, number boxes are uneditable. The only way to edit them is to do a Ctrl + drag to get the value to change.

I suppose because you're in edit mode and not in run mode ;-) By the way, for me "editable" means being able to change the properties of the object (right click -> properties), and that's what edit mode is for. What you want is to *interact* with the number box and that's the purpose of run mode. "Ctrl + drag" is just a way to interact with the number bux while in edit mode.

**Comment by Spacechild1** [comment]
> However, many times the value doesn't seem to correctly propagate until the number is edited again (by doing a Ctrl + drag. For example, a square may have a size of 3, but until I change it from 3 to something else and back to 3, it doesn't actually have a size of 3

I have no idea what you mean here. Can you provide a simple test patch?

> Sometimes, the number box will just lock up and become completely uneditable by any means. It even becomes unmovable on the drawing canvas/diagram

Does this only happen if you press "Ctrl" *after* clicking in the number box? If yes, then this is not a bug. You always have to press the modifier key first.

**Comment by porres** [comment]
> If that was really the case, many people would have complained by now...

that's what  guess too...

> I have no idea what you mean here. Can you provide a simple test patch?

or a video?

**Comment by umlaeute** [comment]
> > I have no idea what you mean here. Can you provide a simple test patch?
> 
> or a video?

or both.

videos are nice to get an idea what the original poster actually means, but a patch to reproduce the problem makes it far easier to test whether the problem was actually fixed.

so: a video is not a replacement for a patch.

**Comment by bmitc** [comment]
Issues are usually interpreted as being a specific case, unless otherwise specified. So when someone says it doesn't work, they mean for them. By square, I meant a square object when using Gem.

However, in this specific case, I did indeed make a mistake by confusing edit and run mode, the intended behavior of the number box, and the fact that in edit mode you can still get the run mode behavior if clicking a number box while holding down `ctrl`. Apologies for that. However, I have still had issues with the second and third bullet points. The third one requires a sketch to be closed and re-opened, since a number box becomes unmovable (via a drag of the entire node) in the sketch when in edit mode, but it is entirely intermittent and is infrequent. The second one may be due to Gem.
