### ISSUE TITLE
"pd -help" produces no output, version 0.51-4 / Win7

### ISSUE THREAD

**Issue by WilliamAHuston** [pure-data/pure-data#1280]
This produces no output:
C:\Program Files\Pd-0.51-4\bin>pd.exe -help

Windows 7.  

Thanks you,
BH

**Comment by umlaeute** [comment]
is there a `pd.com` file?
if so, use that instead of the `pd.exe`

**Comment by Spacechild1** [comment]
@WilliamAHuston I assume you are using `cmd.exe`? That would explain the problem. When you open a "windowed" application in `cmd.exe`, it detaches the process and returns to the console immediately. As a consequence, you don't see any output. You have to run `pd.com`, like @umlaeute suggested.

I always use a Msys2 shell, where `pd.exe` happily prints to the console, so I have long wondered why `pd.com` is necessary at all :-)

**Comment by WilliamAHuston** [comment]
Thanks, Let me try that. **If it works I will close.** 

PS: I have always used pd.exe on Windows. 
Seems like this is something new.

**Comment by WilliamAHuston** [comment]
Works, thanks. Closing.
