### ISSUE TITLE
Samplerate mess when using JACK

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1283]
The "Audio Settings"-dialog from menu "Media" -> "jack" shows buttons for changing samplerate. However, Pd cannot effectively change samplerate when using JACK as audio backend since jack clients "inherit" the samplerate defined by the JACK server. Changing the samplerate in the dialog seems to affect Pd's notion of its own samplerate. For instance, when JACK is running at 44.1k and 48k is set and applied in the dialog, the test tone is played at a slightly lower pitch. When switching to 96k, it drops by one octave. To make matters worse, the object [samplerate~] still reports the samplerate JACK server is running with. See attached screenshot.

I propose to simply disable the samplerate buttons in the 'jack' dialog. This setting makes only sense for other back-ends. By no way should Pd be allowed to change its (perceived) samplerate when using JACK. 

![pd-jack-samplerate-bug](https://user-images.githubusercontent.com/333373/110215434-1b26cd80-7eaa-11eb-85d5-90565fe6870d.png)

**Comment by mxa** [comment]
This would be solved the most elegantly by placing a drop down menu for the backend on top and below only showing the options which the selected backend allows.

**Comment by mxa** [comment]
Related: https://github.com/pure-data/pure-data/issues/717

**Comment by danomatika** [comment]
Implemented in #1287.
