### ISSUE TITLE
Changing "Delay (msec)" in JACK audio dialog doesn't have any effect

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1288]
Changing the value in the JACK dialog doesn't seem to have any effect on the latency added by Pd. It turns out that this is a bug and also when using JACK as backend a ringbuffer with a settable size is used. However, there is a bug in the code, as Milller pointed out here: https://github.com/pure-data/pure-data/pull/1287#issuecomment-800693766

**Comment by umlaeute** [comment]
with the "JACK audio dialog" you mean the standard audio dialog with JACK as the (otherwise selected) backend, right?

**Comment by Spacechild1** [comment]
Fixed in Pd 0.52-1
