### ISSUE TITLE
oscformat: type blob skips the first byte

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1292]
[oscformat] "eats" the first byte of a blob-type argument. In order to check whether the eating happens on the [oscformat] or the [oscparse] side, I added equivalents from the osc library for comparison in the attached patch illustrating the problem.

```
#N canvas 524 155 573 385 10;
#X declare -path osc;
#X obj 39 80 oscformat -f b blob;
#X msg 39 54 97 98 99 100 10;
#X obj 23 17 declare -path osc;
#X obj 233 83 packOSC;
#X msg 233 49 sendtyped /blob b 97 98 99 100 10;
#X obj 39 221 list trim;
#X obj 39 244 route blob;
#X obj 39 198 oscparse;
#X obj 230 194 unpackOSC;
#X obj 230 217 routeOSC /blob;
#X obj 133 145 t a;
#X obj 39 267 print [oscparse];
#X obj 230 263 print [unpackOSC];
#X connect 0 0 10 0;
#X connect 1 0 0 0;
#X connect 3 0 10 0;
#X connect 4 0 3 0;
#X connect 5 0 6 0;
#X connect 6 0 11 0;
#X connect 7 0 5 0;
#X connect 8 0 9 0;
#X connect 9 0 12 0;
#X connect 10 0 8 0;
#X connect 10 0 7 0;
```

**Comment by umlaeute** [comment]
quoting the documentation:
> Blobs are given as an atom count followed by that number of elements.

so your msg `[97 98 99 100 10(` is really interpreted as "here comes 97 blog bytes: 98 99 100 10".
only 4 numbers follow, so obviously there are 93 bytes missing (and `[oscformat]` fixes this without complaining)

at first glance i thought this is bogus (the blob size can be inferred from the Pd-message), but on second thought i think the `[packOSC]` implementation is to blame here, as it enforces a maximum of one blob per message and it MUST be the last element - something that does not align with the OSC-specs.

if you don't want to count the number of bytes, you can use a wildcard:

> [...] If the count is negative, the entire remaining message is included in the blob

**Comment by reduzent** [comment]
OK. Thanks for the clarification and sorry for the noise.
