### ISSUE TITLE
request: add port as an argument for [netsend]

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1301]
this would be because [netreceive] accepts this, so it is intuitive and consistent

**Comment by reduzent** [comment]
I don't think your reasoning makes sense. Also, I challenge your notion that this would be consistent and intuitive. [netreceive] uses the bind port as argument and it can listen to that port without requiring more information. But what should a [netsend 3025] do? Wait for a `connect netpd.org` message? Also, it would mess up the syntax of the `connect` method. Would a  `connect netpd.org` be valid if the port is already given as argument? If it is not specified as argument, would it create an error? 

I'm having a hard time seeing the consistency in this.

**Comment by porres** [comment]
> what should a [netsend 3025] do? Wait for a connect netpd.org message?

it should automatically connect to it at creation time

**Comment by porres** [comment]
>  don't think your reasoning makes sense.

it might really not :)

**Comment by reduzent** [comment]
> > what should a [netsend 3025] do? Wait for a connect netpd.org message?
> 
> it should automatically connect to it at creation time

To which host?

**Comment by Spacechild1** [comment]
@reduzent: I guess/hope @porres is talking about the *local* port.

You can already specify the local port with `[connect <remotehost> <remoteport> <localport>(`.

Adding the local port number as an argument is not necessarily a bad idea, but I'm not sure if it's very useful in practice. `[netreceive 9999]` makes sense because the object will immediately start to do its work. With `[netsend 9998]` you would still need to send the `[connect(` message, so you can just as well pass the port number there...

**Comment by porres** [comment]
> @reduzent: I guess/hope @porres is talking about the local port.

yup

>  With [netsend 9998] you would still need to send the [connect( message for it to do anything
> useful, so you can just as well pass the port number there...

then I'm overseeing this, I had the idea we could force a connection at creation time

**Comment by Spacechild1** [comment]
>  I had the idea we could force a connection at creation time

Without a remote host+port? We *could* allow to pass a hostname + (remote) port as creation arguments, but that would be a different feature request...

**Comment by porres** [comment]
> Without a remote host+port?

not sure I follow and my knowledge is limited, so... 

Anyway, Max's [udpsend] ip or host name (i.e. localhost) and port. I thought we could have the localhost by default and set a port. I got the idea that's how Pd's [netreceive] works (localhost by default and you also set a port# as argument). But I might be overseeing something... or just not getting it

**Comment by Spacechild1** [comment]
>  that's how [netreceive] works (localhost by default and you also set a port# as argument).

No. The default IP address of `[netreceive]` is the "any" address (`0.0.0.0` with IPv4 or `::` with IPv6). However, it's also possible to specify a multicast address or network device address, either as a second creation argument or as a second argument for the `[listen(` method. The port argument is the port it binds to.

`[netsend]` connects to another socket and for this it needs to specify the remote host and remote port. Additionally, you can specifiy the local port, so the other end can know in advance where to send messages (it doesn't have to wait for a packet to find out your port number).

> or just not getting it

Rather this :-) You can read some tutorials on how sockets work, then everything will become clearer.

Would you mind if I close this feature request?

**Comment by porres** [comment]
go ahead and close it then, I had it comming ;) 

 > The default IP address of [netreceive] is the "any" address (0.0.0.0 with IPv4 or :: with IPv6).

should we put this in the documentation?

**Comment by Spacechild1** [comment]
> should we put this in the documentation?

It already says: "by default, netreceive listens on all IPv4 and IPv6 interfaces". This is achieved by binding to the "any" address, but that's a technical detail not worth explaining.
