### ISSUE TITLE
[route] documentation

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1302]
It says that "With zero or one argument, route sprouts an inlet to set the argument (which may be float or symbol)."

This is wrong or misleading, it leds you to believe you can set the argument to either a float or a symbol, but that's not true.

First, if no argument is given, then you have "0" as a default argument, so if you send a message "0 1 2", you get "1 2" in the left outlet.

Secondly, it only lets you set to a symbol if you have a symbol as the argument, and by default you have a float (0).

While we're at it, I'll just ask, was it really an overlook and mistake the fact that [route list] will trim the list selector? Cause that doesn't happen for [route symbol]. I know I'm stepping now on delicate ground. Is it a bug? Should it be fixed? I'm always up for fixing, even if we need those compatibilty flags. I also understand how problematic this can be and it should just stay that way. Well, nonetheless, one way or another, we should document this on the help file.

**Comment by umlaeute** [comment]
> Cause that doesn't happen for `[route symbol]`.

*this* is what bothers me a lot. couldn't we just make `[route]` consistently strip whatever selector matches?

**Comment by porres** [comment]
> couldn't we just make [route] consistently strip whatever selector matches?

yeah, that makes total sense actually :)

**Comment by sebshader** [comment]
Imo there should be a non-stripping and a stripping route (or maybe a flag?). Because there are so many cases where you want to route by type but don't want to trim the selector.

**Comment by umlaeute** [comment]
> there are so many cases where you want to route by type but don't want to trim the selector.

how many? i counted and i came up with exactly 2 (two). then i counted again, and it was only 1 (one!).
and adding a `[symbol]` object puts the selector back in again.

or do you want something like zexy's `[relay]`? (i obviously see a need in such an object, or else i wouldn't have coded it).
i probably misunderstand the "route by type" - the only *types* i know in Pd are `symbol`, `float` and *pointer*, and only the first two are actually routable.

finally: a flag? `-k` for **k**eeping the selector? as in (scr):

~~~
[-h 0.5(
|
[route -k -h -b]
|
k? h?
~~~

**Comment by porres** [comment]
> Imo there should be a non-stripping and a stripping route (or maybe a flag?). Because there are so many cases where you want to route by type but don't want to trim the selector.

I think the idea that route does routing by message type is actually something that abuses the actual functionality of the object (which is getting rid of the first element in a message and pass the rest), and hence it doesn't work that well.

I know this is in the documentation to give an idea that it is good for that, and it works great for floats and symbols, but it doesn't work for lists, and when it fails to do so right there, then it's just no good for this purpose. This is also why I coded an object for else name [routetype], which really works for this task and you can also ask it to route an "anything" message and a "pointer", besides "list", "float", "symbol". I also have [routeall] object which is kinda like relay, and that means it serves a different purpose than [route].

So, I don't know who put this in the documentation and why, but the description of the object is still "route messages according to their first element", and I guess we should just stick to this idea and objective. Routing types, routing the whole message would be something else.

And well, as IOhannes pointed out, the idea that symbol messages go through with its selector intact is the odd one out. It is an exception in the whole structure of [route]. It should really only work for floats or lists of floats, but that's not because of the object, but the fact that Pd doesn't get rid of these selectors in any way. So it's more of a syntactic idiosyncrasy than a feature of [route], and yeah, people may abuse it, but that's something else.

**Comment by sebshader** [comment]
> or do you want something like zexy's `[relay]`? (i obviously see a need in such an object, or else i wouldn't have coded it).

yes, that's it exactly. relay should be in vanilla.

but I do feel that there's a difference between trimming a selector and trimming the message itself. (however route is still inconsistent if that's the case)

**Comment by porres** [comment]
> but I do feel that there's a difference between trimming a selector and trimming the message itself. (however route is still inconsistent if that's the case)

I don't get it. Technically, I believe the selector is the first element in a message. In this sense, [route] trims the selector and passes the message through, but fails to do so in the case of floats and list of floats (for reasons beyond its capabilities and that I already mentioned). 

So, "ms 500" is a message whose selector is "ms" and route trims it and sends "500" through.

And yes, it is inconsistent in the case of "symbol hi", for example.

So, anyway, what do you people think we should do?

**Comment by Spacechild1** [comment]
> So, anyway, what do you people think we should do?

Document it and move on. There's no way to fix how [route] deals with symbols without many breaking existing patches.

**Comment by porres** [comment]
> Document it and move on.

my take on this whole mess

<img width="1184" alt="Screen Shot 2021-04-19 at 00 40 51" src="https://user-images.githubusercontent.com/5360142/115178573-f6786500-a0a7-11eb-8c32-9d8cad9eade5.png">

<img width="1102" alt="Screen Shot 2021-04-19 at 00 40 56" src="https://user-images.githubusercontent.com/5360142/115178606-0a23cb80-a0a8-11eb-9ce1-c1facfd2a660.png">

**Comment by umlaeute** [comment]
@porres a few notes on your improved help patch:

- as you are adding a `[list]` object to "give back the 'list' selector", you might as well add a `[symbol]` object to "give back  the 'symbol' selector - just in case". obviously this is not strictly needed; but it's at least a way to pretend that `[route]` is behaving consistently. i think your patch already clearly documents the inconsistency of `[route symbol]`, so there's no reason to further dwell on this issue.
- "the 'bang' message is another special selector" - in which sense is it special *in this context*?
- regarding the matching of a selector-only message (lower right corner). you say "In a sense it outputs a zero element list and that becomes a bang". the "in a sense" somehow implies to me that _outputting a zero-element list_ is "just one way to see it, and there are other more correct ways". but of course this is not true, as a zero-element list is exactly what is output, though "in a sense this becomes a bang".
- oh and: execption vs exception.

**Comment by porres** [comment]
> as you are adding a [list] object to "give back the 'list' selector", you might as well add a [symbol] object to "give back the 'symbol' selector - just in case". obviously this is not strictly needed; but it's at least a way to pretend that [route] is behaving consistently. i think your patch already clearly documents the inconsistency of [route symbol], so there's no reason to further dwell on this issue.

I don't get the bottom line here, but yeah, I've pointed the inconsistency so I guess we're good here?

> "the 'bang' message is another special selector" - in which sense is it special in this context?

Yeah I haven't mentioned how it is special, neither in general and what happens here. I thought it'd be too much information. So it's meant as a general remark, as "bang is a special selector, and it can also be used in route", I didn't want to go beyond that. And by being a "special selector", it can't really take anything else as the rest of the message. Of course you know that! Do you think I should also mention it? Like, how it can't have extra elements and that a "bang" is sent as the result?

> regarding the matching of a selector-only message (lower right corner). you say "In a sense it outputs a zero element list and that becomes a bang". the "in a sense" somehow implies to me that outputting a zero-element list is "just one way to see it, and there are other more correct ways". but of course this is not true, as a zero-element list is exactly what is output, though "in a sense this becomes a bang".

I'm not sure. follow this and I don't really know how you want me to rephrase this. Just give me the modifications and I'll do it ;)

**Comment by umlaeute** [comment]
> I don't get the bottom line here

the suggestion was, to put a `[symbol]` object after the symbol-outlet, just like with `[list]`.

> bang is a special selector...

i just would drop the entire sentence about being special. it doesn't add any value to understanding `[route]`.
also the sentence about *abusing*: there's no abuse here, this is just how it works.

with the additional screen estate i would re-arrange the msgboxes by (implicit) selector, so that `[list x y z(` and `[1 2 3(` are grouped together, and `[5(` and `[float 3.14(`

> Just give me the modifications

maybe something like: "_It outputs an empty list, which corresponds to a bang-message_".

**Comment by porres** [comment]
> the suggestion was, to put a [symbol] object after the symbol-outlet, just like with [list].

but I don't get it, you also mention how this is unnecessary, which I agree and I also explain that in the documentation

**Comment by porres** [comment]
I made some of the suggested changes and also put examples on how to use [list trim] 

see 
<img width="382" alt="Screen Shot 2021-05-18 at 22 25 49" src="https://user-images.githubusercontent.com/5360142/118743095-1080a100-b828-11eb-8681-96f81b530376.png">
<img width="248" alt="Screen Shot 2021-05-18 at 22 25 54" src="https://user-images.githubusercontent.com/5360142/118743110-16768200-b828-11eb-83df-d91d743ed8c2.png">
