### ISSUE TITLE
Right-click menu disappears/strange mouse behavior occurs when moving canvas windows to different monitor/desktop (MacOS)

### ISSUE THREAD

**Issue by thouldcroft** [pure-data/pure-data#1303]
I've come across a strange behavior with canvas windows when moved to a different desktop/monitor on MacOS. I discovered this when moving Pd windows to a different monitor for teaching. When you move the window to a desktop/monitor that the program didn't originally open on, you lose the ability to right-click on an object and choose from the pop up menu. When the window gets moved back to the original screen, the mouse appears as if you are click-holding and creating  a selection rectangle when you move the mouse into the window, however, right-click functionality still works on the original desktop/monitor. 

Interestingly, if you tell Pd to open on the other desktop/monitor, the right-click functionality works; so only when moving the canvas window to a desktop/monitor that Pd didn't originally open on, does this problem happen.

**Comment by emviveros** [comment]
I can confirm this misbehavior in MacOS 10.13.6 using Pd 0.51-4

**Comment by umlaeute** [comment]
could you please perform some testing, with the following patch, e.g. `test.pd`?

~~~
#N canvas 889 157 450 300 12;
#N canvas 5 51 450 300 test 0;
#X restore 180 162 pd test;
~~~

- start Pd from the cmdline using something like `/Applications/Pd-0.51-4.app/Contents/Resources/bin/pd -d 3 test.pd 2>pd.log`
- right click the `[pd test]` subpatch
- close Pd

this will write a file `pd.log` that contains a lot of debugging information. please follow the steps above exactly an ddon't do anything more (the file is full of stuff, and it's already hard to find the relevant information).

repeat the procedure on the "other screen" (make sure to not overwrite the original `pd.log` file, by either renaming the first or using another name of the second run).

in the end you should have two logfiles, one where right-clicking did work, and one where it did not.
(clean the two files of uninteresting information,) zip them and post them here.

**Comment by thouldcroft** [comment]
I've never created a Pd log before, so I wasn't quite sure what data to clear, the two logs seem to be identical up to `pdtk_canvas_getscroll .x10072fcc0.c` so I cleared everything before that.
[Pd-Logs.zip](https://github.com/pure-data/pure-data/files/6367404/Pd-Logs.zip)

**Comment by emviveros** [comment]
[pd.log.zip](https://github.com/pure-data/pure-data/files/6370079/pd.log.zip)

**Comment by umlaeute** [comment]
thanks for the logs.

it seems like Pd is opening the right-click menu, but somewhere off screen.
(at least on Linux, I can use the Up- and Down- keys to navigate the right-click menu and <kbd>Return</kbd> to execute the selected action).

so here's another thing you can do to help debug this. add the following three lines to the `tcl/pdtk_canvas.tcl` file (hidden somewhere in the .app folder):

~~~diff
diff --git a/tcl/pdtk_canvas.tcl b/tcl/pdtk_canvas.tcl
index e374f5f7..ad22b9bc 100644
--- a/tcl/pdtk_canvas.tcl
+++ b/tcl/pdtk_canvas.tcl
@@ -283,6 +283,9 @@ proc ::pdtk_canvas::pdtk_canvas_popup {mytoplevel xcanvas ycanvas hasproperties
     # window, and subtract the area that is obscured by scrolling
     set xpopup [expr int($xcanvas + [winfo rootx $tkcanvas] - $left_xview_pix)]
     set ypopup [expr int($ycanvas + [winfo rooty $tkcanvas] - $top_yview_pix)]
+    ::pdwindow::post "popup $mytoplevel $xcanvas $ycanvas +${xpopup}+${ypopup}\n"
+    ::pdwindow::post "popup [wm geometry $mytoplevel] [winfo geometry $mytoplevel] [winfo geometry $tkcanvas]\n"
+    ::pdwindow::post "popup ${scrollregion} / [$tkcanvas xview] / [$tkcanvas yview] / [winfo rootx $tkcanvas] / [winfo rooty $tkcanvas]\n"
     tk_popup .popup $xpopup $ypopup 0
 }

 ~~~

then run Pd (like normal by double clicking on the icon; no need to run from the cmdline or similar), and trigger the right-click menu. you should get a 3 line printout on the Pd-console (with a `popup` prefix). repeat this for the *other* case. post the 6 lines here.

**Comment by thouldcroft** [comment]
Here is what I get in the pd console:

`popup .x100322770 202 77 +2059+83
popup 450x300+1857+-16 450x300+1857+-16 450x300+0+0
popup 0 0 450 300 / 0.0 1.0 / 0.0 1.0 / 1857 / 6
popup .x100322770 196 75 +434+381
popup 450x300+238+284 450x300+238+284 450x300+0+0
popup 0 0 450 300 / 0.0 1.0 / 0.0 1.0 / 238 / 306`

**Comment by umlaeute** [comment]
@thouldcroft  which 3 lines correspond to the working right-click menu, and which to the other?

**Comment by thouldcroft** [comment]
Sorry about that, I ran the test again and these were the results:

On the desktop/monitor that right-click _works:_
popup .x10040f2d0 155 58 +2905+-129
popup 450x300+2750+-209 450x300+2750+-209 450x300+0+0
popup 0 0 450 300 / 0.0 1.0 / 0.0 1.0 / 2750 / -187

Canvas window: top right corner of the screen.

On the desktop/monitor where right-click _doesn't_ work:
popup .x10040f2d0 155 59 +985+104
popup 450x300+830+23 450x300+830+23 450x300+0+0
popup 0 0 450 300 / 0.0 1.0 / 0.0 1.0 / 830 / 45

Canvas location: top right corner of screen.

**Comment by umlaeute** [comment]
hmm, that looks pretty sane (though it seems your right monitor extends above the left one, which is a bit confusing).

unfortunately this is bad news, as it indicates that everything works as it should and your problem is *probably* a Tcl/Tk bug.

**Comment by thouldcroft** [comment]
@umlaeute not sure if this helps in any way, but to clarify my monitor situation (so you don't think its an additional bug), my two monitors are a laptop and an external monitor, so I have the two screens positioned with the left monitor (laptop) lining up approximately with the _bottom_ of the right monitor, so when the mouse and/or windows move from one to the other, their place on screen is close to a straight line.

**Comment by umlaeute** [comment]
thanks for clarfying. that at least removes the confusion about the negative coordinates.

i guess i just need to get a mac with a second monitor.
or just ping @danomatika ;-)
(alternatively: @Spacechild1 do you still have a mac lying around?)

**Comment by Spacechild1** [comment]
> (alternatively: @Spacechild1 do you still have a mac lying around?

I will give it try the next time I'm opening my Mac (which I try to avoid as much as possible)

**Comment by danomatika** [comment]
>(which I try to avoid as much as possible)

*Thanks for that. :P*

I guess I will try to look at it later tonight. It's most likely a bug with Tcl/Tk which will take an inordinate amount of time to fix with a custom patch or, hopefully, it's an issue that's fixed upstream in Tk 8.6.11+.

**Comment by danomatika** [comment]
@thouldcroft What macOS version are you using? Is this the precompiled version of Pd or did you build it yourself / customize it?

I tested on macOS 10.14.6 with Pd 0.51-4 and I see no issues: right-click popup appears as expected, both on "Built-in Retina Display" and an external monitor, in this case an old Apple Cinema Display. I tried my usually configuration of laptop left, external right as well as laptop bottom and external top.

This could be a case where older systems, maybe 10.13 or older, work better with an older version of Tk? Dunno.

**Comment by danomatika** [comment]
Ok, testing on macOS 11.3 with Pd 0.51-4 does show the issue: right-click over canvas windows on the external monitor are rendered somewhere offscreen.

@sebshader As you've built & tested PD with Tk 8.6.11+ on macOS, have you seen this issue? Maybe it's already fixed upstream (hopefully).

**Comment by thouldcroft** [comment]
@danomatika sorry I missed this mention. I am on MacOS 10.14.6, and I am using the precompiled version of Pd, without any Tk/Tcl plug-ins running.

**Comment by sebshader** [comment]
@danomatika I just have a laptop, not sure if I can get it hooked to another monitor easily rn.. I will say that I've noticed the right-click menu opening in odd places occasionally I think but it's always on the screen.
but I'm on 10.14.6 so I'm not sure I'd see it anyways (sounds like it only occurs <= 10.13)

**Comment by danomatika** [comment]
>(sounds like it only occurs <= 10.13)

Actually, I *do not* see the issue on my 10.14 system but I *do* see it on my 11.3 system. Both using the same monitor and arrangement.

**Comment by thouldcroft** [comment]
I don't see the issue on 10.14.6 using Pd 0.52.0test posted on Miller's website.

**Comment by sebshader** [comment]
@thouldcroft no-one has seen the issue on 10.14.6. So far the affected OSes are MacOS 10.13 and MacOS 11

**Comment by Garrettlynch** [comment]
Sorry to say I've experienced the same issue, same scenario today teaching Pd. I AM on Mac OS X 10.14.6 and using Pd 0.51-4 - there seem to be other significant issues with Pd 0.52.0 on OSX 10.14 (unstable, crashing) so I was obliged to drop back a version. The right click menu works without issue in the main default laptop screen but in the external monitorit does not appear.

**Comment by Garrettlynch** [comment]
Both run on 10.14.6 but both produce the same error of no visible right-click menu. Curiously the menu seems to be interactively there, if you right click and then click where the menu should be help does open, just not visually there.

**Comment by tremblap** [comment]
just a quick note to say I could swear it was working on my other machine (same os (catalina) same version (52-1-really) but now I have that problem. My second screen is above the main one and on this machine i didn't disable the 2nd menu bar, and that is about all the difference. I hope this helps

**Comment by umlaeute** [comment]
i think i've found it:

it seems that on macOS, `menu` items can only be shown on the screen where the associated toplevel window resides.

we are using a common `.popup` menu for all windows, but this `.popup` menu is associated with the toplevel `.`, which (i guess, as we actually do not display it) resides on the primary screen.

so the solution is to use separate per-window menus.

**Comment by danomatika** [comment]
That makes sense. Is it much overhead to do this? I  ant imagine so… There could be a local bar for each window which can be set to the global instance on other platforms and a local instance on mac.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by umlaeute** [comment]
> Is it much overhead to do this?

https://git.iem.at/pd/pure-data/-/tree/bugfix/context-menus has a tentative fix which i'm going to push to `develop` once i have confirmed that it works on macOS.

**Comment by umlaeute** [comment]
tested on `macOS Monterey 12.5.1` with both arm64 (native) and amd64 (rosetta), and right-click now seems to work. i've submitted a fix to the `develop` branch.

**Comment by goldTongue7** [comment]
Here the solution i think(for mac)
mac system preferences > displays > arrangement >relocate menu bar(to external monitor)

it's done

**Comment by umlaeute** [comment]
@goldTongue7 i'm not sure i can follow: the problem should be (i daresay: is) fixed in the current `master` branch of Pd.
the fix will be part of the next release (without the need for any workarounds on the user's side)
