### ISSUE TITLE
consistency check failed: signal_free 4

### ISSUE THREAD

**Issue by dylanandhunter** [pure-data/pure-data#1307]
Using a PC with Windows 10, but started the patch on a desktop running Windows 8. Mainly a Mac user, so please forgive my inexperience with Windows, in advance. I get this error consistently from the moment that the DAC is turned on, and then subsequently, as I do just about anything else in the patch, especially when deleting objects. There is a good deal of code that I didn't write in my patch, and I have a suspicion that the error may have to do with data from either Touch Designer or the XBOX Kinect camera that the patch is communicating with, but I have scoured the whole thing, and then subsequently the internet, for any idea of "signal_free 4" or even "consistency check failed" and have been totally unsuccessful in finding any pertinent information to help me solve the problem. It really doesn't seem to be doing anything detrimental to the function of my patch, but it is annoying to keep getting an unknown, unsolvable error. I'm including a copy of my patch to see if someone else gets the same message. I saw some mention to "consistency check failed" being a bug many years ago, with a response from Miller Puckett to someone's troubleshooting question, in which he said as much, but then the thread stopped in 2015 and nothing else has been said about it. Thanks!

[DH-Kinect2OSC-bugger.zip](https://github.com/pure-data/pure-data/files/6412016/DH-Kinect2OSC-bugger.zip)

**Comment by umlaeute** [comment]
the patch seems to be buggy in a way that is not possible to create with normal means of patching (at least it should not).

in the `[pd sampler]` subpatch, the `[tabplay~ sf14]` is doubly connected to `[throws $0-dac]` (on the left side of the patch).

remove the double-connection, and see how you fare (and report back).

**Comment by dylanandhunter** [comment]
Amazing! That worked. It was an old piece of unused code up in the corner, anyhow, so I just got rid of it, and it seems to have cleared up the issue. Thank you so much
