### ISSUE TITLE
[pipe] issues

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1312]
**flush message:**

The flush message outputs data not in the incoming order, that is "first in / first out", but the opposite (last in / first out).

I think that a FIFO order makes sense here.

**symbol:**

It says it takes symbols, even though it is untested, well, it doesn't :) (I haven't tried pointers).

**bang:**

there's no bang method documented, but it works by outputting the last float that was output. I would actually like a bang method and that the bang messages would be output. So here we have two things either:
- include the feature request for a bang methof
- remove the bang functionality

**Comment by umlaeute** [comment]
please don't file multiple issues in a single report, even if all of them occur in the same version of Pd.
use separate issues, so they can be solved separately.

> It says it takes symbols, even though it is untested, well, it doesn't :)

i don't know how you tested, but here it works fine.
i think the UNTESTED only refers to pointers (and pointers are a fickle thing if you store them at some place and use them later)

> there's no `bang` method documented

`[pipe]` works very similar to `[pack]`.
there's no specific `bang` method in either of them, but when banged, both will just resend the last message to their inner workings and do something with it (in the case of `[pack]`, output the list immediately; in the case of `[pipe]`, output the list after a delay).

`[pipe]` also guarantees type safety (just like `[pack]?), so a `[pipe f 100]` will *always* output a number and never a symbol nor a bang.
so the feature request doesn't make sense.

i think the best would be to just document the current behaviour and not change it.
