### ISSUE TITLE
online documentation of [expr] is outdated / use [pdcontrol] to open the html

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1327]
[expr] links to an outdated online documentation [link](http://yadegari.org/expr/expr.html) that doesn't include the new stuff from version 0.5+

We can also use [pdcontrol] to open the html file from within pd like [slop~]

**Comment by porres** [comment]
ping @Lucarda

**Comment by Lucarda** [comment]
I'd converted http://yadegari.org/expr/expr.html to an .md file:

[expr.md.zip](https://github.com/pure-data/pure-data/files/6564480/expr.md.zip)


May be you can include all the Version 0.57 info in the .md file and upload it here.
Then I convert the .md to html and include it in `pure-data/doc/8.topics/` whith a [pdcontrol] thing?

**Comment by porres** [comment]
here you go @Lucarda 

[expr.md.zip](https://github.com/pure-data/pure-data/files/6567228/expr.md.zip)

**Comment by porres** [comment]
> Then I convert the .md to html and include it in pure-data/doc/8.topics/ whith a [pdcontrol] thing?

send me the html and I can do it

**Comment by Lucarda** [comment]
[expr-hml.zip](https://github.com/pure-data/pure-data/files/6567328/expr-hml.zip)

**Comment by porres** [comment]
File has changed a bit but it's fine I guess. Can we at least keep the header, with links to the actual internet site? Then we could give sharok the same file too so he could replace it online (if he changes on top of it and updates, we get that back too) - sound like a plan?

<img width="669" alt="Screen Shot 2021-05-31 at 00 21 48" src="https://user-images.githubusercontent.com/5360142/120138748-82a0a080-c1ad-11eb-8dd9-9408c859f8fe.png">

**Comment by Lucarda** [comment]
see this:

[expr-html-v2.zip](https://github.com/pure-data/pure-data/files/6568541/expr-html-v2.zip)
