### ISSUE TITLE
tcl unhandled error when asking for properties of cnv-object

### ISSUE THREAD

**Issue by rolfmeesters** [pure-data/pure-data#1336]
hi,
windows 10 Pd 0.51.3 (64)
attached a patch demonstrating the error,  a picture of the pd-console and the text.
it happens when doing a right-click on the canvas, then asking for properties.

rolf
[tcl-error.zip](https://github.com/pure-data/pure-data/files/6585748/tcl-error.zip)

**Comment by porres** [comment]
this is a known bug, a duplicate issue, and we already have a fix for this, see https://github.com/pure-data/pure-data/pull/948

**Comment by umlaeute** [comment]
just for the sake of completeness:

the original report is actually #880
(#948 contains a fix for it)
