### ISSUE TITLE
Feature Request: methods to delete some line inside a message and insert anywhere

### ISSUE THREAD

**Issue by abreubacelar** [pure-data/pure-data#1337]
Hello, it is possible to create new methods delete and insert for messages? this could work as this:

in a message like:

first;
list foo bar;
42;

if i send delete 0, it would delete the first line:

list foo bar;
42;

delete -1 could behave as in text object deleting everything (a duplicate of an empty "set" method, but to keep consistent)
and a delete N with N bigger than what the message has would delete the last line

insert could add the line somewhere, acting as a special add (that only inserts at the end)

so insert 0 something, would insert in the start, and insert N, is somewhere, if N is bigger then the whole message, it inserts in the end just like normal add

I want this because thinking about #1325 and the documentation ideas, there is a simple way of creating a "pd console" inside a pd patch using the add method and set method from messages. This is nice, but after some lines this gets big, and the only option is to delete everything with set.

So i came with an idea of using text object to actually hold the lines and reset one external message like the video attached. 

https://user-images.githubusercontent.com/16086370/120809497-80797180-c520-11eb-9146-e581c83dcfef.mp4

the problem is that in this way you have duplicates of data (inside the text) and i need to delete everything with "set" before "reprinting" the lines, using until... if message had a method for delete and insert, this could be easier, both to mimic pd console print and to print in reverse order (the last message received being inserted in the start)

(btw the patch that generated that video, just for demo purposes:)

[consoleLike.zip](https://github.com/pure-data/pure-data/files/6598837/consoleLike.zip)

**Comment by porres** [comment]
what about using [text]? seems like a job for that object

**Comment by abreubacelar** [comment]
> what about using [text]? seems like a job for that object

and i am using text to do that example, but as i said, i thought about what @emviveros said in https://github.com/pure-data/pure-data/issues/1325#issuecomment-849023021 so this could be an alternative to creating another object to show anythings or print to pd console, and may be useful in other situations to edit messages created dynamically (using add, set etc) 

you can do this with text, and show it in another window (and text have click method, so you could popup it to bring attention to it if needed), or you can do what i did, but i thought that maybe messages having these methods this would be more efficient than what i did (no duplicates, and no iterating through lines from text to reprint the data in the message), so instead of keeping track of each line inside a text object to then reshow them in a message, you could just delete or insert them directly in the message

**Comment by Spacechild1** [comment]
Message boxes are not really meant for display purposes. There's a reason why they don't show up in GOP patches.

I think you can achieve more useful results with a couple of `[cnv]` objects or with data structures.

**Comment by umlaeute** [comment]
i also think that the msgbox is already overloaded with much too much functionality, and we should striveto reduce its complexity rather than expand it.

**Comment by abreubacelar** [comment]
Ok! indeed i didn't thought about data structures, and yeah, we can draw text with it directly into canvas so it is already a solution for this, thanks for the idea!
