### ISSUE TITLE
Memory leak in osc~?

### ISSUE THREAD

**Issue by robertesler** [pure-data/pure-data#1355]
I may have missed something but I don't see a call to release the memory allocated by `cos_maketable()` in the [osc~] object in d_osc.c line 340.  In [cos~] there appears to be a class-level deconstructor `class_setfreefn(cos_class, cos_cleanup);` (line 234) which calls `freebytes(cos_table, sizeof(float) * (COSTABSIZE+1));` on line 226.  But I don't see this happening in [osc~].  
Unless there is some other backend call I'm not seeing in d_osc.c then this is probably a small memory leak.

**Comment by Spacechild1** [comment]
as you've discovered, `cos_cleanup` is already called when the "cos~" class is freed (which is guaranteed to happen). in fact, the call to `cos_maketable` in `osc_setup` is a bit redundant, as it is already called in `osc_maketable`, but it doesn't hurt.

**Comment by robertesler** [comment]
Ok, sounds good.  I didn't realize that the `class_setfreefn()` was called even if you never create a [cos~] object.

**Comment by Spacechild1** [comment]
yes, for internal objects like `[cos~]` the class setup and free functions are always called.
