### ISSUE TITLE
Gem MacOs Window

### ISSUE THREAD

**Issue by jva07** [pure-data/pure-data#1363]
Hi there, 
I´ve just have installed Pd-0.51-4 in and the extra GEM to work in previous patches with a MacBookPro M1, but in the console showed up a bug like that
[gemmacoswindow]: unable to switch to current window (do you have one?), cannot render!
I don´t know if I should install another version or there´s something wrong with the objets in the new release of Pd-0.51-4.
Thank you for your help!
<img width="1440" alt="Captura de pantalla 2021-07-24 a las 18 34 19" src="https://user-images.githubusercontent.com/5587298/126875145-22d67623-1343-423e-9a53-8d5c2474d4d4.png">

**Comment by umlaeute** [comment]
could you try with a different windowing backend?

1. locate the `gemdefaultwindow.pd` abstraction in the Gem/ folder and open it
2. change the `[gemmacoswindow]` object to one of the following:
    - `[gemglfw3window]`
    - `[gemglutwindow]`
    - `[gemsdlwindow]`
    - `[gemcocoawindow]`
3. save the patch and close it
4. open your main patch and see whether it now works
5. iterate over the options listed above until you have found one that works

**Comment by umlaeute** [comment]
sidenote: the issue-tracker for Gem is at https://github.com/umlaeute/Gem/issues/

i'm closing this.
if the above suggestions do not work for you, please create a new ticket in Gem's issue tracker (for whatever reasons I cannot move the issue there...)
