### ISSUE TITLE
Opening Pd document on Mac

### ISSUE THREAD

**Issue by mmturner2468** [pure-data/pure-data#1374]
After updating to version 0.51-4, I find that when I double click on a pd document (e.g., my_file.pd), the program opens the console but the patcher window itself does not. I need to double click the _my_file.pd_ document a second time for it to launch. 

Pd acts as expected once I've gotten the document open. 

I'm using: MacBook Pro (13 inch, M1, 2020), MacOS 11.5.2, Pd 0.51-4

Thanks for any help,
Mitch

**Comment by umlaeute** [comment]
> The resolution seems to be that this is an issue on macOS 10.15 but is fixed with newer versions of Tk and macOS 11:

hmm, i don't see this on macOS-10.15/Catalina with Pd-0.51-4: the patch opens just fine.

**Comment by danomatika** [comment]
I have a universal test build of (prerelease) 0.52-0 with TK 8.6.12:

http://docs.danomatika.com/pdbuilds/0.52/Pd-0.52-0-universal.zip

On my M1 MBP running macOS 11.6.1, I don't see this issue any more. It thankfully seems to have been fixed with 8.6.12.

**Comment by danomatika** [comment]
This should be fixed in Pd 0.52. Can you double-check and close this issue if everything is working?

**Comment by mmturner2468** [comment]
Hi, Dan. Yes, the Pd 0.52 fixed my issue. Will close the ticket today. 

Thanks for getting this solved.

— Mitch
