### ISSUE TITLE
new gatom crashes when sending data to receiver

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1392]
1. start Pd
2. start a new patch
3. create a list gatom with <kbd>Ctrl</kbd>+<kbd>4</kbd>
4. open it's preferences
5. type `foo` into the "Send symbol"
6. hit <kbd>Apply</kbd>
7. Click the gatom (and type something if you want to; but as of now this is not necessary)
8. Click besides the gatom
9. :boom:

**Comment by umlaeute** [comment]
only the `list gatom` is affected, `numberbox` is fine.

**Comment by millerpuckette** [comment]
yep.  Should be fixed now.

**Comment by umlaeute** [comment]
yes. (with a27ed2194b465279ed0679fe30707900feabe0ce i guess)
