### ISSUE TITLE
Pressed arrow keys enter into undo history cue even when nothing is selected

### ISSUE THREAD

**Issue by ulioidle** [pure-data/pure-data#1404]
This is somewhat annoying when working on patches which use the arrow keys, finding myself needing too undo a great deal to just undo that last change.

**Comment by Lucarda** [comment]
Can't replicate on Pd 0.51-4 on Windows.

I create a couple of objects and press the arrow keys and nothing happens. If I select the objects they move if I press the arrows. I can't undo or redo anything by pressing the arrows.

can you elaborate more?
