### ISSUE TITLE
pd 0.52test1 (ubuntu 20.04.3) random scroll bar glitches

### ISSUE THREAD

**Issue by abreubacelar** [pure-data/pure-data#1410]
i see these strange constant hide and show of the scroll bars when moving the mouse, it seems to happen when i go from one window to another or when in the same window the mouse passes over some objects and messages...  happens both in edit mode on and off

https://user-images.githubusercontent.com/16086370/138769154-64331edc-49f9-41cc-bd28-8faa6f08b8f1.mp4

**Comment by Lucarda** [comment]
The blinking scroll bar happens when the mouse cursor change its icon.

On Linux is more subtle than on Windows.

**Comment by Lucarda** [comment]
ping @Spacechild1 

can you confirm this on Windows?

**Comment by Spacechild1** [comment]
Can confirm! Very noticable.

**Comment by Lucarda** [comment]
This has to be looked deeply but i found that commenting

https://github.com/pure-data/pure-data/blob/master/src/g_canvas.c#L499

is a start. (also related to #1459)

**Comment by Lucarda** [comment]
this was introduced with https://github.com/pure-data/pure-data/commit/5462d1eae0ad9f139997d56d459c212e797d96be

ping @umlaeute

**Comment by Lucarda** [comment]
the issue is that we are having 4 `setbounds` for every `configure -cursor`


````
>> .x$? configure -cursor $$?

.x$? setbounds 104 104 554 404;
<<
.x$? setbounds 104 104 554 404;
<<
.x$? setbounds 104 104 571 404;
<<
.x$? setbounds 104 104 571 404;
````

**Comment by sebshader** [comment]
@Lucarda is the ::pd_bindings::patch_configure proc being called when the cursor is configured?

**Comment by Lucarda** [comment]
@sebshader if I add "foo 1" to `::pd_bindings::patch_configure`:

````
    pdsend "$mytoplevel setbounds $x $y [expr $x + $width] [expr $y + $height]"
    pdsend "foo 1"
````
I get 4 consecutive `1`'s on [r foo] each time there's a cursor change.

commenting out `scan [wm geometry $mytoplevel] {%dx%d%[+]%d%[+]%d} width height - x - y` I get same results.

**Comment by sebshader** [comment]
@Lucarda interesting. here on OSX the patch_configure isn't called on cursor change for some reason

**Comment by Lucarda** [comment]
@sebshader on Linux I get **2** consecutive `1`s

**Comment by umlaeute** [comment]
the actual commit that introduced this was 64300c8fe2da6c1db10fc905c33de868a0e37524

**Comment by umlaeute** [comment]
it seems that f909912 fixes this on my system.
(although the fix is more in the realm of WTF).

could someone confirm that the issue is gone in current `develop`?

**Comment by umlaeute** [comment]
> could someone confirm that the issue is gone in current develop?

at least under wine it seems that the problem is gone...

**Comment by Lucarda** [comment]
@umlaeute this effectively works on Linux but not on Windows.

I steel get 4 consecutive `setbounds`.

**Comment by umlaeute** [comment]
i do not care about getting 4 consecutive `setbounds` right now, but...do the "random scroll bar glitches" still occur?

**Comment by Lucarda** [comment]
> do the "random scroll bar glitches" still occur?

yes.

**Comment by umlaeute** [comment]
which system is this now? and which git-revision are you using?

**Comment by Lucarda** [comment]
Windows 10.
Build `develop` hours ago and manually apply `set geometry ${w}x${h}+${x}+${y}`

I just rebooted my system (same results).

**Comment by Lucarda** [comment]
This is what I get (Win10 amd64) with `pd -d 3`.

````
>> .xf9eca680 configure -cursor $cursor_editmode_resize
<<
.xf9eca680 setbounds 458 162 908 462;
<<
.xf9eca680 setbounds 458 162 908 462;
<<
.xf9eca680 setbounds 458 162 925 462;
<<
.xf9eca680 setbounds 458 162 925 462;
<<
.xf9eca680 motion 135.0 199.0 0;
<<
.xf9eca680 motion 134.0 199.0 0;

````

On linux I don't get any `setbounds`.

**Comment by Spacechild1** [comment]
I have to correct myself, the blinking scroll bars still appear under specific circumstances.

I still seem when following the instructions in https://github.com/pure-data/pure-data/issues/1410#issuecomment-951413044. Also when I switch between edit mode and run mode.

Curiously, this only happens if I *don't* change the canvas *width* after creating a new patch or loading an existing patch. After I change the width - even before creating any objects! - the flickering is gone!

**Comment by Lucarda** [comment]
> After I change the width - even before creating any objects! - the flickering is gone!

Good catch.

the consecutive `setbounds` are also gone from `./pd -d 3`.


> under specific circumstances

Uh, I forgot to tell that the window must had an scrollbar.

:)

**Comment by umlaeute** [comment]
> I still seem when following the instructions in https://github.com/pure-data/pure-data/issues/1410#issuecomment-951413044

actually those where the instructions i followed to confirm that the problem was gone.
anyhow, are there any other instructions (that don't require me to watch a video?)

> After I change the width - even before creating any objects! - the flickering is gone!

does it also work if you change the size of the window (after it was created) via some tcl/tk script?.
e.g. `wm geometry <winid> 320x240+200+200`

the fix in f909912 just adds the window size to the geometry, which somehow appears to make the problem go away.
however, it does that only when opening existing patches (that already have a window size stored) and not for new windows (<kbd>Ctrl</kbd>+<kbd>n</kbd>) (or was it the other way round?).
in any case, does this correlate with your experience?

if so (or not), does it help to change to:

~~~tcl
proc pdtk_canvas_place_window {width height geometry} {
    # read back the current geometry +posx+posy into variables
    set w $width
    set h $height
    if { "" != ${geometry} } {
        scan $geometry {%[+]%d%[+]%d} - x - y
        foreach {x y w h} [pdtk_canvas_wrap_window $x $y $width $height] {break}
        set geometry ${w}x${h}+${x}+${y}
    } else {
        set geometry ${w}x${h}
    }
    return [list ${w} ${h} ${geometry}]
}
~~~



> Uh, I forgot to tell that the window must had an scrollbar.

good point.
i'm sure the scrollbars flicker like mad on windows without them (check your process monitor)

**Comment by Lucarda** [comment]
On a fresh reboot today and opening `pd/develop` I find that the flickering is gone for "saved patches" but is there for "new patches".

replacing `proc pdtk_canvas_place_window` as shown above fixes the issue for "new patches"

:)

**Comment by Lucarda** [comment]
@umlaeute  please push to `develop` :

````
proc pdtk_canvas_place_window {width height geometry} {
    # read back the current geometry +posx+posy into variables
    set w $width
    set h $height
    if { "" != ${geometry} } {
        scan $geometry {%[+]%d%[+]%d} - x - y
        foreach {x y w h} [pdtk_canvas_wrap_window $x $y $width $height] {break}
        set geometry ${w}x${h}+${x}+${y}
    } else {
        set geometry ${w}x${h}
    }
    return [list ${w} ${h} ${geometry}]
}
````

**Comment by umlaeute** [comment]
ouch. forgot to push. now it's done

**Comment by danomatika** [comment]
Good fix on this. I remember fighting something similar years ago...
