### ISSUE TITLE
windows: 'make app' fails if not preceeded by 'make'

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1412]
this fails:

~~~sh
$ ./autogen.sh
$ ./configure
$ make app
~~~

whereas this seems to work:

~~~sh
$ ./autogen.sh
$ ./configure
$ make
$ make app
~~~

since `make` is *really good* at handling dependencies, it should be able to run `make app` without havign to run `make` (resp `make all`) first.

**Comment by umlaeute** [comment]
ah sorry. this is really about creating a macOS "App" bundle rather than creating a Windows bundle.

i've now added the correct tag...

**Comment by reduzent** [comment]
Why does the title of this issue begin with "windows:" then?

**Comment by umlaeute** [comment]
good question. i'll retract to my cell and meditate on that.

**Comment by reduzent** [comment]
:-)

**Comment by umlaeute** [comment]
hmm. meditating did not help.
i guess this is PEBCAK
