### ISSUE TITLE
[0.52-test1] [pd~] needs fix

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pure-data#1418]
On "Pd 0.52-test1" I'm getting no sound from [pd~] and in the console i get:

on Linux 
`pd~: short audio signals (sigs 0, fragment 0)`

on Windows
`pd~: short audio signals (sigs 1, fragment 0)`

**Comment by Spacechild1** [comment]
Here's a fix: https://github.com/pure-data/pure-data/pull/1427

Is this working fine now?

**Comment by Lucarda** [comment]
Yes.

:)

**Comment by Lucarda** [comment]
Closing as b774aae is on branch 'develop'
