### ISSUE TITLE
-stderr always prints messages with high verbosity

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1420]
even when `-noverbose` is given. This used to be not the case until quite recently. This is with 8897538f883c4bec907647989c1198a9ef9495d7, though I don't know exactly which commit introduced it. 

For  instance, when a patch using [tcpclient] from iemnet is loaded, `pd -stderr -noverbose` prints: 

```
tried /home/roman/Pd/externals/iemnet/tcpclient.l_amd64 and failed
tried /home/roman/Pd/externals/iemnet/tcpclient.l_ia64 and failed
tried /home/roman/Pd/externals/iemnet/tcpclient.pd_linux and succeeded
iemnet - networking with Pd: [tcpclient]
        version 0.3.0
        compiled on Jun  7 2021 at 21:49:46
        copyright © 2010-2015 IOhannes m zmoelnig, IEM
        based on mrpeach/net, based on maxlib
```

The `tried ... and failed` messages used to be printed only when `-verbose` was given.

**Comment by Spacechild1** [comment]
Good catch! Here's a fix: https://github.com/pure-data/pure-data/pull/1421

**Comment by Spacechild1** [comment]
fixed in latest master
