### ISSUE TITLE
Simplify audio settings menu

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#1423]
I think the design of the "Media" menu is a bit confusing. One the one hand, you have the "Audio settings" item which - as expected - opens the audio settings dialog. On the other hand, you have dedicated entries for each audio API, like "ASIO (via portaudio)" or "MMIO". Clicking on those will select the appropriate audio API and additionally open the audio settings dialog. This is quite redundant.

I think it makes much more sense to choose the audio API in the audio settings dialog itself. Here are the audio settings from REAPER, for example:

![grafik](https://user-images.githubusercontent.com/16126632/139532958-b448eca1-5026-482d-877a-478fc6877d4e.png)

**Comment by umlaeute** [comment]
ah well. in theory i agree.

in practice the apparent problem is that choosing a different audio backend requires changing of a lot of possible settings (available devices, immutable values...) which maps badly to the current implementation of the audio settings dialog.

i've been working on the dialog (using a single dialog for all major settings in #1397 (which would be a good place to integrate a change as desired by this issue)

**Comment by Spacechild1** [comment]
> in practice the apparent problem is that choosing a different audio backend requires changing of a lot of possible settings (available devices, immutable values...) which maps badly to the current implementation of the audio settings dialog.

I'm not sure I understand the issue. When you pick the API from a list box you would just have to refresh the dialog content... or you could simply destroy and recreate it.

BTW, #1397 looks cool! Will check it out.

**Comment by umlaeute** [comment]
right. i'm probably thinking too much in terms of "keeping the dialog open" while changing the backend (which is what i need for #1397).
if this is not a prerequisite, it's of course easy enough to just re-create the dialog.

**Comment by umlaeute** [comment]
implemented in the GUI-preferences WIP.
