### ISSUE TITLE
Missing doc files

### ISSUE THREAD

**Issue by fdch** [pure-data/pure-data#1425]
The files in question are the following:

https://github.com/pure-data/pure-data/blob/master/doc/5.reference/czero_rev~-help.pd
https://github.com/pure-data/pure-data/blob/master/doc/5.reference/czero~-help.pd
https://github.com/pure-data/pure-data/blob/master/doc/5.reference/lop~-help.pd
https://github.com/pure-data/pure-data/blob/master/doc/5.reference/rzero_rev~-help.pd
https://github.com/pure-data/pure-data/blob/master/doc/5.reference/rzero~-help.pd

**Comment by sebshader** [comment]
it seems like
doc/5.reference/0_all_guis-INTRO.txt
doc/5.reference/pd-help.pd
doc/5.reference/tabreceive~-help.pd

were also removed in the same commit
9a43ab29425de308a728e1358847c9731f1937b5

**Comment by sebshader** [comment]
it seems like tabreceive~-help was removed as well, but I think we should have a differently-named helpfile than tabsend~-help.pd if it is supposed to be for both tabsend~ and tabreceive~

**Comment by porres** [comment]
I'll take care of this

**Comment by porres** [comment]
> it seems like tabreceive~-help was removed as well, but I think we should have a differently-named helpfile than tabsend~-help.pd if it is supposed to function as a shared helpfile for both tabsend~ and tabreceive~

what name do you suggest?

**Comment by sebshader** [comment]
@porres idk, maybe something like tab_send_receive? or tab_send_receive~
