### ISSUE TITLE
opening framp~-help.pd in Pd 0.52test0 blows up Pd

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1432]
macOS 10.14.6

**Comment by umlaeute** [comment]
what does 'blows up Pd' mean?

it would be nice if you could be a bit more specific (i'm not sure if i want a blown up Pd)

**Comment by porres** [comment]
it crashes completely... and closes the app

**Comment by umlaeute** [comment]
i see (and can reproduce this).

the issue seems to be that `rsqrt_exptab` is not initialized (and points to NULL)
