### ISSUE TITLE
is 'qlist' obsolete?

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1434]
It seems we should consider 'qlist' obsolete and document it as such in favor of [text sequence]

**Comment by umlaeute** [comment]
hmm.
iirc, you could have just as well rebuild `[qlist]` with `[msgfile]` for the last two decades (and i think whenever i did need `[qlist]`'s functionality, i indeed used `[msgfile]` instead)
and `[float]` and `[value]` with `[table]` (which i never used as a replacement of the former).

should we document them as being obsolete?

**Comment by sebshader** [comment]
@umlaeute well, [msgfile] isn't part of vanilla and also can't sequence 'automatically' afaict so I'd argue [text sequence] is more similar

[float] and [value] are arguably more convenient to use than [table]

I think we're talking about if the internal has the same functionality, not if it can possibly produce the same functionality with patching/other internals and externals.
though I suppose [text] and [qlist] don't necessarily have the ~exact~ same functionality, they are more similar than [float] is to [table]

**Comment by porres** [comment]
[text sequence] has the same functionality as [qlist] but it's more powerful... like [array] is more powerful than [table] (and documented as such). Perhaps something like saying [text sequence] is a more powerful and a 'better replacemente' in the help file of 'qlist' is enough.

**Comment by umlaeute** [comment]
Am 7. November 2021 03:19:28 MEZ schrieb Seb Shader ***@***.***>:
***@***.*** well, [msgfile] isn't part of vanilla

Doh!

However, I actually mistyped and meant the built-in [textfile].


 and also can't sequence 'automatically' afaict

And no, it probably doesn't do anything "automatic" - but this was actually the motivation to use it on the first place as I had more control over what it does (while still allowing exactly the same functionality with a wee bit of patching)

> so I'd argue [text sequence] is more similar
>

sure

>I think we're talking about if the internal has the same functionality, not if it can possibly produce the same functionality with patching/other

What's "the same functionality"? Many objects that provide the same functionality have a slightly different API - does invoking the API count as 'patching'?

**Comment by porres** [comment]
> Perhaps something like saying [text sequence] is a more powerful and a 'better replacemente' in the help file of 'qlist' is enough.

already did it, already merged, closing
