### ISSUE TITLE
-path startup flag saved to preferences

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#144]
It looks like temporary paths passed to pd via the -path startup flag are being saved to the preferences since they are added to $::sys_searchpath:

1. start pd with `pd -path some/path`
2. open the Path dialog & see the temp path is in the list
3. save by hitting the Ok button
4. restart pd and the temp path is now saved in the preferences

We need some way to differentiate between the two so we only save paths manually added via the Path dialog & not the command line.

**Comment by danomatika** [comment]
Maybe a solution is to add some sort of placeholder string to mark where the actual prefs paths end and the temp paths begin ala:

    some/path1 some/path2 important/stuff TEMP temp/path1 temp/path2

It's a little clunky but wouldn't require adding extra variables or changing the Tcl/GUI proc call arguments.

**Comment by millerpuckette** [comment]
I don't know which is less correct, saving the added path entries or not.  (The "preferences" dialog shows them, so wouldn't the user expect them to get saved?)  One would have to show the distinction in the dialog.  And then, what if the user wants to change a path entry that's there from the command line?  I think the best thing is to let this particular dead dog lie.

**Comment by danomatika** [comment]
My perspective is:

1. The Path dialog should only show paths added explicitly by users when using the dialog.

1. -path on the command line should add a temporary path when running pd. This is like commandline utilities that do not remember command line arguments.

2. Adding a -path to the startup flags in the Startup dialog shouldn't save this path since it's already in the startup flags. Paths here also shouldn't be listed in the Path dialog.

3. Editing -path paths should be done at the originating location (on the command line or in the startup flags Dialog), it should not be done in a secondary location (Paths dialog), which I think is confusing.

We could make a distinction by adding the tmp paths to the Dialog and making them non-editable, but I think that would be pretty confusing too.

My thinking is from a beginner's perspective. Most people will add paths using the dialog. At some point, they might try adding a -path line to the startup flags for some lib or whatever. Later on, they decide they don't want it there anymore, so they delete it from the startup flags ... except it was saved when they last adding another path and saved prefs from the Paths dialog. So in this case, the expectation is to remove the path but it's still there. Confusing: "I have to delete it twice?"

Power users, OTOH, will understand adding -path on the command line and/or startup flags. I also do not thing they would expect those temp paths to be saved the they also use the Paths dialog for adding something else.

**Comment by umlaeute** [comment]
Quoting Miller Puckette <notifications@github.com>:

> I don't know which is less correct, saving the added path entries or  
> not.  (The "preferences" dialog shows them, so wouldn't the user  
> expect them to get saved?)  One would have to show the distinction  
> in the dialog.  And then, what if the user wants to change a path  
> entry that's there from the command line?  I think the best thing is  
> to let this particular dead dog lie.

+1

it's "really hard" to oversee paths added via the "-path" flag in the  
preferences menu.
if they show up in the list, i expect them to be saved when i click  
"save preferences".
if i don't want them to be saved, i can delete them.

**Comment by danomatika** [comment]
>if they show up in the list, i expect them to be saved when i click
>"save preferences".
>if i don't want them to be saved, i can delete them.

I guess I'm saying I don't expect them to show up in the list at all and, when they do, it's annoying to have to take the extra step of deleting them *each time* I would need to save anything else and also remember to do so. Not so user friendly in IMO.

**Comment by danomatika** [comment]
See #153 for a proposal for the behavior I'm talking about.

**Comment by danomatika** [comment]
The discussion can move to #153.
