### ISSUE TITLE
put pow into math-help with 'log', 'sqrt' and 'exp'.

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1457]
we have the operators-help.pd file with a function like [pow], and I think we should also have [log] in it. Right now, [log] resides under math-help.pd, which includes some trigonometric and other functions like [sqrt], [exp] and stuff.

**Comment by umlaeute** [comment]
i'd rather have `[pow]` in the *math-help.pd*.

**Comment by porres** [comment]
what's the reasoning?

**Comment by umlaeute** [comment]
just look at the objects.

*operators-help.pd* lists mainly what i would call "simple math objects" (`[+]`, `[-]`, `[*]`, `[/]`, `[max]`, `[min]`). the functionality of these objects is something everybody who has graduated from elementary school will understand.

otoh, the *math-help.pd* lists objects that have "advanced math" (such as taught in secondary school), namely trigonometric functions (`[sin]`, `[cos]`, `[tan]`, `[atan]`, `[atan2]`), and "stuff related to power functions" (`[sqrt]`, `[exp]`, `[log]`) and the third family whose name i forgot (`[abs]`, `[wrap]`).

imo, `[pow]` is similar to `[exp]` and they should live side-by-side.

**Comment by porres** [comment]
I was concerned with the distinction of 'binary operators', but math would still include [atan2] which is a binary operator, right? Well, I'll do the change...

**Comment by porres** [comment]
taking pow out of operators help also makes it more consistent to the audio version that also groups the same objects in a single help file! Nice!
