### ISSUE TITLE
standardize turning audio on in tilde objects help files

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1462]
currently, some help files have a loadbang to turn audio on in a "; pd dsp 1" message, some do not. There's no reasoning behind this discrepancy. For consistency, and to make things easier, I think all of them should have the loadbang also turn the audio on.

I also think we can have a standard where a loadbang activates a toggle that connects to a " ; pd dsp $1" and then the user can decide to turn the audio off.

**Comment by porres** [comment]
I understand there's an idea we may not want the audio turned on when we open the help patch, but I want to challenge this notion. Honestly, from my experience, it's always a bummer that things are not actually working and I need find my way and click on a message to start things.

Perhaps this made more sense back in the early days, where we probably most always would like to save CPU. In my day to day use, I never really have to worry if opening a help file will start my audio, and my reasoning is that if we want to see how an object works, we want to see it in action.

And then, some of the help objects were already doing things like this, and they were all not well standardized.

Now, as far as being able to shut DSP off in the case we need it, I think my proposal of a standard where we have a loadbang into a toggle easily offers the option to click on the toggle to turn it off if needed.

**Comment by umlaeute** [comment]
please don't.

this is not about saving some CPU cycles, but preventing Pd from babbling out on your 20kW PA.

**Comment by porres** [comment]
already did, but I can just remove all of the [loadbang] objects...

here's what we have most of times, a toggle activating both turning audio on/off and a metro.


<img width="239" alt="Screen Shot 2021-11-18 at 17 58 02" src="https://user-images.githubusercontent.com/5360142/142495756-ccc91903-8d11-4fdf-b8df-7d8f0902a106.png">

Sometimes it just turns audio on/off...

So I can delete and leave it up to the user...

Or... I can replace [loadbang] for a [checkdsp] helper abstraction in the doc files, which outputs '1' or '0' depending if the DSP is on or off when the patch loads. This makes things friendlier, because if the audio is already on and you want to turn it off, the toggle is already activated. And, more compelingly, if the DSP is on, it also activates those [metro] objects.

<img width="671" alt="Screen Shot 2021-11-18 at 18 00 25" src="https://user-images.githubusercontent.com/5360142/142496031-e1360f2e-579e-47f8-976d-1469a14d2b15.png">

This would not be a new object shipped with Pd, just making it clear what I mean by "helper abstraction", and we've had things like this such as the output~ abstraction, so I think it's cool. It's also something users can copy or incorporate in their patches

**Comment by umlaeute** [comment]
hmm, why don't you just listen of `pd dsp $1` messages (to catch "DSP off")  and `pd-dsp-started` (to catch "DSP on")?

no need for a busy [snapshot~].

also, i have no idea why you would want to turn on DSP processing if it is already on, and turn it off it is already off.

**Comment by porres** [comment]
a new commit simply removed the loadbang from activating the DSP on... https://github.com/pure-data/pure-data/pull/1455/commits/85b1d4d268060180c578402ef5a14e1618d65fa6 

so now users just need to click on the toggle if they notice the audio engine is not on...

but I'm keeping the [loadbang] activating [metro] objects for [snapshot~].

I guess this is the no brainer solution, I can open a new issue if I want to add a [checkdsp] helper abstraction.
