### ISSUE TITLE
update Shahrokh Yadegari's webpage on expr

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1464]
Not something we can fix here, but we're now shipping a reference html file as the reference of expr and it is updated, but there's a webpage in the wild on Shahrokh Yadegari's webpage which is outdated. This is more of a reminder for me to try and send our new html to him so he updates it and then we can close this.

**Comment by porres** [comment]
moving to pddp

**Comment by umlaeute** [comment]
i marked this as *invalid* (as we cannot fix it here) but left it open (to keep your reminder).

but i agree moving it to pddp is much better.
