### ISSUE TITLE
Pd-0.52-test2: GUI extremely sluggish when DSP is turned on

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#1475]
I just noticed that when I select the ASIO driver of my Focusrite Scarlett audio interface and turn on DSP, the Pd GUI becomes extremely sluggish. This is most obvious when trying to select or move objects. Typing in text boxes is fine, though.

Curiously, this does not happen when using ASIO4ALL.

The CPU load looks totally fine. I rather have the feeling that Pd accidentally applies an extreme rate limit to upstream GUI messages.

This also happens with Pd-0.52-test1. It does *not* happen with Pd-0.51-4

@Lucarda Can you confirm this?

**Comment by Lucarda** [comment]
Selecting all objects and moving them (this patch):

[sluggish.zip](https://github.com/pure-data/pure-data/files/7589827/sluggish.zip).

I see no difference


0.52-0test2 from Millers site or `develop`

Tascam us-4x4

MMIO 80/64
ASIO 12/64

Can you share your test patch?

**Comment by Spacechild1** [comment]
I find the culprit! @millerpuckette accidentally defined `THREADSIGNAL` in `s_audio_pa.c`. I've pushed a fix to develop.

Can you try latest develop and see if you notice any regressions?

**Comment by Lucarda** [comment]
> Can you try latest develop and see if you notice any regressions?

For me it stays the same.

Not sure if my patch from above is enough to notice differences.

**Comment by Spacechild1** [comment]
I just did a `git blame` and now I see that `s_audio_pa.c` hasn't really changed since Pd 0.51-4 - except for that `THREADSIGNAL` definition. So I don't expect any regressions. Thanks anyway!

**Comment by millerpuckette** [comment]
Drat.  If I recall correctly, I turned on THREADSIGNAL because that reduces audio latency on Macintosh.  But if it breaks things on Windows, perhaps that's a sign that it's problematic in general.  I gather this is undone in the develop branch so will grab that now.

**Comment by Spacechild1** [comment]
@millerpuckette While I think that `THREADSIGNAL` is a good idea in principle, the implementation has several problems. I will try to address them in a PR (not now :-). I think then it could even improve performance on Windows.
