### ISSUE TITLE
improve [trigger] conversions

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1478]
- convert pointers to things other than a bang is 'pointless' (pun intended). It should only convert to bang and produce errors otherwise.
- It's not clear why 'anything' can only be converted to a bang. It could be converted to a list just by adding the list selector. The selector could also convert to a symbol.

**Comment by Spacechild1** [comment]
The purpose of `[trigger]` to distribute the input over several inlets to force a particular ordering.

One important feature of `[trigger]` is that it provides (optional) typesafety. For example, if I specify `l` I don't say: "please convert any input to a list", but rather: "I expect the input to be a list or trivially convertable to a list". I *want* a warning if I accidentally pass the wrong type. I *don't* want an implicit conversion from "anythings" to lists. If I don't care about type safety, I would use `a` instead.

I'm not saying that #1479 is bad per-se, some people might find such a version of `[trigger]` convenient, but it should be a different object (probably an external). It's just impossible to apply these conversions to `[trigger]` without breaking backwards compatibility.

---  

As a side note, conversions inside `[trigger]` can be quite inefficient. Consider this:

A:
![grafik](https://user-images.githubusercontent.com/16126632/143234779-e75d5e0a-57e2-4d03-9173-47bce9a69ad8.png)

B:
![grafik](https://user-images.githubusercontent.com/16126632/143234826-111ad06d-4121-4bea-940e-2146943b7737.png)

A: 1 conversion, B: 10 conversions!

**Comment by Spacechild1** [comment]
> convert pointers to things other than a bang is 'pointless' (pun intended). It should only convert to bang and produce errors otherwise.

Hard disagree. A pointer can be seen as a 1-element list, just like float and symbol.

**Comment by Spacechild1** [comment]
One curious is exception is that you can pass a list to `[t f]`, `[t s]` and `[t a]` and it would just take the first list element. Actually, I think it's a bit inconsequent, but it has always been like that and it's just too convenient.

Generally, `[trigger]` doesn't need more implicit conversions, it needs more and better warnings. See my competing issue :-) https://github.com/pure-data/pure-data/issues/1480

**Comment by umlaeute** [comment]
`[t a]` seems to be a typo and should be `[t p]` instead, no?

**Comment by porres** [comment]
> Hard disagree. A pointer can be seen as a 1-element list, just like float and symbol.

I need an example on how a pointer can be converted to a list, float or symbol.

**Comment by Spacechild1** [comment]
> I need an example on how a pointer can be converted to a list, float or symbol.

A pointer *is* a 1-element list, just like a float or symbol. Passing it to `[t l]` is really a no-op.

On the other hand, passing it to `[t f]` or `[t s]` should be an error, but at the moment you get bogus output instead (0 resp. "symbol float" !?)

**Comment by porres** [comment]
giving this issue and PR up!
