### ISSUE TITLE
can't type negative or decimal numbers in "drawnumber" Data Structures.

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1489]
if you draw a number with [drawnumber], you can edit by clicking and dragging or typing on it, but you can't type negative numbers

you can't type numbers with decimal points either but I guess that's a limitation of the object and it should be documented.

**Comment by Spacechild1** [comment]
> and it should be documented.

or fixed :-)

**Comment by Spacechild1** [comment]
well, data structures hold floating point numbers, so it doesn't make sense to limit typing to (positive) integers.

also, it would be great if you could use the Shift key to increment in 0.01 steps, just like with float atoms.

**Comment by porres** [comment]
>  it would be great if you could use the Shift key to increment in 0.01 steps

+1, thought about that too

**Comment by jmmmp** [comment]
probably these are roughly the same issues I mentioned in #854 some time ago?

**Comment by porres** [comment]
Added in the title the request for shift+click+drag for decimals and keeping this open and closing https://github.com/pure-data/pure-data/issues/854

**Comment by porres** [comment]
closing in favor of https://github.com/pure-data/pure-data/issues/2171
