### ISSUE TITLE
'undarken' message printed when typing to symbol, float, list atoms

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1492]
It looks like a left-over debug message. The culprit is found in 636c7f2a9, specifically in https://github.com/pure-data/pure-data/blob/7b949aa903f2531d2a9c1af9f5aaae2ff6f11f82/src/g_text.c#L759

**Comment by umlaeute** [comment]
fixed with 364d859aa29c1d42be1d42ad81c74bc2fbc76cca
