### ISSUE TITLE
[file-help] multiply defined text

### ISSUE THREAD

**Issue by Ant1r** [pure-data/pure-data#1499]
In `file-help.pd`, there are two instances of the same `[text define -k $0-name-split+join-strings]`.
This causes an error to be post to the Pd console two times when testing `[pd split+join]` and `[pd base+ext`]:
```
warning: 1022-name-split+join-strings: multiply defined
warning: 1022-name-split+join-strings: multiply defined
```
Note: these errors are not traceable (i.e ctrl-clickable), which makes it more difficult to locate their origin.

**Comment by porres** [comment]
we can close this too :)

**Comment by Ant1r** [comment]
Yep!
