### ISSUE TITLE
[Window menu] shows same window multiple times

### ISSUE THREAD

**Issue by Ant1r** [pure-data/pure-data#1504]
current master (364d859aa29c1d42be1d42ad81c74bc2fbc76cca).

- open Pd
- open "List of objects..." from menu `Help`
- open `Window` menu: it contains two occurrences of "help-intro.pd":
![Capture du 2021-12-03 17-06-30](https://user-images.githubusercontent.com/3748246/144634585-e1ff8b24-5030-4d29-9e90-2877c9d1d96a.png)

Moreover, for each opened subpatch, the parent window is repeated one more time, for example opening `send-receive-help` then its subpatch `Dealing with $0` ends with 6 entries in the `Window` menu:
![Capture du 2021-12-03 17-02-21](https://user-images.githubusercontent.com/3748246/144635238-b0fa7ce6-f4af-47f3-971e-ea8c8b0fce33.png)

**Comment by Ant1r** [comment]
the culprit is 7595d2725fa4a28c055d154b92e3ef43bae31294.
@umlaeute an idea?

**Comment by umlaeute** [comment]
could you post a screenshot?

**Comment by Ant1r** [comment]
there are already 2 screenshots in the issue description (I guess only visible from the Github web interface or mobile app).

**Comment by Ant1r** [comment]
https://user-images.githubusercontent.com/3748246/144634585-e1ff8b24-5030-4d29-9e90-2877c9d1d96a.png
and
https://user-images.githubusercontent.com/3748246/144635238-b0fa7ce6-f4af-47f3-971e-ea8c8b0fce33.png

**Comment by umlaeute** [comment]
yes sorry; i only saw the 2nd post ("the culprit is...") and that only by email.

i you're ok with it i'm going to delete the comments from my "could you post a screenshot" to this (inclusive).

**Comment by Ant1r** [comment]
In fact, I found that the bug comes from the last line of 
```tcl
proc ::pd_menus::insert_into_menu {mymenu entry parent}
 ```

If you revert 
```tcl
$mymenu insert $insertat command -label $label -command "::pd_menucommands::scheduleAction raise $entry"
 ```
to the initial:
```tcl
$mymenu insert $insertat command -label $label -command "raise $entry"
 ```
then the bug vanishes.
I don't pretend to understand why, but at least I helped to find out where ;-)

**Comment by Ant1r** [comment]
Ah, of course, since the addition of the new entry is "scheduled", the test
```tcl
if {$currentcommand eq "raise $entry"} {return} ;# it exists already
```
cannot instantly detect that the entry already exists.
Maybe scheduling isn't required in this case? So the  `$mymenu insert (...)` line just has to be reverted to the initial "direct" version?

**Comment by Ant1r** [comment]
Sorry, I was wrong. The problem is that the test now should be:
```tcl
if {$currentcommand eq "::pd_menucommands::scheduleAction raise $entry"} {return} ;# it exists already
```
I'm preparing a PR.

**Comment by umlaeute** [comment]
> I'm preparing a PR.

please target 'develop'

**Comment by Ant1r** [comment]
ok! done.
