### ISSUE TITLE
feature request: implement -x$$ features in drawnumber

### ISSUE THREAD

**Issue by jmmmp** [pure-data/pure-data#1513]
The -x$$ features are useful to restrict user accidents on drawn shapes. They would also be helpful with drawnumber.
(probably it doesn't make sense with drawsymbol or drawtext, as there is no possible interaction)

**Comment by porres** [comment]
> (probably it doesn't make sense with drawsymbol or drawtext, as there is no possible interaction)

these are actually the exact same object class as [drawnumber]

**Comment by porres** [comment]
closing in favor of https://github.com/pure-data/pure-data/issues/2171

**Comment by porres** [comment]
this has been implemented by the way
