### ISSUE TITLE
[Pd-messages] is still used in some help-patches

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1525]
`doc/5.reference/Pd-messages.pd` has been renamed to `pd-messages.pd`, but the following help-patches still reference the capitalized version (and thus the object fails to create on case-sensitive file-systems):

- fudiparse-help.pd
- samplerate~-help.pd
- send-receive-help.pd

**Comment by porres** [comment]
I don't really see it at 'fudiparse'

**Comment by umlaeute** [comment]
Sorry, that was a false positive...I just ran 'grep -l Pd-messages' without checking the files...

🤦

**Comment by porres** [comment]
this has been fixed in my documentation updates https://github.com/pure-data/pure-data/pull/1517
