### ISSUE TITLE
help-patches shouldn't include abstractions with global array names

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1527]
a number of help-patches reference example patches.

i think this is a good thing, as these examples document advanced uses.

however, many example patches use global names, and do not really like it if there are multiple instances opened at once.

e.g. everytime you  open the help-patches of *both* `[trigger]` and `[pack]` (something i would advice any novice Pd user to do, because these two objects are so important), will issue a warning on the Pd-console:
> template pd-template1: warning: already exists.
> warning: pd-data: multiply defined

for a more dangerous example, see #1526

---

i think a somewhat better solution would be to not instantiate the example patches, but instead open them on demand:

~~~pd
see also the "array" examples from section 2:

[arrays(
|
| [more arrays(
|/
[pd examples]
~~~

(with `[pd examples]` using `[pdcontrol]` to open the example-patches on demand)

**Comment by porres** [comment]
again, I can get back to this after I finish adding a 'reference' subpatch

**Comment by porres** [comment]
So, what is the best way to open files in Pd?

I am using the 'open' message to Pd... 
![Screen Shot 2022-03-07 at 17 25 40](https://user-images.githubusercontent.com/5360142/157112400-f1085ea9-ee75-4081-9c76-c0c111e069be.png)

**Comment by porres** [comment]
did it for trigger/pack, these are still missing for the array related objects 

![Screen Shot 2022-03-07 at 17 35 38](https://user-images.githubusercontent.com/5360142/157113821-c59e149c-0b19-4b1b-b120-440b656e5fdc.png)

**Comment by umlaeute** [comment]
>I am using the 'open' message to Pd... 

Yes. This is the way.

However, your use is [makefilename] seems to serve no purpose here (apart from adding another object).
Just use $arg expansion.
