### ISSUE TITLE
Q factor in the hip~ object

### ISSUE THREAD

**Issue by jimkang** [pure-data/pure-data#1534]
Apologies if this isn't the best place to ask this (and let me know what the best place is), but what is the Q factor for the `hip~` object? I tried looking at the C code for it, but I can't say that I understand it well enough to confidently interpret what the Q factor is.

**Comment by Ant1r** [comment]
Hi Jim,

I think that for this kind of question, it's best to post to the Pd list (see https://lists.puredata.info/listinfo/pd-list).
The Github issue tracker is best for bug reporting and feature request.

As for `hip~`, it doesn't have a Q factor as such, being a first-order filter: `hip~` only attenuates signals of frequency lower than the cuttoff frequency (attenuation is 6dB per octave). 

Only filters of order greater than or equal to 2 can have a Q factor (read for example https://en.wikipedia.org/wiki/Q_factor).
