### ISSUE TITLE
[file] switch the working directory to canvas' path

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1536]
Currently, [file] uses Pd's start location as working directory, which means all relative paths are resolved relative to that. This is unlike all other file writing objects that write relative to the patch. There is no apparent reason why [file] handles relative paths differently from other file writing objects. The switch the to canvas' path as working directory would allow to write files beside the patch. Currently, this is only possible with clumsy workarounds.

Read  more about a related discussion in the [mailing list](https://lists.puredata.info/pipermail/pd-list/2022-01/130639.html).

**Comment by Spacechild1** [comment]
> There is no apparent reason why [file] handles relative paths differently from other file writing objects

The reason is that `[file]` is just a thin layer around the POSIX filesystem API. It lets the OS shell decide how to handle relative file paths.

The very existence of `[file which]` shows that this is a design decision.

**Comment by reduzent** [comment]
> The workaround is to use `[dir(` -> `[pdcontrol]`. Not pretty, but also not terrible.

I don't mind 'not pretty' so much. This works only for paths known to be relative. For any given path, a detection 'isrelative' is needed. This turns out to be not so trivial.

> I don't think we can/should change that after the fact...
Yeah, I agree. How about an additional `-p`? `-p`: interpret relative paths as relative to patch.

**Comment by Spacechild1** [comment]
> This turns out to be not so trivial.

That's we I have created https://github.com/pure-data/pure-data/issues/1535

> How about an additional -p? -p: interpret relative paths as relative to patch.

This could be a possibility. I'm curious what @umlaeute thinks.

**Comment by Spacechild1** [comment]
Alternatively, I can imagine a `[file resolve]` object which resolves a path - if it is relative - to the current patch directory. I think putting a `[file resolve]` after a file path is not too much of a hassle.

It would also be handy for other use cases which currently require `[dir( -> [pdcontrol]` shenanigans, e.g. creating file paths for `[readsf~]` or `[writesf~]`.

**Comment by reduzent** [comment]
> Alternatively, I can imagine a `[file resolve]` object - as a sister object of `[file which]` - which resolves a relative path to the current patch directory. (Absolute paths would pass unchanged.) I think putting a `[file resolve]` after a file symbol is not too much of a hassle.

Yeah, that sounds certainly viable. However, you didn't tell what [file resolve] would resolve to. My concern is that in Pd land relative to patch is often used and implemented by other objects. A [file resolve] would absolutely cover my request, _if_ it provides a way to resolve relative to patch.



> It would also be handy for other use cases which currently require `[dir( -> [pdcontrol]` shenanigans, e.g. creating file paths for `[readsf~]` or `[writesf~]`.

I don't see how those require shenanigans for creating file paths, they create/read files already relative to patch.

**Comment by Spacechild1** [comment]
> However, you didn't tell what [file resolve] would resolve to.

I said: "which resolves a relative path to the current patch directory. (Absolute paths would pass unchanged.)". Let's move discussion about `[file resolve]` to the new issue I've created: https://github.com/pure-data/pure-data/issues/1539

> I don't see how those require shenanigans for creating file paths, they create/read files already relative to patch

This only works if the files are next to the patch containing the `[readsf~]`/`[writesf~]` objects. However, these objects are often used in abstractions. If you want to use a file path relative to some parent patch - which is a very common case - you have to use `[dir( -> [pdcontrol]`.

**Comment by reduzent** [comment]
> I said: "which resolves a relative path to the current patch directory. (Absolute paths would pass unchanged.)". Let's move discussion about `[file resolve]` to the new issue I've created: #1539

Sure.

> This only works if the files are next to the patch containing the `[readsf~]`/`[writesf~]` objects. However, these objects are often used in abstractions. If you want to use a file path relative to some parent patch - which is a very common case - you have to use `[dir( -> [pdcontrol]`.

Yeah, right. Thanks for clearing up. I close this now.

**Comment by Spacechild1** [comment]
Thanks for bringing this up!

**Comment by umlaeute** [comment]
> Yeah, I agree. How about an additional `-p`? -p: interpret relative paths as relative to patch.

my initial reaction was: i don't really like this, as `[file]` is really just a shorthand for `[file define]` and `[file define]` already takes an arbitrary symbol (the handle ID).

turns out that `[file]` is really a shorthand for `[file handle]` which already has flags (and thus limits possible handle names), so adding another flag would not be totally out of place.

(i haven't really thought hard about the problem though)
