### ISSUE TITLE
add [file] verb (object) that returns current working directory

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#1537]
Sometimes you want to read/write a file relative to the current working directory, but all "high-level" Pd objects - unlike the "low-level" [file] API - resolve relative paths to the canvas environment. Therefore it would be nice to have an object that returns the current working directory, e.g. `[file cwd]`.

Knowing the cwd is handy when writing Pd based command line utilities. If I pass a relative path to such a utility, I want to resolve it to the cwd and not to the Pd patch itself. Currently I have to wrap the whole thing in a shell script/batch script (which I would anyway) and turn all paths into absolute paths before passing them on to Pd. Not a big deal, but still.

Another case is where I want to generate files and put them in the cwd if the user did not provide an output directory.

**Comment by umlaeute** [comment]
as mentioned on the mailinglist, `[file cwd]` could also be used to *set* the current working directory.
