### ISSUE TITLE
add [file] verb (object) to resolve relative paths to current patch directory

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#1539]
Discussions on the mailing list and in https://github.com/pure-data/pure-data/issues/1536#issuecomment-1007849130 showed that we need an easier way to resolve file paths to the current patch.

I'd like to propose `[file resolve]` which takes a file path, and if it's relative, resolves it to the current patch directory. Absolute paths would pass unchanged.

Passing a `[bang(` could simply output the patch directy.

Finally, we might provide an argument to specify the parent level, like `[pdcontrol]`'s `[dir(` method.

`[file resolve]` would complement `[file which]`, so you can implement reading and writing files like in most other Pd objects (array, text, etc.) `[file resolve]` would be used for writing, `[file which]` would be used for reading.

**Comment by umlaeute** [comment]
i don't really know about `[file resolve]`: for me this somehow clashes with `[file which]` (e.g. i expect having to look up the help path to resolve which one is which every time i use them).

`[file patchpath]` doesn't really have this problem (and is pretty clear about what it does, i think)

what do you think?

**Comment by umlaeute** [comment]
on the [mailinglist](https://lists.puredata.info/pipermail/pd-list/2022-01/130663.html) you wrote:

> `[file patchdir]` would be the other way round: it's main purpose is to 
> get the patch directory, but as an extra feature it should probably also 
> allow to resolve a file path (because such a common task shouldn't 
> require several objects).
> 
> Both would essentially provide the same things. IMO, `[file resolve]`
> would be more intuitive because after all that's what people likely want 
> to do when they ask for the current patch directory.


but on recapping the thread, i see that it ended up pretty univocal:

- call it `[file patchpath]` ([pd-list](https://lists.puredata.info/pipermail/pd-list/2022-01/130667.html))
- it takes a `[bang(` to get the current patch directory, or a `[symbol ...(` that is resolved via the current patchdirectory (unless it's an absolute path) ([pd-list](https://lists.puredata.info/pipermail/pd-list/2022-01/130666.html))
- it can be parametrized to set the parent level ([pd-list](https://lists.puredata.info/pipermail/pd-list/2022-01/130668.html))

so sorry for the noise...

**Comment by umlaeute** [comment]
things have been implemented in https://git.iem.at/pd/file

i only need to create a PR (and review the sources :-)

iirc, the main reason for stalling this is that @porres was updating the help-patches (including that of `[file]`) and i dodn't want to get into some conflict, so I'd rather wait until the #1517 got merged.
