### ISSUE TITLE
file splitname symbol send misnamer

### ISSUE THREAD

**Issue by tremblap** [pure-data/pure-data#1543]
the symbol to test the feature in the base+text subpatch has the wrong send name, it should be [$0-name-base+ext] for the help patch to work.

**Comment by abreubacelar** [comment]
I noticed this, and made this pull request https://github.com/porres/pure-data/pull/18

**Comment by abreubacelar** [comment]
and actually it should be [$0-name-base+ext-in] it first goes inside one subpatch before going to the send for the objects

**Comment by porres** [comment]
on it...

**Comment by porres** [comment]
I noticed this and fixed while adding a reference to [file], so https://github.com/pure-data/pure-data/pull/1517 closes this
