### ISSUE TITLE
Pd doesn't shut down on Windows

### ISSUE THREAD

**Issue by alfonso73** [pure-data/pure-data#1552]
Hi, in the last couple of versions PD doesn't shut down on Windows (i'm using ASIO on two different computers and soundcard)
when using the DSP. Everything works and it does shut down if the DSP is never activated during the patching session.

**Comment by Spacechild1** [comment]
I've never had this problem on Windows... Which Windows version(s)? Which Pd versions? Which soundcards?

**Comment by alfonso73** [comment]
On both my systems i have Windows 10 64bit. On the laptop i use RME Babyface PRO FS and on my desktop system i use Presonus Quantum. On both system i have the same problem on PD.

**Comment by umlaeute** [comment]
so could you clarify what "doesn't shut down" means exactly?

Pd is running two processes, the core (`pd.exe`) and the gui (`wish86.exe` or somesuch).
if you try to quit Pd, what happens to the two processes? (do both keep running? or only the GUI and it's stalling because the core quit unexpectedly? or...)
note: use your taskmanager to inspect the running processes.

also: try running Pd from the cmdline.
1. Open the CLI:
    1. <kbd>⊞ Win</kbd>+<kbd>r</kbd>
    2. type `cmd` and hit <kbd>Enter</kbd>
2. use the *File Explorer* to navigate to the path where Pd is installed (e.g. `C:\Applications\Pd-0.52-1\`)
3. enter the `bin\` subdirectory (e.g. `C:\Applications\Pd-0.52-1\bin\`)
4. locate the `pd.com` executable.
    if your system doesn't show file extensions (which is the unfortunate default on Windows), then it will just be called `pd` with something like "*MS-DOS Application*" or "*Command Executable*" in the description.
   make sure to pick `pd.com` and not ~~`pd.exe`~~
5. drag the `pd.com` into CLI
   - this basically just copies the path to the Pd binary (e.g. `C:\Applications\Pd-0.52-1\bin\pd.com`) into the CLI
6. hit <kbd>Enter</kbd> to start Pd.
7. do whatever you do to make "Pd not shut down"
8. tell us what you see on the screen.

you might also want to add `-stderr -verbose` when starting Pd, to get more printout:

~~~bat
C:\Applications\Pd-0.52-1\bin\pd.com -stderr -verbose
~~~

**Comment by alfonso73** [comment]
@umlaeute thanks for the hint.

this is what i get  when i launch pd.com via cmd

C:\Windows\System32>"C:\Program Files\pd\bin\pd.com" -stderr -verbose
Pd-0.52.1 ("") compiled 15:33:39 Dec 19 2021
float precision = 32 bits
verbose(4): input channels = 2, output channels = 2
port 10568
Waiting for connection request...
... connected
verbose(4): MIDI input (2- ReMOTE SL) opened.
verbose(4): tried C:/Users/fremen/Documents/Pd/externals/patcherize-plugin/patcherize.m_amd64 and failed
verbose(4): tried C:/Users/fremen/Documents/Pd/externals/patcherize-plugin/patcherize.dll and succeeded
patcherize - turn objects into a subpatch

Then i start DSP and i have

verbose(4): input channels = 2, output channels = 2
verbose(4): input device 51, channels 2
verbose(4): output device 51, channels 2
verbose(4): framesperbuf 64, nbufs 1
verbose(4): rate 44100
verbose(4): ... opened OK.

Then i open my patches and i work without problems.
When i'm done i close my patches and turn off DSP (no messages in the console or in cmd appear)
Then i try to quit but nothing happens and PD stays open and kind of freeze. No other messages in console or cmd appear.
No further operations are allowed on PD after i turned off DSP and i have to quit manually in the Task Manager.

**Comment by Spacechild1** [comment]
> Then i try to quit but nothing happens and PD stays open and kind of freeze. No other messages in console or cmd appear.
No further operations are allowed on PD after i turned off DSP and i have to quit manually in the Task Manager.

As @umlaeute  has pointed out, Pd really consists of 2 applications: the core (`pd.exe` resp. `pd.com`) and the GUI (`wish.exe`). The GUI process obviously freezes, but please check in the task manager if the core application keeps running as well.

**Comment by Spacechild1** [comment]
Also, please try to temporarily disable any externals and GUI plugins.

**Comment by alfonso73** [comment]
> As @umlaeute has pointed out, Pd really consists of 2 applications: the core (`pd.exe` resp. `pd.com`) and the GUI (`wish.exe`). The GUI process obviously freezes, but please check in the task manager if the core application keeps running as well.

Both processes keeps running.
How can i disable all plugins? Is there any command line flag to do it?
thanks

**Comment by umlaeute** [comment]
normally `-noprefs`.

it's a bit more complicated with `patcherize` where you would have to (temporarily) rename the `patcherize-plugin` folder

**Comment by alfonso73** [comment]
Using -noprefs seems to quit without freeze. Where are the prefs actually stored? I can't understand which one makes this happen...probably starting with ASIO as preferred audio driver? I say this beacause only activating DSP makes this not-quit behavior happen...

**Comment by Spacechild1** [comment]
> Using -noprefs seems to quit without freeze.

But did you actually start DSP (using your ASIO driver)?

**Comment by alfonso73** [comment]
yep...i can confirm that if PD start with ASIO as preferred device i have this behavior. If PD starts with standard (MMIO) as preferred device it quits normally without freeze/hang

**Comment by alfonso73** [comment]
> > Using -noprefs seems to quit without freeze.
> 
> But did you actually start DSP (using your ASIO driver)?

yes. But if i save the preference quit and start again the next quit will freeze. It works normally if i save standard(MMIO) as preferred device.

**Comment by Spacechild1** [comment]
What happens if you saved your ASIO device in your preferences, but then open Pd, switch to MMIO and turn on DSP? Does it also hang?

**Comment by alfonso73** [comment]
> What happens if you save your ASIO device in your preferences, but then open Pd, switch to MMIO and turn on DSP? Does it also hang?

No. It quits regulary even if passing to MMIO makes PD quite slow and audio dont't play...but it regularly quits without hang

**Comment by Spacechild1** [comment]
Since when do you have this problem? Can you track down which Pd version introduces this problem? Does it still happen with Pd 0.52?

**Comment by alfonso73** [comment]
> Since when do you have this problem? Can you track down which Pd version introduces this problem? Does it still happen with Pd 0.52?

For sure all the 0.52 pre release and the actual latest release. As far as i remember 0.51-4 got the same problem. And probably 0.51-3 to..but i don't remember very well. I should have report this the first time it happend :-(

**Comment by Spacechild1** [comment]
Can you try older releases?

**Comment by alfonso73** [comment]
> Can you try older releases?

which one do you suggest? better said which one did introduced some change in the Windows audio driver department? so i could try the one before

**Comment by alfonso73** [comment]
0.51-0 doesn't have in ASIO driver list any ASIO entry but only MMIO one...i remember this bug...now i try all the subsequent versions

**Comment by alfonso73** [comment]
0.51-1 behave as 0.51-0 so i can't really test. 0.51-2 i can't find anywhere. 0.51-3 behave as 0.52...so probably something is changed before 0.51. I go test 0.50 versions

**Comment by alfonso73** [comment]
I can't find any version let let me make some test...all the versions before 0.51-3 seems to behave differently anyway and i can't find any ASIO entries in the device menu.

**Comment by Spacechild1** [comment]
> and i can't find any ASIO entries in the device menu.

That's very strange! I just tried to open Pd 0.46 and my ASIO driver shows up...

BTW, here you can download old Pd releases: http://msp.ucsd.edu/Software/

Do you know about anybody else who has a similar problem?

**Comment by umlaeute** [comment]
i suspect some problems with some (virtual) soundcard (as in https://github.com/pure-data/pure-data/issues/1532)

please list all devices you get.
do other applications (e.g. REAPER) work properly?

**Comment by Spacechild1** [comment]
@alfonso73 Can you try the following binaries:
[pd-0.52.0-pa-fix.zip](https://github.com/pure-data/pure-data/files/7906519/pd-0.52.0-pa-fix.zip)

**Comment by alfonso73** [comment]
> i suspect some problems with some (virtual) soundcard (as in #1532)
> 
> please list all devices you get. do other applications (e.g. REAPER) work properly?

All my other apps, hosts, daw etc. works fine (Max, Supercollider, Reaper, Ableton Live, Bespoke Synth, Cabbage the ones i use the most from time to time).
PD give me this list of ASIO drivers

ASIO : ASIO Link Pro
ASIO : Quantum ASIO driver
ASIO : Realtek ASIO 
ASIO : ReaRoute ASIO (x64)

BTW I really don't know what have installed ASIO : Realtek ASIO.

For comparison Reaper lists the same 4 drivers as PD plus

iConnectivity ASIO driver  (probably installed by my mio10 MIDI interface)
Novation USB ASIO driver (probably installed by my Novation SL61 controller)
I doubt that these are really audio drivers tho...

Max and Ableton Live list the same as Reaper (so the 4 listed by PD plus the 2 more i reported).
Supercollider lists the same 4 as PD (so no extra 2 as in Reaper, Max and Ableton Live).

**Comment by alfonso73** [comment]
> @alfonso73 Can you try the following binaries: [pd-0.52.0-pa-fix.zip](https://github.com/pure-data/pure-data/files/7906519/pd-0.52.0-pa-fix.zip)

It behaves the same. PD doesn't quit after DSP is turned on with ASIO.

**Comment by Spacechild1** [comment]
Ugh... Which ASIO drivers are installed on your other machine?

**Comment by Spacechild1** [comment]
> It behaves the same. PD doesn't quit after DSP is turned on with ASIO.

Which ASIO driver do you use for testing? Does it also happen with other ASIO drivers?

**Comment by Lucarda** [comment]
@alfonso73 

Can you try

- start Pd from commndline with `pd -noprefs`

- select ASIO from the media menu and select a working soundcard.

- test that audio is working

- quit Pd

I think there is trouble with the `-asio` flag. Will open a issue soon.


Please test.

**Comment by alfonso73** [comment]
> 

@Lucarda nope it doesn't quit.

**Comment by alfonso73** [comment]
> Can you try to run my binaries (`pd.com`) in `cmd.exe` and post the console output?

Pd-0.52.1 ("") compiled 16:38:12 Jan 20 2022
float precision = 32 bits
verbose(4): input channels = 2, output channels = 2
port 12780
Waiting for connection request...
... connected

**Comment by alfonso73** [comment]
> > 
> 
> @Lucarda nope it doesn't quit.

I was wrong...it just need several seconds

**Comment by alfonso73** [comment]
> 

but it hangs, freeze and doesn't quit if i turn off DSP before trying to quit PD

**Comment by Spacechild1** [comment]
> > Can you try to run my binaries (`pd.com`) in `cmd.exe` and post the console output?
> 
> Pd-0.52.1 ("") compiled 16:38:12 Jan 20 2022 float precision = 32 bits verbose(4): input channels = 2, output channels = 2 port 12780 Waiting for connection request... ... connected

There is no console output when you quit Pd???

**Comment by Spacechild1** [comment]
@alfonso73 Here are some more verbose binaries: [pd-0.52.0-pa-fix2.zip](https://github.com/pure-data/pure-data/files/7906881/pd-0.52.0-pa-fix2.zip)

Please post the console output.

**Comment by alfonso73** [comment]
> > > Can you try to run my binaries (`pd.com`) in `cmd.exe` and post the console output?
> > 
> > 
> > Pd-0.52.1 ("") compiled 16:38:12 Jan 20 2022 float precision = 32 bits verbose(4): input channels = 2, output channels = 2 port 12780 Waiting for connection request... ... connected
> 
> There is no console output when you quit Pd???

no output in console when i quit Pd....

**Comment by alfonso73** [comment]
this is what i have when quit PD with DSP on

glob_exit
sys_close_audio
Pa_Terminate

the process take quite a few seconds after i hit quit (around 5 to 10 seconds)

BUT if i turn the DSP off before quit 
i have no console output and PD hangs and doesn't quit anymore.
There's something related to the DSP checkbox toggle and the ASIO driver that have some strangeness...

**Comment by Spacechild1** [comment]
> the 3rd one Pa_Terminate

I'm confused... the console output after closing the Pd with my latest binaries should be:
```
glob_exit
sys_close_audio
sys_close_midi
sys_closesocket
sys_term_audio
Pa_Terminate
exit
```

Please post the *full* console output.

> There's definitely something not working while turning off the (i guess) portaudio system connected to ASIO driver.

Could it be that you have `callbacks` enabled? That would explain everything... When I start DSP with `callbacks` enabled, I am not able to close Pd, either.

**Comment by alfonso73** [comment]
> > the 3rd one Pa_Terminate
> 
> I'm confused... the console output after closing the Pd with my latest binaries should be:
> 
> ```
> glob_exit
> sys_close_audio
> sys_close_midi
> sys_closesocket
> sys_term_audio
> Pa_Terminate
> exit
> ```
> 
> Please post the _full_ console output.
> 
> > There's definitely something not working while turning off the (i guess) portaudio system connected to ASIO driver.
> 
> Could it be that you have `callbacks` enabled? That would explain everything, including the different console output. For the record: when I start DSP with `callbacks` enabled, I am not able to stop DSP or close Pd, either. The callback scheduler is actually broken and needs to be fixed. (It's on my list.)

oh my goodness...yes...i've got 'callbacks' activated (it seemed to guarantee better ASIO stability at low buffer size...i work at 64 usually). I've disabled and i have the same console output and obviouslt pd quits regularly

glob_exit
sys_close_audio
sys_close_midi
sys_closesocket
sys_term_audio
Pa_Terminate
exit

what is 'callback' done for?

**Comment by alfonso73** [comment]
indeed i have more ASIO stability with 'callbacks' on....with 'callbacks' off i have several glitches in audio at 64 buffer size...

**Comment by Spacechild1** [comment]
> what is 'callback' done for?

With `callbacks` enabled, Pd runs direcly in the audio callback. That's what audio applications typically do, but they also have to follow strict realtime safety guarantees. Pd, on the other hand, does various things that you shouldn't do on the audio thread (e.g. allocating memory). With the polling scheduler (= default) Pd runs in a different thread and communicates with the audio thread via an additional ring buffer. This allows for a certain tolerance to CPU spikes and other irregularities. It is generally the "safer" option, but it also adds additional latency.

> with 'callbacks' off i have several glitches in audio at 64 buffer size...

Without `callbacks`, you have to adjust the `Delay (ms)`. Increase this value until the audio stream seems to be stable.

**Comment by Spacechild1** [comment]
I am closing this in favor of https://github.com/pure-data/pure-data/issues/1554

**Comment by alfonso73** [comment]
> I am closing this in favor of #1554

fine!
