### ISSUE TITLE
fix callback scheduler (= "Callbacks" in the audio settings)

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#1554]
Currently, the callback scheduler has a few issues:

* cannot stop DSP resp. switch to the polling scheduler
* with portaudio, attempting to quit Pd while DSP is running causes a dead lock

We should make sure that we do not directly close the stream within the callback itself but instead signal the main thread. With proper thread synchronization, it should also be able to turn DSP off or switch to the polling the scheduler.

I want to do a PR with several scheduler fixes and this will be part of it. I just add this here for reference (and to remind myself :-)

**Comment by reduzent** [comment]
This is addressed by #1756
