### ISSUE TITLE
iemgui objects trigger Tcl error when sending label msg with double quotes

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1559]
Sending a `label` message containing  double quotes to a iemgui object like [cnv], [hsl], etc. triggers a Tcl error on the Pd window:

```
(Tcl) UNHANDLED ERROR: extra characters after close-quote
    while executing
".x55b1ffb49040.c itemconfigure 55b1ffb544e0LABEL -text [::pdtk_text::unescape ""s"
    ("uplevel" body line 23)
    invoked from within
"uplevel #0 $docmds"
``` 
After triggering that messages, (many) iemgui objects are not visually updated anymore, though still trigger messages when clicked. [tgl]s are still updated(?)

**Comment by reduzent** [comment]
Tested on on current master (bad155d26c) on Ubuntu 20.04.

**Comment by reduzent** [comment]
Pd 0.51-4 doesn't exhibit the problem.

**Comment by reduzent** [comment]
Also, the problem only occurs through the `label` message, but not when setting the label through properties.

**Comment by umlaeute** [comment]
afaict this was introduced with fcd13008d (@HenriAugusto), where the curly-quotes where replaced with double-quotes.
