### ISSUE TITLE
[list store]: 'get'ting out-of-bound elements segfaults Pd

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1564]
When using '-1' as the second argument to the `get` method, accessing out-of-bound elements of [list store] segfaults Pd:

![list-store-bug](https://user-images.githubusercontent.com/333373/150859519-82c9e2e2-aa84-4b43-9f5f-0f3a0c05c1a9.png)

Tested with current master (bad155d26cceead85e845da4f7c3d41498ea0574).

**Comment by Spacechild1** [comment]
Thanks for the report! Should be fixed with ffb9cf35556a4acfb169daa432252cafab499e40

**Comment by reduzent** [comment]
Thanks for the fix. I confirm it is fixed.

**Comment by reduzent** [comment]
BTW: should this issue be labelled correctly for later reference?

**Comment by reduzent** [comment]
Ah, I understand that fixed issues get the label pending, but stay open until merged to master

**Comment by Spacechild1** [comment]
Let's keep the issue open until the develop branch gets merged :-)

**Comment by Spacechild1** [comment]
merged to master
