### ISSUE TITLE
"file join" crash pd on some string length's

### ISSUE THREAD

**Issue by ritsch** [pure-data/pure-data#1572]
Using pd 0.52.1 Debian backports on amd64 architecture:
feeding with
"list vrr remote_musician.pd" and "list vrr remotes_musicianss.pd" -> works
"list vrr remote_musicians.pd" and "list vrr remotes_musicians.pd" -> crash pd

```
~/src/pure-data/bin/pd abs/join_error.pd 
free(): invalid next size (fast)
Pd: signal 6

```
[join_error.zip](https://github.com/pure-data/pure-data/files/8017063/join_error.zip)

**Comment by umlaeute** [comment]
confirmed.
thanks for finding this.

**Comment by umlaeute** [comment]
a quick fix is to use the *file*-library which has considerably rewritten the `[file join]` logic and does not exhibit the problem. 

get it from https://git.iem.at/pd/file and load it explicitely ("`pd -lib file`"). this is the base repository i develop and *test* the `file` family of objects)  i'll later commit a PR for puredata to update to the latest and greatest `file`.

i'll also try to chase down the bug and commit a short-term bugfix into `develop`

**Comment by umlaeute** [comment]
fwiw, i've uploaded a fixed version to Debian/bullseye-backports
