### ISSUE TITLE
2nd outlet of [file join] seems to be inactive and is not documented

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1584]

**Comment by porres** [comment]
please, why 'wontfix'?

**Comment by umlaeute** [comment]
because i won't fix it :-)

the 2nd outlet is *currently* dead, and i won't remove it (as it makes the C-code much cleaner).

**Comment by abreubacelar** [comment]
maybe we could document it as a special case? like all file objects have 2 outlets (because this makes the c code cleaner, but this could be expressed to the user as something like "for technical reasons") and then we just explicitly put "inactive" for the ones that don't do nothing

**Comment by porres** [comment]
>  I don't see how you can come up with something useful for it :)

perhaps a flag to say if it's a file or directory as in other objects?

**Comment by Spacechild1** [comment]
let's just document that the second outlet is (currently) not used.

**Comment by Spacechild1** [comment]
> will this enable anybody to do something they wouldn't be able to do otherwise?

No, but people might wonder what the outlet is supposed to do, ask on the mailing list, file bug reports, etc. Therefore I think it's a good idea to document it.

**Comment by umlaeute** [comment]
yeah. probably.

though i think the current amount of discussion will suffice for the next decade :-)
(we had this unused `[loadbang]` inlet for years, and the issue came up every now and again; but probably no more than 3 times (i'm just making this number up))

**Comment by porres** [comment]
similarly, I never noticed bang~ had an inactive inlet until I did this crazy revision for adding references... anyway, it doesn't hurt to mention it is inactive and I did have to write something, so I put this "dead/inactive"

![Screen Shot 2022-03-08 at 10 20 36](https://user-images.githubusercontent.com/5360142/157246281-ad0088ce-a43e-4cd8-8572-3bc81ffccc4f.png)

**Comment by umlaeute** [comment]
my point is solely, that nobody is forcing you to "write something".
there is no greater entity, that **forces** us to document every single bit of dead code (or eastereggs¹).

anyhow, if you are happy with the current description, so be it (though now that i see it, i would prefer a simple "inactive")

¹ we probably should have "more" of those; but due to their very nature they must not be documented; :thinking:
