### ISSUE TITLE
Jack - DSP and GUI freeze if delay is set too low

### ISSUE THREAD

**Issue by brunorohde** [pure-data/pure-data#1587]
As discussed on Pd-list, I noticed that Pd stops working (DSP and GUI freeze) with Jack if the delay is set to less than Jack's blocksize with callbacks OFF. With callbacks ON it works normally. 

My system info:
- Pd 0.52-1 
- Ubuntu 20.04
~~~console
$ uname -a
Linux brunorohde-desktop 5.13.0-35-lowlatency #40~20.04.1-Ubuntu SMP PREEMPT Mon Mar 7 10:14:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
~~~

Quoting Roman Haefeli on the [pd-list](https://lists.puredata.info/pipermail/pd-list/2022-03/131021.html):

> Indeed, if the buffer is set too small, then Pd GUI freezes!
> From my anecdotal testing, it looks like the critical value is
> predictable. As Christof said, the buffer cannot be smaller than JACK's
> blocksize.
> For instance with JACK @ 256 samples @ 44.1kHz (5.8ms):
>   - Pd works with 6ms
>   - Pd freezes with 5ms

There is already a solution being discussed on the list, but we agreed that it was worth opening an issue.

**Comment by Spacechild1** [comment]
Should be fixed with https://github.com/pure-data/pure-data/pull/1586/commits/f7e1bf71ca063d5651998b05ac770178c6143b51.

I will close this issue once develop gets merged into master.
