### ISSUE TITLE
clicking subpatcherized [bang( crashes Pd

### ISSUE THREAD

**Issue by rolfmeesters** [pure-data/pure-data#1588]
create a [bang( message. subpatcherize it through the edit-menu. open the sub-patch, click on the [bang(, et voila.
this happens on Windows 10 , Pd 0.52.1.
(of course i discovered this with a more useful subpatch).

**Comment by umlaeute** [comment]
patcherize is not part of Pd, but installed via a GUI-plugin.

the issue is known and reported as https://git.iem.at/pd/punish/-/issues/1
