### ISSUE TITLE
libpd_start_gui / libpd_stop_gui: closing Pd closes the host software

### ISSUE THREAD

**Issue by jcelerier** [pure-data/pure-data#1601]
Copy of https://github.com/libpd/libpd/issues/337 as I originally thought that it was the correct place for it :

Hi,
it's very simple:
if one opens the Pd GUI with libpd_start_gui, and then closes the Pd window, the whole software goes away because this calls glob_exit() in s_inter.c which in turn calls exit().

I tried to experiment by replacing that function with a call to sys_stopgui(); ; that seems to work but I am getting double frees if I open, close, open, close, the gui on a single instance, and then call libpd_closefile when I'm done.

**Comment by Spacechild1** [comment]
The actual problem is `glob_exit` just calls `exit` - which of course terminates the program. Instead it should just break from the scheduler loop. In libpd, this would simply have no effect.

**Comment by jcelerier** [comment]
It seems to have been fixed recently, works fine now :)
