### ISSUE TITLE
[text]: document the meaning of "line"

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#1604]
From `[text get]`:

> "text get" reads the nth line from the named text and outputs it.

From `[text size]`:

> "text size" reports the number of lines in the text or the length of a specified line.

And so on.

Now, one would think that "line" would mean, well, "line of text". Turns out that comma seperated messages count as seperate "lines"! 

I think the word "line" is very confusing in this context, because what is actually meant is: "message, terminated by either a semicolon or a comma".

Consider the following text:
```
1 2 3;
5 6 7, 8 9 10, 11 12 13;
14 15 16;
```
When looking at the text window, one would intuitively think that there are 3 lines, but it is really 5 "lines".
For example, `[3( -> [text get]` would output `11 12 13`.

I think this should be clarified in the documentation! @porres to the rescue!

**Comment by porres** [comment]
instead of defining the meaning of line I'm changing the description to "message" instead of "line" and I am saying that messages are separated either by commas or semicolons.

**Comment by porres** [comment]
ouch, [text sequence] has a 'line' message :(

**Comment by porres** [comment]
> ouch, [text sequence] has a 'line' message :(

don't know what to do here other than say that 'line' means 'message number' and propose a new 'message' method to replace this for being more meaningful.
