### ISSUE TITLE
Dynamic Patching help does not mention the use of $0 in subpatch names.

### ISSUE THREAD

**Issue by ulioidle** [pure-data/pure-data#1613]
Nor does it use them which could suggest they are unneeded to those just learning. Seems like it should at least be mentioned since sending a clear or dis/connect can make a mess of things in any open patches with a sub-patch of the same name.

**Comment by porres** [comment]
screenshot from the [pd Data-Structures] subpatch inside [pd Dynamic-Patching] subpacth in pd-messages.pd file.

can we close this?

![Screen Shot 2022-04-06 at 00 05 46](https://user-images.githubusercontent.com/5360142/161888077-284f9351-fd92-4139-a103-31ea6ba019a2.png)

**Comment by porres** [comment]
> screenshot from the [pd Data-Structures]

which says **clear, vis, read, write, scalar (Data Structures) and "$0":**

**Comment by Ant1r** [comment]
I see it also says: "open first **examle** of the 4.Data.Strucrure section" btw...

**Comment by ulioidle** [comment]
I have no idea how I missed that, I looked through twice before opening this, I guess I must have saw Data Structures and nothing else. Sorry about that, at least it brought attention to a critical typo.

**Comment by porres** [comment]
typo fixed, thanks
