### ISSUE TITLE
(feature request) GUI object "box"

### ISSUE THREAD

**Issue by rolfmeesters** [pure-data/pure-data#1626]
feature request

i'm missing a GUI object (it could be named "box"), which is clickable like BANG, with the layout possibilities of a CNV, but with lines around it.

(some people simulate this by placing a 'bang' under a cnv).

actually, TOGGLE could do the work if it's borders were not fixed to a square.

rolf

**Comment by porres** [comment]
It seems unclear to me what you want, and it seems unlikely, for what I can see, that something this makes it in, seems like a very special case. Nonetheless, can you please elaborate? I could try and make that an external. By the way, have a look at else/messbox, see if that's kinda close to what you want.

**Comment by reduzent** [comment]
You can turn a slider into a bang like this:

```
[__| _________]
|
[select 0]X[t a]
```
If you make sure, that the handle has the same color as background, you get a clickable rectangle that only emits bangs when clicked.

That is an idiom I use _a lot_.

**Comment by porres** [comment]
oh, if it's just a button you need, and if you can use externals, see [else/button], but roman's hack seems clean and it's pure vanilla

**Comment by rolfmeesters** [comment]
Roman Haefeli schreef op 14-04-2022 12:18:

> You can turn a slider into a bang like this:
> 
> [__| _________]
> |
> [select 0]X[t a]
> 
> If you make sure, that the handle has the same color as background, you get a clickable rectangle that only emits bangs when clicked. 
> 
> That is an idiom I use _a lot_. 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>

you're right, it's possible to turn a slider into this 'general purpose
gui box' i'm talking about. 

 apparently i'm not the only one who feels a need for it. 

i can live with your solution. 

thanx, 

rolf 

Links:
------
[1]
https://github.com/pure-data/pure-data/issues/1626#issuecomment-1099009280
[2]

**Comment by porres** [comment]
please close the issue then if you're happy with the solution or the use of externals

**Comment by rolfmeesters** [comment]
porres schreef op 16-04-2022 19:15:

> please close the issue then if you're happy with the solution or the use of externals 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>

sorry, i don't know how to do that. 

rolf 

Links:
------
[1]
https://github.com/pure-data/pure-data/issues/1626#issuecomment-1100712144
[2]

**Comment by porres** [comment]
![Screen Shot 2022-04-18 at 13 39 11](https://user-images.githubusercontent.com/5360142/163841416-90d764d6-7429-429e-a994-6c13b1a79239.png)
