### ISSUE TITLE
Use "move" for IEMGUIs / Text Objects / Data Structures' Scalars and graphs instead of redrawing or using 'coords'

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1628]
for example, in [bng] https://github.com/pure-data/pure-data/blob/master/src/g_bang.c#L84 it doesn't use simpler and better 'move' code as gatoms use (see https://github.com/pure-data/pure-data/blob/master/src/g_text.c#L1049)

Edit: Scalars and graphs should also be optimized, see discussion below.

It is more efficient to just "move" than recreate and redraw things.

**Comment by porres** [comment]
by the way, I tried checking how Data Structures work when "displacing" but couldn't actually find it...

**Comment by sebshader** [comment]
I think it's for supporting tcl/tk 8.4. Maybe it's time to drop that support..

**Comment by sebshader** [comment]
text_drawborder in g_text.c also uses "coords" instead of "move"

**Comment by porres** [comment]
> it seems like data structures (and arrays) are just redrawn

where? that's quite bad huh?

**Comment by sebshader** [comment]
@porres I think for instance scalars are in g_scalar.c scalar_displace which seems like it just updates the coordinates and then calls scalar_redraw

for garrays & graphs there is graph_displace which calls glist_redraw

**Comment by porres** [comment]
> there is scalar_displace in g_scalar.c which seems like it just updates the coordinates and then calls scalar_redraw

Yeah, that's it, I see it, well, we could have it call a new "scalar_move" function instead  of "scalar_redraw", it should be much more efficient. And in fact, when moving lots of Data Structures Scalars, I can see them getting redrawn and it's very very slow!!!

**Comment by porres** [comment]
> for garrays & graphs there is graph_displace which calls glist_redraw in g_graph.c I wonder if there could be a glist_displace...

Yup, I can also see that! But I need help figuring clarifying this. Does this mean that when moving abstractions aroung with "graph on parent" they all get redrawn?

**Comment by sebshader** [comment]
> Yup, I can also see that! But I need help figuring clarifying this. Does this mean that when moving abstractions aroung with "graph on parent" they all get redrawn?

yes. but usually widgetbehaviors have a "displace" so I'm not sure why that's not being used in a glist_redraw.. maybe some z-ordering/clipping thing?

**Comment by porres** [comment]
> maybe some z-ordering/clipping thing?

why? what do you mean?

Also... "scalar_redraw" is also called when doing "change", like clicking and dragging on a shape (polygons). This is the case where we could use the "coords" message maybe?

**Comment by porres** [comment]
> it doesn't use simpler and better 'move' code as gatoms use (see https://github.com/pure-data/pure-data/blob/master/src/g_text.c#L1049)

funny enough, the "move" code in https://github.com/pure-data/pure-data/blob/master/src/g_text.c#L1055 is not what actually "moves" the gatom and it also gets redrawn in text_drawborder called in text_displace at https://github.com/pure-data/pure-data/blob/master/src/g_text.c#L1053

I can only assume the "move" command is useless and unused...

**Comment by porres** [comment]
> I can only assume the "move" command is useless and unused...

this moves the gatom's label, that's all, anyway, did my first change that takes care of all text objects at https://github.com/porres/pure-data/commit/de4effc47feee43710de16e1e8931d27d55ec1e4

**Comment by porres** [comment]
> yes. but usually widgetbehaviors have a "displace" so I'm not sure why that's not being used in a glist_displace instead.. maybe some z-ordering/clipping thing?

I don't think there's  z-ordering issue, it's just an oversight, just like with the other objects, and I believe that the 'move' command in tcl/tk is relatively new, so...

Anyway, I am working on a glist_displace instead, it's working, I can move the graph and its inlets, the only thing is that all the graph objects ("gobj") inside it still get redrawn, with 

```
                gobj_vis(g, x, 0);
                gobj_vis(g, x, 1);
```

much like in https://github.com/pure-data/pure-data/blob/master/src/g_graph.c#L656

I'm doing this cause I don't know better

there's a gobj_displace code in https://github.com/pure-data/pure-data/blob/master/src/g_canvas.c#L71

but if I use that, the objects get displaced alright when moving the graph on the parent but they also get moved inside the abstraction, which screws things up...

I still think that redrawing "gobj" objects is not ideal, but we can think of a way not to do that later...

I guess I'll save the commit for the graph displace for now, let me still try it a bit more and think a little more.

In the meantime I can move on to iemguis, which seem easy

**Comment by porres** [comment]
closing in favor of https://github.com/pure-data/pure-data/issues/1634
