### ISSUE TITLE
`libpd_start_gui` fails on Windows

### ISSUE THREAD

**Issue by alisomay** [pure-data/pure-data#1630]
Running `libpd_start_gui` in 64 bit Intel Windows 10 yields the following error.

localhost not found (inet protocol not installed?)
Either the application has not called WSAStartup, or WSAStartup failed

I don't plan to debug this since I can't imagine a case yet why a user would need this feature yet and also not very experienced in Windows platforms.
Although I think it is worth to note it here for some other people who might need this functionality.

I've tested it in a Github Action runner and an AWS instance through remote desktop.
If a reader of this can make it work, I'd love to hear how to.

@danomatika suggested me to open the issue here, since `libpd_start_gui` uses a core function to achieve this functionality.

https://github.com/libpd/libpd/issues/352#issuecomment-1101600164

**Comment by Spacechild1** [comment]
This can either be fixed in the core or in libpd. See my reply: https://github.com/libpd/libpd/issues/352#issuecomment-1101778095

> since I can't imagine a case yet why a user would need this feature yet and also not very experienced in Windows platforms.

Without calling `WSAStartup`, all the networking objects wouldn't work either...

**Comment by Spacechild1** [comment]
This appears to be fixed now in libpd, see https://github.com/libpd/libpd/issues/352
