### ISSUE TITLE
feature request: use fontsize to determine iemgui's default size

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1638]
iemgui's have a single default size (e.g. `15`).

this default aligns nicely with a font-size of **8**, but I find myself to user bigger fonts these days (my age is showing; and laptop screens seems to get smaller every year; and when teaching, I prefer to have large fonts as well).
this means, that whenever I create an iemgui, it looks very disproportional, like so:

![guisize](https://user-images.githubusercontent.com/214034/164538995-81d737b6-2520-4881-b14f-ca161204c06f.svg)

i therefore suggest to use the canvas' font-size to establish a base size for iemguis (larger fontsize -> larger iemguis)

i also think, that the font-size of iemgui labels should match the patches font-size.

note that i'm only talking about the defaults when creating a new iemgui object.
the size (and label font-size) are then stored in the patchfile, and changing the canvas' font-size shouldn't do anything to them.

**Comment by porres** [comment]
I also proposed that in https://github.com/pure-data/pure-data/issues/920 which has similar and parallel discussion

**Comment by porres** [comment]
> I also proposed that in https://github.com/pure-data/pure-data/issues/920 which has similar and parallel discussion

oh, and I did some work here as well --> https://github.com/pure-data/pure-data/pull/946 perhaps the same PR could be used for this

**Comment by porres** [comment]
> I also proposed that in https://github.com/pure-data/pure-data/issues/920 which has similar and parallel discussion

actually I just proposed it'd use Pd's default font size, but using the patch's font size is indeed more proper and better. But anyway, if you're going for it in your new PR for refactoring iemguis, please also take into consideration this PR of mine for cherry picking as I think it is related.

**Comment by porres** [comment]
for the record, my gihub desktop app seems to be ruined and that's what caused the problem, I can't commit even to my usual documentation branch. Will reinstall this thing, sorry for the noise, please delete all messages regarding this.

**Comment by umlaeute** [comment]
this needs some more tinkering:
- misbehaves when zoomed
- label offsets
- numbox-height ought to adjust
- should slider-height (resp. width for horizontal sliders) also adjust to the font-size?
