### ISSUE TITLE
Patch window title path stripped of slashes on Windows

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#164]
On Windows. it looks like the string encoding from the Pd core to the GUI strips the Windows backslashes from the Patch path displayed in the Patch window titlebar.

I don't have a screenshot, but it basically looks like:

    Untitled C:UsersNameDocumentsPd

When it should be

    Untitled C:\Users\Name\Documents\Pd

I can confirm the string is sent to the GUI without the slashes.

**Comment by Spacechild1** [comment]
This only happens when starting Pd from the GUI and creating a new canvas from the menu. The bad path actually comes *from* the GUI (passed to `glob_menunew`).

**Comment by umlaeute** [comment]
with `canvas` you mean `window`? (that is: <kbd>Ctrl</kbd>+<kbd>N</kbd> rather than <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>C</kbd>)

**Comment by danomatika** [comment]
I assume this is fixed by now. Can someone confirm?

**Comment by Lucarda** [comment]
for me it works. Windows11 Pd 0.54-0

![windowstitle](https://github.com/pure-data/pure-data/assets/25239522/e3e3c47d-95b4-4849-9447-0a2fb208e47a)

**Comment by danomatika** [comment]
Thanks for the confirmation. Closing.
