### ISSUE TITLE
clock_unset occasionally segfaults

### ISSUE THREAD

**Issue by sebshader** [pure-data/pure-data#1658]
There was a patch from the discord recently that crashed pd, from bng_bang clock_delay (for the flash). After running it through lldb it seems like it's happening in clock_unset trying to access x2->c_next.

using "frame variable" it looks like x2 is 0. Could the end of the scheduling list be 0 somehow? (I know c_next is set to 0 in clock_new..)
edit: it looks like the main body of "clock_unset" shouldn't do anything if the clock isn't on the list..hmm

**Comment by sebshader** [comment]
doing "frame variable x->c_settime" gives
```(double) x->c_settime = 30092047126.760506```
"target variable pd_maininstance.pd_clock_setlist" ->
(_clock *) pd_maininstance.pd_clock_setlist = 0x00000001021b3470

after checking everything on the scheduling list, the clock being unset is not present. this seems like some kind of ordering issue where one thing is modifying the scheduling list before the last thing was taken off or something.

**Comment by umlaeute** [comment]
> There was a patch from the discord recently that crashed pd

please provide the patch.

in general, there are operations that are not re-entrant safe, e.g. clearing a canvas with objects that are currently being executed.

**Comment by sebshader** [comment]
I was going to try to make it more isolated but I'm not sure I even could.. patch uses a couple of externals: mp3cast~ from unauthorized (not needed to reproduce the bug), and purest_json

It can take awhile to segfault (anywhere up to an hour in my experience)
[clock_unset_segfault.zip](https://github.com/pure-data/pure-data/files/8599608/clock_unset_segfault.zip)

**Comment by umlaeute** [comment]
urgh, i see.

thanks for sharing, but if you manage to isolate the problem some more, that would be very welcome :-)

**Comment by umlaeute** [comment]
and thanks for giving me some holiday memories :beach_umbrella: :fog:

**Comment by umlaeute** [comment]
my first quick *guess* would be a problem with [PuRestJson](https://github.com/residuum/PuRestJson/), emitting messages from a thread callback.

that is entire guesswork, but
- PuRestJson uses threading
- your description ("It can take awhile to segfault") hints at a race condition

**Comment by sebshader** [comment]
I thought it might be something like that but it doesn't seem like PuRestJson does anything w/ clocks.. or I guess you're saying that purest json is triggering some pd code?
i should also mention: only tested on MacOS so far afaik (catalina here)

**Comment by umlaeute** [comment]
my hypothesis is:
- PuRestJson uses threads
- within the context of such a thread, it calls some callback
- this callback then triggers `outlet_anything()` or similar, and thus starts a new message that runs in a different thread without proper locking

**Comment by umlaeute** [comment]
probably we should ping @residuum for their input...

**Comment by residuum** [comment]
As @umlaeute has guessed, PuRestJson uses threads for HTTP calls via libcurl to not block execution while data is still loaded. 
When data is fully loaded, it calls `outlet_symbol()`, `outlet_float()` and / or `outlet_bang()`.
Before diving deeper into the Pd code, what does `clock_unset` do, and how should externals react to it?

**Comment by Spacechild1** [comment]
@residuum You can't call Pd API functions from a different thread without proper synchronization. This will lead to data races and crashes. I had a quick look at purestjson and my impression is that there isn't any thread synchronization at all...

There are two general approaches:
1. use `sys_lock`/` sys_unlock` before/after API functions from a different thread
2. push the result to a thread-safe queue + regularly poll the queue with a clock from Pd's main thread.

**Comment by residuum** [comment]
@Spacechild1 Thanks for the head up. I have wrapped all possible calls with sys_lock() and sys_unlock(). I will now try to get the automatic builds running again to release a possible bugfix ASAP.

**Comment by Spacechild1** [comment]
@residuum Cool!

BTW, if you want your external to run in multi-instance Pd (= `PDINSTANCE` is defined), make sure that you set a Pd instance in your worker thread; otherwise many API function calls will segfault.

See for example: https://github.com/pure-data/pure-data/blob/18c9695ba4de543c51c2c013b45b99b8f1c35a19/src/d_soundfile.c#L1683-L1685

(it's cleaner to do `pd_setinstance(x)` instead of `pd_this = x`)

**Comment by residuum** [comment]
Thanks to @sebshader all calls in threads are surrounded by `sys_lock` and `sys_unlock`. 

Moving to Circle CI instead of Travis CI is on the way, currently the linux-amd64 packages are building, but the code should compile locally.

IMHO this issue can be closed.
