### ISSUE TITLE
extending overall pure data default package with state of the art extensions

### ISSUE THREAD

**Issue by tiagmoraismorgado** [pure-data/pure-data#167]
**I would suggest that we consider to:**

- _extending overall pure data default package with state of the art extensions;_

**by doing so:**

- _making a pretty comprehensive set of collections of patches, abstractions, externals, extra documentation, etc._

**Comment by danomatika** [comment]
This is what deken is for: installing compiled externals. It's up to users to add the missing libraries there. Pd vanilla will not become a new Pd-extended and include everything internally, as far as I know.

**Comment by tiagmoraismorgado** [comment]
i recognize the importance of deken. but i think there should be an extensive compilation of opensource material for pure data available in one optional package by default

**Comment by danomatika** [comment]
There has been some talk of providing a meta package to install a large set of libraries in one go. I would open an issue on the [deken repository](https://github.com/pure-data/deken) as this is more related to that project then to the core of Pd here.

**Comment by porres** [comment]
sounds like something you could do and upload to deken

**Comment by umlaeute** [comment]
i agree that this issue should be moved to [deken](/pure-data/deken)
