### ISSUE TITLE
route still outputs a list selector even if the output is a float

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1674]
this bit me cause I have an object with a list and a float method but if I have something like 

"2 3" into [route 2], what comes out is "list 3" and the object doesn't think it is a float.

or am i doing something wrong?

**Comment by Spacechild1** [comment]
A float message is really the same thing as a list message with a single float atom. 

> this bit me cause I have an object with a list and a float method 

This doesn't sound right. If you have a list method, why would you need a float method? The list method already handles float messages. I mean, you *can* also have a float method, but you shouldn't attempt to differentiate between float messages and single-element-lists!

**Comment by porres** [comment]
I wondered if this happened to me before and we ended up discussing it here, but I couldn't/can't find the issue... now that you replied this my belief is stronger...

> A float message is really the same thing as a list message with a single float atom.

how so? Why then I need to pass the output of [route] into [float] so I can get a proper float output into my external (that's the solution I've found)? To me this means both messages are different.

**Comment by porres** [comment]
moreover, would you oppose to having [route] output a 'proper float'?

**Comment by Spacechild1** [comment]
> Why then I need to pass the output of [route] into [float] so I can get a proper float output into my external

because you're external is broken (as I tried to explain above).

**Comment by Spacechild1** [comment]
For example, `[route]` treats a list with a single float atom as a float message. Try this:

![grafik](https://user-images.githubusercontent.com/16126632/170897162-4214ecf0-19ec-4f72-b8e0-fbecdab43171.png)

> moreover, would you oppose to having [route] output a 'proper float'?

I don't mind, but I don't see the need. For any well-behaving object it wouldn't make a difference.

**Comment by porres** [comment]
what you seem to say to me is that a float message is in fact different from a list message with a single float element, hence the list and float methods will pick them up separately, but we, as developers, should know that and work it out...

I can't see how a list message with one element is the same as a float message

anyway, this also seems like something to be cleared out in the documentation somewhere

**Comment by porres** [comment]
> I don't mind, but I don't see the need. For any well-behaving object it wouldn't make a difference.

I also don't see why it should output a list with a single element, as if there's a use case for it. It looks like it's a misbehave to me, even though we should watch for it...

**Comment by Spacechild1** [comment]
> what you seem to say to me is that a float message is in fact different from a list message with a single float element, hence the list and float methods will pick them up separately, but we, as developers, should know that and work it out...

Yes, technically they are different (i.e. they have a different selector), but conceptually they are the same. Again, if you have a list method, there's no real point in having a float method; if there's only a list method, the problem doesn't arise in the first place.

**Comment by Spacechild1** [comment]
> I also don't see why it should output a list with a single element, as if there's a use case for it. It looks like it's a misbehave to me, even though we should watch for it...

You might call it laziness :-) But again, your external should be able to handle it. There are other cases where an object might output a list with a single-float, for example:
![grafik](https://user-images.githubusercontent.com/16126632/170898417-b57551e3-283a-4e9d-97bd-f4ca2a338a30.png)

**Comment by porres** [comment]
> But again, your external should be able to handle it.

I get that! ;) my concern is now on the documentation aspect of this...

> anyway, this also seems like something to be cleared out in the documentation somewhere

actually, the help file of [route] is a place that documents how pd will automatically convert something like "list 5" to a "float" message. That is not true... !!! It is true for [route] but it's not like "Pd does this automatically", in a sense that it checks the message and converts it...

I am of course the culprit here and I was misguided and got confused at some point... 

This is what the earlier documentation of route said:

"To avoid confusion between, say, the number 5 and the list containing only the number 5, both messages match "float", and ditto for symbols. An empty list matches "bang". In Pd these are all considered special cases of lists."

That kinda gives me the idea that these are special kinds of lists that get converted somehow... the documentation of Pd-extended was also rather ambiguous... 

There is not any documentation out there that clarifies how these are technically different but conceptually the same, and how Pd handles this or not...

> You might call it laziness :-) 

Ok, well, I already have a PR for this, so I'll just keep it... (actually I should also handle this in the rejected outlet)... as the documentation maniac person around here, if we don't get this done, I will feel like documenting how [route] still keeps the list selector :)

**Comment by porres** [comment]
Oh well, I now see another issue... if we have a "bang" input or an empty list (a simple "list" message) into a [route] object with float arguments (say, like: [route 4]), nothing comes out! I guess a bang message should come out the rejected outlet..

do we officially have a bug now? :)

**Comment by Spacechild1** [comment]
> There is not any documentation out there that clarifies how these are technically different but conceptually the same, and how Pd handles this or not...
> I will feel like documenting how [route] still keeps the list selector :)

Don't bother. This distinction is not relevant for Pd *users* because every well-behaved Pd object will treat lists with a single float atom the same as float messages. It's only relevant for external authors, so a better place to document this would be https://github.com/pure-data/externals-howto.

I have to admit I'm not a big fan of #1678. It adds complexity, but I don't really see the benefit. After all, the actual problem was in your external. Once you've fixed that, there is no need anymore to change the implementation of `[route]`...

**Comment by porres** [comment]
> Don't bother. 

I should bother at least to better clarify this in the help file of [route]. The help file of [list] would also be a nice place to clarify this as it already tries to explain in detail what a list is in "[pd about-lists]", but we can discuss this in https://github.com/pure-data/pddp/issues/94

> Pd users only need to know that these messages are somehow equivalent.

also something to be discussed where to be officially mentioned in the docs.

> I have to admit I'm not a big fan of https://github.com/pure-data/pure-data/pull/1677. It adds complexity, but I don't really see the benefit.

I think it's more elegant and harmless, and now it also fixes what I consider a real issue: not rejecting bangs (see https://github.com/pure-data/pure-data/issues/1678).  If it is t obe rejected, a new one should be made just to fix the other issue (or maybe cherry picked by @millerpuckette )

**Comment by porres** [comment]
https://github.com/pure-data/pddp/issues/94#issuecomment-1140666767

"[list trim] keeps the list selector for float, symbol and bang... this behaviour is confusingly explained in the help file and I see no benefit in such a functionality and also if it is worth documenting it..."

**Comment by porres** [comment]
I found a special case where the rule 'an empty list must be treated as a bang'. The list box has a bang method but an empty list doesn't behave like a bang. Hence, a proper message should be output from another object. An empty list in the list box shows an empty list and outputs an empty list. In this case I think this the correct and desired behaviour, the list box should be able to receive and show an empty list as well as output an empty list if it is empty. 

But we have issues with the output of other objects. For instance, if you have a bang into [list trim], an empty list comes out. I would expect that a bang message would come out and force output the contents of a list box, but now it just clears it.

In the same way, if we have something like [route 4] and input a float of '4', I would expect a bang message to come out and force output the contents of a list box, but it just clears the list instead.

I think this is a good argument in favor of https://github.com/pure-data/pure-data/pull/1677 as it fixes the bug for both cases above! I will also check other objects in Pd that may be outputting "wrong" selectors for no real benefit and just because of "laziness".

I guess each case must be examined, and the list box should keep its behaviour. This is also challenging for the documentation part. It was first ambiguous and gave the idea that 'magically" these message got always converted in Pd. I am now making this less ambiguous and specifying that objects "USUALLY" treat empty lists as bangs and one element lists as either floats or symbols, but this is something that a particular object needs to do on its own and this is not a supreme golden rule. I have been taking care of this documentation issue already in 'pddp' and my documentation branch. https://github.com/pure-data/pure-data/pull/1594

I will now better explain the special case of the list box

**Comment by porres** [comment]
> I will also check other objects in Pd that may be outputting "wrong" selectors for no real benefit and just because of "laziness".

So, as I had already noted in https://github.com/pure-data/pddp/issues/94#issuecomment-1140608546 the help file of [trigger] is also wrong and misleading, it says

_the 'list' specifier receives 1-element lists like a float, symbol or pointer input and passes them unaltered. Note that a bang is a 0-element list and is also bypassed_

This is not true, a bang element will become a list with zero elements, so a bang into a [t l] is output as "list" and it also doesn't work as a proper bang into a list box...

So, we totally got the documentation wrong. I think the documentation can be fixed in this case and we should note that a bang or float/symbols become 0/1 element lists.

**Comment by porres** [comment]
> I think the documentation can be fixed in this case and we should note that a bang or float/symbols become 0/1 element lists.

I am actually not sure, now I think that if we're going to output a proper bang via [route], it seems we should also output a proper bang via [trigger list].

The way things go now seems to me like there's a concern on how "weird" 0/1 element lists messages are treated as an input, but whatever goes out is not carefully revised. If the general idea is that these are special cases of lists in Pd and we already take care of it in the input, it doesn't make sense not to care about the conversion on the output side. This is also easier to document and give this as a general rule. The odd one out would only be the list box and it's easy to document this special behaviour.

At least [list trim] should definitely change in order to output something meaninful and avoid counter intuitive things like adding and generating a 'list' selector instead of trimming it (as it's the case for bang, float and symbol input).

**Comment by porres** [comment]
closing this in favor of https://github.com/pure-data/pure-data/issues/1681

**Comment by Spacechild1** [comment]
> I found a special case where the rule 'an empty list must be treated as a bang'. The list box has a bang method but an empty list doesn't behave like a bang.

That's a bug in the list atom. An object should *never* distinguish between a bang and an empty list.

The current documentation correctly states that you need to use the `[set(` message to actually set the atom to an empty list. The list atom's list method should dispatch an empty list to the bang method. Actually, the code comment suggests this is done on purpose:
> `* bang outputs value for float and symbol but clears list */`
but IMO it's wrong nevertheless.

Feel free to fix this in a PR :-)

**Comment by porres** [comment]
> the code comment in gatom_list suggests that the current behavior is on purpose

yup, it clearly tells me this is intentional and I can see the point. This is why I am doing all this, in order to document this and sort parallel things out. See discussion in https://github.com/pure-data/pure-data/issues/1681 - let's move it there.
