### ISSUE TITLE
Anomalies

### ISSUE THREAD

**Issue by emr66** [pure-data/pure-data#1675]
Hello, I am noticing some problems in Pd since I upgraded from Windows 7 to 10 and updated to version 0.51.4 of Pd. The first anomaly with respect to windows 7 and an old version was that now when I create a patch with more than 4 tables and 4 objects, when dragging them I notice a certain slowness (the table or the object is delayed with respect to the mouse pointer) another Anomaly that I have noticed is that when saving an audio file from a table of only about 20ms, Pd takes about 3 seconds until I get the message that it has been saved. Now I have installed the latest version of Pd and I have not noticed any change. I have been told that it may be due to a problem with windows scaling, but I am not sure what I should configure. I must also say that a few days ago I noticed that the clock on my PC was behind about 2 minutes and it could be from the CMOS battery but I don't know if this could have any relation (excuse my ignorance) since I haven't noticed anything strange in DAWS I use.
I would appreciate any help because although at the moment it does not cause me any impediment to work in Pd correctly, it is very heavy and somewhat uncomfortable. thank you!!

**Comment by umlaeute** [comment]
- please do not create accumulative issues, with multiple possibly unrelated "anomalies" (if you are unsure, whether issues are related or unrelated, treat them as if they were unrelated).
- please also use descriptive titles "anomalies" is just a nice word for "bugs", and imagine how "very heavy and somewhat uncomfortable" it would be to work with a issue tracker with 1675 issues titles "anomalies".

i would suggest to close this and start anew with two separate issues ("sluggish GUI response" and "saving audio files takes too long" or somesuch).
i would also like to suggest to use paragraphs to make separate the issue description from environment descriptions (OS versions, Pd versions,...)

and finally: i don't think that your system clock has anything to do with the observed behaviour.
