### ISSUE TITLE
[route] doesn't reject "bang" with float arguments

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1678]
this came up when investigating https://github.com/pure-data/pure-data/issues/1674 see https://github.com/pure-data/pure-data/issues/1674#issuecomment-1140569290

sending a bang into [route] with float arguments should send a bang to the rightmost rejected outet, but nothing happens...

![Screen Shot 2022-05-30 at 18 46 59](https://user-images.githubusercontent.com/5360142/171062213-bc097c0a-8a13-47f6-b5ae-c73131ec861e.png)

**Comment by Spacechild1** [comment]
fixed with 03e30d35a7a623fb3326cef420b52f81161d0c3a
