### ISSUE TITLE
better handle special list cases

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1681]
This is a reboot, earlier discussion is in https://github.com/pure-data/pure-data/issues/1674

Pd is somewhat "lazy" when dealing with selectors and may produce empty or 1 elements lists. For example, the [route] object can get a float message and turn it to a list message containing just one float in the rejected outlet. Other objects with issues are [trigger] and [list trim]. The thing is that most objects will interpret these cases correctly, where a "list 4" is treated as a float, or empty lists are treated as bangs (at least developers should know how to deal with this, but we should be able to minimize this and avoid potential headaches). Also, there are exceptions, like the list box not treating an empty list as a bang but as an actual empty list. Hence, better handling such cases has benefits.

The documentation was also misleading, it used to say that something like a "4" into [route 4] would produce a bang, but it doesn't it generates an empty list. For now, I have changed the documentation to what actually happens but I want to make the case to actually implement objects as we believed they worked like. In short, instead of producing 0 or 1 element lists, object should output floats/symbols or bangs.

Issues I've found:
- Rejected outlet of [route] may change the selector. Like already mentioned, a 'float 4' becomes 'list 4', also, a rejected bang input comes out as an empty list. So if you connect this bang message into a list box, instead of behaving like a proper bang (which would output the list) you turn the list box into an empty list and outputs it.
- While we're at it, matched outlet generate 0/1 element lists, we can just output bangs/floats/symbols instead as the documentation in 0.52-2 says so.
- [trigger] list also produces  0/1 element lists with bang/float/symbol inputs but we can also output bangs/floats/symbols instead as the documentation in 0.52-2 says so.
- [list trim]: this is specially bizarre; a float input becomes a 1 element list, so how an object that supposedly trims the list selector does the opposite thing? There's no use case for this, of course, and this was actually documented!!! I removed that from the documentation I say we just treat this in a sane way where we pass floats and bangs unaltered - yeah, a bang input currently becomes a 'list' message without arguments. 

I will keep my eyes on other objects and the code to see if I find other funny things.

**Comment by porres** [comment]
@Spacechild1, let's discuss this in here, I think it's better.

> there are exceptions, like the list box not treating an empty list as a bang but as an actual empty list. Hence, better handling such cases has benefits.

See, I am assuming the way list boxes differentiate a bang and an empty list is intentional. You think this is a bug, right?

**Comment by Spacechild1** [comment]
> See, I am assuming the way list boxes differentiate a bang and an empty list is intentional. You think this is a bug, right?

It seems to be intentional, but it's a bug nevertheless. See my explanation in https://github.com/pure-data/pure-data/issues/1674#issuecomment-1141489392

**Comment by porres** [comment]
> See my explanation in https://github.com/pure-data/pure-data/issues/1674#issuecomment-1141489392

ok, for the record, I had read the code and saw that a bang would intentionally clear the list because of a comment in 

https://github.com/pure-data/pure-data/blob/18c9695ba4de543c51c2c013b45b99b8f1c35a19/src/g_text.c#L744

@Spacechild1 says this is a bug and should never happen, even if it was intended by @millerpuckette 

I can actually see that and this changes lots of things. I should change and revert my documentation changes and yeah, I can also work on a PR for this. But I should open a new issue for that and maybe reboot this thing here once again...

**Comment by Spacechild1** [comment]
> at least developers should know how to deal with this, but we should be able to minimize this and avoid potential headaches).

Easy: document it [[in ](https://github.com/pure-data/externals-howto)
](https://github.com/pure-data/externals-howto)

After all, I only see two general (rare) cases, where this issue arises:
1. an object has a list method + a float/symbol/pointer method
It's not very typical for an object to semantically distinguish between a list and a float message. I would even say that such an interface is bad design. Also note that a list method alone would be sufficient, as the other messages are automatically promoted to lists.
2. an object has a list method + bang method
Again, a list method alone would be sufficient. But if an object decides to have a dedicated bang method, the list method must forward zero-element-lists to the bang method.

> Also, there are exceptions, like the list box not treating an empty list as a bang but as an actual empty list. Hence, better handling such cases has benefits.

Ok, I think we already seem to agree that this is a bug.

> The documentation was also misleading, it used to say that something like a "4" into [route 4] would produce a bang, but it doesn't it generates an empty list.

There's no practical difference for Pd users.

> For now, I have changed the documentation to what actually happens but I want to make the case to actually implement objects as we believed they worked like. In short, instead of producing 0 or 1 element lists, object should output floats/symbols or bangs.

Again, this is an implementation detail that Pd users shouldn't have to care about. I think that documenting it would even be harmful, as it just adds to the confusion. Instead, let's fix those few buggy objects :-)

> [list trim]: this is specially bizarre; a float input becomes a 1 element list, so how an object that supposedly trims the list selector does the opposite thing?

Again, there's no practical consequence and it's not relevant for the Pd user.

**Comment by porres** [comment]
> There's no use case for this, of course, and this was actually documented!!! I removed that from the documentation

To prove I'm in favor of not over documenting things and that I'm on the same page that documenting these things can be confusing, I complained that the current [list trim] object mentions how it adds list selectors and did remove this from the docs. But the thing is that this was generally confusing and some of this stuff was already documented (and not by me or we, like the [list trim] case).

For instance, in the help file of [route] and trigger we have things like that and they were misleading (at least they threw me off). I'm in favor of making these simpler and more consistent. At some point the user should be aware that bangs correspond to zero length lists and stuff and this has come up a few times, like in the help file of list box, where it did say that bang is a zero length list but you should expect it to output the contents of the list box instead of setting it to a zero length list.

Let me go over things again and revise them a bit more. I'm all up for making things simpler and clearer. I'm just not really comfortable in saying a few things that we were saying, like mentioning that a float input into [route 4] would output a bang in the same way as if it was fed to [sel 4]. That is not true and if we're to say this, we should work on these special cases and provide a compatible output.

**Comment by Spacechild1** [comment]
> I complained that the current [list trim] object mentions how it adds list selectors and did remove this from the docs. 

+1

>  like mentioning that a float input into [route 4] would output a bang in the same way as if it was fed to [sel 4]. That is not true 

Again, from the point of a Pd user it *is* true. For any well-behaved Pd object, there is no difference between a bang and an empty list. In the case you've mentioned, `[4( -> [route 4]` and `[4( -> [sel 4]` give the same output for all practical purposes. It simply doesn't matter if it is an actual "bang" message or an empty list. This is just an implementation detail and objects mostly pick the method that is more convenient/efficient.

**Comment by Spacechild1** [comment]
I think there's nothing really to do here except for fixing bugs like https://github.com/pure-data/pure-data/pull/1683 and improving the documentation where it contains unnecessary references to implementation details (such as the case with `[list trim]` you've mentioned above).

**Comment by porres** [comment]
I already have a fix for list box and have worked out the documentation. I reverted to how things were before but made it simpler than it was, the exception is the help file of [print] where I felt like it was a good place to also expose this (while before we didn't have anything of this sort)

**Comment by Spacechild1** [comment]
thanks!
