### ISSUE TITLE
Has "Pd documents directory" been removed intentionally, or accidentally?

### ISSUE THREAD

**Issue by jamshark70** [pure-data/pure-data#1686]
Pd 0.50.2, from my Linux distribution, has a "Pd documents directory" in the Path preferences panel.

![pd-path-old](https://user-images.githubusercontent.com/318301/172522993-acb7f146-a9fb-4deb-8268-5257276f7b76.png)

Pd 0.52.2, built by myself from source, seems to omit this preference.

![pd-path-new](https://user-images.githubusercontent.com/318301/172523008-69b34784-cf23-40bc-94ae-518748c9730d.png)

This is not an impact-free change. I *don't* keep most of my work nearby my user home directory. The Linux file dialog does not support bookmarks. So the way to get to my work location is, step 1, navigate up to `/` and step 2, navigate through media/username/volume_name/Docs/etc etc etc. I had been saving some time by choosing a documents directory within this location. But now, every time I launch Pd, it takes me to my user home directory.

As a workaround, I guess I will have to create a symbolic link in my home directory. But at least this user's experience was nicer when I could say where I wanted to keep my files.

**Comment by umlaeute** [comment]
this seems to be a side-effect of 92f3c68d0f76c29da817cb33945fdc0eae26408d

the entire "Pd Documents Directory" foo is disabled if you start Pd via the core (that is: you just run "pd" on the cmdline).
If you start Pd via the GUI (via your desktop menu; or running "pd-gui" on the cmdline), then the "Pd Documents" will be enabled.

the reasoning [1] was, that power-users (those starting Pd from the cmdline), often do not use the "Documents Directory" at all, and in some cases it is even harmful (e.g. automatically starting Pd with GUI on a system that has no keyboard/mouse).

[1] https://lists.puredata.info/pipermail/pd-dev/2022-01/022936.html

**Comment by jamshark70** [comment]
Oh excellent! That actually was exactly the problem. For my local build, I created my own .desktop file and it indeed had `Exec=/home/dlm/share/pure-data/bin/pd` -- appending `-gui` to the end of this line has resolved the problem.

Happy to close this issue, then.
