### ISSUE TITLE
request, allow up/down arrows for gatom number box to increment/decrement values

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1709]
I guess this makes sense for the number box only, but I guess it's also possible for the list box and its float values though.

So, when the box is activated, the idea would be to allow an up arrow to increment in integers, while down arrow would decrement it. When holding the shift key one could also increment/decrement in decimal values in the same way as dragging.

**Comment by timothyschoen** [comment]
It would be nice to receive arrow key notifications on all objects, as long as we're not in edit mode. It would be easier to implement for gatom that way, but it would also allow externals to make use of this.

**Comment by porres** [comment]
> It would be nice to receive arrow key notifications on all objects, as long as we're not in edit mode. It would be easier to implement for gatom that way, but it would also allow externals to make use of this.

I don't understand. Do you mean it is currently impossible for externals to use arrow keys when not in edit mode? Bacause that is not the case, check [else/messbox] that allows you to type in text when in run mode, like gatom boxes do, and you can use up/down keys to move to the beggining or end of the text, left/right arrows also work.

Also, when you doble click on gatom boxes you can select the text and use left/right/up/down arrows as well. You can also copy/paste values here.

My request is that we can use up/down arrows as well when the object is activated but the text isn't selected

**Comment by timothyschoen** [comment]
What I meant is that the "key" method doesn't get called for arrow keys. It's possible to bind them with tcl/tk, but not to receive them through the normal key function. I didn't think of implementing it through tcl/tk when I wrote that, so never mind!

**Comment by porres** [comment]
So you mean that the "key" method can be expanded to also grab arrow keys, right? This seems like a separate issue, and requires a change to the core itself. I think we can implement this without such changes, but I have no idea how to do it (haven't even tried it yet).

**Comment by Spacechild1** [comment]
> What I meant is that the "key" method doesn't get called for arrow keys.

`[key]` outputs unicode code points and consequently only works for key stroke (combinations) that result in a text character. `[keyname]`, on the other hand, outputs raw key strokes as symbols, e.g. it will output arrow keys as `Left`, `Right`, `Up` and `Down` symbols.

**Comment by porres** [comment]
doh!!! I did it again, another duplicate --> https://github.com/pure-data/pure-data/issues/1007

**Comment by timothyschoen** [comment]
@Spacechild1 Thanks! That makes it much easier!
