### ISSUE TITLE
Turning DSP on/off locks up canvas + DSP processes

### ISSUE THREAD

**Issue by thouldcroft** [pure-data/pure-data#1710]
When I turn DSP on, then later turn it off, it will not turn back on, and it locks up my canvas and any DSP processes. I have tried this with the DSP toggle in the Pd Window, the DSP menu item, and sending messages to Pd via semicolon message box or [send] object, and all exhibit the same behavior. In testing, when turning DSP off while audio is playing, audio cuts out, cuts back on and then permanently out very quickly that it almost has a "popping" quality; from there the the canvas is locked up, I can't edit it nor can I control any GUI controls. I can toggle DSP back on via Pd Window or the Menu, but neither return audio that should be playing when DSP processing returns so I don't know if DSP is actually turned back on, or if the Pd GUI is just displaying that it is back on.

Pd 0.52.2
MacOS 12.2.1
2021 Macbook Pro Apple M1 Pro

**Comment by porres** [comment]
are you using plain vanilla objects? do you have a patch that shows the behaviour?

**Comment by thouldcroft** [comment]
Yes it happens with plain vanilla objects. Even a patch with just 

[; pd dsp 0(

 or

[dsp 0(
|
[s pd]

locks everything up. The DSP toggle in the Pd window locks it up too.

**Comment by umlaeute** [comment]
which audio backend are you using? which soundcard?

**Comment by thouldcroft** [comment]
I'm using Core Audio with a Komplete Audio 6 MK2 interface, but I also just checked it with output using the Macbook Pro speakers and the same behavior happened. I'll admit I haven't tested every Audio setting option, but here is my current audio configuration:

SR: 48000
Delay: 5
Block Size: 64
Use callbacks: yes
Input/output channels: 2/2

**Comment by thouldcroft** [comment]
Ok, looks like "Use Callbacks" was the culprit. But I was getting audio glitches/interruptions when I was using Pd without "Use Callbacks" enabled.

**Comment by umlaeute** [comment]
instead of *Use callbacks* you could try raising the Delay settings (to get rid of the glitches)

**Comment by Spacechild1** [comment]
The problems with "Use Callbacks" are already reported here:

https://github.com/pure-data/pure-data/issues/1710
https://github.com/pure-data/pure-data/issues/1703
https://github.com/pure-data/pure-data/issues/550

I'm closing this issue as duplicate. But thanks for the report!
