### ISSUE TITLE
extra redundant "pd Help" option in Help Menu

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#172]
There's a new menu entry in "Help" named "Pd Help" which just opens the browser, so it the same thing as the "Browser" option below, thus, completely redundant.

Was this supposed to open something else?

cheers

**Comment by porres** [comment]
a screenshot

<img width="693" alt="screen shot 2017-08-10 at 15 21 14" src="https://user-images.githubusercontent.com/5360142/29185550-f223ce70-7ddf-11e7-89e1-46e8aa7d203b.png">

**Comment by danomatika** [comment]
Yes. It is automatically created by Tk and cannot be removed, so at least it does something for now by opening the browser. Is it really a big deal?

The only options are to either disable it (but not remove it) or to not create the Browser menu entry. The Browser entry is left for consistency with other platforms.

**Comment by porres** [comment]
> Is it really a big deal?

Well, maybe not "BIG"... but still... 

> Relatedly, the Search box doesn't contain any relevant Pd entries.

Seems to work fine here, to find menu entries and stuff, such as "Font"

> Another option would be to have it open the manual instead and remove the HTML Manual...

A manual seems more "helpful" indeed.

And how about yet another option: open the browser, but pointing directly to the "manual" part of it?


<img width="733" alt="captura de tela 2017-08-10 as 20 49 11" src="https://user-images.githubusercontent.com/5360142/29196840-89fbf272-7e0d-11e7-801f-dd2218b52a76.png">


Just a thought...

**Comment by megrimm** [comment]
>> And how about yet another option: open the browser, but pointing directly to the "manual" part of it?

this might be better so that the link produces, even just slightly, different functionality.

let me ask, although "Pd Help" is created automatically, can it be renamed?

**Comment by danomatika** [comment]
>let me ask, although "Pd Help" is created automatically, can it be renamed?

From what I've read, no. If it could, I would have done it.

**Comment by danomatika** [comment]
Possible fix is #204.
