### ISSUE TITLE
command line -audioindev -audiooutdev flag indices start at 0

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#1720]
I noticed today that setting the audio in/out device via the `-audioindev` and `-audiooutdev` flags require an indices starting at 0 while the output of `-listdev` and the audio dialog show the device indices starting at 1.

For example, on my macOS 11.6.7 system:
~~~
% pd -listdev
audio input devices:
1. Core Audio: MacBook Pro Microphone
audio output devices:
1. Core Audio: MacBook Pro Speakers
API number 4

MIDI input devices:
1. IAC Driver Pure Data Input
2. IAC Driver Pure Data Output
MIDI output devices:
1. IAC Driver Pure Data Input
2. IAC Driver Pure Data Output
~~~

To use "Core Audio: MacBook Pro Microphone" as input and "Core Audio: MacBook Pro Speakers" as output, I need to use:

    pd -audiooutdev 0 -audioindev 0

I think the simple solution is to change the flags to use the same 1-n range, but I am hesitant to change this without finding a good way to let people know beforehand...

**Comment by abreubacelar** [comment]
what about changing the output of listdev to start at 0?

**Comment by danomatika** [comment]
Then no longer matches the indexing in the audio dialog…

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by umlaeute** [comment]
- i think it is better to introduce changes on the representation layer than on the interface layer (that is: changing the indices for the `-audiodev` flags will *break* scripts that rely on the current enumeration)
- I don't think it is a big issue having different index bases on the command line vs the GUI (but otoh, i think it *is* an issue having different index bases in the realm of command line switches)
- if you don't agree with my last sentence, we can also change the index base in the audio dialog...

**Comment by danomatika** [comment]
I was also thinking the same now and the obvious solution, as pointed out, is to fix the print indices on the command line. Since the contexts are different, then it’s prolly fine that they don’t match with the GUI.

I can make a fix commit to develop later.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by umlaeute** [comment]
it seems that this is somewhat intentional (but wrongly implemented)

```C
/* To agree with command line flags, normally start at 1 */
/* But microsoft "MMIO" device list starts at 0 (the "mapper"). */
/* (see also sys_mmio variable in s_main.c)  */
```

things might have changed sinc ethis ws written, though.

| audio system | needs to start at ... |
|---|---|
|  NONE       | X |
|  ALSA       | 0 |
|  OSS        | 0 |
|  MMIO       |  |
|  PORTAUDIO  | 0 |
|  JACK       | -- |
|  SGI        | X |
|  AUDIOUNIT  | X |
|  ESD        | X |
|  DUMMY      | X |

i couldn't test on MMIO, but probably the logic is just reversed?

**Comment by umlaeute** [comment]
now i've tested on MMIO, and it's 0-based as well.

however, i think the confusion comes from the **MIDI**-devices, which appear to be 1-based, at least on Windows.

i cannot really test on linux (having no OSS-MIDI device for the last decades), and ALSA-MIDI is a different beast altogether.

**Comment by danomatika** [comment]
I like consistency but it’s often not possible to ensure for older projects like this without potentially breaking things. At the least, it’s probably good to point out any differences, ie. the help print states the audio devs are 0-based.

Otherwise, I would personally change it to be 1-indexed to match the other dev ids. ;)

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com
