### ISSUE TITLE
fudiparse over TCP/IP

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1739]
so, we can use [fudiformat] to send messages over the network via UDP or TCP/IP. I want to confirm the use case of using TCP/IP and I am assuming it only makes sense to send it via binary output, as in [netsend -b].

The problem is that [netreceive] gets a stream of bytes and [fudiparse] doesn't handle it as it only converts message by message. If there is a use case for using TCP/IP and raw FUDI messages, I think [fudiparse] should be able to reconstruct the message by listening to the packet separator. Maybe we need an argument for that?

**Comment by Spacechild1** [comment]
> so, we can use [fudiformat] to send messages over the network via UDP or TCP/IP. I want to confirm the use case of using TCP/IP and I am assuming it only makes sense to send it via binary output, as in [netsend -b].

In danger of stating the obvious, but if you just want to send/receive FUDI over the network, you would simply use `[netsend]`/`[netreceive]` (TCP) resp. `[netsend -u]`/`[netreceive]`....

> I think [fudiparse] should be able to reconstruct the message by listening to the packet separator. Maybe we need an argument for that?

That would be a nice feature nevertheless. Manually assembling the bytes is not too difficult, but it's still a PITA.

**Comment by porres** [comment]
> In danger of stating the obvious: if you just want to send/receive FUDI over the network, you would simply use [netsend]/[netreceive] (TCP) resp. [netsend -u]/[netreceive -u] (UDP)....

yup, that's how I see it. So I still don't get the need or use case for [fudiformat]/[fudiparse]. They seem to be used more for converting bytes to ASCII characters and vice versa, but I'm sure there's gotta be a need for it. It would be nice to make it clear why and put that information on the help file maybe.

**Comment by Spacechild1** [comment]
> So I still don't get the need or use case for [fudiformat]/[fudiparse]

I think the mean use case is sending/receiving FUDI messages with external (low-level) networking objects, such as `iemnet`.

Other use cases:
* send/receive FUDI messages over a serial connection
* assemble/manipulate Pd messages on the byte level, similar to `[list fromsymbol]` and `[list tosymbol]`, but with whole messages instead a single symbols
* embed Pd messages in another protocol, e.g. as an OSC blob in an OSC messages

I think the documentation for these objects could be improved indeed. Especially the following sentence is very misleading:
> The fudiformat object makes FUDI objects suitable for sending over the network via netsend (in UDP mode).
You certainly wouldn't use `[fudiformat]` with `[netsend]` and why only UDP?

Calling Dr. Porres!

**Comment by umlaeute** [comment]
> So I still don't get the need or use case for [fudiformat]/[fudiparse].

https://github.com/pure-data/pure-data/pull/74

if you don't need it, don't use it.

**Comment by umlaeute** [comment]
> The problem is that [netreceive] gets a stream of bytes and [fudiparse] doesn't handle it as it only converts message by message.

first of all, let's swap `[netreceive]` for `[comport]`, when talking about a usecase, so you are not permanently made to belief the object is useless :-)

`[fudiparse]` correctly handles packages with multiple FUDI-messages. e.g. a single `[102 111 111 32 98 97 114 59 10 112 105 122 122 97 32 100 105 101 110 115 116 59 10(` will output two messages.

this of course does not help you much, if you are receiving a stream of bytes (rather than packages), such as `[comport]` will output).
however, it's simple enough to create a patch that just builds the lists from the bytes and splits them on the terminator...

```
|
[select 59]            [r $0-list]
|         |            |
|         [list prepend] 
|         |
|         [s $0-list]
|
|    [r $0-list]
|    |
[list]
|
[t l b]
|     |
|     [s $0-list]
|
[fudiparse]
|
```

otoh, it's much simpler to mimick the `[fudiformat -u]` behaviour in the patch, and *this* got its own flag.
so i understand the desire to add a separate flag (but please let's call it something else as "~`-t`: TCP-mode~").

(although: if you are not seeing any uses for `[fudiparse]` anyhow, it's probably better to leave the source until you (or somebody else) really requires that functionality :-))

**Comment by porres** [comment]
> You certainly wouldn't use [fudiformat] with [netsend]. 

Oh really???? I already made one revision to the help file, but now I need to better understand this and other changes must be made such as maybe not saying it should be used with [netsend] and not having an example for it :)

**Comment by porres** [comment]
>  if you are not seeing any uses for [fudiparse] anyhow,, it's probably better to leave the source until you (or somebody else) really requires that functionality :-)

makes sense :) I should probably close this then.

But the point now is that I'd like to know and see a use case to at least better document the object and let people know its purpose. As I see it now, it is confusing, specially because now it seems we shouldn't even really use [netsend].

Anyway, closing this issue but I hope we can continue to discuss it so I can improve the documentation.

**Comment by porres** [comment]
My latest help file update. I made it less redundanct than my last revision as discussed in the telegram group.

![Screen Shot 2022-09-08 at 03 09 03](https://user-images.githubusercontent.com/5360142/189047459-9fcd1fa3-77ec-4597-9157-3b7f46f748cc.png)

![Screen Shot 2022-09-08 at 03 09 10](https://user-images.githubusercontent.com/5360142/189047483-11600add-2546-444e-b9ad-170e8754d0e0.png)

**Comment by umlaeute** [comment]
the updated help-patch is nice. thanks.

as for the description of the FUDI protocol,  you might want to check https://en.wikipedia.org/wiki/FUDI to explain it a bit more in detail (I take https://github.com/pure-data/pure-data/pull/74#issuecomment-312516589 as a suggestion to use the help-patch for FUDI advertising) - the message separator is probably the least interesting aspect of the protocol, while in the current description it seems to be the only defining aspect (the rest is just "bytes").

you might also want to note that the user could just use the built-in FUDI capabilities of `[netsend]`/`[netreceive]`, and that you can mix the two (e.g. using an ordinary `[netsend -u]` to send messages to a `[netsend -u -b]`).

and i would just get rid of the `prepend send` idiom for sending list of bytes in `[netsend]`'s binary-mode (makes the patch more readable).

---

and i can't resist to also answer this:

> specially because now it seems we shouldn't even really use [netsend].

@Spacechild1 said that you *wouldn't* use it, not that you *shouldn't*.
- if you want to use `[netsend]` to transmit FUDI-messages, you do not need `[fudiformat]` as it is already built into `[netsend]`. so there's typically no need to use the two objects together.
- but if you want to do something fancy (like being able to swap the actual transmitting backend for something else; or add some encryption, or mangle the transmitted bytes in some other way), then you are free to do that, of course.

**Comment by Spacechild1** [comment]
> But the point now is that I'd like to know and see a use case to at least better document the object and let people know its purpose. 

I think I already mentioned a couple of use cases: https://github.com/pure-data/pure-data/issues/1739#issuecomment-1239017215

**Comment by porres** [comment]
> I think I already mentioned a couple of use cases: https://github.com/pure-data/pure-data/issues/1739#issuecomment-1239017215

When you say we can assemble/manipulate Pd messages on the byte level, similar to [list fromsymbol] and [list tosymbol], I agree and it seems people are mostly using it for this. So maybe we should really mention it.

**Comment by porres** [comment]
> as for the description of the FUDI protocol, you might want to check https://en.wikipedia.org/wiki/FUDI 

should we maybe add this link to the help file? Or maybe put this information about the protocol in the Pd Manual?

**Comment by umlaeute** [comment]
I think the help-patch should be the reference (so put it there).

It's not that much info.

**Comment by porres** [comment]
> so put it there

put what there? the link to the wikipedia? we could use [pdcontrol] to open the link, huh?

**Comment by porres** [comment]
I just put the link to the wiki page, made a remark for the relation to [list tosymbol] and added more information discussed here.

**Comment by porres** [comment]
screenshots

![Screen Shot 2022-09-08 at 15 56 14](https://user-images.githubusercontent.com/5360142/189203447-ea194e84-bc92-495c-8f99-64859258d96f.png)
![Screen Shot 2022-09-08 at 15 56 19](https://user-images.githubusercontent.com/5360142/189203451-bd35f9a5-fb1d-4a09-9834-04f1b0600483.png)

**Comment by umlaeute** [comment]
>> Or maybe put this information about the protocol in the Pd Manual?

> so put it there

I meant: the documentation pd-patch should be the reference, not some random Wikipedia article.
So I would prefer if the info was copied from Wikipedia rather than linking to it.

**Comment by umlaeute** [comment]
actually, i don't really care whether the "Pd-patch" or the "HTML documentation" of Pd is the reference. it's just that the wikipedia article should not be the reference (see also "original research" on wikipedia)

**Comment by porres** [comment]
having an html reference like slop~ and expr is not a bad idea, calling @Lucarda

**Comment by Lucarda** [comment]
> having an html reference like slop~ and expr is not a bad idea

@porres done via https://github.com/pure-data/pure-data/pull/1750

**Comment by Lucarda** [comment]
I had tried https://github.com/porres/pure-data/pull/20

**Comment by porres** [comment]
seems to be, but i didnt get the warning, anwyay, merging it so you can close the other one

**Comment by Lucarda** [comment]
https://github.com/pure-data/pure-data/pull/1750 closed.

**Comment by porres** [comment]
you know what, now that I actually see the html file and wiki entry, it doesn't seem to be that much long of a description or quite detailed one. It doesn't seem to me worth an html file... what's here could be integrated into the help file itself or maybe we can improve the information about the protocol (and perhaps we should).

**Comment by porres** [comment]
"Each message consists of one or more atoms, separated by one or more whitespace characters"

but mote than one is meaningless, right? it's the same as just one...

**Comment by porres** [comment]
new issue to discuss such things: https://github.com/pure-data/pddp/issues/106
