### ISSUE TITLE
Sending a 'label' message to a hidden [cnv] object triggers Tcl error

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1740]
This is with current master (3990e8883511889e6094642b95e223caf4b29f83). The culprit might be in one of the recent merges. 

Test-patch here:
[canvas-label-bug.zip](https://github.com/pure-data/pure-data/files/9500461/canvas-label-bug.zip)

**Comment by reduzent** [comment]
That's the whole error from the Pd console:

```
(Tcl) INVALID COMMAND NAME: invalid command name ".x556b4f257a50.c"
    while executing
"$tkcanvas itemconfig $tag -text [::pdtk_text::unescape $text]"
    (procedure "pdtk_text_set" line 2)
    invoked from within
"pdtk_text_set .x556b4f257a50.c {556b4f257d90LABEL} {bla} "
    ("uplevel" body line 2)
    invoked from within
"uplevel #0 $docmds"
```

**Comment by reduzent** [comment]
The culprit probably is 6ade4c783d289ab6fd842aa9cff423a2be24d809 . The most recent commit that still is fine is fb050372. Maybe it got introduced by resolving merge conflicts?

**Comment by umlaeute** [comment]
argh.

**Comment by DaliuSinger** [comment]
Sending a disconnect command to a hidden PD patch will trigger:
(Tcl) INVALID COMMAND NAME: invalid command name ".x6000087e8000.c

This can be reproduced in the help file, under namecanvas > pd-messages > pd Dynamic-Patching > pd (dis)connecting-boxes.
Create objects by clicking on the message box, connect, close the patcher window and click disconnect message.
This will trigger the error... Very annoying.
Many thanks!

<img width="507" alt="Screenshot 2023-01-09 at 16 03 33" src="https://user-images.githubusercontent.com/51788325/211339059-34a4355c-2c68-4893-a9c9-63f2734b3158.png">
