### ISSUE TITLE
symbols with spaces are escaped with double-slash in some objects

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1742]
Depending on how a symbol containing spaces is displayed, the spaces are escaped with double-slashes. 

Affected are 

- [text]
- [drawsymbol]
 
Not affected are:

- symbol atom
- list atom
- cnv label
- Pd console.

This was tested on current master (3990e8883511889). Not affected is the last release 0.52.2.

See attached test patch for illustration.
[symbol-double-slash-test.zip](https://github.com/pure-data/pure-data/files/9525934/symbol-double-slash-test.zip)

**Comment by umlaeute** [comment]
as for `[text]`: i would consider the content to be code, where i actually want to see the difference between a atoms and a single symbol with spaces.

as for `[drawsymbol]`: that's probably a regression.

**Comment by reduzent** [comment]
Actually, your fix turns the regression in an improvement: The [drawsymbol] scalars do not show the backslash at all now. Which I think is a good thing. 

Having the spaces within symbols escaped with _one_ backslash makes sense in [text define], as there would be no other way to distinguish the spaces from atom delimiters. 

I guess, there is still no resolution whether the symbol atom should display the escape character. I think it should not.

**Comment by porres** [comment]
> I think it should not.

I guess we all agree on that
