### ISSUE TITLE
hsl and vsl handles stay black, regardless of configured properties

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1743]
This is a regression in current master (3990e8883511889e6094642b95e223caf4b29f83). The latest release 0.52.2 is not affected.

Handles of the iemgui object classes [hsl] and [vsl] stay black and ignore the color configured in the properties. The handle colors are correctly saved with the patch, but are displayed as black. 

![image](https://user-images.githubusercontent.com/333373/189132911-614e4f8d-b32b-4036-a627-5be49fab9aa5.png)

**Comment by reduzent** [comment]
Thanks for fixing it. Now, the color of the handle is set correctly. However, the handle is too large now and overlaps the object's outline. See here:

![image](https://user-images.githubusercontent.com/333373/189347117-0f2d8583-e68c-48b8-bf35-b895de37c931.png)

**Comment by reduzent** [comment]
Also, when having a closer look, the handle is now one pixel wider (4px) than it in the last released version (3px). Also, it seems that in the released version the handle doesn't fully reach the bottom border, leaving 1px of background.


![slider-handle-comparison](https://user-images.githubusercontent.com/333373/189348755-8acb5e4a-4e51-4834-8102-9e5a99bbbbe3.png)

**Comment by umlaeute** [comment]
> in the released version the handle doesn't fully reach the bottom border, leaving 1px of background.

i think this is a bug in the original version.

i didn't mind so much that the knob now occludes the border, but you consider it ugly, i can fix it.

**Comment by umlaeute** [comment]
fixed with 5736c354eef0011db27c52cc3707d09d1861b226

**Comment by reduzent** [comment]
Thanks for fixing. I guess I'm not the only one abusing sliders for many kinds of GUIs with the handle hidden by setting it to same color as the background. Not occluding the border is a crucial property of sliders, I'd say:

![image](https://user-images.githubusercontent.com/333373/189434947-d1580a0c-625b-4f74-b60c-b9a2c0132bb8.png)

**Comment by reduzent** [comment]
> > in the released version the handle doesn't fully reach the bottom border, leaving 1px of background.
> 
> i think this is a bug in the original version.

Yeah.
