### ISSUE TITLE
properties dialog of vsl broken

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1744]
This is a regression in current master (3990e8883511889e6094642b95e223caf4b29f83). The latest release 0.52.2 is not affected.

The properties dialog of [vsl] in the dimensions section, only one number field is displayed. There is no way to change the height parameter through the dialog. The label of the dialog looks broken:

![image](https://user-images.githubusercontent.com/333373/189133731-8cf9a581-c687-4e46-be5f-1b3079772212.png)

**Comment by porres** [comment]
Well, now that the sliders and radio buttons are unified, both horizontal and vertical versions should call the same single properties window! And the orientation should also be set via a new properties setting! After all, this is now settable via a new 'orientation' message.

**Comment by umlaeute** [comment]
> should call the same single properties window

that's an entirely different issue. if you want that, open a new feature request.
