### ISSUE TITLE
iemgui: cannot reset label to 'empty'

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1745]
This is a regression in current master (3990e8883511889e6094642b95e223caf4b29f83). The latest release 0.52.2 is not affected.

Editing the properties of [cnv] lost the ability to reset the label to empty. If either nothing or `empty` is entered and applied, the [cnv] shows an empty label, but when copying such a [cnv] object, the copy shows the previous label. Also, when a [cnv] with an emptied label is saved, the patch file contains the last label instead of `empty`.

**Comment by umlaeute** [comment]
1. open a patch with an iemgui that has a label
2. open it's properties
3. clear the label-field
4. close+apply the properties with <kbd>OK</kbd>
5. duplicate the object

**Comment by umlaeute** [comment]
the problem is obviously in `iemgui_init_sym2dollararg` which falls back to getting the label (and send/receive names) from the old binbuf, if they are currently unset.
