### ISSUE TITLE
only one [filledpolygon] is displayed per [struct]

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1758]
When drawing a scalar consisting of more than one [filledpolygon] or [drawpolygon] object is drawn to a canvas, only one of the many [filledpolygon]s or [drawpolygon]s of the same [struct] is drawn. It appears the [xxpolygon] that wins is the last created one.

See attached patch. The patch draws one scalar consisting of a red and a blue square into the GOP area. But at most one is visible at the time, but not both:

[multi-filledpolygon-issue.zip](https://github.com/pure-data/pure-data/files/9569670/multi-filledpolygon-issue.zip)

When deleting and pasting the lower [filledpolygon] object, the blue square is displayed, but the red one disappears. Vice versa with the upper [filledpolygon].

This is a regression found in current master (ade0160ca291f7) that was introduced after 0.52-2

**Comment by umlaeute** [comment]
hrmpf, this regression was introduced by 1834a3566a411ee24b4f8e2c9f399f024c11e93a

**Comment by reduzent** [comment]
I confirm it is fixed in develop. Many thanks!
