### ISSUE TITLE
pdsend errorname: >>error writing "sock14": broken pipe<<

### ISSUE THREAD

**Issue by fdch** [pure-data/pure-data#176]
I get this error running test7 pd from terminal, but I haven't had any problems and I don't know what it means, so I just copy it here:

The error happens after quitting pd from the gui (even if no patch was opened).

```
Pd-0.48.0 ("test7") compiled 18:17:00 Aug  9 2017
port 5402
"/Applications/Pd-0.48-0test7.app/Contents/Resources/../MacOS/Pd" 5402
Waiting for connection request... 
... connected
Pt_Start() called
pdsend errorname: >>error writing "sock14": broken pipe<<
```

**Comment by danomatika** [comment]
That's normal. I don't think it's a major issue. At most, it's a timing thing on shutdown.

**Comment by fdch** [comment]
Cool! Good to know then, thanks.

**Comment by umlaeute** [comment]
i guess we can close this then..,.
