### ISSUE TITLE
auto-patching does not work for IEM GUIs

### ISSUE THREAD

**Issue by giuliomoro** [pure-data/pure-data#1776]
If I have exactly one object selected and I hit ctrl+1, ctrl+2, ctrl+3, ctrl+4, the new object will automatically be connected to the previously selected object. If I have exactly one object selected  and I hit ctrl+shift+T, ctrl+shift+B etc, the new object will _not_ be automatically connected to the previously selected object.

Expected behaviour: regardless of what shortcut I use to create a new object, if there is exactly one object selected and the new object has an inlet, the new object should automatically be connected to the first outlet of the selected object.

**Comment by Spacechild1** [comment]
I took the liberty and edited the title. This is an old and annoying issue and I'm surprised nobody has opened a ticket before... I hope we can finally fix it!

**Comment by giuliomoro** [comment]
>I took the liberty and edited the title

Well done. I had a blurred memory that that "auto-patching" was the name , but I couldn't tell for sure ...

**Comment by umlaeute** [comment]
i've trained my muscle memory to just create objects like `[hsl]` if i want autopatching for iemguis. it has the added bonus of being  less straining for my wrists.

but yes. i agree it should be fixed.

**Comment by giuliomoro** [comment]
yeah I do the same. Btw how do you make a floatatom that way? I only know how to make a `nbx` but it would be great to get a vanilla floatatom ...

**Comment by umlaeute** [comment]
> Btw how do you make a floatatom that way? 

you don't.
gatoms are primitives, like msgboxes, comments or objects.
iemguis are just objects with a fancy skin.
