### ISSUE TITLE
pipewire-jack-audio-connection-kit not recognised as jack

### ISSUE THREAD

**Issue by muziker** [pure-data/pure-data#1799]
When compiling pure data and specifying --enable-jack, on a pipewire system like a fedora, the configuration script doesn't recognise this as a proper jack library. 

pure-data 0.52-2

**Comment by umlaeute** [comment]
i don't know about the fedora package, so: which (JACK-related) header files does it install?

e.g. on Debian, the `pipewire-jack` package only installs the replacement `libjack.so` library, and no headers at all.

for compiling Pd with JACK support, you *must* have JACK-headers installed.

**Comment by umlaeute** [comment]
while waiting for feedback, i've found out the following:
- `pipewire-jack-audio-connection-kit` is obviously not enough
- the package required to install is `pipewire-jack-audio-connection-kit-devel`
- this still is not enough, as the above installs the `libjack.so` file into `/usr/lib64/pipewire-0.3/jack`
- this location is announced via `pkg-config --libs jack`, but Pd does not use this

**Comment by muziker** [comment]
Yes I just found out where the pipewire jack .so files are located. The configure script doesn't use pkg-config to do it's jack_set_error_function test. I copied the .so files for a quick fix to this.

**Comment by umlaeute** [comment]
urgh, copying files around is usually the wrong apporach.

a better and simpler approach, is to just tell configure where to look for the libaries:

```sh
./configure --enable-jack LDFLAGS="-L/usr/lib64/pipewire-0.3/jack"
```

**Comment by muziker** [comment]
Too true ! But in some instances of other projects, LDFLAGS from the environment gets clobbered somehow during the build process.
