### ISSUE TITLE
Mac OS: Right-click doesn't work when patch is on auxiliary display 

### ISSUE THREAD

**Issue by lukesd** [pure-data/pure-data#1802]
I'm on MacOS 12.6, on an M1 MacBookPro, running Pd 0.52.2.

I have a monitor connected to my laptop. If my Pd patch is on the laptop screen I can right-click and get access to Properties and Help. However if the same patch is moved over to the external monitor, the right-click does not function at all!

Of course this is a pain, since I'd like to do my patching on the bigger screen.

**Comment by cerdemo** [comment]
> I'm on MacOS 12.6, on an M1 MacBookPro, running Pd 0.52.2.
> 
> I have a monitor connected to my laptop. If my Pd patch is on the laptop screen I can right-click and get access to Properties and Help. However if the same patch is moved over to the external monitor, the right-click does not function at all!
> 
> Of course this is a pain, since I'd like to do my patching on the bigger screen.

I have exactly the same (on the same config).

**Comment by 60-hz** [comment]
It's a known issue https://github.com/pure-data/pure-data/issues/1303

**Comment by umlaeute** [comment]
closing as duplicate
