### ISSUE TITLE
Control+click contextual menu not working in macOS on secondary monitor

### ISSUE THREAD

**Issue by brianlindgren** [pure-data/pure-data#1807]
Contextual menu not accessible on secondary (external) monitor with control+click. Makes accessing 'open', 'properties' or 'help' difficult when working with 2 displays.

**Comment by Lucarda** [comment]
It's a known issue https://github.com/pure-data/pure-data/issues/1303

**Comment by brianlindgren** [comment]
thank you

**Comment by umlaeute** [comment]
closing as duplicate (please add any additional information to the original report #1303).

i wonder though: since #1303 is rather old and we have had two reports about the same issue in the last week (#1807 and #1802), is there some (additional) regression?
