### ISSUE TITLE
savepanel does not interrupt trigger 

### ISSUE THREAD

**Issue by brianlindgren** [pure-data/pure-data#1813]
as part of a sequence of triggers, save panel will allow the subsequent triggers to active even before it has capture the filepath chosen by the user. this in effect disrupts a sequence of actions that rely on the filepath provided by the savepanel.

**Comment by umlaeute** [comment]
the alternative would be to halt all message and audio processing until `[savepanel]` returns.
we do not want to do that.

if you need to trigger actions based on the return value of `[savepanel]`, just use it's outlet:

```
|
[savepanel]
|
[t b s b]
|   |   [print before]
|   |
|   [print filename]
|
[print after]

**Comment by brianlindgren** [comment]
this makes sense - thank you for the suggestion
