### ISSUE TITLE
(iem)GUI externals issues with pd 0.53

### ISSUE THREAD

**Issue by ZestieBumwhig** [pure-data/pure-data#1823]
I don't have much info, and it could have been user error, but PD 0.53-0 would crash on my Arch Linux system when trying to open most of my patches. It would close as soon as I tried to open almost any patch; when started via terminal, the only extra info was "Core Dump (Segmentation Fault)".

I was able to open some smaller patches, but the larger ones (which had colors and/or Graph-On-Parent GUIs) would cause the crash. Rolling back to PD 0.52, everything worked again, and I stopped researching/troubleshooting. I only tried about five patches on 0.53 before I returned to 0.52.

Sorry I don't have more info; let me know if you'd like me to test further.

**Comment by thumpclang** [comment]
This sounds very similar to the issue I'm having with Pd 0.53 on macOS Monterey (Intel), certain patches of mine that work fine in 0.52-2 crash immediately in 0.53. (relevant discussion on Pd Patch Repo forum [here](https://forum.pdpatchrepo.info/topic/14122/problems-with-pd-53-on-arch-linux))

Looking at my crash logs I saw mknob (an external GUI knob from moonlib) mentioned, and when trying to open the mknob help file in 0.53 I get an instant crash as well. Not sure if this might be a bigger problem that could affect other GUI externals, so I'm attaching my error log here & will open an issue on moonlib's tracker.
[mknob_crash.txt](https://github.com/pure-data/pure-data/files/9946873/mknob_crash.txt)

**Comment by sebshader** [comment]
I also had numberbox_matrix crash pd in its new function

**Comment by Ant1r** [comment]
FYI mknob has been updated to not crash with Pd 0.53. It's available in moonlib-v0.5 from Deken, for Linux and MacOS (could be great if someone could compile for Windows and upload to Deken! ).

Probably other (iem)GUI externals will crash too, mainly because now empty symbols (for label, send and receive) are NULL, while before they were containing "empty".

**Comment by Ant1r** [comment]
I guess this issue could be renamed (like: GUI externals issues with Pd 0.53).

**Comment by sebshader** [comment]
can this be closed now?

**Comment by porres** [comment]
I think it can be closed as the issue regards externals, right? I'm closing but if anyone disagrees, just reopen
