### ISSUE TITLE
iemguis - composing custom color via properties dialog causes error

### ISSUE THREAD

**Issue by ben-wes** [pure-data/pure-data#1828]
On Win10 and Pd-0.53-0 here (confirmed also for macOS though)

When I'm trying to set a custom color through the color picker, it gives me the following error message:
```
wrong # args: should be "::dialog_iemgui::preset_col mytoplevel presetcol"
wrong # args: should be "::dialog_iemgui::preset_col mytoplevel presetcol"
    while executing
"::dialog_iemgui::preset_col $color"
    (procedure "::dialog_iemgui::choose_col_bkfrlb" line 21)
    invoked from within
"::dialog_iemgui::choose_col_bkfrlb .gfxstub53738b30"
    invoked from within
".gfxstub53738b30.colors.sections.but invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 24)
    invoked from within
"tk::ButtonUp .gfxstub53738b30.colors.sections.but"
    (command bound to event)
```

To reproduce:
* new patch
* add canvas
* open canvas properties
* click "compose color" button
* set arbitrary color
* confirm via "Ok"

It works when I send a `color` message with hex colors though.

**Comment by porres** [comment]
> click "set color" button (not sure how this is named in English 

it's "compose color" and I could not only reproduce this here (macOS) but I can also add this happens in sliders as well and I assume for all iemguis (so maybe you can edit the issue)

**Comment by ben-wes** [comment]
@porres thanks for confirming. I updated the title and description.

**Comment by MSGreen4** [comment]
I stumbled upon a solution to this problem (I think): in the file dialog_iemgui.tcl, change the last statement of procedure ::dialog_iemgui::choose_col_bkfrlb (line 176) from

`::dialog_iemgui::preset_col $color`

to

`::dialog_iemgui::preset_col $mytoplevel $color`

**Comment by ben-wes** [comment]
@MSGreen4 I just tested this and can confirm that it solves the problem. Thanks a lot!

**Comment by ben-wes** [comment]
@MSGreen4 I guess there should be a PR for this then on `develop` - would you want create one?

**Comment by umlaeute** [comment]
Alternatively (without having looked at the code) we might make the 2nd argument optional

**Comment by porres** [comment]
I think this is quite of annoying bug that really calls for a bugfix release soon :) if no one is creating a PR I'll try to do it ;)

**Comment by MSGreen4** [comment]
If you don't mind creating a PR, that would be great (don't know the protocol and procedure for doing that myself, sorry!).

**Comment by ben-wes** [comment]
@MSGreen4 : thanks for your feedback and again for finding this solution!
@porres : If you're willing to create the PR, feel free, of course! Otherwise, let me know if should do it. Thanks!

**Comment by porres** [comment]
@ben-wes please do it as I'm rather busy :)
