### ISSUE TITLE
iemguis - undo replaces '$0' with current ID

### ISSUE THREAD

**Issue by ben-wes** [pure-data/pure-data#1829]
I thought I saw reports on this before, but I don't find anything undo related here right now ... sorry, if that's a redundant report then!

On Win10 here. Issue is also confirmed for macOS though:

If I'm adding a slider (or canvas or other iemguis) and set their sender or receiver to some localized name (`$0-foo`), this gets replaced with the current ID when I undo other changes.

To reproduce:
* Add `hsl`
* set sender name to `$0-foo` in properties and confirm
* edit properties again and change color
* undo with expectation to undo color change ... this doesn't actually undo the color, but replaces the `$0` with its current local ID

... the second undo will undo the color change then.

**Comment by porres** [comment]
> the second undo will undo the color change then

This is not something new. Before you'd also need to hit undo twice to get the color change undone. I think that's a bit annoying, and a separate issue.

**Comment by porres** [comment]
maybe this is related to https://github.com/pure-data/pure-data/issues/1827 ?

**Comment by ben-wes** [comment]
@porres sure, the double undo is not something I wanted to address with this issue here. But since the first undo is causing the `$0` to get replaced, I wanted to mention this at least since it seemed to be connected for me (it looks like the - opposite? -  replacement of the local id ->`$0` has a place in the undo history somehow).

**Comment by ben-wes** [comment]
@porres : is this also happening on macOS? I'd also change the title and description here then as well!

**Comment by porres** [comment]
> is this also happening on macOS?

yup

**Comment by umlaeute** [comment]
Is this a regression or did it happen with older versions of Pd as well?

**Comment by ben-wes** [comment]
just tested with Pd-0.52-2. It behaves different there (although not in an expected way either):
* undo sets the empty fields (in the test case above these are the receive name and label) to `{empty}`. the send name becomes `{$0-foo}`

so I wouldn't call it a regression - it actually solves some of the prior issues. Only the `$0` doesn't survive the undo now.

... the second undo then resets the color as expected.

**Comment by aaaaalbert** [comment]
Two data points on Ubuntu 22.04.1:

Testing on **0.53.0** / 4528eb99f12136bc7145f7ba0b16b729199515f5 self-compiled I **cannot reproduce** the issue. Put `[hsl]`, edit properties (no matter if range or send or color), undo them again -- everything works as expected.

Testing on **0.52.1** / the current `apt install`able version  I **can reproduce** the issue. Again, put `[hsl]`, edit properties (**no matter which of them**), undo them again -- now the slider has a label reading "{empty}", immediately visible on the patch after the undo, and the send and receive symbols are set to "{empty}" as well.

**Comment by porres** [comment]
> just tested with Pd-0.52-2. It behaves different there (although not in an expected way either):

that was a known bug that was kinda fixed, but now we have this other issue, so it is not a regression as I see it
