### ISSUE TITLE
If a toggle is created directly from a object with a label, its label doesn't show up

### ISSUE THREAD

**Issue by abreubacelar** [pure-data/pure-data#1835]
this happens both on pd 0.52-2 and pd 0.53-0

steps:

1. create an object
2. paste "tgl 15 0 empty empty start 17 7 0 10 #fcfcfc #000000"
3. toggle is created but "start" is missing

additional parallel steps:
from 3. if you do undo and redo, "start" shows up
from 3. if you save the patch and reopen, "start" shows up
from 3. if you open properties dialog, "start" is there, if you press apply, it will show up

this was discovered on discord, an user was trying dynamic patching, but you don't need dynamic patching to get this behaviour. ~~Also we didn't test with other iemguis~~

Edit: the user also tested with vsl and bang, and the same happens
Edit2: the user believes it also happens with all iemguis, and not only with the label property

**Comment by porres** [comment]
> this happens both on pd 0.52-2 and pd 0.53-0

when did it work?

note that creating an iemgui object with arguments is not something officially documented.

**Comment by abreubacelar** [comment]
porres teach me outside here that it doesn't work because iemguis needs all parameters to be initialized correctly, so this isn't supposed to work as is, sorry for the noise!

**Comment by porres** [comment]
Yeah, doing [tgl 15 0 empty empty start 17 7 0 10 #fcfcfc #000000 #000000 0 10] works. 

So, unless you had this working before but not now, this is not a regression. Please confirm.
