### ISSUE TITLE
wrong placement of GUI-related objects when zoomed in.

### ISSUE THREAD

**Issue by sevdh** [pure-data/pure-data#1841]
When zoomed in, the placement of the GUI related objects Bang, Toggle, Number2, Vslider, Hslider, Vradio, Hradio, VUmeter and Canvas is not at the cursor position (as it should be) but halfway the left top of the window and the cursor. The position corresponds to where it would have to be positioned when we would not have zoomed in.

PD-0.53.0
macOS 12.6.1

**Comment by porres** [comment]
adding more details, this happens when using the shortcuts when zoomed

@umlaeute hopefully there's time to fix this one now that a bugfix release is round the corner :)
