### ISSUE TITLE
deken now marks wrong architectures as compatible

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#185]
since the `platform(bits)` field is no longer taken into account when calculating the compatibility of deken-installed externals (316f6553), wrong architectures are displayed as compatible.

**Comment by chr15m** [comment]
@umlaeute yep as mentioned on the other comment this whole thing became very complicated when I started implementing it and digging down into different CPU/OS/arch combinations. Basically I guess our obvious end-goal should be showing/highlighting those packages in Deken that match with what the user can actually run on their system.

**Comment by umlaeute** [comment]
this was merged into master with f7dc020 and released as 0.48-1
