### ISSUE TITLE
pd unresponsive on mac ventura 13.0.1

### ISSUE THREAD

**Issue by muccio** [pure-data/pure-data#1857]
after switching audio on the gui became unresponsive (cant't open/close/edit ), need to kill manually all pd processes

**Comment by reduzent** [comment]
@muccio can you post the Pd version you're using? It might be relevant.

On a related note, I experienced the following with Pd 0.53-1 on a macOS 10.15 Intel system: Audio works fine with CoreAudio using default devices (built-in microphone and built-in speakers). After the changing anything in the CoreAudio dialog window (for instance, switch device to some aggregate and back), the Test-tone becomes garbled and Pd starts consuming 100% of a core. Once in that state, it can only be resolved by completely restarting Pd.

I haven't had the chance to test older Pd versions and/or other macOS versions. I will hopefully be able to give more detailed information, once I'll get my hands on a MacBook again.

**Comment by muccio** [comment]
0.53-0, this is happening on mb pro but not on imac, same os and same version...

**Comment by paked** [comment]
Getting the same issue here on a 14" Macbook Pro with Ventura 13.2, anytime I modify an audio setting in Pd 0.53.1

**Comment by paked** [comment]
Update: the 0.53-2test1 build currently linked on http://msp.ucsd.edu/software.html, and discussed in the mailing list fixes my problems.
