### ISSUE TITLE
in 0.53 [hdl] gives the help file of [hradio]

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1859]
we still have old help files for the deprecated versions that used to be called when using the deprecated creators.

**Comment by umlaeute** [comment]
i think the current situtation is fine.

imho, having separate help files for those very old and deprecated creators is just cruft.

**Comment by porres** [comment]
> having separate help files for those very old and deprecated creators is just cruft.

The thing is that it creates an object with a different functionality that is documented in this other help file. Since it's an iemgui, you can't tell what the object name is, so if we include this information into a unified help file it'll be just confusing as one cannot know what the object is. It's not a good alternative.

So, we can make it so that it calls its real help file, or just forget about this and remove the old help files and bury this information... erase it from history. I put it in a way that sounds kinda bad but I can see that this won't cause any real issues as I believe the odds are practically zero that there are patches around with those old/deprecated objects. One way or another, doesn't feel like a good solution and we should see what @millerpuckette has to say.

If were going in this route of not bothering and not documenting it I think it makes sense to actually deprecate this old object/behaviour. Either not letting the object be created anymore or call the new funcionality instead. 

It still seems like the easiest thing to do is makke it call its own help file...

**Comment by porres** [comment]
ha, funny, the old deprecated object also accepts the new 'orientation' message.

**Comment by porres** [comment]
> the old deprecated object also accepts the new 'orientation' message.

not sure wether to document this or not :)

**Comment by umlaeute** [comment]
> ha, funny, the old deprecated object also accepts the new 'orientation' message.

not so funny really, as they are really the same object with slightly different behaviour, depending on how it is called.

> 
> not sure wether to document this or not :)

please don't.

>  it I think it makes sense to actually deprecate this old object/behaviour. 

this **is** deprecated behaviour.
iirc, it comes from a time before the iemguis were actually merged into Pd, so it's been ages.
it has been kept to keep compatibility with old patches.

> Either not letting the object be created anymore

what would that solve? (apart from breaking very old patches that do use these legacy objects?)

> or call the new funcionality instead.

i don't understand what you mean by this.

**Comment by porres** [comment]
> i don't understand what you mean by this.

Keep things as is doesn't seem good to me. If we simply delete the old help files that's not ideal either. We'll just have these deprecated creators loading the new help files which doesn't document the actual behaviour or explain anything.

So I'm asking, should we really deprecate and remove the code? Or (and this is what you didn't understand) have these old creators load the current code (that is, it would be the same as [hradio]).

But now I think I can create a subpatch in the unified help file that explains this and delete the 2 old files and it would all be good!

**Comment by porres** [comment]
> But now I think I can create a subpatch in the unified help file that explains this and delete the 2 old files and it would all be good!

Here it is, what do you think?

![Screen Shot 2022-12-31 at 13 16 57](https://user-images.githubusercontent.com/5360142/210149456-e7a6805e-4ec8-474e-b954-31188b866ad6.png)

**Comment by porres** [comment]
> iirc, it comes from a time before the iemguis were actually merged into Pd, so it's been ages.

For the record, these were actually part of iemguis when incorporated into Pd in 0.34, but in 0.36 the current version was was added by Miller

**Comment by umlaeute** [comment]
> Keep things as is doesn't seem good to me.

I don't see the problem.


> We'll just have these deprecated creators loading the new help files which doesn't document the actual behaviour or explain anything.

It doesn't need to.


>
>So I'm asking, should we really deprecate and remove the code?

This is not my understanding of "deprecating" things.
Instead (for me) it's along the lines of [Wikipedia] (https://en.m.wikipedia.org/wiki/Deprecation), which says: 

> Typically, deprecated materials are not completely removed to ensure legacy compatibility or back up practice in case new methods are not functional in an odd scenario.

**Comment by porres** [comment]
> I don't see the problem.

And what about the solution* I offered to the problem you don't see? Is there a problem with it or is it ok?

(*removing the help files and just adding a subpatch to the current help file)

**Comment by umlaeute** [comment]
> removing the help files 

Fine with me

> and just adding a subpatch to the current help file


I don't see the necessity, but ymmv
