### ISSUE TITLE
memory leakage when opening text define window, using pd 0-53.1

### ISSUE THREAD

**Issue by abreubacelar** [pure-data/pure-data#1860]
this patch is making wish process accumulate memory usage until it makes all my computer stop responding

[lkfsTest.zip](https://github.com/pure-data/pure-data/files/10298807/lkfsTest.zip)

see the image for the memory increasing
![Captura de tela de 2022-12-24 12-17-08](https://user-images.githubusercontent.com/16086370/209442318-c1cce78a-69da-4b60-ac56-7d17d645f79b.png)

the wish process alone had 4 gb of memory when i took the screenshot, i tried to close the patch then i got watchdog: signaling pd...

using self compiled pd on ubuntu 22.04.1 LTS

(i will try now to delete parts of the patch until the problem disappears, and update here)

**Comment by abreubacelar** [comment]
ok, smaller version that shows the same problem:

[textDefineBugPatch.zip](https://github.com/pure-data/pure-data/files/10298903/textDefineBugPatch.zip)

when you open the patch, the wish process has 12 mb of ram here, and it stays still

then:
1. open text define window 

memory will start to increase

2. close text define window

memory won't be released, but now stops to increase

3. open text define window again

memory will "wait" some time before it starts to increase again (like it was reserved to wish process but only after some time it needs to allocate more)

**Comment by sebshader** [comment]
What version of tcl/tk is it?

**Comment by abreubacelar** [comment]
> What version of tcl/tk is it?

hmm, never did this before, but is this the correct way to get it?

```
tclsh
% puts $tcl_version
8.6
% puts [info patchlevel]
8.6.12
% 
```

**Comment by sebshader** [comment]
yeah that should be the version on linux. Pd should also say in the console when it starts up which is more reliable on other platforms

**Comment by sebshader** [comment]
yeah that should be the version on linux. Pd should also say in the console when it starts up which is more reliable on other platforms

**Comment by umlaeute** [comment]
> Pd should also say in the console when it starts up

sidenote: you need to raise the log-level to `4 all` in the GUI to see the printout.

> which is more reliable on other platforms

not more *reliable* but much more *simple*.
anyhow: :+1:

**Comment by sebshader** [comment]
I mean, that MacOS or windows might have tcl/tk installed somewhere system-wide that is less likely to be used by pd on those systems because it will use its own tcl/tk

**Comment by sebshader** [comment]
so I haven't looked into wish's text editor implementation but it might be the case that it supports some kind of history or undo, storing previous lines.
maybe there's some option to disable that..
many text editors still keep previous values in memory structures like ropes, piece tables, or gap buffers

**Comment by sebshader** [comment]
https://www.tcl.tk/man/tcl8.6/TkCmd/text.html#M88

**Comment by sebshader** [comment]
sure enough, seems changing the value of the ```-undo``` option in ```pdtk_textwindow_open``` stops memory from increasing..
plus, looks like tcl/tk doesn't delete the undo history of a text widget but stores it somewhere: https://www.tcl.tk/man/tcl8.6/TkCmd/text.html#M89
