### ISSUE TITLE
Pd v.0.53-1 is in fact v.0.53-0 under Windows 10

### ISSUE THREAD

**Issue by joe-rouen** [pure-data/pure-data#1861]
I have the same issue than here in [[PD] Pd0.53-1 for Windows downloads look like Pd0.53-0](https://lists.puredata.info/pipermail/pd-list/2022-12/131841.html).
Thank you.

**Comment by ben-wes** [comment]
This was immediately fixed though with another build and reupload by @millerpuckette. Can you check on http://msp.ucsd.edu/software.HTML and possibly reload if you don't see yesterday's update (there are comments about this on the site now)? I checked and it all looks correct to me now when I reinstall. If you can confirm this, feel free to close this issue again. :)

**Comment by joe-rouen** [comment]
Done: Just downloaded the latest  'pd-0.53-1.windows-installer.exe' (7826 KB) from msp.ucsd.edu, uninstalled the previous one and installed the new one.
It's looking OK now: Pd version 0.53.1!
Thanks to all involved. :)
