### ISSUE TITLE
Sending disconnect command to a patch triggers Tcl Invalid Command Name: x6000087e8000.c

### ISSUE THREAD

**Issue by DaliuSinger** [pure-data/pure-data#1863]
Sending a disconnect command to a hidden PD patch will trigger:

`(Tcl) INVALID COMMAND NAME: invalid command name ".x6000087e8600.c"
    while executing".x6000087e8600.c delete {l60000388c5e0} "
    ("uplevel" body line 2)
    invoked from within
"uplevel #0 $docmds"`

This can be reproduced in the help file, under namecanvas > pd-messages > pd Dynamic-Patching > pd (dis)connecting-boxes.
Create objects by clicking on the message box, connect, **close the patcher window** and click disconnect message.
This will trigger the error... Very annoying.
Many thanks!

<img width="507" alt="Screenshot 2023-01-09 at 16 03 33" src="https://user-images.githubusercontent.com/51788325/211339780-17461055-22d2-4d77-8d6e-e9b7263f6162.png">

**Comment by umlaeute** [comment]
confirmed.

**Comment by DaliuSinger** [comment]
But it works on creating the connections and it works disconnecting then just with that error.

**Comment by umlaeute** [comment]
yes, i never doubted that.
