### ISSUE TITLE
[send~] now is supposed to deal with different block sizes but instead segfaults

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1874]
I don't know why [send~]/[receive~] now deal with block sizes different than 64, but... cool :) 

I tried a patch with [block~ 128], if I get the output of [r~] and try to print it with [print~] I get a ridiculously large amount of samples in the Pd console and Pd ends up freezing, so it doesn't feel like this is working well yet :)

**Comment by porres** [comment]
ping @millerpuckette / @umlaeute

**Comment by umlaeute** [comment]
simple typo that would read data from the very wrong location...

**Comment by porres** [comment]
perfect, it works great, and I love that we now can do a single sample feedback with [send~]/[receive~] instead of using delay lines or [tabsend~]! Game changer!

**Comment by porres** [comment]
can we close this then @umlaeute ?
