### ISSUE TITLE
Radio objects output an out of range value if their extreme edge is clicked on

### ISSUE THREAD

**Issue by smdoles** [pure-data/pure-data#1875]
I discovered today that when clicking on a radio object, if I accidentally his the very far edge of it (right in a horizontal radio object), it will output a number one higher than the highest box in the object. So if it's a size 8 horizontal radio object, hitting the very rightmost edge will cause it to output an 8 instead of the 7 for the highest box. I noticed this first with a horizontal radio, but I also reproduced it with a vertical radio.

**Comment by porres** [comment]
yup, can confirm... should be easy to fix by clipping the output

**Comment by porres** [comment]
I think this seems like a simple/easy fix to go into develop @umlaeute
