### ISSUE TITLE
Shortcut for Help->Search is the same as Pd->Hide Pd on MacOS

### ISSUE THREAD

**Issue by virusys** [pure-data/pure-data#1883]
Running Pd 0.53-0 in MacOS, pressing MacOS' global shortcut for hiding applications (Command+H) does not hide Pd as expected, but instead launches the Search and Browse Documentation window. 

![Screen Shot 2023-01-31 at 11 24 09 PM](https://user-images.githubusercontent.com/393711/215946744-12d6a016-7774-4d78-bd26-2a08c124b3cb.png)

**Comment by umlaeute** [comment]
found it: it's the *search-plugin* that adds this window and indeed registers the <kbd>⌘</kbd>+<kbd>h</kbd> shortcut.

closing this ticket, as it's out of scope for the puredata repository.

**Comment by virusys** [comment]
Ah okay, I hadn't realized that `search-plugin` was an external I downloaded, my bad!
