### ISSUE TITLE
Jack support not enabled on Linux when building with src/makefile.gnu and OSS=false

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#189]
From Yoann Le Borgne on the pd-list:

After reading src/makefile.gnu, I could however compile with OSS disabled by using:

    make -f makefile.gnu JACK=true PA=false OSS=false

But doing this compiles Pd without working Jack support

**Comment by Barbouze** [comment]
Hi! Yoann here, posting from a different mail address ;)

I tried again, this time from a fresh git clone and I can't reproduce this bug. I suppose there were remains of automake files when I raised this problem.

Sorry for the inconvenience

**Comment by danomatika** [comment]
Right. It helps to do a `make clean` in between builds sometimes.
