### ISSUE TITLE
pdcontrol query for dsp-state

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1890]
yup, another feature for [pdcontrol]...  a "dspstate" message to query for dsp status, which should give us the output of pd_getdspstate()

The use case is to set a toggle that shows us if the DSP is on or off. I would also like to use this in the documentation, which now uses toggles to set DSP on/off. In the case the DSP is on, the toggle would also be on. Right now you have a toggle that can be off when audio is on...

**Comment by Spacechild1** [comment]
![grafik](https://user-images.githubusercontent.com/16126632/217401650-5fb8aafe-5a65-4a87-8705-e913182393b3.png)

**Comment by porres** [comment]
wow, I didn't know "pd-dsp-started" would fire when you open a patch...

seems like a hacky way to do it, but fine, my request is not necessary if I use this :)

I guess I'll explore this in the documentation so this trick also gets more attention

**Comment by porres** [comment]
something like this, what do you think? 

![Screen Shot 2023-02-07 at 22 38 52](https://user-images.githubusercontent.com/5360142/217406584-85c60607-567a-46cf-9340-a8ff159f6bd3.png)

**Comment by porres** [comment]
something like this, what do you think?

![Screen Shot 2023-02-07 at 22 38 52](https://user-images.githubusercontent.com/5360142/217406652-e9a0ae67-52ac-42cb-991d-4018fa32b3c9.png)
