### ISSUE TITLE
error when entering emojis

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1900]
When I enter an high-unicode character (e.g. an emoji like 🤷), an error window pops up.

0. Entering an emoji is probably platform dependent. On my Linux/XFce4 system I can do that with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>u</kbd> (which enters unicode mode; then I enter the unicode codepoint, e.g.) <kbd>1</kbd>-<kbd>f</kbd>-<kbd>9</kbd>-<kbd>3</kbd>-<kbd>7</kbd> (followed by a finishing) <kbd>Enter</kbd>.
1. Start Pd
2. Focus on the Pd Window
3. Enter the emoji
4. Get an error

```
too many nested evaluations (infinite loop?)
too many nested evaluations (infinite loop?)
    while executing
"split $iso {}"
    (procedure "::pd_bindings::sendkey" line 55)
    invoked from within
"::pd_bindings::sendkey $window $state $key $k $shift $keycode"
    (procedure "::pd_bindings::sendkey" line 56)
    invoked from within
"::pd_bindings::sendkey $window $state $key $k $shift $keycode"
    (procedure "::pd_bindings::sendkey" line 56)
    invoked from within
[...]
"::pd_bindings::sendkey .pdwindow.text 1 ?? 🤷 0 0"
    (command bound to event)
```

So it seems that #736 did not completely fix the issue with multichar keystrokes (see also #732)

**Comment by umlaeute** [comment]
the problem is obviously that the following parameters are passed to `sendkey`:
| variable | value |
|-------------|----------|
| key         | `??` |
| iso          | `🤷` |

This enters an inifite loop, as `string length 🤷` returns **2**, but `split 🤷 {}` only returns a single character:
https://github.com/pure-data/pure-data/blob/4baa03e4a4edb5b07758ecad032c9a8611a9d64b/tcl/pd_bindings.tcl#L467-L473


Probably a better solution is to just run `split $iso {}` for all cases, and then count the elements returned by this (instead of running `string length`)

**Comment by umlaeute** [comment]
i can confirm that the problem also exist on macOS (</kbd>⌃</kbd>+</kbd>⌘</kbd>+</kbd>Space</kbd>)

**Comment by danomatika** [comment]
Is `string length` unicode-aware? Seems to be. The [man page](https://tcl.tk/man/tcl8.6/TclCmd/string.htm#M33) says:
>Returns a decimal string giving the number of characters in string. Note that this is not necessarily the same as the number of bytes used to store the string. If the value is a byte array value (such as those returned from reading a binary encoded channel), then this will return the actual byte length of the value.

Judging from the above, I would expect `string length 🤷` to return 1...

**Comment by umlaeute** [comment]
here it returns `2`...

**Comment by umlaeute** [comment]
it seems that with TclTk-9.0, `string length 🤷` finally returns **1**.

**Comment by danomatika** [comment]
Yeah. When does Tcl/Tk  come out?  ;)
