### ISSUE TITLE
long objects are no longer wrapped in the pd file

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#1902]
Current master does not wrap long lines (text, messages, objects) when saving a patch to a .pd file. I'm just reporting this in case this change was not introduced intentionally. 

A side effect of the new style: When saving patches created with previous versions of Pd, git detects a lot of changes even when nothing was changed in the patch by the user

**Comment by umlaeute** [comment]
the current behaviour was introduced by me intentionally in 540321fe079638fce3a5e7bb22fb1436e1bedf85.

i did not announce it very loudly (you could even say: i sneaked it in), but i really think it is a great improvement, *especially* if you are tracking your files in git.

now that you have opened this issue, millerpuckette is likely to notice the changed behaviour and revert it. :cry:

**Comment by reduzent** [comment]
Ok. Thanks for clearing this up.  I'm sorry for raising awareness of this change. I close the issue right now.
