### ISSUE TITLE
Hidden Application after installation on Windows 11 

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1904]
I've just installed Pd-0.53-1 on a "Windows 11 Home" machine (that was just converted from "Windows 11 S-Mode" and while *that* installation was almost a year old, no significant modding happened (as is the case with S-Mode), so I consider the machine almost "pristine").

After installation (with the default exe-installer), Pd is launched just fine.

However, afterwards I can no longer find the Pd application launcher.
I can find the `pd.exe` of course, but there is
- no Application shortcut on the Desktop
- no Entry in any "App" menu of the system

of course I am a total noob when it comes to Windows (and even more so in a crippled version like "Home"), so I might just be looking in the wrong places.

Sidenote: file associations work fine.
It just seems to be a problem with registering Pd as an "App" to the system.

**Comment by Lucarda** [comment]
I had just tested the installer on `Windows 11 pro` and I get the descktop shortcut and the entry on the App menu:

 
![win11-post-install](https://user-images.githubusercontent.com/25239522/222991192-8497bdd0-a106-4197-98ea-390d260d3020.png)


I think that on `Win11 home` you have to run the installer with `admin rights`.

you can first uninstall the app from:

`Control Panel\All Control Panel Items\Programs and Features` (paste this on a file explorer address)

re-run the installer (right-click on the installer -> Run as administrator)

Note: This is one of many issues that makes one consider upgrading from `home` to `pro` :)

**Comment by umlaeute** [comment]
thanks for confirming.

> I think that on *Win11 Home* you have to run the installer with **admin rights**.

I think I did.
I'm *pretty* sure that I had to enter the admin-password for the installer (but probably I did not "Run as Administrator").
I'm going to try again in the next few days.

a quick question about your screenshot: in the "Pinned" section it says `pd` (all lower-case), rather than `Pure Data (64bit)`.
Is this by your doing, or something automatic (e.g. because the actual executable is called `pd.exe` rather than `Pure Data (64bit).exe`)?
And does this launch the pd-core or the pd-gui? (see #1905)


> Note: This is one of many issues that makes one consider upgrading from home to pro :)

it's not that I'm actually going to use either *Home* nor *Pro*.
However, I would like users be able to run Pd, even if they somehow decide that they *Home* is their thing.

**Comment by Lucarda** [comment]
> a quick question about your screenshot: in the "Pinned" section it says pd (all lower-case), rather than Pure Data (64bit) (as in the "Recommended" section).
Is this by your doing, or something automatic (e.g. because the actual executable is called pd.exe rather than Pure Data (64bit).exe)?
And does this launch the pd-core or the pd-gui? (see https://github.com/pure-data/pure-data/issues/1905)

What you see in the pic (the names of the app in the "pinned" and in the "desktop icon") where right after running the installer. Nothing done by me.

it lunched the pd-core when finished with default options from the installer (ticked "see readme" and "start pd"). I think this is what your question is about.

**Comment by umlaeute** [comment]
> it launched the pd-core when finished with default options from the installer (ticked "see readme" and "start pd"). I think this is what your question is about.

ah, no. the question is, what gets launched if you click the `pd` icon (rather than the `Pure Data (64-bit)` icon)

**Comment by umlaeute** [comment]
hmm. i checked on that computer again, and:
- when logged in with the Admin account (where i guess i performed the installation), there's an app icon on the desktop.
- when logged in as a normal user, there's no app icon (which i guess is expected).

as the normal user, i cannot find the Application in none of the *pinned*, *recommended* and *All* apps

**Comment by umlaeute** [comment]
> Can you test it on your win-home non-admin user?

not before tomorrow.

anyhow, the docs for `RequestExecutionLevel` talk only about Vista and Win7. I would have assumed that to mean "this is a compat flag for old versions of Windows and is not needed anymore". But of course it could also mean that the docs (are 15 years old and) mean "this flag is required for newer versions of Windows, starting with Vista/Win7"...

**Comment by umlaeute** [comment]
afaict, the problem is, that the launcher is not installed into `C:\ProgramData\Microsoft\Windows\Start Menu\Programs`  (presumably `%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs`.
Manually copying the launcher-shortcut into this folder, makes it visible in to all the users.

See also:

- https://www.techguy.org/threads/solved-nsis-smprograms-in-user-start.902981/post-7250625
- https://nsis.sourceforge.io/Reference/SetShellVarContext

**Comment by Lucarda** [comment]
I can't get into this until next monday.

of course there should be an `nsis` way to install to all users. but I would like to know anyway how the above link installer work, the `RequestExecutionLevel highest` thing should be what non-admin users want.

Please test : https://nc.nubegris.com.ar/index.php/s/ZjrJy9NgMLwPpaD in your *winn11:home* *non-adin-user*.

**Comment by umlaeute** [comment]
OK.

my system has two account:
   - *admin* (with admin privileges)
   - *user* (without admin privileges)
   - there's other non-account users as well (but only a single admin-account)

0. I uninstalled my previous Pd installation
1. log in as *user*
4. Downloaded https://nc.nubegris.com.ar/index.php/s/ZjrJy9NgMLwPpaD  as *user*
5. Run the installer as *user* (double-clicking).
   - this started OK, but as soon as it came to actually copying files, it would stop
<img width="665" alt="InstallPd 2023-03-10 090221" src="https://user-images.githubusercontent.com/214034/224263753-7db01d41-e5de-4c2a-85e6-48f453a1032c.png">

  - <kbd>Repeat</kbd> just shows the error again, <kbd>Skip</kbd> shows the error for the next file. I decided to <kbd>Cancel</kbd> instead.
6. Right-click the installer (as *user*) and "Run As Adminstrator"
   - this asks me for the credentials of my *admin* account. after giving them, the installer proceeds and eventually finishes.
7. Selecting the "Launch Pd now" option, launches the Pd-GUI (so obviously #1905 is fixed :-))
8. There are *No traces* of a "Pure Data" installation. E.g. this is my "All Apps" view:
<img width="186" alt="AppsUser 2023-03-10 090727" src="https://user-images.githubusercontent.com/214034/224265134-42857a5e-9a31-4779-8c38-c093e043e3e1.png">
9. Switch to (login as) *admin*
10. Here I can see the "Pure Data" installation as expected:
<img width="136" alt="AppsAdmin 2023-03-10 090859" src="https://user-images.githubusercontent.com/214034/224265398-4b146c3f-fcea-402d-a780-1199cebe06fe.png">

11. I see that Pure Data is installed into the *admin*'s `%AppData%\Microsoft\Windows\Start Menu\Programs`
12. I see that there is *no* Pd in the global ~`%ProgramData%\Microsoft\Windows\Start Menu\Programs`~.
13. So I copied the "Pure Data" folder into `%ProgramData%\Microsoft\Windows\Start Menu\Programs`
14. Switch to *user*
15. I now have a `Pure Data` (folder-)app in my start menu #1236 


so to conclude:
- your package fixes #1905 
- however, it does **not** fix this issue with "Application not being in Start Menu except for the user how installed Pd"
- it makes things slightly worse (at least, I cannot remember seeing these "Error opening file for writing" popups when running Pd as a non-admin *user*.


### Sidenotes about the visual appearance of the startmenu:
- the "Pure Data" app-name now looks good (no more "64bit")
- the "Uninstall" looks a bit sad. Could that me named "Uninstall Pure Data" instead?
  (while searching for the uninstall option of Pd via my Win11 global search, I encountered a lone "Uninstall" application without any context of what would be uninstalled if i clicked it. This might have been Pd's uninstaller or not (it might have been called `Uninst`, cannot remember right now; but i'm pretty sure it featured the generic NSIS-uninstaller icon), but it reminded me, that we might improve UX by giving more context)
- why is there no icon for the website?

**Comment by umlaeute** [comment]
I've moved the "visual appearance" remarks into a separate ticket:
- #1912

**Comment by Lucarda** [comment]
> - your package fixes Pd-core is launched in post-installer (rather than Pd-gui) #1905

good

> - however, it does not fix this issue with "Application not being in Start Menu except for the user how installed Pd"

we will have to tackle that based on what you posted above.


> - it makes things slightly worse (at least, I cannot remember seeing these "Error opening file for writing" popups when running Pd as a non-admin user.

:(

`RequestExecutionLevel` does not buys us anything. we can wipe it and leave the installer as it was before. I expected that user/pass were asked.


I'll look into all this on next monday.

**Comment by Lucarda** [comment]
@umlaeute  please test

https://nc.nubegris.com.ar/index.php/s/HgGHiGr6NBWd7NP
    
- it installs for all users but you need admin rights (default behavior)
  - also admin rights are required to uninstall

- website icon from `shell32.dll` on the target machine.

**Comment by umlaeute** [comment]
i'll try to test tonight.

> it installs for all users but you need admin rights (default behavior)

is it possible to *also* install as a normal user (who has does not know any admin credentials), falling back to the old behavior?
to be honest, i have no clue, but iirc Pd by default tries to install into %ProgramFiles%, which requires admin privileges. *however*  you can ask it to install into some other place (where you are allowed to write). if this is the use-case for a given user, it would also be nice if they could install the new version (which might require to answer a question in the installer, whether they want to make the application available for everybody. or somesuch.

something like:
- check the privileges of the current user (using the `UserInfo` module)
  - https://nsis.sourceforge.io/Reference/SetShellVarContext
  - https://nsis.sourceforge.io/Examples/UserInfo/UserInfo.nsi
- if we **do** have admin privileges, default to installing the launcher to %ProgramData% (with `SetShellVarContext all`)
- if we **do not** have admin privileges, default to installing the launcher to %AppData% (with `SetShellVarContext current`)

**Comment by umlaeute** [comment]
so here's the result of my test.

### installation

0. first i uninstalled Pd (at least i think i uninstalled it; but later on i discovered some leftovers)
1. starting the new installer as a "normal2 (non-admin) *user* immediately asks for the *admin* password.
2. after that, it's a smooth ride.

being asked for the *admin*-password felt natural (keep in mind that I am not a Windows guy), so you probably can disregard my last comment on supporting both admin and non-admin installation.

### availability ("hidden-ness")

once the installation was done, the "Pure Data" application did show up in my "Apps".
switching to another (non-admin) user, "Pure Data" still shows up.

:tada: mission accomplished :fireworks: 

### URL-icon

the link to puredata.info now has some generic icon.
i'm slightly confused which icon is used, as at first it seemed that it was just the Edge-icon (which is the default browser for that account), but later on it was an unknown-to-me icon with a monitor and a world (see screenshot).

i could associate both icons with "the internet", and it does look much nicer than the blank "document" icon.
so:

:tada: mission accomplished :fireworks: 

### Uninstaller name

this confused me most.
1. in the "Apps" view, i do not see any uninstaller.
2. if I navigate to `%ProgramFiles%\Pd\`, I can see an `uninst` application :smirk: 
3. there's still the "Uninstall" option in the Settings->Apps.

<img width="131" alt="Screenshot 2023-03-13 210749" src="https://user-images.githubusercontent.com/214034/224840190-ebebf0c3-46af-4c9f-af57-409e6256c413.png">


i'm honestly not sure whether this is an improvement or not. 
i don't recally any application having an "Uninstall" option in the "Apps" view, so it's probably a good idea that Pd doesn't have one either.
the `uninst` application in `%ProgramFiles%\Pd\` is definitely uglier than what I remember (but I figure that people are not advised to go into `%ProgramFiles%\Pd\` anyhowm so it's probably not a big deal.

**Comment by Lucarda** [comment]
### installation

> being asked for the admin-password felt natural (keep in mind that I am not a Windows guy), so you probably can disregard my last comment on supporting both admin and non-admin installation.

I would like to stay away from non-admin installation for now. It seems complicated for he registry settings.

https://nsis.sourceforge.io/Docs/MultiUser/Readme.html

It can be done surely but it will take me toooooo long testing and I think most people have rights on their computers and eventually in a desperate need you have the zip package.



### URL-icon

this is taken from Windows system icons `"%SYSTEMROOT%\system32\shell32.dll" 14` 14 is the index of one of them. They are different on each OS release.

win11:

![uninstallwin11](https://user-images.githubusercontent.com/25239522/224905223-2cc68b79-775a-4b23-b184-a5eff491567b.png)


win10

![ununstallwin10](https://user-images.githubusercontent.com/25239522/224905239-f5e0468b-de2d-44ad-810e-47cb5fce7f73.png)


### Uninstaller name

> this confused me most.

Me to.

NOTE: I used Millers installer on Win10 and I could see the **uninstaller icon** in the start menu folder. 2 seconds later it was gone. Same with my installer. Don't ask. and also don't ask me why I can't reproduce with the last installer I did.

Also while changing the code there where sometimes where I could not see it in my Win11 dev machine. I thought there was white-space trouble in the expansion on `"$SMPROGRAMS\${PRODUCT_NAME}\Uninstall ${PRODUCT_NAME}.lnk"`
so now I switched to `Uninstall-Pd.lnk` to put the code in the safest possible state.


----------------

I will push to #1909 to expose the changes

**Comment by Lucarda** [comment]
here is an installer as [900dc36](https://github.com/pure-data/pure-data/pull/1909/commits/900dc36321a707e4d6bc7a6b1175ff6133bdbe03)

https://nc.nubegris.com.ar/index.php/s/LatM7ECyX2d4iJ9

**Comment by umlaeute** [comment]
The uninstaller now looks good (kind of :-))

<img width="144" alt="Screenshot 2023-03-14 193617" src="https://user-images.githubusercontent.com/214034/225259556-57f68e4b-91f1-4bb7-9690-88f6bcfa7670.png">
