### ISSUE TITLE
Pd-core is launched in post-installer (rather than Pd-gui)

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1905]
When installing Pd on a Windows host with the installer, there is the option to launch Pd after the installation.

Now it seems that if you choose this option, it launches `pd.exe` (that is: `pd-core`) for you.

However, with the normal Application menu (at least if they work; see #1904 ), the `pd-gui` is launched instead of the pd-core.

There are subtle differences between the two. The most prominent (and which is why I am raising this here) is that Pd-GUI will run the "Pd Documents" dialog.

As a "normal" user, i would expect that this "Pd Documents" dialog is indeed thrown into my face when launching from the installer. (Currently the experience is like this: during the installation Pd is launched "just so"; when later launching Pd "for real" for the first time, the user is presented the "Pd Documents" dialog).

The other subtle difference is, that Pd-GUI prevents multiple instances of the Pd-GUI, and I'm not sure what happens if you have a Pd open while installing a new version (and i'm not even sure what *should* happen in that case)

**Comment by Lucarda** [comment]
I got a fix for this that is not so a trivial one-liner.

I'll make a PR when `develop` gets reopened.

**Comment by umlaeute** [comment]
it probably would be nice to be able to bypass the "already running" check somehow...

**Comment by umlaeute** [comment]
on closer inspection, I think it is already implemented.

1. the "key" to detect whether Pd is already running contains the full scriptname https://github.com/pure-data/pure-data/blob/4baa03e4a4edb5b07758ecad032c9a8611a9d64b/tcl/pd-gui.tcl#L745-L747
    so if the pd-gui.tcl script is in a different location than the already-running Pd, a new Pd is opened

2. if you try to install Pd in the same location as the already-running Pd, Windows will probably refuse to install anyhow, as some files are "in use" (so the only way to install Pd while there is an instance of Pd running is in different locations, which sends us back to item#1)

**Comment by umlaeute** [comment]
> I'll make a PR when develop gets reopened.

PRs cannot target other PRs. They can only target *branches*.
Since the `develop` branch exists even now, you can create your PR right now (targeting `develop`).

Once there is *any* new content in the `develop` (e.g. *your* commits), I will open a PR (from `develop` to `master`).
One cannot create a PR with no differences (right now `develop` does not diverge from `master` at all)

**Comment by umlaeute** [comment]
actually dan pushed to`develop` last night, so i've opened #1907...

**Comment by umlaeute** [comment]
while hacking on the Pd-installer: would it make sense to change the naming scheme a bit:

| old | new |
|----|----|
| Pure Data (32-bit) | Pure Data (32-bit) |
| Pure Data (64-bit) | Pure Data |

that is: make the 64bit installation the default, and only add extra information if the word-size is onn-default (that is: 32bit)

**Comment by Lucarda** [comment]
PR for all this on https://github.com/pure-data/pure-data/pull/1909
