### ISSUE TITLE
Windows start menu improvements

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1912]
The windows start-menu entry could be improved:

<img width="136" alt="AppsAdmin 2023-03-10 090859" src="https://user-images.githubusercontent.com/214034/224269050-093e5a10-75ba-4453-98fb-5301f25404bc.png">

1. The default installation these days is the "64bit" windows. I think there is no need to call this default installation "*Pure Data (64bit)*", and it should instead be just called "*Pure Data*"
   - This has been discussed in https://github.com/pure-data/pure-data/issues/1905#issuecomment-1455670672
   - This has been fixed in 9a8f914b45704b7775e9643ae86cb1f6e4912445 (#1909)
   - (The screenshot above uses a binary from this PR, that's why the name is fixed here)

2. The "Uninstall" looks a bit sad. Could that me named "Uninstall Pure Data" instead?
    (while searching for the uninstall option of Pd via my Win11 global search, I encountered a lone "Uninstall" application without any context of what would be uninstalled if i clicked it. This might have been Pd's uninstaller or not (it might have been called Uninst, cannot remember right now; but i'm pretty sure it featured the generic NSIS-uninstaller icon), but it reminded me, that we might improve UX by giving more context)

3. Why is there no icon for the website?

observations made on *Windows11/Home*

**Comment by Lucarda** [comment]
### about the uninstaller

we can surely give it a better name. but right now there is a full name of the app if you go to the standard uninstall practice:

control panel / Programs and Features


![uninstall-thing-1](https://user-images.githubusercontent.com/25239522/224361325-26e6054f-0b12-462b-97dd-04a1bbaf7a26.png)


### about: icon for the website


I will get into it next monday.

**Comment by umlaeute** [comment]
> we can surely give it a better name. but right now there is a full name of the app if you go to the standard uninstall practice:

i know (and this is how i uninstalled Pd).
But even though the executable is called by the Programs-and-Features software-center regardless of the actual name, i still think it could have a nicer name in case you come across the file without much context.


i also forgot to mention (though it should be pretty obvious), that the issues i mention here are very minor (so don't invest too much time...but then i think/hope they are low hanging fruit anyhow)

**Comment by Lucarda** [comment]
see https://github.com/pure-data/pure-data/issues/1904#issuecomment-1465789130

there is an installer there that fixes the "uninstaller name" and the "website icon"
