### ISSUE TITLE
iemguis's labels don't appear if it ends with "_"

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1924]
gui boxes (number/symbol/list) do not have a problem with it.

**Comment by umlaeute** [comment]
cannot reproduce.

i tried:
- setting the label to "transpose_" in the properties
- (re-opening the properties and) re-setting the label to "help_" in the properties
- setting the label to "juju_" via a message
- (re-opening the properties and) re-setting the label to "help_" in the properties

the label always displays correctly and i don't get any errors.
this is with both Pd-0.53-1 (as packaged in Debian) and current `develop` branch (77dd0898)

![label_](https://user-images.githubusercontent.com/214034/226399314-1f8454dd-fcd0-4b63-811b-60c2a602724d.jpg)

please provide a full example showing the problem.

**Comment by umlaeute** [comment]
funnily enough, I do see **no** label in the patch provided in #1921.
