### ISSUE TITLE
Pd crashes with 64 channels and a JACK-blocksize of >=2048

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1930]
1. configure jack to use a blocksize of *2048*
2. start `pd -jack -channels 64`
3. turn on DSP
4. notice a segfault

it **does** work, if 
- you limit Pd's channels to 32
- use a smaller JACK blocksize (e.g. *1024*)

Test system:
| key | value | note
|---|---|---|
|OS | Debian | bullseye(+bpo) |
| arch | amd64 | 
| soundcard |  RME Hammerfall DSP MADI |
| JACK | jackdmp 1.9.17 | `jackd2_1.9.17~dfsg-1` |
| Pd | 0.53-1 | `0.53.1+ds-2~bpo11+1`|

**Comment by umlaeute** [comment]
I guess the real threshold is `blocksize * channels` but haven't actually checked.

**Comment by umlaeute** [comment]
also note that I cannot reproduce the issue on another machine running pipewire:

 key | value | note
|---|---|---|
|OS | Debian | sid/bookworm |
| arch | amd64 | 
| soundcard |  Focusrite Scarlett 2i2 USB |
| JACK | pipewire 0.3.64 | `pipewire_0.3.64-4` |
| Pd | 0.53-1 | `0.53.1+ds-1`| 

however, i'm unsure whether i actually managed to set the blocksize for pipewire (i used `qjackctl`)

**Comment by reduzent** [comment]
> however, i'm unsure whether i actually managed to set the blocksize for pipewire (i used `qjackctl`)

I use `jack_bufsize` for checking the actual buffer size used in the jack daemon. It seems that for pipewire the jack buffer size is configurable in `~/.config/pipewire/jack.conf` with: 

```
jack.properties = {
     node.quantum       = 128/48000
}
```

**Comment by reduzent** [comment]
I can reproduce the issue here, but the segfault only happens when I turn DSP on (or if I load  a patch that does it). Simply following your three step does not segfault here.

**Comment by umlaeute** [comment]
i think the problem is, that Pd tries to allocate the jack buffers on the stack: https://github.com/pure-data/pure-data/blob/4baa03e4a4edb5b07758ecad032c9a8611a9d64b/src/s_audio_jack.c#L60-L62

And with 512KiB, we hit the stack frame size.

**Comment by reduzent** [comment]
> And with 512KiB, we hit the stack frame size.
Seems consistent with the fact, that using 1024 as buffer size and `-channels 128` also triggers the  segfault.

**Comment by umlaeute** [comment]
should be fixed in current `develop`.
Could you test?

**Comment by reduzent** [comment]
Works now even with:
* `/usr/bin/jackd -dalsa -dhw:sofhdadsp -r48000 -p2048 -n2`
* `pd -jack -channels 128`
