### ISSUE TITLE
.ps does not seem to save fonts properly, PDF/SVG/PNG printing coming in the future?

### ISSUE THREAD

**Issue by esaruoho** [pure-data/pure-data#1938]
i just went through the trouble to convert a .ps to .pdf and this was the result - is there any chance Printing would allow for saving SVG or PNG or PDF directly, eventually
[multimagic-16plom_-_-_bicoeff_wo_granulator_wospectrograph.pdf](https://github.com/pure-data/pure-data/files/11130607/multimagic-16plom_-_-_bicoeff_wo_granulator_wospectrograph.pdf)
<img width="1435" alt="Screenshot 2023-04-02 at 0 11 22" src="https://user-images.githubusercontent.com/4966687/229314100-4f5d4a7c-c400-4438-ba3d-8b6f4f5a1048.png">

**Comment by umlaeute** [comment]
Export to SVG is provided via the `patch2svg` plugin (available via deken).
