### ISSUE TITLE
nbx2: deactivate log height in linear mode

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1939]
This is for the properties window! The log height parameter is only meaningful if you're in 'log' mode. It could then be inactivated when not in log mode, a bit like how defined user architecture is inactive in deken, when not set to it.

![Screen Shot 2023-04-04 at 14 06 05](https://user-images.githubusercontent.com/5360142/229865818-adb0ba5f-6239-42e0-9da7-d710a0bedfc2.png)

**Comment by umlaeute** [comment]
totally unrelated, but the user-defined platform indeken should not be `\{\}` (unless you set it to that value, which i doubt). could you please report this in the [deken](https://github.com/pure-data/deken/issues/) repository?
