### ISSUE TITLE
[soundfiler] not working for stereo files being fed into 2 arrays

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1948]
The help file example works, but uses the 'raw' flag, if you remove it and just have "read ../sound/bell.aiff array1 array2" it doesn't work!

tested with current master and 0.53-2

I do believe this worked at some point, so looks like a regression bug

**Comment by umlaeute** [comment]
reading stereo files into two arrays works for me.

note that the `bell.aiff` is a mono-soundfile, so if you remove the `-raw` flag, Pd will properly detect that there's only a single channel and act accordingly. (using the `-raw` header you can *force* Pd into accepting the file as a 2-channel file, even though it is not)
