### ISSUE TITLE
Change language via the GUI preferences

### ISSUE THREAD

**Issue by H-MLim** [pure-data/pure-data#1955]
just simple question: I'm so glad that the multi language translations in Pd are finally accepted after version 0.53. but how could change language if I want to? (ex. English -> Spanish). it seems it depends on the whole Window/Mac language settings, but can I change it inside the Pd preference?

**Comment by Spacechild1** [comment]
> but can I change it inside the Pd preference?

Unfortunately, this is not possible yet, but it would be a great feature!

In the meantime, if you want to "switch" to English, you can rename the "po" folder as workaround, and then rename it back to "po" to switch back to the current OS language :-)

I took the liberty to rename this issue and make it a feature request.

**Comment by umlaeute** [comment]
note that the `feature/gui-preferences` branch (#1379) implements this functionality.
