### ISSUE TITLE
"Pd documents directory cannot be found:"

### ISSUE THREAD

**Issue by swissscout** [pure-data/pure-data#1958]
After startup Pd asks me to choose a new location, because he can't find it. When I choose the location it gives me mentioned error, and I can't do it anything. 

I uninstalled and reinstalled Pd few times, with different versions of Pd, but didn't helped me out. 

Hope, someone has an answer to it. Have a nice one

```
UNHANDLED ERROR: invalid command name "if{!1}"
    while executing
"if{![::pd_docsdir::update_path $newpath]} {
                            # didn't work
                            return
                        }"
    (procedure "::pd_docsdir::init" line 73)
    invoked from within
"::pd_docsdir::init"
    ("uplevel" body line 273)
    invoked from within
"uplevel #0 $tclcode"
FAILED TO LOAD /Applications/Pd-0.53-2.app/Contents/Resources/Scripts/pd_docsdir.tcl
`

**Comment by umlaeute** [comment]
interesting.
does changing the line https://github.com/pure-data/pure-data/blob/dd20389559b3b293a1dd4fdc427f1881e3818bd3/tcl/pd_docsdir.tcl#L113 to 

```
if {![::pd_docsdir::update_path $newpath]} { 
```

help? (it's just adding a space betwen `if` and `{`)

1. Right click the `Pd.app`
2. Select `Show Package Contents`
3. with the Pd.app folder navigate to `Contents/Resources/tcl/`
4. open the `pd_docsdir.tcl` file with a *simple* text-editor (e.g. `TextEdit`)
5. fix the line
6. save and close `TextEdit`
7. restart Pd
