### ISSUE TITLE
Record window state within top level patch

### ISSUE THREAD

**Issue by pmallard** [pure-data/pure-data#1959]
Hello everyone,

Currently PD does not save the window state property (state "zoomed" that occur when maximizing a window or "normal" for not maximized but visible windows). 

It may then open patches on unwanted position (i.e. the user save in the maximize state but the window load on the former position, before the maximized state).

I propose to record the windows state within pd top level patches in order to be able to open the patch in the maximize state.

This change leads to a modification of the .pd file format to add the window state on the top level canvas line.
When the window state is missing it would default to normal state (i.e. neither maximized or minimized).

This may be at the very first line of the pd file as follows for a maximized window:
#N canvas 86 117 1600 817 10 zoomed;

Another example for a normal one :
#N canvas 86 117 1600 817 10 normal;

Unfortunately this change will impact the pd message 'setbounds' and may leads to regression with other window manager than the default tcl/tk one.
 
Regards,

**Comment by umlaeute** [comment]
see my notes in the PR why i think that this is a bad idea.
