### ISSUE TITLE
Improve adc~_dac~-help.pd

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#1975]
The "multichannel" section of adc~_dac~-help.pd could be improved. It starts by talking about `[dac~]` and then switches to `[adc~]` abruptly:

> \[dac~\] distributes multichannel signals over multiple outputs starting at the number given by its argument\[s\].
> \[adc~ -m 3 4\], for example, outputs a three-channel signal with an offset of 4 channels (so channels 5, 6, and 7).

I guess this is just an oversight.

Also, the different meaning of the "set" message in the multi-channel version of `[dac~]` and `[adc~]` should be mentioned as well.

Finally, I think there could be an example for `[adc~ -m]`.

@porres

**Comment by porres** [comment]
this is what I have and that's been merged, I think you have an olde version 
![Screen Shot 2023-06-09 at 19 54 50](https://github.com/pure-data/pure-data/assets/5360142/f5fefa8d-87f5-4207-9d39-f32ce7151c4d)

**Comment by Spacechild1** [comment]
Ah, sorry! That's much better!

Actually, now that I read the source code of `[adc~]`, I discovered that the "set" message is broken for the multi-channel version. Will make a PR and once it is merged you can update the help patch.

**Comment by Spacechild1** [comment]
The adc~/dac~ objects are likely to be revisited and the help patches will need to be updated anyway. Closing for now.
