### ISSUE TITLE
missing help file for [snake~]

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#1976]
The [snake~] objects currently have no help file... @porres to the rescue!

**Comment by porres** [comment]
weird, I have them here

![Screen Shot 2023-06-09 at 20 53 58](https://github.com/pure-data/pure-data/assets/5360142/2cf769a9-a87e-473d-b199-d54ba061ff03)

**Comment by porres** [comment]
hmmm, maybe @Lucarda already rescued... https://github.com/pure-data/pure-data/pull/1973/commits/c80512f343e89a8b16b9fe119c4679261c3df204

**Comment by porres** [comment]
but I still don't get how it works in my compilation and I can find the help file over here

**Comment by porres** [comment]
or maybe I have it because I am using the documentation branch with the fix by @lucarda , but I really believe not and, whatever, big mystery, just check if the doc branch works fine and maybe @millerpuckette can merge it once again

**Comment by porres** [comment]
I have to say I downloaded from master here https://git.iem.at/pd/pure-data/-/pipelines and got the help file of snake~ as well...

**Comment by Spacechild1** [comment]
> hmmm, maybe @Lucarda already rescued... https://github.com/pure-data/pure-data/commit/c80512f343e89a8b16b9fe119c4679261c3df204

Thanks, that's exactly the problem! `snake-tilde-help.pd` is indeed in my `doc` folder, but it is not installed by autotools.

**Comment by porres** [comment]
seems like it's not an issue for macos

**Comment by umlaeute** [comment]
> seems like it's not an issue for macos

that's because the `make app` on macOS (or rather the `mac/osx-app.sh` script) simply ignores all the `make install` magic and does a raw copy of the doc/ directory instead...https://github.com/pure-data/pure-data/blob/39c3d82ee838551bf5158b49452ee384e94a04d3/mac/osx-app.sh#L312
