### ISSUE TITLE
rename '-di', '-do', '-d' flags in [clone]

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#1977]
now that `[adc~]` has my proposed '-m' flag for multichannel, I guess it makes better sense to use the same for `[clone]`, and I also find 'd' a rather odd choice. So I propose '-mi' for "multichannel input", "-mo" for "multichannel output", and just '-m' for "full" multichannel support (both in and out).

ping @millerpuckette and @Spacechild1

**Comment by Spacechild1** [comment]
Makes sense to me.

**Comment by porres** [comment]
> Makes sense to me.

cool, maybe you could do it as part of https://github.com/pure-data/pure-data/pull/1978 ?

**Comment by millerpuckette** [comment]
THe thing is, in clone it's all multichannel - the distinction is whether it's distributed among the copies (hence "-d" or simply copied in and out (default).  That's different from what adc~ does, so it's not unreasonable to have the flags look different.

**Comment by Spacechild1** [comment]
I see. You are of course right that `[clone]` can take/output multichannel signals either way. On the other hand, outputs are packed, not distributed, so I am not sure what `-do` (or `-d`) actually stands for :) Maybe there is even a better name? For now, I will remove the commit from #1978.

**Comment by porres** [comment]
I guess [clone] is multichannel if you think every instance copy is a channel, and we have to see if, for instance, we sum them up in the output or not.

But I think the "multichannel" aspect relates to the signal connection, if it generates or if it receives a multichannel connection signal. And since the idea of "multichannel" connections just came up right now, and also that we never promoted [clone] in the documentation or whatever as a 'multichannel' thing, I guess it makes total sense to use a '-m' flag to say it gets and outputs multichannel signal connections. The '-d' flag is definitely more obscure in this sense. Also, 'do' sounds like the verb 'to do', haha.

**Comment by umlaeute** [comment]
just for the record: i would also favor `-m`, mostly because of the *do* verb-a-like.

**Comment by porres** [comment]
for the record, miller stated  _"-d" etc stand for "distribute". Another possibility would be "-f" , etc, meaning "fan" , "fan-in", "fan-out"._ at https://github.com/pure-data/pure-data/pull/2004#issuecomment-1608095233

I think "f" for fan is better indeed, but would still prefer "m"

**Comment by porres** [comment]
I guess this ship has sailed :)
