### ISSUE TITLE
can't read "::lastIdx": no such variable OSX 0.48.0

### ISSUE THREAD

**Issue by megrimm** [pure-data/pure-data#199]
If I start Pd. Then Pd -> Preferences -> Startup -> New

If I "X" out of the "Add new Library" window I get the following error:

can't read "::lastIdx": no such variable
can't read "::lastIdx": no such variable
    while executing
"if { $curIdx != $::lastIdx } {
        # clear any current selection
        $mytoplevel.listbox.box selection clear 0 end

        set oldIdx $::last..."
    (procedure "::scrollbox::release" line 5)
    invoked from within
"::scrollbox::release .gfxstub100574350 92 76"
    (command bound to event)

If I type something, "Gem" for example, and "X" out of window I get a similar error AND "Gem" (or whatever) gets added to "Pd libraries to load on startup":

can't read "::lastIdx": no such variable
can't read "::lastIdx": no such variable
    while executing
"if { $curIdx != $::lastIdx } {
        # clear any current selection
        $mytoplevel.listbox.box selection clear 0 end

        set oldIdx $::last..."
    (procedure "::scrollbox::release" line 5)
    invoked from within
"::scrollbox::release .gfxstub1006138e0 94 71"
    (command bound to event)

**Comment by megrimm** [comment]
well.... right now i can in no way reproduce what was happening yesterday. i tried adding/removing items from box, etc. but everything seems now fine. i do not know what might have changed.

i will keep messing around and if i get error again I will add details to this thread.

**Comment by danomatika** [comment]
Looks like IOhannes has a fix.
