### ISSUE TITLE
use 'make install' as part of the osx-app.sh process

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#1992]
this is inspired by https://github.com/pure-data/pure-data/issues/1976#issuecomment-1586363853

i would like to (optionally?) switch the `osx-app.sh` script to use `make install` as the source of truth for installing files.

This would give users of all platforms a more uniform view on the shipped files (and avoid things likes "the file is missing! - not on my system..."

since @danomatika did the script: are there any objections, thoughts,...?

**Comment by umlaeute** [comment]
ah i forgot: the main motivation for this is, to be able to ship a double-precision Pd in the generated .app

**Comment by umlaeute** [comment]
here's a question:
currently the Pd.app includes all .h files (headers) from Pd/src/, including decidedly private headers (e.g. `m_private_utils.h`).

I think we should only include the public headers (those installed by `make install`), which excludes:
- m_private_utils.h
- s_audio_*.h
- x_libpdreceive.h
- z_*.h
- s_utf8.h

afaict
- the additional m_*.h and s_audio*.h files are just mistakes.
- there is no use for the libpd headers (as there is no libpd in the app-package; not even sources to build it from the package).
- the sole s_utf8.h header might be of use to externals (though hopefully it is not, given that neither the Windows bundle nor the Linux packages ship it)

**Comment by danomatika** [comment]
The reason I avoided making the script the default build approach, is that you first have to build the Tcl/Tk Wish.app. This takes a bit of time and *requires* an internet connection whereas the current method will work out of the box if the build system has the minimum defaults.

At a minimum, this important detail should be noted. Another option I have thought of is to allow using a previous Pd .app as a doner for a newer build, ie. feed the script Pd-0.53-2.app when building Pd- 0.54.app. In this case, it just takes the binary and required frameworks, then fills the rest from the build tree, just as it does using the Wish.app.

**Comment by danomatika** [comment]
Regarding the headers: yes, it should ideally only ship with the public headers. I believe we decided to keep them there "for now" but perhaps this is a good time to change this with a new version.

**Comment by danomatika** [comment]
Ah, I misread the original post.

Regarding using `make install`, do you mean for "installing" from the build tree into the Pd .app or?

**Comment by umlaeute** [comment]
> Regarding using make install, do you mean for "installing" from the build tree into the Pd .app or?

yes.

e.g. `make install` already knows which binaries need to be installed into `bin/` (typically `/usr/local/bin` and `/usr/local/lib/pd/bin`, but on macOS the same files go into `${APP}/Contents/Resources/bin`).

i have a working prototype for having both single-precision and double-precision Pd in a single .app (as you suggested on the list).
but for this to work, i need some better logic to install binaries (and `make install` already has it)

**Comment by danomatika** [comment]
👍 Sounds good. I agree with utilizing long-standing tools which already have the logic for us. ;)

**Comment by umlaeute** [comment]
i think it's less about long standing tools but about not having multiple code-paths to (hopefully) reach the same result.

anyhow, i take it you are fine if i completely drop the old codepath for *manually* copying files into the .app bundle?

**Comment by danomatika** [comment]
>anyhow, i take it you are fine if i completely drop the old codepath for manually copying files into the .app bundle?

Ja, we can replace the `cp -R` lines if `make install` does the equivalent. I suppose you just need to override the install prefix when running `make app`?

**Comment by umlaeute** [comment]
so i've pushed an updated version for `osx-app.sh` to #1995, if you have time, could you review it?
