### ISSUE TITLE
WASAPI: test tone sounds higher at 44.1 kHz

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#1998]
I just tested the new WASAPI backend on Windows.

Try the following:
1. start DSP at the default settings (44.1 kHz) and play a test tone -> ok
2. change sample rate to 48 kHz and apply -> ok
3. change sample rate back to 44.1 kHz and apply -> test tone sounds higher!

@Lucarda Can you confirm this?

**Comment by Lucarda** [comment]
@Spacechild1  yes I can confirm this. The thing is that WASAPI samplerate is not changed by Pd but via "Windows Sound settings" so you have to manually make the match.

![wasapi](https://github.com/pure-data/pure-data/assets/25239522/758c4584-a798-431b-8361-eaee8d6ac467)



I also noted that WASAPI works only on newer sound cards. I have a built-in card from around 2010 and I can select it but I got errors and it does not sound (on Win10 or Win11).

**Comment by umlaeute** [comment]
> so you have to manually make the match.

doesn't Pd (or portaudio) read back the actual samplerate?

**Comment by Spacechild1** [comment]
@Lucarda Thanks for testing!

> The thing is that WASAPI samplerate is not changed by Pd but via "Windows Sound settings" so you have to manually make the match.

Yes, that seems to be the default behavior, but there is also an option to allow automatic resampling (at least in shared mode). See https://github.com/pure-data/pure-data/blob/bbe61ea24a5685543fa5ea154f4a380d8864b5a3/portaudio/portaudio/include/pa_win_wasapi.h#L83-L87

> doesn't Pd (or portaudio) read back the actual samplerate?

I thought so, that's why I am confused... (Side note: shouldn't we print a warning if the desired sample rate is not available?)

Also, note that in step 1 the test tone sounds at the correct pitch, only in step 3 it sounds higher, although the sample rate is the same.

**Comment by Spacechild1** [comment]
I will investigate this, since I am working on a few other WASAPI related things anyway.

**Comment by Spacechild1** [comment]
Pd's portaudio backend definitely checks if the samplerate is supported; if not, it uses the device's default samplerate.

In step 3, `[samplerate~]` correctly outputs 48000 (my current default system samplerate), but everything sounds too high... This rather suggests a bug in portaudio's WASAPI implementation. Will investigate further.

**Comment by Lucarda** [comment]
> I also noted that WASAPI works only on newer sound cards. I have a built-in card from around 2010 and I can select it but I got errors and it does not sound (on Win10 or Win11).

This turned to be wrong. I could get sound of it after changing Windows sound settings.

**Comment by Spacechild1** [comment]
Should be fixed with 00708a0bf67bf6ee0ed52500e593369f434fc8e5. (Keeping it open until merged.)

**Comment by Lucarda** [comment]
@Spacechild1 I just built #2003 with this fix and it works nicely.

I'm testing with Win10 and a built-in soundcard. Changing Pd's sample rate I always get the 440hz tone.

:)
