### ISSUE TITLE
[file] return value from outlet2 when 'read' prior to 'open'

### ISSUE THREAD

**Issue by mariobuoninfante** [pure-data/pure-data#2008]
I thought it might be useful to have a mechanism in place that allows to detect in the patch itself when one is trying to read prior to opening a file.
The scenario I am thinking about is for example when one is trying to dump all the bytes of a file, maybe using a [metro] and a counter, and it could be useful to have an easy way to stop the [metro] if no file has actually been loaded.
Hence why I thought about returning something via outlet2.

**Comment by umlaeute** [comment]
but that seems to be easily solvable on a patch level, no?
you just set a flag when there was an `[open(` message, and clear it when you get a `[close(` message.

```
|
[t   a   a]
|         [route open close]
[file]    [1(    [0(
```

**Comment by mariobuoninfante** [comment]
it is indeed. not sure what I was thinking when I wrote this.
apologies for the noise! :)

**Comment by mariobuoninfante** [comment]
ok, I went and checked the patch I was working on and I see now why I opened this.
I had _fixed_ the issue in a similar way to what you described but, also using the bang from outlet2 when the end of the file is reached, etc..
And actually that led me to think that, for _consistency reasons_ we might want to get a bang when trying to read a file before it's been open, since this is what happens both when something goes wrong (e.g. trying to open a file that doesn't exist) and when the EOF is reached.
Reality is, in retrospective I think this is a bit of a chicken and egg situation, because you can prevent that error to happen entirely (in fact I think I was seeing it before implementing the _fag thing_), but at the same time it is kind on inconsistent (even if it might be that big of a deal).
hope this makes sense.

**Comment by umlaeute** [comment]
i'm not fully opposed to outputting a `bang` if no file was opened.

however:
- you still get the ugly error message on the console...
- as for consistency: other file-reading objects in Pd (like `[readsf~]`) don't output a bang in the read-before-open case either
  (but then, they might not give a `bang` in *any* error-case, only at the EOF; so not much of an argument here)

**Comment by mariobuoninfante** [comment]
Yap, I agree with everything you've said.
About the _ugly error_ on the console, I think that is quite useful though.
But, I see what you mean about other objects behaving slightly differently.
Maybe this raises more of a question about whether or not more consistency across objects is required.
In an ideal world I'd be tempted to say yes, but I also appreciate that it might not be the most pressing thing on the list ;)
