### ISSUE TITLE
Startup dialog sizing wrong on Linux 0.48.0 

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#201]
Reported by Peter P. on the pd-list:

>On my system the ~path~ startup preference dialog features a largely hidden line with a
checkbox that can't be made visible by enlarging the window (see
attached screenshot). Is this the case on someone else's system too?

![](https://lists.puredata.info/pipermail/pd-list/attachments/20170821/7de3f48a/attachment.png)

This is a sizing issue which can be fixed by switching from fixed metrics to autosizing. This was done successfully with the audio & midi dialogs and should be done here.

**Comment by danomatika** [comment]
This should be fixed by 859340a5659d190342144218c9dc7aa5313a7ece

**Comment by umlaeute** [comment]
Pd-0.48-1 has been released.
