### ISSUE TITLE
B15.tabread4~-onset seems to not produce artifacts in single precison (53.2)

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2010]
Not sure what's happening, I was testing the new double precision of upcoming .54 versus single precision and then I noticed I wasn't able to hear the expected artifacts in B15.tabread4~-onset  with single precision. Then I tested with 0.53-2 where I expected to surely listen to them but they're not there either. I didn't go back more but I see I updated this to 0.52 so I believe I was able to hear it back then.

macos 10.14.6

**Comment by umlaeute** [comment]
i have rather the opposite problem:
I can hear the artifacts (in the single-precision build) both with the onset and the naive `[*~]`

no artifacts are audible in the double-precision build

**Comment by umlaeute** [comment]
>  I can hear the artifacts (in the single-precision build) both with the onset and the naive [*~]

but checking again: this only happens with the current `master`.
With Pd-0.53-1 (single), the artifacts are perceptible.

if you don't hear them, check your speakers :headphones:

**Comment by umlaeute** [comment]
the commit that introduced the artifacts in the "GOOD" part (that is: with using an offset) is 3fde7100fcfb8fd0debb4e5f1b4c264e053a6254
