### ISSUE TITLE
tabplay~: bang with multichannel

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#2024]
The help patch of `tabplay~` says:

> Note that the arrays do not need to be of the same length and, in which case the bang output is only sent when reaching the end of the largest table.

However, in the implementation the bang is really sent when the *first* channel runs out.

Personally, I think the behavior as described in the help patch would make more sense. @millerpuckette If you agree, I can push a fix to develop. (I have just pushed a few other bugfixes for table DSP objects.)

**Comment by Spacechild1** [comment]
@millerpuckette Which behavior do you prefer:

1. bang after *first* channel runs out (= current) :-(
2. bang after shortest channel runs out :-|
3. bang after largest channel runs out :-)

If you really want to keep 1., @porres would need to update the documentation. Otherwise I can push a fix to develop.

**Comment by porres** [comment]
I noticed this yesterday but I had tested before writing this, it seems something has changed or I'm just crazy

**Comment by porres** [comment]
weird, I was testing this yesterday and I just can't see a bang at all now... I was about to file an issue

**Comment by millerpuckette** [comment]
I think it would be best to have it play until the _longest_ array is exhausted (which is not what I actually did, nor what I thought I was doing :) - so if Christof would like to contribute a fix I'd be happy to merge it in.

**Comment by Spacechild1** [comment]
Fixed on develop with db777311d808bb3ba728b94ab067f8d333b7d0c2
