### ISSUE TITLE
remove duplicate "Preferences" in Pd menu OSX

### ISSUE THREAD

**Issue by megrimm** [pure-data/pure-data#203]
There are duplicate "Preferences" in the Pd menu on OSX illustrated with attached screenshot:
<img width="502" alt="screen shot 2017-08-21 at 11 39 02 am" src="https://user-images.githubusercontent.com/134831/29527122-da8ae9a4-8665-11e7-8436-cacff9a00edc.png">

Recent discussion started here:
https://lists.puredata.info/pipermail/pd-list/2017-07/119525.html

Although issue is NOT a big deal as logged here:
https://lists.puredata.info/pipermail/pd-list/2017-07/119527.html

I am adding as github issue so we don't forget.

Although maybe with recent update to tcl/tk 8.5 on mac there is easy(ier) fix?
https://lists.puredata.info/pipermail/pd-list/2017-07/119351.html

**Comment by danomatika** [comment]
It's not currently possible to remove it. I've tried.

**Comment by danomatika** [comment]
This has been, more or less, fixed with the introduction of the tabbed preferences in Pd 0.54 and simply renaming Preferences to Settings:

![Screenshot 2023-08-11 at 1 03 55 PM](https://github.com/pure-data/pure-data/assets/480637/15df2027-e8fc-49ea-ae3d-4b64649f1ac5)
