### ISSUE TITLE
error and crash under preferences in 0.54

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2044]
under startup preferences, if I try to add a new library and then hit cancel I get an error and Pd blows up next. I'm on macos 10.14.6

the log error is

```
invalid command name ".gui_preferences.content.frames.f1.listbox.box"
invalid command name ".gui_preferences.content.frames.f1.listbox.box"
    while executing
"$mytoplevel.listbox.box index active"
    (procedure "get_curidx" line 2)
    invoked from within
"get_curidx $mytoplevel"
    (procedure "::scrollbox::add_item" line 7)
    invoked from within
"::scrollbox::add_item .gui_preferences.content.frames.f1 {}"
    invoked from within
".gui_preferences.content.frames.f1.actions.add_path invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 23)
    invoked from within
"tk::ButtonUp .gui_preferences.content.frames.f1.actions.add_path"
    (command bound to event)
```

**Comment by umlaeute** [comment]
> if I try to add a new library and then hit cancel 

as i'm unable to reproduce, please give full step-by-step instructions (including notes about what you see, esp. things like tabbed prefs)

**Comment by umlaeute** [comment]
closing this dues to inactivity.

**Comment by umlaeute** [comment]
reopening as i was now able to reproduce

**Comment by danomatika** [comment]
I noticed this once as well, but I was busy with something and don't remember how I triggered it. It's likely a timing issue where the frame is not existing yet, perhaps on first dialog creation? If so, might need to add an `update` somewhere earlier?
