### ISSUE TITLE
crash on instantiating [adc~ -m]

### ISSUE THREAD

**Issue by bapch** [pure-data/pure-data#2045]
Linux Mint 21.1, kernel 6.1
self-compiled x86_64 Pd version 0.54-0

Having jackd started and Pd set to 8 inputs and 8 outputs, DSP on, if i instantiate [adc~ -m 8 1] Pd will crash in seconds with an error message like 

- `malloc_consolidate(): invalid chunk size`
- `malloc(): corrupted top size`
- `free(): invalid next size (fast)`
- `corrupted size vs. prev_size while consolidating`
- `realloc(): invalid pointer`

Interestingly enough, it will also crash with [adc~ -m 7 2], going beyond the 8 available inputs, with
```
pd: malloc.c:2617: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
```

**Comment by umlaeute** [comment]
confirmed on Debian

**Comment by bapch** [comment]
Tested the develop branch, no more crash. Thanks !
