### ISSUE TITLE
Can't open Jack on Apple silicon

### ISSUE THREAD

**Issue by HaHeho** [pure-data/pure-data#2065]
Installed `jack 1.9.22` and `Pd 0.54.0` via homebrew and received the error "Can't open Jack (it seems not to be installed)" when using the Jack backend. Running on `Apple M1 Pro` with `macOS Ventura 13.4.1 (c)`.

I have not observed this behavior with the same Jack and PD version on older Intel Macs. I'm surprised nobody else has encountered this yet, but I couldn't find any related reports.

**Comment by umlaeute** [comment]
- are you running Pd in rosetta (x86_64 emulation)?
- if not, this might be a search-path problem (Pd looking for jack in `/usr/local/` but  brew/arm64 installing in `/opt/homebrew/`

**Comment by HaHeho** [comment]
> * are you running Pd in rosetta (x86_64 emulation)?

Activity monitor says that PD is running natively.

>     * if not, this might be a search-path problem (Pd looking for jack in `/usr/local/` but  brew/arm64 installing in `/opt/homebrew/`

Yes, that sounds likely to be the problem. How could that be debugged?

**Comment by danomatika** [comment]
The precompiled Pd is built to link to the official jack distribution which installs to `/usr/local` not jack from Homebrew: https://jackaudio.org/downloads/

This is noted in INSTALL.txt but perhaps it's not obviously enough / easy to find: https://github.com/pure-data/pure-data/blob/master/INSTALL.txt#L235

If you want to use Homebrew and an alternate lib search path, you need to compile Pd yourself. Configure should find `/opt/*` by calling pkg-config when using `./configure --enable-jack`.

**Comment by HaHeho** [comment]
> The precompiled Pd is built to link to the official jack distribution which installs to `/usr/local` not jack from Homebrew: https://jackaudio.org/downloads/ (also includes qjackctl.app)

I see. That is why the homebrew install works on Apple with Intel CPUs, since `/usr/local` is also the default location.

> This is noted in INSTALL.txt but perhaps it's not obvious enough / easy to find: https://github.com/pure-data/pure-data/blob/master/INSTALL.txt#L235

No, that is not obvious to a naive user. I would say it is very prone to happen on Apple silicon that one installs Jack and PD both via homebrew and runs into this issue clueless. Therefore, it may be reasonable to directly link to the build-it-yourself instructions on Apple silicon and this Jack error?

> If you want to use Homebrew and an alternate lib search path, you need to compile Pd yourself. Configure should find `/opt/*` by calling pkg-config when using `./configure --enable-jack`.

It is unfortunate that one has to go that mile.

**Comment by danomatika** [comment]
> No, that is not obvious to a naive user. I would say it is very prone to happen on Apple silicon that one installs Jack and PD both via homebrew and runs into this issue clueless.

How is it possible to install pd via Homebrew? I was not aware of this. If this is your standard way of installing, sorry things don't work perfectly, *however* I would say the *vast* majority of macOS users who install Pd do *not* do it via `brew`.

Here is some history and perspective: On 32-bit macOS systems, JACK was *always* installed as a pre-compiled download from the JackOSX project, since maybe 2008 or so. With the transition to 64-bit, the official JACK project started releasing jack 2 for macOS. Both installed to the standard /usr/local location. As long as Pd has been released for macOS with jack support built-in, it has weak-linked to the current Jack distribution, ie. either JackOSX or the download from jack.org was installed on the system when PD was built. This has not changed, only been updated for newer builds as JackOSX went by the wayside.

Yes, it is possible to link against Jack installed via Hombrew instead, however, this means anyone who wants to use Jack *must* install it via Homebrew... for most users, this is IMO too much of "an extra mile" as opposed to "I download Pd from their website" and "I download jack from their website."

Also, as far as my testing has shown, trying to link against both hombrew jack and weak-link to the official jack distribution isn't really possible. See discussion here: https://github.com/pure-data/pure-data/issues/1190

If you *really* want an all home-brew solution, you could propose a brew formula to build Pd from source, however you will need to also build the correct version of Tcl/Tk Wish.app with our custom patches applied. It's not difficult, really, but more than a simple `make && make install`. It's also possible to install pd to the system without being in an app bundle, but this has a host of its own problems so you definitely need the .app bundle.

**Comment by HaHeho** [comment]
> How is it possible to install pd via Homebrew? I was not aware of this. If this is your standard way of installing, sorry things don't work perfectly, _however_ I would say the _vast_ majority of macOS users who install Pd do _not_ do it via `brew`.

It is possible to install as a [cask](https://formulae.brew.sh/cask/pd), which can be invoked by something as simple as `brew install pd`.

I used to install PD via download from the website as well. But since more and more things are available on homebrew, I tend to use that whenever possible.

> Yes, it is possible to link against Jack installed via Hombrew instead, however, this means anyone who wants to use Jack _must_ install it via Homebrew... for most users, this is IMO too much of "an extra mile" as opposed to "I download Pd from their website" and "I download jack from their website."

Of course requiring homebrew is not feasible either.

> Also, as far as my testing has shown, trying to link against both hombrew jack and weak-link to the official jack distribution isn't really possible. See discussion here: #1190

Working with both would be best. I don't know much about linking, and I believe you when you say that it seems not possible, unfortunately.

> If you _really_ want an all homebrew solution, you could propose a brew formula to build Pd from source, however you will need to also build the correct version of Tcl/Tk Wish.app with our custom patches applied. It's not difficult, really, but more than a simple `make && make install`. It's also possible to install pd to the system without being in an app bundle, but this has a host of its own problems so you definitely need the .app bundle.

Maybe someone could look into this in the future. There is already the homebrew cask formula. Although, AFAICT, this simply unpacks the downloaded app from the homepage. But implementing the full build process should be possible. But currently probably not relevant to so many users.

**Comment by danomatika** [comment]
I’d suggest opening an issue on the cask formula about adding info that the pre compiled app requires jack from the jack website.

I’m looking at this again, the problem was that we can build pd to use jack from homebrew however this build will not run if jack isn’t installed. I don’t believe the homebrew jack can use weak linking while the official download does. Wearing linking to the official download let’s us distribute pd which runs without jack.

**Comment by sebshader** [comment]
I tried to compile pd with (weak linking) Jackmp.framework using a github actions CI script (modified from https://github.com/pure-data/pure-data-ci/blob/main/iem-ci/puredata.yml) and it couldn't find the framework. Afaict jack2 doesn't include Jackmp.framework

**Comment by danomatika** [comment]
You are right. That framework was included with the 32-bit JackOSX and the frame working linking is disabled the building for newer macOS versions: https://github.com/pure-data/pure-data-ci/blob/main/iem-ci/puredata.yml#L62C26-L62C50

Something that could be explored is to modify the pd core binary LD_PATH to include both `/usr/local` and `/opt/local` but IMO this is a bad idea.

**Comment by sebshader** [comment]
judging by https://github.com/DISTRHO/PawPaw/blob/main/pack-jack2.sh the official package installs them in the same location (```/usr/local```)?
seems like some environment variable for the linker path should be set for homebrew w/ different prefixes..

**Comment by umlaeute** [comment]
maybe.
also note, that we are building the fat Pd in a *single* go (and i don't know whether we can apply different linker paths in this case; probably we could use `otool` or something to modify the arch-specific parts of the binary afterwards)

**Comment by HaHeho** [comment]
It's 2026, and I ran into the same issue again ... only to find my own report on it from years earlier. 🙄 
(last tested with the Homebrew versions of  `jack 1.9.22` and ` pd 0.56-3`)

I want to recall possible solutions to implement something to improve resolution in the future.

1. Propose a new brew formula to build Pd from source, as explained in https://github.com/pure-data/pure-data/issues/2065#issuecomment-1674684438.

2. Modify the existing [brew cask formula](https://github.com/Homebrew/homebrew-cask/blob/26eec672e7ecb95df8c9aef6eb1312b618b8ee4c/Casks/p/pd.rb) with a "caveats" section (shown on `brew info` or after `brew install`) to point at the incompatibility with Homebrew JACK and possible resolution steps.

Are there other convenient solutions missing?

I can implement the second one, as the first is beyond my Homebrew capabilities and the complexity of the building process. I would propose and ask for feedback on the exact wording later. The recommended resolution steps are to build Pd locally from source, as laid out in https://github.com/pure-data/pure-data/issues/1190#issuecomment-790190424. Are there easier alternatives?

**Comment by umlaeute** [comment]
I think the problem is an issue with homebrew, and should be solved there. that is: yes, submit a patch to homebrew to update their Pd formula to use their ecosystem.

the Pd.app binaries we are distributing are really targeting non-homebrew systems. (it's of course nice of it works with both; but the property is clearly the "download app" user)

**Comment by HaHeho** [comment]
> I think the problem is an issue with homebrew, and should be solved there. that is: yes, submit a patch to homebrew to update their Pd formula to use their ecosystem.
> 
> the Pd.app binaries we are distributing are really targeting non-homebrew systems. (it's of course nice of it works with both; but the property is clearly the "download app" user)

Sounds reasonable. To clarify, the issue does not arise on macOS with Intel processors, but only on Apple Silicon (which is 100% of devices sold now, AFAIK). Is that correct?

The issue is that Jack from homebrew installs to `/opt/homebrew/` on `arm64`, whereas on' x64' it installs to `/usr/local/`. Other available Jack binaries (https://jackaudio.org/downloads/ and https://github.com/jackaudio/jack2-releases/releases) always install into `/usr/local/`. Lastly, all distributed Pd binaries ([homebrew](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/p/pd.rb) and https://puredata.info/downloads/pure-data) expect libraries to also be in `/usr/local/`. Is that also correct?

**Comment by umlaeute** [comment]
> Is that also correct?

sounds reasonable, but i don't really know.

Pd doesn't "expect" libraries to be anywhere, but afaict due to the way the linker works on macOS the paths get hardcoded.

basically, when building Pd what happens is:
- we tell the linker that it has to link against "libjack" (`-ljack`).
- the linker tries to find a `libjack.dylib` file somewhere in the linker-paths
- it eventually finds `/usr/local/lib/libjack.dylib`
- it generates a binary that has a (weak) dependency on `/usr/local/lib/libjack.dylib`

afaik, it's not possible to create a binary that looks for `libjack.dylib` in both `/usr/local/lib/` and `/opt/homebrew/lib/`.
 it's probably a security thingie, to prevent injection of malicious libraries

**Comment by danomatika** [comment]
It's possible to change the linker search path in the compiled binary using install_name_tool, however this is not for the general user. You could try that, however, as IOhannes has said, we can't really make a solution that works for both and IMO we have focused on non-homebrew Jack for now. The other, more nuclear option is to *include* libjack in the Pd app bundle but I do not think that is a good idea or that the Jack project even encourages it.

**Comment by HaHeho** [comment]
> It's possible to change the linker search path in the compiled binary using install_name_tool, however this is not for the general user.

This option for providing instructions on how to resolve the issue with using Pd and Jack binaries from Homebrew on `arm64` seems interesting. Instructions that involve applying a few commands to modify the Pd binaries appear much simpler than building Pd locally from scratch.
**Comment on the local build process on `arm64`:** I found that following https://github.com/pure-data/pure-data/issues/1190#issuecomment-790190424 was straightforward. However, I encountered difficulties with the inclusion of the older default Tcl/Tk version. Creating a fully functional app bundle (i.e., no errors when displaying the settings menu) with the latest version required some frustrating additional steps.

Could we source the instructions for using `install_name_tool` to modify the Homebrew Pd binaries with Homebrew Jack, that are easy to apply, resilient, and portable?

**Comment by danomatika** [comment]
We can take a PR, no problem. 😁 I would add this to the platform-specific info in either INSTALL.txt or in the mac/README.txt

Also: The Tcl/Tk versions are quite different depending upon which macOS versions your are targeting and the default precompiled Wish.app included in the repo is often out of date. Unfortunately, it usually involves building Wish by default and using it to build the app bundle. Not ideal but we put a lot of work into making the scripts helpful.

Note: As mentioned in mac/README.txt, running pd installed to the system with a default Tcl/Tk installed doesn't really work. I have not tried it with homebrew libs, maybe it has improved, but it has never really been supported. I assume you are building an app bundle or at least the homebrew formula is...

**Comment by umlaeute** [comment]
> I assume you are building an app bundle or at least the homebrew formula is...

afaict, the [homebrew formular](https://github.com/Homebrew/homebrew-cask/blob/0eafe97869385475c5a92584932e474eeff8e251/Casks/p/pd.rb#L1) just downloads the release binary, and doesn't compile at all.

**Comment by danomatika** [comment]
> [homebrew formular](https://github.com/Homebrew/homebrew-cask/blob/0eafe97869385475c5a92584932e474eeff8e251/Casks/p/pd.rb#L1)

Ok, at least there is that. I see they forget to remove the pd core settings plist. Oh well.

**Comment by danomatika** [comment]
Nevermind. On my macOS 15 system, changing the lib path on the downloaded app bundle invalidates the notarization. Trying to open the app gets the Gatekeeper warning dialog with the only options of Cancel and Move to Trash. Forcing an adhoc signature doesn't work either, nor does clearing the quarantine flags.

Building the app yourself bypasses this issue for your own system, at least.

Another option: if nothing is installed to /usr/local, why not make symlinks to the jack libs from homebrew? I don't think they would want to add that to the formula, but should work on an individual basis.

~~~
# change path
install_name_tool -change /usr/local/lib/libjack.0.1.0.dylib /opt/homebrew/lib/libjack.0.1.0.dylib  ~/Desktop/Pd-0.56-3.app/Contents/Resources/bin/pd
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/danomatika/Desktop/Pd-0.56-3.app/Contents/Resources/bin/pd (for architecture x86_64)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/danomatika/Desktop/Pd-0.56-3.app/Contents/Resources/bin/pd (for architecture arm64)

# verify
otool -L ~/Desktop/Pd-0.56-3.app/Contents/Resources/bin/pd
/Users/danomatika/Desktop/Pd-0.56-3.app/Contents/Resources/bin/pd (architecture x86_64):
	/opt/homebrew/lib/libjack.0.1.0.dylib (compatibility version 0.1.0, current version 1.9.22, weak)
	... *snip*
/Users/danomatika/Desktop/Pd-0.56-3.app/Contents/Resources/bin/pd (architecture arm64):
	/opt/homebrew/lib/libjack.0.1.0.dylib (compatibility version 0.1.0, current version 1.9.22, weak)
	... *snip*

# attempt to re-sign adhoc
codesign -s - --force --deep ~/Desktop/Pd-0.56-3.app

# attempt to clear any flags
xattr -c  ~/Desktop/Pd-0.56-3.app
~~~

**Comment by HaHeho** [comment]
> Nevermind. On my macOS 15 system, changing the lib path on the downloaded app bundle invalidates the notarization. Trying to open the app gets the Gatekeeper warning dialog with the only options of Cancel and Move to Trash. Forcing an adhoc signature doesn't work either, nor does clearing the quarantine flags.

Thank you for investigating all this. I didn't think of the code signing, so I'm glad you noticed the issue before I sunk any time into trying it myself.

> Another option: if nothing is installed to /usr/local, why not make symlinks to the jack libs from homebrew? I don't think they would want to add that to the formula, but should work on an individual basis.

I thought it might work, but wasn't sure whether this should be done or recommended. I agree that adding direct modifications to the current brew formula carries the risk of breaking existing setups. Therefore, I suggested adding a "caveats" section, which is shown as for the following example of the Jack formula (the way the this exact caveat content is populated is actually different than it could be done for the Pd cask):
```
❯ brew info jack
==> jack ✔: stable 1.9.22 (bottled)
Audio Connection Kit
https://jackaudio.org/
Installed (on request)
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/j/jack.rb
License: GPL-2.0-or-later
==> Installed Kegs and Versions
jack ✔ 1.9.22_1 (48 files, 3.7MB) [Linked]
==> Dependencies
Required (3): berkeley-db@5 ✔, libsamplerate ✔, aften ✔
Recursive Runtime (3): all installed ✔
Dependents: 3
==> Caveats
To start jack now and restart at login:
  brew services start jack
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/jack/bin/jackd -X coremidi -d coreaudio
==> Analytics
install: 408 (30 days), 1,539 (90 days), 6,882 (365 days)
install-on-request: 63 (30 days), 201 (90 days), 1,021 (365 days)
build-error: 0 (30 days)
```
I believe all caveats are also repeated at the end of a complex install routine with extensive outputs. Therefore, hints on Pd's compatibility with Jack should be quite visible there. We can populate that section with any brief instructions or pointers to further documentation we see fit.

**Comment by umlaeute** [comment]
> changing the lib path on the downloaded app bundle invalidates the notarization

sure. 
but on homebrew systems, all the devtools are available, so you could just ad-hoc sign the binaries after fiddling with them, couldn't you?

**Comment by danomatika** [comment]
🤷 I did adhoc resigning and it didn't work. This is likely a antimalware protection step as anything could essentially redirect to bad lib.

**Comment by HaHeho** [comment]
> Another option: if nothing is installed to /usr/local, why not make symlinks to the jack libs from homebrew? I don't think they would want to add that to the formula, but should work on an individual basis.

Starting from the latest Jack installation from Homebrew, with the following libraries:
```
❯ ls -la /opt/homebrew/Cellar/jack/1.9.22_1/lib
total 3600
drwxr-xr-x@ 13 helmholz  admin      416 May 21  2024 .
drwxr-xr-x@ 14 helmholz  admin      448 Oct  3  2024 ..
drwxr-xr-x@ 13 helmholz  admin      416 May 21  2024 jack
lrwxr-xr-x@  1 helmholz  admin       15 Feb  2  2023 libjack.0.1.0.dylib -> libjack.0.dylib
-rw-r--r--@  1 helmholz  admin   533808 May 21  2024 libjack.0.dylib
lrwxr-xr-x@  1 helmholz  admin       15 Feb  2  2023 libjack.dylib -> libjack.0.dylib
lrwxr-xr-x@  1 helmholz  admin       18 Feb  2  2023 libjacknet.0.1.0.dylib -> libjacknet.0.dylib
-r--r--r--@  1 helmholz  admin   203360 May 21  2024 libjacknet.0.dylib
lrwxr-xr-x@  1 helmholz  admin       18 Feb  2  2023 libjacknet.dylib -> libjacknet.0.dylib
lrwxr-xr-x@  1 helmholz  admin       21 Feb  2  2023 libjackserver.0.1.0.dylib -> libjackserver.0.dylib
-rw-r--r--@  1 helmholz  admin  1101760 May 21  2024 libjackserver.0.dylib
lrwxr-xr-x@  1 helmholz  admin       21 Feb  2  2023 libjackserver.dylib -> libjackserver.0.dylib
drwxr-xr-x@  3 helmholz  admin       96 May 21  2024 pkgconfig
```

To keep everything path and version agnostic, I managed to grab all versions of `libjack` with
`sudo ln -s "$(realpath $HOMEBREW_PREFIX/lib/jack)"/../libjack.*dylib /usr/local/lib/`
with the following result (Pd doesn't recognize the libraries if the symlinks are placed in `jack` directory):
```
❯ ls -la /usr/local/lib
total 0
drwxr-xr-x@ 5 root  wheel   160B Jun 14 17:35 jack
lrwxr-xr-x  1 root  wheel    66B Jun 14 18:10 libjack.0.1.0.dylib -> /opt/homebrew/Cellar/jack/1.9.22_1/lib/jack/../libjack.0.1.0.dylib
lrwxr-xr-x  1 root  wheel    62B Jun 14 18:10 libjack.0.dylib -> /opt/homebrew/Cellar/jack/1.9.22_1/lib/jack/../libjack.0.dylib
lrwxr-xr-x  1 root  wheel    60B Jun 14 18:10 libjack.dylib -> /opt/homebrew/Cellar/jack/1.9.22_1/lib/jack/../libjack.dylib
```

This seems to start Pd with Jack just fine. Is there any reason `libjacknet` and `libjackserver` should also be linked? Are there any other hints or comments regarding this method?

**Comment by danomatika** [comment]
I think only the various libjack dylibs would be linked by Pd and there is usually only 1 single dylib with the rest being version symlinks. I don't think libjacknet or libjackserver would be needed unless libjack links to them. You can check the output of `otool -L` on libjack to see.

As for the location, looking at the official jack macOS installer with Pacifist.app, it seems that it places the main libs in `lib` with what looks like internal libs in `lib/jack`, so putting the symlinks to `/usr/local/lib` would be fine.

<img width="407" height="365" alt="Image" src="https://github.com/user-attachments/assets/c8943acd-044e-4c85-8c39-589862d46069" />

**Comment by danomatika** [comment]
Thinking about this again, setting the symlinks could probably go in the formula as an optional flag ala "--link-jack" etc.

* install: check if the official jack is installed, if not make the symlinks. Could probably just check if the root `/usr/local/lib/libjack` dylib is a real file or a symlink.
* remove: check if the official jack is installed, if not then remove symlinks.

For systems without an existing `/usr/local` directory, I wonder if sudo is required. Probably.

Note this in the formula documentation / `brew info` output.

**Comment by umlaeute** [comment]
> 🤷 I did adhoc resigning and it didn't work. This is likely a antimalware protection step as anything could essentially redirect to bad lib.

i'm baffled why this shouldn't work. isn't the entire point of adhoc signing to allow such things?

unfortunately, my test VM (Sonoma, provided by [tart](https://tart.run/)) is very dev-centric, which means that the gatekeeper is somewhat more forgiving... at least i can run the binaries *just fine* when fuddling with the  `install_name_tool` - even without code-signing :-/



anyhow, i *think* we might be able to use the `rpath` to allow lookup in both directories...
something like:
~~~sh
install_name_tool -change /usr/local/lib/libjack.0.1.0.dylib @rpath/libjack.0.1.0.dylib -add_rpath /usr/local/lib -add_rpath /opt/homebrew/lib pd
~~~

which (if i got it right) will prioritize  `/usr/local/lib/libjack.0.1.0.dylib` over `/opt/homebrew/lib/libjack.0.1.0.dylib`.

it does seem to work, with both brew-installed and "official" jack.

**EDIT** the good thing about this solution is, that we we could apply it before doing the actual *official* codesigning (so no need for ad-hoc magic). it seems that miller is currently getting 0.56-4 out, i guess I have to wait for the release before i can apply these changes to the CI)

**Comment by umlaeute** [comment]
i've pushed a potential fix as eca0ab23fb73394e482cbe74dcf5f0b143edc797 (don't know why github decided to not autolink the commit).

you could try the signed/notarized app from [here](https://git.iem.at/pd/pure-data/-/jobs/101376/artifacts/raw/Pd-0.56-4-3-geca0ab23.dmg) to see whether it now works.
it would be great if people could test both homebrew jack and the official jack installer for macOS.

**Comment by HaHeho** [comment]
> i've pushed a potential fix as [eca0ab2](https://github.com/pure-data/pure-data/commit/eca0ab23fb73394e482cbe74dcf5f0b143edc797) (don't know why github decided to not autolink the commit).
> 
> you could try the signed/notarized app from [here](https://git.iem.at/pd/pure-data/-/jobs/101376/artifacts/raw/Pd-0.56-4-3-geca0ab23.dmg) to see whether it now works. it would be great if people could test both homebrew jack and the official jack installer for macOS.

Uhhh, wonderful. On my system, your build found the Jack libraries from Homebrew (without the previously suggested fix in https://github.com/pure-data/pure-data/issues/2065#issuecomment-4702343588).

Unfortunately, I couldn't test the official jack installer, since the OS blocks execution, which I reported in https://github.com/jackaudio/jack2/issues/1019. Hence, that way may be not be easily available at the moment, which makes this fix in Pd even more valuable.

**Comment by HaHeho** [comment]
> Unfortunately, I couldn't test the official jack installer, since the OS blocks execution, which I reported in [jackaudio/jack2#1019](https://github.com/jackaudio/jack2/issues/1019). Hence, that way may be not be easily available at the moment, which makes this fix in Pd even more valuable.

Tested now with the official Jack installer and I can confirm that it also worked with your Pd build.

I see that you added the improvements to the development branch. I assume it will take some time until this is available on Homebrew with the next release, considering `Pd 0.56-4` was just released?

**Comment by umlaeute** [comment]
> I assume it will take some time until this is available on Homebrew with the next release.

yes, most likely.

given miller's first commit after the release (upgrade of port audio), I don't think there will be another bugfixe release (0.56-5), but the next release will be 0.57-0, which might take a while (no idea though)

**Comment by danomatika** [comment]
Ok, that should be a harmless fix. The only issue I cna see is if someone is confused as to why Jack now works form homebrew, but that's not a bad thing, right.

**Comment by umlaeute** [comment]
@danomatika i might be mistaken, but the only user-story i can come up with that would trigger your concerns is:
- the user has homebrew's jack installed
- the user cannot build Pd themselves
- the user selects that "jack" backend but does not want to be able to use it

that sounds a bit unlikely. am I missing something?

**Comment by danomatika** [comment]
Yeah, that's the only thing I can foresee and as you say, it's not really an issue.
