### ISSUE TITLE
Lost MIDI in 0.54.0-1

### ISSUE THREAD

**Issue by jazzbassoon** [pure-data/pure-data#2066]
After upgrading to 0.54.0-1, I am no longer able to see any MIDI devices in the MIDI settings window. I have tried with two different audio interfaces as well as a separate usb midi cable. The MIDI device shows up in Cadence, but there's nothing to select in pd.

Arch Linux kernel 6.4.6.arch1-1
PD 0.54.0-1 installed from arch repos, jack2 1.9.22-1

**Comment by umlaeute** [comment]
which MIDI backend were you using?
can you post a screenshot of your old (working) configuration/preferences?

- personally, I haven't seen any OSS MIDI device in the last decade (but others, like miller, seem to use them successfully)
- with ALSA MIDI, there never was any MIDI device selection dialog (you have to do the connections in an external application, like qjackctl, qpwgraph, aconnect, aconnectgui,...)

**Comment by jazzbassoon** [comment]
Well that got me in a direction that got it to work. Here's what I think is happening.

In the version before the upgrade, pd defaulted to using the alsa backend. I use jack, so I would go and change to jack backend and everything worked great. MIDI devices would show up in the MIDI settings window.

After the upgrade, pd stopped defaulting to alsa, and defaulted to jack. For some reason, it doesn't find my MIDI devices this way. But I changed to the alsa backend, and then back to jack and it found them again. 

I was looking in catia, and didn't see any midi ports in pd to connect my midi device to in another way, but I at least have a workaround. Definitely don't know the details of why though!

**Comment by umlaeute** [comment]
glad it's working somehow.

I cannot follow your explanation though:
the audio and MIDI backends are completely separate.
on linux, there are 4 audio backends (OSS, ALSA, portaudio, JACK) and 2 MIDI backends (OSS, ALSA).
if you say that Pd now "defaulted to jack" (which i'm very sure it does not (unless the arch maintainers changed something on their side, which you should then bring to them), but that's beside the point), then this is about the *audio* backend and unrelated to the *MIDI* backend.
and if you use the ALSA MIDI backend then there *never* are any devices in the properties.

it might help if you posted screenshots.

**Comment by jazzbassoon** [comment]
Oh right, I guess that was all audio backend. I'm not sure what MIDI backend I'm using. I can't find anything about it in pd, so I'm guessing that's at the OS level? I know in the jack config in cadence, I have no MIDI driver selected.

What screenshots would be most helpful? I feel like the MIDI settings window with nothing in it isn't very helpful.

**Comment by umlaeute** [comment]
> What screenshots would be most helpful? I feel like the MIDI settings window with nothing in it isn't very helpful.

actually, it is.

**Comment by jazzbassoon** [comment]
Well, I'm not really sure what happened, but it seems to be working like normal again. Thanks for helping!
