### ISSUE TITLE
Erroneous text in value help > dealing with $0

### ISSUE THREAD

**Issue by esluyter** [pure-data/pure-data#2074]
In the middle of the help page, there is this text: "This kitchen was specially designed to make it easy for a disabled person to use. This kitchen was specially designed to make it easy for a disabled person to use. "

https://github.com/pure-data/pure-data/blob/c0a7c16c63e86ccc8ce05c8273ccd8aec7ae044c/doc/5.reference/value-help.pd#L49

**Comment by porres** [comment]
that's been fixed already in my documentation branch, see https://github.com/pure-data/pure-data/pull/2042 and https://github.com/pure-data/pure-data/pull/2042/commits/f3a825a87bb9bd5620573b212715691b4105f5ad and you can open doc related issues in https://github.com/pure-data/pddp/issues, 

cheers
