### ISSUE TITLE
pd~ subpatch doesn't open, pd hangs with watchdog

### ISSUE THREAD

**Issue by grybouilli** [pure-data/pure-data#2076]
# minimal example
Done with pd 0.54.0 (also tried with 0.53.1)
Create the two following patches in the same folder; run `pdtest.pd` and trigger the message in it. The sub patch terminal opens but hangs and starts watchdog. So the patch of `pureA.pd` never opens.

pureA.pd:
![image](https://github.com/pure-data/pure-data/assets/38727647/eacdb8b1-f635-4e6f-9cb1-11e0dabb57f2)

pdtest.pd:
![image](https://github.com/pure-data/pure-data/assets/38727647/87b8c772-3c28-4504-9fba-69ce0aed7fc2)

# some more info

when running the same example in wrappers such as plugdata, the following appears in the console:
```
pd~: can't stat /pdsched.so
pd~ startup failed
```

**Comment by grybouilli** [comment]
Update: issue is not present in Pd-0.51.4

**Comment by umlaeute** [comment]
quoting from the help-patch for `pd~`:

> ATTENTION: DSP must be running in this process for the sub-process to run. This is because its clock is slaved to audio I/O it gets from us!

turning the DSP on (in the host application) before sending the `pd~ start` message should fix the issue.
of course, it would be better if you would get better error messages (and no hangs), if the DSP happens to be off.

as for Plug Data not being able to run `[pd~]`: that is an issue with Plug Data itself (aka: raise it at https://github.com/plugdata-team/plugdata/issues)

**Comment by grybouilli** [comment]
> quoting from the help-patch for `pd~`:
> 
> > ATTENTION: DSP must be running in this process for the sub-process to run. This is because its clock is slaved to audio I/O it gets from us!
> 
> turning the DSP on (in the host application) before sending the `pd~ start` message should fix the issue. of course, it would be better if you would get better error messages (and no hangs), if the DSP happens to be off.

I can confimr it solved the issue in pd vanilla.

> as for Plug Data not being able to run `[pd~]`: that is an issue with Plug Data itself (aka: raise it at https://github.com/plugdata-team/plugdata/issues)

it seems to be a more general issue in pd instances as I get the same error in pd instanced in ossia-score. Any lead on that? Is [pd~] not supposed to work in pd instance?

**Comment by umlaeute** [comment]
It's only an issue that `[pd~]` depends on an external implementing a scheduler (and a usable `pd`), and for whatever reasons some variants of Pd fail to provide that.
In the case of Plug Data it's foremost a path issue (most likely it fails to detect its own path which is used to calculate the path to pdsched, iirc).

In any case, it is totally unrelated to the issue at hand, so if you want to discuss it, let's use a different thread/issue/...
