### ISSUE TITLE
[file cwd] not finding "home" directory

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2080]
tested with pd 0.54-0, macOS 10.14.6, macbookr air 2013

![Screen Shot 2023-08-27 at 13 54 21](https://github.com/pure-data/pure-data/assets/5360142/fab43011-b316-4a21-8851-b6d12d31448b)

**Comment by porres** [comment]
It seems I added this to the help file with 6cf041fcd

but since [file glob] can expand this and we have it in the code, see

https://github.com/pure-data/pure-data/blob/master/src/x_file.c#L134

can we make it a request to allow it to expand in other [file] methods like 'cwd' and maybe some others that could be also relevant?

**Comment by umlaeute** [comment]
makes sense
