### ISSUE TITLE
"Start Here" instructions don't work when using headphones on MacOS

### ISSUE THREAD

**Issue by blakej11** [pure-data/pure-data#2082]
I'm a new user of Pd; I just downloaded version 0.54.0 this evening, and I'm working through the tutorial. I spent 45 minutes getting it to play a simple patch through my headphones. I'm using MacOS Big Sur (11.7.7), and Bose QC35 II wireless headphones. I looked at the guidance in the [docs](http://msp.ucsd.edu/Pd_documentation/x3.htm#s1.0), but that didn't seem to have anything actionable for me.

My patch is extremely basic:

<img width="185" alt="Screen Shot 2023-08-28 at 8 19 53 PM" src="https://github.com/pure-data/pure-data/assets/49706341/7b7a438b-8279-4a1b-8a75-e0c5e5d001f5">

I also did this with a patch that has a `*~ 0.2` object in the middle, as suggested in the [Start Here](https://puredata.info/docs/StartHere/) doc, and it didn't make a difference.

I've enabled audio/DSP:

<img width="412" alt="Screen Shot 2023-08-28 at 8 20 42 PM" src="https://github.com/pure-data/pure-data/assets/49706341/b98d61e6-665b-45e2-b416-718b8f37c8f9">

The audio settings are set up to use my headphones:

<img width="377" alt="Screen Shot 2023-08-28 at 8 21 19 PM" src="https://github.com/pure-data/pure-data/assets/49706341/8361e256-0201-491b-ae8a-f1c6485f33e5">

and I had my headphones connected to the laptop before starting Pd.

When I open the "Test Audio and MIDI..." window, and set the Test Gain to something other than "off", it *does* play sound through my headphones:

<img width="129" alt="Screen Shot 2023-08-28 at 8 22 21 PM" src="https://github.com/pure-data/pure-data/assets/49706341/575c9c1c-b9cc-4c63-a30d-11cb9e79ec73">

So Pd clearly knows how to generate audio in my headphones - it just doesn't do so for my own patch.

Eventually, after fiddling with the controls in the "Test Audio and MIDI..." window, I noticed that it seemed to be generating output on channel 2. So I tried saying `dac~ 2`, rather that just `dac~`, in the output object in my patch, and it worked.

So I guess this bug report is a request to have the "Start Here" documentation have an initial example that works well for users with headphones, or at least to describe this issue. If nothing else, maybe the bug report itself can help future users who encounter this issue.

**Comment by blakej11** [comment]
Another detail that I just figured out: this only happens when it's using the headphones' microphone as an input device, as that seems to turn the output into mono. If I disable the input device, then `dac~` works as expected.

**Comment by Spacechild1** [comment]
> I also did this with a patch that has a *~ 0.2 object in the middle, as suggested in the [Start Here](https://puredata.info/docs/StartHere/) doc, and it didn't make a difference.

The example in the guide actually connects the signal to *both* inlets of `[dac~]`, so you will hear it on both channels. In this case, you would have heard the sound (albeit only on the right channel). 

>  this only happens when it's using the headphones' microphone as an input device, as that seems to turn the output into mono

Now here's the explanation for your problem. For some reason, it only plays through the right channel when also used as a microphone. There's not really much we can do about it... In fact, all examples in the manual and in the help patches play sound to *both* channels.

**Comment by blakej11** [comment]
Thanks, that's a very reasonable explanation!
