### ISSUE TITLE
[bng] -> [until] hangs

### ISSUE THREAD

**Issue by blakej11** [pure-data/pure-data#2084]
When I click the bang button on this program, Pd hangs:

![Screen Shot 2023-09-01 at 8 01 48 PM](https://github.com/pure-data/pure-data/assets/49706341/f838b091-0f4c-4127-b59d-873fc354c55c)

I distilled the issue down to this patch while trying to implement [this one](https://forum.pdpatchrepo.info/topic/13134/things-i-wish-i-had-known-when-i-started-pd/3), to try to understand it.

The Activity Monitor shows that Pd has gone into a spin loop. It doesn't actually print anything to the text console. If I remove the [print], it also spins, but it's easier to interrupt; with the [print], once I click the bang I can't get it back into edit mode or do anything else.

This is with Pd 0.54.0 on MacOS 11.7.7.

**Comment by porres** [comment]
this is intentional and explained in the help file, you can close this issue

**Comment by blakej11** [comment]
So it is.
