### ISSUE TITLE
bad window path name ".x10d31a8f0.c" OSX 0.48

### ISSUE THREAD

**Issue by megrimm** [pure-data/pure-data#209]
To reproduce error:

If I open a help patch for an abstraction. Click the abstraction to open it. Edit abstraction. NOT save the edited abstraction and close window. Then close help patch I am asked "Do want to save changes you made in "foo.pd"?. Choosing "No" gives me the following error:

~~~
bad window path name ".x10d31a8f0.c"
bad window path name ".x10d31a8f0.c"
    while executing
"winfo toplevel $tkcanvas"
    (procedure "::pdtk_canvas::pdtk_canvas_getscroll" line 2)
    invoked from within
"::pdtk_canvas::pdtk_canvas_getscroll .x10d31a8f0.c"
    ("after" script)
~~~

**Comment by danomatika** [comment]
Fixed. Should be in the next bug fix release.

Basically, it tries to calculate the scroll position and defers if the window is not fully created. It looks like this was happening as it was trying to re-do the scrollbars on a window that was closed.
