### ISSUE TITLE
[keyname] malfunctioning

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2096]
It seems that when you have multiple rows of keys pressed, the object cannot receive key presses from other keys in the same row.

Let's take as an example a "qwerty" keyboard, regular english. Steps to reproduce it

- Press 'z' key, keep it pressed, then press 'x' key and release it many times, you can see that \[keyname\] receives the 'x' key press by checking the bang button.
- Now press 'z' and 'q' and keep them pressed. If you press 'x' now, you can see that \[keyname\] does not receives the 'x' key press.

See attached example to try and reproduce this. I'm on a macbook air, macOS 10.14.6, with Pd 0.54-0

[test.pd.zip](https://github.com/pure-data/pure-data/files/12798645/test.pd.zip)

by the way, I have a similar object called [keycode] that has the same issue, inging @sebshader , author of [keycode]

**Comment by sebshader** [comment]
Have you made sure it doesn't have to do with the keyboard hardware or os?

**Comment by porres** [comment]
tried now on another computer, a macbook pro, with another built in hardware keyboard and on a different OS (monterey instead of mojave), same deal.

**Comment by sebshader** [comment]
here on windows with a lenovo it doesn't happen.

**Comment by porres** [comment]
just tried with plugdata (no tcl/tk) and I get the same thing

**Comment by porres** [comment]
hmmm, pressing "q" and "w" also doesn't let "x" through

**Comment by sebshader** [comment]
that seems to indicate that it's most likely the keyboard hardware. (same behavior could occur on multiple keyboard models)

**Comment by sebshader** [comment]
https://en.wikipedia.org/wiki/Key_rollover#:~:text=A%20keyboard%20with%20n%2Dkey,of%20keys%20are%20pressed%20simultaneously.

**Comment by sebshader** [comment]
https://en.wikipedia.org/wiki/Key_rollover

**Comment by porres** [comment]
tried with an external USB keyboard, same issue

**Comment by sebshader** [comment]
multiple keyboard models can have the same issue. But whatever the cause, if the window manager/OS is not giving the keys pd can't get them either. And that seems to be the case because it occurs in every app, not just pd.

**Comment by porres** [comment]
yeah, I see that if I try some text editor the same issue applies, so, ok, it's not software related... I wonder if it's an OS thing?

**Comment by sebshader** [comment]
maybe, but most likely the keyboard hardware

**Comment by porres** [comment]
and I also have the same issue if I try to control VCV rack via keyboard...

**Comment by porres** [comment]
Maybe we could we document this issue, huh?

**Comment by sebshader** [comment]
maybe, imo seems to be kind of out of the scope of pd documentation and more to do with the documentation/advertising of the keyboard
