### ISSUE TITLE
More settings in array property dialog

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#2103]
In Pd 0.52 graphical arrays received new methods for changing the graph width, color, style and also a method for enabling/disabling mouse interaction. Currently, only "style" is exposed in the array property dialog. It would be nice to also have the remaining settings. In particular, it's much easier to set the color in the GUI than with a message. Also, many people are probably not aware that these settings exist in first place.

Of course, the new GUI settings should also be saved with the object, just like IEM GUIs.

**Comment by porres** [comment]
I think i proposed this somewhere here already

**Comment by Spacechild1** [comment]
Ah, you're right! Closing as duplicate of https://github.com/pure-data/pure-data/issues/1838
