### ISSUE TITLE
macOS build endianness warning with MACHINE_ENDIAN_H defined

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#2123]
With Pd 0.54 on macOS 13, I still see the following warning when building both libpd and Pd itself on macOS:

~~~
./m_private_utils.h:104:4: warning: unable to detect endianness (continuing anyhow) [-W#warnings]
#  warning unable to detect endianness (continuing anyhow)
   ^
1 warning generated.
~~~

`MACHINE_ENDIAN_H` is defined, so I would think at least `BYTE_ORDER` would be defined...

**Comment by umlaeute** [comment]
nah, that's a somewhat weirder issue.

if `_XOPEN_SOURCE` is defined, then the `<machine/endian.h>`-include does not properly set the `BYTE_ORDER`.
we must set `_XOPEN_SOURCE` in a few cases (afaik, the only case is currently `x_file.c` where it is needed for recursive file deletion), in which case the `m_private_utils.h` will spit out a warning.

you would get an *error* if `BYTE_ORDER` was not defined and `_XOPEN_SOURCE` wasn't defined either.

you will notice, that you only get that warning for the compilation of a single file (`x_file.c`).

- i don't really want to get rid of the warning, as it indicates a *potential* problem (if for some reason we need both `BYTE_ORDER` and `_XOPEN_SOURCE` in a single compilation unit)
- we could selectively disable a given part of `m_private_utils.h`, e.g. by defining `PD_DISABLECHECK_BYTE_ORDER` before including that file besides the `_XOPEN_SOURCE` define.
we probably might disable the entire

**Comment by danomatika** [comment]
...or we could define `_DARWIN_C_SOURCE` so the defines are properly set by `<machine/endian.h>` but you seem to be against anything like `#ifdef __APPLE__`... :)

**Comment by danomatika** [comment]
Here is the important part out of `arm/endian.h` on my system which is included by `machine/endian.h`:
```C
/*
 * Definitions for byte order, according to byte significance from low
 * address to high.
 */
#define __DARWIN_LITTLE_ENDIAN  1234    /* LSB first: i386, vax */
#define __DARWIN_BIG_ENDIAN     4321    /* MSB first: 68000, ibm, net */
#define __DARWIN_PDP_ENDIAN     3412    /* LSB first in word, MSW first in long */

#define __DARWIN_BYTE_ORDER     __DARWIN_LITTLE_ENDIAN

#if     defined(KERNEL) || (!defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE))

#define LITTLE_ENDIAN   __DARWIN_LITTLE_ENDIAN
#define BIG_ENDIAN      __DARWIN_BIG_ENDIAN
#define PDP_ENDIAN      __DARWIN_PDP_ENDIAN

#define BYTE_ORDER      __DARWIN_BYTE_ORDER

#include <sys/_endian.h>

#endif /* defined(KERNEL) || (!defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)) */
```

**Comment by danomatika** [comment]
> ...or we could define `_DARWIN_C_SOURCE` so the defines are properly set by `<machine/endian.h>` but you seem to be against anything like `#ifdef __APPLE__`... :)

This was probably unfair. IN any case, I think the following could work as I believe `machine/endian.h` is used by macOS only:
```C
#ifdef HAVE_MACHINE_ENDIAN_H
#define _DARWIN_C_SOURCE
# include <machine/endian.h>
#elif defined HAVE_ENDIAN_H
# include <endian.h>
#endif
```

**Comment by danomatika** [comment]
Also, should we check if `BIG_ENDIAN` is defined as well as `LITTLE_ENDIAN`?

**Comment by danomatika** [comment]
Closing for now. The fix is to define `_DARWIN_C_SOURCE` which helps in finding machine/endian.h.
