### ISSUE TITLE
Windows installer fails if usbipd service is running

### ISSUE THREAD

**Issue by IrregularShed** [pure-data/pure-data#2128]
I've recently got a new computer, so I've been installing software and drivers for a few days. One of these packages is [USBIPD](https://github.com/dorssel/usbipd-win) which is used for accessing USB devices on a Windows machine from within the Windows Subsystem for Linux. (WSL2 doesn't do this automatically, unlike WSL1, so there has to be a daemon running in between on Windows.)

When I tried to install pd I received an error: `Refusing to continue. Save your work and quit any running Pd app before doing an (un)installation.` Obviously, I didn't have any existing application running at this point, so after scratching my head I checked Task Manager to see if there was anything matching 'pd' and found only the usbipd service. Killing that service allowed me to install as expected.

I'm guessing it's down to this line being greedy and matching anything running that contains `pd.exe` or `pd.com`:
https://github.com/pure-data/pure-data/blob/0259d00373b9e6f3bc1d76eebc5b243283ca7063/msw/pd.nsi#L188

... as provided by the function just after:

https://github.com/pure-data/pure-data/blob/0259d00373b9e6f3bc1d76eebc5b243283ca7063/msw/pd.nsi#L204-L209

If I could fix it, I'd give it a go - however, it's been 15 years since I last worked with NSIS and I can barely remember any of it (sorry!)

**Comment by Lucarda** [comment]
Hi @IrregularShed,

Thanks for the report. There were also some reports of not being able to run the installer under WINE. I'm to blame for the changes. The reason of having this is that if Pd is running and the installer overwrites files they will be black-listed by some anti-virus software.

Here @umlaeute suggested in the [pd-list](https://lists.puredata.info/pipermail/pd-list/2023-11/132690.html) that we have an option to force installation.

I'll put this on my to-do-list

**Comment by Lucarda** [comment]
@IrregularShed 

I made a PR to fix this issue. Let's keep (this issue) open so it auto-closes on merge.

You can get an artifact from [here](https://nc.nubegris.com.ar/index.php/s/zHXPrf8YyiHswdg).
If you can please test it. You don't have to actually install anything. You should get to the "Run the uninstaller (recommended)" part without getting any warning.

**Comment by IrregularShed** [comment]
I'll give it a try tomorrow!

**Comment by umlaeute** [comment]
thanks.

for what it is worth, i can now install on Wine, but...

if Pd is already running in Wine, this is now **not** detected at all (so i don't get the dialog, even if Pd *is* running)

```
$ ps aux | grep Pd
umlaeute  155559  0.2  0.3 1984608 55268 pts/3   Sl   10:30   0:00 C:\Program Files\Pd\bin\wish86.exe C:\PROG~FBU\Pd\tcl\pd-gui.tcl
umlaeute  155567  2.1  0.1 1821488 26076 pts/3   S    10:30   0:03 C:\Program Files\Pd\bin\pd.com -guiport 39101
```

**Comment by IrregularShed** [comment]
This worked perfectly for me.  `usbipd.exe` was ignored, while it caught the running Pd process.

Thanks!

**Comment by Lucarda** [comment]
> but if this doesn't give any results, why would the original code have triggered the warning?

@umlaeute on my tests on wine the problem was the `find` pipe. if you do (as current `master`):

`tasklist | find /I "pd.com"`

it will return some error like `find: invalid flag /I`. The test expects an empty return but here it returns something so the detection was a false-positive. 

> in any case, as mentioned on the Pd-list, running the installer in WINE is probably too much of an edge-case to properly care.

true.

**Comment by umlaeute** [comment]
`tasklist` just doesn't show anything, but it seems that this is a Wine problem.
maybe a problem with *my* Wine installation.
please disregard my observations for now :-)
