### ISSUE TITLE
keyup & keyname return immediately on macOS 0.48.0+

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#213]
[keyup] & [keyname] return immediately on a key press when using 0.48.0 on macOS. This seems like an underlying issue with the Tk 8.5+ Cocoa backend and key events are sent from the GUI to the pd core.

The relevant parts in `pd_bindings.tcl` are:

* [Key bindings](https://github.com/pure-data/pure-data/blob/master/tcl/pd_bindings.tcl#L135)
* [sendkey proc](https://github.com/pure-data/pure-data/blob/master/tcl/pd_bindings.tcl#L327)

Here's a minimal test to try with wish:

~~~
package require Tk

bind . <KeyPress>   {puts "press   %K"}
bind . <KeyRelease> {puts "release %K"}
~~~

Bug behavior:

1. press key
2. two events generated: \<KeyPress\> & \<KeyRelease\> 
3. release key

Expected Tk behavior:

1. press key
2. one event generated: \<KeyPress\> 
3. release key
4. one event generated:\<KeyRelease\> 

Tested on macOS 10.12.6:

* 8.4 on system: expected behavior
* 8.5.9 on system: alternate behavior with 3 events on press: \<KeyPress\>, \<KeyRelease\>, then  \<KeyPress\> (known to be buggy in general)
* 8.5.19: bug behavior
* 8.6: not tested
* 8.7 Github master branch: bug behavior

EDIT: Tk bug report opened: <https://core.tcl.tk/tk/tktview/1ba71a86bb6ab29180418ba4a25b0074e3c9de7a>
EDIT2: Bug fix now in TK: ["Merge mac-keyrelease-branch to fix 1ba71a86bb"](https://github.com/tcltk/tk/commit/797282fc2929c8427bd830748d7b08ea022c1177)

**Comment by danomatika** [comment]
After fiddling for a while, this seems to be a bug in Tk. <Key> and <KeyPress> bindings work as expected, but <KeyRelease> is triggered immediately and *not* on an actual key up. This is true whether system key repeat is enabled or not.

**Comment by danomatika** [comment]
I've opened a bug report at the Tk project: https://core.tcl.tk/tk/tktview/1ba71a86bb6ab29180418ba4a25b0074e3c9de7a

**Comment by danomatika** [comment]
Pinging @millerpuckette so you're aware of this.

**Comment by millerpuckette** [comment]
Doesn't happen on my MACOS  10.6 machine - presumably it only happens on newer MACOS versions.
Idea: should Pd have a feature to just filter out all auto-repeats?

**Comment by danomatika** [comment]
>presumably it only happens on newer MACOS versions.

Yes, when using TK 8.5 which uses the Cocoa backend.

**Comment by danomatika** [comment]
>Idea: should Pd have a feature to just filter out all auto-repeats?

It can't if it never gets an actual release event which is the main problem. This is a bug in Tk....

**Comment by pierreguillot** [comment]
Is it the reason why when I use a shortcut to create an object then two are created?

**Comment by danomatika** [comment]
>Is it the reason why when I use a shortcut to create an object then two are created?

Are you using Pd built from source and TK 8.5.9 which comes with macOS? Tk 8.5.9 is pretty buggy and using a newer version solves this issue. This is mentioned in the mac readme file included with the Pd sources.

**Comment by pierreguillot** [comment]
No, I use 8.6.6.

**Comment by danomatika** [comment]
>No, I use 8.6.6.

On which macOS version? I'm not seeing this with 10.12 and Pd 0.48.0 with Tk 8.4, Tk 8.5.19 (Miller's build), and Tk 8.7a0 built from git.

**Comment by pierreguillot** [comment]
I'm on maxOS 10.12.6 with Pd 0.48.8 (eef2afa) and Tk 8.6.6 build with the script osx-app.sh (this is also the version displayed in the Pd console). And the same thing happens with Miller's build.

**Comment by danomatika** [comment]
Very strange. I have the same macOS version and it's fine for me.

Can you send me your build somehow? Also, I assume your'e not running it from the command line.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by pierreguillot** [comment]
[Pd-0.48.0.zip](https://github.com/pure-data/pure-data/files/1410482/Pd-0.48.0.zip)
No, I'm not using it from the command line.

**Comment by danomatika** [comment]
>Pd-0.48.0.zip

I'm seeing any duplicates with object creation via keybindings on my system with the zipped app.

**Comment by danomatika** [comment]
Maybe it's a locale issue. Can you try with a US English keyboard setting?

**Comment by pierreguillot** [comment]
Hey I didn't think about it :) I'll do that today and I keep you informed. Thank!

**Comment by pierreguillot** [comment]
You're right, I don't have any problem with the US keyboard.

**Comment by danomatika** [comment]
I've created a new issue for the key binding problem. Let's keep this thread for [keyup].

**Comment by pkstone** [comment]
I see this problem with a US keyboard.

**Comment by danomatika** [comment]
Which problem? There are two within the discussion at this point? keyup or key bindings?

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by pkstone** [comment]
keyup. Sorry, I thought it was clear from the context.


On Dec 5, 2017, at 12:53 AM, Dan Wilcox <notifications@github.com<mailto:notifications@github.com>> wrote:

Which problem? There are two within the discussion at this point? keyup or key bindings?

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com<http://danomatika.com>
robotcowboy.com<http://robotcowboy.com>

**Comment by nuromantix** [comment]
Has there been any progress on this? Really need to use KEYUP!
thanks

**Comment by nuromantix** [comment]
I don't know anything about Tk so please forgive me if it's a stupid
question: can I work around this problem by using an older version of
something? Or would I need to completely install an old version of
OSX?

**Comment by danomatika** [comment]
Short answer: yes

Tk is the Tcl GUI library that the Pd GUI uses. The problem appeared on macOS with newer versions of Tk 8.5+ which has transitioned to the more modern macOS framework called Cocoa. Tk version 8.4 and earlier used the older, and now deprecated, Carbon framework which is 32 bit only and thus will most probably be removed in the macOS 10.14 which comes out this fall.

Which version of macOS are you using? If it is 10.12 or earlier, then it's possible for the Pd GUI to use the Tk 8.4 included with the system. If you are using 10.13, Tk 8.4 was removed so you would need a build of the Pd macOS .app that includes it within the app. It depends on your particular situation and I could probably make you a test build.

The *real* solution, of course, is to fix what's wrong in Tk...

**Comment by nuromantix** [comment]
Thanks for the info.
I am on 10.13. I guess I will just use one of my older Macs for PD stuff
until they come out with a fix.
Ed

**Comment by codebykevin** [comment]
Upstream Tk bug closed, thanks for the report.

**Comment by nuromantix** [comment]
does that mean it's been fixed?
thanks
ed

**Comment by danomatika** [comment]
@nuromantix Possibly. It means the issue has been fixed in Tk, but we still need to build and test with Pd.

@codebykevin Is this something that may be back ported to Tk 8.5 or will it be in TK 8.7+? Thanks!

**Comment by danomatika** [comment]
@codebykevin I tested with the current Tcl/Tk github master branches (0.9.0a) and the fix works.

**Comment by nuromantix** [comment]
So I just need to update OSX and I should be good to go? Or do I need to
get a new build of PD as well?

**Comment by codebykevin** [comment]
Bug has been fixed in branches 8-6-core and trunk (8.7) of Tk. Will not be back ported to 8.5. Updating the OS is not necessary, but updating Tk is.

**Comment by danomatika** [comment]
Thanks @codebykevin. I can test again with 8.6 when y'all sync the 8.6 branches on the GitHub mirror.

**Comment by danomatika** [comment]
@nuromantix  Try this build: 
http://docs.danomatika.com/pdbuilds/Pd-0.48-2-tk8519-keyfix.zip

This includes the key fix manually back ported int TK 8.5.19 by @millerpuckette.

**Comment by nuromantix** [comment]
Thanks

**Comment by pkstone** [comment]
[keyup] doesn’t fire if you hold the key down for longer than a moment (the repeat delay interval?). Is anyone else seeing this?


Phil Stone
UC Davis

**Comment by danomatika** [comment]
>[keyup] doesn’t fire if you hold the key down for longer than a moment (the repeat delay interval?). Is anyone else seeing this?

With what build of Pd are you seeing this?

**Comment by pkstone** [comment]
http://docs.danomatika.com/pdbuilds/Pd-0.48-2-tk8519-keyfix.zip <http://docs.danomatika.com/pdbuilds/Pd-0.48-2-tk8519-keyfix.zip>

**Comment by danomatika** [comment]
@pkstone I'm looking into it now. The key release works but the repeat seems to be inconsistent.

**Comment by danomatika** [comment]
The main issue is that press & hold on a alphanumeric key will activate the [Character Accent Selector](https://support.apple.com/kb/PH25643?locale=en_US) (that text popup in other programs) and ignore key repeat. Tk or Pd don't show this, so it seems like the key release is swallowed as the system is waiting for further input until another key is pressed. Press and Hold on the spacebar, for example, does a simple key repeat.

I think there is a way to disable this via an app's info.plist.

**Comment by danomatika** [comment]
Ok, try this build: 
http://docs.danomatika.com/pdbuilds/Pd-0.49-0test0-keyfix2.zip

The GUI now disables the character composition so key repeat works as before. I compared with the output of Pd-extended. Also, I slightly updated our tk patch to reset the releaseCode var after sending the release event. I think this was swallowing the first key release.

**Comment by pkstone** [comment]
That worked. The keyup is firing after a prolonged press now. Thanks, Dan.

But there may be another issue. Key repeat is happening irrespective of the system setting (i.e. it can’t be turned off).

**Comment by pkstone** [comment]
The ideal behavior would be to control repeat (and repeat rate) from within Pd, but that’s enhancement, not bug-fix.

**Comment by danomatika** [comment]
>But there may be another issue. Key repeat is happening irrespective of the system setting (i.e. it can’t be turned off).

Pd-extended is doing this as well, so it's something outside of Pd. Probably Tk.

**Comment by pkstone** [comment]
Well, the broken [keyup] was the critical thing — thanks for nailing that one.

**Comment by danomatika** [comment]
>The ideal behavior would be to control repeat (and repeat rate) from within Pd, but that’s enhancement, not bug-fix.

There is always [change] for now...

**Comment by pkstone** [comment]
That doesn’t work in a ‘polyphonic’ way. The only real way to work around it is to have a state table for each key; then you know whether or not you’re getting a repeat.

**Comment by danomatika** [comment]
@codebykevin If it's useful, here's the patch for the key release changes we're applying to 8.5.19: https://github.com/pure-data/pure-data/blob/master/mac/patches/tk8.5.19_keyfix.patch. This plus disabling the char composition popup using `defaults` gives us key repeat as in Tk 8.4:

    defaults write org.puredata.pd.pd-gui ApplePressAndHoldEnabled -bool false

**Comment by danomatika** [comment]
@pkstone I don't think there is a way in TK to tell if a key is a repeat. That's lowered level and is translated into separate down / up pairs.

**Comment by danomatika** [comment]
As the fixes have been merged, I'll close the issue. *hooray*

**Comment by pkstone** [comment]
I used to just turn repeats off (with the OS) to avoid this problem, but now that has no effect (in other words, that behavior changed at some point, probably in TK).

I’m going to implement a workaround with a table of state variables for each key, which will allow me to detect and ignore key repeats.

Thanks again for your work on this, Dan.

**Comment by danomatika** [comment]
Well, we could simply ignore repeats in our custom TK patch, but I'm *very* hesitant to start introducing things which change Tk's behavior beyond bugfixes. Unfortunately, this is one of those many details of moving to the TK Cocoa backend that doesn't seem to have translated 1:1 as it did with Carbon before.

**Comment by pkstone** [comment]
If repeat-enable were *switchable*, say with an argument/inlet to [key], that would be ideal. But I agree with you about not altering the expected behavior by eliminating repeat completely.

**Comment by danomatika** [comment]
>If repeat-enable were *switchable*, say with an argument/inlet to [key], that would be ideal.

It can't be. The unsavory possibility I mention is compiled in, not a run time option.

**Comment by pkstone** [comment]
Of course. I realized that after I hit ‘send’. Sorry for the noise!

**Comment by pkstone** [comment]
Dan,

There seems to be a problem with simultaneous key presses, in that when two or more keys are pressed at the same time, and then released, only one keyup is fired, for the last key pressed. Sorry I didn’t spot this sooner.


Phil

**Comment by danomatika** [comment]
I see what you're saying, but that's something at the system level. As far as Pd is concerned, things are working as before. I'm testing using this smal patch and comparing both 0.49-0 and Pd-extended:

<img width="447" alt="screen shot 2018-09-19 at 8 46 56 am" src="https://user-images.githubusercontent.com/480637/45735563-93b94700-bbe8-11e8-8083-b9b52515b9b5.png">

As far as I can tell, the behavior is the same between both Pd versions/forks and I'm getting matching key release events *most* of the time. Weird stuff seems to happen when, for example, you press A, W, & D and then try pressing S with your thumb. The S events are not fired. Not in Pd, Pd-extended, or TextEdit for that matter, so this is something outside of Pd & Tk and, more likely, a limitation of my computer's keyboard matrix. I suggest finding the pattern that doesn't seem to work for you and testing it outside of Pd as well.

**Comment by pkstone** [comment]
My experience with this is that [key]/[keyup] used to work wonderfully and polyphonically (i.e., you could “chord” with the ascii keyboard) before [keyup] stopped working. I mean, I used to perform with it that way, so I know I’m not imagining it. It worked well long after I had transitioned from pd-extended to Pd vanilla/deken. Then, more recently, [keyup] stopped working altogether (because of a Tk bug, I gather). In this version, it’s useless as a music keyboard because there’s not a keyup for every key.

I’m not doubting what you say at all — I certainly can’t argue with the logic of the similar behavior with pd-extended. It’s just a shame that a very musical tool will no longer work, and I’m extremely puzzled as to how it ever did.

Thanks, Dan.


Phil



On Sep 18, 2018, at 11:50 PM, Dan Wilcox <notifications@github.com<mailto:notifications@github.com>> wrote:


I see what you're saying, but that's something at the system level. As far as Pd is concerned, things are working as before. I'm testing using this smal patch and comparing both 0.49-0 and Pd-extended:

[screen shot 2018-09-19 at 8 46 56 am]<https://user-images.githubusercontent.com/480637/45735563-93b94700-bbe8-11e8-8083-b9b52515b9b5.png>

As far as I can tell, the behavior is the same between both Pd versions/forks and I'm getting matching key release events most of the time. Weird stuff seems to happen when, for example, you press A, W, & D and then try pressing S with your thumb. The S events are not fired. Not in Pd, Pd-extended, or TextEdit for that matter, so this is something outside of Pd & Tk and, more likely, a limitation of my computer's keyboard matrix. I suggest finding the pattern that doesn't seem to work for you and testing it outside of Pd as well.

**Comment by danomatika** [comment]
*sigh* Well that means we need a lookup table now to keep track of multiple releases. I can probably add that but I really can't spend much more time on Pd right now.

> On Sep 19, 2018, at 5:04 PM, pkstone <notifications@github.com> wrote:
> 
> My experience with this is that [key]/[keyup] used to work wonderfully and polyphonically (i.e., you could “chord” with the ascii keyboard) before [keyup] stopped working. I mean, I used to perform with it that way, so I know I’m not imagining it. It worked well long after I had transitioned from pd-extended to Pd vanilla/deken. Then, more recently, [keyup] stopped working altogether (because of a Tk bug, I gather). In this version, it’s useless as a music keyboard because there’s not a keyup for every key. 

--------
Dan Wilcox
@danomatika <http://twitter.com/danomatika>
danomatika.com <http://danomatika.com/>
robotcowboy.com <http://robotcowboy.com/>

**Comment by pkstone** [comment]
I hear you. Thanks for everything you’ve done, Dan.

By the way, are you still at ZKM? I’ll be there in late November for the GigaHertz award. I’ll buy you a beer or six if you’re around then.


Phil



On Sep 19, 2018, at 8:07 AM, Dan Wilcox <notifications@github.com<mailto:notifications@github.com>> wrote:

*sigh* Well that means we need a lookup table now to keep track of multiple releases. I can probably add that but I really can't spend much more time on Pd right now.

> On Sep 19, 2018, at 5:04 PM, pkstone <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> My experience with this is that [key]/[keyup] used to work wonderfully and polyphonically (i.e., you could “chord” with the ascii keyboard) before [keyup] stopped working. I mean, I used to perform with it that way, so I know I’m not imagining it. It worked well long after I had transitioned from pd-extended to Pd vanilla/deken. Then, more recently, [keyup] stopped working altogether (because of a Tk bug, I gather). In this version, it’s useless as a music keyboard because there’s not a keyup for every key.

--------
Dan Wilcox
@danomatika <http://twitter.com/danomatika>
danomatika.com<http://danomatika.com> <http://danomatika.com/>
robotcowboy.com<http://robotcowboy.com> <http://robotcowboy.com/>

**Comment by danomatika** [comment]
I will be here, it's our (Hertz-Lab) event!

> On Sep 19, 2018, at 5:09 PM, pkstone <notifications@github.com> wrote:
> 
> By the way, are you still at ZKM? I’ll be there in late November for the GigaHertz award. I’ll buy you a beer or six if you’re around then. 

--------
Dan Wilcox
@danomatika <http://twitter.com/danomatika>
danomatika.com <http://danomatika.com/>
robotcowboy.com <http://robotcowboy.com/>

**Comment by pkstone** [comment]
Excellent. I’ll be there as a member of The Hub. See you then!


On Sep 19, 2018, at 8:11 AM, Dan Wilcox <notifications@github.com<mailto:notifications@github.com>> wrote:

I will be here, it's our (Hertz-Lab) event!

> On Sep 19, 2018, at 5:09 PM, pkstone <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> By the way, are you still at ZKM? I’ll be there in late November for the GigaHertz award. I’ll buy you a beer or six if you’re around then.

--------
Dan Wilcox
@danomatika <http://twitter.com/danomatika>
danomatika.com<http://danomatika.com> <http://danomatika.com/>
robotcowboy.com<http://robotcowboy.com> <http://robotcowboy.com/>

**Comment by umlaeute** [comment]
@danomatika @pkstone it seems your private conversation somehow shows up on github...

**Comment by pkstone** [comment]
Sorry. My fault.

On Sep 19, 2018, at 8:52 AM, umläute <notifications@github.com<mailto:notifications@github.com>> wrote:


@danomatika<https://github.com/danomatika> @pkstone<https://github.com/pkstone> it seems your private conversation somehow shows up on github...

**Comment by umlaeute** [comment]
i'm going to delete those comments (if you are both ok with that)

**Comment by pkstone** [comment]
Sure.

On Sep 19, 2018, at 8:54 AM, umläute <notifications@github.com<mailto:notifications@github.com>> wrote:


i'm going to delete those comments (if you are both ok with that)

**Comment by Spacechild1** [comment]
Windows 7: AWD + S -> the S isn't triggered - but it's like that in all programs. same for E, Q, Y, X and C so this is rather a keyboard matrix issue as you mentioned.

keyup seem to work fine on 0.48.1 but on 0.49 the keyup message already fires *before* the keydown (and also on auto key repeats) while actually lifting the key does nothing.

**Comment by Spacechild1** [comment]
OTOH, the left outlet of [keyname] seems to work fine on both Pd versions.

**Comment by pkstone** [comment]
Sorry, I should clarify, this is the behavior with Dan’s patch.

In the non-patched version of Pd, the same test produces three(!) zeroes. Go figure.


On Sep 19, 2018, at 10:24 AM, pkstone <pkstone@ucdavis.edu<mailto:pkstone@ucdavis.edu>> wrote:

I just tried [keyname] (OS X): push two keys simultaneously — two 1s come out. Release both keys, only one zero comes out.


On Sep 19, 2018, at 10:21 AM, Spacechild1 <notifications@github.com<mailto:notifications@github.com>> wrote:


OTOH, the left outlet of [keyname] seems to work fine on both Pd versions.

**Comment by umlaeute** [comment]
same here, <kbd>a</kbd> <kbd>w</kbd> <kbd>w</kbd> report their keypressed, while  <kbd>s</kbd> stays silent.
`[keyup]` fires after `[key]`, as it should be (both wit h0.49 and 0.48-2)

**Comment by pkstone** [comment]
That works great! I beat on it pretty severely with many keys pressed at once, and there were corresponding [keyup]s to every [key]. I can tell when there aren’t matching [keyup]s, as I get hanging notes if there is. There were none with this build.


On Sep 19, 2018, at 3:20 PM, Dan Wilcox <notifications@github.com<mailto:notifications@github.com>> wrote:


Try this build:
http://docs.danomatika.com/pdbuilds/Pd-0.49-0test3-keyfix3.zip

**Comment by danomatika** [comment]
More questions for Linux & Windows:

1. If you press multiple keys at the same time and release them at the same time, do you get matching press and release events. (Not always in the same order.)
2. Does Pd honor the system's key repeat setting or does it always show repeats or swallow all repeats?

**Comment by Spacechild1** [comment]
well, as I said, with the current master on Windows [keyup] is totally messed up as it fires on *pressing* a key and *before* the [key] object.

**Comment by danomatika** [comment]
Using which version of Tk? We haven't changed any of the key event handling in Pd directly, only Tk for mac.

**Comment by danomatika** [comment]
*sigh* All I want is for this to work the same on all platforms. I thought it was only broken on mac...

**Comment by Spacechild1** [comment]
32-bit Pd with Tk8.5. The system key repeat settings are honored btw.

**Comment by Spacechild1** [comment]
something must have changed between 0.48.1 and 0.49 in Pd as both use the same Tk version.

**Comment by Spacechild1** [comment]
just want to point out again that [keyname] behaves as expected...

**Comment by pkstone** [comment]
Not on OS X.

On Sep 19, 2018, at 4:05 PM, Spacechild1 <notifications@github.com<mailto:notifications@github.com>> wrote:


just want to point out again that [keyname] behaves as expected...

**Comment by Spacechild1** [comment]
Dan, please ignore my last posts, now that I test again it works fine. I think I messed something up. I take this as a sign that I need more sleep... sorry for the noise!

**Comment by danomatika** [comment]
Ok, I should have a fix for this finalized tomorrow. I've added key repeat honoring from system preferences but somehow broke the key repeat release events.

**Comment by joshuahudelson** [comment]
Just want to add a quick THANK YOU to everyone working on this issue.  I'm teaching a university class in Beirut on making music with PD, and a few of my students are having this problem with [keyup].  It's lovely to see such a responsive and responsible community in action!

**Comment by Ant1r** [comment]
On Linux (0.49-test3):

>     If you press multiple keys at the same time and release them at the same time,
>     do you get matching press and release events. (Not always in the same order.)

yes 

>     Does Pd honor the system's key repeat setting 
>     or does it always show repeats or swallow all repeats?

yes, it does honor the system setting.

BUT: it clearly depends on the keyboard, and on the keys used.

e.g on my PS/2 HP azerty keyboard, I can type <kbd>a</kbd><kbd>z</kbd><kbd>e</kbd><kbd>r</kbd><kbd>Space</kbd> and getting reliable key/keyup events;
but if I type <kbd>r</kbd><kbd>t</kbd><kbd>y</kbd> then so-called "key-jamming" gives me random response (I guess it depends on the actual timing of the key presses), sometimes key/keyup just keep silent, sometimes one of the keys is reported, sometimes 2 of them.

By contrast on my logitech wireless USB keyboard, most of 6-keys combinations are correctly reported, but some combinations fail anyway.



See https://en.wikipedia.org/wiki/Rollover_(key)

**Comment by danomatika** [comment]
Good to know. Then it seems Linux works as expected. The per-keyboard differences are down to hardware and not OS or Pd.

**Comment by danomatika** [comment]
Update: I have this 90% working, except for key repeats not sending UP events yet. I may not be able to finish it until Sunday or Monday.

**Comment by danomatika** [comment]
I decided to just finish it now. Here's a new build: 
http://docs.danomatika.com/pdbuilds/Pd-0.49-0test3-keyfix4.zip

Release events should work, key repeat should work, multiple press/release should work, and the key repeat system setting is now followed (aka no repeat in Pd if the repeat is off).

**Comment by millerpuckette** [comment]
Cool (and wow, you're up late)...

I imagine you had to debug TK8.5 some more - I'll go ahead and test this on
my machine, but would like to have your new Tcl/Tk tree for the release :)

thanks so much for following through with this.

M

**Comment by danomatika** [comment]
Reopening for now until the *newest* fix is confirmed. The updated patch is in the `update/0.49` branch: 0ee284ecfb5215c51b64c263ae7fdeb2ddbd521f

>Cool (and wow, you're up late)...

That's about the only time you can get anything like this done with a small child around. :)

**Comment by pkstone** [comment]
Dan,

Your latest revision seems to work perfectly on OS X. [key]s are all matched by corresponding [keyup]s, even when chording on the keyboard. Key repeat setting from OS is honored (including repeat rate), and repeated keys all have corresponding [keyup]s.

Nice work!


Phil


On Sep 22, 2018, at 7:09 AM, Dan Wilcox <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopening for now until the newest fix is confirmed. The updated patch is in the update/0.49 branch: 0ee284e<https://github.com/pure-data/pure-data/commit/0ee284ecfb5215c51b64c263ae7fdeb2ddbd521f>

Cool (and wow, you're up late)...

That's about the only time you can get anything like this done with a small child around. :)

**Comment by danomatika** [comment]
The latest fix has been merged, so I'll close this for now.

**Comment by codebykevin** [comment]
Does this patch require adjusting some system setting to work? I recall you mentioning this earlier in the thread.

**Comment by danomatika** [comment]
No. I tested both with our app which disables the accent selector (via ApplePressAndHoldEnabled defaults key) to re-enable key repeat for all alpha keys as well as with a tiny tcl script via my generated Wish.app. It think it should work in both cases.

An easy test is to use the space bar to trigger the key repeat as it doesn't trigger the selector when it's enabled.

**Comment by codebykevin** [comment]
Ok.  I will review soon.  Thank you.

**Comment by codebykevin** [comment]
This patch diverges from a recent commit I made on Tk 8.6 and trunk, and doesn't apply cleanly.

**Comment by danomatika** [comment]
It was made to the 8.5.19 tree, so I suppose that's not a surprise.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by danomatika** [comment]
@codebykevin TO slightly resurrect this issue, a newer patch for this issue with Tk 8.6.10 is here: https://github.com/pure-data/pure-data/blob/master/mac/patches/tk8.6.10_keyfix.patch

If this isn't sufficient, I could open a PR to the tk repo.

**Comment by danomatika** [comment]
Actually @codebykevin, scratch that for now. The patch includes key repeat detection based on the system setting, but it may not nbe something for Tk in general. We are figuring out now if we need it for our project as well and I'll wait and submit a PR later on when we decide. Sorry for the noise.

**Comment by sebshader** [comment]
I'm getting this bug again with tk 8.6.11

**Comment by danomatika** [comment]
We apply custom patches to fix this when building Tk Wish.app used to create the Pd.app:

https://github.com/pure-data/pure-data/tree/master/mac/patches

If you are building 8.6.11, they are not applied and the problem reemerges. You can try copying the the 8.6.10 patches and renaming them to 8.6.11 to see if they apply cleanly when building with the `tcltk-wish.sh` script.

**Comment by sebshader** [comment]
@danomatika it looks like tk completely revamped its key handling (well anyways to the point where I couldn't easily find analogous sections from perusing it in the file that was patched)

**Comment by sebshader** [comment]
@danomatika or rather I should say there was an analogous section in a new function but it looked different enough that I didn't think the same patch file would work

**Comment by sebshader** [comment]
turns out the bug was just that the system preferences weren't being respected. Submitted a pr

**Comment by pkstone** [comment]
Thanks, Seb!


Phil

From: Seb Shader ***@***.***>
Date: Friday, April 30, 2021 at 4:30 PM
To: pure-data/pure-data ***@***.***>
Cc: Philip Stone ***@***.***>, Mention ***@***.***>
Subject: Re: [pure-data/pure-data] keyup & keyname return immediately on macOS 0.48.0+ (#213)

turns out the bug was just that the system preferences weren't being respected. Submitted a pr
