### ISSUE TITLE
A "DSP off/on" cycle interrupts audio with non-JACK backends

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#2152]
There are some inconsistencies between audio back-ends and how they behave when Pd  receives a dsp-off, dsp-on cycle:

```
[0, 1 (
|
[dsp $1 (
|
[s pd]
```
I was always assuming that the `dsp` message to `s pd` actually was only turning DSP on and off. However, with the non-JACK back-ends, such a cycle interrupts audio. It seems that such message turn the audio back-end off and on. I think this is undesired and I hope it is unnecessary. 

This happens on:
  - Linux / ALSA
  - macOS / CoreAudio
  -  Windows / MMIO

A DSP cycle does _not_ interrupt Audio on:
  - Linux / JACK
  - macOS / JACK

Ideally, all back-ends behave the same.

Ideally, all back-ends behave like JACK.

Why a DSP cycle?

I turn DSP off during operations that would normally trigger multiple DSP graph calculations. Since Pd doesn't update the DSP graph while DSP is turned off, I save a few cycles (with large patches a significant amount). Pd only does the calculation once when I turn DSP on again. With a large enough buffer, I often even doesn't get any interrupt at all. It appears this trick works only nicely with JACK.

**Comment by Spacechild1** [comment]
> It seems that such message turn the audio back-end off and on. I think this is undesired and I hope it is unnecessary.

Generally, this is very much desired. If you don't do DSP, there is no point in keeping the audio device running.

Jack is the only exception. Pd intentionally keeps the audio device open to maintain the Jack connections.

> Since Pd doesn't update the DSP graph while DSP is turned off, I save a few cycles (with large patches a significant amount). 

This is a very valid optimization. In fact, Pd objects/externals may use the API functions `canvas_suspend_dsp`/`canvas_resume_dsp` to temporarily suspend/resume DSP. In this case, the audio device is *not* stopped!

So what we actually need is another message that mimicks the behavior of `canvas_suspend_dsp`/`canvas_resume_dsp`. Something like `[;pd dsp-suspend 1(` / `[;pd dsp-suspend 0(`.

**Comment by reduzent** [comment]
> > It seems that such message turn the audio back-end off and on. I think this is undesired and I hope it is unnecessary.
> 
> Generally, this is very much desired. If you don't do DSP, there is no point in keeping the audio device running. Keep in mind that some audio APIs take exclusive access over the device, in this case we definitely want to close it!

I don't think this desired. I want DSP to turn off and on, not the audio device. The method is even called 'dsp'. When audio is disconnected and connected, it should be done with a different method. That it is an implicit side effect of the 'dsp' method is bad design, imho. 


> Jack is really the exception: Pd intentionally keeps the audio device open to maintain the Jack connections.

Isn't that more proof it is a bad design choice? Ideally, a method works the same regardless of current backend.


> > Since Pd doesn't update the DSP graph while DSP is turned off, I save a few cycles (with large patches a significant amount).
> 
> This is a very valid optimization. In fact, Pd has API functions (`canvas_suspend_dsp`/`canvas_resume_dsp`) to temporarily suspend/resume DSP. In this case, the audio device is _not_ stopped!
> 
> So what we actually need is another message that corresponds to `canvas_suspend_dsp`/`canvas_resume_dsp`. Something like `[;pd suspend-dsp 1(` / `[;pd suspend-dsp 0(`.

I very welcome such a method.

**Comment by reduzent** [comment]
Also, things seems to have changed, at least according to my memory. If I'm not mistaken, other backends used to behave like JACK, or at least ALSA did.

**Comment by Spacechild1** [comment]
> I don't think this desired. I want DSP to turn off and on, not the audio device.

Again, why would you need to keep the audio device running if there's no DSP (except for Jack)?

> When audio is disconnected and connected, it should be done with a different method.

IMO this would be super confusing. There *are* scenarios where you want DSP but no audio devices; in this case you can simply disable the inputs and outputs (or start pd with `-noaudio`)

> Isn't that more proof it is a bad design choice? Ideally, a method works the same regardless of current backend.

It's rather because of a very specific issue with Jack.

> I very welcome such a method.

Then I think we kind of agree anyway :)

**Comment by reduzent** [comment]
> > I don't think this desired. I want DSP to turn off and on, not the audio device.
 
> Again, why would you need to keep the audio device running if there's no DSP (except for Jack)?

My question is: Why is the method called 'dsp' when it does other things, too? Maybe I'm wrong, but I think 'dsp' once did turn on and off only DSP. It's not the first time these things are discussed.
 
> > I very welcome such a method.
> 
> Then I think we kind of agree anyway :)

Yeah. There is clearly some merit in having a way to control DSP specifically. How it is labelled is of lesser concern.

**Comment by reduzent** [comment]
I need to correct myself.  Apparently, the current behavior has been in place since at least 2015 (probably forever). I was bringing up the topic back then, but didn't get any answers:

https://lists.puredata.info/pipermail/pd-list/2015-09/111595.html

**Comment by reduzent** [comment]
Closed in favor of https://github.com/pure-data/pure-data/issues/2153
