### ISSUE TITLE
atom boxes are loosing inlets/outlets

### ISSUE THREAD

**Issue by 60-hz** [pure-data/pure-data#2154]
atom boxes GUI object are loosing their inlet/outlet when specify a send and receive name in the property panel.
Can break patches and is inconsistent with other GUI (tgl, bang, hslider...)

MacOS Sonoma 14
pd-0.54-1

**Comment by umlaeute** [comment]
duplicate of https://github.com/pure-data/pure-data/issues/1005

**Comment by porres** [comment]
more like a dupe of https://github.com/pure-data/pure-data/issues/1344
