### ISSUE TITLE
TCL errors on File->Open or creating subpatches

### ISSUE THREAD

**Issue by Barbouze** [pure-data/pure-data#216]
Hi!
I have this problem from time to time when opening a file or creating subpatches. I couldn't track what triggers it but it seems related to the windows size when a file is saved.
If this problem occurs, I can't do anything and have to close PD. Then I have to open a working file, close it and try to re-open the problematic patch.
What informations should I provide you to help resolving this bug?
Cheers,
Barbouze
![capture du 2017-09-02 13-56-19](https://user-images.githubusercontent.com/2013289/29995342-442b765a-8fe7-11e7-8809-2fbac89603f3.png)

**Comment by umlaeute** [comment]
weird one, as the `_left` variable should be set in the line just above the one that raises the error.

could you try to install the [`tclprompt-plugin`](https://github.com/pure-data/tclprompt-plugin), enable it ("*Help* -> *Tcl Prompt*"), and see what you get by typing

   ::pdwindow::post [wm geometry .pdwindow]

in the tcl-prompt (just below the Pd-console)

**Comment by Barbouze** [comment]
I got "500x400+20+50" and after moving the main window in the top left corner (as I usually do), I get "500x400+-9+-8".
Hope that helps

**Comment by Barbouze** [comment]
... and that is what triggers the error. For some reason, Pd or Cinnamon, my DE, thinks that the top left corner isn't 0,0 but -9,-8.

**Comment by umlaeute** [comment]
dd96625 should fix this. let's hope it gets included into Pd-0.48-1

**Comment by Barbouze** [comment]
Thanks! :)
