### ISSUE TITLE
Patch titlebar path is stripped of slashes on Windows

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#217]
The path in the titlebar for patches is stripped of it's slashes on Windows, ie. "path/to/some/patch.pd" becomes "pathtosomepatch.pd". This i happening in `pdtk_canvas_reflect_title`.

**Comment by danomatika** [comment]
@Spacechild1 Is this fixed by now? Can you check?

**Comment by umlaeute** [comment]
ping @Lucarda for an alternative authority in the winworld

**Comment by Lucarda** [comment]
Ping response:

I'm going to be terribly busy until mid July relocating all my place.

> Is this fixed by now? Can you check?

all fine with `Pd 0.55.0test2`

![pic-path](https://github.com/pure-data/pure-data/assets/25239522/6d8c609d-10d4-4df7-8cf6-e3d513898374)

**Comment by danomatika** [comment]
Thanks for checking.
