### ISSUE TITLE
trying to move a modified abstraction can lock you into an infinite loop

### ISSUE THREAD

**Issue by Ant1r** [pure-data/pure-data#2176]
steps to reproduce:

- create a patch containing an abstraction, save the patch.
- modify the abstraction (add, delete or move an object within it). The abstraction is now marked as "dirty", and an asterisk is appended to its window title. Don't save the abstraction.

- in the parent patch, click on the (modified) abstraction, move it, and try to place it somewhere by clicking again;
- Pd then opens a dialog asking _"Discard changes to [the abstraction name].pd? Yes/No"_.
- If you tap "No", you are returned to the parent patch, however the abstraction is still attached to the mouse pointer, so your only choice is to click somewhere to try again to place the abstraction; you are then returned to the previous step, and again and again, and you end up dying from lack of sleep or food.
- If you tap "Yes", then you can at last drop off the abstraction (which was still attached to the pointer), but you lose the information that it was modified.

**Comment by umlaeute** [comment]
possibly correct behaviours (more than one answer):
- do not pop the "Discard changes" dialog when moving a dirty abstraction
- stop moving the abstraction (regardless of the user's choice)
- stop moving (or deselect altogether) by pressing <kbd>Esc</kbd>

**Comment by Ant1r** [comment]
I chose solution number 2, hoping it's the right one.

**Comment by umlaeute** [comment]
i think all of them are correct :-)

**Comment by umlaeute** [comment]
> I chose solution number 2, hoping it's the right one.

hmm, are you?

afaict (but it's quite possible i misunderstand my own suggestion) this means that i would not be able to move an object that refers to a modified abstraction/subpatch.
however, it seems i can still move it.

otoh, i still get the "Discard changes?" popup after the move (also, accepting the discard-changes, the abstraction is marked as undirty (the asterisk goes away) but in fact all the changes are kept.
while this state allows me to just close the patch without another pestering "Discard changes?" dialog, it's somewhat weird.

**Comment by Ant1r** [comment]
your solution #2 was:
> stop moving the abstraction (regardless of the user's choice)

As I understood it, it means that once you close the dialog (whether you chose "yes" or "no"), the mouse should stop moving the abstraction. This indeed fixes the current bug (aka infinite loop).

However I agree with you this is not optimal:
- if the abs does not need to be re-created (only placed after a move), there is no need to warn for the inner changes.
- that situation, where Pd just "forgets" the changes although the changes are still there, is weird. Note it's already the case in current master.

After digging into the source to try fixing #2184, I think the triggering of the "Discard changes" dialog should be revised at several places; 
I'd suggest to accept #2183 and wait for this latter "Discard changes" revision to fix those weirdies.

**Comment by Ant1r** [comment]
For clarity: #2183 is now closed in favor of #2200 which implements umlaeute's proposition 1: the dialog doesn't appear anymore after moving (or clicking on) the dirty abs. Instead, it opens when typing into the abs.
