### ISSUE TITLE
Sysex message on Windows

### ISSUE THREAD

**Issue by GlidingTr** [pure-data/pure-data#2185]
Hi guys,

The midiout function only works under Linux.
Is there any plan to make it work also under Windows?

Thanks!

**Comment by Spacechild1** [comment]
> The midiout function only works under Linux.

`[midiout]` works fine here on Windows... Is this issue only about Sysex or MIDI in general? Also, please provide a minimal test patch that demonstrates the problem.

**Comment by GlidingTr** [comment]
Hi, I'm trying to control the lighted keys of my midi controller.
I can successfully light a key with the below sysex message from a tool call Bome SendSX:
![image](https://github.com/pure-data/pure-data/assets/158178192/708dacab-b69f-4de9-9f04-75a39b2932d6)

If I try to replicate the same message in pd, I convert the hex code into decimal and send it to [midiout].
![image](https://github.com/pure-data/pure-data/assets/158178192/7446d17b-56a1-47ec-93e0-3d80459a36b3)

But I'm unsuccessful.
As you can see I'm using Purr-Data-2.19.3 20230725-rev.e9fca4f8 (Pd-0.48.0)

I aslo saw in the documentation (Linux only) for [midiout].
![image](https://github.com/pure-data/pure-data/assets/158178192/0d90fb61-9d4c-4bbf-a824-eba2551f7f57)

**Comment by Spacechild1** [comment]
I think "(Linux only)" only refers to "(the second inlet is the port number)". `[midiout]` itself works fine on Windows (except that currently you can only use the first output device.

BTW, this is the repository for Pd vanilla. If you have a problem with Purr-Data, please open an issue at *their* issue tracker. I'm closing this therefore.

**Comment by GlidingTr** [comment]
Thanks for you help. I just tested it on Pd vanilla and it works perfectly. Thanks.
Sharing the screenshot here.
![image](https://github.com/pure-data/pure-data/assets/158178192/69fefe02-33ac-4a8a-9c11-6bd3949d4668)

**Comment by Spacechild1** [comment]
Great! Thanks for confirming.
