### ISSUE TITLE
Invalid format specifier causes stderr output to be garbled on windows / clang

### ISSUE THREAD

**Issue by jcelerier** [pure-data/pure-data#2187]
Here:  

https://github.com/pure-data/pure-data/blob/0259d00373b9e6f3bc1d76eebc5b243283ca7063/src/s_print.c#L58

This only prints me ??? with clang / ucrt on windows.

simple repro:

```c++
#include <cstdio>
#include <cwchar>
int main() {
  fwprintf(stderr, L"%s", "hello");
}
```

gives ??o with clang / ucrt (matching MSVC), hello with g++ / msvcrt (which apparently had buggy, incorrect behaviour: https://stackoverflow.com/a/17702172).

Replacing `%s` with `%S` fixes things.

Can I suggest a patch replacing %s with %S there if we are on a newer C runtime on windows?

Edit: after more investigation the cause is actually when compilers define (or don't define) __USE_MINGW_ANSI_STDIO.
When it is undefined or 0, the behaviour matches MSVC.

**Comment by Spacechild1** [comment]
Will have a look!

**Comment by umlaeute** [comment]
ping @Spacechild1
