### ISSUE TITLE
vu inconsistency before/after save [sender option in properties]

### ISSUE THREAD

**Issue by charlesneimog** [pure-data/pure-data#2189]
Hi, when we create a `vu` object, it is possible to set a "`sender`" (that will not work). See the video:

It disappears after we save and reopen the patch.

https://github.com/pure-data/pure-data/assets/31707161/cfbd736d-21ec-40a6-80ff-050fc11e0e13

**Comment by umlaeute** [comment]
while i can confirm, i'd say that this is a rather low-priority issue...
