### ISSUE TITLE
control-click in console doesn't take user to the error on Windows

### ISSUE THREAD

**Issue by sebshader** [pure-data/pure-data#2191]
Windows 10 Home, Pd 0.54-1.

On MacOs and Linux (iirc) ctrl-click on an error in the console brings up the object that 'threw' the error.
On Windows when I hold control it brings up an "I" text insertion cursor in the console, and text in the console is just selected as normal when clicking.

'Find Last Error' in the find menu does take me to the error/correct object

**Comment by umlaeute** [comment]
there seem to be two separate issues preventing this from working:
- Clicking the error does not seem to emit a callback to Pd at all (it should send a `pd findinstance ${id}`
- Pd-core uses `%p` to format the canvas-id, which on Windows gives something like `0000000000cf4ea0`. however `pd findinstance` assumes `0x%lx` or `.x%lx` as the formatter.

**Comment by Spacechild1** [comment]
Can confirm on Windows 10 with Pd 0.54.1!
