### ISSUE TITLE
openpanel/savepanel not working if triggered in invisible patch

### ISSUE THREAD

**Issue by ben-wes** [pure-data/pure-data#2195]
tested with pd32 from the current develop-branch on mac, arm64, sonoma 14.3.1 (to exclude build-related problems on my side, i also tested with the current develop-artifact from the iem-pipeline):

when trying to trigger an openpanel/savepanel dialog in an invisible patch (i'm doing this in abstractions - and i guess it's valid practice?), i get errors like this:

~~~
(Tcl) UNHANDLED ERROR: bad window path name ".x600003a94000.c"
    while executing
"tk_getOpenFile -initialdir $localdir  -parent $parent"
    (procedure "pdtk_openpanel" line 14)
    invoked from within
"pdtk_openpanel {d600002590140} {} 0 .x600003a94000.c "
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $docmds"
~~~

here's a minimal patch for testing:
* [test-bug-openpanel.pd.zip](https://github.com/pure-data/pure-data/files/14282818/test-bug-openpanel.pd.zip) 

i didn't test other versions now - but might be related to https://github.com/pure-data/pure-data/commit/9524f8d1f80235748d33d343c96b1ffffa55d0c9?

**Comment by ben-wes** [comment]
just noting here: i can work around this for now by naming the canvas and then doing something like this:
~~~
[t b a b]
|   |   |
|   |   [vis 1(
|   |   |
|   |   [s $0-cnv]
|   |
|   [openpanel]
|
[vis 0(
|
[s $0-cnv]
~~~

... that's obviously not a solution though, but maybe relevant for the fix.

**Comment by umlaeute** [comment]
sidenote: on Linux (Xfce) this doesn't seem to be a problem.

**Comment by Lucarda** [comment]
sidenote: on Win11 this doesn't seem to be a problem.

**Comment by ben-wes** [comment]
and another sidenote of macOS: the edit-dialog for `text` works as expected and is also a non-modal dialog.

**Comment by umlaeute** [comment]
hmm, i've just tested with 0.54-1 on macOS 13.6.1 "Ventura", and i don't see any problem.

**Comment by umlaeute** [comment]
i've now tested with c863bbecce07ab7cd632eccace3e51e4e0f07357 and i can confirm the behaviour on both macOS/Ventura/arm64 and Debian/sid/amd64

**Comment by ben-wes** [comment]
looks good here now with a local `develop` build on Sonoma. thanks!
