### ISSUE TITLE
 Unexpected Behavior in Pure Data's `[switch~]` Object with some of externals

### ISSUE THREAD

**Issue by charlesneimog** [pure-data/pure-data#2198]
Hi, 

I have weird behavior. 

It is easier if you see this simple example:

[bug.zip](https://github.com/pure-data/pure-data/files/14324729/bug.zip)

When we have some `switch~` set with a different vector size of global pd inside some subpatch, for some reason, the audio connected in the `inlet~` of the subpatch is passed for the output of the outlet even if there is no connection. This happens just if, for some reason, we return the audio without the processing. Something like this:

``` c
static t_int *bug_perform(t_int *w) {
  t_bug *x = (t_bug *)(w[1]);

  if (1) {
    //let's say this check if there is an error
    return (w + 4);
  }
}

``` 

This is some kind of limitation or it is a bug? I always need to fill the outputs with 0 in all my externals in case of errors?

Thank you!

**Comment by Lucarda** [comment]
may be related:

see: https://github.com/pure-data/pure-data/issues/2136 it has been merged to `develop`.

If you can build https://github.com/pure-data/pure-data/tree/develop and test if your issue is gone with this fix?

**Comment by Lucarda** [comment]
i'm deleting my previous post and this one as they are unrelated. sorry for the noise. :)

**Comment by Spacechild1** [comment]
>  Should I always need to fill the outputs with 0 in all my externals in case of errors?

Yes, you have to! Otherwise the output will contain garbage.

**Comment by charlesneimog** [comment]
Because this just happens when I use the `switch~` in the subpatch (`[switch~ 1024]` for example).

So this is expected behavior?

**Comment by Spacechild1** [comment]
All I can say is that you *must* write something to the outputs, otherwise they will contain garbage. (The exact garbage depends on the patch structure.)

**Comment by sebshader** [comment]
> Because this just happens when I use the `switch~` in the subpatch (`[switch~ 1024]` for example).
> 
> So this is expected behavior?

most likely the last thing processed in the graph was the signal in the inlet. so it is expected behavior, and also undefined behavior.

**Comment by charlesneimog** [comment]
If this happens with all blocksizes I will understand, but just when it is different of the main blocksize.

But whatever, this is not really a problem, just weird!

**Comment by umlaeute** [comment]
> If this happens with all block sizes I will understand, but just when it is different from the main blocksize.

that's the joy of *undefined behaviour*.

**Comment by charlesneimog** [comment]
ba bum pssiiiiii rsrsrs
