### ISSUE TITLE
symbol object in nogui environment breaks everything

### ISSUE THREAD

**Issue by patricecolet** [pure-data/pure-data#2202]
Using pd-0.54.1 on linux arm64

A patch containing a symbol object has a line called `#X listbox`

when pd -nogui opens this patch, console outputs: `error: canvas: no method for 'listbox'`

then all connections are broken.

**Comment by Lucarda** [comment]
can't replicate on Pd 0.54-1 on Win11

```
#N canvas 77 157 450 300 12;
#X obj 88 103 dac~;
#X obj 125 18 osc~ 440;
#X obj 309 43 loadbang;
#X obj 292 137 s pd;
#X msg 305 90 dsp 1;
#X listbox 139 198 20 0 0 0 - - - 0;
#X msg 157 130 list 1 2 3;
#X connect 1 0 0 0;
#X connect 2 0 4 0;
#X connect 2 0 6 0;
#X connect 4 0 3 0;
#X connect 6 0 5 0;
```

`C:\Program Files\Pd\bin>pd -nogui c:/tmp/foo.pd`

**Comment by Lucarda** [comment]
I suspect that your invocation `pd -nogui ...` is taking you to an older Pd version installed on your system.

try `pd -version` to tell which Pd is starting.

**Comment by umlaeute** [comment]
i'm pretty sure that @Lucarda is right.
you need at least Pd-0.52 for the `#listbox`

**Comment by patricecolet** [comment]
`$ pd -version
Pd-0.54.1 ("") compiled 21:47:56 Feb 29 2024`

I have pain to reproduce the context of the bug

`$ echo '#N canvas 77 157 450 300 12;
#X obj 55 95 dac~;
#X obj 55 34 osc~ 440;
#X obj 364 23 loadbang;
#X obj 347 117 s pd;
#X msg 360 70 dsp 1;
#X listbox 246 199 20 0 0 0 - - - 0;
#X msg 251 138 list 1 2 3;
#X symbolatom 55 246 10 0 0 0 - - - 0;
#X obj 57 199 symbol;
#X msg 57 153 hello;
#X obj 197 33 t b b b;
#X obj 57 66 *~ 0.01;
#X connect 1 0 11 0;
#X connect 2 0 10 0;
#X connect 4 0 3 0;
#X connect 6 0 5 0;
#X connect 8 0 7 0;
#X connect 9 0 8 0;
#X connect 10 0 9 0;
#X connect 10 1 6 0;
#X connect 10 2 4 0;
#X connect 11 0 0 0;'>test-patch.pd`

`$ echo '#N canvas 781 1156 450 300 12;
#N canvas 997 1403 450 300 subpatch 0;
#X obj 10 10 test-patch;
#X restore 49 266 pd subpatch;
#X obj 48 8 loadbang;
#X obj 48 53 t b b;
#X obj 48 134 del 5;
#X msg 80 81 \; pd-subpatch clear;
#X msg 48 180 \; pd-subpatch obj 10 10 test-patch \; pd-subpatch editmode 0 \; pd-subpatch menusave \; pd-test-patch.pd loadbang;
#X connect 1 0 2 0;
#X connect 2 0 3 0;
#X connect 2 1 4 0;
#X connect 3 0 5 0;'>test.pd`

`$ pd -nogui -noadc -alsamidi -alsa -r 48000 -blocksize 64 -audiobuf 10 test.pd `

This is something like this, but the bug still doesn't come out

**Comment by patricecolet** [comment]
This has always happened since listbox has been introduced.

**Comment by patricecolet** [comment]
I think you are right, there is still /usr/bin/pd -v : Pd-0.51.4 ("") compiled for Debian (0.51.4-1) on 2020/12/29 at 20:18:32 UTC

**Comment by umlaeute** [comment]
that's typically because of the `PATH` variable being set differently (e.g. because you only add`/usr/local/bin` to `PATH` for interactive shells; or because you are running as different user; ...)

**Comment by patricecolet** [comment]
> can't replicate on Pd 0.54-1 on Win11
> 
> ```
> #N canvas 77 157 450 300 12;
> #X obj 55 70 dac~;
> #X obj 55 34 osc~ 440;
> #X obj 364 23 loadbang;
> #X obj 347 117 s pd;
> #X msg 360 70 dsp 1;
> #X listbox 246 199 20 0 0 0 - - - 0;
> #X msg 251 138 list 1 2 3;
> #X symbolatom 55 246 10 0 0 0 - - - 0;
> #X obj 57 199 symbol;
> #X msg 57 153 hello;
> #X obj 197 33 t b b b;
> #X connect 1 0 0 0;
> #X connect 2 0 10 0;
> #X connect 4 0 3 0;
> #X connect 6 0 5 0;
> #X connect 8 0 7 0;
> #X connect 9 0 8 0;
> #X connect 10 0 9 0;
> #X connect 10 1 6 0;
> #X connect 10 2 4 0;
> ```
> 
> `C:\Program Files\Pd\bin>pd -nogui c:/tmp/foo.pd`

Just for info, this patch has almost destroyed the speaker of the device I'm testing in, because there is no volume settings, it scared me, and my neighbourgs, please add [*~0.05] after [osc~ 440] or prevent the user about the loud sound. And thank you again for your lights.
