### ISSUE TITLE
cannot use 'find last error' feature for the "couldn't create" error

### ISSUE THREAD

**Issue by brianlindgren** [pure-data/pure-data#2209]
sometimes I'll get "... couldn't create" errors in my patch when I change an abstraction's initialization argument from a float to a symbol (123 to abc). When I use the 'find last error' feature to search for the broken object, PD returns 'no findable error yet'. My patch is large with many abstractions and searching for the object which broke using 'find' will return thousands of results. 

Is there a way to use 'find last error' to find the "... couldn't create" errors?

thank you!

**Comment by Ant1r** [comment]
You can ctrl-click an error in the console, it should bring you to the
object it comes from.
This works for most kinds of error, and particularly for the "couldn't
create" ones.

Le lun. 11 mars 2024 à 20:34, brianlindgren ***@***.***> a
écrit :

**Comment by brianlindgren** [comment]
thank you. however this doesn't seem to be working for me (I'm on a Mac if that makes any difference). when I try that, my cursor becomes an up arrow with a flat line below it, but clicking on the error does not produce any result.

**Comment by umlaeute** [comment]
you have press <kbd>Ctrl</kbd>  (or <kbd>Cmd</kbd> resp <kbd>⌘</kbd>) while clicking the error message.

there's a known issue on Windows (#2191), but on macOS it should work.

**Comment by brianlindgren** [comment]
yes, command worked - lifesaver - thank you!

**Comment by Ant1r** [comment]
I can't remember exactly how it works on mac, but it should do either way. Did you try with Cmd key?

You can also hover the error and press Return key.

**Comment by brianlindgren** [comment]
out of curiosity, is there a reason (in terms of PD design) that 'find last error' won't work unless pushing that modifier key?

**Comment by umlaeute** [comment]
well yes: the last error depends on a "handle" to the object, but if the object cannot be created there's no such handle.

**Comment by Ant1r** [comment]
I think @brianlindgren was talking about simply clicking the error (rather "find **this** error").

Good question. Why not just clicking after all...

It simply should be done in a way that still allows to select text in the console without opening every erroneous object in the selection.

**Comment by Spacechild1** [comment]
> but if the object cannot be created there's no such handle.

But there *is* a text object, even if the desired object could not be created, see `canvas_objtext`:
```
if (!x)
    {
        x = (t_text *)pd_new(text_class);
        canvas_error_couldntcreate(x, b, "... couldn't create");
    }
```
So I don't see a particular reason why finding should not work in this case.

**Comment by Ant1r** [comment]
See #1508 :-)
