### ISSUE TITLE
can't expand "~/" in [openpanel]

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2214]
[file] does expand "~/" to home directory as of https://github.com/pure-data/pure-data/pull/2160

This could also be useful for other objects like [soundfiler], etc, right? It'd also be good for consistency.

**Comment by umlaeute** [comment]
it would be so good that it already works.

**Comment by porres** [comment]
I will test it then, but I already see [openpanel] doesn't seem to be able to take '~' and open in the home directory, can you confirm?

**Comment by umlaeute** [comment]
nope.

this does what it should:
```pd
[symbol ~(
|
[openpanel]
|
```

**Comment by porres** [comment]
then we got a bug... on my macbook air 2013, running 10.14.6, it opens the default 'pd' directory instead... 
![Screen Shot 2024-03-14 at 18 04 03](https://github.com/pure-data/pure-data/assets/5360142/e5f3a67a-cf6e-4fe1-9d5a-17ce959e9cc0)

**Comment by porres** [comment]
writesf~ couldn't handle ~ for me either, [soundfiler] and [readsf~] are fine

**Comment by umlaeute** [comment]
these are about reading vs writing.
when finding existing files, Pd expands `~/`, but not when writing files.

so with `[soundfiler]`,  `[read ~/voice.wav mytable(` will read the `voice.wav` from your homedirectory, but `[write ~/voice.wav mytable(` will write the file into the `./~/` subdirectory of the cwd (provided that this subdirectory exists (`[symbol ~(` -> `[file mkdir]`)

**Comment by umlaeute** [comment]
these are about reading vs writing.
when finding existing files, Pd expands `~/`, but not when writing files.

so with `[soundfiler]`,  `[read ~/voice.wav mytable(` will read the `voice.wav` from your homedirectory, but `[write ~/voice.wav mytable(` will write the file into the `./~/` subdirectory of the cwd (provided that this subdirectory exists (`[symbol ~(` -> `[file mkdir]`).

with `[openpanel]` i think this is a bug in Tcl/Tk and/or the macOS fileselector.

i think we should keep these two issues separate.

**Comment by umlaeute** [comment]
while i've fixed `[openpanel]` in the devel branch, there's still #2169 , which kind of makes this irrelevant...

**Comment by porres** [comment]
> there's still https://github.com/pure-data/pure-data/issues/2169 , which kind of makes this irrelevant...

I'm here still on mojave :) and current OS is Sonoma, this also happens there I believe, huh?

**Comment by porres** [comment]
> while i've fixed [openpanel] in the devel branch

ok, changed the subject so this can be closed when devel is merged again, will open a new one for writting into ~
