### ISSUE TITLE
ctrl+d shortcut is missing in the menus

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2217]
and it should be in the 'edit' menu

**Comment by umlaeute** [comment]
I'm not sure about which Pd you are using, but mine does have this shortcut in the Edit menu
![ctrl-d](https://github.com/pure-data/pure-data/assets/214034/dc3dc570-9033-4536-8ce4-e1ebc77887ab)

**Comment by porres** [comment]
Ouch, nevermind
