### ISSUE TITLE
feature request: correctly output lenght of audio with [soundfiler]

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pure-data#2226]
As seen in https://github.com/pure-data/pure-data/issues/2225 [soundfiler] does not give you the correct length of the sound data in bytes, only the header offset to the start of the sound data (when not suppling an array).

Not suppling an array is convenient if we just need to pre-calculate playing time(s) or other stuff.

**Comment by umlaeute** [comment]
i'm not really sure but why does the first outlet of `[soundfile]` not work for you?

at least on my system, it gives me the length of the data chunk in sampleframes.

**Comment by Lucarda** [comment]
right, thanks for the clarification.  i misread 2 times 

https://github.com/pure-data/pure-data/issues/2225#issuecomment-2005211877

i'll close this as i can have accurate time prediction on 1sec file (with or without metadata). I thought there was a trouble with that.

![pic](https://github.com/pure-data/pure-data/assets/25239522/345790e7-225e-4795-b9a7-06e097bf85f4)
