### ISSUE TITLE
feature request: add a way to change Pd's sample rate from an object in the patch.

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pure-data#2227]
This is really needed (i think).

**Comment by porres** [comment]
[pdcontrol]? :)

**Comment by Lucarda** [comment]
[samplerate~] ?

**Comment by Spacechild1** [comment]
I'm just curious: what is your use case?

One thing to keep in mind: the global samplerate is part of the audio settings. Instead of an ad-hoc solution, it would be better to think of a general solution for programmatically changing *all* audio settings.

Actually, the `mediasettings` library already lets you do that, but must rely on (semi)private API functions. It would be better to have a stable solution in Pd vanilla.

**Comment by Lucarda** [comment]
> what is your use case?

Say i have 2 patches that heavily rely on soundfiles and one patch expects different sample rate(Pd's and soundfiles) than the other. of course i can manually change that but i could have it done from the patch level.

> It would be better to have a stable solution in Pd vanilla.

indeed :)

**Comment by Lucarda** [comment]
I think at least having something like this would be very useful at patch level:


```
samplerate     delay

[44100\        [20\
|              |
[audiosettings~]
```

**Comment by umlaeute** [comment]
> Actually, the mediasettings library already lets you do that, but relies on (semi)private API functions. It would be better to have a stable solution in Pd vanilla.

obviously the idea of the mediasettings library *is* to offer a stable interface on the patchlevel (whichever private, public or semi-private interface it is using).

that is not to say, that i would mind if mediasettings (or some improved version) would be part of Pd's object set.

**Comment by umlaeute** [comment]
@Lucarda wrote
> I think at least having something like this would be very useful at patch level

the question is: *why* would this be very useful?

the *only* reason i can think of, is to build your own audio-settings dialog that matches the aesthetics of the rest of your patch.

i'm a bit afraid of people just throwing in a `[samplerate 44100(` without thinking, and then the patch would do all kind of weird stuff on your system which is hardwired to to a 96kHz system.

**Comment by Lucarda** [comment]
you asked why it is useful and the answer i gave it above.

you say "without thinking" but that's a different animal. if you did that without thinking you will have to change the audio settings or better :) you can change the *patch* setting.

**Comment by Spacechild1** [comment]
I think @Lucarda already gave a very convincing use case:

> Say i have 2 patches that heavily rely on soundfiles and one patch expects different sample rate(Pd's and soundfiles) than the other.

This makes lots of sense. I occasionally run into this problem myself. `[readsf~]` cannot resample, so if you accidentally have the wrong samplerate, all your soundfiles are messed up. With 44.1 kHz vs. 48 kHz that isn't always immediately obvious. In this case it makes sense to "force" the samplerate on the patch level.

(Of course, it would be even better if `[readsf~]` had an option to resample.)

> and then the patch would do all kind of weird stuff on your system which is hardwired to to a 96kHz system.

If you select a samplerate that is not supported by your sound card, you'll get an error message in the console.

**Comment by Spacechild1** [comment]
> but this cannot be solved with switching the samplerate on patchlevel.

It's clear that you can't open both patches at the same time (unless `[readsf~]` itself can resample). In this context, I read "patch" to really mean "project".

> afaict, the only way to solve this problem is by adding resampling to [readsf~]

I would prefer that solution, of course. But there are other objects with the same problem, e.g. `[tabplay~]`. Of course, we could identify and add resampling capabilities all of them, but then there are also externals.

That being said, resampling [+ playrate control] for `[readsf~]` and `[tabplay~]` is already on my to-do list.

**Comment by Lucarda** [comment]
@umlaeute hmm, yes. Well i was thinking more for myself in a Windows machine. but now thinking again on what you meant as "hard wired" i guess this is the case when using `jack`. i catch that there's no point in changing Pd's samplerate.  

@Spacechild1 

> That being said, resampling (+ playrate control]) for [readsf~] and [tabplay~] is already on my to-do list.

nice!!!

PS: should we close this?

**Comment by Lucarda** [comment]
PS2: yes we close it. feel free to reopen.

**Comment by umlaeute** [comment]
maybe the real solution would be to allow for resampling to arbitrary samplerates in a subpatch (or at least a `pd~`).

**Comment by Lucarda** [comment]
yes. in the subpatch please.

**Comment by Lucarda** [comment]
some added thing|code for [block~]?

**Comment by Spacechild1** [comment]
> maybe the real solution would be to allow for resampling to arbitrary samplerates in a subpatch (or at least a pd~).

I'm skeptical. Arbitrary resampling of subpatches would raise quite a few open questions. It would be far from trivial to implement.

IMO it makes more sense to add resampling to `[readsf~]` and `[tabread~]`. It would then also allow to control the playback speed! FWIW, SuperCollider has had this since forever (see `VDiskIn` and `PlayBuf`).

**Comment by umlaeute** [comment]
well it's definitely non-trivial.
it was mainly a response to your  (emphasis mine):
> we could identify and add resampling [to] capabilities **all** of them, , but then there are **also externals**...

which i think is a hopeless task (in its totality).

of course, changing the playback speed of `[readsf~]` and `[tabplay~]` has other uses as well, so it schould  be implemented in its own right.

**Comment by Spacechild1** [comment]
> which i think is a hopeless task in its totality

Sure! Anyway, I will make PRs for resampling resp. rate control for `[readsf~]` and `[tabplay~]` (I already have an external for the latter).
