### ISSUE TITLE
batch VST chain (question)

### ISSUE THREAD

**Issue by geextahslex** [pure-data/pure-data#2230]
I just want to ask a question this is not an issue :)

Hi, I don't know much about pure data, but someone recommended it on reddit for vst batch script ability.
I want to know if I can send a .wav to pure-data in command line (no GUI), run it through 2-3 vst plugins with some settings and return it as .wav.
I'm using windows if this matters.

Thank you
Sorry if this is the wrong place for my question :)

**Comment by charlesneimog** [comment]
Yes, you can, basically you need the `vstplugin~`, then load the plugin and process. 

You need to use the `-batch` flag. Also, you need to exit PureData after the process with `; pd quit` (without this pd will not quit)

Here you find some examples:

https://github.com/zepadovani/pd-python_NRT

Here also, but it is lisp hehe

https://github.com/charlesneimog/om-pd

**Comment by geextahslex** [comment]
Thank you for your answer.
Okay that looks complicated, but it's cool that (somehow) it is possible.
Until now I was using mrswatson, and all that was needed was something like this
`mrswatson64 --input center.wav --output out.wav --plugin FabFilterMono --parameter 0,0 --parameter 1,0.415 --parameter 2,0.90`

**Comment by Lucarda** [comment]
@geextahslex you can do it just with the external [vstplugin~]. but you need to know Pd. Pd can be run in `-batch` mode, etc. but such a task is not for beginners.

**Comment by geextahslex** [comment]
@Lucarda I see, but you must start somewhere ^^ I'm also new (2 weeks) to ffmpeg and scripts. 
Is there a forum or some place where pure-data people are around?

**Comment by Lucarda** [comment]
@geextahslex oh welcome, yes :)

there is the main Pd List https://lists.puredata.info/listinfo/pd-list

the main Pd portal https://puredata.info/

and some tutorials to start learning the basics (which is really needed) http://pd-tutorial.com/
