### ISSUE TITLE
GEM not loading video files

### ISSUE THREAD

**Issue by ImPazuzu** [pure-data/pure-data#2232]
quite new to working with GEM and constantly get this issue whenever I try and load any video file format. Can load static images fine, but it appears like GEM always tries to load the file as a TIFF file resulting in it failing. 

`[GEM:imageTIFF] C:/Users/Cammy/Documents/Pd/finalhope/egg4final.avi Not a TIFF or MDI file, bad magic number 18770 (0x4952)
[pix_movie]: unable to open file: C:/Users/Cammy/Documents/Pd/finalhope/egg4final.avi
[GEM:imageTIFF] C:/Users/Cammy/Documents/Pd/finalhope/egg4final.avi Not a TIFF or MDI file, bad magic number 18770 (0x4952)
[pix_movie]: unable to open file: C:/Users/Cammy/Documents/Pd/finalhope/egg4final.avi`

this is what the error message looks like. I've tried searching for solutions but the closest I got was a guy 14 years ago experiencing the same issue in a thread who got told to report it as its own issue and never did.

**Comment by umlaeute** [comment]
try installing the K-lite codec pack.

also the bug-tracker for Gem is at https://bugs.gem.iem.at (for whatever reasons, i cannot transfer this ticket)
