### ISSUE TITLE
class dispatcher missing prototypes? ex. clicking on pd subpatch no longer calls canvas_click

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#2241]
This looks like a bug introduced when merging #688 which added Emscripten support.

@millerpuckette  has noticed a problem with the class dispatcher which indicates it may not cover all required function prototypes. @Spacechild1 maybe we actually do need the full 36?

I am personally not surprised as those working with the original PR likely ran the Emscripten version as a runtime via libpd and not with normal desktop-style patch creation with the GUI.

I am copying in Miller's email here in the case that anyone building the current master wonders what is going on:

---

> It looks like the code now in m_class_dispatcher* does "objectmaker" calls OK but omits some cases (and includes nonexistent ones) for plain messages. All plain messages are called with at least one pointer-sized argument that is the object to pass the message to, and no top of that may have up to five integer or floating-point arguments.  So for instance,
> 
>     case 0x00 : (*(t_vfun00)(m->me_fun))(); break;
> and
> 
>     case 0x01 : (*(t_vfun01)(m->me_fun))(ad[0]); break;
> 
> aren't needed but there should be a
> 
>     case 0x15: [...]
> 
> etc.  The number of cases is still 21.  I think they are precisely the cases currently listed, each incremented by 16 with one leading integer argument.
> 
> (symptom: clicking on a "pd" doesn't open it since canvas_click has 5 floating-point args :)

**Comment by danomatika** [comment]
Also, I see the `m_class_dispatcher.c` file ... but how do I run it? I assume I compile it then run it in the `src` directory or...? Would be nice to have some further documentation about this so we could, possibly, integrate these steps into the auto tools makefiles etc (if this makes sense).

**Comment by Spacechild1** [comment]
@millerpuckette already found the issue:

> All plain messages are called with at least one pointer-sized argument that is the object to pass the message to, and no top of that may have up to five integer or floating-point arguments. 

The solution is simple: just invoke `m_class_dispatcher.c` with 6 maxargs. This would still create 2 unnecessary cases (`0x00` and `x06`), but we don't need to care.

> I assume I compile it then run it in the src directory or...?

Yeah, I guess so. It's just a single source file with no dependencies. I can generate new `m_class_dispatcher` headers and make a PR.

> Would be nice to have some further documentation about this so we could, possibly, integrate these steps into the autotools makefiles etc (if this makes sense).

Once we fix this issue, we won't ever need to run it again, unless we decide to change the value of `MAXPDARG` (which is pretty unlikely).

**Comment by danomatika** [comment]
Thanks @Spacechild1. This is a part of Pd I haven't delved into grokking. I would also add a little copy paste line about running the extra .c file as I prefer to document this so I don't have remember later.
