### ISSUE TITLE
How can we clarify confusion in G05 example patch?

### ISSUE THREAD

**Issue by maftkd** [pure-data/pure-data#2263]
This is a very minor issue, but the comment in G05 did confuse me, so maybe it will help others if we clarify it.

The patch is designed to teach how the sort order of [delwrite~] and [delread4~] matter when it comes to really small delays (smaller than 1 block). The patch uses a "correct" branch outlined in red that uses subpatches to guarantee sort order, and then an "incorrect" branch outlined in green where sort order is not correct.

![image](https://github.com/pure-data/pure-data/assets/30270257/ca83e426-e02b-41ac-a442-92ead86d59ed)

The comment kind of throws me off: "off to hear left-hand side; on to hear right hand side."

It's a bit confusing because the left and right sides sort of criss-cross towards the bottom of the patch.

When the toggle is off, what you actually hear is the [delread4~] outlined in green, and when it is on you hear the subpatches outlined in red, which is sort of the reverse of what I would expect given the comment.

Further adding to the confusion, when the toggle is on, the "wrong" version outlined in green appears to always be included in the output regardless of the toggle due to the way the [+~] blocks are laid out.

So what do you all think? Is this worth clarifying, or am I just missing something?
If worth clarifying, should we change the comment, or even change the layout of the patch to more clearly separate the "correct" and "incorrect" branches.
I'm happy to make a proposed change, but wanted to verify that this makes sense to others first as I am still relatively new to PD (hence working through the example patches in painstaking detail)

CC @porres since you are maintaining the documentation PR's

**Comment by ben-wes** [comment]
this example also confused me. please note that since this is a documentation related issue, it should be opened in the documentation project: https://github.com/pure-data/pddp

besides that, i think it would be nice to simplify the patch a bit and show more explicitly what's going on. maybe like this (if i'm not missing anything):

![image](https://github.com/pure-data/pure-data/assets/1923787/5b374498-f82a-4cf7-845a-4ac14287eea8)

**Comment by maftkd** [comment]
Hey @ben-wes,
Thank you for the info, I actually didn't know there was a separate project for documentation.
I'll close this one as not resolved, and re-open the issue in pddp.

**Comment by maftkd** [comment]
Closed this one, and re-opened it over here https://github.com/pure-data/pddp/issues/196

**Comment by umlaeute** [comment]
sidenote: we (the admins of the `pure-data` group), can transfer issues from this repository to `pure-data/pddp` if the need arises (and vice versa)... just so you know
