### ISSUE TITLE
multiple array warning message typo

### ISSUE THREAD

**Issue by LGoodacre** [pure-data/pure-data#228]
If you create multiple arrays with the same name, you get the following warning message:

`warning: array1: multiply defined`

This is supposed to say "multiple defined", right?

**Comment by porres** [comment]
if you think so (I'm no native speaker), it should be easy for you to propose a PR ;)

**Comment by LGoodacre** [comment]
Unfortunately I'm not a native git speaker. I did my best though (first PR I've ever made). Let's hope I didn't mess it up.

**Comment by porres** [comment]
looks good ;)
