### ISSUE TITLE
Wrong extension for MacOS externals [Pd Manual]

### ISSUE THREAD

**Issue by charlesneimog** [pure-data/pure-data#2283]
Hi, 

Following @umlaeute, https://github.com/pure-data/pd.cmake/commit/dbf8330aef15c9bd5f14879de5fcd24c57b50cbf#r141693677

the right extension for MacOs is `.so` not `.dylib` as in the Pd Manual.

https://msp.ucsd.edu/Pd_documentation/x4.htm

**Comment by charlesneimog** [comment]
@porres, can you check this, I didn't understand the thing with #2281, maybe it is easy to fix this there?

**Comment by charlesneimog** [comment]
Sorry, this seems right here (just the website that is wrong).

**Comment by umlaeute** [comment]
duplicate of #2156
