### ISSUE TITLE
Minor revisions to "About Pd"

### ISSUE THREAD

**Issue by julovi** [pure-data/pure-data#230]
The first line should say the current version, currently it says Pd 0.0.0

The file "  /Applications/Pd-0.48-0.app/Contents/Resources/Scripts/LICENSE.txt"

doesn't exist.

I'm in a Mac OS 10.12.6

**Comment by umlaeute** [comment]
i think this has been partly fixed in PR #182

**Comment by umlaeute** [comment]
both issues have been fixed in Pd-0.48-1
