### ISSUE TITLE
Patch loaded at startup stays hidden after receiving 'vis 0, vis 1' cycle

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#2310]
A patch loaded from command line stays hidden, when it receives a 'vis 0, vis 1' cycle at loadbang time. This seems to be a regression in the current test version of 0.55.0 (tested with f2bf19f85097505bd5a64d92d49e79822b5c2b43). 

Illustration patch here:

```pd
#N canvas 861 180 448 210 10;
#X obj 21 20 namecanvas hiddenandshown;
#X obj 18 108 loadbang;
#X msg 18 131 vis 0 \, vis 1;
#X obj 18 154 s hiddenandshown;
#X connect 1 0 2 0;
#X connect 2 0 3 0;
```

The patch is visible, when opened from the menu. It stays hidden when opened at startup like this:

```
pd -open vis-at-loadbang-regression.pd
```

Sometimes it even triggers a Tcl error:

```
(Tcl) INVALID COMMAND NAME: invalid command name ".x5f0eb6f793f0.c"
    while executing
".x5f0eb6f793f0.c create line 21 20 175 20 175 38 21 38 21 20 -dash "" -width 1 -capstyle projecting -tags {{.x5f0eb6f793f0.t5f0eb6faa910R} {obj} } "
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $docmds"(Tcl) UNHANDLED ERROR: bad window path name ".x5f0eb6f793f0"
    while executing
"wm deiconify $mytoplevel"
    (procedure "pdtk_canvas_raise" line 2)
    invoked from within
"pdtk_canvas_raise .x5f0eb6f793f0 "
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $docmds"
```

**Comment by reduzent** [comment]
Issue seems related to recent changes regarding late-loading GUI and to #2300.

**Comment by reduzent** [comment]
Trying to make invisible patch visible again  by sending it `[vis 1 (`  creates an error:

```
(Tcl) UNHANDLED ERROR: bad window path name ".x62f582bb54d0"
    while executing
"wm deiconify $mytoplevel"
    (procedure "pdtk_canvas_raise" line 2)
    invoked from within
"pdtk_canvas_raise .x62f582bb54d0 "
    ("uplevel" body line 2)
    invoked from within
"uplevel #0 $docmds"
```

The patch _can_ be made visible by sending `vis 0, vis 1` _twice_.

**Comment by reduzent** [comment]
For context: I have some patches that read a configuration and adjust their window size accordingly with a message:

```
vis 0, setbounds 0 0 $1 $2, vis 1
```

I can make those patches work with Pd 0.55 by delaying the message by 100 ms. However, I don't know how scalable this solution is (does it take more time on slower systems?) and it might be an indication for more troubles, when loadbang behaviour at startup is different from loadbang behaviour of patches loaded later.

**Comment by reduzent** [comment]
I just found another related issue. Since Pd 0.55, I cannot hide scrollbars with the [kiosk-plugin](https://git.iem.at/pd/kiosk-plugin) anymore for the initially loaded window. However, for a subpatch of the same  patch hiding the scrollbars works:

![image](https://github.com/pure-data/pure-data/assets/333373/6e86e5e1-52ab-4ce7-b322-3e59ee025ea2)

```
pd -path Pd/externals/kiosk-plugin -open Pd/trigger-scrolllbar2.pd
```

I'm just posting this as an example. I suspect that loading patches before GUI breaks probably more things and loading patches from command line is full of surprises.

**Comment by reduzent** [comment]
BTW: For the window showing the scrollbars, it doesn't help to resize it. The scrollbars won't disappear, probably exactly because the kiosk-plugin disables scrollbar management all together. This leads to the paradox situation that trying to hide the scrollbars actually forces them to be shown.

**Comment by umlaeute** [comment]
could you also post the `kiosk.cfg`? (it might just be a problem that is fixable within *kiosk*)

**Comment by reduzent** [comment]
Even if it would be fixable, I'd like to point out that the current situation is that loading patches from command line exhibits vastly different behavior from loading patches from the menu. Ideally, it doesn't matter how or when a patch is loaded. 

Here  is my kiosk.cfg (leaving out the comments):

```
HideMain False
KioskNewWindow True
ShowMenu False
FullScreen False
PreventClose False
QuitOnClose False
HidePopup False
QuitBinding True
Bindings True
ScrollBars False
```

**Comment by reduzent** [comment]
> could you also post the `kiosk.cfg`? (it might just be a problem that is fixable within _kiosk_)

Is it fixable? A work-around is to to send `vis 0, vis 1` to the main patch after a 100ms (or so) delay. Which is dead ugly, of course. Bad enough Pd 0.55 broke  patches loaded from command line. I don't see how this is less severe than the `pd quit` bug that is already fixed.

**Comment by umlaeute** [comment]
a quick fix for the `vis 0, vis1` problem is to make sure that the GUI is synced before proceeding.

E.g. with this:
```diff
diff --git a/tcl/pdtk_canvas.tcl b/tcl/pdtk_canvas.tcl
index 2da0adeb..a89b1386 100644
--- a/tcl/pdtk_canvas.tcl
+++ b/tcl/pdtk_canvas.tcl
@@ -161,6 +161,8 @@ proc pdtk_canvas_new {mytoplevel width height geometry editable} {
     # this should be at the end so that the window and canvas are all ready
     # before this variable changes.
     set ::editmode($mytoplevel) $editable
+
+    tkwait window $mytoplevel
 }
 
 # if the patch canvas window already exists, then make it come to the front
```

however, I guess this might slow down Pd considerably when opening many windows at once.

**Comment by umlaeute** [comment]
sidenote: i was unable to reproduce the kiosk scrollbar problem.

**Comment by reduzent** [comment]
Dear @umlaeute, thing seems in order now. No tricks necessary anymore to resize main patch (loaded from cmdline) at loadbang. Also, the kiosk-plugin is able to to suppress scrollbars from the beginning. 

Thanks a lot for the fix. I'm sure this is for the greater good. I only realize now that I could've done a bisect session myself, sorry for that. I'll try to remember next time.

**Comment by umlaeute** [comment]
np.
if you know how to use `git bisect run` for such things, it doesn't take *that* long :-)
