### ISSUE TITLE
cannot load external when opening patch from relative path

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#2334]
I just installed Pd 0.55-test3 on Windows 10 and tried to test one of my externals:
```
pd ./install/mingw64/vstplugin~-help.pd
```
The external is located next to help patch. However, Pd refuses to load it and shows the following error message in the console:
```
.\.\install\mingw64\vstplugin~\vstplugin~.dll: Das angegebene Modul wurde nicht gefunden.
 (126)
```
When I open the help patch from an *absolute* path, everything works.

This only happens with Pd 0.55. I wondering what could have changed... @umlaeute Any ideas?

**Comment by Spacechild1** [comment]
For some reason, Pd now uses a relative path to search for the library.

The problem is that `LoadLibrary` only accepts absolute paths. This leads to the odd situation that the library is found, but cannot be loaded.

Pd 0.55:
```
tried ././install/mingw64/vstplugin~/vstplugin~.dll and succeeded
.\.\install\mingw64\vstplugin~\vstplugin~.dll: Das angegebene Modul wurde nicht gefunden.
 (126)
```

Pd 0.54:
```
tried C:/Repos/vstplugin/./install/mingw64/vstplugin~/vstplugin~.dll and succeeded
vstplugin~ 0.6.1-pre1
```

This could be solved by ignoring `ERROR_MOD_NOT_FOUND` (126)  and continue searching.

I'd still like to know what exactly caused this change in the library loading logic...

> I can't reproduce on Linux.

Me neither. I think that's because `dlopen` can deal with relative paths (they are resolved to the current working directory).

**Comment by Spacechild1** [comment]
Ha! `[file pathpath]` now also returns a *relative* path.

Pd 0.55:
`././install/mingw64/vstplugin~`

Pd 0.54:
`C:/Repos/vstplugin/./install/mingw64/vstplugin~`

So it seems like `ce_dir` in `t_canvas_environment` is now set to a relative path. This is a breaking change that may have all kinds of nasty side effects!

**Comment by Spacechild1** [comment]
I found the offending commit: https://github.com/pure-data/pure-data/commit/3d44f7d91d7be54efd66352566e8881e7e24a65e

Previously we've passed the current working directory to `openit` when opening patches from the command line:
https://github.com/pure-data/pure-data/commit/3d44f7d91d7be54efd66352566e8881e7e24a65e#diff-7d5545e1dccaacdc0c420981df260eb10c15a9a25ca92424aac5149644126a08L317-L318

Now we just pass `.`:
https://github.com/pure-data/pure-data/commit/3d44f7d91d7be54efd66352566e8881e7e24a65e#diff-7d5545e1dccaacdc0c420981df260eb10c15a9a25ca92424aac5149644126a08R415-R416

I think the old behavior should be restored! Ping @millerpuckette

**Comment by Spacechild1** [comment]
I just went ahead and pushed a fix (https://github.com/pure-data/pure-data/pull/2333/commits/1905c1cadfb297b4c824e21c89a9dc247deddc4a) to develop.

**Comment by millerpuckette** [comment]
Ouch.  What I would like to do is remove any dependence on the current working directory from which either Pd or its GUI is started.  Things can reasonably be searched for relative to Pd's location, to whatever patch that tries to open a file, or to directories in the global or patch-specific search path.  However, obviously, I didn't do it right if things are getting loaded with CWD-relative paths.

**Comment by millerpuckette** [comment]
I'll look at Christof's patch when I have time later today... but please try to avoid using getcwd() or the like and stay relative to something indendent of CWD :)

**Comment by Spacechild1** [comment]
I basically just restored the previous behavior of `pd -nogui`.

When starting Pd from the GUI, this would only have any effect if you put `-open` directives into the startup flags. (Who does that?) In that case, you probably want to use absolute paths anyway.

**Comment by millerpuckette** [comment]
Anyhow, even though (1) Pd really shouldn't ever be sensitive to the CWD it is started in, (2) it's exactly compatible to simply use CWD in place of "." which has always meant CWD.  So the patch (in develop) is fine, and sometime later we might want to add a warning message if a patch is opened which is not written independently of CWD.  Note that ".." in a declare means parent directory WRT the patch (or I think any directory in the path), which is inconsistent with having "." mean CWD.  This is all my fault, dating from 1997 or so.
To answer a question above: the reason for sending CWD from the GUI was that, if we're running on bare metal with the GUI on a different machine, we might not have a local filesystem at all.  Back when Pd only used a few system calls this made sense - you could run it on a coprocessor, like the old Max/FTS.  I don't think anyone ever did this though.

**Comment by Spacechild1** [comment]
> Anyhow, even though (1) Pd really shouldn't ever be sensitive to the CWD it is started in, 

You are absolutely right when we talk about things *inside* Pd. In fact, Pd usually does *not* consider the CWD.

However, there is a weird exception: when I make a new (unsaved) document, it uses the CWD as the canvas path; as a consequence, relative paths will be successfully resolved to the CWD, simply because it happens to be in the canvas search paths. (The GUI sets `filenewdir` to `[pwd]` by default and passes that to the `menunew` command.)

Now, in the case of `pd ./foo.pd`, we basically ask Pd to open a document. Here I definitely expect the relative file path to be resolved to the CWD, just like when I do `nano ./foo.pd`. (If Pd can't find the file in the CWD, it will continue in the search paths, which some may regard as a feature, others as a bug :)

>  Note that ".." in a declare means parent directory WRT the patch (or I think any directory in the path), which is inconsistent with having "." mean CWD. 

AFAICT `./foo` is really the same as `foo`. It does *not* mean CWD. I don't see any inconsistency between `.` and `..`.

> (or I think any directory in the path)

This.

> To answer a question above: the reason for sending CWD from the GUI was that, if we're running on bare metal with the GUI on a different machine, we might not have a local filesystem at all. Back when Pd only used a few system calls this made sense - you could run it on a coprocessor, like the old Max/FTS. I don't think anyone ever did this though.

Thanks for the lore :)
