### ISSUE TITLE
Patch loaded from command line always shows scrollbars

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#2335]
When loading a patch from command line with `-open mypatch.pd`, the main window of the patch (almost) always shows scrollbars even if they're not necessary. If there is a margin between content and window content, it suffices to resize the window a tiny bit to make them disappear. 

[scrollbars.webm](https://github.com/pure-data/pure-data/assets/333373/472a7c17-8eed-4614-b181-77c3f12e5416)

This is on Linux (Ubuntu 22.04) with current master (5e079f6625). This is a regression since 0.54.

**Comment by umlaeute** [comment]
hmm, i cannot reproduce this right now (neither with current master @ c0f1664bbf600c9e7d27d2b5defa806f7bd1474a, nor with 5e079f6625e53460a5434d60a73feb8200924add)

**Comment by reduzent** [comment]
It's still happening with master@c2d65103 (0.55-2test1), quite consistenly (more than 9 times out of 10), with this patch:

```
#N canvas 0 32 508 207 12;
#X obj 30 23 cnv 20 300 150 empty empty empty 20 12 0 12 #e0e0e0 #404040 0;
```
 started like this:
 
```
pd -noprefs -open Pd/trigger-scrolllbar.pd
```

Interestingly (or expectedly), the scrollbars do not appear when the patch is an empty canvas. It seems it is related to the boundary calculation which probably is only triggered if there are objects at all. 

Also interestingly,  it happens only when I invoke `pd`. However, when I launch it with the `pd-gui` skript, the scrollbars stay hidden (when it's not necessary to show them):

```
pd-gui -open Pd/trigger-scrolllbar.pd
```

(Apparently, `pd-gui` doesn't understand many flags that `pd` understands, thus no `-noprefs`)

**Comment by reduzent** [comment]
BTW: This is on Ubuntu 24.04 (wayland) if that matters

**Comment by reduzent** [comment]
It happens also with Pd 0.55.1 from bookworm-backports on my Raspberry Pi 4, through X tunneled through ssh:

```
ssh -Y pi@heidelbeeri.local puredata -open trigger-scrollbars.pd
```

**Comment by umlaeute** [comment]
it's obviously triggering a race condition
- when started via `pd-gui`, the GUI is always fully initialized before Pd connects
- when started via `pd`, the GUI might not be ready.
  commands received by the GUI might overtake commands previously received (but taking too long). afair, we cannot really force flushing the commands, without sacrifying the bit of performance we have...
