### ISSUE TITLE
[readsf~] cannot search audio files in paths from [declare -path] 

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#234]
Hi, I'm on Pd-0.48

I downloaded some reverb patches from Tom Erbe and they came with some sound files. see below

<img width="418" alt="screen shot 2017-10-14 at 13 10 25" src="https://user-images.githubusercontent.com/5360142/31577232-24eb6d52-b0e1-11e7-823d-14db12850e5c.png">

 I wanted to use an external abstraction I have to load the sound files from this patch. The abstraction is from my library called "else", which is installed in the search path under Pd/Documents/externals/else, see below

<img width="450" alt="screen shot 2017-10-14 at 13 09 45" src="https://user-images.githubusercontent.com/5360142/31577244-52def3e6-b0e1-11e7-88b2-441195fd212e.png">

Also note that I have another path there just for sound files (Pd/Documents/sounds), but instead of dragging the audio files that came from Tom Erbe there, I thought I'd just use [declare -path ../] to load the parent folder to Pd's search path and load these sound files from within my external abstraction.

Well, it didn't work... 

And I confirmed the issue only concerns [readsf~]! Another abstraction based on [soundfiler] works just fine.

**Comment by porres** [comment]
this seems to be a bug with [readsf~] actually... not [declare]!

[readsf~] is the object I'm using inside my abstraction to load the sound files.

**Comment by porres** [comment]
yes, I confirmed this!

if I'm using [soundfiler] instead of [readsf~], it works! 

so... the issue actually concerns [readsf~], I'll change the title and edit the first message

**Comment by Ant1r** [comment]
Maybe readsf_open() (in audio thread) could call open_soundfile_via_canvas() and store the file descriptor, which then would be used by child thread in a safer way?
[soundfiler] uses open_soundfile_via_canvas().

**Comment by umlaeute** [comment]
`open_soundfile_via_canvas()` is very much thread-unsafe, so it cannot be used in the reading thread.

simply opening a new soundfile is non-realtime safe, so calling the actual `open` function in the audio-thread is not a realy option either.

**Comment by Ant1r** [comment]
So maybe we should think of a thread-safe version of canvas_open(), I presume without using gensym() ?

**Comment by umlaeute** [comment]
as discussed with @reduzent recently on IRC, one possible solution is to add a single object that resolves file-names via the canvas-paths. then pass the absolute filename (as returned by that object) to `[readsf~]`.

something like (assuming the name was `canvasfile`):

~~~
[symbol foo.wav(   <-- file to find
|
[canvasfile]       <-- searches for "foo.wav" in all search-paths
|          |
|          [1\     <-- indicates whether the file has been found
|
[open $1(
|
[readsf~]
~~~

This allows the user to break the realtime safety (or resolve the filename before DSP is being started)

**Comment by porres** [comment]
Hi, sorry, but why is this marked as wontfix, I don't get it, is there a technical issue that prevents this from being fixed? What is it?

And anyway, I was already using that sort of solution.

**Comment by reduzent** [comment]
I'm happy to see that there is already an issue about this. I think why IOhannes marked this as 'wontfix' is because it's unfeasible to do all the path checking in a realtime-sensitive thread. From my limited understanding, you cannot use the function that is usual used for this, because it is not thread-safe. You'd have to do it separately in the readsf~ thread but actually you shouldn't do any syscalls (with expectedly long return time) in such a thread. So checking for files in a bunch of paths is a no-go. Since there is no way to fix this, it is marked as 'wontfix'. 

The better way to deal with this is what IOhannes proposed two comments ago. So maybe you could open another feature request about an object to look for files in declare/configured searchpaths (if IOhannes hasn't done so already).

**Comment by umlaeute** [comment]
@porres the (terse) explanation of the technical issue that prevents the fix can be found in https://github.com/pure-data/pure-data/issues/234#issuecomment-337183458

**Comment by porres** [comment]
> So maybe you could open another feature request about an object to look for files in declare/configured searchpaths (if IOhannes hasn't done so already).

Well, yeah, my external solution wasn't really searching declare/configured search. I see now how a solution for this problem with a new [canvasfile] object is a good fix. But then "won't fix" means there's nothing to be done in code level for [readsf~], but this doesn't mean we won't be able to fix this in some other way.

So yeah, a new object request than as a fix for this could be opened in a seaparate issue I guess.

**Comment by porres** [comment]
It seems there are plans to fix this after all, see: https://lists.puredata.info/pipermail/pd-dev/2019-04/021939.html

we could maybe just reopen this issue then

**Comment by Spacechild1** [comment]
reopening because Miller seems to have plans to fix this.

By the way: I think the fix could simply be to have a common RW lock for all (canvas) search paths. Search paths are rarely added but frequently read. Will have a closer look.

**Comment by porres** [comment]
Now that this is reopened, can we mark it as a bug fix rather than "won't fix"?

**Comment by danomatika** [comment]
Any updates on this?

**Comment by Spacechild1** [comment]
For technical reasons, the "open" method for `[readsf~]` requires an absolute file path. With the introduction of `[file which]`, there is now a trivial workaround. It just needs to be documented as such. (Maybe it already is, I can't check atm)

**Comment by danomatika** [comment]
> For technical reasons, the "open" method for `[readsf~]` requires an absolute file path.

Mmm I don't think so. The help patch itself uses a relative path:

![Screenshot 2023-08-11 at 1 57 05 PM](https://github.com/pure-data/pure-data/assets/480637/791dcd8e-ab42-436c-96c1-47ff03c0812a)

> With the introduction of `[file which]`, there is now a trivial workaround. It just needs to be documented as such. (Maybe it already is, I can't check atm)

I think this is the right answer. I agree that having consistent behavior between `readsf~` and `soundfiler` is desired, however if this is not something we can easily do for now, we should *definitely* point this out with an easy-to-use solution in the help patch.

**Comment by Spacechild1** [comment]
> Mmm I don't think so. The help patch itself uses a relative path:

Ah, relative paths do work, but only relative to the patch containing the `[readsf~]` objects, which is not particularly useful for abstractions.

Also,  I think I meant `[file patchpath]`, not `[file which]`.

Anyway, the help patch should explain how to open files relative to the patch search paths.

**Comment by porres** [comment]
ok, gonna say it searches for the folder relative paths and that you can use [file] to help out, but hopefully we'll still fix this, right?

**Comment by porres** [comment]
well, actually, this one DOES search for the user added paths, the problem is just with [declare] as the title suggests

**Comment by porres** [comment]
> well, actually, this one DOES search for the user added paths, the problem is just with [declare] as the title suggests

anyway, using [file which] in this case helps because it can search paths from [declare], so we can use it, and not [file patchpath]!

> Ah, relative paths do work, but only relative to the patch containing the [readsf~] objects, which is not particularly useful for abstractions.

This is true for everything not just this object. so I don't see why we need to say it in this help file, so I can't see why suggesting [file patchpath] here.

Anyway, I really consider this a "bug" (not a feature request), and all I could do is document this bug with the current suggestion.

**Comment by porres** [comment]
doing this 

![Screen Shot 2023-08-25 at 16 20 42](https://github.com/pure-data/pure-data/assets/5360142/5cbd5468-5639-4d50-bd0a-6d7b86677eb6)

**Comment by danomatika** [comment]
I don't feel that *every* inconsistency has to be qualified as a *bug*. In this case, documenting it would be enough ala:

>Note: [readsf~] cannot find files in folders added via a [declare] object and it is recommended to use [file which] to get absolute paths which can be used with open. Paths added to the search path via preferences do work.

For some such "bugs" which 1. have reasons to be the way they are and 2. are not likely to change for said reasons in the future, I don't find it ultimately useful to name them bugs nor to keep the issue open forever. Best to document the different behavior and move on.

**Comment by porres** [comment]
![Screen Shot 2023-08-25 at 17 22 26](https://github.com/pure-data/pure-data/assets/5360142/4290af78-8468-402c-b43c-fd92e986472c)

**Comment by porres** [comment]
I would still like to have this issue open unless we have a proper rejection that such a feature will never be implemented for whatever reason. I know it requires some work, but it's not like it can't be done and Miller has mentioned this is in his "to do" list... so...

**Comment by porres** [comment]
this has been finally fixed
