### ISSUE TITLE
arrays not fully showing values

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#235]
Hi, tried loading a 10 min audio into an array, and at about 3/5 of it, it just doesn't show anything. See picture below (testing it with cyclone/buffer~ which is a vanilla abstraction).

<img width="965" alt="screen shot 2017-10-15 at 14 52 37" src="https://user-images.githubusercontent.com/5360142/31587033-d2cb8b50-b1b8-11e7-86d1-bdda63988e93.png">

**Comment by Lucarda** [comment]
This might be because the soundfile is more than 16777216 samples in lenght.

https://lists.puredata.info/pipermail/pd-list/2017-02/118146.html

**Comment by porres** [comment]
I don't think that's related at all, and where the points stop being visualized are way over 16777216 points

**Comment by umlaeute** [comment]
try closing the `$0-buffers` subpatch and reopen it.

table updates get throttled

**Comment by fdch** [comment]
Well,

i run into this on OSX 10.11.6

If you simply create an empty array like 
[array define array1 2.646e+07], the value line is shown up to about 1.677e+07. 


fdch.github.io/tv

**Comment by porres** [comment]
> If you simply create an empty array like
> [array define array1 2.646e+07], the value line is shown up to about 1.677e+07.

Yeah, I was wrong, sorry, I thought it was way over, but it wasn't, it's stopping right at that value, so it can't go over it... though the actual discussion in that link was about indexes not about visualizing it.

> try closing the $0-buffers subpatch and reopen it.
> 
> table updates get throttled

I had tried that before, it just doesn't work, I don't think it can ever visualize such long tables, though the samples are still right there and you can even listen to them

Well, I guess that involves bit precision and requires some deep surgery, huh?

**Comment by Lucarda** [comment]
Yeah the samples are there but you cant access them with [tabread] because the “control level” cant handle bigger numbers than 16777216. 

I think that IOhannes attempt to “put to fly” an double-precision Pd is becoming a “must”.

**Comment by porres** [comment]
I don't see how you cant access them with [tabread] is related to this. And you could fix that with an onset thing like in [tabread4~]

**Comment by Lucarda** [comment]
If you do a +1 counter it will stop at 16777216, no bigger number, so no further index for [tabread].

**Comment by porres** [comment]
sure, I'm totally aware of that

**Comment by Lucarda** [comment]
?

So how you access samples beyond the 16777216 limit with [tabread]?

What result you get if you add 2 million to 16 million in Pd?

Is it correct?

**Comment by porres** [comment]
> So how you access samples beyond the 16777216 limit with [tabread]?

I never said I could. And I'm sorry, but I already said I consider this a separate issue, can we not discuss this on this thread? I just feel this si turning into a separate discussion.

What we know is that it seems the arrays stop displaying points at around 16777216, can we discuss that and ways to fix that?

cheers

**Comment by Lucarda** [comment]
IMO this relates to “Double-precision” Pd.

I'm most interested in being able to handle big tables via [tabread] than actually seeing them displayed, but that me …

: - )

**Comment by porres** [comment]
> I'm most interested in being able to handle big tables via [tabread] than actually seeing them displayed, but that me …

open an issue/request about it ;) - it could easily be done with something like the onset inlet as in tabread4~ like I already said

**Comment by Lucarda** [comment]
I think being able to handle bigger numbers accurately is best than a onset, for many reasons.

I could be wrong wanting “Double-precision” but since IOhannes has done some preliminary work on that...

Why not?

Is a solution for your issue and also for mine. Probably to others too.

**Comment by umlaeute** [comment]
@Lucarda while I totally agree that we need double-precision, I also agree with @porrres, that this (pure-data/pure-data#235) is the wrong place to discuss this.

(even if the two things are related, as suggested by the suspicious number of samples; but I'm pretty sure that having double-precision numbers in Pd will not magically make tables display more values; otoh the tables-lacking-values problem can most likely be solved without having to switch Pd to double-precision)

**Comment by Lucarda** [comment]
Sorry half-off-topic here:

@umlaeute,

Do you have a wip, branch or PR for double-precision?

I don't know C, can I contribute with greps?

**Comment by umlaeute** [comment]
turns out it was indeed related to floating point precision.

A double-precision Pd would not exhibit the problem (because of a side-effect), but even a single-precision Pd can have this fixed (which is what  a49129c attempts to do)
