### ISSUE TITLE
[text insert] unexpectedly unescapes `\;` and `\,`

### ISSUE THREAD

**Issue by ben-wes** [pure-data/pure-data#2354]
these 2 versions both lead to separate lines in [text]. i would expect the escaping to be preserved in just 1 entry when using `text insert` though:

```
[list message 0 \; message 1 \; message 2 \;(
|
[text insert foo]
```

```
[list message 0 \; message 1 \; message 2 \;(
|
[text fromlist foo]
```

maybe my expectations are wrong - and probably, this can't be easily fixed since it would break existing behaviour. but is this designed like this on purpose? seems related to #1262 - but i currently can't seem to wrap my head around the logic of escaping/unescaping here.

**Comment by ben-wes** [comment]
since the aim here was to store text for other [text] objects in separate lines, a workaround i use now is to store the fudiformatted [text tolist] output. so the actual issue is solved for me. i'll leave this open for feedback anyway for now.

**Comment by ulioidle** [comment]
The bug is actually in [text define], #1951, [text get] and [text sequence] will get the proper message assuming you don't open the editor and save the text. 
![Untitled](https://github.com/pure-data/pure-data/assets/8304564/b05bf461-5690-4667-bc76-af43e90835c3)

**Comment by ulioidle** [comment]
This is the text editor bug #1951 [text get] and [text sequence] will read things properly despite the editor displaying it improperly, assuming you don't do a save from within the editor. 
![Untitled](https://github.com/pure-data/pure-data/assets/8304564/5d01d4c5-f716-4ed3-9231-67005b85e070)

**Comment by ben-wes** [comment]
@ulioidle cool, thanks a lot for mentioning this! that makes the issue here obsolete.

i didn't consider the option that it might be a display issue. didn't even test the `get` after i saw the contents.
