### ISSUE TITLE
Array List view issues 

### ISSUE THREAD

**Issue by alcomposer** [pure-data/pure-data#2362]
Array list view is really powerful, but it has two bugs (checked with Pd 0.55.5 and W11):

1) Array list viewport does not grow when the window is resized, to show more values.
2) When moving the column at the top, the user can drag the column past the right (Less of an issue than 1, as it does snap back when drag ends)

Please see screen capture for visual:

https://github.com/pure-data/pure-data/assets/12004932/0e0f75e6-db50-4f1a-b14c-b72ec1a129ec

**Comment by porres** [comment]
yeah, '2' is not a big deal

but '1' (the fact that resizing the window vertically doesn't show more values) is terrible and must be fixed.

both act the same way in macOS by the way

**Comment by alcomposer** [comment]
IIRC Linux has more substantial bugs with this window. But I'm unable to test ATM.

**Comment by umlaeute** [comment]
'2' is not only "not a big-deal", but it is a non-issue.

'1' should be fixed, but if a heavy user "never felt the need to resize to catch this issue", then i think that "is terrible and must be fixed" are too strong words.

**Comment by porres** [comment]
Indeed as I heavy user I almost never had to check contents in list view :) and when I did it I never felt like expanding and would rather scroll down.

anyway, thanks for fixing it
