### ISSUE TITLE
pd's cursor issues on linux

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2366]
@timothyschoen mentioned that the cursor change for abstractions/guis in run mode (pointing the arrow up) doesn't work on Linux.

Is this a known issue? Is there something we could do about it?

I just documented this on the manual and if it can't work like that across platforms I need to say it,

**Comment by umlaeute** [comment]
not sure what you (or timothy) are talking about, so you would need to add some details.

(having that said, i think in general one shouldn't "over-document" what one might think is a defined behaviour)

**Comment by porres** [comment]
> not sure what you (or timothy) are talking about

the fact that the cursor changes for abstractions/guis in run mode when passing the mouse over it, where the arrow changes from being diagonally tilted to fully pointing up.

**Comment by timothyschoen** [comment]
https://github.com/pure-data/pure-data/assets/44585538/3bb0aef2-17e6-438b-8542-b0ac55949750

Here's what happens for me on Fedora 40 with GNOME, with Pd installed from Flathub. Cursor changes work for outlets and resizing, but not to indicate subpatches are clickable. I'm using the Adwaita cursor theme.

**Comment by umlaeute** [comment]
that's because for the *Adwaita* cursor theme, the `left_ptr` and the `arrow` cursors look the same.

i do not really consider this a problem of Pd.

**Comment by porres** [comment]
while we're at it, let ask how does one choose a cursor theme and is it the Adwaita the default choice in this case?

**Comment by porres** [comment]
in this case can the user (tim) choose another in some very very reasonably easy way?

**Comment by timothyschoen** [comment]
Yeah, I could change it myself! The only problem I see here is that Adwaita is the default theme for many popular Linux distributions. But yeah, @umlaeute is correct to say that it's their problem in that case.

**Comment by porres** [comment]
Since i described things in the manual, i feel compelled to address this issue over there and mention this might happen. Can you give me an example of a theme that works?
