### ISSUE TITLE
request: save subpatch and turn it into an abstraction

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2367]
I got this idea from MAX, it seems it can do it

it'd be nice to have a command that saves a subwindow and its subwindows as a separate file, which would easily make it a loadable abstraction.

I won't elaborate too much so I can leave room for other ideas on how this could go

**Comment by ben-wes** [comment]
i like the idea - although it's not a huge workaround to copy/paste subpatches to new patches and then just replace the [pd ...] with the newly created abstraction. but sure, this would save a few steps!

so would that mean that this replacement is also done automatically?

**Comment by porres** [comment]
hmmm, I guess this is related to https://github.com/pure-data/pure-data/issues/1099

and, by the way, I can't find patcherize anymore on deken. I can't remember how it works now :/

and this brings us to this other request that was discussed a few times, to also be able to use a command to turn a selection of objects into a subpatch. I was actually thinking about that and then with this other feature one could also save it as an abstraction.

**Comment by porres** [comment]
yeah, I should just close this cause it's what patcherize does, but I downloaded it and I couldn't either turn it into a subpatch nor an abstraction as it is just flawed...

**Comment by umlaeute** [comment]
if patcherize doesn't work for you, you can always create an issue at https://git.iem.at/pd/punish/-/issues
