### ISSUE TITLE
[declare -stdpath] doesn't search ~/Documents/Pd/externals

### ISSUE THREAD

**Issue by Ant1r** [pure-data/pure-data#237]
on Linux at least:

even if a patch contains [declare -stdpath foo], Pd can't create [bar], while there is a ~/Documents/Pd/externals/foo/bar.pd.
This happens even if  ~/Documents/Pd/externals is declared into preferences.

Since by default Pd now downloads new externals to ~/Documents/Pd/externals (which I personally like), these externals are unusable through [declare], i.e you HAVE to declare their full absolute path into preferences (which I don't like...).

Actually I think [declare -stdpath] should try to complement every user search path (declared in preferences).

This is also related to PR #205, which solves that but only if you [declare -path foo] (it still doesn't work with [declare -stdpath]).

**Comment by porres** [comment]
see https://github.com/pure-data/pure-data/pull/205

**Comment by porres** [comment]
oops, I see you know about it now... let me check what you mean

**Comment by porres** [comment]
Ok, I see what you mean now. Well, in short, I can say I already tried selling this idea that the Documents/Pd would be considered a -stdpath and you can see this in a closed PR I had attempted to make it happen, but it didn't https://github.com/pure-data/pure-data/pull/139 - this has also been reffered to in https://github.com/pure-data/pure-data/pull/205 and you might have missed. I also made several attempts to raise awareness to this discussion on the Pd list, which you may also have missed.

Anyway, if you don't feel like reading 100+ messages in https://github.com/pure-data/pure-data/pull/139 or search the Pd list, the bottom line is that -stdpath has always been, apparently, meant for only the "extra" folder, and not anything else. Though somehow it got polluted with other options, which were even described as the "way to do it".

Well, currently, I'm now hoping to make things clear and avoid further issues and confusion like you're having. So I opened a new Pull Request related to this issue right here https://github.com/pure-data/pure-data/pull/183

When this is settled, I hope I can publish a manual on how to deal and manage externals and make this clearer for everyone.

**Comment by Ant1r** [comment]
Yes indeed, I missed a large part of #139 debate, and finally I agree the present issue is somewhat redundant with #139 and #205, so I'm closing it. 
But I really see the current behavior as a bug, and I vote (again) for #205 to be adopted, which would resolve all these difficulties and greatly simplify externals management for every kind of user.

**Comment by porres** [comment]
> I really see the current behavior as a bug, and I vote (again) for #205 to be adopted, which would resolve all these difficulties and greatly simplify externals management for every kind of user.

Sure, as the responsible for the (long) discussion in https://github.com/pure-data/pure-data/pull/139 I can say this also came up there as a bug, hence the https://github.com/pure-data/pure-data/pull/205 PR emerged from that. So things are moving on and I think it'll happen.

Now, I wonder how you feel about https://github.com/pure-data/pure-data/pull/183 - which is also tightly related to this as I see it. And I'm not so sure what'll come out of that. If you have anything to add to that discussion, please do so.

thanks
