### ISSUE TITLE
route w/ single argument prints error when setting float to symbol or symbol to float

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#238]
The route help patch says:

>With zero or one argument, route sprouts an inlet to set the arument (which may be float or symbol).

However, I've noticed the following error when sending a symbol to the second inlet to a route with a float argument ie. [route 4] or no argument ie. [route]:

>inlet: expected 'float' but got 'symbol'

and the opposite when sending a float to the second inlet to a route with a symbol argument ie. [route foo]:

>inlet: expected 'symbol' but got 'float'

If this is expected behavior, maybe the help patch should explain in a little more detail? Otherwise, perhaps this can be fixed.

**Comment by umlaeute** [comment]
I'd say that this is (currently) expected behavior (and the help-patch ought to clarifiy this).

otoh, allowing a single-arg `[route]` to be able to switch from `symbol`-mode to `float`-mode might be a useful feature on it's own, so :+1:

**Comment by danomatika** [comment]
I'm fine with following an establish type when setting an argument, but I think it should allow either type if there is no argument aka "0".

**Comment by porres** [comment]
this has been explained in the current help file, can we close this?

**Comment by umlaeute** [comment]
i think so. thanks for improving the helps
