### ISSUE TITLE
Microsoft-Deployment-Toolkit Deployment

### ISSUE THREAD

**Issue by bentalm** [pure-data/pure-data#2387]
Hello,

I try to deploy silently puredata with MDT but it doesn't work. It keeeps returning an unexpected exit code 2. I saw that we can run the install silently with /S argument which works perfectly if I launch the installation locally.
If I launch the deployment with MDT and without any argument, it also works. So I think that maybe I missed some arguments to launch it correctly with MDT. I also tried with /ALLUSERS because it's something that the installer asks but it keeps returning the same error 2.

Do you have an idea ? Do you have a list of all arguments for your installer ?

Thanx for the help.

**Comment by umlaeute** [comment]
what's MDT?
please provide more context and what exactly you are doing.

**Comment by bentalm** [comment]
It's Microsoft Deployment Toolkit (part of Windows Deployment Service). Basically for automation of OS and applications installations. We provide the exe (or the msi) and the command line (with the silent argument of course) and that's it.

**Comment by umlaeute** [comment]
> We provide the exe (or the msi) and the command line (with the silent argument of course) and that's it.

who is "we"?

I'm afraid, if you want people to spend their volunteer time to help with your problem, you ought to be more specific.
to repeat myself:
*please provide more context and what exactly you are doing.*

with "what exactly you are doing", i mean just that: a step-by-step walkthrough what you are doing.
among other things:
- where did you get which exe (or msi).
- which commands did you type
- what else did you do

**Comment by umlaeute** [comment]
@ping Lucarda

**Comment by bentalm** [comment]
We, as I, as everyone who use MDT...I described the general way of using it.
I provide the exe pd-0.55-0.windows-installer.exe to the task sequence I created, and secondly I also provide the command pd-0.55-0.windows-installer.exe /S but it returns the error code 2.

I tried with pd-0.55-0.windows-installer.exe /S /AllUsers but it's the same.

For a start I just wanted to know if someone can provide a list of all existing arguments of the exe cause I'm well aware that you do not have to know WDS/MDT but I repeat myself : it's just a tool from Microsoft which automates installations with the help of an executable (or msi), and a command line, that's it.

I successfully deploy dozens of software with MDT but I can't find a way to have pure data goes right whereas the silent installation runs smoothly locally...

**Comment by Spacechild1** [comment]
> For a start I just wanted to know if someone can provide a list of all existing arguments of the exe

The installer is built with NSIS, so you can look in the NSIS documentation. One possible issue could be that the installer requires Admin privileges.

**Comment by umlaeute** [comment]
so where's that ominous "task sequence" you created?
and did I already ask, *where did you get which exe (or msi)?*

as @Spacechild1 mentioned, the options to the installer are documented at https://nsis.sourceforge.io/Docs/Chapter3.html#installerusagecommon

**Comment by Spacechild1** [comment]
> but it returns the error code 2.

I think this just means "installation aborted by script", see https://nsis.sourceforge.io/Docs/AppendixD.html.

Can you try running your command line with Admin privileges?

**Comment by umlaeute** [comment]
one thing that might be worth noting, is that the W64 installer is a `PE32` executable (that is: x86_32)

**Comment by bentalm** [comment]
> so where's that ominous "task sequence" you created? and did I already ask, _where did you get which exe (or msi)?_
> 
> as @Spacechild1 mentioned, the options to the installer are documented at https://nsis.sourceforge.io/Docs/Chapter3.html#installerusagecommon

Yes I just tried the D argument to add another path to install but same problem...
For the exe, I obviously get them in the download section of puredata website





> > but it returns the error code 2.
> 
> I think this just means "installation aborted by script", see https://nsis.sourceforge.io/Docs/AppendixD.html.
> 
> Can you try running your command line with Admin privileges?

The fact is that it's already running with admin privilege. I mean I can't really choose this during the creation of the automation but the LiteTouch.vbs script generated by MDT is running with admin privilege to launch all the deployment of all apps. And by way, the real obscure thing is that the installer is well launched if it's not silent ! And of course if I do the rest manually (basically clicking next) everything is ok and I have no return code from mdt.

**Comment by Lucarda** [comment]
> one thing that might be worth noting, is that the W64 installer is a PE32 executable (that is: x86_32)

@bentalm can you test if this is causing the issue.

use this file as the installer:

https://nc.nubegris.com.ar/index.php/s/J5fPt7Nd4nksq7r

**Comment by bentalm** [comment]
Same with this installer. I guess there is something with the installer that MDT doesn't like. It happens sometimes with others installers but with some others error code the installations are nonetheless completed. Not here.

**Comment by umlaeute** [comment]
it's probably possible (for someone in the know, like @Lucarda ) to add a logging facility to the installer, so we see how far it gets.

i don't even know how you get the errorcode of a program that detaches itself from the cli.
probably it's as simple as the following (but here it only runs for 1 second or so, and returns '0'; but then, Pd is successfully installed)
```cmd
start /wait pd-installer.exe /S /D=C:\temp\Pd\
echo %ErrorLevel%
```

---

as a sidenote, these questions are still un-answered:
- please provide [...] a step-by-step walkthrough
- which commands did you type?
- so where's that ominous "task sequence" you created?

since i think  i've asked them multiple times, using different wording, it seems you are holding back on purpose.
but really: this is not about stealing your company secrets. it's about being able to reproduce the problem

so once more: can you please share literal transcriptions of the things you do and the things you run?
preferably in a minimal form.

**Comment by bentalm** [comment]
I'm sorry but I don't hold anything back. It's just that I can't explain the whole MDT thing. I already anwer here : 

> I provide the exe pd-0.55-0.windows-installer.exe to the task sequence I created, and secondly I also provide the command pd-0.55-0.windows-installer.exe /S but it returns the error code 2.

> I tried with pd-0.55-0.windows-installer.exe /S /AllUsers but it's the same.

With MDT, you create a deployment and inside of it you create a task sequence where you can capture a whole system to redeploy it, where you can install the system you want by preparing it with all options you want. You create you own image and deploy it to the machine you want with PXE boot, like FOG if you want.

But I don't use it that way. In a deployment yo ucan create a task sequence just to install apps, in bulk. In that way you go on the machine you want and connect to the network share and start the script LiteTouch.vbs, select the task sequence you prepared, select the apps you want to install on this machine and here it goes.

I really can't explain it better because of time and laguage, but nevermind, I wanted to ask in case of someone would have been confronted to the same issue but it seems not so I will find another solution, go through the GUI manually on each machine or take time to prepare a GPO to deploy the portable version. I'll see.

You can close this ticket if you want.

**Comment by bentalm** [comment]
Ok I guess I found the reason why. I launched the installer through MDT without the /S and went trought the GUI manually and it seems that the installer doesn't work with UNC path ! But it asks if you wanna force it, which I had to do it twice and then the installation was ok.

So I guess that's why it doesn't with silent install through MDT.

**Comment by umlaeute** [comment]
i found a very old forum entry on using NSIS installers with UNC paths: https://nsis-dev.github.io/NSIS-Forums/html/t-252885.html
maybe this helps.

i think it would also help, if we could see the actual commands being run via your vbs script.
e.g. when you say that the command is run as `pd-0.55-0.windows-installer.exe /S`, I do not see any UNC path (actually, I do not even see *any* path).
so where does the UNC path come from?
- is the problem, that `pd-0.55-0.windows-installer.exe` is located on a UNC path?
- or are you trying to install to a UNC path (and how does the installer know)?

**Comment by umlaeute** [comment]
so i guess the solution is to copy the installer to the harddisk first, and run it from there

**Comment by bentalm** [comment]
So I can't go with MDT which was my point ;)
Nevermind, thanx for the help, I close the ticket now !

**Comment by Lucarda** [comment]
@bentalm can you try this file:

https://nc.nubegris.com.ar/index.php/s/AqzBf7ZtpCzDNmK

it has `AllowRootDirInstall true` which supports UNC paths. Lets try it.

**Comment by bentalm** [comment]
> @bentalm can you try this file:
> 
> https://nc.nubegris.com.ar/index.php/s/AqzBf7ZtpCzDNmK
> 
> it has `AllowRootDirInstall true` which supports UNC paths. Lets try it.

Thanx for trying but nope, still the same error :-/

**Comment by umlaeute** [comment]
> it has `AllowRootDirInstall` true which supports UNC paths. Lets try it.

afaict, this allows installing *to* a UNC path.
the problem betalm is facing, is that they want to install **from** a UNC path.

unfortunately, i cannot really test installing from a UNC path, as my SAMBA server is configured to not prevent direct execution of files, and I cannot change that right now.

bentalm then wrote:
> So I can't go with MDT which was my point ;)

i'm slightly astonished, that you cannot perform a simple file-copy with MDT.
what if i want my deployments to have a README.pdf on the user's desktop? surely there must be a way to achieve this without having to write an installer.
if you *can* copy a README.pdf to the user's (local) desktop directory, then surely you can also copy a `pd-0.55-0.windows-installer.exe` to, say, `C:\temp\`
and if you can do *that*, you should be able to run `C:\temp\pd-0.55-0.windows-installer.exe /S` instead of what you are currently running.

**Comment by bentalm** [comment]
Oh no you misunderstood me, I can't go with MDT "applications installation" part  but I certainly can find another way to achieve it. It's just that it takes more time to me, that's it.

But hey, thanx again !
