### ISSUE TITLE
Duplicate key binding events with non-US keyboard locale on macOS Tk 8.5+

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#239]
(@pierreguillot bringing this over from #213) 

It seems the creation shortcuts are being triggered twice when using a non-US English keyboard locale with newer builds of Pd and Tk 8.5+ on macOS. Switching to a US keyboard makes the issue go away, so it seems the problem lies with the binds and/or menu accelerators.

**Comment by danomatika** [comment]
Note: This is similar to the behavior found when using the buggy TK 8.5.9 included with macOS. Disabling the menu accelerators makes that go away, but is a less-than-ideal solution.

**Comment by pierreguillot** [comment]
If I create an array with cmd+shift+a, the array isn't created and I got this message in the console:
```
(Tcl) UNHANDLED ERROR: bad window path name ".gfxstub7ff604e54570"
    while executing
"wm transient $mytoplevel $::focused_window"
    (procedure "create_dialog" line 6)
    invoked from within
"create_dialog $mytoplevel $newone"
    (procedure "pdtk_array_dialog" line 7)
    invoked from within
"pdtk_array_dialog .gfxstub7ff604f153b0 array1 100 3 1"
    ("uplevel" body line 2)
    invoked from within
"uplevel #0 $docmds"
```
It doesn't happen using the menu. Do you think it's related to this issue? I can try to disable the menu accelerators but I don't know how to do. Can you explain me?

**Comment by Spacechild1** [comment]
@danomatika is this still relevant?

**Comment by danomatika** [comment]
I don't know. Maybe @pierreguillot can elaborate.

**Comment by pierreguillot** [comment]
I think it's still relevant:
- If I create a number box using cmd+shift+n, it creates two number box. The first one appears when the mouse is and the second one is still "attached" to the mouse so I can drag it and then I have to click again to "drop" it.
- If I create an array using cmd+shift+a, this message appears:
> (Tcl) ERREUR : bad window path name ".gfxstub100519dc0"
>   while executing
> "wm transient $mytoplevel $::focused_window"
>     (procedure "create_dialog" line 6)
>     invoked from within
> "create_dialog $mytoplevel $newone"
>     (procedure "pdtk_array_dialog" line 7)
>     invoked from within
> "pdtk_array_dialog .gfxstub100519e30 array1 100 3 1"
>     ("uplevel" body line 2)
>     invoked from within
> "uplevel #0 $docmds"
and the array properties windows is empty so it doesn't create the array. 

Everything works well if I use the menu but it's not optimal. 

- mac 10.14.6
- French keyboard
- Pd-0.50-2

**Comment by danomatika** [comment]
@pierreguillot Does it happen with this build?

http://docs.danomatika.com/pdbuilds/0.51/Pd-0.50-0-saveas-fix-tk867.zip

(I really hate TK some times...)

**Comment by pierreguillot** [comment]
Yes, it also happens.

**Comment by danomatika** [comment]
Is this still an issue with Pd 0.51-3? I hope it's fixed by using TK 8.6.10.

**Comment by pierreguillot** [comment]
Unfortunately, using the shift key triggers actions twice... (Pd 0.51-3 & Tk 8.6.10)

**Comment by umlaeute** [comment]
> Has anyone tried this with a Pd build using Tk 8.6.11?

Has anyone tried this with a Pd build using Tcl/Tk 8.6.**12**? (it's been released last week)

**Comment by umlaeute** [comment]
correction: i *does* happen With Tcl/Tk-8.6.12 on macOS-10.14 with a **French** keyboard layout. it does not happen with e.g. a German keyboard layout, which is non-US as well :-)

I guess the problem is somewhat related to numbers requiring <kbd>Shift</kbd> and similar quirks of the French layout

**Comment by umlaeute** [comment]
here's a little test-script in Tcl/Tk, that mimicks the binding done in Pd:

~~~tcl
set ::modifier "Mod1"
proc bind_capslock {tag seq_prefix seq_nocase script} {
    bind $tag <${seq_prefix}-[string tolower ${seq_nocase}]> $script
    bind $tag <${seq_prefix}-[string toupper ${seq_nocase}]> $script
}
bind_capslock all $::modifier-Shift-Key N {puts "W:%W k:%k s:%s K:%K A:%A N:%N"}
~~~

Pressing <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd> (on a french layout) only outputs a single line (so the problem sedems not to be in Tcl/Tk)
Pressing the same sequence in Pd, sends the `numbox` command twice.

After further investigation, it appears that:
- the first `numbox` command is sent from the **menu** https://github.com/pure-data/pure-data/blob/8049fa849e9ac728251715feae4db3c369904400/tcl/pd_menus.tcl#L251-L252
- whereas the second `numbox` command is sent from the *explicit keybinding* https://github.com/pure-data/pure-data/blob/8049fa849e9ac728251715feae4db3c369904400/tcl/pd_bindings.tcl#L100

**Comment by umlaeute** [comment]
@danomatika commented on Oct 24, 2017:
> Note: This is similar to the behavior found when using the buggy TK 8.5.9 included with macOS where the global patch keybinding _and_ the menu accelerator bindings are both called. Disabling the menu accelerators makes that go away, but is a less-than-ideal solution.

so as my test have shown, this is (still) exactly the same as "when using the buggy TK 8.5.9 included with macOS"

**Comment by umlaeute** [comment]
so after checking on [StackOverflow](https://stackoverflow.com/questions/69896172), the official solution seems to be to:
- either drop the explicit bindings on macOS (similar to what @danomatika  said about dropping the accelerators, i think this is less than ideal)
- OR filter out duplicate events

7595d27 has an implementation of the latter (with the advice given by upstream), that actually just throttles the events.
so far it seems to work nicely on macOS and i haven't encountered problems on Linux either.

**Comment by umlaeute** [comment]
side-note (directed at our French friends, e.g. @pierreguillot , @Ant1r ,...) it seems that while i can create objects and msgboxes with <kbd>⌘</kbd>+<kbd>1</kbd> resp <kbd>⌘</kbd>+<kbd>2</kbd> on a French keyboard, i fail to do so with floatgatoms/listgatoms/comments <kbd>⌘</kbd>+<kbd>3</kbd>..<kbd>⌘</kbd>+<kbd>5</kbd>.

is this a general issue with macOS? (those keystrokes do "something" that seems to be out of Pd's realm)

**Comment by Ant1r** [comment]
iirc, these shortcuts are already assigned by macOS (I seem to remember taking a lot of screenshots while trying to create float-atoms...), hence they are masked. I think you can de-assign them through the system preferences editor.

**Comment by danomatika** [comment]
@umlaeute Good catch with 7595d27. Thanks for digging into this.

This issue makes sense and is consistent with how native Cocoa apps function: setting an accelerator on a menu item in Xcode Interface Builder automatically calls the method bound to the menu item. Most Cocoa apps do not read or handle key events manually, but TK does, so it both catches the key events for the bind *and* the Cocoa menu accelerator also calls the bound method.

I believe I added explicit menu accelerators when I first overhauled the GUI for macOS, so the root of this is my fault perhaps.

**Comment by umlaeute** [comment]
antoine wrote:
>  iirc, these shortcuts are already assigned by macOS 

ah yes thanks for the hint. disabling the Screenshot shortcuts in the System Preferences did the trick.

dan wrote:
> I believe I added explicit menu accelerators when I first overhauled the GUI for macOS, so the root of this is my fault perhaps.

no. the root cause is that "menus work differently on macOS to how Tk really expects".
i think it was a very good idea to add menu accelerators on all platforms.

**Comment by 60-hz** [comment]
I noticed that with pd 0.52-1 the duplicate key binding under OSX is back (OSX 10.15.4). It was fixed with 0.52-test4.

**Comment by umlaeute** [comment]
@60-hz given the [minimal difference between the two versions](https://github.com/pure-data/pure-data/compare/0.52-0test4%E2%80%A60.52-1-really) i think this is highly unlikely - unless we managed to ship the wrong Tcl/Tk version again...

- make sure you are really running `Pd-0.52-1-really`
- what is the Tcl/Tk version reported in the Pd-console (you have to set the loglevel to "***4** all*")

**Comment by 60-hz** [comment]
@umlaeute my mistake, I was using the wrong pd version.!It looks ok at least with french keyboard, sorry for the noise.

**Comment by danomatika** [comment]
@60-hz False positive or not, I appreciate you double-checking this.

**Comment by 60-hz** [comment]
@danomatika Sure, I confirm that it works, no more duplicate key with Pd-0.52-1-really and Tk 8.6.12 under OSX.
