### ISSUE TITLE
 Inconsistent positioning of hsl and vsl

### ISSUE THREAD

**Issue by charlesneimog** [pure-data/pure-data#2391]
The `hsl` and `vsl` positions differ even when their y positions are set to be the same. This causes inconsistencies if we try to draw the same patch using another gui.

This patch (check the 6 for y position).

```
#N canvas 480 281 380 183 8;
#X obj 17 6 vsl 25 160 0 8 0 0 s-vsl2 r-vsl2 empty 0 -9 0 8 #fcfcfc #000000 #000000 0 1;
#X obj 47 6 hsl 128 15 0 127 0 0 hsl3-s hsl3-r empty -2 -8 0 8 #fcfcfc #000000 #000000 0 1;
```

The patch:

![Pasted image](https://github.com/user-attachments/assets/ac4de64d-62e3-486c-aae4-099a7b5ab5f1)

**Comment by umlaeute** [comment]
yes. this is known.

fixing this would probably break numerous patches (GOP with tight alignment).
