### ISSUE TITLE
JACK autoconnect only connects input (but not output)

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#2392]
i'm runnig Pd with JACK on top of the pipewire audio daemon.

when I start Pd, it only connects a device to Pd's input, but Pd's output is not connected anywhere, so I get no sound out by default:

![qjackctl](https://github.com/user-attachments/assets/57a90828-dc51-4991-9eb7-5b329da21585)

the available inputs are:
- **`Tiger Lake-LP Smart Sound Technology Audio Controller Digital Microphone`** (capture)
- `Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 1 Output` (monitor)
- `Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 2 Output` (monitor)
- `Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 3 Output` (monitor)
- `Tiger Lake-LP Smart Sound Technology Audio Controller Headphones Stereo Microphone` (capture)
- `Tiger Lake-LP Smart Sound Technology Audio Controller Speaker` (monitor)

the available outputs are:
- `Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 1 Output` (playback)
- `Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 2 Output` (playback)
- `Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 3 Output` (playback)
- **`Tiger Lake-LP Smart Sound Technology Audio Controller Speaker`** (playback)

(I've marked the *primary* devices in bold)

afaict, Pd assumes that the primary input device has the same name as the primary output device, and only tries to connect one.
https://github.com/pure-data/pure-data/blob/4cdf007e337b3e5f1b9c59aba42d85066b6009c3/src/s_audio_jack.c#L546-L547

**Comment by jamshark70** [comment]
I just built from latest sources (cloned just now, with `--enable-jack`) and find that the behavior is unchanged. Upon launching Pd (`./bin/pd`) and enabling DSP:

- "Alder Lake PCH-P High Definition Audio Controller Digital Microphone" is connected to Pure Data's 2 inputs.
- Pd's 2 outputs are *not* connected to "Alder Lake PCH-P High Definition Audio Controller Speaker + Headphones"

Other JACK software on my machine that finds the output channels: SuperCollider, Audacity, Reaper, PlugData standalone, WineASIO driver (though there's some issue with VCV Rack here).

![Image](https://github.com/user-attachments/assets/091cd17e-bab1-416e-a110-4a00d8d1f209)

**Comment by umlaeute** [comment]
> I just built from latest sources (cloned just now

which exact version (git commit) is this?

**Comment by jamshark70** [comment]
> which exact version (git commit)

12de13067 (April 6, 2025) -- there's nothing newer than that in the master branch.

(Commit e2fe5fd, fixing this issue, should be in master AFAICS.)

**Comment by jamshark70** [comment]
Just rebuilt to update to 0.56-1 -- should I open a new bug for this? AFAICS it is not fixed.

**Comment by umlaeute** [comment]
I am (was) pretty sure it is fixed.

please provide: 
- JACK implementation (and version) 
- list of devices (as listed by JACK)

also make sure you do not have any jack connection manager interfering (eg qjackctl has the notion of exclusive connections)

**Comment by jamshark70** [comment]
> JACK implementation (and version)

`jackd --version` tells me "jackdmp version 1.9.21 tmpdir /dev/shm protocol 9"

However jackd isn't running, only jackdbus.

> list of devices (as listed by JACK)

I have to admit, I'm confused by this question. In the past, when I was using JACK directly, hardware device names would be provided by ALSA, not by JACK (which only opened system:capture and system:playback ports). 

Pipewire is kind of a different beast, which is what this issue report is about. I'm not using JACK directly.

If I do `pw-cli list-objects | grep node.description` then I get this (deleting camera references as irrelevant):

```
 		node.description = "Alder Lake PCH-P High Definition Audio Controller Speaker + Headphones"
 		node.description = "Alder Lake PCH-P High Definition Audio Controller HDMI / DisplayPort 3 Output"
 		node.description = "Alder Lake PCH-P High Definition Audio Controller Digital Microphone"
 		node.description = "Alder Lake PCH-P High Definition Audio Controller Headphones Stereo Microphone"
 		node.description = "Alder Lake PCH-P High Definition Audio Controller HDMI / DisplayPort 1 Output"
 		node.description = "Alder Lake PCH-P High Definition Audio Controller HDMI / DisplayPort 2 Output"
 		node.description = "Audio Adapter (Unitek Y-247A) Analog Stereo"
 		node.description = "Audio Adapter (Unitek Y-247A) Mono"
 		node.description = "ALSA Capture [VirtualBoxVM]"
```

To compare, when I boot the SuperCollider audio server, it's configured (by way of the `SC_JACK_DEFAULT_OUTPUTS` environment variable) to connect to "system" ports -- using the old JACK nomenclature. Pipewire intercepts these connection requests and interprets "system" as whatever device is chosen as Pipewire's default at the time, e.g. "JackDriver: connected  SuperCollider:out_1 to Audio Adapter (Unitek Y-247A) Analog Stereo:playback_FL"

On my machine, when I launch Pd and turn on DSP, Pure Data input_1, input_2, output_1 and output_2 ports are created. input_1 and input_2 may be connected to the default input device; output_1 and output_2 *always* have to be connected manually. Pd is silent until I go into qpwgraph and manually drag the cables over.

> also make sure you do not have any jack connection manager interfering (eg qjackctl has the notion of exclusive connections)

For the last test, I quit qpwgraph first just to be sure. No difference.

I used qjackctl in the past but I see no reason to use it with Pipewire.

**Comment by jamshark70** [comment]
FWIW: I did

```
cd pure-data
git fetch origin
git checkout 0.56-3
make
```

... and my .desktop points to `./bin/pd-gui` relative to the pure-data folder, so I should be running the latest. (Full command line is `wish /home/dlm/share/tools/pure-data/bin/../tcl/pd-gui.tcl --`. Other pd command lines are similar, and file dates are today, so I'm completely confident that I'm running the new executable.)

But I get the same behavior: adc~ connected, dac~ not connected.

From the PR:
> connect Pd's [adc~] to the first JACK client that has audio source ports

`jack_lsp -p` reports this as the first available port, and indeed this is the one that's connected. So that part is working.

```
Alder Lake PCH-P High Definition Audio Controller Digital Microphone:capture_FL
	properties: output,physical,terminal,
Alder Lake PCH-P High Definition Audio Controller Digital Microphone:capture_FR
	properties: output,physical,terminal,
```

> connect Pd's [dac~] to the first JACK client that has audio sink ports (even if different from the above)

Continuing... these are the first input (sink) ports. They are not connected.

```
... (a few other output (source) ports, skipping)
Alder Lake PCH-P High Definition Audio Controller Speaker + Headphones:playback_
FL
	properties: input,physical,terminal,
Alder Lake PCH-P High Definition Audio Controller Speaker + Headphones:playback_
FR
	properties: input,physical,terminal,
```

If I plug in a different device, the first listings for output and input are indeed the device I expect. So the logic of the PR is sound, but for some reason, on my system, it isn't actually connecting pd's output.

**Comment by umlaeute** [comment]
1. can you manually connect? (iirc, sometimes ports just refuse from connecting)
2. do you have some connection manager running, that might interfere? (eg by actively disconnecting Pd after it connected)

**Comment by jamshark70** [comment]
> can you manually connect? (iirc, sometimes ports just refuse from connecting)

Yes -- dragging a connection across in qpwgraph or raysession works fine.

> do you have some connection manager running, that might interfere?

No. (RaySession allows session configurations to be saved and reloaded, but I haven't loaded any files. So it only shows the current status and allows me to manipulate it by hand.)

**Comment by millerpuckette** [comment]
I have a problem that might be related - `jack_get_ports()` takes a regex pattern and sometimes device names have characters that gum up the regex search.  I was unable to find a way to quote the device name so that the regex matches it.  I've been meaning to look at this more closely and try to fix it or at least report it better.  My offending device was an RME babyface in class compliant mode on linux.

**Comment by umlaeute** [comment]
> I was unable to find a way to quote the device name ...

do i understand correctly, that the problem is, that your device (as filled in by `jack_get_clients()`) has some "weird" name (containing regex-special characters, like `[]().*?+`), and when using this client-name as part of the regex in `jack_connect_ports()` it doesn't match itself?

out of interest: what is this name?

checking with the names reported by @jamshark70 , i see that the non-working devices are eg `Alder Lake PCH-P High Definition Audio Controller Speaker + Headphones`.
the `+` has special meaning, so the regex will match any string that has 2 or more spaces between `Speaker` and `Headphones`, but it won't match the literal `+`. which explains why it is not working.

now we only need a fix :-)

**Comment by umlaeute** [comment]
> now we only need a fix :-)

i've submitted a fix in the `develop` branch.

**Comment by jamshark70** [comment]
> i've submitted a fix in the develop branch.

Confirmed that this works in my environment -- I tested with two problematically-named devices and both of them connected both inputs and outputs. Thanks!
