### ISSUE TITLE
Windows Pro 11 issues

### ISSUE THREAD

**Issue by bsureshkrishna** [pure-data/pure-data#2394]
Hello,

I am a beginner. I just downloaded Pd 0.55 for Windows Pro 11.

1. The font in the open window for example, is unreadably small. I tried using -font 18 etc. when calling pd.exe, it did not change anything. I tried the vanilla version of 0.55 (both installer and zip) and also the ceamcc version.

2. I downloaded the mrpeach external using help-find externals, it is in my externals directory in the standard location. I tried to include that in the pd.exe call manually, it still does not detect the object (says object not found). The same thing happened with the osc library, and when I look in find externals after installing successfully (as per the message), it does not indicate that the library is locally available.

3. When I try to edit or add a new path in the preferences window to see if mrpeach can be loaded, I am not able to enter anything there at all. I just keep getting a message - to edit this, you need to restart pd.

Thanks, Suresh

ps. I did get a basic tone playing successfully. If that helps in answering the question. thank you !

#N canvas 100 100 450 300 10;
#X obj 100 100 osc~ 440;
#X obj 100 150 *~ 0.5;
#X obj 100 200 dac~;
#X connect 0 0 1 0;
#X connect 1 0 2 0;
#X connect 1 0 2 1;

**Comment by bsureshkrishna** [comment]
The library issue is resolved by adding mrpeach/ before udpreceive and unpackosc. FIXED

I am now able to edit the startup path. I used the .exe from the [msp.ucsd.edu](http://msp.ucsd.edu/) page rather than the [puredata.info](http://puredata.info/) page (which initially crashed). i have not checked that one again. FIXED

The font issue however remains. NOT FIXED

**Comment by Lucarda** [comment]
> The font issue however remains. NOT FIXED

see https://msp.ucsd.edu/Pd_documentation/x2.htm#s2.1.1

search there for "HiDPI screens"

**Comment by bsureshkrishna** [comment]
Thank you ! Yes, that works.
