### ISSUE TITLE
opening files via [readsf~]  can crash the GUI.

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#2404]
with a patch under heavy GUI-load (loads of moving bangs and GOPs and whatnot), i sometimes experience a weird lockup (eventually making the GUI unresponsive).

when the error occurs, the GUI displays the following:
```
tried /home/umlaeute/_____/________/__________/______/_______/49.wav and succeeded
tried /home/umlaeute/_____/________/__________/______/_______/40.wav and succeeded
tried /home/umlaeute/_____/________/__________/______/_______/17.wav and succeeded
(Tcl) INVALID COMMAND NAME: invalid command name ".x5564f5fbe700.c:coordsow::logpost"
    while executing
".x5564f5fbe700.c:coordsow::logpost obj:(nil) 4igur {0x5564f60bd020BASE} 334  {tried /home/umlaeute/_____/________/__________/______/_______/52.w..."
    ("uplevel" body line 147)
    invoked from within
"uplevel #0 $docmds"tried /home/umlaeute/_____/________/__________/______/_______/10.wav and succeeded
tried /home/umlaeute/_____/________/__________/______/_______/15.wav and succeeded
tried /home/umlaeute/_____/________/__________/______/_______/24.wav and succeeded
tried /home/umlaeute/_____/________/__________/______/_______/08.wav and succeeded
```

turning on debugging for the core<->gui communication i see:

```
>> .x5564f5208ab0.c delete {0x5564f62ae790IN0} ;
>> ::pdwindow::logpost obj:(nil) 4 {tried /home/umlaeute/_____/________/__________/______/_______/17.wav and succeeded
} ;
>> pdtk_text_set .x5564f5208ab0.c {0x5564f61f2df0LABEL} {⮊} ;
>> .x5564f5208ab0.c coords {0x5564f61f2df0LABEL} 330 485 ;
[...]
>> .x5564f5208ab0.c coords {0x5564f5fbdd50LABEL} 430 585 ;
>> .x5564f5208ab0.c itemconfigure {0x5564f5fbdd50LABEL} -font {{DejaVu Sans Mono} -22 {bold} } -fill #404040 ;
>> pdtk_text_set .x5564f5208ab0.c {0x5564f5fbdd50LABEL} {⮊} ;
>> .x5564f5208ab0.c coords {0x5564f5fbdd50LABEL} 430 585 ;
>> .x5564f5208ab0.c delete {0x5564f5fbdd50OUT0} ;
>> .x5564f5208ab0.c delete {0x5564f5fbdd50IN0} ;
>> .x5564f5fbe700.c coords {0x5564f60bd020RECT} 334 51 382 99 ;
>> .x5564f5fbe700.c itemconfigure {0x5564f60bd020RECT} -fill #e0e0e0 -outline #e0e0e0 ;
>> .x5564f5fbe700.c :coords obj:(nil) coords {0x5564f60bd020BASE} 3344 {tried /home/umlaeute/_____/________/__________/______/_______/52.wav and succeeded
} ;
  {tried /home/umlaeute/_____/________/__________/______/_______/52.wav and succeeded
} ;
51 382 99 ;
>> .x5564f5fbe700.c itemconfigure {0x5564f60bd020BASE} -width 1 -outline #e0e0e0 ;
>> .x5564f5fbe700.c coords {0x5564f60bd020LABEL} 348 75 ;
>> .x5564f5fbe700.c itemconfigure {0x5564f60bd020LABEL} -font {{DejaVu Sans Mono} -30 {bold} } -fill #e0e0e0 ;
>> pdtk_text_set .x5564f5fbe700.c {0x5564f60bd020LABEL} {} ;
```

so obviously some messages for the GUI get interleaved before sending them over.

this is with Pd-0.55-0

**Comment by umlaeute** [comment]
this appears to be related to "something" asynchronously (that is: from a sub-thread) printing out messages.

Running the same patch with `-stderr`, i haven't seen the issue yet.

Potential culprits are `[hid]` or `[readsf~]`.
I have replaced `[readsf~]` with reading my samples from tables (which makes more sense anyhow), and i don't see the issue any more either (even when printing to the Pd-console).

**Comment by umlaeute** [comment]
ah, the problem comes from this (introduced in 15895dc9b6e16d187354f7f4602441b2b5bae7e8): https://github.com/pure-data/pure-data/blob/6f9a4077513bd9b997714495c8e574b81b58cb41/src/d_soundfile.c#L1866-L1868


this basically means, that the soundfile is opened from the helper-thread (`readsf_child_main`) using `open_soundfile_via_path()`, which in turn uses `open_via_path()`, which uses `sys_trytoopenone()`, which uses `logpost()`. :boom:

Somewhat related to https://github.com/pure-data/pure-data/issues/234

**Comment by umlaeute** [comment]
i still think that that the proper solution is to move the path-resolution process into the main thread (even though it might block), and only pass absolute filenames (or even file-descriptors) to the child thread.

this comes with the risk of locking the main thread while looking for the path. (but that's not a problem if the user passes absolute paths, e.g. by calculating the the path prefix at startup time, e.g. using `[file patchpath]`).

alternatively, don't resolve at all and just pass the filename as is (but that would break existing patches, so is not a very good idea).

or have an `open_via_path()` variant that doesn't print out (but then it's harder to debug while things go wrong).

or use a thread-safe queue for `pdgui_vmess()`/`sys_gui()`

or lock `pdgui_vmess()`/`sys_gui()`

thoughts @Spacechild1 , @danomatika ?

**Comment by Spacechild1** [comment]
> , and only pass absolute filenames (or even file-descriptors) to the child thread.

That's what we do in practice anyway since `readsf~` can't resolve canvas relative paths. So I think moving `open_via_path` via path to the main thread is a valid trade-off. After all, the current code isn't really thread-safe anyway:
https://github.com/pure-data/pure-data/blob/6f9a4077513bd9b997714495c8e574b81b58cb41/src/d_soundfile.c#L408-L411

> or use a thread-safe queue for pdgui_vmess()/sys_gui()
> or lock pdgui_vmess()/sys_gui()

Aren't these two essentially the same?

Actually, in my multi-threading branch I did exactly this: https://github.com/Spacechild1/pure-data/pull/5/commits/3be5d4ac3a4b763a056c0f498889c25781757c32.

I really think that logging should be threadsafe anyway. Currently, there isn't a safe and convenient way to log from a helper thread. (Remember, `sys_lock`/`sys_unlock` are dangerous!) There is https://github.com/pure-data/pure-data/pull/2303, but it's really meant for more elaborated tasks than just posting a message :)

**Comment by umlaeute** [comment]
for completeness sake, here's a minimal patch to reproduce the problem (pretty early):

```
#N canvas 1178 206 450 300 12;
#X msg 283 60 \; pd dsp 1;
#X obj 74 205 readsf~;
#X obj 74 230 *~;
#X obj 74 255 dac~;
#X msg 74 177 open test.wav;
#X obj 236 185 bng 20 250 50 0 empty empty empty 0 -10 0 12 #a0a0a0 #404040 #fce0e0;
#X msg 236 146 color 1 2 3;
#X obj 123 78 tgl 20 0 empty empty empty 0 -10 0 12 #fcfcfc #000000 #000000 0 1;
#X obj 122 128 t b b;
#X floatatom 208 101 5 0 0 0 - - - 0;
#X obj 123 103 metro 10;
#X connect 1 0 2 0;
#X connect 2 0 3 0;
#X connect 4 0 1 0;
#X connect 6 0 5 0;
#X connect 7 0 10 0;
#X connect 8 0 4 0;
#X connect 8 1 6 0;
#X connect 9 0 10 1;
#X connect 10 0 8 0;
```

**Comment by millerpuckette** [comment]
Ouch.
I'd been planning for years to do something slightly different, simply copying the "path" down to the helper thread so that it could access its own local copy (thus avoiding the non-thread-safety of open_via_path()).  However, now I see that it would also be necessary to disable logging from the thread as well.  So there would have to be a separate call, open_via_thread_copy, that would also suppress any logging, or else buffer the log output where the main thread can get it and print it out.
Moral: anyone who ever uses threads will one day suffer for it :)

**Comment by Spacechild1** [comment]
> Moral: anyone who ever uses threads will one day suffer for it :)

Small correction: anyone who uses threads *in C* will suffer for it :)

**Comment by porres** [comment]
can we close this? Does pd 0.55-1 test take care of this?
