### ISSUE TITLE
[vu] seems to ignore 0.0 at the inlet?

### ISSUE THREAD

**Issue by jamshark70** [pure-data/pure-data#2410]
```
#N canvas 0 0 450 441 12;
#X obj 53 62 tgl 20 0 empty empty empty 0 -10 0 12 #fcfcfc #000000 #000000 0 1;
#X obj 53 87 metro 1000;
#X obj 53 112 tgl 20 0 empty empty empty 0 -10 0 12 #fcfcfc #000000 #000000 0 1;
#X obj 54 153 vu 20 200 empty empty -1 -10 0 12 #404040 #000000 1 0;
#X connect 0 0 1 0;
#X connect 1 0 2 0;
#X connect 2 0 3 0;
```

Toggle --> vu.

When vu receives 1, it displays a value somewhere between 0 and 2 dB.

When it receives 0, it does *not* fall back to 0 dB. 0 appears to be inactive as an input value.

Pd vanilla 0.52.1 does not reproduce the problem. Pdnext 0.55 and latest plugdata both *do* reproduce the issue.

Is this a new feature, or just a bug?

EDIT: Also confirmed in Pd vanilla 0.55, hence it must be a regression.

**Comment by Spacechild1** [comment]
> Is this a new feature, or just a bug?

Gotta love your sarcasm xD Yes, that's a bug. Thanks for reporting!

**Comment by umlaeute** [comment]
this is fixed in https://github.com/pure-data/pure-data/pull/2260

**Comment by porres** [comment]
we can close this then, since the fixes from https://github.com/pure-data/pure-data/pull/2260 were made

**Comment by jamshark70** [comment]
Fix is working here, great, thanks!
