### ISSUE TITLE
libpd: audio broken since 5115d552512f93e73a21f336d414fd36987706b6

### ISSUE THREAD

**Issue by jcelerier** [pure-data/pure-data#2429]
Offending bisected commit: 5115d552512f93e73a21f336d414fd36987706b6

I'm testing with pdtest.c provided by libpd (https://github.com/libpd/libpd/tree/master/samples/c/pdtest)

I build with:

    $ clang pdtest.c /home/jcelerier/ossia/score/3rdparty/libpd/build/libs/libpd.so  -I /home/jcelerier/ossia/score/3rdparty/libpd/libpd_wrapper/ -I /home/jcelerier/ossia/score/3rdparty/libpd/pure-data/src/ -fsanitize=address  -fsanitize=undefined  -lm -DPDINSTANCE=1 -DPDTHREADS=1 -DPD=1
    $ ./a.out  test.pd $PWD

since this commit, the audio output (firest ten values of the output buffer) of this test patch is
```
0
0
0
0
0
0
0
0
0
0
```

before that, it was

```
0.937108
0.937108
0.915696
0.915696
0.89132
0.89132
0.864065
0.864065
0.833976
0.833976
```

ping @umlaeute @danomatika @Spacechild1

**Comment by Spacechild1** [comment]
Hmmm... there was indeed a libpd bug in https://github.com/pure-data/pure-data/commit/5115d552512f93e73a21f336d414fd36987706b6 , but that should have been fixed with https://github.com/pure-data/pure-data/commit/42f868ef3bcdbe74646458c0a4f88b3f58735c8a...

Which Pd version (commit hash) are you using to build libpd?

**Comment by danomatika** [comment]
Note: I haven't actually tested any of the 0.55 stuff, so updating the submodule commit is probably the fix.

**Comment by umlaeute** [comment]
sidenote: I do run tests regularly, and the test_libpd.c that comes with Pd is known to still work with Pd-0.55-1: https://salsa.debian.org/multimedia-team/pd/puredata/-/jobs/6253423#L809

*also*, i just compiled your test-example against the `libpd` that comes with Debian (based on Pd-0.55-1), and it works as expected (though i think that libpd is built without multi-instance support).
so i rebuilt libpd (0.51-1) with multi-instance support and tried again, and it still seems to be working allright.

i therefore conclude, that there is no bug in Pd.
maybe (as @danomatika  indicated), there's a bug in libpd (as in: not using the latest and greatest), but then it should be reported over there.

i'm therefore closing this (we can of course re-open it, if you disagree)

**Comment by danomatika** [comment]
To confirm: the issue lies in libpd. I haven't integrated the newest changes from Pd yet, so it's a little more than doing a pull in the submodule. I had some shows recently so I use the latest stable version and was waiting until 0.55-1 was released first before making a new libpd release.

**Comment by danomatika** [comment]
I've updated libpd master with the back ported fixes and audio i/o should be fine now.

I think I will keep the `libpd_wrapper` sources for this release *but* move the makefiles and project files to use the `z_*` sources in the pure-data submodule with a note about removing `libpd_wrapper` in the next release.

**Comment by danomatika** [comment]
Another followup: this is fixed in libpd, but requires updating the submodule to checkout the pure-data `develop` branch for now. I am waiting for a merge to `master` before I make a new libpd release.
