### ISSUE TITLE
Multi instance support for [text define]

### ISSUE THREAD

**Issue by pierreguillot** [pure-data/pure-data#243]
When I use libPd with PDINSTANCE and PDTHREADS and I use pd_instance pdinstance_new(), if I load a patch with [text define], it crashes in [text-define_new()](https://github.com/pure-data/pure-data/blob/master/src/x_text.c#L280) because x->x_scalar is NULL (because in [scalar_new()](https://github.com/pure-data/pure-data/blob/master/src/g_scalar.c#L113), the function template_findbyname(templatesym) returns NULL). So it seems that the function can't find a template linked with the symbol "pd-text". 

After several investigation, I found that at initialization, pd_init() calls [conf_init()](https://github.com/pure-data/pure-data/blob/master/src/m_pd.c#L311)  that calls [x_qlist_setup()](https://github.com/pure-data/pure-data/blob/master/src/m_conf.c#L91) that calls [text_template_init()](https://github.com/pure-data/pure-data/blob/master/src/x_text.c#L1970) etc. and that ends by calling [template_new()](https://github.com/pure-data/pure-data/blob/master/src/g_template.c#L154) that binds a template to the the symbol "pd-text". 

This binding is only valid at initialization and is not duplicated when using new pdinstances that why it crashes. And I guess there is the same problem with the symbols "pd-float" and "pd-float-array" with garray_init().

Here is the discussion (with myself :) ) on [pd-dev list](https://lists.puredata.info/pipermail/pd-dev/2017-11/021313.html). And the initial [issue](https://github.com/libpd/libpd/issues/196) on the libpd repository.

I create a PR to correct the bug but as I'm not sure that this is the best solution, I also prefer to create this issue.

**Comment by danomatika** [comment]
This would be good to have in 0.48-1 and libpd needs it as well.

**Comment by pierreguillot** [comment]
PR Merged
