### ISSUE TITLE
`fexpr~ $x[-1]+$y[-1]` crashes

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#2432]
As of Pd-0.55-1, an object `[fexpr~ $x[-1] + $y[-1]]` crashes as soon as the DSP is turned on.
Pd-0.55-0 could handle this just fine.

Other variants, like `[fexpr~ $x[0] + $y[-1]]` work fine.

`git bisect` tells me, that this regression was introduced by  cad91dc791c7b17972d4d508f6bf6a93f1ff0613

here's my test-patch:
```
#N canvas 2616 283 450 300 12;
#X obj 124 107 fexpr~ $x[-1]+$y[-1];
#X msg 281 54 \; pd dsp 1;
```

**Comment by porres** [comment]
I'm letting Shahrokh know about this, but he's away and only back in a week

we can try and fix it in the meantime of course

I think this calls for a quick 0.55-2 update
