### ISSUE TITLE
libpd: z_ringbuffer broken on iOS

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#2436]
So the atomics update is a good idea, but there is another teething issue: the z_ringbuffer appears to be broken on iOS with the libpd and the Pd 0.55-1 sources.

Trying out the libpd "pdtest" iOS project, it sounds like a buffer is filled then simply repeated without newer samples. Also, the test print messaging is working but seems to be repeated over and over to some degree, which made me think there is a problem with the ringbuffer. Low and behold, copying in an old version before the atomics update fixes both audio and messaging.

**Comment by Spacechild1** [comment]
Ouch! Will have a look in the next few days!

What's strange is that Pd 0.55.1 uses the same atomic functions in the portaudio ringbuffer. I just checked on my MacBook and Pd runs just fine.

When you build your iOS project, does it use the the C11 atomics or the GCC/Clang atomics?

**Comment by Spacechild1** [comment]
I'm pretty sure I've tested with all implementations (C11, MSVC and GCC/Clang). I just built Pd 0.55-1 from source on Windows, once with the C11 atomics and then again with the GCC/Clang atomics. Both work fine. The ringbuffer only uses simple atomic loads and stores -- with the strongest memory ordering (= sequential consistent) -- so I have no idea what's going on...

Does this only happen on iOS? Can you test on Apple Silicon? Maybe it has to do with ARM, but as I've said, I'm already using the strongest memory ordering...

It *could* also be a problem with the `z_ringbuffer` itself that has only been exposed by the new atomic functions. Will take a closer look.

**Comment by danomatika** [comment]
The libpd examples on macOS work fine, it's an iOS issue. Also, portaudio is not affected as portaudio is not used by libpd on the platform.

The Xcode project is using the "Compiler default" for the C language version, so I assume it's using the clang default, whatever that is. I tried both C11 and C17 with the same result.

**Comment by danomatika** [comment]
> It could also be a problem with the z_ringbuffer itself that has only been exposed by the new atomic functions. Will take a closer look.

It would have to be something that subtle before as `z_ringbuffer` was in use for over 10 years now.

**Comment by danomatika** [comment]
@nettoyeurny If you have time, could you quickly double check the atomics update to `z_ringbuffer`?

Specifically:  
[m_private_utils.h](https://github.com/pure-data/pure-data/blob/master/src/m_private_utils.h#L21)  
[z_ringbuffer.c](https://github.com/pure-data/pure-data/blob/master/src/z_ringbuffer.c)

**Comment by Spacechild1** [comment]
> Also, portaudio is not affected as portaudio is not used by libpd on the platform.

I meant the portaudio audio *ringbuffer* (= `src/s_paring.c`). I know it's not used by libpd, but it uses the same atomic functions and it works just fine.

> The libpd examples on macOS work fine,

Intel or ARM? If you have a chance, please test on ARM.

>  I tried both C11 and C17 with the same result.

Can you please verify that it does indeed use the C11 atomics? Just put an `#error` in the other clauses. Then please try again by forcing the *other* atomic implementation, i.e. instead of the C11 atomics force the old GCC/Clang atomics - or vice versa.

Unfortunately I can't really test on iOS, but I can test on a Raspberry Pi to rule out an ARM issue.

**Comment by danomatika** [comment]
I am building the libpd examples for macOS arm64.



> > Also, portaudio is not affected as portaudio is not used by libpd on the platform.
> 
> I meant the portaudio audio _ringbuffer_ (= `src/s_paring.c`). I know it's not used by libpd, but it uses the same atomic functions and it works just fine.

That is irrelevant on iOS and I *bet* it wouldn't currently work there either. ;)

> > The libpd examples on macOS work fine,
> 
> Intel or ARM? If you have a chance, please test on ARM.

I have an M1, so I am building  the libpd examples for arm64.

> > I tried both C11 and C17 with the same result.
> 
> Can you please check which implementation is selected? Just put an `#error` in the other clauses. Then please try again by forcing the _other_ atomic implementation, i.e. instead of the C11 atomics force the old GCC/Clang atomics - or vice versa.

Changing C dialect in the Xcode project:
* default: C11 atomics
* C11: C11 atomics
* C17: C11 atomics
* C99: fails to build due to missing functions:
~~~
/Users/danomatika/src/pd/libpd/pure-data/src/z_ringbuffer.c:42:20: Call to undeclared function '__atomic_load_4'; ISO C99 and later do not support implicit function declarations

/Users/danomatika/src/pd/libpd/pure-data/src/z_ringbuffer.c:52:20: Call to undeclared function '__atomic_load_4'; ISO C99 and later do not support implicit function declarations

/Users/danomatika/src/pd/libpd/pure-data/src/z_ringbuffer.c:82:3: Call to undeclared function '__atomic_store_4'; ISO C99 and later do not support implicit function declarations

/Users/danomatika/src/pd/libpd/pure-data/src/z_ringbuffer.c:100:3: Call to undeclared function '__atomic_store_4'; ISO C99 and later do not support implicit function declarations

/Users/danomatika/src/pd/libpd/pure-data/src/z_ringbuffer.c:118:3: Call to undeclared function '__atomic_store_4'; ISO C99 and later do not support implicit function declarations

/Users/danomatika/src/pd/libpd/pure-data/src/z_ringbuffer.c:125:5: Call to undeclared function '__atomic_store_4'; ISO C99 and later do not support implicit function declarations
~~~

**Comment by Spacechild1** [comment]
> I have an M1 cpu, so I am building the libpd examples for arm64.

Just to be clear: the M1 binaries are working fine, right? It's only failing on iOS? In this case it's not an ARM issue...

> Changing C dialect in the Xcode project:

Thanks. So you are indeed using the C11 atomics. That's really strange. Why would this work on every other platform (including other ARM platforms), but not on iOS!?

**Comment by Spacechild1** [comment]
Turns out this has nothing to do with the atomics functions. It was a simple copy-paste error 🤦‍♂️ 

https://github.com/pure-data/pure-data/commit/e72039c58467c6fc0610e13c500fc8eb58030d7d#diff-4eafbf81168d4b22c00ce3d4a5cd8badec73597085a265d9db7180ba9aa5a226R118

Can you try to replace this line with
```
atomic_int_store(&buffer->read_idx, (read_idx + len) % buffer->size); // includes memory barrier
``` 

I'm so sorry!!

**Comment by danomatika** [comment]
That was it. Fixing line 118 gives me normal execution now.

This explains why desktop Pd is fine as it doesn't use `z_ringbuffer`. Also, I think my other tests on macOS were perhaps faulty, they made noise but it was repeating samples and I wasn't;t *really* listening the output quality... just checking if numbers and sound came out.

**Comment by Spacechild1** [comment]
Phew! Now that my sanity has been restored, I've pushed a fix to develop: https://github.com/pure-data/pure-data/pull/2433/commits/25dd40fa583f579a706a228821fc305466859b2c

**Comment by danomatika** [comment]
Should we close this as the fix is in `develop` *and* the lips has been updated to point to it?

**Comment by umlaeute** [comment]
i'd rather only have this closed once it has been merged into `master` (and GitHub automatically does this for us ;-))
