### ISSUE TITLE
add 'clear' message to [vcf~]

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2438]
Seems like this is the only filter without a clear and/or set message in Pd...

so... for the sake of consistency...

**Comment by no382001** [comment]
Hi, I'm a first-time contributor. Could you take a look at my MR to ensure everything's correct?

**Comment by porres** [comment]
> Hi, I'm a first-time contributor. Could you take a look at my MR to ensure everything's correct?

I think it looks good, thanks! @umlaeute / @Spacechild1 ?
