### ISSUE TITLE
sigmund~ with -nharmonics flag reports error

### ISSUE THREAD

**Issue by Josef-N** [pure-data/pure-data#2440]
It took me a while to find out, when using the -nharmonics flag in sigmund~ it needs two numbers, e,g. [sigmund~ -nharmonics 6 0]. This worked in Pd 0.54 and in 0.55-0, but in Pd 0.55-1 the console reports an error:
sigmund~: : unknown flag or argument missing

I am not sure if this is a bug or just an incorrect warning, because sending messages to nharmonics (inside sigmund~) seems to work, nevertheless.
Besides that, it would be good if this special situation is documented in the help file, I think.

**Comment by porres** [comment]
Documentation says it needs one float, but yeah, I see it in code now that it needs two! So the documentation is wrong indeed and needs to be fixed!

> This worked in Pd 0.54 and in 0.55-0, but in Pd 0.55-1 the console reports an error:
> sigmund~: : unknown flag or argument missing
> I am not sure if this is a bug or just an incorrect warning, because sending messages to nharmonics (inside sigmund~) seems to work, nevertheless.

I see the error, but note it's not an error for '-nhamrmonics' having wrong number of arguments, if I try a single argument I get 

sigmund~: -nharmonics: unknown flag or argument missing
sigmund~: : unknown flag or argument missing

so yeah, it's an incorrect warning and there's no warning or something wrong for -nharmonics I guess... well, one way or another, there's a bug in the code!

> Besides that, it would be good if this special situation is documented in the help file, I think.

Me too, I would love to have EVERYTHING documented with examples and all, and count me in for that. But I don't really understand these new features and I needed help...

**Comment by Josef-N** [comment]
Thanks for your response! Good to know, that you are seeing the same things as me.
Then let’s hope that someone helps us to understand and ideally resolve this issue.

**Comment by no382001** [comment]
reversing 13f9b43 solves the issue, `-nharmonics` is the only flag in `sigmund~` that takes 2 parameters so this change must have been a mistake

**Comment by no382001** [comment]
solution is not so simple as i thought, i'll keep you updated

**Comment by Josef-N** [comment]
ok, thanks!

**Comment by no382001** [comment]
the problem is that the code that parses the flags and their parameters in `sigmund_new` is not made to handle more than 1 parameter per flag, and `-nharmonics` afaik is the only flag that takes 2 parameters.
in 13f9b43 everytime `-nharmonics` was called it left the last argument in the argument stack, that lead to more warnings.
the logic was incorrect either way, shouldn't there be a more robust way to handle argument parsing here?

**Comment by Josef-N** [comment]
@no382001 thanks for your efforts! I don’t know much about coding, but hopefully this will fix the issue and will be merged, unless there is another solution.
@porres I could help you for the documentation to describe how it works, but I think it is better to wait for the final solution, in case something will change.

**Comment by Josef-N** [comment]
this issue is fixed in Pd-0.55-2test1. I saw, the documentation got an update, too. Great, thanks!
So I will close it.
