### ISSUE TITLE
support for Tcl/Tk-9.0

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#2452]
Tcl/Tk 9.0 has been released a few days ago (2024-09-25)

Currently Pd refused to run with TclTk-9.0 as it hardcodes dependencies on the TclTk-8.x:

- https://github.com/pure-data/pure-data/blob/d0f2798de3c1a521de99a91e13b82e29af78096b/tcl/pd-gui.tcl#L15-L21
- https://github.com/pure-data/pure-data/blob/d0f2798de3c1a521de99a91e13b82e29af78096b/tcl/pd_docsdir.tcl#L14
- https://github.com/pure-data/pure-data/blob/d0f2798de3c1a521de99a91e13b82e29af78096b/tcl/pd_deken.tcl#L21

afaict, the fix is simply to replace `package require Tcl 8.4` with `package require Tcl 8.4 9`  (and replace the versioned `package provide` stanza with `package require` as well. I'm not sure whether `package provide` is the correct thing to do anyhow)

**Comment by umlaeute** [comment]
note: deken has been updated/fixed separately with https://github.com/pure-data/deken/commit/42af15390bc8903411a4866baa1e501e4499155b

**Comment by umlaeute** [comment]
some plugins (available via deken) are also affected:
- completion-plugin
- [x] deken-plugin
- [ ] dnd-plugin
- [ ] kiosk-plugin
- [ ] scrollpage-plugin
- [ ] search-plugin

**Comment by ben-wes** [comment]
cool! maybe not relevant at this point (and not even sure how it's connected) - but i quickly tested this here on Darwin 24.0.0 ...

works for me - but:
* data structure drawing and pdlua GUIs seem quite a bit slower
* right click in patch window doesn't work (both, with mouse button and 2 finger tap on touchpad) - it does work with the middle button and via control+click though
* scrolling in patch window doesn't work (both, with scroll wheel and 2 finger gesture on touchpad) - it does work in the pd window though

**Comment by umlaeute** [comment]
thanks for the tests, cool that there's no speed regression.

@millerpuckette : just to make sure that you can still merge this regardless of ben's observations: i guess it might take some time till we *actually* switch the Tcl/Tk to 9.x (if ever). in any case, i'd like to be ready when we do..
