### ISSUE TITLE
double free in cos_cleanup() and other related crash bugs

### ISSUE THREAD

**Issue by agraef** [pure-data/pure-data#2455]
Found while porting multi-channel to purr-data and running our regression test suite. (There's more fallout from the multi-channel code detected by our regression tests which I'm still investigating, so I don't know yet whether there may be other engine bugs to be reported here in due course.)

But this one definitely *is* a bug in the engine. Actually, I think that it may have been around for very a long time, probably since https://github.com/pure-data/pure-data/commit/e68a8b125f707cce3e6cc51ca8a95146e5b2518c. The reason we never saw these in our regression tests before is that we never ported that cos_cleanup function to purr data until now.

Firstly, see: https://github.com/pure-data/pure-data/blob/d0f2798de3c1a521de99a91e13b82e29af78096b/src/d_osc.c#L214-L216

Replace `cos_table = 0` with `cos_newtable = 0` there to prevent a double free (resulting in Pd crashing with SIGABRT) if cos_cleanup() gets invoked more than once (as it surely will in most real-world examples).

But there's a deeper issue there, which rears its head in d_osc.h, where `tab` in `COSPERF()` may already be set to a NULL pointer after a previous `cos_cleanup()`, resulting in Pd crashing with SIGSEGV. Since `cos_table` and `cos_newtable` are global and shared by all cos~ objects, there needs to be some reference counting in place, so that the tables don't get freed while they may still be in use. But this also requires some refactoring, since currently the tables *only* get initialized once, at the time the cos_class is set up.

So why not just keep the tables around forever? Memory concerns on small embedded systems? IMHO, if your system memory is so tight that you can't keep 8K worth of floats in RAM then you probably have more serious issues running Pd there. So I'd suggest to just not free the tables at all, which is the solution that I implemented in purr-data, but that's up to you to decide.

**Comment by umlaeute** [comment]
For Pd(-vanilla), this is actually dead code, as we do not free classes (so it never got triggered).

you are right that line 216 is obviously a copy-and-paste error, and should be fixed.

i have no specific opinion about keeping the table forever, but i tend towards your suggestion of not deleting it (although i do not agree with your dismissal of saving 8k on embedded systems,,, but anyhow).
however, it would be interesting to hear @jpcima (who authored https://github.com/pure-data/pure-data/pull/64, which was specifically geared towards running on embedded systems).

>  Since `cos_table` and `cos_newtable` are global and shared by all cos~ objects, there needs to be some reference counting in place, so that the tables don't get freed while they may still be in use.


i think if you delete the cos~ class while there are still some `[cos~]` instances around, you are in for more trouble than just a freed costable.

**Comment by agraef** [comment]
There's another crash bug in signal_makereusable() where sig->s_borrowedfrom may be 0 even though sig->s_isborrowed is set, and since it's easy to fix and I'm too lazy to open another ticket, here's the fix:

~~~diff
--- a/src/d_ugen.c
+++ b/src/d_ugen.c
@@ -471,7 +471,7 @@ void signal_makereusable(t_signal *sig)
     if (THIS->u_loud) post("free %lx: %d", sig, sig->s_isborrowed);
     if (sig->s_isborrowed || sig->s_isscalar)
     {
-        if (sig->s_isborrowed)
+        if (sig->s_isborrowed && sig->s_borrowedfrom)
         {
             /* if the signal is borrowed, decrement the borrowed-from signal's
                 reference count, possibly marking it reusable too */
~~~

**Comment by agraef** [comment]
> For Pd(-vanilla), this is actually dead code, as we do not free classes (so it never got triggered).

Fair enough.

> i think if you delete the cos~ class while there are still some [cos~] instances around, you are in for more trouble than just a freed costable.

No, this is not what happens. I think that purr-data indeed does the class creation and destruction automatically as needed, at least in the very special stripped-down environment in which the rgression tests are being run. But of course it won't destroy a class as long as there are any instances for it. :) In any case, this isn't the issue here -- the issue is that once cos~ has been unloaded once, it's static tables are gone for good, even if it gets loaded again later, and that's precisely why the regression test failed. As soon as I fixed that, the regression test went through alright.

I think that all of this can indeed never happen in pure-data. But then why have a routine like cos_cleanup in the first place if it's never going to run anyway?

**Comment by agraef** [comment]
The second issue might have a similar cause, but it's also different enough that I think that it would be prudent to look into this. For one thing, here signal_cleanup() *is* actually being called via ugen_stop(). So I think that there might still be some (possibly rare) conditions also in pure-data where sig->s_isborrowed is set but sig->s_borrowedfrom may be not.

Our regression tests are designed to be very aggressive so they test conditions and shake out bugs that might rarely if ever arise in normal use. That's why we have them.

Anyway, I have all tests passing in purr-data now, so I'm a happy camper. Make of this report what you will. :)

**Comment by umlaeute** [comment]
> > For Pd(-vanilla), this is actually dead code, as we do not free classes (so it never got triggered).
> 
> Fair enough. But then why have a routine like cos_cleanup in the first place if it's never going to run anyway?

see
- https://github.com/pure-data/pure-data/pull/64

> 
> > i think if you delete the cos~ class while there are still some [cos~] instances around, you are in for more trouble than just a freed costable.
> 
> I'm not sure what exactly is going on there in the very special stripped-down environment in which the regression tests are being run. But this is not what happens -- the issue is that once the generated test involving cos~ has been unloaded once, the static tables are gone for good, even if another test involving cos~ gets loaded again later, and that's precisely why the regression test failed. As soon as I fixed that, the regression test went through alright.

i wonder though, how you make sure that "cos~ gets loaded again".
- a class is *created* with `class_new()` (and accompanying `class_add...()` calls).
- a class is *destroyed* with `class_free()` (as i understand it :-))

now, in the Pd code, the `cos~` class is created together with the costables, within a single function:
https://github.com/pure-data/pure-data/blob/d0f2798de3c1a521de99a91e13b82e29af78096b/src/d_osc.c#L219-L227

now grouping the calls to `class_new()` and `cos_maketable()` into a single code-block does not magically associate the costables with the `cos_class` (and `class_free()` is apparently (and imho wrongly) assuming that the costables *are owned* by the class) - but in practice the class creation is indeed coupled to the costable creation.

so how do you re-create the `cos_class` if you (apparently) are not calling `cos_setup()` again (as otherwise you would *also* be calling `cos_maketable()` again?
do you
- somehow cache the calls to `class_new()` and friends so you can re-play them later?
- assume that `cos_class` is valid after calling `class_free()` (which is wrong)

(@agraef please do not go away just yet, i'm genuinely interested in what is going on here exactly)

**Comment by umlaeute** [comment]
and could you share a link to your test-suite ressources?

**Comment by umlaeute** [comment]
about the second issue (borrowed signals), here's a bit more context of the code you are patching:
https://github.com/pure-data/pure-data/blob/d0f2798de3c1a521de99a91e13b82e29af78096b/src/d_ugen.c#L472-L482

i think the intention of lines 478-480 is to be notified of an actual bug in the signal-borrowing code. your patch basically paints over this check, hiding it deeper (so yes, I agree with you that that should be looked into).

**Comment by umlaeute** [comment]
> I'm too lazy to open another ticket,

nevertheless i've moved this to https://github.com/pure-data/pure-data/issues/2456

**Comment by agraef** [comment]
> please do not go away just yet, i'm genuinely interested in what is going on here exactly

No worries. IOhannes, I'm really happy that you started triaging so that this has some chance of getting some additional eyeballs, and at least the signal_makereusable issue gets a proper fix instead of my quick-and-dirty work-around.

> nevertheless i've moved this to https://github.com/pure-data/pure-data/issues/2456

Ok, thanks. I'll reply to your other remarks and questions there then.

> so how do you re-create the cos_class if you (apparently) are not calling cos_setup() again

Well spotted! Incidentally, I've been asking myself exactly that same question. :smiley: TBH, I don't understand Jonathan's external-tests.pd patch well enough to answer that question, so I'll have to dig deeper into the patch; it could still be a bug in that patch, for all I know.

> and could you share a link to your test-suite ressources?

The patch that is being run there is this:

https://github.com/agraef/purr-data/blob/testing/scripts/external-tests.pd

(NB: It's the same patch as on the master branch, which is simply a mirror of Jonathan's upstream source. But the version of the source that I'm currently testing, which includes all the latest backports from vanilla Pd including the multi-channel support, is on the testing branch right now. Kind of like the develop branch that you're using over here.)

This patch gets run as `$(pdprog) -noprefs -nostdpath -nogui -noaudio scripts/external-tests.pd` from our [toplevel Makefile](https://github.com/agraef/purr-data/blob/testing/Makefile) with `make check`, where `$(pdprog)` points to the (uninstalled) main executable in the staging area after a build. So basically I first run `make` to build the entire thing, then `make check` to make sure that everything's alright. The same happens in our GH CI and all the other Linux builds that I do on the Open Build Service.

The patch does simple instantiation tests for all the externals that we ship (well, most of them, as we don't quite have 100% test coverage yet). It also tests many of the abstractions, which is how I found the issues this report is about. I think they actually occurred while testing Tom Schouten's creb library which also happens to be the first tested library that includes a bunch of abstractions utilizing dsp stuff like cos~. Thus if there's anything wonky in that part of the core, it usually turns up there. In this specific case, when I ran into the reported segfault, I could then run `coredumpctl debug` to get a gdb backtrace and see exactly where it crashed. For the SIGABRT problem which doesn't generate a core dump, I had to run the regression test manually in gdb to get the backtrace.

Unfortunately, you can't just run that patch in vanilla Pd since it uses some special self-inspection objects (pdinfo and classinfo) that don't exist in vanilla Pd, and it also assumes that it is run inside the purr-data source tree after a build (which differs a lot from vanilla's, since it also includes all the externals).

You can open the patch, though, if you disable loadbangs, with something like `pd -noloadbang scripts/external-tests.pd` (or `purr-data -noloadbang scripts/external-tests.pd` if you do have purr-data installed). It will give you some errors in pd due to the missing inspection objects, but at least you can look at it.

I can't tell you exactly how the patch works, as I didn't write it -- I wish I did, but it was Jonathan's work. :wink: I've looked at it for some time, but it's a little ... complicated and not very perspicuous, I'm afraid.

**Comment by agraef** [comment]
> `$(pdprog) -noprefs -nostdpath -nogui -noaudio scripts/external-tests.pd`

Looking at what I just wrote, it came to me that the `-noaudio` option there could possibly play a part in the regression test problems that I saw. But then again, we've been running that test suite for many years now and never ran into these issues before.

**Comment by umlaeute** [comment]
Afaict, the patch just searches the disk for objects, then tries to load them, creates all the newly added classes and calls their methods with some default argument. 

As I won't have the time to run this any time soon, would it be possible to get the output of the test patch (it's posting a bit of data to the stderr).

(Feel free to mail me the data, if you don't want to add it here)

**Comment by agraef** [comment]
You don't see much there, having instantiated the creb cosc~ abstraction, the system just runs into a "double free or corruption" error after which it aborts the program (Signal 6):

~~~
creating_object: list /home/ag/Sources/github/purr-data/packages/linux_make/build/usr/lib/pd-l2ork/extra/creb/cosc~ A_GIMME
double free or corruption (!prev)
Pd: signal 6
make: *** [Makefile:202: check] Error 1
~~~

FWIW, here's the full log of `make check`, run on the exact revision before I worked around this by getting rid of cos_cleanup:

[make-check-log.txt](https://github.com/user-attachments/files/17266990/make-check-log.txt)

**Comment by agraef** [comment]
And here's a little test patch in which I tried to replicate what's going on in the regression test as best as I could in vanilla:

[testpatch.zip](https://github.com/user-attachments/files/17267890/testpatch.zip)

This just contains the relevant abstractions from creb (cosc~.pd and sin~.pd) and a patch which creates a test subpatch with dynamic patching as the regression test would do it -- minus the absolute path to the abstraction, and replacing purr-data's $@ with $1 and the canvasinfo object which vanilla doesn't have with a placeholder symbol object.

But despite my best efforts I can't reproduce the crash in vanilla. My conclusion is that this is very likely a purr-data-specific issue which I'll have to investigate. The same is probably true for the other issue that I reported.

The fact of the matter is that we ship a *lot* of externals, and most of these still date back to the glorious pd-extended days. I've never used most of the legacy stuff myself, but I've touched most of them in order to fix compile warnings and errors over the years. Some of these have been completely unmaintained for well over a decade now. I'd say that many of them are still in need of a detailed audit to make sure that they're really 64 bit clean (yes, some of those externals are *that* old) and that they don't have any memory allocation and access issues, off-by-one bugs, etc. As you can probably imagine, such an audit would be a substantial amount of work, so this is not likely to happen anytime soon. Instead, we've relied on bug reports from our users so far to get these issues fixed, which hasn't worked out very well, TBH. That's probably because, just like me, most current users avoid at least the most ancient externals as much as possible.

I know for certain that there are some bad apples in there (pun intended), because some of the legacy externals make the engine crash in the native Apple Silicon port of purr-data (that's why we still rely on Rosetta 2 to run purr-data on modern Macs right now). I have a big cleanup planned for the not-so-distant future (GSoC 2025 at latest) in order to get the Apple Silicon port working, streamline the list of externals we ship, and update cyclone to the latest version. There will probably be some tears and gnashing of teeth when we do this. :) But we just can't drag along all these unmaintained legacy externals forever. I'll try to save as many of them as possible, though, since I see purr-data as pd-extended's spiritual successor, and preserving as much of the legacy is also a valuable service to the Pd community at large IMHO.

So the (embarrassing) TL;DR is that the real problem probably lies elsewhere and isn't likely to affect vanilla Pd in any way. Hence I will close both issues that I reported now; apologies for the false alarm!

**Comment by agraef** [comment]
IOhannes, I can't close #2456 because I didn't create it, can you please take care of this? Thanks.

**Comment by agraef** [comment]
It gets even more embarrassing. :( The double free was actually due to a botched backporting job, during which somehow cos_cleanup ended up as the freemethod of the class, instead of being set with class_setfreefn, as in the original source.

To my defense, I didn't do that part of the backport myself, but I certainly should have noticed this when I integrated those changes, or at least should have realized what's going on when I saw that cos_cleanup was being called in pd_free.

I'll look at the other issue #2456 now, which is more complicated, but I suspect that this might well be due to a similar glitch in the backport. Which means that I'll have to review every single chunk in that commit once again. Oh joy.

**Comment by agraef** [comment]
The other crash was actually due to moonlib/dinlet~ using the wrong t_vinlet data structure and initialization, so it's another downstream issue. Sorry again for wasting your time, IOhannes. :(

**Comment by umlaeute** [comment]
n.p. any bug found (and fixed) is good :-)

**Comment by agraef** [comment]
True. Even if I reported it on the wrong bug tracker. ;-)
