### ISSUE TITLE
crash bug in signal_makereusable()

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#2456]
There's another crash bug in `signal_makereusable()` where `sig->s_borrowedfrom` may be 0 even though `sig->s_isborrowed` is set, and since it's easy to fix and I'm too lazy to open another ticket, here's the fix:

~~~diff
--- a/src/d_ugen.c
+++ b/src/d_ugen.c
@@ -471,7 +471,7 @@ void signal_makereusable(t_signal *sig)
     if (THIS->u_loud) post("free %lx: %d", sig, sig->s_isborrowed);
     if (sig->s_isborrowed || sig->s_isscalar)
     {
-        if (sig->s_isborrowed)
+        if (sig->s_isborrowed && sig->s_borrowedfrom)
         {
             /* if the signal is borrowed, decrement the borrowed-from signal's
                 reference count, possibly marking it reusable too */
~~~

_Originally posted by @agraef in https://github.com/pure-data/pure-data/issues/2455#issuecomment-2388220951_

**Comment by umlaeute** [comment]
@agraef added
> The second issue might have a similar cause, but it's also different enough that I think that it would be prudent to look into this. For one thing, here `signal_cleanup()` is actually being called via `ugen_stop()`. So I think that there might still be some (possibly rare) conditions also in pure-data where `sig->s_isborrowed` is set but `sig->s_borrowedfrom` may be not.
>
> Our regression tests are designed to be very aggressive so they test conditions and shake out bugs that might rarely if ever arise in normal use. That's why we have them.

**Comment by umlaeute** [comment]
about the second issue (borrowed signals), here's a bit more context of the code you are patching:
https://github.com/pure-data/pure-data/blob/d0f2798de3c1a521de99a91e13b82e29af78096b/src/d_ugen.c#L472-L482

i think the intention of lines 478-480 is to be notified of an actual bug in the signal-borrowing code. your patch basically paints over this check, hiding it deeper (so yes, I agree with you that that should be looked into).

**Comment by agraef** [comment]
> your patch basically paints over this check

You're right, of course. It's not a fix, but simply prevents the segfault if `sig->s_borrowedfrom` happens to be NULL. The real questions to be asked there are:

- What's the right way to proceed after the `bug("signal_free")` call? Clearly, just going on with fingers crossed isn't the right thing, the NULL `sig->s_borrowedfrom` condition needs to be handled in some way, if the assumptions being made there are violated for some reason.

- More importantly, under which conditions is the implied invariant "if `sig->s_isborrowed` is set, then `sig->s_borrowedfrom` can't be NULL" violated. I'm beginning to suspect that this might actually be a purr-data issue, not a vanilla issue at all. Maybe I missed some bits and pieces while pulling this over. Which would be rather embarrassing. :(( So let me double-check that first.

**Comment by agraef** [comment]
Confirmed that this is actually a downstream issue, see https://github.com/pure-data/pure-data/issues/2455#issuecomment-2395618082. So this ticket can be closed.

**Comment by umlaeute** [comment]
good to know.
thanks for your efforts in hunting this down.
