### ISSUE TITLE
[pointer] set to a scalar looses it when another scalar is deleted

### ISSUE THREAD

**Issue by jyg** [pure-data/pure-data#2458]
I create scalars using [append my_struct x y] and I store the gpointer from output into a [pointer] object, for further animation . If I delete any other scalar in the patch, the [pointer] looses the link with the scalar it referenced. Is this a normal behaviour ?
![image](https://github.com/user-attachments/assets/e65620c2-e528-45e6-9370-71865b7ac795)

**Comment by Spacechild1** [comment]
> Is this a normal behaviour ?

Yes, it is. Deleting a scalar invalidates all pointers to any other scalar in the same canvas.

**Comment by porres** [comment]
so we can close this, huh?

**Comment by jyg** [comment]
May be this is not the right place to discuss about it, but I would like to understand why all other pointers are invalidated. Is this a design choice ? 
My use case : I'm using scalars to display popup menus and submenus items in the patch. If I delete the submenu items, I loose the pointers to the menu items. Do I have to [traverse( the patch every time a scalar is deleted?

**Comment by porres** [comment]
we can keep discussing things, but I'm just gonna go ahead and close this as it is a non issue :)
