### ISSUE TITLE
Fisty element typo

### ISSUE THREAD

**Issue by chr15m** [pure-data/pure-data#2460]
~/pd $ rgrep fisty doc/
doc/5.reference/canvas-help.pd:#X text 161 130 list - sets values into array \, fisty element is starting index (from 0)., f 74;

**Comment by porres** [comment]
thanks, like I said in the PR, use https://github.com/pure-data/pddp/issues instead. Fix is now at https://github.com/pure-data/pure-data/pull/2434/commits/0882d0262b6bdd997b13cb0c795170c5f50cb7ff
