### ISSUE TITLE
The file open dialog on Linux is very small

### ISSUE THREAD

**Issue by reduzent** [pure-data/pure-data#2477]
Actually,  ridiculously small considering common screen sizes nowadays:

![image](https://github.com/user-attachments/assets/7903f553-5f5c-46b6-a419-3fbc12b98796)

From what I gathered, the functions `tk_getOpenFile`  and `tk_getSaveFile` don't provide a way to set the window size. But it's worthwhile figuring out first, if people think it is a problem.

Personally, I think it is way too small, showing only 5 items out of very many. I drag it big every time once after each Pd start. Luckily, it remembers its last size.

**Comment by umlaeute** [comment]
you are right that `tk_getOpenFile` doesn't provide a way to set the window size programmatically (and if it did, any value we could fill in would most probably be wrong 70% of the time as well).
ideally, `tk_getOpenFile` would just fire up a "native" dialog (which knows what the user expects), but sadly it only does so on macOS (i think).

**Comment by umlaeute** [comment]
(personally, i don't feel inclined to spend time on solving this; while i understand that it is less than ideal, i just take it as the special look and feel of the underlying widgeting toolkit)

**Comment by reduzent** [comment]
OK. So I guess we can close this.

**Comment by umlaeute** [comment]
I dunno (whether it should be closed).
Paper cuts do cause pains and should eventually be fixed (even if it is low priority on *my* to-do list)
