### ISSUE TITLE
pd~ on windows

### ISSUE THREAD

**Issue by chikashimiyama** [pure-data/pure-data#251]
I'm trying to run a very heavy patch using pd~ on windows 10. The version of Pd is 0.48-0.
I opened simply pd~ help patch with DSP on, clicked "pd~ start pd~subprocess.pd" message box, 
then the second pd window opens and the application freezes. (all windows do not react to my mouse clicks)

**Comment by Lucarda** [comment]
Strange!
I couldn't replicate the issue. I opened [pd~] help patch, start the sub-process and everything is working as expected.

Win10
Pd 0.48.0

**Comment by Spacechild1** [comment]
hi, what's the output from the console? in which directory does your Pd live? pd~ doesn't like directory paths with whitespace. try to move your Pd folder to a path without whitespace and see if it solves the problem.

**Comment by Spacechild1** [comment]
@chikashimiyama is this still a problem with Pd 0.50 or can we close this?

**Comment by Spacechild1** [comment]
Closing because can't reproduce and OP doesn't respond. This has likely been fixed by one of my pd~ bugfixes.
