### ISSUE TITLE
Multi instance support for MIDI out

### ISSUE THREAD

**Issue by pierreguillot** [pure-data/pure-data#253]
Actually there is a multi instance support for MIDI in but not for MIDI out. It would be useful to have it. One easy solution would be to set the **outmidi_** functions inside the **pdinstance**. I'll try to find a solution but if you have suggestion ;)

**Comment by pierreguillot** [comment]
I guess a real easy solution would be to use the send/receive mechanism with symbol that support multi instance in the **outmidi_** functions (like the implementation of the **inmidi_** functions).
For exemple with libpd:
```
static void libpd_multi_noteon(int channel, int pitch, int velocity)
{
    t_atom av[3];
    SETFLOAT(av, (float)channel);
    SETFLOAT(av+1, (float)pitch);
    SETFLOAT(av+2, (float)velocity);
    libpd_message("camomile", "#noteout", 3, av);
}
```
All my instances are bind to the symbol **camomile** and now each instance should receive its specific notein events. Note I use a specific receiver mechanism that support the multi instance (not the one originally offered by libpd). 
I try it and close the issue if it works!

**Comment by pierreguillot** [comment]
ps: the same thing can be done for multi instance support on the post function

**Comment by danomatika** [comment]
Is this still an issue with Pd? I'd like to have this fixed at the source as opposed to wrapper/workarounds.

**Comment by danomatika** [comment]
I answered my own question: see #836
