### ISSUE TITLE
Pd 0.48 starts with -verbose by default on Windows

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#255]
this is just a minor inconvenience I stumbled across.

**Comment by umlaeute** [comment]
can it be that you just accidentally had the `verbose` checkbox ticked in your preferences (or had `-verbose` added to the startup-flags in the prefs) and forgot about it?

**Comment by umlaeute** [comment]
alternatively this might be a problem with *undefined behaviour*: `sys_verbose` (and a number of other variables) are not initialized explictely and therefore might contain bogus values (depending on your compiler)

**Comment by umlaeute** [comment]
forgot to say: if you are using a self-compiled Pd, does the problem go away if you change [`s_main:53`](https://github.com/pure-data/pure-data/blob/6f0141f307a4a873b8b167d6ae173430dc5d65cd/src/s_main.c#L53):

~~~diff
-int sys_verbose;
+int sys_verbose = 0;
~~~

**Comment by Spacechild1** [comment]
hmmm... actually the problem went away after I ticked/unticked verbose and saved all preferences. I deleted the Pd registry entry and restarted Pd to check the default behaviour again and now it's fine. probably I just had an old registry entry lurking around. the windows registry is such a mess... sorry for the noise!
