### ISSUE TITLE
[soundfiler] doesn't keep with "Right To Left Outlet Order"

### ISSUE THREAD

**Issue by Bendrien** [pure-data/pure-data#257]

**Comment by umlaeute** [comment]
please provide a context where and how this happens.

(otherwise i will close this as unreproducible.)

**Comment by Bendrien** [comment]
Oh I thought in this case it would be redundant. Here is a simple patch which shows this behaviour. As far as I know the print outputs are in the wrong order. It should be r: ... l: ... but its l: ... r: ...
![soundfiler](https://user-images.githubusercontent.com/17148056/33484540-f9752e78-d6a2-11e7-98e3-b56a7fda8880.PNG)

**Comment by danomatika** [comment]
This is a bug. Should be fixed in the 0.48-1 release.
