### ISSUE TITLE
Unnecessary buffer allocation in atom_getsymbol

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#26]
line 24 of m_atom.c

~~~C
t_symbol *atom_getsymbol(t_atom *a)  /* LATER think about this more carefully */
{
    char buf[30];
    if (a->a_type == A_SYMBOL) return (a->a_w.w_symbol);
    else return (&s_float);
}
~~~

'buf' is not used at all!

**Comment by umlaeute** [comment]
while it's true that the buffer is unnessessary and unused, it shouldn't have any impact on the runtime behaviour (e.g. speed and memory consumption of the function call). most likely the compiler will optimize the unused variable away anyhow...
