### ISSUE TITLE
pd-0.48-0 can not choose audiodev via cmdline flags in DOS-cmd-shell

### ISSUE THREAD

**Issue by tmusil** [pure-data/pure-data#260]
I used pd-0.48.0 vanilla under Win 7 with a class compliant USB-stereo-audio-converter (Lexicon Alpha Studio, only for testing, not for my ears). 
I tried "pd -audiooutdev 2" (also 0 and 1 and 3) , the audio setting showed me always to the internal device.
The popup showed both devices.
Under pd-0.47-1 everything worked correctly.

**Comment by Lucarda** [comment]
I tested 0.48.0 on win8.1 and `pd -audiooutdev n` is working as expected. I have 2 soundcards.

Does the Lexicon get listed with `pd -listdev` ?

**Comment by Lucarda** [comment]
But there is a bug using `-asio`:

I can choose from 1 to 7 -audiodev, all worked except the last one (7), it uses number 6.

The 7 can be accessed from the menu, but it don't get saved. When restarting uses 6.

: (

**Comment by tmusil** [comment]
OK , I couldn't repeat this issue. Maybe I was confused about the device indeces beginning with 0.
Sorry. Issue closed.
