### ISSUE TITLE
loadbang not sending to cloned/current abstractions after saving

### ISSUE THREAD

**Issue by fdch** [pure-data/pure-data#261]
- When saving a clone object (saving when a cloned abstraction is in focus), and the abstraction has a [loadbang], there is no loadbang message sent.

What I have to do then is `select` the [clone] object, `delete` and `undo` so that there is a loadbang. 

- When saving regular abstractions, the loadbang message is sent to other instances of the abstraction, not the current (just-saved) one. It is also not sent to cloned instances of the same abstraction.

**I think it makes sense that the currently saved abstraction received the loadbang message**. 
This issue might be related to: https://github.com/pure-data/pure-data/issues/242

**Comment by Spacechild1** [comment]
> It is also not sent to cloned instances of the same abstraction.

actually it is. maybe this has been fixed in the meantime?

> I think it makes sense that the currently saved abstraction received the loadbang message.

I rather think this would be super annoying. saving an abstraction doesn't necessarily mean you want to reinitalize it.

**Comment by Spacechild1** [comment]
@umlaeute can we close this?
