### ISSUE TITLE
compiling warning

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#274]
/Applications/Pd-0.48-1test3.app/Contents/Resources/src/g_canvas.h:48:9: warning: 
      'IOHEIGHT' macro redefined [-Wmacro-redefined]
#define IOHEIGHT 3       /* height of an inlet/outlet in pixels */
        ^
envelope.c:10:9: note: previous definition is here
#define IOHEIGHT 1

**Comment by Ant1r** [comment]
where does this "envelope.c" come from?

**Comment by Ant1r** [comment]
so this is not a pd issue... you just have to un/re/define IOHEIGHT, or use another name.

**Comment by umlaeute** [comment]
i agree with @Ant1r, that the problem ought to be fixed in the external.
