### ISSUE TITLE
factorial of negative values in [expr]

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#284]
<img width="171" alt="screen shot 2018-01-09 at 15 46 39" src="https://user-images.githubusercontent.com/5360142/34737232-4f55d4c6-f554-11e7-812c-4d010a962003.png">

As said in the image above, this freezes pd for a while and outputs 0...

Now, I don't know what the output should be, maybe minus infinity? 

Anyway, it seems a simple logic could prevent the factorial of negative values to be calculated (thus, preventing it from freezing Pd for a while).

**Comment by umlaeute** [comment]
`n!` with `n<0` is not defined.

**Comment by porres** [comment]
this has been fixed!
