### ISSUE TITLE
extra folder should have search priority over user added search paths

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#289]
Hi, in cyclone we have a hilbert~ object, that I'm trying to load only as [cyclone/hilbert~], so just "[hilbert~]" would still call the abstraction that resides in "extra".

But that never happens as it seems externals have priority in the search path before the extra folder.

So the only way I can load pd vanilla's hilbert~ is if I don't have cyclone in Pd's path or in [declare], which is bad...

this could be fixed if extra had priority in the search, which I think it'd be common sense, as Pd Vanilla objects actually do have priorities over externals in general.

cheers

**Comment by umlaeute** [comment]
i concur.

each and every software i know will prioritize in the following order:
1. user specific (e.g.  `%AppData%\Pd`)
2. administrator provided data (e.g. `%CommonProgramFiles%\Pd`)
3. system provided data (e.g. `%ProgramFiles%\Pd\extra`)

if you want to avoid nameclashes with "builtins", you shouldn't create them in the first place.

**Comment by porres** [comment]
> if you want to avoid nameclashes with "builtins", you shouldn't create them in the first place.

I don't have that option with cyclone, unless I just don't create the object. But we have successfully avoided nameclashes with "builtins" for many other objects in cyclone, because vanilla objects have a priority. Anyway, I don't wanna get into that details unless I really have to, or discuss cyclone. My only point is that this can't happen for the "extra" folder as it doesn't have the same priority and my consideration is that this is inconsistent behaviour.

> system provided data (e.g. %ProgramFiles%\Pd\extra)

I don't see extra as "system provided data", as its README states, it's a **library**, consisting of Pd
objects which are too specialized or otherwise non-canonical for inclusion into Pd proper. That is, these are Pd objects part of Pd Vanilla, but not as "internals".

These are objects that will automatically be loaded, like Pd internals, without the need to be imported or added to the path or anything. That is to say it is a default search folder that you don't need to worry about. That also shows how important and sort of "prioritized" they are, but the thing is that, as a library which comes as part of Pd Vanilla, it doesn't have any priority over other libraries that are specified in Pd's path. 

Unless I add it to the search path as the first option. Now, this is a path I don't really have to bother loading into Pd's path, why should I have to do it? It seems that it was just supposed to have such a priority, but it doesn't somehow - hence my motivation to open this issue.

cheers

**Comment by porres** [comment]
I ended up not including a [hilbert~] option for cyclone.

But I still think Pd Vanilla objects should have priorities over externals.

**Comment by danomatika** [comment]
ping @umlaeute @millerpuckette 

My first take was "oh no, recording paths might break something" but on this case, the following is a good point:

>this could be fixed if extra had priority in the search, which I think it'd be common sense, as Pd Vanilla objects actually do have priorities over externals in general.

This is not likely to change many setups unless they rely on putting *everything* in extra, however we've clearly demphasized this with [declare] and the Documents/externals directory + documentation.

**Comment by porres** [comment]
> reordering paths might break something

can't see how

> This is not likely to change many setups unless they rely on putting everything in extra

but how? If everything is in extra, things will still be found. It'll just look there first

**Comment by danomatika** [comment]
I think you misread my email. I was agreeing with and saying that changing this should *not* really break anything.

My first paragraph was about my initial reaction, not my later agreement.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by millerpuckette** [comment]
I'm scared of changing anything related to search paths - I can't see how
it won't just deepen the confusion and misery that already reigns - and I'm
sure somthing will break, as it always does when anything regarding search
paths gets touched.

cheers
Miller

**Comment by porres** [comment]
yeah, I can't see the issues, but my vision is limited anyway so I can't argue :) 

Since I'm now more worried about documenting Pd and editing the manual, I'm just concerned on understanding how it really works so I can explicitly explain this structure in that reference.

So it seems the search priority for externals is: relative folder (relative to the patch), then the user added search paths (in preferences => path), and then finally the standard paths (which still includes global system provided data, administrator provided data and finally the user/application folder - which is the 'extra' folder - in the very end of the search list.

It did make sense to me that "extra" should have a search priority over other externals, it seems weird to point out in the manual that this is the last place Pd will ever search for something - but maybe not that many people will question it as I did. Maybe if we say this is more of just another external library, and not something to be deeply connected to Pd itself, it can make more sense - otherwise it seems counterintuitive to me.

**Comment by porres** [comment]
and actually, as I'm revising Pd's manual, it does say pretty clearly, already, that 'extra' is searched for last. This may indicate it was all very intentional. If so, @millerpuckette  can you tell us the reasoning behind it?

**Comment by millerpuckette** [comment]
So that you can override stuff in extra with your own better objects.

**Comment by porres** [comment]
> So that you can override stuff in extra with your own better objects.

I don't think I can make better ones :) but that reminds me we could include some information on how Pd allows you to override internals with compiled objects, and then it can also include this idea that objects in 'extra' can also be overriden!

So I'll do that in my manual revision, and I might just say that the reason is because you can override stuff with better objects, cause it sounds funny :)  

Anyway, will close this issue and my PR

Thanks
