### ISSUE TITLE
abstractions in the extra folder are found multiple times 

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#291]
hi, I was checking out the output of the verbose flag when searching for the hilbert~ object, and I see that it finds it twice! After finding it it still searches again and finds it again, here's the output, I'm on Mac OS 10.12.6 with Pd 0.48-1

tried /Users/porres/Desktop/test/hilbert~.d_fat and failed
tried /Users/porres/Desktop/test/hilbert~.pd_darwin and failed
tried /Users/porres/Desktop/test/hilbert~/hilbert~.d_fat and failed
tried /Users/porres/Desktop/test/hilbert~/hilbert~.pd_darwin and failed
tried /Users/porres/Desktop/test/hilbert~.pd and failed
tried /Users/porres/Desktop/test/hilbert~.pat and failed
tried /Users/porres/Desktop/test/hilbert~/hilbert~.pd and failed
tried /Users/porres/Documents/Pd/externals/hilbert~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/hilbert~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/hilbert~/hilbert~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/hilbert~/hilbert~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/hilbert~.pd and failed
tried /Users/porres/Documents/Pd/externals/hilbert~.pat and failed
tried /Users/porres/Documents/Pd/externals/hilbert~/hilbert~.pd and failed
tried /Users/porres/Documents/Pd/sounds/hilbert~.d_fat and failed
tried /Users/porres/Documents/Pd/sounds/hilbert~.pd_darwin and failed
tried /Users/porres/Documents/Pd/sounds/hilbert~/hilbert~.d_fat and failed
tried /Users/porres/Documents/Pd/sounds/hilbert~/hilbert~.pd_darwin and failed
tried /Users/porres/Documents/Pd/sounds/hilbert~.pd and failed
tried /Users/porres/Documents/Pd/sounds/hilbert~.pat and failed
tried /Users/porres/Documents/Pd/sounds/hilbert~/hilbert~.pd and failed
tried /Users/porres/Documents/Pd/externals/cyclone/hilbert~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/cyclone/hilbert~.pd_darwin and succeeded
tried /Users/porres/Documents/Pd/externals/cyclone/hilbert~.pd and failed
tried /Users/porres/Documents/Pd/externals/cyclone/hilbert~.pat and failed
tried /Users/porres/Documents/Pd/externals/cyclone/hilbert~/hilbert~.pd and failed
tried /Users/porres/Documents/Pd/externals/else/hilbert~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/else/hilbert~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/else/hilbert~/hilbert~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/else/hilbert~/hilbert~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/else/hilbert~.pd and failed
tried /Users/porres/Documents/Pd/externals/else/hilbert~.pat and failed
tried /Users/porres/Documents/Pd/externals/else/hilbert~/hilbert~.pd and failed
tried /Users/porres/Documents/Pd/externals/soundhack/hilbert~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/soundhack/hilbert~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/soundhack/hilbert~/hilbert~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/soundhack/hilbert~/hilbert~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/soundhack/hilbert~.pd and failed
tried /Users/porres/Documents/Pd/externals/soundhack/hilbert~.pat and failed
tried /Users/porres/Documents/Pd/externals/soundhack/hilbert~/hilbert~.pd and failed
tried /Users/porres/Library/Pd/hilbert~.d_fat and failed
tried /Users/porres/Library/Pd/hilbert~.pd_darwin and failed
tried /Users/porres/Library/Pd/hilbert~/hilbert~.d_fat and failed
tried /Users/porres/Library/Pd/hilbert~/hilbert~.pd_darwin and failed
tried /Users/porres/Library/Pd/hilbert~.pd and failed
tried /Users/porres/Library/Pd/hilbert~.pat and failed
tried /Users/porres/Library/Pd/hilbert~/hilbert~.pd and failed
tried /Library/Pd/hilbert~.d_fat and failed
tried /Library/Pd/hilbert~.pd_darwin and failed
tried /Library/Pd/hilbert~/hilbert~.d_fat and failed
tried /Library/Pd/hilbert~/hilbert~.pd_darwin and failed
tried /Library/Pd/hilbert~.pd and failed
tried /Library/Pd/hilbert~.pat and failed
tried /Library/Pd/hilbert~/hilbert~.pd and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/hilbert~.d_fat and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/hilbert~.pd_darwin and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/hilbert~/hilbert~.d_fat and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/hilbert~/hilbert~.pd_darwin and failed
**tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/hilbert~.pd and succeeded**
tried /Users/porres/Desktop/test/hilbert~.pd and failed
tried /Users/porres/Documents/Pd/externals/hilbert~.pd and failed
tried /Users/porres/Documents/Pd/sounds/hilbert~.pd and failed
tried /Users/porres/Documents/Pd/externals/cyclone/hilbert~.pd and failed
tried /Users/porres/Documents/Pd/externals/else/hilbert~.pd and failed
tried /Users/porres/Documents/Pd/externals/soundhack/hilbert~.pd and failed
tried /Users/porres/Library/Pd/hilbert~.pd and failed
tried /Library/Pd/hilbert~.pd and failed
**tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/hilbert~.pd and succeeded**

**Comment by porres** [comment]
This sort of thing only seems to happen for abstractions in the extra folder, this is what I get with rev1~, which is found many many many times!

tried /Users/porres/Desktop/test/rev1~.d_fat and failed
tried /Users/porres/Desktop/test/rev1~.pd_darwin and failed
tried /Users/porres/Desktop/test/rev1~/rev1~.d_fat and failed
tried /Users/porres/Desktop/test/rev1~/rev1~.pd_darwin and failed
tried /Users/porres/Desktop/test/rev1~.pd and failed
tried /Users/porres/Desktop/test/rev1~.pat and failed
tried /Users/porres/Desktop/test/rev1~/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/rev1~/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/rev1~/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/rev1~.pat and failed
tried /Users/porres/Documents/Pd/externals/rev1~/rev1~.pd and failed
tried /Users/porres/Documents/Pd/sounds/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/sounds/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/sounds/rev1~/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/sounds/rev1~/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/sounds/rev1~.pd and failed
tried /Users/porres/Documents/Pd/sounds/rev1~.pat and failed
tried /Users/porres/Documents/Pd/sounds/rev1~/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~.pat and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~.pat and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~.pat and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~/rev1~.pd and failed
tried /Users/porres/Library/Pd/rev1~.d_fat and failed
tried /Users/porres/Library/Pd/rev1~.pd_darwin and failed
tried /Users/porres/Library/Pd/rev1~/rev1~.d_fat and failed
tried /Users/porres/Library/Pd/rev1~/rev1~.pd_darwin and failed
tried /Users/porres/Library/Pd/rev1~.pd and failed
tried /Users/porres/Library/Pd/rev1~.pat and failed
tried /Users/porres/Library/Pd/rev1~/rev1~.pd and failed
tried /Library/Pd/rev1~.d_fat and failed
tried /Library/Pd/rev1~.pd_darwin and failed
tried /Library/Pd/rev1~/rev1~.d_fat and failed
tried /Library/Pd/rev1~/rev1~.pd_darwin and failed
tried /Library/Pd/rev1~.pd and failed
tried /Library/Pd/rev1~.pat and failed
tried /Library/Pd/rev1~/rev1~.pd and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1~.d_fat and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1~.pd_darwin and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1~/rev1~.d_fat and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1~/rev1~.pd_darwin and failed
**tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1~.pd and succeeded**
tried /Users/porres/Desktop/test/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/rev1~.pd and failed
tried /Users/porres/Documents/Pd/sounds/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~.pd and failed
tried /Users/porres/Library/Pd/rev1~.pd and failed
tried /Library/Pd/rev1~.pd and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1~.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.d_fat and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd_darwin and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage/rev1-stage.d_fat and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage/rev1-stage.pd_darwin and failed
**tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded**
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-final.d_fat and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-final.pd_darwin and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-final/rev1-final.d_fat and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-final/rev1-final.pd_darwin and failed
**tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-final.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-final.pd and succeeded**

**Comment by porres** [comment]
This sort of thing only seems to happen for abstractions in the extra folder, this is what I get with rev1~, which is found many many many times!

tried /Users/porres/rev1~.d_fat and failed
tried /Users/porres/rev1~.pd_darwin and failed
tried /Users/porres/rev1~/rev1~.d_fat and failed
tried /Users/porres/rev1~/rev1~.pd_darwin and failed
tried /Users/porres/rev1~.pd and failed
tried /Users/porres/rev1~.pat and failed
tried /Users/porres/rev1~/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/rev1~/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/rev1~/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/rev1~.pat and failed
tried /Users/porres/Documents/Pd/externals/rev1~/rev1~.pd and failed
tried /Users/porres/Documents/Pd/sounds/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/sounds/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/sounds/rev1~/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/sounds/rev1~/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/sounds/rev1~.pd and failed
tried /Users/porres/Documents/Pd/sounds/rev1~.pat and failed
tried /Users/porres/Documents/Pd/sounds/rev1~/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~.pat and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~.pat and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~/rev1~.d_fat and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~/rev1~.pd_darwin and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~.pat and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~/rev1~.pd and failed
tried /Users/porres/Library/Pd/rev1~.d_fat and failed
tried /Users/porres/Library/Pd/rev1~.pd_darwin and failed
tried /Users/porres/Library/Pd/rev1~/rev1~.d_fat and failed
tried /Users/porres/Library/Pd/rev1~/rev1~.pd_darwin and failed
tried /Users/porres/Library/Pd/rev1~.pd and failed
tried /Users/porres/Library/Pd/rev1~.pat and failed
tried /Users/porres/Library/Pd/rev1~/rev1~.pd and failed
tried /Library/Pd/rev1~.d_fat and failed
tried /Library/Pd/rev1~.pd_darwin and failed
tried /Library/Pd/rev1~/rev1~.d_fat and failed
tried /Library/Pd/rev1~/rev1~.pd_darwin and failed
tried /Library/Pd/rev1~.pd and failed
tried /Library/Pd/rev1~.pat and failed
tried /Library/Pd/rev1~/rev1~.pd and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1~.d_fat and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1~.pd_darwin and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1~/rev1~.d_fat and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1~/rev1~.pd_darwin and failed
**tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1~.pd and succeeded**
tried /Users/porres/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/rev1~.pd and failed
tried /Users/porres/Documents/Pd/sounds/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/cyclone/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/else/rev1~.pd and failed
tried /Users/porres/Documents/Pd/externals/soundhack/rev1~.pd and failed
tried /Users/porres/Library/Pd/rev1~.pd and failed
tried /Library/Pd/rev1~.pd and failed
**tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1~.pd and succeeded**
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.d_fat and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd_darwin and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage/rev1-stage.d_fat and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage/rev1-stage.pd_darwin and failed
**tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-stage.pd and succeeded**
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-final.d_fat and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-final.pd_darwin and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-final/rev1-final.d_fat and failed
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-final/rev1-final.pd_darwin and failed
**tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-final.pd and succeeded
tried /Applications/Pd-0.48-1.app/Contents/Resources/Scripts/../extra/rev1-final.pd and succeeded**

**Comment by umlaeute** [comment]
i'm not sure what problem you are having.

the first time you load an abstraction, it is searched for two times:
- once to determine that the object is an abstraction (rather than e.g. a compiled external)
- the second time to actually load it

if the abstraction is used multiple times, the first step is skipped, and only the 2nd step is executed (so if you are using an abstraction *many many times* it will also be searched for (and opened) *many many* times).

**Comment by porres** [comment]
> (so if you are using an abstraction many many times it will also be searched for (and opened) many many times).

no, I'm loading it just once

**Comment by porres** [comment]
oh, I see, so it's common that it is searched and opened twice as an abstraction, ok... and the thing about rev1~ is that it's loading other internal abstractions not the same one over and over...

**Comment by porres** [comment]
I still don't understand why it goes over the same paths as before, redoing the same search, after finally getting to the same path and loading for good

**Comment by umlaeute** [comment]
well, either you trust my word and explanation or you have to read the source code.
i still don't understand what's your problem with the current behavior.

the *why* is very simple: it's an easy way to speed up search for abstractions without losing per-canvas searchpaths.

**Comment by porres** [comment]
> well, either you trust my word and explanation or you have to read the source code.
> i still don't understand what's your problem with the current behavior.

I don't really have a problem, and I trust your words, hence the questions. I just didn't get it, as it'd be more intuitive to me to just successfully load it the first time. I still kinda don't get it, but it's not important.

**Comment by umlaeute** [comment]
it's an implementation detail of how *loaders* work in Pd.
to re-iterate what i said above:

> the abstraction is searched for two times:
> - once to determine that the object is an abstraction (rather than e.g. a compiled external)
> - the second time to actually load it

the first pass is really there to determine which "loader" is to be used (e.g. the abstraction loader as opposed to a the lua loader), or more precisely to register the object `[hilbert~]` as an "abstraction" class.
the 2nd pass then calls the abstraction loader to instantiate the abstraction.
