### ISSUE TITLE
pd~ dooesn't work when installed with `sudo make -f makefile.gnu install`

### ISSUE THREAD

**Issue by avilleret** [pure-data/pure-data#293]
With the @millerpuckette vanilla build system on Linux (I mean that [makefile.gnu](https://github.com/pure-data/pure-data/blob/master/src/makefile.gnu)), `pd~` can't open patcher with this error : 

> error: pd~: can't stat /usr/local/lib/pd/pd

here is a full log of building, installing and running Pd.
https://gist.github.com/avilleret/783d967d48f4ada5b033309719c062d3
It comes from a Travis CI script that makes some unit test with pd patcher.

**Comment by umlaeute** [comment]
from your commit [bf6f465](https://github.com/OSSIA/libossia/commit/bf6f4656b7161e21f85c6d6460a1ec6720d8fa74), I assume that it is working correctly with autotools? can you confirm

**Comment by avilleret** [comment]
yes it does as the log says : https://travis-ci.org/OSSIA/libossia/jobs/332240789#L1250-L2791 (quite verbose)

**Comment by danomatika** [comment]
Issue is probably due to bad path check in https://github.com/pure-data/pure-data/blob/master/extra/pd%7E/pd%7E.c#L226

**Comment by danomatika** [comment]
Also, double check the location of the pd~ external. It should be in `/usr/local/lib/pd/extra/pd~` if so, the relative search path should be `../../bin/pd` which it's not getting right.

**Comment by umlaeute** [comment]
it seems that pd~ searches for the `pd` binary in `/usr/local/lib/pd/bin/` (and does not consider `/usr/local/bin/pd`).

however, the `makefile.gnu` only installs the `pd` binary into `$(prefix)/bin` and not into `$(libpdbindir)` - unlike the autotools makefile (see `src/Makefile.am:install-exec-hook`)

**Comment by danomatika** [comment]
I'd consider that a bug with the `makefile.gnu` install step.

**Comment by danomatika** [comment]
Maybe makefile.gnu should have two install targets:

* normal system install: /usr/local/lib/pd/bin
* local/folder install: /some/path/pd/bin

**Comment by umlaeute** [comment]
hmm, dunno; but what is wrong with just symlinking `$(bindir)/pd` to `$(libpdbindir)/pd`, just like it is done in autotools? or copying the same file into both directories (to keep it simple).

**Comment by danomatika** [comment]
I'm feeling more like it's simpler to change the actual bin file location from src to ../bin in the end to avoid all of the excessive symlinking to tcl & externals required for it to work with the autotools build. I've done it before with other autoconf/automake projects. I know it's not "the ONE right way" but it might be a decent concession to make to match the makefile builds and remove some of the custom rules complexity I added. ON some platforms like Windows, symlinking results in making a copy anyway.

In any case, maybe this is better discussion to have in a separate issue.

**Comment by umlaeute** [comment]
i'm not sure what problem you are trying to solve (the excessive symlinking in autotools to allow running Pd in-place?), but afaict the problem at hand is only about the result of `make install`(so the running-in-place is a none-issue here)

**Comment by danomatika** [comment]
Yes, I'm digressing. As originally pointed out, this is an install issue. :)

**Comment by Spacechild1** [comment]
@umlaeute can we close this?

**Comment by umlaeute** [comment]
probably @avilleret is the one to answer this :-)

but i guess it is just a matter of a error in the commit message (missing `Closes: `)

**Comment by danomatika** [comment]
Yeah, in general it catches “closes #00” or “fixes #00”.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com
