### ISSUE TITLE
support for 64bit soundfiles (and/or improve  soundfile error messages)

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#295]
recently i created a soundfile with floating-point samples, using something like:

~~~python
import numpy
import scipy.io.wavfile
scipy.io.wavfile.write("test.wav", 44100, numpy.array([1., 2., 3.]))
~~~

now opening this in Pd yields:
~~~
tried .../test.wav and succeeded
soundfiler_read: .../test.wav: unknown or bad header format
~~~

so i checked the file:

~~~sh
$ sndfile-info test.wav 
========================================
File : test.wav
Length : 82
RIFF : 74
WAVE
fmt  : 18
  Format        : 0x3 => WAVE_FORMAT_IEEE_FLOAT
  Channels      : 1
  Sample Rate   : 44100
  Block Align   : 8
  Bit Width     : 64
  Bytes/sec     : 352800
fact : 4
  frames  : 3
data : 24
End
~~~

it took a while (and firing up a printf debugger) to figure out the root of the problem: the created file has a bit-width for `64` (rather than the supported `16`, `24` (for PCM) or `32` (for IEEE_FLOAT).

it would be very nice if Pd could support reading 64bit IEEE_FLOAT wavs.

it would also be nice if Pd would yield a more specific error message, e.g. "unsupported sample width (64)" or similar

**Comment by danomatika** [comment]
I believe this is resolved with the sound file objects update and support for CAF files.

**Comment by Spacechild1** [comment]
Can we close this?

**Comment by umlaeute** [comment]
unfortunately not.

i still get:
> tried /tmp/test.wav and succeeded
> soundfiler read wave: test.wav: unsupported sample format

**Comment by umlaeute** [comment]
sidnote: opening a 64bit CAF file (created with `sndfile-convert test.wav test.caf`) doesn't work either.

in case someone cannot run the above python code or the conversion themselves, i'm attaching my test-patch and two test soundfiles: [doublesound.zip](https://github.com/pure-data/pure-data/files/14955906/doublesound.zip)

**Comment by danomatika** [comment]
I can look at it. For single-precision Pd, I'd assume it would cast to float samples? For double-precision it should "just work." IMO I agree it should either play or complain. In any case, fix will be in s_audio_caf.c header check. I can look later.enohp ym morf tnes-----------Dan Wilcoxdanomatika.comrobotcowboy.comOn Apr 12, 2024, at 10:07 AM, umläute ***@***.***> wrote:﻿
sidnote: opening a 64bit CAF file (created with sndfile-convert test.wav test.caf) doesn't work either.
in case someone cannot run the above python code or the conversion themselves, i'm attaching my test-patch and two test soundfiles: doublesound.zip

**Comment by danomatika** [comment]
For this to work, the bytespersample checks in both file type .c files can be extended to include 8 bytes per sample for 64 bit. Then, `d_soundfile.c` needs to handle sample conversion for `sf->sf_bytespersample == 8` in:
* soundfile_xferin_sample
* soundfile_xferin_words
* soundfile_xferout_sample
* soundfile_xferout_words

For the later, I think we can replace the internal `t_floatuint` with `t_sampleint_union`.

**Comment by danomatika** [comment]
I've added a `feature/sfsamples64` branch which allows for reading 64bit WAV and CAF headers successfully, however no samples are read since `d_soundfile.c` does not handle the case for `sf->sf_bytespersample == 8` yet.

**Comment by danomatika** [comment]
Ok, reading and writing now work with the latest commit. I have not tested with a double-precision build, but I assume it should work.

**Comment by umlaeute** [comment]
cool.
my quick test with a file generated like above shows it is working as expected.

while your are there AIFF would of course also be nice :-)

**Comment by danomatika** [comment]
Latest commits add 64 bit samples for AIFF/AIFC files. I need to next update the help files and track down a bug with "-little" to `writesf~` with AIFF and float samples.

**Comment by danomatika** [comment]
Ok, this is pretty much done on my end: #2261. Please test.

**Comment by Lucarda** [comment]
## tests on Windows (amd64)

### Pd64

- create a 64bit `wav` file with `soundforge`
- open the file with [readsf~]
- record the output of [readsf~] with [writesf~ -bytes 8]
- open the `soundforge` file with [soundfiler] to an array
- write the array (-bytes 8) with [soundfiler] as `wav` file 

all good.

### Pd

same as above. all good. I suspect that obviously there was a bit-depth truncation but the written files are 8 bytes.

:tada:

**Comment by porres** [comment]
can we close this?

**Comment by danomatika** [comment]
> can we close this?

I think so.
