### ISSUE TITLE
Some ASIO troubles.

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pure-data#298]
This is my device list

`pd -asio -listdev`

```
audio input devices:
1. MMIO:Microsoft Sound Mapper - Input
2. MMIO:Microphone (Mixing Driver 1 for
3. MMIO:Microphone (Mixing Driver 2 for
4. MMIO:Microphone (US-4x4)
5. ASIO:US-2x2 & US-4x4
6. ASIO:US-2x2 & US-4x4 Mixing Driver
audio output devices:
1. MMIO:Microsoft Sound Mapper - Output
2. MMIO:Speakers (Mixing Driver 1 for U
3. MMIO:Speakers (US-4x4)
4. MMIO:Speakers (Mixing Driver 2 for U
5. ASIO:US-2x2 & US-4x4
6. ASIO:US-2x2 & US-4x4 Mixing Driver
API number 4
```

When opening Pd like this:

`pd -noprefs -asio -blocksize 256 -audiobuf 6 -audiodev 6`

or this:

`pd -noprefs -asio -blocksize 256 -audiobuf 6 -audioadddev "ASIO:US-2x2 & US-4x4 Mixing Driver"` 

I get Pd audio settings with wrong driver “ASIO:US-2x2 & US-4x4”

![asio1](https://user-images.githubusercontent.com/25239522/35360034-17d11536-013b-11e8-98a3-76dc9bb4087a.jpg)

I can select from GUI the "ASIO:US-2x2 & US-4x4 Mixing Driver" 

![asio2](https://user-images.githubusercontent.com/25239522/35360043-23497d72-013b-11e8-8bb0-d574c1c03977.jpg)

But when I save prefs they take me back to the wrong “ASIO:US-2x2 & US-4x4”

pref file:

```
audioapi: 4
noaudioin: False
audioindev1: 4 2
audioindevname1: ASIO:US-2x2 & US-4x4
noaudioout: False
audiooutdev1: 4 2
audiooutdevname1: ASIO:US-2x2 & US-4x4
audiobuf: 6
rate: 44100
callback: 0
blocksize: 256
midiapi: 0
nomidiin: True
nomidiout: True
path1: C:/Users/Luccarda/Downloads/Pd-0.48-1-all-w64
path2: C:/Users/Luccarda/Downloads/Pd-0.48-1-all-w64/cyclone
npath: 2
standardpath: 1
verbose: 0
loadlib1: C:/Users/Luccarda/Downloads/Pd-0.48-1-all-w64/cyclone
nloadlib: 1
defeatrt: 0
flags: 
zoom: 1
loading: no
```

So I'm not sure if I get sound from "ASIO:US-2x2 & US-4x4 Mixing Driver"

**Comment by Atavic** [comment]
You should select:

>ASIO:US-2x2 & US-4x4

Then the system calls the *ASIO:US-2x2 & US-4x4 Mixing Driver* automagically.
You should select the actual hardware device and not its drivers, IMHO

**Comment by Lucarda** [comment]
> Then the system calls the ASIO:US-2x2 & US-4x4 Mixing Driver automagically.

No I don't think so. On other apps I can select which ASIO driver from those 2.

**Comment by Atavic** [comment]
>audioindevname1: ASIO:US-2x2 & US-4x4
audiooutdevname1: ASIO:US-2x2 & US-4x4

audio... *dev*name1 means the hardware device, so the choice is right.

On `pd -noprefs -asio -blocksize 256 -audiobuf 6 -audiodev 6`

I'd use `**5**. ASIO:US-2x2 & US-4x4` instead.

**Comment by Atavic** [comment]
audioindevname1: ASIO:US-2x2 & US-4x4
    audiooutdevname1: ASIO:US-2x2 & US-4x4

audio... *dev*name1 means the hardware device, so the choice is right.

On `pd -noprefs -asio -blocksize 256 -audiobuf 6 -audiodev 6`

I'd use `5. ASIO:US-2x2 & US-4x4` instead.

**Comment by umlaeute** [comment]
is this still an issue with Pd-0.49?

also the `-audiodev` flag is known to be 1-off depending on the platform. is this just one of these issues?
that is: does `-audiodev 3` give you `MMIO:Speakers (US-4x4)` (or is it `-audiodev 2` or `-audiodev 4`?

**Comment by Lucarda** [comment]
Is still happening with this sound card. May be is an issue for this device only.

`pd -noprefs -font 12 -asio -listdev -blocksize 256 -audiobuf 6 -audiodev 6`

```
audio input devices:
1. MMIO:Microsoft Sound Mapper - Input
2. MMIO:Microphone (Mixing Driver 1 for
3. MMIO:Microphone (Mixing Driver 2 for
4. MMIO:Microphone (2- High Definition
5. MMIO:Microphone (US-4x4)
6. ASIO:ASIO4ALL v2
7. ASIO:US-2x2 & US-4x4
8. ASIO:US-2x2 & US-4x4 Mixing Driver
audio output devices:
1. MMIO:Microsoft Sound Mapper - Output
2. MMIO:Speakers (Mixing Driver 1 for U
3. MMIO:Speakers (Mixing Driver 2 for U
4. MMIO:Speakers (2- High Definition Au
5. MMIO:Speakers (US-4x4)
6. ASIO:ASIO4ALL v2
7. ASIO:US-2x2 & US-4x4
8. ASIO:US-2x2 & US-4x4 Mixing Driver
API number 4
```

Starting with `-audiodev 6` gives me the correct "6. ASIO:ASIO4ALL v2".

when starting `-audiodev 8` i get "7. ASIO:US-2x2 & US-4x4".

I can select the "8 mixing driver" from the GUI and I get sound but not sure from where because when reopening the GUI "ASIO:US-2x2 & US-4x4" is displayed.

May be there's something portaudio don like about the sound card ( The mixing driver is kind of strange but I can use it with other apps):

![tascam](https://user-images.githubusercontent.com/25239522/46104636-399d2080-c1aa-11e8-80a9-780a788da496.jpg)


May be we can close this issue.

**Comment by Lucarda** [comment]
Oh, see pic above. Same resutls if "**External Effects(asio)**" is bypassed or not.

**Comment by Lucarda** [comment]
Something more:

All tests with 32 and 64 Pd's.
I have 2 other cards and I have no trouble with them.

**Comment by Atavic** [comment]
> when starting -audiodev 8 i get "7. ASIO:US-2x2 & US-4x4".

That's correct. The Driver is not an output device. It is the mixer for "7. ASIO:US-2x2 & US-4x4".

You shouldn't choose 8 but 7 IMHO.

**Comment by Lucarda** [comment]
But I can use the "Mixing driver" e.g on Ableton Live.
IIRC if using this driver other apps can also have sound.

**Comment by Lucarda** [comment]
I'm closing this issue as it seems to be something specific with the Tascam 4x4 device.
