### ISSUE TITLE
[clone] bug + fix: phase not preserved after [all( message

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#305]
clone_in_all() doesn't preserve the current phase, so [next( after [all( will always yield 0. 
here's a patch:
[clone.zip](https://github.com/pure-data/pure-data/files/1720972/clone.zip)

**Comment by Spacechild1** [comment]
moved here: https://sourceforge.net/p/pure-data/patches/584/

**Comment by umlaeute** [comment]
i've included this in #282 
in general i'd daresay that these days github is the better place to report bugs than sf.
