### ISSUE TITLE
[clone] crasher bug + fix

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#306]
bug in clone_free() which causes a segmentation fault if the number of cloned instances is smaller than then number of outlets. here's a patch:
[clone_free.zip](https://github.com/pure-data/pure-data/files/1722000/clone_free.zip)

**Comment by Spacechild1** [comment]
moved here: https://sourceforge.net/p/pure-data/patches/584/

**Comment by umlaeute** [comment]
i've included this in #282 
in general i'd daresay that these days github is the better place to report bugs than sf.
