### ISSUE TITLE
get number of cloned instances from inside [clone]

### ISSUE THREAD

**Issue by fdch** [pure-data/pure-data#312]
It would be useful to have such a feature from within a cloned abstraction.
For example, if I wanted to get number of cloned instances now, I would have to create [clone abs 20 20] and use $2 for such a thing, which feels redundant: it occupies a space that could be better used with a symbol or a more useful argument.

**Comment by Spacechild1** [comment]
internally, a cloned abstraction only knows that it's cloned but it doesn't have a handle to the "clone" object so right now it's not possible to get this information.
can't you just send the number of cloned instance to each instance from outside?

**Comment by fdch** [comment]
Well, yes. But sometimes I need to determine *where* the cloned abstraction is in the cloned sequence as soon as it is created. I realize now loadbang would work much better now (thanks:), so a more elaborate handle might not be unnecessary for now.

But, I guess I am after that handle to the clone object :)

**Comment by umlaeute** [comment]
I cannot think of any consistent way to *access* the number of clones to the cloned abstractions that is not already possible (either via an additional argument or via a a message).

but then, I don't really understand @Spacechild1's comment that "a cloned abstraction [...] knows that it's cloned" either...

**Comment by Spacechild1** [comment]
>but then, I don't really understand @Spacechild1's comment that "a cloned abstraction [...] knows that it's cloned" either...

I was referring to the `gl_isclone` bitfield in `t_glist` which is set to 1 in `clone_makeone()`

**Comment by umlaeute** [comment]
a well, yes; but this is not accessible from the *abstraction* :-)

**Comment by Spacechild1** [comment]
with "internally" I meant "on the code level", sorry.

**Comment by LGoodacre** [comment]
BTW you can achieve this fairly easily within the patch:

![screenshot from 2018-04-14 18-46-06](https://user-images.githubusercontent.com/22167643/38769433-2d073666-4014-11e8-9a62-75b43eae1c08.png)

**Comment by fdch** [comment]
I have been thinking about this issue.

What if we change the `loadbang` message within cloned abstractions to a `list` with data?

This is what I have in mind, which relates to `canvas_loadbangabstractions()` in g_canvas.c

Once `canvas_loadbangabstractions()` detects `clone_class`
- get useful data from `t_clone`, like `x_n, x_argc` ...
- instead of `gensym("loadbang")`, send a `list` with that data

The only real difference would be to [t b] `loadbang` inside a clone so that you have the previous behavior. Or, perhaps we can have a flag to disable/enable this loadbang replacement...

I realize these might be deep waters, but, Would this be feasible?

**Comment by Spacechild1** [comment]
what would be the gain for risking to break backwards compatibility? what problem are you trying to solve? when you do [clone 10 foo], you already know you have 10 instances, so just send the number to each instance or pass it as an creation argument. if you need to know the number of *all* cloned instances of 'foo', Liams method above does the trick.

**Comment by Spacechild1** [comment]
>  I would have to create [clone abs 20 20] and use $2 for such a thing, which feels redundant: it occupies a space that could be better used with a symbol or a more useful argument.

ok, I see where you're coming from, but I think this is a purely cosmetic concern. if the number of instances is important for each abstraction, there's nothing wrong with just passing it in just like any other argument, even if looks redundant. I just don't recommend touching [loadbang].

**Comment by fdch** [comment]
Very good point, indeed. Thank you for pointing that out. 

I agree, I would not want to mess with backwards compatibility. Also, I realize the risk here, simply because most patches would have a loadbang somewhere. 

But, I would say that this change in loadbang can be a highly restricted one. It would *only* affect cloned abstractions, and, revising what I wrote above, it can simply be called for with a flag in `t_clone`. So if you get `clone_class` and the struct has, say, `x_loadbang=1`, you get a different loadbang behavior...

**Comment by fdch** [comment]
I have to say, though, that I am not sure if I am missing something here, because I don't fully understand how `pd_vmess()` is working from `canvas_loadbangabstractions()` ...

**Comment by Spacechild1** [comment]
> But, I would say that this change in loadbang can be a highly restricted one.

many if not most cloned abstractions use [loadbang] so I wouldn't call this restrictive. outputting something else than a *single* bang will break simple things like [loadbang] -> [f $0]. again, better don't touch loadbang!

**Comment by fdch** [comment]
:) I see.

I now realize that what I wrote would require to add a second method to loadbang `loadbang_list` and something like another `action` ... quite a lot of messing around with [loadbang] 

Thanks for taking this b*awkward*-incompatible solution into account, though :) 

I still think it is not a cosmetic concern, and more things can come out of having data from the `t_clone` struct available from inside the cloned abstraction.

**Comment by fdch** [comment]
Perhaps this could be achieved if initbang / closebang enter into the picture #496?

**Comment by umlaeute** [comment]
knowing the number of cloned instances is orthogonal from initialising a patch.
for the latter we have `[loadbang]`.
for the former we have nothing, but I don't see any compelling reason why `[loadbang]` (or `[initbang]`) should be overloaded with this unrelated feature. (to throw in sume unconstructive ideas: We could also overload `[soundfiler]` of `[closebang]` to provide this information).

i agree with @Spacechild1 that you are mostly looking for *syntactic sugar* (what @Spacechild1 calls "cosmetic"), which is nothing bad per se. `[loadbang]` is most likely^W^Wcertainly the wrong place for this.

**Comment by fdch** [comment]
I see! I realize now that this issue is not *quite* an issue, in this cosmetic sense, so I'll close it.

Thanks for taking it into account!!

As an outro, I will still suggest that having a cloned instance with a notion of itself (and of its other clones) could be an interesting thing to have :) ...then again, it might just be a good idea for a movie...

**Comment by mxa** [comment]
I just found myself in the situation where I would have needed this feature. Guess i am going with [clone abstraction 20 20] for now.
