### ISSUE TITLE
README

### ISSUE THREAD

**Issue by tiagmoraismorgado** [pure-data/pure-data#32]
greetings. My name is Tiago Morais Morgado I have been using pure data since 2007, although not always in a systematic way, once I also work with other tools. I would suggest you guys to create a duplicate version of README in both txt and md format, so that we can actually stylize the README file using stylization

**Comment by danomatika** [comment]
Thanks for the suggestion. Markdown files look better on Github but most people using macOS or Windows won't be able to open the .md files directly. With .txt files they can, so we will likely stay with .txt files in lieu of better styling for now.

**Comment by luzpaz** [comment]
Sorry to resurrect this, but @danomatika would you consider having both `.md` and `.txt` ? Other projects are doing this as well.

**Comment by danomatika** [comment]
I personally would prefer to only have to worry about 1 file to maintain. Historically, this project has always had a .txt file so that has precedence.

**Comment by danomatika** [comment]
Also, the readme is so short there isn't much to render other than the header tags. Github is already rendering the links as it is.

**Comment by luzpaz** [comment]
Fair enough
