### ISSUE TITLE
what if suddenly pure data would feature a qtquick UI with a better aesthetic appeal then MaxMSP

### ISSUE THREAD

**Issue by tiagmoraismorgado** [pure-data/pure-data#33]
another cool suggestion I would like to make, is that perhaps, we could think of a way of suddenly making a qtquick UI with a better aesthetic appeal then even MaxMSP one. I can contribute to this, but I will need the help of people in the community to accomplish such an issue

**Comment by umlaeute** [comment]
ah yes. this has been an ongoing discussion for the last 10 years.

**Comment by chr15m** [comment]
@tiagmoraismorgado you should check the purr-data project by Jonathan Wilkes it has many cool & fancy new UI features https://git.purrdata.net/jwilkes/purr-data

**Comment by danomatika** [comment]
As @umlaeute mentions, this is an ongoing discussion and best moved to the pd-dev list. Closing for now.
