### ISSUE TITLE
0.48's new tcl/tk not handling colors well

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#331]
An easy way to test this is with [hcs/colorpanel], but you can also test with any GUI and set its color, then reopen and just hit "ok" again. Slowly, this keeps changing the color, which means it's not being able to set the color just right and keeps adding an offset to it.

I tested with vanilla 0.47-1 and it works fine, so I think it's the new tcl.tk upgrade in 0.48 that ruined it somehow! I tested this in 0.48-1 and 0.48-0 to confirm that and I've only used the 64 bits macOS applications.

If you're testing this with [hcs/colorpanel], it becomes quite clear and easy. In its help file, just "bang" it to open the color picker and hit "ok" over and over. Supposedly the same color would come out, but you'll see that at each iteration the color changes. But it doesn't do that in 0.47-1

**Comment by porres** [comment]
ok, here's a test that doesn't require externals.

open the color of any GUI, go to "compose color" and the RGB values, set them to 127 each

<img width="226" alt="screen shot 2018-03-20 at 15 24 06" src="https://user-images.githubusercontent.com/5360142/37675007-dff28e0e-2c52-11e8-97bc-4c33899eb992.png">

hit ok to get out of  "compose color", you don't even have to hit ok to come out of the color settings, just hit "compose color" again, and you'll see the values changed to "107"

<img width="223" alt="screen shot 2018-03-20 at 15 23 25" src="https://user-images.githubusercontent.com/5360142/37675064-0d8ba9a4-2c53-11e8-8b88-f92a2c555d8b.png">

**Comment by porres** [comment]
As you can see, this is really annoying, as you can't set the right color and you get a quite different one instead!

**Comment by danomatika** [comment]
>so I think it's the new tcl.tk upgrade in 0.48 that ruined it somehow!

PD on Linux and Windows have used Tk 8.5 for years... is it "ruined" there too?

**Comment by Lucarda** [comment]
On Windows it works fine:

![t85](https://user-images.githubusercontent.com/25239522/37942357-0a76ae08-3149-11e8-88e8-34b21d1a6324.jpg)

**Comment by mxa** [comment]
I can confirm the bug for Linux. If you set the colors numerically they are not saved. If you change the colors with the color sliders in the poperties, then their value will be saved. By the way it's impossible to get 127 as a value with those sliders, I can do 126 or 128, but not 127.

![screenshot from 2018-03-28 17-57-18](https://user-images.githubusercontent.com/1220707/38041232-85f47196-32b1-11e8-9a19-fadbe15f2a17.png)

**Comment by porres** [comment]
> By the way it's impossible to get 127 as a value with those sliders, I can do 126 or 128, but not 127.

Can't you type it in?

**Comment by mxa** [comment]
Yes but then it's not persistent.

**Comment by porres** [comment]
ok, now I'm confused.

when you set a color, what is the output/outcome? Different? What happens when you reopen the properites?

**Comment by mxa** [comment]
Basically typing in the numbers has no effect, these numbers will not be saved. Sliders work as expected minus they are too short, so there aren't 255 pixels wide which means you can't access all the numbers.

**Comment by porres** [comment]
so it's a different bug altogether I guess

**Comment by mxa** [comment]
indeed.

**Comment by porres** [comment]
could you please report it then as a separate one? cause I don't think they might even be related

**Comment by mxa** [comment]
https://github.com/pure-data/pure-data/issues/339

**Comment by porres** [comment]
Ok, so now we can confirm this is only a Mac issue, thanks guys

**Comment by danomatika** [comment]
Is this still an issue to has it been fixed via newer versions of Tk in the meantime?

**Comment by porres** [comment]
YAY!!!! IT HAS BEEN FIXED, WHAT A BEAUTIFUL DAY!!!

confirming it works now in macOS 10.14.6, Pd-0.52 test2
