### ISSUE TITLE
Linux: Color properties not saved when entered numerically.

### ISSUE THREAD

**Issue by mxa** [pure-data/pure-data#339]
When color properties in the `Compose color` dialogue are entered numerically in the properties they will be ignored and not applied/saved. The sliders do work as expected with the caveat that they are shorter then 255 pixels wide (161 pixels), so not every possible value can be applied.

![screenshot from 2018-03-28 17-57-18](https://user-images.githubusercontent.com/1220707/38097173-f2e7cbd6-3374-11e8-8cd6-f837548f3f4e.png)

**Comment by porres** [comment]
Ok, so now we confirm this is only a Mac issue

**Comment by umlaeute** [comment]
is this still a problem?

because it seems to work here nicely (although i have to hit <kbd>Enter</kbd> whenever i changed either one of the red/green/blue values or the full-color specifier (in your example `#7e7e7e`)

**Comment by mxa** [comment]
duh. Seems this was working all along, I'm just spoiled by the more streamlined user experience in Inkscape or gimp where a confirmation with enter isn't necessary to change the color.
