### ISSUE TITLE
what about [drawtext] / [drawsymbol] documentation?

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#342]
both of these are missing in help-intro.pd

[drawtext] is not mentioned in any help file

**Comment by HenriAugusto** [comment]
Also curiously when you open the help file for [drawnumber] or [drawsymbol] it opens a file named *drawtext-help.pd*. And neither [drawsymbol] or [drawtext] appears in *help-intro.pd* (the main help file).

**Comment by umlaeute** [comment]
@HenriAugusto this is intentional: the two objects share the same help-patch.

**Comment by HenriAugusto** [comment]
I know :) Just like other may other like midi objects and stuff. 

Just saying that it adds to the confusion. Right now, for example, i can't even tell if [drawtext] and [drawsymbol] does the same thing. The and the fact that neither appears on *help-intro* makes it kind of obscure.

**Comment by porres** [comment]
> the fact that neither appears on help-intro makes it kind of obscure.

hence I opened this issue ;)

i could easily make a pull request for this when the new version starts popping up
