### ISSUE TITLE
[page] documentation?

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#343]
this object is not mentioned anywhere, as an obsolete object or anything

looks like an obsolete object, so it could be mentioned as "obsolete" in help-intro.pd

**Comment by umlaeute** [comment]
it's just an alias for `pd` for ispw-max compatibility.

most aliases are not documented.

**Comment by porres** [comment]
> most aliases are not documented

ok, but shouldn't they? I guess it couldn't hurt
