### ISSUE TITLE
Add 'fmod' operator to 'expr'

### ISSUE THREAD

**Issue by Bendrien** [pure-data/pure-data#344]
I would like to use the fmod operator inside expr.

**Comment by porres** [comment]
well, expr has an fmod operator, check its help file

**Comment by Bendrien** [comment]
i think only expr~

Am 01.04.2018 um 19:01 schrieb Alexandre Torres Porres:

**Comment by porres** [comment]
nope, expr and fexpr~ too

**Comment by porres** [comment]
again, just check its help file, it now includes all functions in there since Pd 0.48

**Comment by Bendrien** [comment]
Oh ok. sry for the inconvenience i got it now.

**Comment by porres** [comment]
no problem!

cheers
