### ISSUE TITLE
wrapped around menu bar causes window to shrink or move when it is opened

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#348]
so far, this seems to happen on Windows and Ubuntu but not on OSX (I guess because there's no menu bar)

here's a minimal example:
[shrink-test.zip](https://github.com/pure-data/pure-data/files/1884668/shrink-test.zip)

**Comment by umlaeute** [comment]
this is a known side-effect of https://github.com/pure-data/pure-data/pull/44
(of course, a fix would be preferred)

**Comment by umlaeute** [comment]
i think i finally found a solution for this... (see #1296)

**Comment by umlaeute** [comment]
ah, actually i t still *shrinks* (but only on Windows).
the code in #1296 at least prevents the window from *moving* if the menubar  is wrapped.
