### ISSUE TITLE
consistency error with "add-to-path" message

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#351]
the new "add-to-path" message - which was added with https://github.com/pure-data/pure-data/commit/c917dd1938e8b48927dc6414916bdc47bbcfeb34 - prints a consistency check error (consistency check failed: sys_decodedialog: "path"), even though it succeeds in adding a path.

<img width="527" alt="screen shot 2018-04-20 at 12 45 02" src="https://user-images.githubusercontent.com/5360142/39060776-ad6ab8ea-4498-11e8-9e82-56b2b4542dc5.png">

**Comment by porres** [comment]
Well, by checking the code, the error goes away if the symbol starts with "+", so I did that to my code and it works fine without errors.

<img width="503" alt="screen shot 2018-04-20 at 13 09 36" src="https://user-images.githubusercontent.com/5360142/39062078-c3d1f13a-449c-11e8-89cf-773606091707.png">

So there might be no issue at all, and I can just ask why do we need a "+" then?

**Comment by umlaeute** [comment]
the `+` prefix is (most likely) a qualifier telling Pd that the file is indeed encoded.

**Comment by porres** [comment]
thanks!
