### ISSUE TITLE
functions keys not working on pd-0.48

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#352]
This is with pd 0.48 and 0.48-1 4 bits on macOS 10.12.6, with a macbook Pro using the new touchbar thingy.

But it was working with Pd < 0.48. Here's a screenshot of 0.48-1 on the left and 0.47-1 (also 64 bits) on the right when trying to get "F4", but other functions keys (F1, F2, etc) have a similar issue. This also affects an external like [cyclone/comment] which uses "F4".

<img width="1100" alt="screen shot 2018-04-22 at 18 43 55" src="https://user-images.githubusercontent.com/5360142/39100266-b124c09a-465d-11e8-9200-019bcf2130a2.png">

I also find it funny how [key] and [keyup] 0.48 spit out a big number when hitting a function and 0.47 doesn't

**Comment by umlaeute** [comment]
so is the big-number unique? (e.g. it differs between <kbd>F4</kbd> and  <kbd>F5</kbd>)

also, which tcl/tk version are the two binaries using?
if you cannot tell, you might want to install the `tclprompt-plugin` and run the following command in the new `Tcl` entry just below the Pd-console (after re-starting Pd):

~~~tcl
::pdwindow::post "Tcl:${tcl_version} Tk:${tk_version}\n"
~~~

**Comment by porres** [comment]
> so is the big-number unique? (e.g. it differs between F4 and F5)

It differs, F4 = 63239 / F5 = 63240

Log 4 in 0.48-1 gives me Tk 8.5.19, but I can't get it like that in 0.47, but I know from the Pd list it was using an earlier 8.4 version

**Comment by porres** [comment]
yeah, this seems like a mac only issue

**Comment by danomatika** [comment]
I see this too. Looking into it today.

**Comment by danomatika** [comment]
>if you cannot tell, you might want to install the tclprompt-plugin and run the following command in >the new Tcl entry just below the Pd-console (after re-starting Pd):

@umlaeute You don't need to do this with 0.48+ as I added the TK version as a verbose print.

**Comment by danomatika** [comment]
Actually, the modifier keys do not give good values either (command, control, option, shift).

This looks like another change between the Carbon and Cocoa implementations of Tk. The [tk keysyms table](https://www.tcl.tk/man/tcl/TkCmd/keysyms.htm) is derived rom X windows and I think the special key vales are slightly different in Cocoa. I'm able to fix the F* keys by adding more keysym matching to `canvas_key` in g_editor.c or is it better to translate this on the GUI side in `::pd_bindings::sendkey`?

**Comment by umlaeute** [comment]
my intuition says that the pd-gui would be the more appropriate place for this.
ideally, Pd-core shouldn't need to know anything about the framework that is used for the GUI...

**Comment by danomatika** [comment]
I agree, however there is already a good amount of keysym matching in the core, hence my question.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by danomatika** [comment]
I've done some more testing and the modifier keys are broken by Tk itself. Using the modified TK 8.5.19 from @millerpuckette fixes this as it appears to be related to #213.

**Comment by danomatika** [comment]
#442 is a fix for this.

**Comment by porres** [comment]
works!
