### ISSUE TITLE
suggestion: expand trigger's functionality as in Purr Data

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#354]
this is coming from a request I've seen on the facebook group. In a user discussion, someone brought it up how [trigger] in Purr Data has a different behaviour and it'd be cool if Vanilla worked like that too.

I think they got this from max, where number arguments are just sent to the corresponding outlet, whatever comes in.

<img width="184" alt="screen shot 2018-05-03 at 11 25 35" src="https://user-images.githubusercontent.com/5360142/39582624-ba635382-4ec4-11e8-8def-f72b57b57951.png">

as having number arguments is not something documented or what people should be doing in vanilla, I don't think this breaks anything

**Comment by mxa** [comment]
Not only numbers, any constants like symbols too. Max help looks like this: ![photo_2018-09-16_11-50-09](https://user-images.githubusercontent.com/1220707/45595094-b0663c80-b9a6-11e8-9872-25ba1c84386e.jpg)

**Comment by umlaeute** [comment]
so sending "2" to [trigger float gloat] gives you both `2.0` and `gloat`?

sounds like a great feature to me. not.

**Comment by porres** [comment]
i have to say this was coming from a personal concern that purr data and vanilla could be more compatible, but this seems to be a lost battle and i'd better just give up...

if a more flexible and powerful object is needed, I can come up with an external... and I know that this would only have a better shot for consideration if I ended up doing a Pull Request or something and I guess I'm not...

**Comment by umlaeute** [comment]
i don't really like the `symbol` feature, as it clashes with the current use of arguments.
this is not a problem with numbers (and already seen in e.g. ´[pack]`).

whether it is actually a good idea to add yet another functionality to `[trigger]` ("outputting *const*-values"; in addition to the current "force execution order" and "convert between message-types"), might be discussed separately.

**Comment by porres** [comment]
Anyway, with another request for this feature, I just thought I'd give it a shot so I created a Pull Request that includes the code and features from Purr Data

**Comment by porres** [comment]
I've split this issue into two new ones; see https://github.com/pure-data/pure-data/issues/691 and https://github.com/pure-data/pure-data/issues/692
