### ISSUE TITLE
seed not working for [random]

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#369]
Can anybody else confirm? I tried sending it "seed 123" to a [random 100] object, but I always get a different result.

**Comment by fdch** [comment]
seems to be working as expected in 0.48.1

**Comment by porres** [comment]
I'm using that, can you share a patch with me and tell me the expected behaviour?

**Comment by fdch** [comment]
afaict, the expected behavior is: if you send two [random] objects the same seed value, you would get the same output (even every time you open the patch). Otherwise, the seed is taken from the system time on each instantiation.

**Comment by porres** [comment]
yeah, it's working :)
