### ISSUE TITLE
[netsend] connecting to non-open port via TCP locks Pd (watchdog awakes)

### ISSUE THREAD

**Issue by musger** [pure-data/pure-data#378]
Trying to connect to a non-existing IP address via TCP, or to an existing one but on the wrong port number will lock Pd, causing it's console to print
`watchdog: signaling Pd`
This does not happen when connecting to localhost or when using UDP.

**Comment by umlaeute** [comment]
on a Debian system, when via TCP/IP with `[connect 8.8.8.8 9876(` (an existing server that doesn't serve on that port), the system stalls for about 130seconds (`[realtime]` gives me *129543ms*)

**Comment by Spacechild1** [comment]
on my Windows 7 machine it's about 20 seconds.

**Comment by umlaeute** [comment]
anyhow, this seems to be system specific (i get the same timeout of 129seconds, when doing a simple `nc 8.8.8.8 9876` on the terminal)

**Comment by Spacechild1** [comment]
I still think it would be a good idea to be able to set the timeout. And maybe set a lower default (system independent) timeout. I can give it a try.

**Comment by umlaeute** [comment]
something like this should do the trick:

~~~
    t_float ftimeout = 1500; /* in ms */
    struct timeval timeout;
    timeout.tv_sec = (int)(ftimeout/1000.);
    timeout.tv_usec = (int)(ftimeout-1000*timeout.tv_sec)*1000;
    if (setsockopt (sockfd, SOL_SOCKET, SO_SNDTIMEO, (char *)&timeout,
                sizeof(timeout)) < 0)
        error("setsockopt:sndtimeo failed\n");
~~~

**Comment by danomatika** [comment]
I’m doing some work on these objects and will roll this in.

**Comment by danomatika** [comment]
#577 includes a settable netsend timeout which defaults to 10 seconds.

**Comment by musger** [comment]
Great!
but will this then block my system as described in the original post,
but only for 10 seconds rather than forever when connecting to a
non-existing IP address of non-open port?

Thanks!

* Dan Wilcox <notifications@github.com> [2019-08-11 03:53]:

**Comment by danomatika** [comment]
>but will this then block my system as described in the original post,
but only for 10 seconds rather than foreve

By default, yes. And this default applies to all operating systems rather than the, sometimes quite divergent OS defaults.

However, you can now also do `[timeout 0, connect 127.0.0.1 3000<` which disables the timeout and returns immediately...

**Comment by Spacechild1** [comment]
> However, you can now also do [timeout 0, connect 127.0.0.1 3000< which disables the timeout and returns immediately...

note that `[timeout 0(` is not be a good idea because it might timeout too early. It seems to work when connecting to a local IP, but connecting to a remote server like "www.google.com 80" won't work. I'll update the help patch. There are two more things I've wanted to fix but forgot. I'll make a PR in a couple of minutes.

**Comment by musger** [comment]
* Dan Wilcox <notifications@github.com> [2019-08-11 11:04]:
> >but will this then block my system as described in the original post,
> but only for 10 seconds rather than foreve
> 
> By default, yes. And this default applies to all operating systems rather than the, sometimes quite divergent OS defaults.
> 
> However, you can now also do `[timeout 0, connect 127.0.0.1 3000<` which disables the timeout and returns immediately...
Which is what I should do if I want to connect from a patch processing
audio and messages without audio or message dropouts.
Please don't beat me if this has been discussed already, but couldn't
netsend have its own thread and then not block Pd but having enough time
to connect to a WAN IP?

**Comment by Spacechild1** [comment]
asynchronous connect has been discussed as a feature, but I think this is too much for now (the PR is already *huge*). This is definitely something to be added in the future - together with threaded sending!

**Comment by Spacechild1** [comment]
> but couldn't netsend have its own thread 

technically, we don't even need a thread for asynchronous connect because we already use "connect" on a (temporarily) non-blocking socket + "select". This means we could repeatedly call "select" with a 0 timeout, but this would need some refactoring.

**Comment by danomatika** [comment]
On a local network it might be fine but of course a reasonable timeout is at least 1-2 seconds.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by Spacechild1** [comment]
fixed because `[netsend]` now has a `[timeout(` message

**Comment by musger** [comment]
Thanks Christof, 
as asked before, let me ask again if message and/or audio processing are
suspended while I try to connect from a netsend object for the duration
of "timeout"? Will it still lock Pd if I don't specify a timeout? Then,
despite thre great work and PR for which I am sure everyone is very
thankful, let's leave this issue open, as the situation is still
persisting.

**Comment by Spacechild1** [comment]
>  if message and/or audio processing are suspended while I try to connect from a netsend object for the duration of "timeout"?

yes

> Will it still lock Pd if I don't specify a timeout?

The default timeout is now 5 seconds (I think), so you're original issue is resolved.

Checkout this new feature request, which I think is what you want: https://github.com/pure-data/pure-data/issues/950

**Comment by musger** [comment]
It definitely is what I wand, thanks a lot!

* Christof Ressi <notifications@github.com> [2020-04-18 19:08]:
> >  if message and/or audio processing are suspended while I try to connect from a netsend object for the duration of "timeout"?
> 
> yes
> 
> > Will it still lock Pd if I don't specify a timeout?
> 
> The default timeout is now 5 seconds (I think), so you're original issue is resolved.
> 
> Checkout this new feature request, which I think is what you want: https://github.com/pure-data/pure-data/issues/950

**Comment by danomatika** [comment]
Default timeout is 10 seconds, not 5.

**Comment by Spacechild1** [comment]
Thanks. I was too lazy to look it up :-)
