### ISSUE TITLE
"format s, 42"--[oscparse] crash

### ISSUE THREAD

**Issue by claudeha** [pure-data/pure-data#379]
https://github.com/pure-data/pure-data/blob/f83c88ba7ac68368248797ef0d0febc3526432bb/src/x_misc.c#L555

           if (*sp)
                typecode = *sp++;
            else if (argv[j].a_type == A_SYMBOL)
                typecode = 's';
            else typecode = 'f';
            if (typecode == 's')
                msgindex += ROUNDUPTO4(strlen(argv[j].a_w.w_symbol->s_name) + 1);

`oscformat` trusts the type code given in the format specifier `sp`, before checking the type of the atom.  When the type code is `'s'` and the atom is not a symbol, the `w_symbol` field is bogus and an invalid memory access crash results.

**Comment by danomatika** [comment]
Ok, here's a fix: https://github.com/pure-data/pure-data/pull/468/commits/525a0dae1b45a227d1f146f2a17023b70cdad6c4
