### ISSUE TITLE
some dynamic strings are not translated

### ISSUE THREAD

**Issue by Ant1r** [pure-data/pure-data#384]
Although declared in pd_dynamic_strings.tcl, the string:
` "Discard changes to '%s'?"`
is not translated, certainly because the `'%s'` is replaced by the actual string (the name of the modified patch) before being sent to tcl.

**Comment by umlaeute** [comment]
i noticed that too, while working on #375 ...
the problem is, that the string is generated on the Pd-core side, and sent as is to the Pd-gui.
