### ISSUE TITLE
netreceive creates outlets when receiving 'listen'

### ISSUE THREAD

**Issue by fdch** [pure-data/pure-data#388]
Hi

It appears that netreceive creates an outlet after receiving a [listen $1( message, but it only shows after vis 0, vis 1. I attach a patch showing this. I tested this on Macos using pd-0.48-1.mac.tar.gz from msp.ucsd.edu

[netreceive-outlets.txt](https://github.com/pure-data/pure-data/files/2130608/netreceive-outlets.txt)

Cheers!

f

**Comment by umlaeute** [comment]
confirmed
