### ISSUE TITLE
[intelligent patching] default inlet in subpatch

### ISSUE THREAD

**Issue by LGoodacre** [pure-data/pure-data#390]
As IOhannes suggested, I'm posting this as a separate request from the main discussion on Intelligent Patching.

I've always thought it would be great if you could autopatch a subpatch with an inlet already given. Ie. if you have an object selected, press Ctrl 1 and type [pd something], the connection remains intact and you get a subpatch with a single inlet at the top. (Better yet, the inlet should be selected, so you can continue the autopatching chain within the subpatch).

**Comment by LGoodacre** [comment]
:+1:

**Comment by umlaeute** [comment]
i'm not entirely sure whether this won't be very confusing.
and there's also the issue, that we currently get an empty dummy object, when doing <kbd>Ctrl</kbd>-<kbd>1</kbd> with a yet-to-be-created subpatch.

basically:
1. <kbd>Ctrl</kbd>-<kbd>1</kbd> and type `f`
2. <kbd>Ctrl</kbd>-<kbd>1</kbd> and type `pd foo`
3. <kbd>Ctrl</kbd>-<kbd>1</kbd>
    - this will create an unconnected empty object in the parent patch (and issue an error on the Pd-console) :frowning: 
    - and will also open the subpatch, with a new selected `[inlet]` (which is of course the desired behaviour)

and yes, you probably *are* greedy.

**Comment by LGoodacre** [comment]
I meant to ask about the dummy object. Is it intentional, or not? If it's meant to be there, then the proposed feature could just close the subwindow and place the cursor in the dummy object box.

There isn't ordinarily a reason to do Ctrl-1 on an [outlet] object, so I don't think that this feature would create any new confusion (unless you're already quite confused). It would seem to do exactly what the patch-into-subwindow feature, or any new intelligent patching feature, does: speed things up.
