### ISSUE TITLE
[intelligent patching] Multi connections selection

### ISSUE THREAD

**Issue by mrpropre** [pure-data/pure-data#392]
As the patching experience is now greatly improved, I see one simple thing that makes patching life a bit tricky: one by one connections selection...

Would be very nice to be able to hold Shift key down and add/remove connections as it works for boxes selections. Even better, the "draw rectangle" for quick multi-selection like in Max.

Cheers!

**Comment by umlaeute** [comment]
i don't see many real world use cases that would require such a feature (and it would introduce incompatibilities on the code level; so introducing this feature really requires *very* compelling reasons).

Actually the only use case i can think of would be to remove a number of connections. And if we leave the "drag selection" aside, it would amount to `n` times manually <kbd>shift</kbd>-clicking each connection and then hitting <kbd>Delete</kbd>, as opposed to `n` times clicking each connection and hitting <kbd>Delete</kbd>...*not very* much gain.

**Comment by umlaeute** [comment]
i'm closing this as `wontfix` as allowing for connection multi-selection is likely to break the ABI for little apparent gain.
