### ISSUE TITLE
home/end keys don't truly move the text cursor

### ISSUE THREAD

**Issue by Ant1r** [pure-data/pure-data#393]
During editing an object box content, **home** and **end** keys do move visually the cursor, but subsequently typed text is written at the initial cursor location.

These keys behave correctly in the [text define] edition window, though.

Pd 0.48-1, Ubuntu 16.04, Tcl/Tk 8.6

**Comment by umlaeute** [comment]
confirmed.

btw, the reason why it works n the `[text define]` editor is, because this is just a bog standard text-editing window that is completely handled by Tcl/Tk (and they obviously got it right), whereas the *object editing* is handled (buggily) by Pd itself.

**Comment by Ant1r** [comment]
unfortunately it seems to be a TclTk bug in the canvas `icursor` command, isn't it?

**Comment by umlaeute** [comment]
nope. it's just that <kbd>Home</kbd> and <kbd>End</kbd> are not handled at all by the Pd-editor.

**Comment by umlaeute** [comment]
ah. the above snippet is the reason why the cursor does jump to the beginning (resp end) of the text.
however, since the Pd-core doesn't know about the cursor change (as it currently ignores the <kbd>Home</kbd> and <kbd>End</kbd> keys), you keep inserting at the old position.

**Comment by Ant1r** [comment]
I see; cool you fixed it!
