### ISSUE TITLE
TCL Invalid Command Name

### ISSUE THREAD

**Issue by shreeswifty** [pure-data/pure-data#407]
Linux 64 Ubuntu 
Linux shree-linux2 4.4.0-116-lowlatency #140-Ubuntu SMP PREEMPT Mon Feb 12 22:41:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

when opening midi alsa window  

is it supposed to be "raise" -- not sure but,,,

(Tcl) INVALID COMMAND NAME: invalid command name "rase"
    while executing
"rase "$id""
    (procedure "pdtk_alsa_midi_dialog" line 67)
    invoked from within
"pdtk_alsa_midi_dialog .gfxstub212e2c0 1 1 1 0 0 0 0 0 1 1"
    ("uplevel" body line 5)
    invoked from within
"uplevel #0 $docmds"opened alsa client 128 in:1 out:1
opened alsa client 128 in:1 out:1

**Comment by porres** [comment]
this is with pd 0.48-2test1, right?
