### ISSUE TITLE
[fexpr~] segfaults

### ISSUE THREAD

**Issue by mxa** [pure-data/pure-data#411]
3 objects needed:

~~~
[fexpr~ if ($x1[0] > xmax-$0, xmax-$0 = $x1[0], xmax-$0=xmax-$0*decay-$0)]
[v decay-$0]
[v xmax-$0]
~~~

then switch DSP on = segfault
**probably a wrong syntax, but segfault should not happen never the less.**

**Comment by porres** [comment]
it's a syntax error, check the help file of [expr]

2018-08-12 14:22 GMT-03:00 mxa <notifications@github.com>:

**Comment by mxa** [comment]
For the record: correct syntax is `_$0` instead of `-$0`.
Still, segfaults should be caught and handled gracefully.

**Comment by umlaeute** [comment]
as of Pd-0.50, this `[fexpr~]` fails to create with:

~~~
Bad left value: 
=
-
xmax 
1003 
$x1
0 
~~~

so i guess the issue is fixed.
