### ISSUE TITLE
specifying tempo arguments in [text sequence] crashes PD

### ISSUE THREAD

**Issue by LGoodacre** [pure-data/pure-data#416]
If I create the object **[text sequence myname -t 500 msec]**, PD crashes. I don't know whether I'm getting the arguments right for [text sequence], but I'm pretty sure that it shouldn't be crashing.

Using 0.48.1 and Ubuntu 18.04.1.

**Comment by Spacechild1** [comment]
this has been fixed in 0.48.2 ;-)
