### ISSUE TITLE
Conflict of hotkeys (Ctrl+M)

### ISSUE THREAD

**Issue by HenriAugusto** [pure-data/pure-data#418]
Both

- File/Message
- Window/Minimize

are mapped to Ctrl+M. When you press Ctrl+M the Minimize has precedence.

Confirmed on windows and Ubuntu/xfce.

**Comment by umlaeute** [comment]
the <kbd>Ctrl</kbd>-<kbd>M</kbd> binding for minimizing the window comes from your window-manager (this is also the reason why it takes precedence).

it is virtually impossible to know **all** keyboard-shortcuts **any** window-manager (on any of the supported OSs) is currently using resp. is going to use in the future, and avoid them to build application-specific shortcuts.

the simple fix is to re-assign your window managers `minimize` shortcut to some key combination other than <kbd>Ctrl</kbd>-<kbd>M</kbd> (or remove the assignment entirely). Your WM should provide means to do so (xfce definitely has).

a different solution would be to add a shortcut editor to Pd-GUI. doing that *right* is probably non-trivial - i guess PRs are welcome.

(I'm very inclined in closing this as wontfix)

**Comment by HenriAugusto** [comment]
I got interested because <kbd>Ctrl</kbd>+<kbd>M</kbd> wasn't set for minimize in my windows manager. 

I've looked the sources and the problem was that while it is actually assigned to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd> in `pd_bindings.tcl` it was given the wrong <kbd>Ctrl</kbd>+<kbd>M</kbd> label on `pd_menus.tcl`.

There is a fix on #419
