### ISSUE TITLE
vd: spurious "blocksize larger than delread~ buffer" error

### ISSUE THREAD

**Issue by Ant1r** [pure-data/pure-data#433]
with current master:

![blocksize_larger](https://user-images.githubusercontent.com/3748246/45321868-cd35e680-b546-11e8-9e27-8fb1c5c73041.png)

3 things:
- when vd~ is connected to delwrite~ (even through another signal object), the spurious error is printed to the console. This doesn't happen without the connection, neither if delread~ is used instead.
- it should write "blocksize larger than **delwrite**~ buffer" i think
- the error could be ctrl-clickable in the console, by the use of pd_error() instead of error().

**Comment by Spacechild1** [comment]
thanks for catching that! I'll have a look (since I've caused this regression...)

**Comment by Spacechild1** [comment]
https://github.com/pure-data/pure-data/pull/434

I fixed point 2 and point 3 but I can't manage to reproduce the spurious error message... did you use the latest master? can you send a Pd patch which triggers the error?

**Comment by Spacechild1** [comment]
I think I've fixed it!

**Comment by Ant1r** [comment]
The error only happens when DSP is on.
Also I've just noticed that if [delread4~ delay2] is created after the [delwrite~ delay2] (which the delaread4~ is **not** connected to), then it throws the error after the patch is saved and reload.

[testvd.pd.zip](https://github.com/pure-data/pure-data/files/2368453/testvd.pd.zip)
 
EDIT: too late ! You fixed it... I'm gonna try.

**Comment by Spacechild1** [comment]
thanks, tell me if you still get dummy warnings!

**Comment by Ant1r** [comment]
great, it's fixed! Thanks!
