### ISSUE TITLE
pd 0.49test1 - where did font shortcut go? (macOS)

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#446]
on macOS, I can't use command + T to open the text menu anymore

![screen shot 2018-09-11 at 22 18 39](https://user-images.githubusercontent.com/5360142/45396258-d68b8580-b610-11e8-86c8-3416125f1f8a.png)

**Comment by umlaeute** [comment]
it went away, as <kbd>Ctrl</kbd>-<kbd>T</kbd> is now taken by triggerize, following my own argument at https://lists.puredata.info/pipermail/pd-list/2018-06/122797.html

**Comment by umlaeute** [comment]
do you have a use-case where you need to change on such a regular basis that it warrants a shortcut?

**Comment by porres** [comment]
I was using heavily, cause I was changing the font size of 323 examples :) but I hope I won't ever need to do it again...

**Comment by umlaeute** [comment]
i see.
changing 323 patchfiles, i would use a script to fix the patches.

something like the following (changing the font from `12` to `24` in all patches in the directory (and recursively, in all subdirectories)

~~~bash
find . -type f -name "*.pd" -exec sed -e '1s/12;$/24;$/' -i {} ';'
~~~

**Comment by porres** [comment]
I had to translate them to english as well :)

**Comment by umlaeute** [comment]
in that case, i usually use another script:

~~~bash
$ find . -type f -name "*.pd" -exec pt2en -i {} ';'
~~~
