### ISSUE TITLE
pd 049-test3 tcl crash (macOS)

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#449]
Hi, I'm on macOS and I'm getting a weird crash with this patch https://github.com/porres/Live-Electronics-Tutorial/blob/master/Vol.1/Part%201%20-%20Basic%20Audio/08.Signal-Routing/02.Pan/1.Equal.Power.Pan.pd

If I save and then try to close the patch, it doesn't close and I get several errors, see below

![screen shot 2018-09-12 at 15 24 55](https://user-images.githubusercontent.com/5360142/45445347-57de2900-b6a0-11e8-8f9d-c56b790e865c.png)

This patch relies on object by the ELSE library, but you do not need to have the library install in order to replicate this, I tested and got the same issue...

**Comment by porres** [comment]
needless to say, I still haven't found the same issue with other patches... also, there isn't a problem with pd 0.48-2 and earlier

**Comment by umlaeute** [comment]
no, problems here although i miss the following objects:
~~~
else/pan4~
else/slider2d
f2s~
initmess
meter2~
out~
pan2~
pi
setdsp~
~~~

i tried various combinations of spaces in filenames and paths, but everything is happy.

**Comment by umlaeute** [comment]
no.

**Comment by danomatika** [comment]
Apart from creation errors, I'm not seeing this issue in either 0.48-2, a custom 0.49-0 I built from the current master, or Miller's 0.49-0test3.

**Comment by porres** [comment]
Indeed I'm not having this anymore when deleting my library so is something from my objects, which is weird cause I'm not using any externals that use tcl code here... anyway, I'm closing this and need to investigate it throughly

**Comment by umlaeute** [comment]
its probably related to #467 (fixed in current `update/0.49` #468)

**Comment by porres** [comment]
this is a bug in one of my externals: slider2d, but the crash is from Pd as it is an abstraction. The thing is that I was still loading it even though I removed "else" from path, cause I was using namespaces [else/slider2d]. With many objects not creating, I missed the clear fact this one was still loading and was definitely the culprit.

Anyway, I removed dependencies from other objects from else within this abstraction (there weren't that many and they were not that important), making it a plain vanilla patch, and the problem still remains. 

I was surely not getting this by the time I created this object earlier this year, with Pd 0.48-1... I need to try it back with that earlier version. 

I tested with 0.48-2 and it didn't work.

Anyway, gotta do some more testings and then open a new issue.

the abstraction relies heavily in dynamic patching and data structures

**Comment by porres** [comment]
Wow, I just finished my journey into finding and describing the bug :) - ok, I'll test!

**Comment by porres** [comment]
I can't actually build and test this I guess, whenever I compile Pd, I get a tcl error warning that I got the wrong tcl version, I can't even use deken when I compile it... I'll try but...

**Comment by porres** [comment]
well, while we're all here, I'll just make the new report here as well.

This is definitely a 0.49 issue, I developed an abstraction for 0.48-1 which works for 0.48-2, it's a 2D slider that relies on dynamic patching and data structures. So, what happens is that I cannot "cut" it from the patch cause pd goes crazy, other objects disappear from the patch. Another procedure that crashes it is if I just open the patch, save it, and try to close it, same things happen. And after I tried saving this patch, the abstraction gets corrupted somehow and the same errors start happening when I try this with the earlier versions.

Here's before saving  
![screen shot 2018-09-14 at 14 41 40](https://user-images.githubusercontent.com/5360142/45566271-8ab52800-b82c-11e8-8171-5ef5ca34f7e3.png)

here's what happens when I try saving it
![screen shot 2018-09-14 at 14 42 05](https://user-images.githubusercontent.com/5360142/45566283-986aad80-b82c-11e8-9e1e-c6c1e8d1da15.png)

And here's the abstraction, vanilla adapted. 
[slider2d.pd.zip](https://github.com/pure-data/pure-data/files/2384360/slider2d.pd.zip)

**Comment by porres** [comment]
I tested with a build from the 0.49 update branch and I don't have the issue, but, as I said, Pd complains I don't have the latest tcl

![screen shot 2018-09-14 at 14 50 06](https://user-images.githubusercontent.com/5360142/45566658-be448200-b82d-11e8-8e6a-ce21ffb302e4.png)

How can I update the version and fix this when compiling? I can't be sure the tcl error is fixed because, well, I don't seem to have the right one :) - again, not even deken works

**Comment by porres** [comment]
Oh, this error seems to be just for the completion plug-in, but again, I know other things like deken do not work, it just cannot find any external... and I know they're there :)

**Comment by danomatika** [comment]
You have to build Tk and then make the app with it embedded.

**Comment by Spacechild1** [comment]
The tcl error was caused by Pd, so if the error disappeared the issue is solved

**Comment by porres** [comment]
> You have to build Tk and then make the app with it embedded.

embarrassed to sound dumb, but I need a bit more of a detailed help and steps on how to do that - i'm really dummier than it looks

**Comment by porres** [comment]
> The tcl error was caused by Pd, so if the error disappeared the issue is solved

awesome, well, you have the avstraction, you could test it too just to be double sure, then I can close this ;)

**Comment by porres** [comment]
thanks, I'd never figured that out, you rock :) 

all works great, thanks everyone

**Comment by danomatika** [comment]
In general, my work flow is:

* if just testing C source changes, `make` and run pd form the bin folder
* if working on the GUI, also run form the bin folder for simple things, but for stuff that needs the full app, I run `osx-app.sh` to create the .app and then run that
