### ISSUE TITLE
s_audio_pa.c: uses private portaudio headers

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#450]
the portaudio backend now uses a function like `PaUtil_ValidateStreamPointer` (at least), which appears to be a *private* function of the portaudio library.
since Pd includes a full copy of portaudio (for system that lack proper dependency handling), this is technically possible.

however, these private symbols are not exported by `libportaudio` (e.g. as found in the official Debian package of portaudio), so one cannot link against such  systemwide portaudio.

this is a serious regression (esp. for the Debian world). please allow the usage of a dyamically linked  portaudio.

**Comment by umlaeute** [comment]
mention @Spacechild1

**Comment by Spacechild1** [comment]
sorry, I forgot that there's the dynamic linking option... I'll swap PaUtil_ValidateStreamPointer for the public Pa_IsStreamActive.

**Comment by danomatika** [comment]
We're no longer using `PaUtil_ValidateStreamPointer`.
