### ISSUE TITLE
savestate into help-intro.pd and warning

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#456]
this is a firendly reminder that savestate still prints a warning "savestate is experimental - may change or disappear". Now, I suspect once it is in 0.49, it'll be as is forever :) so watch not to miss removing this warning.

Also, it's still not listed in help-intro.pd, so just a reminder to do that as well before the final release

cheers

**Comment by umlaeute** [comment]
hmm. when would you expect that warning to show?

(i think there's little use in adding an "experimental" splashscreen, if the only people who are ever going to see it are those daredevils who pull an experimental snapshot of the source-code and compile themselve. *they* hopefully know that everything they currently experience is experimental)

**Comment by danomatika** [comment]
Yeah, [savestate] should be in help-into.pd.

**Comment by porres** [comment]
> hmm. when would you expect that warning to show?

i'd expect no warning as I'm assuming it is not experimental anymore once it's in... unless @millerpuckette tells us differently.

**Comment by umlaeute** [comment]
but isn't this issue exactly that you want to override the explicit statement of @millerpuckette that the object is experimental?

**Comment by porres** [comment]
> but isn't this issue exactly that you want to override the explicit statement of @millerpuckette that the object is experimental?

oh, no... besides including [savestate] into help-intro.pd I just wonder if the warning is real and should go or stay

**Comment by millerpuckette** [comment]
I think I can get rid of it now :)

**Comment by umlaeute** [comment]
cool. just don't forget to also add it to `help-intro.pd` .-)

**Comment by porres** [comment]
made a PR if it's just easier... https://github.com/pure-data/pure-data/pull/493
