### ISSUE TITLE
Pd on Windows should should use different paths for 32 and 64 bit binaries

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#469]
(Bringing this in from the pd-dev list.)

Pd should install to and use different paths on Windows for 32 and 64 bit:
* on a 32 bit system: `%Program Files%`
* on a 64 bit system:
  - 32 bit: `%Program Files (x86)%`
  - 64 bit: `%Program Files%`

These paths should be used for the settings file location, in the registry, and by the installer.

This probably involves changes to `src/s_file.c`, `tcl/pd_guiprefs.tcl`, and the `msw/build-nsis.sh` installer script

**Comment by Lucarda** [comment]
Do you want to start a **[WIP] PR**?


Here are some things i collected:

Change occurrences of` !define PRODUCT_NAME "Pure Data"` to `"Pure Data 32-bit"` /` "Pure Data 64-bit"`/ in pd32.nsi / pd64.nsi

Change occurrences of `"$SMPROGRAMS\Pd"` (start menu) with` "$SMPROGRAMS\Pd 32-bit"` `"$SMPROGRAMS\Pd 64-bit"` in pd32.nsi / pd64.nsi

Change occurrences of `Pd.lnk` to `Pd 32-bit.lnk` in pd32.nsi

Change occurrences of `Pd.lnk` to `Pd 64-bit.lnk` in pd64.nsi

Change occurrences of `"$PROGRAMFILES\Pd"` to `"$PROGRAMFILES64\Pd"` in pd64.nsi

`$PROGRAMFILES64` is explained --> http://nsis.sourceforge.net/Docs/Chapter4.html#varuser

**Comment by mxa** [comment]
Related question in https://github.com/pure-data/pure-data/issues/469 : Should Pd-Single and Pd-double share the same preferences? If not, should Pd-32 and Pd-64?

**Comment by danomatika** [comment]
I'm not going to be able to do anything major on this right now. I'm mainly cleaning up bug fixes we worked on last week and I need to do some actual work/work this week.

**Comment by Lucarda** [comment]
I went ahead and started a #476 a WIP PR.

**Comment by Lucarda** [comment]
We can close this.
It was fixed in #476.
