### ISSUE TITLE
Strg-X, Strg-Z trick to bring object to foreground isn't working any more

### ISSUE THREAD

**Issue by mxa** [pure-data/pure-data#472]
This was never documented but still a very useful trick to alleviate for the lack of an arrange / bring to back / bring to front functionality. Probably it's gone because of the (long awaited and amazing) infinite undo feature.

**Comment by Ant1r** [comment]
I guess you mean this trick was bringing object to front, right? In that case, just do cut+paste (strg-x then strg-v) instead of cut+undo.

**Comment by danomatika** [comment]
I've always cut & paste myself for this.

**Comment by mxa** [comment]
I think it was @umlaeute who taught me that feature :)

Am 17. September 2018 12:26:18 MESZ schrieb Dan Wilcox <notifications@github.com>:
>This is really a question for @umlaeute.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pure-data/pure-data/issues/472#issuecomment-421958762

-- 
Max Neupert

**Comment by mxa** [comment]
Should I close this here and make 'arrange objects' a proper feature request?

**Comment by umlaeute** [comment]
indeed. the new undo system is supposed to *really* undo cutting, which also means that the object-creation order is re-instantiated.

so Undo/Redo-hack to bring an object to front is expected to no longer work (and probably needs to be replaced by something new)

**Comment by abreubacelar** [comment]
what about paste replace?

**Comment by mxa** [comment]
Made a feature request here https://github.com/pure-data/pure-data/issues/475

**Comment by umlaeute** [comment]
i thought about adding a short-cut for paste-replace, but decided against it.
it's totally unclear, how many people will be liking/using that feature and how often they will need it *quickly*.
since we already have complicated keystrokes, i didn't want to reserve another one for something of potential little practical use (see: shortcut for changing the X-spread factor between objects...)
