### ISSUE TITLE
Windows/Pd doesn't honour directory started from

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#478]
When starting Pd on Windows from the command line in my project-directory, the first "Open" (<kbd>Ctrl</kbd>-<kbd>O</kbd>) will fire up the open-dialog in `$::env(HOME)/Documents` (or in my `$::env(HOME)` if the former does not exist).

i think this is unexpected behaviour and quite confusing:
- I keep my projects wherever i like (on my USB-stick; on my 2 TB external disk)
- I started from the cmd (since i know what i'm doing)
- I `cd`ed into my project directory (because this is where all my files live)
- I call `....\Pd.com` (passing my project's `MAIN.pd` patch, which gets successfully opened!)
- I trigger an `[openpanel]` because i want to load one of my project's *soundfiles* (which happen to reside besides my `MAIN.pd` patch).
   - alternatively I just use <kbd>Ctrl</kbd>-<kbd>O</kbd> to open an additional Pd-patch
- the "file open dialog" lands me in `~/Documents/`, and I have to navigate to my project again!!!

(note: while i write "I" it is not actually me who is experiencing this; rather it's my work-colleagues who keep pestering me about it but haven't created any bug-report yet...; also they don't do these steps (apart from the last one) manually, instead they just open a `myproject.bat` file which does all the things for them.)

this has been introduced with `Pd-0.48-0`, as part of the "Pd Documents" revamp.
The problem does not exist on Linux.
I see the value of providing a default documents directory for ordinary users (kind of).
But for power-users (who manually start Pd from the cmdline), this is impractical.

i suggest to:
- keep the current behaviour  when Pd is started from the "Start Menu" resp. the "Application Link" (on the desktop). afaict, these should start Pd via the GUI (but i haven't checked the installers; if this is not true, probably the installers should be fixed)
- when starting Pd from the cmdline (directly calling `pd.exe` resp. `pd.com`) the current working directory should be honoured.

i'm not entirely sure how Pd should behave when being started by clicking on a Pd-patch.
probably:
- when Pd is launched while opening the Pd-patch, the fileopendir should be set to the directory containing the Pd-patch
- when the patch is opened into a running Pd-instance, don't change whatever fileopendir is currently set to

**Comment by danomatika** [comment]
Something similar happens in macOS where it keeps resetting to `~/Documents/Pd`.

**Comment by Spacechild1** [comment]
1) I agree with IOhannes that when starting from the cmdline the save and open dialogues should start in current working directory.
2) regarding opening from the GUI: most Windows apps start from the last opened/saved document. they either keep it in a preference file or write it in the registry.

**Comment by danomatika** [comment]
One option for opening just the GUI would be to use the base name of the most recently opened file loaded form the stored files list. If the dir exists, use it, if not or the list is empty fall back to the doc dir/home dir.

**Comment by Spacechild1** [comment]
ah, I didn't mean to actually open the last patch (OSX used to do that and it was super annoying :-)) but rather use the directory as the starting point for the open/save dialog.

**Comment by danomatika** [comment]
>but rather use the directory as the starting point for the open/save dialog

... that's what I meant. I *did not* mean re-open the last patch.

**Comment by umlaeute** [comment]
yes, i figured. i just wanted to make sure.

**Comment by danomatika** [comment]
Seems to be working for me on macOS:

* open GUI by double clicking or `open Pd-###.app`: uses `~/Documents/Pd` (or `~/` when docsdir plugin is off)
* open GUI by invoking `bin/pd` inside the app bundle: uses commandline current working directory

Also, the path saving is working between opening or saving in the GUI and panels starting by [openpanel] or [savepanel] objects. This wasn't quite working right before, in spite of my efforts to standardize the path variables in the last release.

One thing I noticed: if Pd receives a patch to open the it's started, should it use the this location (or the last in a list of patches) as the starting directory? As in, on macOS you can use the universal `open` command and pass commandline args via:

    open Pd-###.app --args ~/Desktop/somepatch.pd

Should Pd start the patch and use `~/Desktop`?

**Comment by danomatika** [comment]
Yeah, in that context it makes more sense to keep it how it is. We should be good now then.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by umlaeute** [comment]
not sure. i don't think it is fixed on windows yet.
