### ISSUE TITLE
opening a Pd patch from explorer launches a new instance

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#479]
when double-clicking a Pd-patch in the Windows Filesystem Explorer, Pd launches and opens the patch. nice.

however, when double-clicking *another* Pd-patch in the Windows Filesystem Explorer, a *new* instance of Pd is launched (so the two patches run in separate processes).

i think this is a regression. in the Pd-0.42 rewrite (and in Pd-extended) we have put considerable amount in avoiding this kind of behaviour, making sure that the "other" Pd-patch is opened in the same instance of Pd.

this works by associating the Pd-GUI with the `.pd` files, rather than `pd.exe` (the DSP-core).
The GUI takes (took?) care of avoiding being re-launched and of opening the patch in the already running instance.
if you wanted to run two instances of Pd, you could have this by starting Pd via the DSP-core (`pd.exe`) instead of the GUI.

This still works on Linux (the Debian packages take care of associating the `.pd` patches with the GUI rather than the DSP)

**Comment by Spacechild1** [comment]
> however, when double-clicking another Pd-patch in the Windows Filesystem Explorer, a new instance of Pd is launched (so the two patches run in separate processes).

this has been the case for Pd vanilla as far as I can think back (i.e. for at least 5 years) and I don't think that's necessarily a regression. I can only really speak for Windows land but usually you either have 
a) a program which only has one instance but allows several tabs and/or windows (REAPER, Sibelius, GIMP)
b) each file gets its own instance (OpenOffice, MS Paint)

if you allow several instances and you prevent double clicking a file from spawning a new instance - which of the running instances should it belong too? Such thing happens e.g. with QtCreator which has workspaces but doesn't prevent multiple instances. In this particular case, all files seem to be associated with the first opened instance.

so the current behaviour is not necessarily wrong. but of course we can argue if it's the design we want. I personally enjoy that it will open a new instance but I also understand why other users don't like that.

**Comment by umlaeute** [comment]
i'm sure there are use-cases where you would want to spawn multiple instances. but i think that this is mostly for power-users, who probably can set the file-associations themselves (an alternative would be a GIU-preference).

regarding which instance should be chosen when several are already open: probably the first opened one (or the one that was opened via start-menu/file-association, in contrast to those started from the cmdline; and if all other instances have been started from the cmdline, start yet another instance)

**Comment by umlaeute** [comment]
also it seems that the singleton code is currently half-broken.

**Comment by danomatika** [comment]
I agree that opening new patches in Explorer should use an existing instance. That matches exiting behavior on Linux and macOS and I find the current behavior irritating whenever I use Pd on windows.

**Comment by umlaeute** [comment]
fixed with 732f0bacb1b6c61d688f52ad512166a82480b85f
