### ISSUE TITLE
Pd-GUI no longer honors `-path`

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#483]
up till `Pd-0.48-2` I could start Pd with:

~~~
pd -path /path/to/my/pdguiplugins/
~~~

and the Pd-GUI would automatically load any GUI-plugins found in `/path/to/my/pdguiplugins/`.
It seems this no longer works with `Pd-0.49-0test3`.

It *does* work if I add `/path/to/my/pdguiplugins/` to my searchpaths in the preferences and restart Pd.

Since GUI-plugins are only loaded at startup, this makes it a bit inconvenient when using GUI-plugins which you only want to enable ad-hoc.

I guess this is related to separating searchpaths given with `-path` and via the path-preferences.

**Comment by danomatika** [comment]
The temp paths probably need to be added when loading. I thought it was already doing that, but I'll check.

**Comment by millerpuckette** [comment]
I looked at this and can confirm that 0.48 and 0.49 act differently, although I can't see that any of the relevant code has changed.. mysterious.

**Comment by danomatika** [comment]
Might be related to the changes to [declare]?

**Comment by danomatika** [comment]
I think I see it. st_temppath is only searched in `g_canvas.c` canvas_open() but not used by canvas_path() or canvas_lib(). I'll add and test.

**Comment by Spacechild1** [comment]
btw, here's another regression with [declare]: https://github.com/pure-data/pure-data/issues/410

**Comment by danomatika** [comment]
This is a different issue dealing with the GUI not knowing about the st_temppath. [declare] seems to be working fine with `-path` but GUI plugins do not.
