### ISSUE TITLE
iemgui GOP broken

### ISSUE THREAD

**Issue by claudeha** [pure-data/pure-data#484]
When loading a patch with iemguis in a GOP, they are not visible until you open the subwindow and close it again.  Then they disappear if the window is minimized and maximized again

Test patch:

    #N canvas 3 61 450 300 10;
    #N canvas 3 61 450 300 gop 0;
    #X floatatom 106 120 5 0 0 0 - - -;
    #X obj 106 142 nbx 5 14 -1e+37 1e+37 0 0 empty empty empty 0 -8 0 10
    -262144 -1 -1 0 256;
    #X obj 142 122 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144
    -1 -1;
    #X obj 163 122 tgl 15 0 empty empty empty 17 7 0 10 -262144 -1 -1 0
    1;
    #X connect 0 0 1 0;
    #X coords 0 -1 1 1 85 60 1 100 100;
    #X restore 69 80 pd gop;

I suspect this is due to the recent fix for #477 not taking GOP into account properly: I will revert 8b01a9f995e34c4ed8fc780f3458868744c2ef38 in my local copy and test again.

**Comment by claudeha** [comment]
reverting the patch makes GOP behave correctly, but #477 surfaces again...

**Comment by danomatika** [comment]
*whack a mole*

Thanks for testing.

**Comment by millerpuckette** [comment]
yep, reverting 8b01a9f fixes this.

**Comment by millerpuckette** [comment]
OK, and commit 978b16efa42 might have addressed the original problem better...?

**Comment by Ant1r** [comment]
@millerpuckette sorry but I think that 8b01a9f995e34c4ed8fc780f3458868744c2ef38 was better (but buggy on one point).
I just tested, and excepting in  `iemgui_vis()` (where it caused the present issue, and was useless anyway IMO), it seems `glist_isvisible()` fixes both #477 and #488, where `gobj_shouldvis()` only fixes #488.

**Comment by millerpuckette** [comment]
So If I understand correctly, you think all the gobj_shouldvis() calls should go back to glist_isvisible()
except that in iemgui_vis() there should be no test at all, right?
