### ISSUE TITLE
Tcl invalid command name setting iemgui label in nested (non)gops

### ISSUE THREAD

**Issue by claudeha** [pure-data/pure-data#488]
toplevel patch contains a non-GOP abstraction which contains a GOP abstraction which contains [loadbang]--"label bug"--[hsl], loading the toplevel patch gives:

    (Tcl) INVALID COMMAND NAME: invalid command name ".x559f9a52b480.c"
        while executing
    ".x559f9a52b480.c itemconfigure 559f9a52c540LABEL -text {bug} "
        ("uplevel" body line 43)
        invoked from within
    "uplevel #0 $docmds"

the matching C code seems to be https://github.com/pure-data/pure-data/blob/master/src/g_all_guis.c#L450

    pure-data/src/g_all_guis.c:450:            sys_vgui(".x%lx.c itemconfigure %lxLABEL -text {%s} \n",

[abstraction.pd.txt](https://github.com/pure-data/pure-data/files/2408023/abstraction.pd.txt)
[gop-abstraction.pd.txt](https://github.com/pure-data/pure-data/files/2408024/gop-abstraction.pd.txt)
[toplevel.pd.txt](https://github.com/pure-data/pure-data/files/2408025/toplevel.pd.txt)

**Comment by claudeha** [comment]
can't reproduce in 0.49test3 or 0.49test4, so I think it was a transitory issue in master...

**Comment by Ant1r** [comment]
yep, but #477 surfaces again, in this specific case (receive/send setting in a GOP in a non-GOP)...
I'm about to send a PR for that.
