### ISSUE TITLE
[clone] prevents [loadbang] to fire inside abstraction on creation.

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#49]
let's say there's an abstraction called 'foo'. if you create [clone foo 16], loadbangs inside foo instances don't fire as they would if you created a single instance (without clone). they do fire however if you save and reopen the patch OR if you click on [clone] and save [foo]. since the latter method is an easy workaround, it's not a big deal once you're aware of the issue. if you're not aware, however, you easily end up scratching your head why your abstraction isn't working as expected...

**Comment by Spacechild1** [comment]
this seems to be fixed now...

**Comment by porres** [comment]
> this seems to be fixed now...

how come? Which new commit could be related to this?

**Comment by Spacechild1** [comment]
dunno, but I can't reproduce it anymore so I assume this got fixed on the way. 
also, I can't reproduce https://github.com/pure-data/pure-data/issues/242
loadbangs in a cloned abstraction clearly load before the parent patch. looks like this has also been fixed.
correct me if I'm wrong.
https://github.com/pure-data/pure-data/issues/261 seems also to be fixed...

right now I'm doing lots of testing with [clone] because I'm working on a PR. are you aware of any other issues with clone?
