### ISSUE TITLE
Bug on external loading on Windows

### ISSUE THREAD

**Issue by HenriAugusto** [pure-data/pure-data#498]
I'm on Windows 7 64 bit.

For some reason i can't load .dll externals anymore. But PD still loads abstractions normally, though.

![image](https://user-images.githubusercontent.com/11790621/46032384-d3dd6580-c0d1-11e8-8eab-6f3ba8edfdf1.png)

The screenshot is a test patch that runs absolutely normal on some versions.

I first saw this bug on 49 test1 but in the next test it was fixed. Then it appeared again in test5 and 49 stable.

**working**

- 0.49-0test2
- 0.49-0test3
- 0.49-0test4

**not working**

- 0.49-0test1
- 0.49-0test5
- 0.49-0

I only have a single path set which is 

> C:/Users/User/Dropbox/PureData/shared extras

![image](https://user-images.githubusercontent.com/11790621/46032599-772e7a80-c0d2-11e8-8860-eabc0f976735.png)

**Comment by HenriAugusto** [comment]
Oh, totally forgot to say: 

i'm on win 64 but using the 32bit version of PD. And i'm using the exectuable from the zip file (no installer).

I've tried removing the whitespace from the `shared extras` folder because i know they sometimes mess stuff up but i still can't load any .dll external. :thinking: 

About the `oscx`: i've downloaded it waaay back and forgot to delete it. Done.

**Comment by umlaeute** [comment]
tested on Win7/32bit without any problems (in a path with a lot of spaces like `C:\Users\me\Neuer Ordner\Pure Data\`).

also, please use maximum verbosity. (start Pd with `-verbose`; set log-level in the Pd-console to `4 All`)

**Comment by HenriAugusto** [comment]
Okay. Here is the console output. (0.49.0 stable 32bit)

[externalLoadingTestConsole.txt](https://github.com/pure-data/pure-data/files/2416765/externalLoadingTestConsole.txt)

**Comment by umlaeute** [comment]
hmm, the dump you posted states that the the architecture of Pd-core is `Windows-amd64-float32`, which is really the **64bit** version of Pd (and **not** the 32bit version).

Also the path to the Pd-binary is `.../pd-0.49-0/`, indicating that this is a 64bit installation (the 32bit installation unzips to `pd-0.49-0-i386/`.

please double-check that this is a 32bit installation (and show us some proof)

**Comment by HenriAugusto** [comment]
haha can't believe it. Yeah, i downloaded the wrong version and made confusion with my folders. Sorry for that.
