### ISSUE TITLE
some bugs with DSP

### ISSUE THREAD

**Issue by tiagmoraismorgado** [pure-data/pure-data#50]
Below follow some **DSP bug**s I encountered **while doing patches on pd**:

- _if the frequency of oscillators is set to 0 you will, most likely have DC Offset (that isn't a good idea)_
- _if you unplug a patch cord, that is routing some form of audio, the same thing may eventually happen as well_

**Looking forward,
T.**

**Comment by umlaeute** [comment]
> if the frequency of oscillators is set to 0 you will, most likely have DC Offset (that isn't a good idea)

actually it is.
if you specify a very low frequency (say `0.00001`) the output of `[osc~]` is hardly changing at all (but it still *is* changing). in the general case, you certainly do not want to remove the "DC-offset" in this case.
if you drop the frequency even lower to `0`, the oscillator will *still oscillate*, it just will not change any more.

if you want to get rid of the DC-offset, add a DC-offset remover (`[hip~ 5]`).

> if you unplug a patch cord, that is routing some form of audio, the same thing may eventually happen as well

i'm not entirely sure what you mean with this, but:
disconnecting an audio-input is the same as sending a constant signal (usually with value `0`) to the object.
so if you disconnect the input of `[osc~]`, you are just telling it that it should continue to oscillate with a frequency of `0`.

**Comment by porres** [comment]
howdy, it is a cosine wave, so a 0 frequency (where no oscilation happens) at pahse 0 is "1", this is correct.

if you connect and disconnect cords, you're hearing clicks, not "DC", this happens cause audio comes in and out drastically, there's no much way of dealing with this, it's like pluging and unpluging your guitar cord in and out of your amplifier...
