### ISSUE TITLE
a new object proposal as a fix solution for #234 ([readsf~] can't search files from [declare])

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#502]
As discussed in https://github.com/pure-data/pure-data/issues/234 the [readsf~] object is unable to search for files from a path set in [declare -path], unlike other Pd objects that can. A solution that came up in this discussion is to include an object that could be used to search for a file in a declared path. 

Maybe an object JUST for that is too much, but there have been other discussions about including an object that deals with "path" and "canvas" info, so this could be only another functionality to this object. I'm talking mainly about this discussion here: https://github.com/pure-data/pure-data/pull/150#issuecomment-318823336 but I also made a request for a "canvas information" object here: https://github.com/pure-data/pure-data/issues/273 

Quoting @danomatikac on the other possible functionalities:

"a set of utilities like this could be rolled up into a [path] object ala:

[path canvas $arg] <- equivalent to [getdir] with optional depth arg
[path basename] <- file/dir name without parent dir
[path dirname] <- parent dir
[path rootname] <- filename without extension
[path extension] <- only extension
[path filename] <- alias for makefilename, etc
[path split] <- split a filename into a list using a separator
[path join] <- join a list into a filename using a separator
[path absolute] <- ensure an absolute path
[path dirlist $ext $ext $ext...] <- output the contents of a directory as symbols, with optional extension filters
[path makedir] <- make a directory, could be locked to relative to a location or "safe places" only
[path rmdir] <- remove a directory, could take force and recursive options
..."

"
Maybe a [canvas] object?

* [canvas dir $depth]: get canvas dir or parent dir
* [canvas name]: get canvas name
* [canvas mouse]: get/send mouse interaction
* [canvas key]: get/send key interaction
* [canvas close]
* ...

And maybe the following from the "donecanvasdialog" message:
* [canvas gop]
* [canvas size]
* [canvas pos]
* [canvas margin]
"

**Comment by porres** [comment]
yeah, sorry, that would have been important :) well, following the idea in https://github.com/pure-data/pure-data/issues/234#issuecomment-424686424 I think of a message to this object that could give us a full path, like when you use [openpannel] 

Anyway, another reference, there were discussions for a similar "canvas" object in here https://github.com/pure-data/pure-data/pull/150#issuecomment-318823336 - so whatever other funcrtionalities we think is important, ands whatever the name is ( I guess I like the option of just [canvas] ) we could also have a message to query for a declared file.

But I'm really opened to any suggestions, the important thing is that we find a way in Vanilla to allow this to happen

**Comment by umlaeute** [comment]
please do update your initial post, adding relevant information from #234, #150 and whatever you think appropriate. it's just no fun, forcing everybody to collect that info manually from some links everytime you want to give it a thought.


> we could also have a message to query for a declared file.

could you please clarify, what you mean by this? (what is a "declared file"?)

**Comment by porres** [comment]
> please do update your initial post

sure

> what is a "declared file"

I meant a file in a declared path

**Comment by umlaeute** [comment]
>  >  please do update your initial post
> sure (done)

would you also mind updating the title? (so the casual reader doesn't have to lookup what "#234" might mean)

**Comment by porres** [comment]
done

**Comment by porres** [comment]
It seems there are plans to fix this after all, see: https://lists.puredata.info/pipermail/pd-dev/2019-04/021939.html

we could maybe just close this issue if that happens then

**Comment by Spacechild1** [comment]
@porres I think the issue at hand has been fixed with the introduction of `[pdcontrol]` right? Can I close this?

**Comment by porres** [comment]
nope, [pdcontrol] doesn't take care of this issue, and I don't think it will

**Comment by porres** [comment]
to recap, the original issue is actually https://github.com/pure-data/pure-data/issues/234 - it was closed as "won't fix", it requires some changes under the hood (make it thread safe). 

> It seems there are plans to fix this after all, see: https://lists.puredata.info/pipermail/pd-dev/2019-04/021939.html

What Miller says here is that he has plans to make it thread safe.

So what I think, actually, is that this issue might be closed and  https://github.com/pure-data/pure-data/issues/234 reopened

**Comment by Spacechild1** [comment]
sounds good
