### ISSUE TITLE
pd crashes before open on OSX Mojave (yes, localhosts is fine)

### ISSUE THREAD

**Issue by brandonblock** [pure-data/pure-data#506]
Yep, basically this. If I'm lucky I get an icon bounce but that's it for both vanilla and extended. Purr Data fires right up however.

**Comment by umlaeute** [comment]
which Pd?

**Comment by brandonblock** [comment]
0.49-0

**Comment by brandonblock** [comment]
Well, I'm dumb. I accidentally downloaded the 32-bit version.

**Comment by NiccoloGranieri** [comment]
I am having the same problem, tried 64/32 bit, and went back to 0.48.1 having the same problem.

**Comment by umlaeute** [comment]
@NiccoloGranieri so `0.48.1` is crashing as well?

**Comment by NiccoloGranieri** [comment]
Sorry @umlaeute, had massively edited the definition of localhost in my machine. Fixed that, everything went back to normal.
