### ISSUE TITLE
[feature request] allow to programmatically set temporary search-path

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#509]
since Pd-0.48 we have the `add-to-path` message, that allows us to add a new search-path via a message to Pd.
this was originally intended for `deken`, but is used by external libraries as well (e.g. `cyclone`, `Gem`), to add library's path to Pd's search-path (for additional objects, like abstractions)

the message takes an option, that allows to immediately save the paths to the preference files.

However, when using from a library, it is often preferably if the dynamically added search path would not be saved to the preferences at all (to avoid duplicate adding; or multiple automatic additions of different versions).

So I'd suggest to use the "saveflag" to declare a non-saveable adding: e.g. if `saveit==-1` then the path is added to `st_temppath` instead of `st_searchpath`

**Comment by danomatika** [comment]
sounds good to me

**Comment by danomatika** [comment]
Is this fixed in 0.50? If not, let's move it to the 0.51 milestone.

**Comment by umlaeute** [comment]
moved the milestone to the corresponding PR #510
