### ISSUE TITLE
Are text colours hardcoded?

### ISSUE THREAD

**Issue by rnkn** [pure-data/pure-data#51]
After looking around the code I found [`pdtk_text_new:8`](https://github.com/pure-data/pure-data/blob/master/tcl/pdtk_text.tcl#L8) which takes a variable `color`.

This function appears to be used in [`g_rtext.c:312-320`](https://github.com/pure-data/pure-data/blob/master/src/g_rtext.c#L312-L320) where it appears the the colours "black" and "blue" are hardcoded, although I don't understand the C code to figure this out myself sorry.

Is this true?

**Comment by umlaeute** [comment]
yes.

**Comment by rnkn** [comment]
Cool thanks. I've had a loot at the Pd-extended source and implementing `canvas_fill` was pretty easy, but the others (e.g. `msg_cord`, `signal_cord`) look slightly more complicated than a simple find/replace.

If I tinker along with this and get it figured out, would you be interested in a PR?

And, if so, should I use the same variable names that Pd-extended used?

**Comment by umlaeute** [comment]
since i'm not in charge i cannot comment on "would you be interested in a PR".

from my personal pov, i found the "filled" looks of objects in PdX rather annoying.
i would welcome it though, if less things were hardcoded (like colors,...)

**Comment by umlaeute** [comment]
since the original issue/question has been resolved, i think this ticket should be closed.
for discussion, please see the [pd-dev](https://lists.puredata.info/listinfo/pd-dev) mailinglist.
