### ISSUE TITLE
Crash on macOS when closing the open dialog

### ISSUE THREAD

**Issue by aalex** [pure-data/pure-data#514]
System info:
* OS: macOS 10.13.1
* Pd version: vanilla 0.49-1

What happened:
* Chose menu item File > Open...
* Hit Command-W (by mistake) to close a window while the focus was on the open dialog.
* Crashed. Instead, it should have either done nothing, or closed the dialog without a crash.

See log for details.
[crash-report.txt](https://github.com/pure-data/pure-data/files/2496598/crash-report.txt)

**Comment by Benitoite** [comment]
Could not reproduce on macOS 10.12.6 or 10.14.3b2

**Comment by umlaeute** [comment]
Your crash-report indicates that your are using `Pd-0.49-0` (see 2nd and 4th line of the crash-report.txt).

`Pd-0.49-1` was released especially to fix the issue you are describing. Please double check your installation.

**Comment by Spacechild1** [comment]
@aalex can you please check if the crash persists?

**Comment by danomatika** [comment]
In testing this on my M1 MBP macOS 11.6.1 system:

* Pd 0.51-4 x86_64 release: cannot reproduce, open panel closes
* Pd 0.52-0 custom build with Tk 8.6.12: cannot reproduce, open panel closes

I'd say we can close this for now.
