### ISSUE TITLE
crash when I save a patch to a new .pd file

### ISSUE THREAD

**Issue by LucienRapilly** [pure-data/pure-data#518]
On my laptop (osx) 0.49-0 crashes everytime I save a patch to a new .pd file. The patch is still saved, and the file properly created, but I have to restard  pd. Never had this on previous versions.

**Comment by Spacechild1** [comment]
This is an OSX specific problem which was fixed in the most recent release. Check miller's download section

**Comment by umlaeute** [comment]
closing, as this has been resolved with [0.49-1](https://puredata.info/downloads/pure-data/releases/0.49-1)
