### ISSUE TITLE
sublist object?

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#520]
Hi, what is the "sublist" object described here? Is it upcoming? Has it been deleted? Should it be removed from this comment?

**see line 15**

https://github.com/pure-data/pure-data/blob/a02c37b34baf51c8fc9e4f469d08144a323581f2/src/g_traversal.c

**Comment by umlaeute** [comment]
> what is the "sublist" object described here? 

it's an object to "get a pointer into a list which is an element of another scalar" :-)

> Is it upcoming? Has it been deleted?

you could start with `git blame` to see when the line mentioning `sublist` has been added.
that was with 52dca0f96dcd8bf382b8a35a0df36927c0931015, the initial commit of the repository (a long long time ago), so `sublist` has either been removed or was a mere pipe dream.
checking out the [code at this commit](https://github.com/pure-data/pure-data/blob/52dca0f96dcd8bf382b8a35a0df36927c0931015/src/g_traversal.c) you can see that there indeed was an object `[sublist]` back then, so it obviously was removed later.
i leave it as an exercise to the reader to find out when the object was dropped.

i guess the Pd-list is a better place to ask such questions (miller hardly ever answers GH-tickets)
