### ISSUE TITLE
[clone] probably always should have an inlet.

### ISSUE THREAD

**Issue by mxa** [pure-data/pure-data#534]
If a `[clone]`d abstraction has no inlet defined, `[clone]` will have no inlet either. This is undesired, since we want to be able to send `[clone]` a` [vis 5 1(` message no matter if the abstraction has inlets defined or not.

**Comment by porres** [comment]
+1

**Comment by mxa** [comment]
Oh, if the cloned abstraction has an audio [inlet~] the vis method will fail
inlet: expected 'signal' but got 'vis'

**Comment by porres** [comment]
yep, this is because it needs a control inlet. One thing we were doing is having the signal inlet accept control messages as well so you wouldn't need an extra dummy control inlet just for this - see https://github.com/pure-data/pure-data/pull/365
