### ISSUE TITLE
make app: Contents/MacOS/Pd linked to versioned Tcl & Tk

### ISSUE THREAD

**Issue by Benitoite** [pure-data/pure-data#535]
MacOS 10.14.3 β 18D32a / OSX 10.9 build sysroot.
After `make app` the Pd executable is linked to:

`/System/Library/Frameworks/Tcl.framework/Versions/8.4/Tcl` and `/System/Library/Frameworks/Tk.framework/Versions/8.4/Tk`

This particular MacOS provides version 8.5, so in order to launch the app I changed the link to the pre-versioned symbolic link:

`install_name_tool -change /System/Library/Frameworks/Tcl.framework/Versions/8.4/Tcl /System/Library/Frameworks/Tcl.framework/Tcl ~/pd/Pd-0.49.0.app/Contents/MacOS/Pd `

`install_name_tool -change /System/Library/Frameworks/Tk.framework/Versions/8.4/Tk /System/Library/Frameworks/Tk.framework/Tk ~/pd/Pd-0.49.0.app/Contents/MacOS/Pd `

**Comment by danomatika** [comment]
FYI: The Tk 8.5 versions provided with macOS are *very buggy* and should be avoided. This is why Pd now ships with the frameworks in the app bundle.

**Comment by danomatika** [comment]
How are you building and running Pd? Installing as a command line application *works* on macOS, however there are issues with the font and application behavior, as []noted in the INSTALL.txt](https://github.com/pure-data/pure-data/blob/master/INSTALL.txt#L256), so building an app bundle is recommended. There are several tools in the `/mac` folder to facilitate building the Tcl / Tk frameworks and a Pd app bundle. See the `/mac/README.txt` for info.

**Comment by danomatika** [comment]
We will most like update the included Wish build that is used by `make app` as Tk 8.5 build from source on macOS 10.14 has issues as well.

**Comment by danomatika** [comment]
Miller's build of our patched TK 8.5.19 is now used when running `make app`.
