### ISSUE TITLE
minor peculiarity selecting audio output in macOS

### ISSUE THREAD

**Issue by sevdh** [pure-data/pure-data#536]
I came across a minor peculiarity in Pd 0.49-1 running on macOS 10.14.2
I have created a multi-output device in Audio MIDI Setup. It’s works as a splitter where the audio is sent in parallel to the built-in output and to soundflower. I have named it ‘Built-in Output and Soundflower’.
In Pd I can select it as output device in the menu but after pressing OK it takes and stores the 'Built-in Output' as device instead of my ‘Built-in Output and Soundflower’. If I name the multi-output device differently (i.e. ‘Multi out’) I can select it properly and everything works as expected. After testing with different names it seems that Pd only looks at/remembers the first x (x=15?) characters of the name of the selected device.

Best!

Edwin
<img width="749" alt="screenshot 2019-01-07 at 09 45 11" src="https://user-images.githubusercontent.com/16959264/50830105-07719200-1347-11e9-91d1-100f78c2d488.png">

**Comment by danomatika** [comment]
> After testing with different names it seems that Pd only looks at/remembers the first x (x=15?) characters of the name of the selected device.

It's option 1, Pd is doing a string comparison for "Built-in Output" with 15 characters and matches your aggregate device's first 15 characters. The fix is to also check if the device's name has a different string length as well.

**Comment by danomatika** [comment]
Actually, this exact issue was already fixed for MIDI device names, so I ported it over for audio device names. Can you try a test build?

http://docs.danomatika.com/pdbuilds/Pd-0.49-1-devname-fix.zip

**Comment by sevdh** [comment]
I'm sorry to have missed your replies. I can confirm that it is working in 0.50-0-test1.
Thanks a lot!!!
