### ISSUE TITLE
bang in switch~ issues

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#538]
Hi, I'm trying to precompute audio stuff when loading a patch and, for that, I'm relying on the bang method of [switch~], which computes a single block of audio.

Well, I can't just use loadbang as it will print an error if the DSP is off. By the way, the first issue is that this error is not clear or is misleading, as the console print is "bang to block~ or on-state switch~ has no effect", but it's not addressing the actual case, which is that the DSP is off!

Now, if I use [r pd-dsp-started] I can get a "loadbang" when the audio gets turned on and use the first bang (that is the bang from the first time the audio gets turned on) to initialize my patch. Should work, right? Well, that's the thing, it doesn't!

Here's a screenshot:

<img width="816" alt="screen shot 2019-01-09 at 23 56 56" src="https://user-images.githubusercontent.com/5360142/50940991-49dfbf80-146a-11e9-9fbe-e004ae74c3ba.png">

find the test patch attached

[switch~-test.pd.zip](https://github.com/pure-data/pure-data/files/2743271/switch.-test.pd.zip)

I'd expect to be able to print the audio block and record the noise input into a table, but that only happens the second time [switch~] receives a bang. So I just can't use this feature to manage this.

Anyway, this is a bug, right?

cheers

**Comment by porres** [comment]
ok, this needs just a decent message ordering, then it works ;) using trigger made the trick! But perhaps more details in the documentation would help, huh?


<img width="390" alt="screen shot 2019-01-10 at 17 03 38" src="https://user-images.githubusercontent.com/5360142/50990670-cf5e8080-14f9-11e9-81ad-d7354f60ab53.png">

**Comment by umlaeute** [comment]
so which documentation changes do you suggest, that would have helped you?

not using trigger is the root of all evil (and i seem to remember having said that before)
