### ISSUE TITLE
Document logic behind source file names

### ISSUE THREAD

**Issue by eldruin** [pure-data/pure-data#539]
pure-data's source file names contain some prefixes that I cannot really make sense of: `d_`, `g_`, `m_`, `s_`, `u_` and `x_`. e.g. `x_interface.c`
In libpd even `z_`.
Is it documented somewhere what the meanings are? If so, where?

If not, could you explain them? I can create a PR with the explanation afterwards if you let me know where a good place for this information would be.

**Comment by nicolasdanet** [comment]
https://github.com/pure-data/pure-data/blob/master/src/CHANGELOG.txt#L170

**Comment by eldruin** [comment]
Thanks @nicolasdanet. However, that refers to the names in the code. I was asking about the source file names.

**Comment by eldruin** [comment]
Ah, I see it now. It is documented at the end of that file: https://github.com/pure-data/pure-data/blob/7c27aa0ad505bb4802eee3fc40886836c814353f/src/CHANGELOG.txt#L248
Thanks @nicolasdanet!
