### ISSUE TITLE
[print] with '-n' flag prints colon when receiving list of numbers

### ISSUE THREAD

**Issue by mariobuoninfante** [pure-data/pure-data#540]
Tested with Pd 0.49.1 on MacOS Sierra
When sending a 'list' of numbers to [print -n], this would print a colon ':' first then the list of numbers

**Comment by mariobuoninfante** [comment]
***EDIT***
Tested with Pd 0.49.1 on MacOS Sierra

When sending a 'list' of numbers to [print -n], this would print a colon ':' first then the list of numbers

**Comment by umlaeute** [comment]
btw, you can directly *edit* your post, by clicking on the <kbd>...</kbd> and selecting <kbd>Edit</kbd> in your original post.

(please do update your original post; you can then delete the followup "***EDIT***" post (or i'll do it for you))

**Comment by danomatika** [comment]
I actually looked into this a while ago, but my solution ended up being overly complicated.

**Comment by danomatika** [comment]
This is fixed via #580.
