### ISSUE TITLE
triggerize and last object moved changes cord position

### ISSUE THREAD

**Issue by fdch** [pure-data/pure-data#544]
Doing triggerize with nothing selected changes the position of the cords connected to the last object moved. 

Not a huge deal, but I think this comes out of the combination of the current implementation and the old `control+t` Font shortcut/reflex that is quite hard to forget. Any chance `control+t` could fall back to opening the Font menu if there is indeed nothing to triggerize?

**Comment by umlaeute** [comment]
could you explain the exact problem? what exactly is happening with the cord?

**Comment by fdch** [comment]
Something like this:

![cord_pos](https://user-images.githubusercontent.com/13335792/51861856-91f15400-233d-11e9-9b11-3fa41bd65560.gif)

This first:
![screen shot 2019-01-28 at 20 36 36](https://user-images.githubusercontent.com/13335792/51861930-c2d18900-233d-11e9-8ef9-11eedbc34f42.png)
Then this:
![screen shot 2019-01-28 at 20 37 02](https://user-images.githubusercontent.com/13335792/51861931-c2d18900-233d-11e9-8600-ed827c8023a6.png)

(the loop does not happen in real life)

**Comment by Lucarda** [comment]
@fdch : 
Are you sure those are the correct 3 images?
The 3 are the same.

**Comment by fdch** [comment]
the firs one is a gif, composed of the second and the third one. They are exactly the same except for the cords that shift a bit, making them "wiggle". It's hard to see unles you overlay them somehow, that's why I made a gif. The gif should play on github

**Comment by fdch** [comment]
I realize the canvas redraw causes a click on the DSP chain, and I would vote for having triggerize do nothing if nothing is selected (or fall back to Font dialog, as I suggested above)
