### ISSUE TITLE
Undo with Tidy Up may have some unexpected behavior

### ISSUE THREAD

**Issue by fdch** [pure-data/pure-data#545]
Tidy Up works generally very well but *in some rare cases* its action can't be undone

For example:

1.  Open any Pd help file,
2.  Before doing anything, hit `Tidy Up` (objects get rearranged as expected)
3.  Then, `Undo motion` (Nothing gets undone)

The above results, somewhat oddly in:

4.  Edit mode being triggered...
5.  Closing the patch does not prompt the 'Save the changes' dialog... (but it does not save anyway)

Is this only happening to me? Happens on both msp.ucsd.edu version and on my compiled version (using Tk 8.6.7 on macos, latest git, app built with osx-app.sh)

**Comment by fdch** [comment]
For me, it works with selection and in stages: first selecting and tidying a few objects vertically, then horizontally. I tend to repeat those stages until things are tidy, always correcting manually some things at some point. 

However, I agree, if you select a large crowd it is hard to predict what it will do. 

I think the problem is the name: tidiness is very subjective. Something like `align` would be more appropriate in my opinion, at least that is how I think of it.

**Comment by umlaeute** [comment]
the problem only occurs, when nothing is selected.
