### ISSUE TITLE
[feature request] -resize flag for array read message

### ISSUE THREAD

**Issue by fdch** [pure-data/pure-data#546]
When you send a `[read myfile.txt(` message to an array, myfile.txt is read up to the size of the array. 

Although an abstraction can be implemented (using `[text]`, `[text size]`, `[array size]`, etc), I think it is much more efficient to have a `-resize` flag for that purpose, like when reading with `[soundfiler]`

A more extreme case would be just to consider resizing as a default (like `[text]` does), which would (perhaps) remove the need for a `-resize` flag from `[soundfiler]`.

**Comment by fdch** [comment]
An example of an abstraction that resizes arrays can be found [here](https://github.com/fdch/fd_lib/tree/master/fd_read-resize)

**Comment by fdch** [comment]
Hi! 
I have a working solution for this request, but I am not really sure where to make the PR. 

Basically, I followed the wiki, but I am not sure now if I have to make the PR directly to master or to some other branch that might be out there. The screenshot shows where I stopped:
![screen shot 2019-02-18 at 03 16 05](https://user-images.githubusercontent.com/13335792/52924184-e29c1180-332b-11e9-8696-0815372f241c.png)

It is officially the first time *ever* I am attempting to add some actual code to Pd. So, please, let me know if I missed some stuff!

The branch on my fork is here:
https://github.com/fdch/pure-data/tree/array-resize

**Comment by Lucarda** [comment]
Hi,
The Pic is Ok, you should be able to merge to pure-data/master. 

:)

**Comment by fdch** [comment]
Thanks! Will do!! here's the test patch I'm using: 
[arrayresize-test.zip](https://github.com/pure-data/pure-data/files/2873862/arrayresize-test.zip)

**Comment by fdch** [comment]
This issue was addressed here https://github.com/pure-data/pure-data/pull/561
