### ISSUE TITLE
Conflict: incoming OSC/FUDI data and DSP on

### ISSUE THREAD

**Issue by NiccoloGranieri** [pure-data/pure-data#55]
This problem occurs when, while receiving OSC data from inside the machine (thus using a localhost), DSP is turned on. The OSC data stops visually flowing (the GUI freezes) until the DSP isn't turned off. 

Even though it might seem like a GUI glitch, this has a major delay effect also on the digital sound processing. The delay rises up to 5 seconds when the glitch occurs. The same effects appear if the patch is launched with the -nogui command from the terminal.

The only workaround I found to solve this issue is to run two separate instances of Pd: the first one that will act as an OSC parser, not having the need to turn on DSP. Once the data is parsed, the data is sent to a second instance of Pd via FUDI protocol (netsend) where it can coexist with DSP on without causing any issues.

This unfortunately brings up the amount of computing power needed.

The bug can be replicated in two different ways. 
- On MacOS the glitch appears even by simply sending OSC data from pd and receiving it on the same patch at a high rate.

- On Linux this doesn't happen, but it can easily be reproduced by sending OSC data to Pd from another application, Processing for example, at a high frame-rate.

Example patches are attached below.

[Pd_Bug.zip](https://github.com/pure-data/pure-data/files/944269/Pd_Bug.zip)

**_# UPDATE_**

The same glitch appears with large amount of data incoming NOT formatted in OSC, but in Pd's native formatting FUDI. To replicate this, run this small python script in the terminal typing first:

`python`

and then pasting the code below:

`import socket`
`import time`

`IP="127.0.0.1"`
`PORT=5005`
`addr=(IP, PORT)`
`EOL=';\n'`
`sock=socket.socket(socket.AF_INET, socket.SOCK_DGRAM)`

`for i in range(10000000):`
`  msg="list foo "+str(i)+" bar"`
`  sock.sendto(msg+EOL, addr)`
`  time.sleep(0.001)`

This example sends data to PD via FUDI using the local host on the port 5005 every millisecond. As said previously if DSP is turned on the GUI freezes. The issue is avoided if the data is throttled once every 10 milliseconds. (This is achieved by changing the last line of the python code to: time.sleep(0.01)

**Comment by umlaeute** [comment]
so the Mac-patch locks the GUI immediately on my linux laptop, afaict, regardless of DSP.

this happens, even if I disconnect the output of `[netreceive]` from `[parseosc]`.

also, the patch keeps working (e.g. if I `[print]` the output of `[parseosc]` to *stderr*, it shows all the data) - it's *only* the GUI that stops responding.

could you confirm this?

**Comment by NiccoloGranieri** [comment]
I can confirm that the patch locks even if you disconnect the output of [netreceive] from [parseosc].

I don't know what you mean by printing to stderr. If you help me reproduce it I will be happy to help.

**Comment by umlaeute** [comment]
print to stderr: start Pd from the cmdline and use the `-stderr` startup flag.

**Comment by NiccoloGranieri** [comment]
Yes, I can confirm that the data flows through stderr.

I had already noticed that the signal was flowing because the data sent to control a sound parameter was still effecting it, but with a major delay.

**Comment by J-Bledsoe** [comment]
I am getting the same problem when trying to receive and parse a large amount of OSC data. Having two separate instances of Pd seems to solve the issue (similar to above) and the patch attached to this thread instantly causes PureData to freeze when DSP is turned on. Using the latest version of Pd (48-1) and macOS High Sierra, the UI hang still occurs and the audio is distorted. I am able to turn the DSP off using the keyboard shortcut, after which all the UI 'catches-up' and the audio returns to normal. Any signs on a fix for this networking issue?

**Comment by umlaeute** [comment]
@J-Bledsoe please be more specific about the term `distorted` (as it means very different things to different people and/or in different contexts)

**Comment by J-Bledsoe** [comment]
There is noticeable crackling and occasional dropouts of the audio, sounds like it's most likely the result of buffer drops.

**Comment by J-Bledsoe** [comment]
Just a quick bump on this. Any luck on this?

**Comment by J-Bledsoe** [comment]
@umlaeute bump

**Comment by J-Bledsoe** [comment]
@umlaeute @millerpuckette  We've had another report of a user on Linux experiencing the same audio dropouts when working with OSC messages. Is there any progress being made on this?

**Comment by Spacechild1** [comment]
I can confirm. Some observations:
1) with TCP the GUI lock-up happens Note, however, that with TCP I need to set the [metro] to 1 ms for the GUI to lock up.
2) when using [iemnet/udpreceive] there is *no* GUI lock-up, I tried to go as low as [metro 0.01]. audio starts crackling below [metro 0.1] but that's kind of expected. Can you confirm this?

looking at the sources, [udpreceive] doesn't seem to do anything fancy, so I think this is merely a logic bug somewhere in Pd.

@danomatika something for the netobject updates? ;-) I can help, but not now...

BTW, *real* solution is to do the actual network IO in dedicated worker threads and use a lockfree queue to communicate with the audio thread (like the Supercollider server), but that's a different story :-)

**Comment by Spacechild1** [comment]
> Even though it might seem like a GUI glitch, this has a major delay effect also on the digital sound processing. The delay rises up to 5 seconds when the glitch occurs.

I can't confirm this part, though. At least on Windows, sound continues playing as normal, only the GUI freezes. Just for the record: I tried both the "Mac" and "Linux" example (although I don't quite understand why they are called like that :-) 

@NiccoloGranieri can you run your examples with [iemnet/udpreceive] instead of [netreceive -b -u] and tell us the results?

**Comment by NiccoloGranieri** [comment]
Hi @Spacechild1, thanks for looking into this.
 
> Just for the record: I tried both the "Mac" and "Linux" example (although I don't quite understand why they are named like that :-)

The examples are named like that because on Linux the macOS example doesn't produce the same bug. For a pd patch to exhibit the same behaviour on Linux a different approach must be taken, hence the different example files :-)

>>The bug can be replicated in two different ways.

>>On MacOS the glitch appears even by simply sending OSC data from pd and receiving it on the same patch at a high rate.

>>On Linux this doesn't happen, but it can easily be reproduced by sending OSC data to Pd from another application, Processing for example, at a high frame-rate.

Just tested using iemnet's [udpsend] and [udpreceive] replacing [netsend -u -b] and [netreceive -u -b] and I can confirm the GUI freezes in the exact same way. Patch attached below.

[Example patch using [iemnet/udpreceive]](https://github.com/pure-data/pure-data/files/3216420/iemnet.udpreceive.zip)

Tested on:
MacBook Pro (Retina, 15-inch, Mid 2015)
2.8 GHz Intel Core i7
16 GB 1600 MHz DDR3

**Comment by Spacechild1** [comment]
thanks for reporting! from mid of June I might have time to investigate this on different machines.

**Comment by Spacechild1** [comment]
turns out the GUI freeze was a very simple logic bug in Pd: https://github.com/pure-data/pure-data/pull/640 

in hindsight it might explain various other mysterious GUI freezes... so thanks a lot for reporting!

regarding the audio problem I have to investigate this on different machines. I have some ideas but it'll take some time.

**Comment by NiccoloGranieri** [comment]
The problems seems to be gone in Pd 0.50.0! Both the GUI freeze and the audio glitch/delay! Thanks for working on this guys, thanks @Spacechild1!
