### ISSUE TITLE
Opening audio settings freeze Pd on windows using callbacks

### ISSUE THREAD

**Issue by mxa** [pure-data/pure-data#550]
With ASIO (via portaudio) and callbacks active, switching DSP on, then off and then opening the audio settings a will freeze Pd on (this?) MS Windows.

Windows 10
Soundcards: Fireface 400 / Realtek HDA

**Comment by Lucarda** [comment]
Could it be that using "Callbacks" is still experimental?

From the "release notes" on 0.41:
https://github.com/pure-data/pure-data/blob/master/doc/1.manual/x5.htm#L568


I get crashes if I switch DSP off and on with "Use Callbacks" selected.

Windows 8.1 
Pd 32-bit.
Pd 64-bit.
Tascam 4x4.

**Comment by Spacechild1** [comment]
With "Use Callbacks", the scheduler runs inside the low level audio callback, which is not a good idea, especially if you want low latency... So you probably shouldn't use it anyway. But yes, I've also experienced crashes when trying it out.

**Comment by Lucarda** [comment]
@mxa 

Could you include "**using callbacks**" in the title of this issue?

**Comment by reduzent** [comment]
This should be addressed by #1756
