### ISSUE TITLE
number2 label is on top

### ISSUE THREAD

**Issue by mrpeach-xx** [pure-data/pure-data#555]
I was in the habit of placing the label field of a number2 object inside the number field, so the label would appear behind the number, but this behaviour has changed recently. Now the label appears in front of the number, making the number illegible. This is with Pd 0.49.1 on Windows7.

![number2_labels](https://user-images.githubusercontent.com/1071864/52593230-6cbd1500-2e16-11e9-9954-c88837df8392.png)

**Comment by mrpeach-xx** [comment]
I can fix this by changing the order of the last two sys_vgui calls in my_numbox_draw_new at line 213 of g_numbox.c.

**Comment by danomatika** [comment]
Yes, I changed the ordering so that all GUIs draw their labels after their controls. This makes sense for the sliders and radio buttons. I suppose it makes less sense for you use case?

**Comment by danomatika** [comment]
In looking at the code, you are right in that the layer was not consistent either. This is fixed with 256af56c596b3d9aa07c2ad3e91f0244db30b374 in the `update/0.50` branch,
