### ISSUE TITLE
receive message in iemguis not working with "$0"

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#556]
best to check this with the following test patch (find it attached)
 
<img width="420" alt="screen shot 2019-02-14 at 17 12 10" src="https://user-images.githubusercontent.com/5360142/52811210-b0648880-307b-11e9-9791-a79170a4a2b0.png">

[test.pd.zip](https://github.com/pure-data/pure-data/files/2866478/test.pd.zip)

**Comment by umlaeute** [comment]
1. please don't post your bug-report as screenshots of text. use text instead (which can be searched, pasted,...)
2. the only problem i can see is that `x_$0` is not working when being set from the properties. all the rest is expected behaviour.

please amend the issue (and title) or close it.

**Comment by porres** [comment]
Hi, ok, but first please explain why the rest is expected. Let me see if my hypothesis is correct. Is it so that whenever a Pd message receives a "$0" it becomes a patch ID number and there's nothing we can do about it unless structural changes are made into how Pd handles messages all together?

**Comment by umlaeute** [comment]
you send a `[bang(` message to an `[f $0]` object.
the `[f]` object will always output the number it has stored (which happens to be the expanded `$0` value).
so the object really sends (e.g.) `1003` (and not `$0`), to the message box. which then expands the `$1-x` symbol using that incoming value. and you set the receive label to `1003-x`.

Pd has no concept of *variables*. messages passed between objects (and message boxes) are always *by value*.

so i fail to see how your example patch could ever set t receive-label to the literal `$0-x`.

**Comment by porres** [comment]
> so i fail to see how your example patch could ever set t receive-label to the literal `$0-x`.

yeah, I really did not think that through :( 

> Pd has no concept of _variables_. messages passed between objects (and message boxes) are always _by value_.

> so i fail to see how your example patch could ever set t receive-label to the literal `$0-x`.

just so it's 100% clear, my question was wether we could send a literal `$0-x` message to a receive label in a pacth. Seems using something like [symbol $0-x] also fails, but thinking about it, I think I remember a trick using [text] or something.

The thing is that I need to know wether this is possible and works with GUIs so we can set send/receive names for them in a message, before I close/reopen this issue with more pertinent considerations.

thanks

**Comment by Spacechild1** [comment]
> wether we could send a literal `$0-x` message to a receive label in a pacth

yes, it's possible :+1: 
[dollar-hack.zip](https://github.com/pure-data/pure-data/files/2872084/dollar-hack.zip)

I have no idea why you need this with [bang], but personally I've needed this to dynamically create Pd patch files within Pd.

**Comment by fdch** [comment]
I think you just need to call $0 from a [symbol] with a `\` and an added string, like this:
 `[symbol \$0-x]` 
it seems to work after saving and reopening :)

**Comment by porres** [comment]
> I have no idea why you need this with [bang]

I actually don't, it's just a test :) thanks for the solutions,  I'll talk about how to deal with this in my Pd syntax tutorial. Thanks again.

**Comment by porres** [comment]
Well, BLOW ME DOWN! Now that we can use "\" in Pd, the [symbol] solution is something new. I guess before [makefilename] was the way to go, but now we can use this "\" with symbol as well...

And I'll be dammed, but I tested and also realized you can just use "\0" in a message!!!

Meaning, "$0" can now be used in messages in Pd and we never praised that!!!

**Comment by porres** [comment]
At least I tested "receive \$0-x" and it worked for setting a receive name in a GUI... but now I'm also making other tests and it's not going that well... "; \$0-x something" does not send "something" to a [receive $0-x] object. And it still complains "$0-x: no such object".

Maybe open a separate issue?

<img width="448" alt="screen shot 2019-02-16 at 17 06 57" src="https://user-images.githubusercontent.com/5360142/52904053-5c89a900-320d-11e9-9610-f61eeefc8254.png">
