### ISSUE TITLE
[triggerize] selecting [t a b] object text and getting [t a a b]

### ISSUE THREAD

**Issue by fdch** [pure-data/pure-data#565]
When selecting the text of a [t a b] and then triggerizing, *sometimes* pd crashes as in #542, but *sometimes* a [t a a b] is created, that is, an *anything* is prepended to [trigger]

This feature is really, really nice, and I don't remember seeing it in the doc. I like this because all the outlets are offset by one, thus remaining aligned to the arguments, so you don't need to swap cords (If it's in the docs, I must have missed it and you can ignore this.)

The problem is that if I it worked, and I repeat the above (for example, to get a [t a a a b]) afaict the crash always happens.

**Comment by umlaeute** [comment]
so what is the problem?

- the *crash* is reported in #542 and fixed in 0f81f54.
- the *feature* is there (hooray), but there's no need to open an issue about it.

so i'm closing this as i really think it's a dupe (please clarify if it is not)

**Comment by fdch** [comment]
If you say it's a dupe, it must be. I just found another way to get to that crash (which must be really the same situation) and found this feature in the meantime :)

**Comment by umlaeute** [comment]
you could check whether it's a dupe by compiling the `update/0.50` branch and see whether it's gone.
if it is not gone, i need more a detailed description of the problem (without interleaving it with praise for the feature :-))

**Comment by fdch** [comment]
Indeed, it is gone with `update/0.50`(the feat is there but i won't praise it :) Also, #544 is gone as far as I can see
