### ISSUE TITLE
Introduce modifier to intelligently patch all selected object's outlets to the specified inlet.

### ISSUE THREAD

**Issue by musger** [pure-data/pure-data#568]
When selecting multiple objects, for example to copy and paste them, and connecting a single of their outlets to another (unselected) object's inlet, all selected object's outlets do get connected. In some cases this is a great additional feature, more often it seems to be undesired to users. Everyone seems to be served best by introducing a modifier key which has to be pressed when releasing the patch cord drawing mouse button to make the multiple connections.

**Comment by umlaeute** [comment]
which key? which actions should be affected?

**Comment by musger** [comment]
* umläute <notifications@github.com> [2019-03-07 15:22]:
> which key? which actions should be affected?
Thank you, will try to add that info. Where can I find a summary of all
the intelligent patching additions? Thanks!

**Comment by umlaeute** [comment]
https://vimeo.com/273707442 & https://vimeo.com/279631360

**Comment by Ant1r** [comment]
I would add it: #374

**Comment by musger** [comment]
From the various features I propose to introduce the $modifier key to be required when releasing the mouse button making a connection with the following features:

- connecting multiple objects to a single inlet

- connecting multiple objects to a the inlets of an object

- connecting a single outlet to multiple objects

- connecting the outlets of an object to multiple objects

- connect one of a group of selected objects to a sink, and all selected objects will be conntected to the sink (provided they have enough outlets and the iolets are compatible)

- connect a (signal) source with one of a group of selected objects, and the source will be connected to ll selected objects

**Comment by umlaeute** [comment]
i think 5 and 6 are duplicates of 2 and 3 resp. (the list at the top of #543 was updated when new features were added)

**Comment by musger** [comment]
(sorry, wrong click)

**Comment by umlaeute** [comment]
hmm, after an initial implementation i'm not very convinced.

the modifier-key switches to "Run"-mode which interacts a bit with a seemless workflow.

**Comment by musger** [comment]
Looks like the Shift key is available as an alternative for the above functions...
