### ISSUE TITLE
Very Small Menu Fonts on Windows

### ISSUE THREAD

**Issue by megrimm** [pure-data/pure-data#572]
I have a student running windows and the fonts are very very small in the menus (and default in patches before changing font size).

He seems to have a super high resolution screen (4k?)

All i have is a sceenshot but can get more info if needed.

![52638820_10156568649617935_3478327664652058624_n](https://user-images.githubusercontent.com/134831/54493326-1a539600-48a5-11e9-951b-fe60739d8503.jpg)

**Comment by umlaeute** [comment]
that's a bit weird, as the top-level menus (those that are always visible) seem to have the correct font-size, only in the pull-down menus you get the smallish font.

what happens when specifying `-font-size 20` (or whatever) in the startup options (without the quotes, see #551)

**Comment by megrimm** [comment]
yeah i noticed that its only in pull down menus... but it was also very small in the patch (he just changed font size to work)

I will try the suggested flags later today when i have access to his laptop.

**Comment by megrimm** [comment]
so i checked on this.... -font-size 20, etc changes nothing. also "forget all"... still same extremely small font sizes.

**Comment by megrimm** [comment]
yo... just wanted to check up on this now that we are getting a new release.

I just had another student with same mini fonts on high resolution screen. 

She has at 3840x2160. It's a Dell XPS 15 running windows.

Reducing display to 1920x1080 allows Pd menus to be more useable. Default canvas fonts very small and need to be increased to 16+. All is useable but doesn't look great at this res btw.

screenshot she sent me attached.
![1920x1080](https://user-images.githubusercontent.com/134831/61824100-2e973900-ae2b-11e9-9f87-c9601a5c0741.PNG)
![3850x2160](https://user-images.githubusercontent.com/134831/61824101-2e973900-ae2b-11e9-8d7a-6d3c5ac32963.PNG)

**Comment by megrimm** [comment]
still trying to figure this out.

From: https://www.ghacks.net/2016/07/17/fixing-tiny-text-in-windows/

"The "tiny text" issue is caused by programs that are not optimized for high-DPI resolutions, and programs that don't scale well."

Seems like a similar problem is on Linux from a search of "Hidpi font tk" but since I do not have such a display no tests can be made. Seems like all the architecture students here now have these laptops with hi-dpi displays so maybe we will run into this more?

**Comment by danomatika** [comment]
It's a tk issue with high-dpi displays on windows. I would suggest looking at tk docs on this as there might be a setting that is required, as we do for macOS.

**Comment by megrimm** [comment]
yeah finding "tk scaling" on tk in docs might do trick?

https://www.tcl.tk/man/tcl8.5/TkCmd/tk.htm#M10

also on stackoverflow: https://stackoverflow.com/questions/34132203/scaling-of-tkinter-gui-in-4k-38402160-resolution#34133102

at this point I have no way to make a test because my access to that particular hi-dpi display is just until September.

**Comment by megrimm** [comment]
in pd-gui.tcl line 285:

```
    # we are not using Tk scaling, so fix it to 1 on all platforms.  This
    # guarantees that patches will be pixel-exact on every platform
    # 2013.07.19 msp - trying without this to see what breaks - it's having
    # deleterious effects on dialog window font sizes.
    # tk scaling 1
```

not quite sure how to add a condition to look for hi-dpi display but according to tk docs maybe scaling to 2.0 does trick.

**Comment by danomatika** [comment]
Why not try it out? You can borrow a machine that has the issue and easily hack the tcl files and see if you can get it working?

**Comment by danomatika** [comment]
Also, it seems like the DPI awareness can be provided by a Windows Application Manifest XML file (https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests) but that needs to be built into the application as a resource. I do remember reading somewhere (can't find it now) that Tk 8.5.19's default Wish shell should be DPI aware already but seeing that tiny font in the menus leads me to believe otherwise.

@Spacechild1

**Comment by danomatika** [comment]
If the Windows API needs to be called by the GUI, one approach is to make another tiny TCL extension, like pdfontloader, to make the appropriate calls.

**Comment by digiecho** [comment]
don't suppose you peeps have a simple workaround for this that a noob can follow? I'm desperate to use PD but I cannot see a thing haha

**Comment by danomatika** [comment]
I believe I pointed to a possible solution in my last two posts but, as I don't have a Windows install handy, I was hoping someone else in the discussion would try it out...

In any case, here is my usual approach to such problems: typing "windows application manifest example set dpi` into DuckDuckGo led me to two useful links ([1](https://stackoverflow.com/questions/23551112/how-can-i-set-the-dpiaware-property-in-a-windows-application-manifest-to-per-mo) & [2](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt846517(v=vs.85))).

From the StackOverflow link, someone has the XML contents of a manifest file as an example:

~~~
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
    <assemblyIdentity type="win32" name="MyApplication" version="1.0.0.0" processorArchitecture="amd64"/>

    <asmv3:application>
        <asmv3:windowsSettings>
            <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/pm</dpiAware> <!-- fallback for Windows 7 and 8 -->
            <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness> <!-- adding v1 as fallback would result in v2 not being applied to dialogs on capable systems -->
            <gdiScaling xmlns="http://schemas.microsoft.com/SMI/2017/WindowsSettings">true</gdiScaling> <!-- enables GDI DPI scaling -->
        </asmv3:windowsSettings>
    </asmv3:application>
</assembly>
~~~

So someone can try the following:

1. Close Pd if it's running.
1. Create a manifest file in the Pd/bin, the file needs to have the same name as the Pd.exe and end with ".manifest" aka something like "pd.exe.manifest"
2. Copy and past the example XML above into this new file with a text editor... do not use Wordpad, at leas use Notepad or even better Notepad++ or Sublime Text.
3. Edit the XML so the application name and processor architecture match the build of Pd you have aka name is probably "Pd" or "Pure Data" and architecture is probably "i686": or 32 bit and "amd64" for 64 bit.
4. Save the file and start Pd. If there are no errors or popups, you can assume the manifest is working.
5. Close pd and start playing with the DPI scaling settings, aka true/false. Save and restart Pd each time to see if it has an effect.

If you find something that works, please post the XML contents or the file to this discussion and we can then roll it into the Windows build.

_Note: I'm typing the names for things off the top of my head. You should double check and make sure what you try is correct and not just what I'm positing."

**Comment by ylevtov** [comment]
@danomatika Just tried this with all sorts of combinations of true/false etc. in the manifest and no luck, unfortunately. Even when I change the global scaling settings for Windows (requires logging out and back in for the changes to take effect), the Pd menu items stay tiny...

**Comment by laonikoss** [comment]
Hi, in case this is still relevant and useful - I edited pd-gui.tcl, line 380 and simply changed the font size to 26 and it now looks a lot better.

`font create menufont -family Tahoma -size -26`

I also changed the Startup Preferences to '-font -size 36' so the objects look nice and neat. 

I am using a Surface Pro 6 / Windows 10, and it now looks and works fine. 

My only question is how to change the starting size of new windows, which are also tiny and I have to resize them every time.

**Comment by matiaslanzi** [comment]
This worked for me on windows 11:
-Right Click .exe > properties > compatibility tab >change high DPI settings.
- tick both boxes and select "System (enhanced)" on the bottom combo box.
- Apply > ok

Ready!

Source:
https://www.thewindowsclub.com/how-to-change-scaling-for-specific-apps-in-windows-11

**Comment by danomatika** [comment]
We should add those keys to the registry for the app with the other app settings. This would be done in `tcl/pd_guiprefs.tcl` at the end of the "registry" section in `::pd_guiprefs::init`. We already do the same on macOS by setting a couple of preferences to disable window state saving, etc. @Spacechild1 What do you think?

**Comment by millerpuckette** [comment]
I think this would be worth doing... I'm scared to try it myself since I don't have a windows machine to test it on :)

**Comment by Lucarda** [comment]
from https://learn.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process

i think there's no need to change the registry. instead we could create a manifest file for `wish8X.exe`. i think `pd.exe` has no role in dpi settings.

i can't test myself as i don't have a highDPI screen.

**Comment by Lucarda** [comment]
if anyone is willing to test:

- create an empty plain text file in utf-8 and paste this:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
  <asmv3:application>
    <asmv3:windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
    </asmv3:windowsSettings>
  </asmv3:application>
</assembly>
```

- save it as `wish86.exe.manifest` somewhere writable as the `documents` dir.

- copy `wish86.exe.manifest` to your `Pd/bin` folder, normally `C:\Program Files\Pd\bin`

- start Pd


@matiaslanzi could you test?

if yes first make sure to return to the state where fonts were small.

**Comment by umlaeute** [comment]
i finally got around to testing this (in a VM; with Windows scaling cranked up to 250%), and I'm afraid I do not see a difference with or without the manifest file (applying the HiDPI  fix in the preferences/registry *does* solve the issue to some extent)

**EDIT** i don't see a difference even if i change the manifest to `<dpiAware>false</dpiAware>` (which I think is the correct value)

**Comment by umlaeute** [comment]
one more thing: I just did a simple `pestr wish86.exe` to see the strings in the binary, and lo and behold! I found:
~~~xml
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0"
xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
    <assemblyIdentity
    version="8.6.2.10"
    processorArchitecture="AMD64"
    name="Tcl.Tk.wish"
    type="win32"
    <description>Tcl/Tk windowing shell (wish)</description>
    <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
<security>
    <requestedPrivileges>
<requestedExecutionLevel
level="asInvoker"
uiAccess="false"
    />
    </requestedPrivileges>
</security>
    </trustInfo>
    <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
<application>
    <!-- Windows 10 -->
    <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
    <!-- Windows 8.1 -->
    <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
    <!-- Windows 8 -->
    <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
    <!-- Windows 7 -->
    <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
    <!-- Windows Vista -->
    <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
</application>
    </compatibility>
    <asmv3:application>
<asmv3:windowsSettings
xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
    <dpiAware>true</dpiAware>
</asmv3:windowsSettings>
    </asmv3:application>
    <dependency>
<dependentAssembly>
    <assemblyIdentity
    type="win32"
    name="Microsoft.Windows.Common-Controls"
    version="6.0.0.0"
    processorArchitecture="AMD64"
    publicKeyToken="6595b64144ccf1df"
    language="*"
</dependentAssembly>
    </dependency>
</assembly>
~~~


which afaiu means, that wish86.exe already contains an embedded manifest which says:
~~~
<dpiAware>true</dpiAware>
~~~

**EDIT** as per [this](https://stackoverflow.com/questions/17853304), embedded manifests override external ones

I did a quick check, replacing this string in the embedded manifest with `<dpiAware>false</dpiAware>` (using ugly `sed` foo), and indeed, the objects now scale correctly:

<img width="1816" height="967" alt="Image" src="https://github.com/user-attachments/assets/79022e8b-3db1-440f-8fe5-26626c78ad0f" />

as you can see, upscaling is rather blocky/aliased.
