### ISSUE TITLE
[intelligent patching] inserting objects broken for non-first connection

### ISSUE THREAD

**Issue by ch-nry** [pure-data/pure-data#573]
Using <kbd>Control</kbd>-<kbd>k</kbd> to insert an object between 2 connected object, or to disconnect the middle object works only if the connection is made with the 1st outlet of the 1 object.
i.e : 
selecting this 3 object and <kbd>Control</kbd>-<kbd>k</kbd> works as expected : 
~~~
[t b b b]
  |  
  |    [f]
  |  
  [f]
~~~

selecting this 3 object and <kbd>Control</kbd>-<kbd>k</kbd> did not work as expected : 
~~~
[t b b]
      |  
      |    [f]
      |  
      [f]
~~~

**Comment by umlaeute** [comment]
sidenote: i formatted your post to use `code`-sections (in order to get monospaced fonts), but i'm not sure about the indentation in the first example.

**Comment by umlaeute** [comment]
to answer your original question: yep, there seems to be a bug.

in the meantime, you can (instead of selecting all three objects) select only the **connection** (between `[t b b]` and the lower `[f]`) and the **object to be inserted**, and hit <kbd>Control</kbd>-<kbd>k</kbd>

**Comment by ch-nry** [comment]
yes, selecting only the connection (and the object to insert) does work.
