### ISSUE TITLE
[intelligent patching] staged undo

### ISSUE THREAD

**Issue by ch-nry** [pure-data/pure-data#574]
Intelligent patching is very useful but it is sometime hard to get used to it. 
In order to facilitated the learning phase, I propose to split the "undo" in 2 action : the action automatically created, and the manual action.
I.E : create one object, create an other one, noticed that the 2 objects are unintentionally connected, cancel the automatic connection using <kbd>Control</kbd>-<kbd>z</kbd>. a 2nd <kbd>Control</kbd>-<kbd>z</kbd> will cancel the creation of the 2nd object. Curently only 1 <kbd>Control</kbd>-<kbd>z</kbd> undo the connection and the object creation.

Same principle should be used when multiples connection are created because multiples objects are selected when creating a connection.

This will make intelligent patching feature less annoying when not done on purpose.

**Comment by umlaeute** [comment]
i'd rather have intelligent patching not step on your toes in the first place (see #568)

**Comment by ch-nry** [comment]
since #568 have not been solved, this look like a good alternate solution (at least for me). 
Moreover, it would also solve the auto-connect feature added few years ago (I'm still not used to it):
When adding an object with a keyboard shortcut, one have to press 2 (or 3 key on french keyboard). adding an extra one is a bit to much for such common task.

**Comment by umlaeute** [comment]
well, there's a branch with a solution for #568 /(i just created pr #575)

**Comment by ch-nry** [comment]
PR #575  is good for intelligent patching, not for the old auto-patch feature. 
I still believe that staged undo is a good solution for the auto-patching function.

**Comment by umlaeute** [comment]
i guess the biggest problem is, that with autoconnect enabled the flow is really:

1. create an empty object
2. connect the last object with the new (empty) object
3. have the user type some characters
4. re-instantiate the empty object with the content the user just typed.

so if we had (staged) Undo, this would
1. remove the newly created object and replace it with an empty object
2. remove the connection
3. remove the empty object

which is most likely not what you want. (i think you want to undo the connection without removing the created object).

**Comment by ch-nry** [comment]
Hum, I understand.
the autoconnect could be changed to : 
- create an object
- have user type some characters
- re-instanciate the object
- connect with last object
But since my problem with intelligent patching is also that the new created object position is not at the mouse position, I guess I  should get used to : control 1, control Z, control 1 to create an object.

**Comment by umlaeute** [comment]
changing the order makes the implementation much more complicated.

btw, you can still use the `-noautopatch` flag to get rid of autopatching (though not the other "intelligent patching" features) if it annoys you out of your wits.

**Comment by ch-nry** [comment]
I do use -noautopatch in my computer, but I also use lot's of other computers that use default behaviours. That is not very practical. I would like to use default behaviours.

Maybe adding a fast and easy keyboard shortcut that clear object selection would be ok.
For example : a double press on the control key. 
that way one can easily defeat the auto-patch feature using only keyboard short-cut...

**Comment by umlaeute** [comment]
as in #547?

**Comment by ch-nry** [comment]
yes

**Comment by umlaeute** [comment]
now that <kbd>Esc</kbd> deselects the current object, you can suppress autoconnection with a one-keypress action (per connection).

does this resolve this issue? (aka: can we close it?)

**Comment by ch-nry** [comment]
let's try like that and see how things goes...
