### ISSUE TITLE
Tcl/Tk Error with Pd-0.49

### ISSUE THREAD

**Issue by oliverstotz** [pure-data/pure-data#578]
sorry for a not so precise bug-report, but it's all i can offer:

recently i discovered a strange behaviour in Windows PD 0.49 (32bit) when the closing of a patch window (or even the closing of a subpatch window) would result in a Tcl/Tk error that i have not excperienced up until PD 0.49.

so, i close a window (main or subpatch - mostly with STRG+w), the patch window turns white with some inlet relics still being displayed and the console prints out a Tcl/TK error message in red colour.

the console says for example this:

~~~
(Tcl) UNHANDLED ERROR: bad window path name ".x3b212c8"
    while executing
"wm title $mytoplevel "$name$dirtychar$arguments - $path""
    (procedure "pdtk_canvas_reflecttitle" line 15)
    invoked from within
"pdtk_canvas_reflecttitle .x3b212c8 {D:/pd_0.49/_MYPATCHES_/MFPOW} {metronome} { [edit]} 0"
    ("uplevel" body line 718)
    invoked from within
"uplevel #0 $docmds".x2596028: no such object
.x2596028: no such object
.x2596028: no such object
.x2596028: no such object
~~~

......................................  ({metronome} is the name of a subpatch with GOP enabled)

from this point on nothing can be done in PD anymore, the only way to get out of this is to kill the PD process from the outside. These "crashes" seem to occur completely random, so unfortunately i can not supply an example patch, but i noticed this:

the patch contains several GOP subpatches and also some of my own GUI abstractions, that contain GOPs. the "crash" only happens when a window is closed.

(the patch is very involved so i couldn't really check what would happen, if i replaced all of my abstractions with something else ...)

**Comment by Spacechild1** [comment]
probably related: https://sourceforge.net/p/pure-data/bugs/1290/

**Comment by bobczz** [comment]
I also encounter this error many times when I use and/or modify GOP, frankly I've never see it before 0.49. I hope someone finds a solution.


[TCL error.txt](https://github.com/pure-data/pure-data/files/3133104/TCL.error.txt)

**Comment by umlaeute** [comment]
i acknowledge the issue (having seen it at least once), but we really need to be able to reproduce it, before we can fix it.

so if anybody can describe how they got the error, *please* share this info.

so far i only know that it is related to *edit*ing *GOP*s (i doubt that merely *using* them - as indicated by @bobczz - is enough to trigger the issue)

**Comment by umlaeute** [comment]
so: i *think* i might have a way to reproduce the problem.

- setup
  - create an abstraction `A`
  - create a **GOP**-abstraction `B` which contains the first abstraction `[A]`
  - create a top-level patch that contains at least *two* instances of `[B]`
- make it fail
  - open one of the `[B]` instances in the top-level patch
  - open the `[A]` instance within the just opened GOP-abstraction
  - save the `[A]` instance
- :boom: 

can anybody confirm that this is indeed triggering the problem we are discussing here?

**Comment by Ant1r** [comment]
I can confirm (Ubuntu 16.04 Pd-0.49).
The message was:
```
(Tcl) COMMANDE INVALIDE : invalid command name ".x9e46a0.c"
    while executing
".x9e46a0.c delete all"
    ("uplevel" body line 6)
    invoked from within
"uplevel #0 $docmds"

```

**Comment by umlaeute** [comment]
@Ant1r well, your error message is significantly different from the ones that @oliverstotz and @bobczz posted.

anyhow, if the problem is the one i think it is, then I think I have a fix (but not yet pushed to github). You could try one of the experimental "less intelligent patching" builds (see "experimental builds" in the top post of #575)

**Comment by Ant1r** [comment]
Yes! You were right, with intellipatch2 I get:
```
(Tcl) ERREUR : bad window path name ".xda9bb0"
    while executing
"wm title $mytoplevel "$name$dirtychar$arguments - $path""
    (procedure "pdtk_canvas_reflecttitle" line 15)
    invoked from within
"pdtk_canvas_reflecttitle .xda9bb0 {/home/arsene/Patchs/test} {B.pd} { [edit]} 0"
    ("uplevel" body line 7)
    invoked from within
"uplevel #0 $docmds"
```

**Comment by umlaeute** [comment]
@Ant1r you could check out the `intellipatch2` branch from https://git.iem.at/pd/pure-data (which contains the supposed fix, and some merges with `master` and `updates/0.50`)

but anyhow, I already know that the [example that i gave](https://github.com/pure-data/pure-data/issues/578#issuecomment-501293126) triggers *some* bug, and that my commit will fix that.
the question i'm really interested in is: is this the bug that @oliverstotz reported or something else?

**Comment by Spacechild1** [comment]
> can anybody confirm that this is indeed triggering the problem we are discussing here?

I can confirm that I get a Tcl error, but it doesn't cause a GUI freeze or crash.

**Comment by Ant1r** [comment]
@umlaeute OK, your fix on  https://git.iem.at/pd/pure-data/intellipatch2 works for me, no more Tcl error when saving `A.pd` located in GOPed `B.pd`.

**Comment by oliverstotz** [comment]
umläute wrote:
> so: i /think/ i might have a way to reproduce the problem.
> 
>   * setup
>       o create an abstraction |A|
>       o create a *GOP*-abstraction |B| which contains the first
>         abstraction |[A]|
>       o create a top-level patch that contains at least /two/ instances
>         of |[B]|
>   * make it fail
>       o open one of the |[B]| instances in the top-level patch
>       o open the |[A]| instance within the just opened GOP-abstraction
>       o save the |[A]| instance
>   * 💥
> 
> can anybody confirm that this is indeed triggering the problem we are 
> discussing here?


i tried your approach and got the same result as christof:

Tcl error but no GUI freeze or crash.

PD 0.49 (64bit) / Windows7 (64bit)



best

Oliver

**Comment by umlaeute** [comment]
then please go ahead and find a way to reproduce the original problem.
(if you can only reproduce it in your huge mega-project that you don't want to expose publicly, feel free to contact me in private)
