### ISSUE TITLE
quotes in settings string causing issue with TCL

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#579]
Singles quotes, as used by loading a font string in the start up settings cause issues with Tcl. There probably needs to be some explicit string escaping going on when processing these commands, either in the GUI or core if the startup settings are sent as a string to the GUI. (I haven't looked yet.)

Relevant copy/paste from Pd-list:

>> I am no expert, but after your first email, I played around a bit. I
>> am on Ubuntu 18.10 running Pd 0.48.2, and I cannot reproduce your
>> problem. I tried:
>> 
>>     pd -font-face "Celeste Small"
>> 
>> Pd started OK, and Celeste Small was loaded as the default font (see
>> screenshot — just a labelled canvas).
> 
> strange ... this is what happens on my system when i do this:
> 
> WARNING: Font family '"Celeste' not found, using default (DejaVu Sans Mono)
> 
> Small": can't open
> -font-size: can't open
> 12: can't open
> -font-weight: can't open
> normal: can't open
> (Tcl) UNHANDLED ERROR: extra characters after close-quote
>     while executing
> "pdtk_startup_dialog .gfxstub5648e27e9080 0 "-font-face "C"
>     ("uplevel" body line 7)
>     invoked from within
> "uplevel #0 $docmds"
> 
> from that point on PD doesn't respond to anything anymore.
> 
> Tested on both PD 0.48 and PD 0.49
> 
> BTW: my system is:
> Ubuntu 19.04 (Disco Dingo) with an XFCE desktop
> 
> (but the same happened on a Ubuntu 18.04.2 LTS)

**Comment by umlaeute** [comment]
moved milestone to corresponding PR #741
