### ISSUE TITLE
Graph on parent Pd crash

### ISSUE THREAD

**Issue by bobczz** [pure-data/pure-data#589]
Debian Stretch 64bit
Pd Vanilla 0.49

1. ctrl+n for a new window
2. put graph
3. open graph
4. put object or comment (**only these two**)
Pd closes immediately without any error message
Note: if you put on graph other elements (bang, number, slider ect) works great.

**Comment by Spacechild1** [comment]
confirmed (Windows 7)

**Comment by porres** [comment]
that just happened to me, macOS mojave

**Comment by umlaeute** [comment]
@bobczz what's the use-case of adding an object into a graph?

**Comment by bobczz** [comment]
@umlaeute the "classic" GOP use, to make, in my case, compact GUI of effects and instruments. See snapshot. Thanks!
![snapshot_20190509](https://user-images.githubusercontent.com/49860580/57481003-7208ef00-72a1-11e9-92f2-149e9aed35ef.png)

**Comment by umlaeute** [comment]
i'm not talking about a GOP in general (as in: GOPifying an abstraction or a subpatch), but rather why you would want to abuse a `graph` window to put code therein.

also, your screenshot doesn't show anything related to `graph`.
btw, ordinary GOPified abstractions/subpatches work nicely.

**Comment by bobczz** [comment]
The problem, for me, is the creation of a GOP:
Please be patient:
1. menu Put
2. put graph (on Linux Shift+Crtl+G)
3. right click for open and place an object on graph window and Pd crash.
Isn't this the correct procedure for GOP?
I think we talk about different things, maybe?
What you see on screenshot are GOP make with older version than 0.49.

**Comment by umlaeute** [comment]
yes, but this is not how GOPs are supposed to be created (where did you learn that weird way to create GOPs?)

the intended way to create GOPs is:
- open a new patch (<kbd>Ctrl</kbd>-<kbd>n</kbd>)
- right-click the canvas and select `Properties`
- toggle the `Graph-On-Parent` checkbox
   - eventually change the size and margin parameters
- click `Apply`

**Comment by bobczz** [comment]
Frankly I don't remember where I learned this method but I've always used it from many, many years... and I suppose I'm not the only one. Anyway, thank you for the explanation.

**Comment by Spacechild1** [comment]
> this is not how GOPs are supposed to be created

IMO it's a valid shortcut. after all, a "graph" is nothing but a subpatch with GOP enabled, there's nothing special about them. you can even use GOP-subpatches as "graphs" for arrays.

**Comment by umlaeute** [comment]
@Spacechild1 actually this is not entirely true, else we wouldn't get a crash in the first place (the problem is that when adding a graph, it's canvas is not created as a proper canvas).

also i don't see much of a "shortcut" here (how many steps/keystrokes/... do you save?

**Comment by Spacechild1** [comment]
> actually this is not entirely true, else we wouldn't get a crash in the first place

the crash happens because the undo queue is not initialized for graphs. this is a bug and the fix is trivial (see my PR). before 0.49 there wasn't a relevant difference, both could be used interchangingly.

> it's canvas is not created as a proper canvas

what do you mean by that? it's true that they are created differently in the sense that they don't use the same constructor methods, but in the end `canvas_new` and `glist_addglist` do the same thing (which I found quite confusing to be honest).

> also i don't see much of a "shortcut" here (how many steps/keystrokes/... do you save?)

well, 1 click (or key combo) instead of: create new object + typing [pd foo] + right click + turn GOP on. so how is it not a shortcut for creating an anonymous GOP subpatch?

**Comment by umlaeute** [comment]
> the crash happens because the undo queue is not initialized for graphs. this is a bug and the fix is trivial (see my PR). before 0.49 there wasn't a relevant difference, both could be used interchangingly.

actually i missed your PR. thanks for reminding me :-)

> 
> > it's canvas is not created as a proper canvas
> 
> what do you mean by that? it's true that they are created differently in the sense that they don't use the same constructor methods, 

this.

> 
> > also i don't see much of a "shortcut" here (how many steps/keystrokes/... do you save?)
> 
> well, 1 click (or key combo) instead of: create new object + typing [pd foo] + right click + turn GOP on. so how is it not a shortcut for creating an anonymous GOP subpatch?

1. it's more than "1 click (or key combo)"
2. but i was also asking (though admittedly not explicitly) about how many keystrokes do you safe *in total*.

**Comment by Spacechild1** [comment]
> about how many keystrokes do you safe in total.

I save only 2 keystrokes, but 3 mouse clicks.

also have a look at how a graph is actually saved (hint: just as a subpatch ;-)

**Comment by Spacechild1** [comment]
BTW, I did some Pd archeology by trying out ancient Pd releases on Windows (ah, the joy of backwards compatibility).

* Pd 0.34 (2001) and older: subpatches don't have any GOP functionality yet, while graphs/arrays are strictly GOP (you can't even open them), so at least from the outside they appear to be different things.
* Pd 0.35 (2002): subpatches can be made GOP but there is no notion of a GOP rect: instead the whole subpatch content is "squeezed" into visible area on the parent patch or the area is expanded (couldn't figure out the logic). graphs/arrays can be opened and treated just like subpatches.
* Pd 0.39 (2005): introduces the GOP rect as we know it today.

**Comment by Spacechild1** [comment]
Closed with 9d6795b in https://github.com/pure-data/pure-data/pull/508

**Comment by porres** [comment]
> Pd 0.39 (2005): introduces the GOP rect as we know it today.

that's when I got into Pd and I always took for granted it had been like that all along :)

**Comment by Spacechild1** [comment]
> that's when I got into Pd

:-o
