### ISSUE TITLE
issue with turning off GOP area

### ISSUE THREAD

**Issue by LGoodacre** [pure-data/pure-data#59]
There is a small bug in PD while turning off the GOP area through the properties menu. Let's say you have a subpatch or abstraction on the canvas which has "GOP" and "hide object name and arguments" selected. If you go to the properties menu and deselect GOP and hit apply, it won't turn off.

What does work is to turn the "hide..." option off, apply, then turn the GOP off and apply. But I'd imagine that a lot of users will get confused searching for this.

**Comment by pierreguillot** [comment]
The problem seems to be solved bca0f5c9141ad15e275d61dda2f5e150de68ed90
