### ISSUE TITLE
keyboard shortcuts and capital letters

### ISSUE THREAD

**Issue by LGoodacre** [pure-data/pure-data#60]
It would be really super wonderful if Ctrl + s, e, c, v, and d worked with capital letters also. Reason: you can't use these handy shortcuts if caps lock is on. Seems like this would be an easy fix.

**Comment by umlaeute** [comment]
hmm,... <kbd>Ctrl</kbd>+<kbd>s</kbd> (aka `Save`) is already something different as <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>s</kbd> (aka `Save as...`)...and those two keystroke assignments are very common.

And the difference between <kbd>Shift</kbd>+<kbd>s</kbd> and uppercase `S` (<kbd>CapsLock</kbd>-<kbd>s</kbd>) is somewhat...subtle.

OTOH, <kbd>CapsLock</kbd>-<kbd>Ctrl</kbd>+<kbd>s</kbd> seems to be something different from <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>s</kbd>, whereas <kbd>CapsLock</kbd>-<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>s</kbd> seems to be the same as <kbd>Ctrl</kbd>+<kbd>s</kbd>. urgh.

**Comment by umlaeute** [comment]
if you have access to non-linux platforms, it would be great if you could test the PR #61.
(just replace the [pd_bindings.tcl](https://github.com/pure-data/pure-data/blob/capslock-keybindings/tcl/pd_bindings.tcl) file; no need to recompile...)

**Comment by LGoodacre** [comment]
Sorry for the delayed response. I tested the new pd_bindings.tcl on Windows 10 and it seems to work perfectly. I tried Ctrl S, N, C, V, D, and they all seem to work as expected. In addition, Ctrl + Shift + s/S calls save-as regardless of case, as expected. Nice job. I'd love to see this included in the next release.

**Comment by LGoodacre** [comment]
Sorry for the delayed response. I tested the new pd_bindings.tcl on Windows 10 and it seems to work perfectly. I tried Ctrl S, N, C, V, D, and they all seem to work as expected. In addition, Ctrl + Shift + s/S calls save-as regardless of case, as expected. Nice job. I'd love to see this included in the next release.

**Comment by LGoodacre** [comment]
Sorry for the delayed response. I tested the new pd_bindings.tcl on Windows 10 and it seems to work perfectly. I tried Ctrl S, N, C, V, D, and they all seem to work as expected. In addition, Ctrl + Shift + s/S calls save-as regardless of case, as expected. Nice job. I'd love to see this included in the next release.
