### ISSUE TITLE
annoying error when closing a closed [text] window

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#610]
currently, [text] uses 'click' and 'close' messages, but this is more of a hack, as you don't have 'official' methods to open and close. And if you give it a 'close' message for an object that is closed, you get an annoying error. Maybe a more official 'vis' method would be better for this and would be able to filter the error.

I tried checking in the code where the 'close' message is handled in the code, so I could maybe temper with it, but I couldn't find it yet.

**Comment by porres** [comment]
this is the kind of error you get

<img width="491" alt="Screen Shot 2019-04-30 at 19 19 25" src="https://user-images.githubusercontent.com/5360142/56997060-e2ff2700-6b7c-11e9-9596-83ee064fe8cf.png">

**Comment by porres** [comment]
I see now where the close message is, it's here and, if I'm correct, it calls this sys_vgui  function: https://github.com/pure-data/pure-data/blob/e17154abc2a7cd0f6298a10f48e0dc1e9a1c927e/src/x_text.c#L103

which then sends a message to Pd here https://github.com/pure-data/pure-data/blob/6d0825bcd349f64e186d152af02b161f94fdac62/tcl/pdtk_textwindow.tcl#L54 

And when Pd receives this message for a window that's already closed, here is where the error is printed: https://github.com/pure-data/pure-data/blob/a9fd832e9b2ad355292b5eb1ecdb94139e08f2a7/src/m_binbuf.c#L704

**Comment by porres** [comment]
Now, if you comment that error message, the annoyance is over, but that's not the best thing to do I guess :) 

It would be just great to not call "sys_vgui("pdtk_textwindow_doclose .x%lx\n", x);" if the window is not openned.

**Comment by porres** [comment]
I'm figuring out a way to have a flag that tells us if the window is open, so it only closes it it's openned.

I'll send a PR for it. 

I'll also work on an alias message for 'click' that's just 'open', because I think it makes better sense to work with 'open' and 'close', instead of 'click' and 'close'. Then we don't need a 'vis <float>' message.

**Comment by porres** [comment]
So, https://github.com/pure-data/pure-data/pull/611 fixes the annoying error and documents a new 'open' message instead of 'click'.

Maybe we could do the same now for [qlist].

**Comment by millerpuckette** [comment]
I can't reproduce the annoying message... perhaps this got fixed elsewhere?
"click" and "close" are indeed a stupid name pair, but I'm not so into making internal messages make sense to users :)

**Comment by porres** [comment]
I can't reproduce it either

**Comment by umlaeute** [comment]
it was fixed a year ago with 50eafdadc9d282935ce1fce4f483947247c82c89
