### ISSUE TITLE
Fix link to 0.49.1 installer on downloads page

### ISSUE THREAD

**Issue by RichardJECooke** [pure-data/pure-data#613]
On the Pure Data info [website ](https://puredata.info/downloads/pure-data/releases/0.49-1) the download link for release 0.49.1 points to 0.49.0: http://msp.ucsd.edu/Software/pd-0.49-0.windows-installer.exe.

I really need 0.49.1 to work with the ceammc soundfont library. Please update the link.

I tried downloading http://msp.ucsd.edu/Software/pd-0.49-1.windows-installer.exe manually but it doesn't exist.

**Comment by Spacechild1** [comment]
the 0.49.1 release only fixed a packaging error on macOS, apart from that there is no difference to 0.49 (i.e. the code is the same), see: http://msp.ucsd.edu/software.html

**Comment by umlaeute** [comment]
i can confirm @Spacechild1 : there is no `0.49-1` release for any platform except macOS.
