### ISSUE TITLE
unexpected behaviour with unescaped '$0-x'

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#620]
Hi there, I've been making some tests and working on an object that gets arguments from a canvas, based on [iemguts/canvasargs], for this PR => https://github.com/pure-data/pure-data/pull/617

The idea is to load arguments from an abstraction and the thing I noticed is that there are issues when we have inserted an unexpanded and unescaped argument such as "$0-x" (which can be a receive name, for instance). 

This is dealt hardly in the patch, and the first thing funny about it is that it doesn't get output as a symbol message. This is in the case it's a single argument, where it should come out as a symbol as any other symbol argument is.

Moreover, it it is part of a list, say "1 $0-x" we cannot use [unpack f s] to get it as a symbol, as it gives a "type mismatch" error. This is for the same reason, that it doesn't get a selector somehow. There's a way to get "$0-x" from "1 $0-x" without [unpack], like using [list store] and 'get', but guess what comes out, a symbol message as it should? Nope... just "$0-x" without a selector.

You can reproduce this with [canvasarg] and an abstraction that loads something like "$0-x". But I have another way to create such a problematic string in Pd using [else/toany]. Basically this is the same as [list to symbol] but without the symbol selector.

check it out.

<img width="730" alt="Screen Shot 2019-05-06 at 17 24 11" src="https://user-images.githubusercontent.com/5360142/57254035-a15ff780-7026-11e9-88bc-b0cbd112765c.png">

So, '36 48 45 120' is the list that creates the '$0-x' message. See how it gets printed alright, and now let's try to force Pd to give it a selector. First with [symbol], no luck, we get 'symbol list'. Then with a [list] object, in the same way as I informed above, with [list store], we don't get a selector.

Anyway, the only method I could get it to become a symbol was by using [list fromsymbol] and [list tosymbol].

Maybe this is a known issue and an explainable and expected behaviour for very practical and understandable reason, but I don't know that, so I opened this issue :) 

One way or another, this is something I'd like to learn and at least point it out in a tutorial somewhere.

cheers

**Comment by Spacechild1** [comment]
> You can reproduce this with [canvasarg] and an abstraction that loads something like "$0-x".

you're right. this is a bug in [iemguts/canvasargs], [dollarg] from iemlib works as expected.

> But I have another way to create such a problematic string in Pd using [else/toany].

I tried your bytes list with [list tosymbol] --> [list trim] and it works as expected. I think the problem is in [else/toany]. I can see that you're using `binbuf_text`. note that this function parses text to a list of Pd atoms - including A_SEMI, A_COMMA, A_DOLLAR, A_DOLLSYM which are not allowed in Pd lists on the patch level! in your case, you get a A_DOLLSYM as the selector which can lead to all kind of weirdness. 

have a look at [fudiparse], it explicitly checks against "forbidden" atoms.

**Comment by porres** [comment]
the [toany] object was a specific request by Liam Goodacre, he needed this exact behaviour, but I don't remember why. I never had a use for it until today, to investigate this. Since Liam kinda stoped developing for Pd, maybe no one needs this anymore and I could just get rid of it :)

**Comment by porres** [comment]
> [dollarg] from iemlib works as expected.

For what I see, what [dollarg]  does is bad for me as it's not what I want all! This is because it just expands the $0 value, maybe using realizedollar or something. 

I actually need '$0' as it is, and the way Pd deals with it is just funny/weird. Not that I can't deal with it myself, but... feels like something we should look into and not an issue with [canvasargs] or [toany]

**Comment by porres** [comment]
> I tried your bytes list with [list tosymbol] --> [list trim] and it works as expected.

yes, I know, using [list tosymbol] is the only solution I found to this issue, and I presented it as such. The thing is that other stuff don't work and I think they should.

**Comment by Spacechild1** [comment]
> he needed this exact behaviour

I highly doubt that ;-)

**Comment by Spacechild1** [comment]
> The thing is that other stuff don't work and I think they should.

again: this is both a bug in [iemguts/canvasargs] and [else/toany]. Pd lists on the patch level must only contain A_FLOAT, A_SYMBOL and A_POINTER

**Comment by Spacechild1** [comment]
> For what I see, what [dollarg] does is bad for me as it's not what I want all! 

well, it's exactly the behaviour I would expect. if I do `[myabs $1 $2 $3]` I want to pass the arguments of the parent canvas down to the abstraction. If the parent canvas has the creation arguments `foo bar baz`, [list append $1 $2 $3] in myabs will output `foo bar baz`. why should [canvas args] be different? I want the *actual values* of the creation arguments, not what I've typed into the text box on the parent canvas!

**Comment by Spacechild1** [comment]
after all, isn't the purpose of [canvas args] that I can get a list of all creation args? as we all know, the problem with [list append $1 $2 $3 ...] is that I have to know the number of arguments in advance.

**Comment by porres** [comment]
Well, I mentioned this on the first comment, but let me try and be clearer so you can see how Pd is acting funny.

I'm gonna use [toany] again, but now I'll create a list that starts with a float "1", followed by a symbol "$0-x". 

See that in [else/display] I don't handle this well (at least yet), so what happens is that it also shows us it's really getting an unexpanded "$0-x" symbol, but it internally expands it to the abstraction value. Down the chain, another [display] value shows a different number, for example. And it receives 'n' characters long but it gets expanded to more characters when I display it, that's why the displayed string is out of bounds.

Well, routetype just routes a list message wihtout clipping its list selector, unlike [route], this is to prove we have a list that starts with 1, followed by $0-x.

And here's when it gets funny. I try to unpack this list, but Pd doesn't handle '$0-x' and gives me a type 'mismatch'

<img width="407" alt="Screen Shot 2019-05-06 at 19 48 41" src="https://user-images.githubusercontent.com/5360142/57259998-1f78ca00-7038-11e9-9412-5cec908380e5.png">

**Comment by Spacechild1** [comment]
Alex! I tried to tell you several times that [else/toany] is buggy! it outputs atoms of type A_DOLLAR, A_DOLLARSYM etc.  so all kinds of weird stuff can happen with such malformed Pd lists... first fix the bug in your object and then run your tests again.

> really getting an unexpanded "$0-x" symbol,

no, in your case you get an dollarsym atom because of [else/toany]. it has the same t_word (t_symbol *), but a different atom type (A_DOLLSYM). many Pd methods/objects expect valid Pd lists and don't check for those "forbidden" atom types, so you get all kinds of weird behaviour.

**Comment by Spacechild1** [comment]
you can easily see one of such resulting errors in [else/toany] itself: why do you get a *list* in the first place? because you check if the first atom is A_SYMBOL, and if not you treat it as a list. the problem is that "$0-x" as parsed by `binbuf_text` is an A_DOLLSYM and *not* an A_SYMBOL.

**Comment by porres** [comment]
But then, does [canvasarg] have the same exact issues? see: https://github.com/iem-projects/pd-iemguts/blob/master/src/canvasargs.c

> no, in your case you get a dollarsym atom

I see, perhaps the solution for both [toany] and [canvasargs] would be to escape these with a backlash? anyway, I gotta think now...

**Comment by porres** [comment]
The thing is that I don't want an expanded symbol like [dollarg] gives! The canvasargs object actually gives me something I can use and I'm happy with.

But I just tested it now and saw that Pd blew up when I gave the abstraction just "$0" or "$1" and that doesn't look good at all!

**Comment by Spacechild1** [comment]
> But then, does [canvasarg] have the same exact issues?

for the version you are using - yes! but the current development version is here: https://git.iem.at/pd/iemguts/blob/master/src/canvasargs.c

you can see that it adds an option to get the *raw* canvas args, where the dollarsym is escaped.

**Comment by porres** [comment]
hmmm https://github.com/iem-projects/pd-iemguts/blob/master/src/canvasargs.c#L64

**Comment by Spacechild1** [comment]
> The canvasargs object actually gives me something I can use and I'm happy with.

I don't understand you use case then... *my* use case to get a list of all canvas arguments, because with [list append $1 $2 $3 ...] I have to know the number of creation args in advance. can we agree on that?

**Comment by Spacechild1** [comment]
just to be clear: I'm speaking about *getting* the canvas args. setting them is another topic.

**Comment by Spacechild1** [comment]
the recent iemguts version I've should you has the option to get the raw unexpanded canvas args. but this is only for special use cases (I guess when you want to replace certain args, you first need to get the original unescaped args to preserve dollarsyms).

**Comment by porres** [comment]
say you're designing an abstraction that behaves pretty much like an iemgui.

Then you can set a receive as an argument using whatever, like "$0-x"... and that will be your receive name. Of course we'd need something like https://github.com/pure-data/pure-data/pull/604 - or a hacky dinamic patching deal to do this in vanilla... (or an external), but back to the use case.

If I'm using [dollarg], what I get as the receive name is an expanded symbol, like [1003-x], and that is just bad...

Now, of course, if I set it like "\$0-x" then it works like a charm. But I'm not expecting people to intuitively do that, so I'm hoping for a way to deal with it, maybe escape it with a backlash...

**Comment by porres** [comment]
>  the recent iemguts version I've should you has the option to get the raw unexpanded canvas args.

what? where do I get that?

**Comment by Spacechild1** [comment]
https://github.com/pure-data/pure-data/issues/620#issuecomment-489820033

**Comment by Spacechild1** [comment]
ok, I understand your use case now, but in this case the user must escape the $0 like `[myabs \$0-foo]` - there's no way around it because I might as well write [myabs $0-foo] where I *want* the $0 to expand.

**Comment by Spacechild1** [comment]
> Now, of course, if I set it like "\$0-x" then it works like a charm. But I'm not expecting people to intuitively do that

just document it.

**Comment by Spacechild1** [comment]
to sum it up: don't mess with the creation argument handling and just do it like [dollsym] - please! everything else is a minefield.

**Comment by Spacechild1** [comment]
of course you can add an *option* to get the "raw" creation arguments, but don't make it the default! and it won't help the use case you've mentioned because of https://github.com/pure-data/pure-data/issues/620#issuecomment-489822428

**Comment by porres** [comment]
what is the use case of getting it raw then? Since [canvasargs] is now heading into giving that option...

**Comment by Spacechild1** [comment]
just for the record: the recent iemguts version returns the actual (expanded) creation argument values by default, so I hope this convinces you that the old behavior was a bug :-)

> what is the use case of getting it raw then?

https://github.com/pure-data/pure-data/issues/620#issuecomment-489821214

say I do [foo $1 x y] and inside [foo] I want to replace the second creation argument with z and save the abstraction. I want to make sure that the literal creation arguments are preserved when saving so that's where getting the "raw" symbol gets handy. but this is all a bit hazardous.

**Comment by Spacechild1** [comment]
anyway, let's close this issue because it's not an error in Pd but with an old version of [iemguts] and [else/toany].

**Comment by porres** [comment]
ok

**Comment by porres** [comment]
not sure I still get that use case, maybe a test patch would help. If a literal $1 is needed, why not load it as \\$1? Or is 'raw' something different than 'literal'? 

Anyway, I'm in the task of designing and thinking about a [canvas arg] object for https://github.com/pure-data/pure-data/pull/617

The ability to save new arguments is also something I think is useful, but I'm not sure there's a place in Pd for whatever edge case this is :) - I'll just work on a simpler design and, I don't know, maybe if we think hardcore cases may be useful, we do it later...

**Comment by Spacechild1** [comment]
> I'll just work on a simpler design and, I don't know, maybe if we think hardcore cases may be useful, we do it later...

+1 BTW, thanks for working on this, being able to get the creation args as a list is really overdue, so we could finally do proper default argument handling in abstractions :-)

**Comment by porres** [comment]
> +1 BTW, thanks for working on this, being able to get the creation args as a list is really overdue, so we could finally do proper default argument handling in abstractions :-)

tell me about it. I just put it up... I'm actually going for a rather different approach than [canvasarg] in the end. And it seems to work fine. https://github.com/pure-data/pure-data/pull/617

**Comment by porres** [comment]
more precisely https://github.com/pure-data/pure-data/pull/617/commits/c874927fa42e7553439ee6fef34b36e422688b26
