### ISSUE TITLE
literal '\' freeze iemguis

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#622]
If I try to name a label with a literal backlash, Pd freezes

<img width="254" alt="Screen Shot 2019-05-08 at 17 33 11" src="https://user-images.githubusercontent.com/5360142/57406649-aef8b700-71b7-11e9-9533-8f875d9402df.png">

here's a test patch, click on the message and watch Pd become unresponsive

[crash-test.pd.zip](https://github.com/pure-data/pure-data/files/3159202/crash-test.pd.zip)

**Comment by Spacechild1** [comment]
a single escaped backslash seems to generally cause weirdness. try `[send \\(` for example. I agree that it should be possible to display such a symbol. I think this could be part of the iemgui update.

**Comment by porres** [comment]
It seems it can't handle literal characters in general inside a label...

For instance, this gets expanded

<img width="202" alt="Screen Shot 2019-05-09 at 14 23 33" src="https://user-images.githubusercontent.com/5360142/57473429-30a71e00-7266-11e9-82e3-c787dac6acc7.png">

**Comment by porres** [comment]
> It seems it can't handle literal characters in general inside a label...

Not true, not "in general", this works, for instance

<img width="249" alt="Screen Shot 2020-04-16 at 14 22 37" src="https://user-images.githubusercontent.com/5360142/79486880-c0645900-7fed-11ea-9b8f-2cebe2113e99.png">

**Comment by porres** [comment]
> this works, for instance

not fully... well, many issues in iemguis and I'm trying hard to make sense of it.

- literal \ freezes 
- literal $0 gets expanded, but this is a separate issue and not a "general" issue related to the above
- literal things like comma kinda work, but they trigger a tcl error when you try to open the properties dialog afterwords, and this seems to be yet another unrelated issue (see image below for the error)

<img width="513" alt="Screen Shot 2020-04-16 at 14 27 19" src="https://user-images.githubusercontent.com/5360142/79487296-6ca63f80-7fee-11ea-872b-f2004c2c73b5.png">




 even though it is unrelated to a literal $0 getting expanded in the label

**Comment by porres** [comment]
> literal $0 gets expanded, but this is a separate issue and not a "general" issue related to the above

it's probably related to this https://github.com/pure-data/pure-data/issues/558

**Comment by porres** [comment]
> I think this could be part of the iemgui update.

I'm trying to organize all issues related to updating iemguis, I edited this issue and included more issues under a newly named issue regarding escaping characters in general.

**Comment by porres** [comment]
regarding "issue 1", @umlaeute  mentioned about it in https://github.com/pure-data/pure-data/pull/647 , saying that fix was closely related, but that he didn't adress this because he "gave up, not wanting to put the same code again and again in about 60 or so places; iemguis ought to be modularized first"

**Comment by porres** [comment]
kinda related, trying to setting a label as "\" in atom boxes sets the label to "empty"
