### ISSUE TITLE
no "inf" and "nan" for [nbx]

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#629]
As part of the iemgui updates that we were talking about here, I'd like to point out these issues. First is that [nbx] will not print "inf". I actually know of a hacky workaround way for it to be able to print 'inf', but it's too ugly. Anyway, check below.

<img width="259" alt="Screen Shot 2019-05-11 at 17 49 19" src="https://user-images.githubusercontent.com/5360142/57574753-21b29e00-7415-11e9-9e7e-7d96b0c3eb49.png">

Unlike the atom box, the code of numbox creates min/max values here:

https://github.com/pure-data/pure-data/blob/master/src/g_numbox.c#L777

with the atom box, by default, you get a range from 0 to 0 and this means it's unrestricted. So it can go up to inf or -inf... but with nbx, a range of 0-0 clips it to this single value of 0... and since it does not understand if you type "-inf" or "inf" as an actual infinite float, we're pretty much tied up in setting this via the interface. My suggestion is to make it simply behave like the atom box and fix this inconsistency.

--------------

Now, regarding nans, this is an old issue I opened here, that I closed and now I'm reopening as part of this new issue.

In Pd 0.46, there was some bug introduced where NaNs were not displayed either in the atom box or [nbx], this was fixed for atom boxes in 0.47, but not [nbx]. This was probably introduced here, where the comparison would filter nans: https://github.com/pure-data/pure-data/commit/cd737749b51e03ba1bdc6d8b66b890d89823d158

I just tried a quite old version of Pd (0.43) and we can see here how this used to work fine

![Screen Shot 2019-05-11 at 18 15 04](https://user-images.githubusercontent.com/5360142/57574915-66d7cf80-7417-11e9-9b67-38a2a7536981.png)

This was also brought up in the Pd dev list https://lists.puredata.info/pipermail/pd-dev/2017-07/021185.html , where it mentioned a simple revert didn't seem to work, so something else must be going on...

both inf and nan display were really important for an object like [cyclone/number~]

**Comment by porres** [comment]
In Current Vanilla, instead of a NaN, the number box just sends whatever last value it had... which is quite bad. If it would convert to '0' that was something else, this is not what happens. In here, 0 is just the value loaded by default. 
<img width="264" alt="Screen Shot 2019-05-11 at 18 07 13" src="https://user-images.githubusercontent.com/5360142/57574936-cb932a00-7417-11e9-8447-8ade20687849.png">

**Comment by porres** [comment]
https://github.com/pure-data/pure-data/pull/631 fixes it

**Comment by porres** [comment]
> In Current Vanilla, instead of a NaN, the number box just sends whatever last value it had... which is quite bad. If it would convert to '0' that was something else, this is not what happens. In here, 0 is just the value loaded by default. <img alt="Screen Shot 2019-05-11 at 18 07 13" width="264" src="https://user-images.githubusercontent.com/5360142/57574936-cb932a00-7417-11e9-8447-8ade20687849.png">

**Comment by umlaeute** [comment]
is this last comment some glitch? it looks identical to https://github.com/pure-data/pure-data/issues/629#issuecomment-491543948

**Comment by porres** [comment]
oops, probably something stupid I did, let's delete them all

**Comment by porres** [comment]
fixed with https://github.com/pure-data/pure-data/pull/1633
