### ISSUE TITLE
fft: ooura_init lock consistency error

### ISSUE THREAD

**Issue by jpcima** [pure-data/pure-data#63]
Hello, I am trying to make a version of [libpd](https://github.com/jpcima/libpd) which is up to date with Pd's master branch.
The pd-test program fails on test-extra.pd, having Pd built with PDINSTANCE defined.

    bonk version 1.5
    fiddle version 1.1 TEST4
    pique 0.1 for PD version 23
    sigmund~ version 0.07
    error: consistency check failed: pd_globallock

This traces back to ooura_init. The bug condition suggests a pd_globallock() is attempted without a previous sys_lock(). It works for me using this solution, is this a correct fix?

    diff --git a/src/d_fft_fftsg.c b/src/d_fft_fftsg.c
    index 36853b2..d915008 100644
    --- a/src/d_fft_fftsg.c
    +++ b/src/d_fft_fftsg.c
    @@ -48,6 +48,7 @@ static int ooura_init( int n)
             return (0);
         if (n > ooura_maxn)
         {
    +        sys_lock();
             pd_globallock();
             if (n > ooura_maxn)    /* recheck in case it got set while we waited */
             {
    @@ -64,6 +65,7 @@ static int ooura_init( int n)
                     error("out of memory allocating FFT buffer");
                     ooura_maxn = 0;
                     pd_globalunlock();
    +                sys_unlock();
                     return (0);
                 }
                 ooura_costab = (FFTFLT *)t_getbytes(n * sizeof(FFTFLT)/2);
    @@ -73,12 +75,14 @@ static int ooura_init( int n)
                     t_freebytes(ooura_bitrev, ooura_bitrevsize);
                     ooura_maxn = 0;
                     pd_globalunlock();
    +                sys_unlock();
                     return (0);
                 }
                 ooura_maxn = n;
                 ooura_bitrev[0] = 0;
             }
             pd_globalunlock();
    +        sys_unlock();
         }
         return (1);
     }

**Comment by jpcima** [comment]
The steps to reproduce are to clone my libpd repo recursively, then
- at the top, run `make EXTRA=true`
- `make` again in samples/c/pdtest
- `./pdtest test-extra.pd $(pwd)`

**Comment by Spacechild1** [comment]
the ooura buffers are now thread local
