### ISSUE TITLE
[vu] has no "send symbol" and its outlets can't be hidden

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#632]
[vu] only has "receive symbol".

I use this mostly for hiding inlets/outles, but I can't hide the outlets of [vu]...

**Comment by Spacechild1** [comment]
to be honest, I never realized that [vu] actually has outlets... now I'll always notice, thanks a lot! :-p 

adding a send symbol means we would have to append it to the object binbuf for backwards compatibility which would be very ugly... also, the outlets of [vu] just pass the input, which doesn't seem to be very useful to me... maybe we can just hide them by default?

**Comment by porres** [comment]
why ugly? just add an extra argument... it'll be a bit weird that it's in the end, far from the send argument, but no one will ever notice

**Comment by porres** [comment]
it's hard to notice them because the background color is pretty dark by default. The way I dealt with this in [else/meter~] was by having it set to full blown black as the inlet color. But I actually wanted to mess with the color differently...

Anyway, what just stroke me is that there are two inlets and only one receive symbol. Of course if you really want to use a send address, you can send it a list of 2 values and it'll work.

But what about the send symbol? It'll be just one, it'll hide the two outlets and it'll send the value of just one outlet?

I think not...

Maybe the send address can actually send a list of 2 values.

So yeah, it's a bit tricky to mess with this, it's just a design flaw that's kinda cumbersome to fix.

**Comment by Spacechild1** [comment]
> Anyway, what just stroke me is that there are two inlets and only one receive symbol. 

the receive symbol takes a list of 2 floats: rms + peak

> Maybe the send address can actually send a list of 2 values.

yes, so it would mirror the behavior of the receive symbol. anyway, I don't understand the purpose of the outlets at all, so I would just hide them :-D

**Comment by porres** [comment]
>  so I would just hide them :-D

I know, they shouldn't exist! Perhaps just hiding them is not that bad of an idea...

**Comment by porres** [comment]
> I don't understand the purpose of the outlets at all,  so I would just hide them :-D

I know, they shouldn't exist! Perhaps just hiding them is not that bad of an idea...

If an ugly fix is what we're looking ahead one way or the other, this is not the ugliest and it's just the easiest. The object will still have phantom outlets for those who ever used it (I doubt anyone ever did, though). But in practice this would be like removing them and not documenting it or giving people a hint it exists.

**Comment by porres** [comment]
[vu] actually has a placeholder in the arguments for the send symbol, but it's always "empty".

It doesn't seem so hard to actually include a send symbol in the end.

> adding a send symbol means we would have to append it to the object binbuf for backwards compatibility which would be very ugly... 

what do you mean @Spacechild1 ? Have you checked the code?

**Comment by porres** [comment]
Ok, I don't actually understand how 'vu' keeps saving the send symbol as "empty". The save part seems to just ignore and skip it https://github.com/pure-data/pure-data/blob/master/src/g_vumeter.c#L445

this doesn't make sense to me, so I can't fix this

**Comment by Spacechild1** [comment]
> Have you checked the code?

obviously not

**Comment by Spacechild1** [comment]
`#X obj 305 103 vu 15 120 receive label -1 -8 0 10 -257985 -1 1 0;`

**Comment by Spacechild1** [comment]
by convention, the iemguis have the send, receive and label argument in a row. I don't think the send symbol is so important to break this rule and add it to the end. on the other hand, hiding the outlet boxes is simple: just deactivate all code which follows a check for `!x->x_gui.x_fsf.x_snd_able`. I just tried it, it works.

**Comment by porres** [comment]
oh, my bad :(

**Comment by porres** [comment]
I forgot about the label!

**Comment by porres** [comment]
> just deactivate all code which follows a check for !x->x_gui.x_fsf.x_snd_able. I just tried it, it works.

yeah, I'll do that and just send a PR.

If people think we should implement a send symbol and averything, I can also work on it and add the send name argument to the end. It wouldn't break anything...

**Comment by porres** [comment]
> yeah, I'll do that and just send a PR.

https://github.com/pure-data/pure-data/pull/634

**Comment by porres** [comment]
So, I was trying the other solution of adding a send symbol and yeah, setting a send symbol in the end of the argument string requires lots of surgery in 'g_all_guis.c' -  because actually ALL GUI share the same code... so setting a different standard for vu wouldn't be that simple. Hence, it's actually a matter to think if it's worth it.

Honestly, I don't think so... so I gave it up. But if that's what we have to do, I can try it...

perhaps the best would be to cerate a separate file, 'g_justvu_gui', haha, then 'g_all_guis.c'  wouldn't be really ALL of them...

So, hidden/phantom/undocumented outlets is what we have for now...

**Comment by porres** [comment]
This just hit me, why not just hide the outlets as well when you give it a send symbol?

**Comment by umlaeute** [comment]
you mean a *receive* symbol, right?

**Comment by porres** [comment]
> you mean a receive symbol, right?

sure, see: https://github.com/pure-data/pure-data/pull/654

**Comment by umlaeute** [comment]
DoH.
somewhat accidentally (not being aware of the existing #1024) i've also fixed this in #1633 (outlets are hidden along with the inlets, if a "receive" name is specified)
