### ISSUE TITLE
nbx clips incoming values

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#633]
this is inconsistent behaviour to sliders, radios and atom boxes.

<img width="340" alt="Screen Shot 2019-05-12 at 03 55 19" src="https://user-images.githubusercontent.com/5360142/57578856-f5753c80-7469-11e9-9cf8-d0bc8aefa2b7.png">

An atom number box will only clip values if it has a min/max range and if you're clicking and dragging. If you type any other number into it or if it receives values outside that range, then it doesn't clip.

For consistency, I think [nbx] should behave the same way

This issue is a duplicate of https://sourceforge.net/p/pure-data/bugs/1224/ - created by Dan. 

Moreover, the behavior for many IEM GUIs changed in Pd 0.46, before that, all objects did clip. This has changed, but not for [nbx] - it seems it got accidentally left out.

I see no way out other than also changing this and creating a compatibility flag for this one too, for the sake of consistency.

**Comment by porres** [comment]
This issue is a duplicate of https://sourceforge.net/p/pure-data/bugs/1224/

**Comment by porres** [comment]
https://github.com/pure-data/pure-data/pull/631 fixes it

**Comment by porres** [comment]
The behavior for many IEM GUIs changed in Pd 0.46, before that, all objects did clip. This has changed, but not for [nbx]. 

I see no way out other than also changing this and creating a compatibility flag for this one too, for the sake of consistency.

**Comment by millerpuckette** [comment]
I haven't touched this since I want to just freeze nbx and later drop it from the menu (and just keep it around to keep old patches running).

**Comment by porres** [comment]
this has been fixed in master
