### ISSUE TITLE
Copy+Paste vs. Duplicate

### ISSUE THREAD

**Issue by mxa** [pure-data/pure-data#644]
There seems to be only one buffer for both actions, copy+paste and duplication.

Not sure how other applications handle this, I would have thought they are separate things, meaning i can copy A, then duplicate B, then paste A. In Pd the last step will paste B.

**Comment by Spacechild1** [comment]
in Pd, duplicate is really just a shortcut for copy+paste. you're right that other applications handle this differently (e.g. REAPER) but for Pd I don't know if it's worth the hassle to add dedicated undo/redo actions for duplication...

**Comment by mxa** [comment]
I do think these usability things are important, but maybe that's something to throw out with tcl/tk alltogether.

**Comment by Spacechild1** [comment]
it has nothing to do with tcl/tk, though

**Comment by umlaeute** [comment]
esp. all the copy/paste & duplicate logic is implemented in the Pd-core.
(that is: tcl/tk doesn't even know about any such thing)

**Comment by mxa** [comment]
Then this issue shall persist until it solved.
