### ISSUE TITLE
proposal for a new hybrid iemgui: [sradio]

### ISSUE THREAD

**Issue by fdch** [pure-data/pure-data#652]
I have been working on this GUI external that is pretty messy and has a lot of copied code inside that could be better and more efficiently loaded. But I thought I share it here and see if anyone might be interested in something like this. It works pretty well and afaict it is pretty robust.
![sradio-help](https://user-images.githubusercontent.com/13335792/59152467-bc1df580-8a44-11e9-98a3-1a87d383be5d.jpg)
 

It is a combined hack of `[hradio]` and `[text]`, and it acts as a sequence of toggles that can be set by clicks or by set message passing a list. With <key>shift</key> + click you open its text file for further edits, and it has a store/recall methods for quickly switching between patterns. Next/prev messages advance the sequence by one step, and the output is the stored value (0 or 1, as in a toggle)

It is a lot of code to move around, so I thought I should ask first if this is something that would be of interest for anyone other than me. It is a nice tool to make patterns on the fly and to read them in sequence.

The code for now is here https://github.com/fdch/fd_lib/tree/master/sradio

Cheers!

**Comment by Spacechild1** [comment]
Hi, I think it would be more interesting to actually have a 2D grid of cells (so your [sradio] would be just a special case of a grid with a single row) + methods to set/get individual cells as well as whole rows and columns. At least this is what I would want to do immediately.

**Comment by fdch** [comment]
I agree. In fact, that is exactly what it is, only that you can only see/access one row at a time. I have been using it as you say, just stacking different same-length [sradio] to have that matrix-like GUI and synch all of them with the same metro, for instance

**Comment by porres** [comment]
I have thees abstractions as a way to deal with 2D toggle arrays 

https://github.com/porres/pd-else/blob/master/Classes/Abstractions/drum.seq.pd
https://github.com/porres/pd-else/blob/master/Classes/Abstractions/mtx.ctl.pd

**Comment by jmmmp** [comment]
You can also check [jmmmp/matrixctrl] and use them with only 1 row. Not exactly the purpose of that object, but can work.

**Comment by fdch** [comment]
The object in question [is included on my fd_lib library](https://github.com/fdch/fd_lib/blob/main/src/sradio.c), so I'll close this.

**Comment by porres** [comment]
> The object in question [is included on my fd_lib library](https://github.com/fdch/fd_lib/blob/main/src/sradio.c), so I'll close this.

it crashes Pd for me....

**Comment by sebshader** [comment]
seems like this should be mentioned as a version too: https://github.com/nicklan/tglgrid

**Comment by fdch** [comment]
@porres thanks for pointing that out! It’s an old object and I need to update it. 

@sebshader nice reference! I did not know that it existed!

**Comment by porres** [comment]
that one also looks like [else/mtx.ctl]

**Comment by porres** [comment]
not sure why this was closed, isn't there a wish anymore to have 2d radio buttons? Radio is already unified for vertical/horizontal, theoretically we could add a new dimension but I know how hard it is to deal with iemguis code...

Anyway, I will soon work on a compiled object that is just like this a 2D radio, for ELSE

**Comment by fdch** [comment]
I'll reopen it, since I want to refactor my lib and include this object.
