### ISSUE TITLE
feature request: if function with only "then" in expr

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#662]
the if function in expr needs two arguments, one for "then" and other for "else"

I was hoping for the option of just having the "then" function with only one argument. In this case, the "else" expression would be inexistent and ignored, that is it won't have any output.

**Comment by porres** [comment]
maybe a new "ifthen" function?

something:

[expr ifthen($f1 > 0, 1)]

would then only output a "1" if the input is > 0

**Comment by umlaeute** [comment]
if it doesn't generate any output, then it's no longer an *expression*.
quoting [wikipedia](https://en.wikipedia.org/wiki/Expression_(computer_science)):

> An **expression** in a programming language is a combination of one or more constants, variables, operators, and functions that the programming language interprets [...] and computes to produce ("to return", in a stateful environment) another value.

**Comment by danfuzz** [comment]
I'd like to petition for this issue to be reopened. I understand that there is a "mathematical purity" to guaranteeing that all `expr` outlets emit values. However, as a practical matter, it would be very useful to have this functionality, thereby being able to avoid a bunch of boilerplate off of an `expr` output (e.g. having _two_ outputs, one a boolean, and using that to perform a `select`).

**Comment by porres** [comment]
there's a new issue now: https://github.com/pure-data/pure-data/issues/663

**Comment by danfuzz** [comment]
Thanks. I saw #663, but I think doing this original issue would be better: What I find myself wanting is, for example, things like a three-output `expr` where just _one_ of them is possibly not output per incoming execution.
