### ISSUE TITLE
feature request: set font size for data structures

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#668]
that's basically it, it could be set with an extra argument and message

**Comment by jmmmp** [comment]
also with a "scale with canvas" option, so that it scales equally as other scalars do when canvas xy units per pixel are changed.
Or, make "scale with canvas" the default behavior, and the user can set the font size accordingly. This makes usually more sense than making scaling optional, as text should integrate with the scalars.

**Comment by porres** [comment]
> also with a "scale with canvas" option, so that it scales equally as other scalars do when canvas xy units per pixel are changed.
> Or, make "scale with canvas" the default behavior, and the user can set the font size accordingly. This makes usually more sense than making scaling optional, as text should integrate with the scalars.

seems like a separate issue/request, can you do that please?

**Comment by porres** [comment]
my suggestion is that this is set via an extra float argument, which can come in place of the option label symbol argument.

**Comment by jmmmp** [comment]
if "in place" of the label, does it mean that the label is the next defined argument? labels are useful, it would be a pity to loose them.

**Comment by porres** [comment]
> if "in place" of the label, does it mean that the label is the next defined argument? 

no, labels are symbol arguments, this is a float argument that can come instead of the label argument (which is optional) or after it

**Comment by porres** [comment]
closing in favor of https://github.com/pure-data/pure-data/issues/2171
