### ISSUE TITLE
Pd crashes on load (MacOS) when loading a patcher with a window in negative space

### ISSUE THREAD

**Issue by tremblap** [pure-data/pure-data#670]
how to reproduce:
1) arrange you screens so the window in which you save generates a negative coordinate. The file attached has such feature.

2) try to reopen the file. It crashes the app.

[test.pd.txt](https://github.com/pure-data/pure-data/files/3351711/test.pd.txt)

**Comment by umlaeute** [comment]
on Debian with a Desktop that does not extend to negative coordinates, loading your patch doesn't crash (and instead wraps the the window into the visible area).

does the problem also exist with negative `x`-coordinates?

**Comment by Spacechild1** [comment]
Doesn't crash on Windows 7, the patch window is simply off-screen. Which system are you on?

**Comment by umlaeute** [comment]
title says "MacOS"

**Comment by mariobuoninfante** [comment]
I've experienced this issue several times (MacOS Sierra 10.12.6) and the workaround I found is to launch Pd from the terminal (Pd version installed from source), then launch the patch that now doesn't crash anymore, and save it again.
Coordinates are fine then

**Comment by mariobuoninfante** [comment]
just tried and works with the patch attached above as well.
Basically Pd compiled from source code seems to make the negative coordinate of the patch positive

**Comment by umlaeute** [comment]
@mariobuoninfante what happens if you launch the pre-compiled version of Pd from the terminal.

@tremblap could you try to run Pd from the cmdline to see whether you get some additional information? (probably *also* in conjunction with *-stderr*)

**Comment by tremblap** [comment]
@umlaeute I don't know how to do that, do you have a quick pointer to a simple how-to? I do not compile Pd I use the binaries from MP's website.  Reading [this](https://puredata.info/docs/faq/how-do-i-run-pd-from-the-command-line) implied I download Wish/TCL-TK...

Also, it is interesting to say that sometimes a window in the top window (negative y space) will jump down whilst I'm actually editing it (or saving, or moving an array drawn on canvass)

**Comment by umlaeute** [comment]
well. the quote from the FAQ you gave 

> you have to have the Tcl/Tk's Wish.app installed on your computer somewhere findable

does not really imply that you have to download anything.

just proceed without worrying about the findability of the `Wish.app`, everything should work out automagically (if not, then Pd will complain; and *then* we can start looking into it)

**Comment by tremblap** [comment]
Now, that is proper troubleshooting feedback ;-)
running
`/Applications/Pd-0.49-1.app/Contents/MacOS/Pd -stderr
`
I get this feedback on crash:

> 2019-07-03 11:12:38.287 Pd[52698:9661486] *** Assertion failure in -[_NSCGSWindow setFrame:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1504.83.101/CGS.subproj/NSCGSWindow.m:663
> 2019-07-03 11:12:38.288 Pd[52698:9661486] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: CGRectContainsRect(CGRectMake((CGFloat)INT_MIN, (CGFloat)INT_MIN, (CGFloat)INT_MAX - (CGFloat)INT_MIN, (CGFloat)INT_MAX - (CGFloat)INT_MIN), frame)'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x00007fffcc54265b __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x00007fffe138148d objc_exception_throw + 48
> 	2   CoreFoundation                      0x00007fffcc5473d2 +[NSException raise:format:arguments:] + 98
> 	3   Foundation                          0x00007fffcdf8fa00 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
> 	4   AppKit                              0x00007fffca0d3485 -[_NSCGSWindow setFrame:] + 252
> 	5   AppKit                              0x00007fffca19b4f4 _NSCreateWindowWithOpaqueShape2 + 162
> 	6   AppKit                              0x00007fffca19a135 -[NSWindow _commonAwake] + 1150
> 	7   AppKit                              0x00007fffca84eb96 -[NSWindow _resolveAutomaticEnterFullScreenFlags] + 51
> 	8   AppKit                              0x00007fffca199b5b -[NSWindow makeKeyAndOrderFront:] + 31
> 	9   Tk                                  0x00000001000c8bc6 XMapWindow + 197
> 	10  Tk                                  0x0000000100035437 Tk_MapWindow + 89
> 	11  Tk                                  0x000000010003e345 TkToplevelWindowForCommand + 2673
> 	12  Tcl                                 0x00000001001e4ef9 TclServiceIdle + 76
> 	13  Tcl                                 0x00000001001c8eaf Tcl_DoOneEvent + 329
> 	14  Tk                                  0x000000010001ba84 Tk_MainLoop + 24
> 	15  Tk                                  0x0000000100028861 Tk_MainEx + 1797
> 	16  Pd                                  0x000000010000447c Pd + 17532
> 	17  Pd                                  0x00000001000043d8 Pd + 17368
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
> gui socket 6 -
> closing audio...
> closing MIDI...
> ... done.
> Abort trap: 6

**Comment by Spacechild1** [comment]
So this is a Tk bug (it should validate parameters passed to Cocoa or handle exceptions). Which Tcl/Tk version are we using on MacOS? (On Windows we still ship 8.5). Maybe this has already been fixed in a newer version, otherwise we should file a bug report. Anyway, we probably have to workaround this on the Pd side.

**Comment by mariobuoninfante** [comment]
@umlaeute I've got what I think is the same issue @tremblap reported. Just in case I'm attaching mine as well:

2019-07-03 15:56:01.744 Pd[2715:114680] *** Assertion failure in -[_NSCGSWindow setFrame:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1504.83.101/CGS.subproj/NSCGSWindow.m:663
2019-07-03 15:56:01.746 Pd[2715:114680] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: CGRectContainsRect(CGRectMake((CGFloat)INT_MIN, (CGFloat)INT_MIN, (CGFloat)INT_MAX - (CGFloat)INT_MIN, (CGFloat)INT_MAX - (CGFloat)INT_MIN), frame)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffa3d822cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffb8bc048d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffa3d87042 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fffa57cfbe0 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   AppKit                              0x00007fffa1916485 -[_NSCGSWindow setFrame:] + 252
	5   AppKit                              0x00007fffa19de4f4 _NSCreateWindowWithOpaqueShape2 + 162
	6   AppKit                              0x00007fffa19dd135 -[NSWindow _commonAwake] + 1150
	7   AppKit                              0x00007fffa2091b96 -[NSWindow _resolveAutomaticEnterFullScreenFlags] + 51
	8   AppKit                              0x00007fffa19dcb5b -[NSWindow makeKeyAndOrderFront:] + 31
	9   Tk                                  0x00000001000c8bc6 XMapWindow + 197
	10  Tk                                  0x0000000100035437 Tk_MapWindow + 89
	11  Tk                                  0x000000010003e345 TkToplevelWindowForCommand + 2673
	12  Tcl                                 0x00000001001e4ef9 TclServiceIdle + 76
	13  Tcl                                 0x00000001001c8eaf Tcl_DoOneEvent + 329
	14  Tk                                  0x000000010001ba84 Tk_MainLoop + 24
	15  Tk                                  0x0000000100028861 Tk_MainEx + 1797
	16  Pd                                  0x000000010000447c Pd + 17532
	17  Pd                                  0x00000001000043d8 Pd + 17368
	18  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
gui socket 9 - 
closing audio...
closing MIDI...
... done.
Abort trap: 6

**Comment by umlaeute** [comment]
assigning @danomatika , our OSX guru.

**Comment by danomatika** [comment]
Ug. I thought this was fixed with the last version. Tk is becoming a pain as the Cocoa implementation has *so many* more bugs than the pretty-solid Carbon implementation before it, aka Tk 8.4.

**Comment by danomatika** [comment]
Here's what I can say:

* newer versions of Tk also crash, I tested 8.6.7 and 8.6.9
* this probably requires a manual fix via patching the TK 8.5.19 source code again (ugg)
* I can make a manual fix, but I cannot test it as Tk 8.5.19 has issues when it's compiled on a 10.14 system
* if the fix does work, Miller needs to (re)build Tk 8.5.19 and we need to update the included copy of Wish so people can build with the update

**Comment by danomatika** [comment]
The quickest triage is to return to clipping negative ranges on macOS, ala reverting parts of https://github.com/pure-data/pure-data/pull/225. The result of this, of course, will be the same people wondering why their multi monitor setups don't work with Pd when the reopen a patch. :P

**Comment by danomatika** [comment]
>assigning @danomatika , our OSX guru

I would like the monetary to expand, it's lonely.

**Comment by danomatika** [comment]
I have an older laptop at work with macOS 10.11 on it which I could use to try to find a fix and make another patch, but it will have to wait for a while as we are in heavy production at work for the next 2 weeks.

If someone wants to get their hands dirty, I can give you steps of how to approach doing this on your own.

**Comment by enlillebror** [comment]
I started running into this problem on version 0.48-1, had that same error message and I am also running dual monitors. Have a few patches that at some point would make pd crash when opening.
I just downloaded pd 0.51-1 and now I can open those patches again without a problem (so far).
So it's solved?

**Comment by porres** [comment]
0.51-3 is already out, you may have missed because you tried puredata.info which is usually a bit outdated

**Comment by umlaeute** [comment]
@porres since the problem has already been fixed with an older release of Pd (<=0.51-1), i don't see how the rant about the outdatedness of puredata.info is relevant (esp. since a version that fixes the issue *is* available)

**Comment by porres** [comment]
Sorry, it wasn't intended as a rant, it was more an intend to inform of a new version that is out and that we can test. I don't know if it's solved, if the latest version have fixed it, this is still open and we're still questioning about it.

**Comment by umlaeute** [comment]
well @enlillebror said that upgrading to Pd-0.51-1 fixed the problem for them.
whether it also fixes the problem for @tremblap , probably needs confirmation (that's why this is still open; we could of course just assume it does, and close...)

**Comment by danomatika** [comment]
It was most likely fixed by moving to Tk 8.6.10 on macOS with it's improved Cocoa support.

@tremblap If you can confirm this is fixed in Pd 0.51-3, please close the issue.

**Comment by tremblap** [comment]
this is fixes on my machine for sure thanks
