### ISSUE TITLE
expr helpfile typo

### ISSUE THREAD

**Issue by tremblap** [pure-data/pure-data#680]
a very small error here in the helpfile:
in [pd all_function] [pd Trigono] the bottom line should be

[expr tan($f1)] [expr atan($f1)]  [expr tanh($f1)] 

at the moment it is

[expr tan($f1)] [expr tan($f1)]  [expr atanh($f1)] 

p

**Comment by porres** [comment]
thanks for catching that, that was my bad, as I wrote that one. Just fixed it along other documentation updates of mine in: https://github.com/porres/pure-data/commit/23d24d759baf458922417265951d1b322f107e44
