### ISSUE TITLE
[trigger anything] and bang/pointer input

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#681]
A bang input will not quite come out as a bang in [trigger anything]

trigger_bang calls trigger_list in https://github.com/pure-data/pure-data/blob/master/src/x_connective.c#L1051

so the  output is coded here: https://github.com/pure-data/pure-data/blob/master/src/x_connective.c#L1033

what we have as an output is then a "list" message without any elements, what becomes a bang in Pd, but that doesn't work 100%

I have an external that has both a bang and a list method, and this output triggers is treated as a "list" input instead of a "bang" input.

**Comment by porres** [comment]
In practice, there's no difference of a bang input into [trigger list] and [trigger anything].

I guess it is "ok"  to have an empty list come out from [trigger list] with a bang input though...

**Comment by porres** [comment]
I realize now that another a request I had already fixes this issue. Much of the code comes actually from purr data, so I guess they were aware of this issue and fixed it over there.

The Pull Requests also offers constant floats and allows anythings to be converted to other types as well. Regarding the issue reported here, it seems this is taken care in this line https://github.com/pure-data/pure-data/blob/ba93a6447038216b8092a705d0145e28c66237f2/src/x_connective.c#L1039

**Comment by porres** [comment]
Note that the PR https://github.com/pure-data/pure-data/pull/682

still outputs an empty list come out from [trigger list] with a bang input... which is "ok" as I said

**Comment by Spacechild1** [comment]
I think I ran into this very issue with [mrpeach/midifile] which defines both a bang and a list method. 

While I agree that `[t a]` should pass messages unchanged, I would also suggest that you check for empty lists in your external (+ call your bang method) because there are other objects around which output empty lists as bangs. Unfortunately, Pd's semantics are a bit ambiguous here, so it's probably good to take care of it on both sides.

**Comment by porres** [comment]
trying to make things more obejctive, so I rebooted this issue into https://github.com/pure-data/pure-data/issues/683
