### ISSUE TITLE
[trigger anything] and bang/pointer input 

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#683]
I think that [trigger anything] should output whatever originally comes in. But this doesn't happen for 'bang' and 'pointer'.

A bang becomes a "list" message without any elements, what becomes a bang in Pd, but that doesn't work 100% - for instance, I have an external that has both a bang and a list method, and this output triggers is treated as a "list" input instead of a "bang" input.

In a similar way, a pointer input comes out with a list selector.

**Comment by umlaeute** [comment]
btw, this is a duplicate of https://sourceforge.net/p/pure-data/patches/506/
