### ISSUE TITLE
add "constant float" to trigger

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#691]
A float as an argument would become a constant value always output by the [trigger] object.

This is used in max and purr data, and there have been requests for this functionality (such as on the Pd facebook group).

<img width="184" alt="screen shot 2018-05-03 at 11 25 35" src="https://user-images.githubusercontent.com/5360142/39582624-ba635382-4ec4-11e8-8def-f72b57b57951.png">

As having number arguments is not something documented or what people should be doing in vanilla, I don't think this breaks anything.

**Comment by porres** [comment]
changed my mind, don't want this no more... (will work on my PRs for this and remove them too).

**Comment by 60-hz** [comment]
May we know why you changed your mind on this? I think saving time building many messages boxes with a mouse to carry a simple float is still a great feature.

**Comment by porres** [comment]
- it doesn't make sense to initialize just a float message (and not a symbol or even a list). 
- It doesn't seem like the job for this object and its true idea "convert message types".
- I have a [trigger2] external in ELSE that initializes floats and symbols and never really use it (and I'm removing it from my library).

**Comment by porres** [comment]
another one
- I was worried with incompatibilties betwen purr data and vanilla and hoped to include this feature they have, but trying to mitigate the incompatibilities between them is just impossible and I don't like battling wars I can't win.

**Comment by porres** [comment]
> I have a [trigger2] external in ELSE that initializes floats and symbols and never really use it (and I'm removing it from my library).

I really think that something like this is the best solution, creating an external with expanded functionality. This would have been a much better alternative to Purr Data instead of introducing yet another incompatibility.

**Comment by 60-hz** [comment]
> it doesn't make sense to initialize just a float message (and not a symbol or even a list).
Doesn't pack is making it? 

> It doesn't seem like the job for this object and its true idea "convert message types".
Yes, but I see "- sequence messages in right-to-left order" as the first description in help files, so It can still makes sens.

> I have a [trigger2] external in ELSE that initializes floats and symbols and never really use it (and I'm removing it from my library).
I can understand, and that's a user habit. In my old Max era, I was using this trigger features so often, It was handy and even helps me understanding the necessity to put trigger everywhere, which is a good practise regarding dataflow programming. Today I must admit I sometimes avoid a trigger box only because it's a bit boring to patch so many messages boxes ;)

I even think having the same functionnality for [unpack] would be a great benefit, as it would following the [pack] and [trigger] logic.

**Comment by porres** [comment]
> Doesn't pack is making it?

[pack] initializes floats, but that's another object with a complete different functionality.

> Yes, but I see "- sequence messages in right-to-left order" as the first description in help files, so It can still makes sens.

or we can improve the description.

and yeah, I'm aware purr data follows the max idea, but...

**Comment by umlaeute** [comment]
> > Yes, but I see "- sequence messages in right-to-left order" as the first description in help files, so It can still makes sens.
> 
> or we can improve the description.

ah no, why do you think that would be an improvement?

the core functionality of `[trigger]` is to *trigger* events (hence the name), rather than "convert message types" (i'd use  `[convert]` for that)

**Comment by porres** [comment]
> ah no, why do you think that would be an improvement?

I was considering it already included the 'conversion' description, as it already does in fact, but I also dunno what I would do differently...

**Comment by umlaeute** [comment]
ah.
i thought you meant to "improve the description" by stating that 
>  its true idea [is to] "convert message types".
