### ISSUE TITLE
request, change default font size to 12 (instead of 10)

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#703]
This seems like a best configuration for most users, as a font size of 10 is kinda tiny... 

The font size of the Pd documentation and audio examples are, by the way, in font 12, and I just configured Pd once to a font size 12 and forgot it ships with a font size of 10 preconfigured.

By the way, Purr Data chose a size of 12 instead, for the same reasoning I guess.

**Comment by porres** [comment]
for reference, it seems all it takes is to change "10" to "12" in https://github.com/pure-data/pure-data/blob/086ede6a34b4e01f88dc69ab59a39e21a7dac717/src/s_main.c#L202

**Comment by porres** [comment]
miller did it by hand with https://github.com/pure-data/pure-data/commit/9b76f4f64372fdd006fe3df7a76cb0650d511fbc

**Comment by danomatika** [comment]
It might be good to make this a settable startup flag. I'm fine with size 10 font and I'd like to be able to change this back without having to manually do it for *each* and *every* patch I open.

**Comment by porres** [comment]
> EDIT: Dohh. It already exists: --font-size. Time for bed...

yup :) seems to work just as "-font" as well!
