### ISSUE TITLE
html manual issues

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#705]
opening an issue to discuss issues regarding the html section.

here's one, this is a dead link: 

https://github.com/pure-data/pure-data/blob/master/doc/1.manual/x1.htm#L100

**Comment by porres** [comment]
on x3 it says "Pd should work under any version of Windows since 95." - Ok, should we change this to "XP"?

**Comment by porres** [comment]
It seems the whole how to install thing should/could be rewritten, but I'm not the one to do that

**Comment by porres** [comment]
in 3.6, we can append a link to the section for, something like below in bold

The slots at top each specify a binary "library" for Pd to load on startup. These may be for Gem, pdp, zexy, iemlib, cyclone, and so on. Typically, a single binary object (an "extern") is left for Pd to load automatically; startup library loading is appropriate for collections of many objects specified by a single binary library **- See 4. Externals for more on externals and how to load them**

**Comment by porres** [comment]
Some of the **Command line arguments** in 3.6 seem to be missing, maybe revise that too!

**Comment by porres** [comment]
in 3.7 where it says "You can see and edit the path while Pd is running using the "path..." item in the "File" menu:" 

we should update to

"You can see and edit the path while Pd is running using the "path..." item in the "**Preferences**" menu:"

**Comment by porres** [comment]
still in 3.7...

_If "use standard extensions" is enabled, the usual "extras" directory is also searched. This contains standard external objects like "expr" and "fiddle", and perhaps much more depending on the distribution of Pd you're using._

**expr** is not part of extras anymore - and I need to make sure if only "extra" (and not "extra**S**") or the other standard paths too

**Comment by porres** [comment]
and more...

_Regardless of path, Pd should look first in the directory containing the patch before searching down the path. **Pd does not automatically look in the current directory however; to enable that, include "." in the path**._

so, this doesn't seem to be true anymore...

**Comment by porres** [comment]
It also says "_The "extra" directory, if enabled, is searched last._" - I'm discussing this should be changed in https://github.com/pure-data/pure-data/issues/289

**Comment by porres** [comment]
_A filename specified in a patch with any "/" characters in it (such as "../sounds/sample1.wav") causes Pd to to look both in the path and relative to the directory containing the patch. You may also invoke externs that way._ - here, at the end, we can say that more on how to load externals is discussed in the next section!

**Comment by Lucarda** [comment]
@porres see #720 or [here](http://lucarda.com.ar/html-preview-2/index.htm)

not yet included:

- > expr is not part of extras anymore ...

- > It also says "The "extra" directory, if enabled ...

**Comment by porres** [comment]
I ended up removing "writing Pd objects in C" and included that text  in the beggining of the section - this was basically only a paragraph and a pointer to IOhannes' tutorial. I also added pd-lib-builder as a resource for building externals.

**Comment by porres** [comment]
@Lucarda, have all of these issues been fixed and merged already?

**Comment by Lucarda** [comment]
@porres Yep, except those two above.

**Comment by umlaeute** [comment]
> Yep, except those two above.

well, 

> It also says "The "extra" directory, if enabled ...

this documents existing behaviour, so it is correct. and afaict the consensus reached in #289 was that this should stay as it is.



> `expr` is not part of extras anymore ...

this is still the case.
it also lists both "fiddle" among those standard externals, which has been superseded by `[sigmund~]`, so i wonder whether we should just change the list to (e.g.) sigmund~ and pd~. otoh, i think fiddle~ has been one of the most popular Pd-objects, so probably we should leave it in just to help people with searching... also i'm not sure about the availability of pd~ on all platforms (as it's much more brittle than the other objects that don't encode any system specifics.

probably something like:

> This contains standard external objects like "sigmund~" (as well as it's predecessor "fiddle~") and "bonk~", and perhaps much more depending on the distribution of Pd you're using.

**Comment by Lucarda** [comment]
>probably something like:
>>This contains standard external objects like "sigmund~" (as well as it's predecessor "fiddle~") and "bonk~", and perhaps much more depending on the distribution of Pd you're using.

Ok, #1460 includes this and a few other corrections.

**Comment by porres** [comment]
why are we using "extras" directory, and not just "extra"?

**Comment by porres** [comment]
here's something else we can fix

"You can't mix messages and audio in a subpatch inlet or outlet; they must be one or the other exclusively. Inlets and outlets appear on the invoking box in the same left-to-right order as they appear in the subpatch."

well, now we can with the 'fwd' argument to inlet~ :)

**Comment by umlaeute** [comment]
> why are we using "extras" directory, and not just "extra"?

i think it's a typo.

**Comment by porres** [comment]
@Lucarda ,  I made a couple of PRs to fix things in your branch, see if they're there and take them please...

**Comment by Lucarda** [comment]
@porres fantatstic!

I'll like to know how you did that. Is it all magic from the web-interface when you create the PR?

**Comment by porres** [comment]
what magic? I just edited the file directly in your repo, yeah...

note that I'm also making changes to the manual, just revised section 4 in my documentation branch! Please don't touch it? :) 

we can ask @millerpuckette to take both PRs ( https://github.com/pure-data/pure-data/pull/1460 & https://github.com/pure-data/pure-data/pull/1455 ) ASAP? I'm done with my new batch of documentation updates.

**Comment by Lucarda** [comment]
> I just edited the file directly in your repo, yeah...

?
I just use git from command line. How do I open your `Documetation` branch and make a PR to it? (I'm not going to do it for real)

> just revised section 4 in my documentation branch! Please don't touch it?

Ok

**Comment by porres** [comment]
come here, go to any file and then click to edit it on site ;)

**Comment by porres** [comment]
come here => https://github.com/porres/pure-data/tree/Documentation
go to any file and then click to edit it on site ;)

**Comment by Lucarda** [comment]
?

![gitedit](https://user-images.githubusercontent.com/25239522/142588330-6db65b02-60a3-411f-bbea-635e65e7dee2.png)

?

**Comment by Lucarda** [comment]
Aha.

Fantastic!!!

:)

**Comment by porres** [comment]
Well, Miller merged doc updates, I believe I can close this now
