### ISSUE TITLE
pdcontrol: no method for 'gui' - Pd 0.50.0test1 OSX 10.14.6

### ISSUE THREAD

**Issue by megrimm** [pure-data/pure-data#726]
With new pdcontrol object example patch clicking the message give me in console:

`pdcontrol: no method for 'gui' `

seemed to work fine when i compiled it myself last a couple weeks ago. This is from the miller Pd 0.50.0test1 version. Im on OSX 10.14.6

**Comment by Lucarda** [comment]
The "gui" method was removed. See https://github.com/pure-data/pure-data/commit/6d28e3fcd805ffb11cb8047f6a6fe26de433ba77

**Comment by megrimm** [comment]
so this is an example patch issue... sounds good

**Comment by porres** [comment]
> so this is an example patch issue

which already got fixed :)

**Comment by porres** [comment]
see: https://github.com/pure-data/pure-data/commit/3dd17e1eca70d066d76952fde8173e14c0fdf3b9

**Comment by porres** [comment]
so, you can close the issue ;)
