### ISSUE TITLE
Change in sys_microsleep() causes deadlock in multi-threaded libpd app

### ISSUE THREAD

**Issue by cuinjune** [pure-data/pure-data#727]
I tried updating pd's source files for my libpd app from `0.49-0` to `0.50-0test1` today.

However, my app freezes when I use `0.50-0` pd sources files.

Since my app is multi-threaded, I use `sys_lock()` and `sys_unlock()` whenever the main thread tries to access variables from pd's thread and it used to work perfectly fine in `0.49-0` but the app freezes on startup when I use `0.50-0`.

After some testing, I found out [the recent change](https://github.com/pure-data/pure-data/commit/7f6ad7ab971d74567c9214448d41525cf5183746#diff-5e902c4a160abd3bba173ef87048c43dR253) in `s_inter.c` file's `sys_microsleep()` function is causing this issue.

```
void sys_microsleep(int microsec)
{
    sys_lock(); // <-- this was recently added.
    sys_domicrosleep(microsec, 1);
    sys_unlock();  // <-- this too.
}
```

When I remove `sys_lock()` and `sys_unlock()` from the function, my app works fine without the deadlock.

I would appreciate if `sys_microsleep()` function can be reviewed so the deadlock won't happen in a multi-threaded libpd app. Thank you!

**Comment by Spacechild1** [comment]
what are you doing exactly? can you show your code?

**Comment by Spacechild1** [comment]
Another question: what do you expect sys_microsleep to do? Honest question!

**Comment by Spacechild1** [comment]
But anyway, `sys_microsleep` can currently only deadlock if you call it while holding a lock on Pd. The correct thing is to release the lock before calling `sys_microsleep` because why would you want to lock Pd while sleeping?

**Comment by danomatika** [comment]
Most libpd wrappers do lock between DSP processing and message sending.

**Comment by Spacechild1** [comment]
> Most libpd wrappers do lock between DSP processing and message sending.

Yes, Pd does as well. The point is that you have to unlock Pd before calling `sys_microsleep` on the same thread. Although I would really prefer if `sys_microsleep` what just do what it name suggests (without side effects), the current behavior makes kind of sense, because you don't want lock Pd while  sleeping (otherwise nobody else ever has a chance to acquire a lock). But I really need to see some actual code of libpd users. I'm only familiar with the Pd scheduler, not other people's schedulers.

**Comment by danomatika** [comment]
>But I really need to see some actual code of libpd users.

https://github.com/libpd/libpd/blob/master/libpd_wrapper/z_libpd.c#L185

**Comment by Spacechild1** [comment]
Ah, all good. `sys_microsleep(0)` won't deadlock because it doesn't try to lock Pd.

**Comment by danomatika** [comment]
Could the issue be that sys_lock() is being called with the pd instance set, ie. per your commenting...

**Comment by Spacechild1** [comment]
Ahhhhhh... no, I looked at the wrong method (`sys_domicrosleep`). You indeed must *not* call `sys_microsleep` while have a lock on Pd.

**Comment by danomatika** [comment]
Sure, but a good point here is: might this change be breaking externals?

**Comment by Spacechild1** [comment]
externals should never call `sys_microsleep` :-)

**Comment by danomatika** [comment]
If it's not part of the "public API" then good. We can change libpd in that case.

**Comment by Spacechild1** [comment]
`sys_microsleep` is a mess because it has completely different behavior whether its argument is 0 or non-zero...

here's the thing: if you want to poll sockets, you should really call `sys_pollgui`

**Comment by Spacechild1** [comment]
sys_microsleep(0) polling sockets is an ugly implementation detail, which IMO should be removed. In my PR I've completely seperated polling from sleeping, so that sys_microsleep only sleeps and a new function `sys_pollsockets()` behaves like `sys_microsleep(0)`

**Comment by danomatika** [comment]
If the PR is accepted (or not), let us know what to change in libpd.

**Comment by Spacechild1** [comment]
I will! I think Miller is interested in doing this after Pd 0.50.

**Comment by danomatika** [comment]
>after Pd 0.50.

Is there a fix for now? Otherwise, I cannot update libpd with the newer vanilla features :P

**Comment by Spacechild1** [comment]
if you don't have a GUI, `sys_pollgui()` behaves very much like my `sys_pollsockets()`, so in the meantime you could at least replace `sys_microsleep(0)` with `sys_pollgui()`

**Comment by danomatika** [comment]
>so in the meantime you could replace sys_microsleep(0) with sys_pollgui()

Can you try this in libpd.c @cuinjune?

**Comment by cuinjune** [comment]
Yes,  replacing the `sys_microsleep(0)` with `sys_pollgui()` in [z_libpd.c's PROCESS macro](https://github.com/libpd/libpd/blob/master/libpd_wrapper/z_libpd.c#L185)
 fixed the problem. Thank you!

**Comment by danomatika** [comment]
Thanks for testing. I will implement this fix when I update libpd to the vanilla 0.50 after the release.

**Comment by danomatika** [comment]
I'm looking into this now.

@millerpuckette As I'm changing libpd to call `sys_pollgui` when processing audio, does this make `libpd_pollgui` redundant?

**Comment by Spacechild1** [comment]
I think `libpd_poll_gui` can stay, because you might want to call it if you're idle.

BTW, make sure to also replace `sys_microsleep()` with `sys_pollgui()` in `libpd_process_raw()`

**Comment by danomatika** [comment]
Ok. I'm just wondering if I should put a note about not needing to call it if you are already suing one of the process functions.

**Comment by Spacechild1** [comment]
Sounds good. Maybe also add a note that it's a good idea to call it repeatedly when you're idle, because you get more throughput for `[netreceive]` et al.

**Comment by danomatika** [comment]
Then we should probably also change this example: https://github.com/libpd/libpd/blob/master/samples/c/pdtest_gui/pdtest_gui.c#L87.

TO clarify: by "idle," do you mean "not calling a libpd process function?"

**Comment by Spacechild1** [comment]
> To clarify: by "idle," do you mean "not calling a libpd process function?"

Yes, or more generally: when you've done all the work you've needed to do and still have some time left. We do this in the Pd scheduler.

**Comment by danomatika** [comment]
@cuinjune I have made this change to the libpd master branch. Please test.
