### ISSUE TITLE
[vradio] and [hradio] store initial value even when set to No init.

### ISSUE THREAD

**Issue by cuinjune** [pure-data/pure-data#730]
[vradio] and [hradio] store initial value even when set to No init.

Here's how to test this issue:

1) create an empty patch.
2) create the following objects.
[loadbang]
|
[hradio]
|
[print]
3) select the last segment in [hradio]. It will print `7` on the Pd window.
4) Save and close the patch.
5) If you reopen the patch, you will see  the `7` printed in the Pd window although the GUI indicates the first segment is selected.

If you open the patch using the text editor, you can check that `7` is stored as the GUI parameter although it is set to `No init`.

```
#X obj 141 81 hradio 15 1 0 8 empty empty empty 0 -8 0 10 -262144 -1
-1 7;
```

I used `Pd-0.50-test1` on macOS.

**Comment by umlaeute** [comment]
confirmed (with Pd-0.49.0 on Debian/GNU)

**Comment by umlaeute** [comment]
i missed this bug report, and created a duplicate #1347 
this has been fixed in https://github.com/pure-data/pure-data/commit/e67a91aeb15125e7c811db8fdd3326539c79fd5c which was part of Pd-0.52-1
