### ISSUE TITLE
request, query for files in a folder.

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#731]
We now have a 'dir' method in the new [pdcontrol] object. the 'dir' message also allows searching for relative files. It'd be great if we could give it something like *.wav  and it outputs all .wav files in that directory! Or 'dir dump' and it dumps all files in that dir!

**Comment by umlaeute** [comment]
`dir dump` should probably read `*` (a wildcard matching everything).

also, what about sub-directories?

**Comment by porres** [comment]
> dir dump should probably read * (a wildcard matching everything).

yeah, perfect

> also, what about sub-directories?

it's already happening, you can give a sub-directory or any relative path, including a file or not as the 2nd argument in the 'dir' method

**Comment by umlaeute** [comment]
>> also, what about sub-directories?
> it's already happening, you can give a sub-directory or any relative path, including a file or not as the 2nd argument in the 'dir' method

i meant: if a directory contains both files and sub-directories, how
would the result enable me to distinguish between the two types?

you are only talking about "files", which could either mean to exclude
directories (as they are not files) or include directories (since under
unix everything is a file), or that you just didn't think specifically
about directories when you wrote the proposal (which is ok for a simple
proposal...)

**Comment by danomatika** [comment]
I would suggest a `dir list` naming instead.

**Comment by danomatika** [comment]
>also, what about sub-directories?

`dir list -r`

I agree that a simple glob would be cool as that's probably the biggest use case for this, getting a list of wav files, etc from a folder. It would also remove the need for lots of list processing.:

    dir list *.wav

Paths should work of course:

    dir list ../../samples

or

    dir list ~/Desktop/tables/*.txt

**Comment by porres** [comment]
> or that you just didn't think specifically about directories 

I didn't think :)

> or include directories (since under unix everything is a file)

in [else/dir] it just spits the subdirectory as a file, indeed

> I would suggest a dir list naming instead.

seems good to me ;)

**Comment by danomatika** [comment]
>i meant: if a directory contains both files and sub-directories, how
would the result enable me to distinguish between the two types?

It could behave like `find`:

    # this dir, files only, recursive
    dir list -f -r

    # directories on the desktop
    dir list -d

**Comment by umlaeute** [comment]
On 8/16/19 12:30 AM, Dan Wilcox wrote:
> I would suggest a `dir list` naming instead.
> 


as in `[dir list /path/to/directory *.wav(`?

the path could be optional (and defaults to the patch path; or
whatever). use [dir 2 ../foo( beforehand, to calculate the path if you
want full control about relative paths.

the globbing pattern could be optional (and default to `*`).
if you want to specify a globbing pattern, you must provide a path.

**Comment by umlaeute** [comment]
> dir list -f -r

urgh.
i'd prefer no flags, and instead:
- mark the type each item in the output message (so you can `[route]` files and directories).
- make the object re-entrant save (so the user can recurse into subdirectories on the patch level)

**Comment by danomatika** [comment]
Flags are easier to parse :)

**Comment by umlaeute** [comment]
i think this is obsoleted by the new `[file glob]` object.

so i'm closing this (if you think this is an error, please re-open or shout out loud)
