### ISSUE TITLE
[makefilename] help file - wrong description of %p pattern

### ISSUE THREAD

**Issue by mariobuoninfante** [pure-data/pure-data#737]
Ubuntu Studio 19.04 - Pd 0.50

[makefilename %p] returns '(nil)' when receives a 0.
It works fine on MacOS High Sierra 10.13.1

![pd_linux_makefilename_bug_%p](https://user-images.githubusercontent.com/20879405/64124138-1a394b00-cd9e-11e9-80c2-fa0652669e9f.png)

**Comment by Spacechild1** [comment]
"%p" is for C pointers and the actual format can vary across platforms. What are you trying to do?

**Comment by umlaeute** [comment]
what did you expect?

**Comment by mariobuoninfante** [comment]
maybe I'm missing something obvious, but I'd expect '0x0' to be printed. at least according to the [makefilename] help file
![makefilename_help](https://user-images.githubusercontent.com/20879405/64132628-0e16b300-cdc9-11e9-8552-a982b9f1fbfb.png)

**Comment by mariobuoninfante** [comment]
also because with numbers bigger than 0, that is what I get

![Uploading makefilename_issue.png…]()

**Comment by Spacechild1** [comment]
OK, this is a bug in the help file. `%p` is for printing memory addresses and there is no standardizes format. "unsigned hexadecimal with preceded by '0x'" is just one possible way. With MinGW, `[1( -> [makefilename %p]` gives me `00000001`

**Comment by Spacechild1** [comment]
0 is the NULL pointer, and your system decides to print it as (nil).

**Comment by mariobuoninfante** [comment]
understood. It does make sense, also because it was 'working' on MacOS, and I found it quite weird.
that said, I think it would be useful if we could have a way of printing hex preceded by '0x'.

**Comment by mariobuoninfante** [comment]
PS I know that all you need to to is to have 2 makefilename in cascade to obtain that
[makefilename %X]
|
|
[makefilename 0x%s]

but still since the object is meant to be use for formatting purposes, I think have that by default without need to use a 'workaround' would be great

**Comment by Spacechild1** [comment]
`[makefilename]` is modelled after `printf`, and there you would also have to do `printf("0x%x", mynumber);`

**Comment by Spacechild1** [comment]
there's no need to cascade, just do `[makefilename 0x%x]`

**Comment by mariobuoninfante** [comment]
@Spacechild1 of course it is, I don't really know what I was thinking when I wrote that :(
so focused on the %p thing.
Anyway thanks for looking into it. I suppose like you said the bug is just in the help file.

**Comment by Spacechild1** [comment]
no problem. can you change the description or open a new issue?

**Comment by porres** [comment]
I have a revision of the documentation here: https://github.com/pure-data/pure-data/pull/608/commits/831d93ed0e8eeac5c9a1301c9dc12b62dd6077b1

and discuss issues here: https://github.com/pure-data/pure-data/issues/549

so if you think there's something else to discuss about the documentation...

**Comment by mariobuoninfante** [comment]
@porres what should I do? you already referred this issue in #549 .
is it worth having this one open? should I write a brief summary in there?

**Comment by porres** [comment]
> Close this one and let's move the discussion there

so, can we do this? Can you participate in https://github.com/pure-data/pure-data/issues/549 ?

**Comment by porres** [comment]
and close this one?

**Comment by umlaeute** [comment]
i dont think there's much left to discuss here (everything has been said, that's to say about this specific issue. i think everybody agrees on what ought to be done).

i would keep this open until its fixed (and rather spend time on fixing things than on micromanaging tickets)

**Comment by porres** [comment]
> i dont think there's much left to discuss here

me too, that's why I think we can close this, and what we have here is being addressed on a broader issue on the documentation. 

> i would keep this open until its fixed

I'm fixing it, just wanted to make things sure before

**Comment by porres** [comment]
> I'm fixing it, just wanted to make things sure before

fixed with  1e2db76

**Comment by porres** [comment]
this can be closed!
