### ISSUE TITLE
How to use sys_startgui 

### ISSUE THREAD

**Issue by pierreguillot** [pure-data/pure-data#75]
I started to update my project [zpd](https://github.com/pierreguillot/zpd) (that is a kind of libpd) with the last version of Pd (before testing the new features in libpd). I don't really understand how [sys_startgui](https://github.com/pure-data/pure-data/blob/master/src/s_inter.c#L1377) should be used and what it does. In the Miller's branch of libpd, the [example](https://github.com/libpd/libpd/pull/171/files/ddd6ef004c00ca41f1834fcb5bf5f72f972bc20d..35e4272a2c3ba610836fa4cdff3bea99dac815fb#diff-44ec7e62314f045847d1166bd74411b5R77) use a relative path but I don't know what is the path to my application and what should be the target of the path. The solution I found for the moment is to copy the static function [sys_fakefromgui](https://github.com/pure-data/pure-data/blob/master/src/s_main.c#L271) but it's dirty. Anyone has a solution?

**Comment by danomatika** [comment]
It probably needs the path to the pd folder which contains the tcl scripts and . On Linux, it's usually /usr/local/lib/pd. Maybe that works? I agree we need to document this when we decide how to wrap this functionality with libpd.

**Comment by pierreguillot** [comment]
I don't understand why we would need to use a tcl script in libpd (I don't really like the idea) but I don't fully understand this part of the code, I should investigate a bit more :). Anyway, I'll try it. Thanks!

**Comment by danomatika** [comment]
We don't use a tcl script in libpd. libpd starts up the Pd gui if you have desktop Pd installed. The Pd gui is all tcl.

**Comment by pierreguillot** [comment]
and if I don't have Pd installed what path should I give to the function?

**Comment by danomatika** [comment]
If you don't have Pd installed, there is no GUI to start. I would ask Miller how this all works on the pd-dev list.

**Comment by pierreguillot** [comment]
The discussion has continued on the pd-dev list [here](https://lists.puredata.info/pipermail/pd-dev/2017-07/021128.html). And with 214377333afb55705b2e41e608e039effe0c1383, sys_fakefromgui() should not be necessary anymore so I close this issue for the moment.
