### ISSUE TITLE
multiple "save as" windows allowed

### ISSUE THREAD

**Issue by jmmmp** [pure-data/pure-data#751]
Try the following (tested on windows)
- open/create a patch window
- press save as
- use alt-tab to focus on any other program
- go back to the patch window
- press save as 
- now you have 2 open save as windows
- keep doing it, until you have as many "save as" windows as you might find necessary...

**Comment by umlaeute** [comment]
do you want to provide a PR to document this?

**Comment by jmmmp** [comment]
what is a PR?

Am So., 22. Sept. 2019 um 18:09 Uhr schrieb umläute <
notifications@github.com>:

**Comment by Spacechild1** [comment]
PR = pull request

> do you want to provide a PR to document this?

@umlaeute why document and not fix?

IMO, the open/save dialogs should simply be modal, like in any other application...

BTW, a similar problem occurs with `[openpanel] `and `[savepanel]`, but they probably should stay non-modal. Instead we can fix it in the core (don't create the dialog if the object already has one).

**Comment by umlaeute** [comment]
> why document and not fix?

because @jmmmp described a behaviour, which he (most likely) finds odd.

there's nothing inherently and/or obviously *wrong* with how the "Save As..." currently behaves. I don't know whether the OP meant this as a feature request, a bug report or as a documentation of the current behaviour.

as for @Spacechild1's proposed solution: i find modal dialogs rather cumbersome in multi-window applications like Pd: it's just too easy to hide the modal behind one of the many open windows, which leaves you with a non-responsive Pd (that you can't even quit). this is think is much more problematic than having 23 open "Save As..." windows for a single patch.

**Comment by Spacechild1** [comment]
> there's nothing inherently and/or obviously wrong with how the "Save As..." currently behaves.

@umlaeute  I'm pretty sure that being able to create more than 1 open/save dialog for the *same* document is a bug.

>  i find modal dialogs rather cumbersome in multi-window applications like Pd: it's just too easy to hide the modal behind one of the many open windows, which leaves you with a non-responsive Pd

First, a modal dialog should *always* be in front. The problem you're describing (dialogs hidden by other windows) really applies to the current implementation and modal dialogs would actually solve that! Also, the dialogs should probably be window-modal (and not application-modal), so it wouldn't block the user from interacting with the rest of app.

**Comment by umlaeute** [comment]
> > there's nothing inherently and/or obviously wrong with how the "Save As..." currently behaves.
> 
> @umlaeute I'm pretty sure that being able to create more than 1 open/save dialog for the _same_ document is a bug.

why? what is the problem you are experiencing?
(and no, I don't see any need to be able to open multiple "Save As..." dialogs; i just don't see the actual problem)


> First, a modal dialog should _always_ stay in front of the parent.

sure.
but what I described was not a theoretical problem but a real world problem: I know that I have had modal file-selector dialogs in Pd that were hidden behind windows. Or on a different desktop. (Probably a bug in the window manager. But I don't want to get there again...)

**Comment by Spacechild1** [comment]
> why? what is the problem you are experiencing?

It simply goes against the (unwritten) rules of desktop GUI development. Are you really saying this behavior is ok?

> I know that I have had modal file-selector dialogs in Pd that were hidden behind windows.

Well, that's a bug in the implementation then. As I've said, a modal dialog should stay on top of the parent. In some implementations, a *window*-modal dialog might be hidden behind other (non-parent) windows, but even that's not a problem because it doesn't block interaction with the rest of the app.

**Comment by Spacechild1** [comment]
Even if we keep the open/save dialogs non-modal, there should be at least a mechanism to prevent the creation of multiple dialogs for the same window.

**Comment by Spacechild1** [comment]
BTW, GIMP is a curious case: open/save dialogs are always on top of *all* other windows, but they are non-modal. And of course, you can't open multiple open/save dialogs for the same window ;-)

**Comment by Spacechild1** [comment]
If you're ok with it, I would go ahead and do the following:
* prevent multiple menu open/save dialogs for a given window
* prevent multiple dialogs for a given [openpanel]/[savenpanel]
* make all open/save dialogs always stay on top of the parent
* keep make menu open/save dialogs non-modal for now

**Comment by umlaeute** [comment]
> Are you really saying this behavior is ok?

i never said that it was ok. i was asking what the actual problem is.

> If you're ok with it, I would go ahead [...]

sure.

**Comment by Spacechild1** [comment]
> i never said that it was ok.

let me quote you:

> there's nothing inherently and/or obviously wrong with how the "Save As..." currently behaves.

I still don't understand why you wrote that...

**Comment by umlaeute** [comment]
i just did a quick test and `[openpanel]`, `[savepanel]` and the menu file dialogs are now modal, at least on Linux with Tcl/Tk-8.6

so: can we close this?

**Comment by Spacechild1** [comment]
> [openpanel], [savepanel] and the menu file dialogs are now modal

Not here on Windows (Pd 0.54.1), so I guess #764 would still be necessary.

**Comment by umlaeute** [comment]
thanks for confirming.
