### ISSUE TITLE
bob~, bonk~, choice, fiddle~, loop~, lrshift~, pdsched, pd~, pique, sigmund~, stdout lack PIE

### ISSUE THREAD

**Issue by dvzrv** [pure-data/pure-data#758]
Hi! I'm maintaining the pure-data package on Arch Linux (as pd).
During build of `0.50-1` (aka. `0.50-1`) and before, I run into the following extras, that all lack [PIE](https://en.wikipedia.org/wiki/Position-independent_code#PIE) (as reported by our [namcap](https://wiki.archlinux.org/index.php/Namcap) tool):

```
pd W: ELF file ('usr/lib/pd/extra/bob~/bob~.pd_linux') lacks PIE.
pd W: ELF file ('usr/lib/pd/extra/bonk~/bonk~.pd_linux') lacks PIE.
pd W: ELF file ('usr/lib/pd/extra/choice/choice.pd_linux') lacks PIE.
pd W: ELF file ('usr/lib/pd/extra/fiddle~/fiddle~.pd_linux') lacks PIE.
pd W: ELF file ('usr/lib/pd/extra/loop~/loop~.pd_linux') lacks PIE.
pd W: ELF file ('usr/lib/pd/extra/lrshift~/lrshift~.pd_linux') lacks PIE.
pd W: ELF file ('usr/lib/pd/extra/pd~/pdsched.pd_linux') lacks PIE.
pd W: ELF file ('usr/lib/pd/extra/pd~/pd~.pd_linux') lacks PIE.
pd W: ELF file ('usr/lib/pd/extra/pique/pique.pd_linux') lacks PIE.
pd W: ELF file ('usr/lib/pd/extra/sigmund~/sigmund~.pd_linux') lacks PIE.
pd W: ELF file ('usr/lib/pd/extra/stdout/stdout.pd_linux') lacks PIE.
```

It would be great, if PIE could be accomplished for these by default.

**Comment by umlaeute** [comment]
do you use autotools or Makefile.gnu?

have you considered this to be a false positive? (those files are not "executables", but dlopen()end plugins)

have you considered this to be a packaging bug? (e.g. you not inserting the proper CFLAGS?)

i'm closing this as "wontfix" for now, but if you have a solution for the problem, feel free to create a PR.
