### ISSUE TITLE
Files with spaces don´t open with double click

### ISSUE THREAD

**Issue by allanfelipe** [pure-data/pure-data#759]
Hi, I´m having an issue I didn´t have before with an older version of pd running in another computer. Now I´m with 0.50.1 in Windows 10, 64 bit. When I double click .pd files with spaces (spaces anywhere in the path), I receive the following error and pd doesn´t even start. Everything else is fine (and the files open with File/Open).
![space](https://user-images.githubusercontent.com/8100700/65729253-01b60b00-e094-11e9-95be-46d70fb93939.png)

**Comment by umlaeute** [comment]
what was the last version of Pd where this worked?

**Comment by allanfelipe** [comment]
The old notebook has Pd extended 0.42.5 running in Windows Vista 32bit. Is this something that never worked in vanilla?

**Comment by porres** [comment]
> Is this something that never worked in vanilla?

If this was known, it would have been said, so I don't think it's the case.

In fact, Pd-Extended is not Pd Vanilla, so you cannot compare to it.

Can you then please test earlier vanilla versions so we can have more to investigate? It's important to know which version broke it, if any, so we can try to see how it got broken.

**Comment by Lucarda** [comment]
@allanfelipe thanks for reporting.

I think the issue is on the installer when it writes to the registry line:
https://github.com/pure-data/pure-data/blob/master/msw/pd.nsi#L118

the ending `%1` should be `"%1"` (quoted).

I get no error if I manually edit my registry.

(@allanfelipe If you want you can edit your registry and have it fix. Edit this entry:
**HKEY_CLASSES_ROOT\PureData\shell\open\command** )

**Comment by allanfelipe** [comment]
Thanks. Indeed, this solves the problem :)

**Comment by allanfelipe** [comment]
Since the bug fix wasn't implemented, but there is a workaround, I'm not sure if the issue must be closed or not.

**Comment by porres** [comment]
> I'm not sure if the issue must be closed or not.

please reopen :)

**Comment by Lucarda** [comment]
I made PR #761 to fix this issue.
