### ISSUE TITLE
macOS key regression 0.50-1

### ISSUE THREAD

**Issue by danomatika** [pure-data/pure-data#760]
As reported on the pd-list, the recent deadkey handling introduced a regression where pressing the "BackSpace" key, often labelled confusingly "delete" on Mac keyboards, results in a "Delete" event, aka. forward char removal (ASCII 127 BS) instead of reverse removal (ASCII 8 DEL).

Relatedly, pressing FN+Backspace does not produce a DEL event as expected.

**Comment by danomatika** [comment]
In `::pd_bindings::sendkey`, it seems that the scan from key to $iso is the issue. This quick hack seems to fix it:

~~~
            switch -- $key {
                "BackSpace" { set key   8 }
                "Tab"       { set key   9 }
                "Return"    { set key  10 }
                "Escape"    { set key  27 }
                "Space"     { set key  32 }
                "space"     { set key  32 }
                "Delete"    { set key 127 }
                "KP_Delete" { set key 127 }
                "KP_Enter"  { set key  10 }
                default     {    
                    scan $iso %c key
                    if { "$key" eq "13" } { set key 10 }
                    catch {
                        if { "" eq "${::pd_bindings::key2iso}" } {
                            set ::pd_bindings::key2iso [dict create]
                        }
                        # store the key2iso mapping
                        dict set ::pd_bindings::key2iso $keycode $iso
                    }
                }
            }
~~~

**Comment by umlaeute** [comment]
what `$iso` code is the <kbd>BackSpace</kbd> key sending on OSX?

i'd rather understand why the current imlementation fails on OSX (but not on Windows and Linux) before adding more "quick hacks"

**Comment by danomatika** [comment]
>what $iso code is the BackSpace key sending on OSX?

"iso" comes as an empty string. I'd say this is a bug in Tk, but go figure. A post added to the beginning of the proc:

    ::pdwindow::post "state \[$state\] key \[$key\] key code \[$keycode\] iso \[$iso\] shift \[$shift\]\n"

yields the following:

    state [1] key [BackSpace] keycode [3342463] iso [] shift [0]

When comparing to the other explicitly checked keys (macOS 10.14.6 w/ Pd's embedded Tk 8.5.19):

| key | keycode | $iso char | note |
| - | - | - | - |
| BackSpace | 3342463 | "" | |
| Tab | 3145737 | "\t" | |
| Return | 2359309 | "\n" | |
| Escape | 3473435 | "" | |
| Space | ? |  _not triggered_  | see space |
| space | 32 |  " " | |
| Delete | 7730984 | "" |FN+Backspce on laptop, Delete on mac USB KB |
| KP_Delete | ? |  _not triggered_  | called "Clear" on mac USB KB |
| KP_Enter | 4980739 | "" | on mac USB KB |
| Clear | 4716345 | ""| |

What's basically failing is that scan seems to convert BackSpace to ASCII 127 DEL and similarly fails to convert FN+BackSpace to ASCII 127 DEL.

I will try to print the iso chars in hex for better inspection.

>before adding more "quick hacks"

I couldn't quite follow the logic of what's going on in that proc, so I tried a few "hacks" just to work around things in a spare half hour. If proving there is some way to fix it without being able to do a deep fix is somehow *not* useful, I won't bother next time.

_Semantics: Officially, the OS called is "macOS" since 2016._

**Comment by danomatika** [comment]
Also, maybe this is a bug in my custom Tk key fix patch? I dunno. I can't even build Tk 8.5.19 any longer in order to tell.

**Comment by umlaeute** [comment]
> What's basically failing is that scan seems to convert `BackSpace` to ASCII *127* DEL

bummer. so it reports the "backward delete" key as "forward delete"....go figure.

i also tested with Tcl/Tk-8.5.9 (as shipped with "El Capitab") and it reports the same broken keycodes.

the big issue i'm having with moving (or copying) the `switch -- $key` up, is that this will break whenever those keys are involved in deadkeys...

here's a patch that i like better (it's also supposed to be more performant, as the matching is done on the `bind` level:
~~~diff
diff --git a/tcl/pd_bindings.tcl b/tcl/pd_bindings.tcl
index 9c86f6f..49972fc 100644
--- a/tcl/pd_bindings.tcl
+++ b/tcl/pd_bindings.tcl
@@ -125,6 +125,12 @@ proc ::pd_bindings::global_bindings {} {
             bind all <$::modifier-Key-m>       {menu_minimize %W}
             bind all <$::modifier-quoteleft>   {menu_raisenextwindow}
         }
+        # BackSpace/Delete report the wrong isos (unicode representations) on OSX,
+        # so we set them to the empty string and let ::pd_bindings::sendkey guess the correct values
+        bind all <KeyPress-BackSpace>      {::pd_bindings::sendkey %W 1 %K "" 1 %k}
+        bind all <KeyRelease-BackSpace>    {::pd_bindings::sendkey %W 0 %K "" 1 %k}
+        bind all <KeyPress-Delete>         {::pd_bindings::sendkey %W 1 %K "" 1 %k}
+        bind all <KeyRelease-Delete>       {::pd_bindings::sendkey %W 0 %K "" 1 %k}
     } else {
         bind all <$::modifier-Key-q>       {pdsend "pd verifyquit"}
         bind all <$::modifier-Key-m>       {menu_minimize %W}
~~~

**Comment by danomatika** [comment]
That's a good solution.
This was what initially had me confused as those keys were simply not processing through the switch in the way they should have been. Too bad we did not catch this sooner.

I'll test it on my system. If this works, we should push Miller for a 0.50-2 release for this bug alone.

**Comment by umlaeute** [comment]
i've pushed this to the `deadkeys` branch, so it's easier to test for everybody :-)

**Comment by umlaeute** [comment]
and of course, i would also like to invite everybody (including people on Windows and Linux and FreeBSD) to test the branch.

(although this time the changes really should only effect OSX users; but you never know...)

**Comment by umlaeute** [comment]
adding @Lucarda, @Spacechild1 and @porres to the list of people who should read the above.

**Comment by danomatika** [comment]
>the changes really should only effect OSX users

(... "macOS")

**Comment by umlaeute** [comment]
> > the changes really should only effect OSX users
> 
> (... "macOS" users)

that was of course on purpose.

**Comment by Spacechild1** [comment]
@umlaeute just tested on Windows 7 and OSX 10.11. Backward/forward deletion works as expected. Tilde works as well. Didn't notice anything unusual.

**Comment by danomatika** [comment]
Works for my 10.14 system. I added some key bindings for the numpad KP_Enter and Clear buttons as well. On Apple "extended keyboards", Clear only deletes selected text, so I didn't bother to map it to either BS or DEL. AT least now you can respond to it with [key] if you want.

**Comment by danomatika** [comment]
>Clear only deletes selected text, so I didn't bother to map it to either BS or DEL.

OTOH we could map it to KP_Delete to match KP_Enter. Oh well, just a detail...

**Comment by Lucarda** [comment]
@umlaeute tested with 0.50-1 with the "pd_bindings.tcl" from `deadkeys` branch on win10 and debian10lxqt.
I get <kbd>del</kbd> to delete to the right and <kbd>backspace</kbd> to delete to the left.

**Comment by HenriAugusto** [comment]
Tested with 0.50-1 in Win 7. Everything working correctly.
