### ISSUE TITLE
need to press 'ctrl' or other function key to start gui

### ISSUE THREAD

**Issue by r33p** [pure-data/pure-data#766]
On ubuntu 18.04, once in a while, pd dont start and just open a grey windows (without any menu nor GUI), and after a few seconds : watchdog: signaling pd...

```
rep@w00t:~/Sources/pure-data$ ./bin/pd -noprefs
watchdog: signaling pd...
```

the gui comes up and show itself (menu bar, dsp check box, console etc) if I press one of these keyboard keys :
'left shift', 'capslock', 'left ctrl' 'left alt', 'alt gr', 'right shift', 'right ctrl'

```
rep@w00t:~$ ~/Sources/pure-data/bin/pd -version
Pd-0.50.2 ("") compiled 09:53:55 Oct  7 2019
rep@w00t:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
rep@w00t:~$ uname -a
Linux w00t 5.0.0-31-generic #33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by umlaeute** [comment]
weird, i never had this.

does the same happen with the Debian/Ubuntu packages?

**Comment by r33p** [comment]
sadly yes...
![Capture d’écran de 2019-10-07 14-30-08](https://user-images.githubusercontent.com/1814233/66311617-2a999400-e90f-11e9-8c69-5a3a2727f3cd.png)

but once I press ctrl or another function key, 
the GUI comes up and I can use pd...

```
rep@w00t:~$ /usr/bin/pd -version
Pd-0.48.1 ("") compiled for Debian (0.48.1-3) on 2018/02/27 at 20:11:48 UTC
```

**Comment by r33p** [comment]
Note that I have network problems with this laptop (something bad happen with intel firmware) : network disconnect sometimes and I dont know why :/
Could this be a reason ?

**Comment by reduzent** [comment]
Oh, I'm glad to see I'm not the only one having this. Only last week I figured out that such GUI freezes can be resolved by hitting the Control key.

This with Pd 0.50.1 compiled from git on Ubutnu 18.04. Maybe an Ubuntu problem?

**Comment by r33p** [comment]
Yes it is strange... And sometines it happen also with the property window of a gui element (a number box, symbol etc...) : nothing is drawn until I press the ctrl or a function key.

**Comment by umlaeute** [comment]
could it be related to the window manager?
i guess you are using gnome, what happens in xfce4 (which i use, and never experience any problems with)

**Comment by r33p** [comment]
Yep, you are right, I've just tested with fluxbox and the problem dont seems to happen with this window manager...
