### ISSUE TITLE
Cannot type ~ anymore with AZERTY keyboard

### ISSUE THREAD

**Issue by justanotheridentity** [pure-data/pure-data#774]
I can't make the sign ~ in Pure Data anymore.
To use use it I have type it in a text editor and then copy and paste it in Pure Data which is not ideal.

On a AZERTY keyboard to make this sign [~] you need use [Alt Gr] + [é] release and then press another key 

and then ONLY the symbol [~] will appear with the other key you have have type for example:
[Alt Gr] + [é] + [e] = [~e]

Alternatively you can use [Alt Gr] + [é] release and then press [space] who will result in [~]
These work no more.

Thanks for any help.

**Comment by porres** [comment]
hints, tell us the operating system and what version of pd you're using

there was a problem for windows on pd 0.50 and non american keyboard layouts, but it got fixed, current version of pd is 0.50-2

maybe you're on 0.50 and should upgrade and close this issue

**Comment by justanotheridentity** [comment]
I was in pd 0.50, I wasn't aware it's was fix, sorry for this.
Sadly I wasn't able to upgrade, can't figure how to compile myself so I will just wait for an installer. 
Thanks anyway.

**Comment by porres** [comment]
What OS? If you're on windows, there are installers.
