### ISSUE TITLE
help

### ISSUE THREAD

**Issue by WanShane** [pure-data/pure-data#775]
bug message as follow

 count 32
... couldn't create

When I created Object Box in Pd, this bug message reminded.
It is something wrong with my Pd or my MacBook. (OS: Mac Mojave)

**Comment by umlaeute** [comment]
ah btw, it's usually better to keep the issue-tracker for bugs/feature-requests/... and use the [mailinglist, forum, irc,...](https://puredata.info/community) for questions.

**Comment by porres** [comment]
all of them create for me
<img width="215" alt="Screen Shot 2019-10-10 at 04 09 57" src="https://user-images.githubusercontent.com/5360142/66555185-dca1ad80-eb13-11e9-985f-67d0ae775e9e.png">

**Comment by umlaeute** [comment]
i think nobody doubted that they create, if you have the libraries

**Comment by WanShane** [comment]
> ah btw, it's usually better to keep the issue-tracker for bugs/feature-requests/... and use the [mailinglist, forum, irc,...](https://puredata.info/community) for questions.

Okay. Thank you very much.
