### ISSUE TITLE
Feature request: `arg` object, kinda like `list` or `array` but for abstraction arguments.

### ISSUE THREAD

**Issue by danfuzz** [pure-data/pure-data#780]
There seem to be a lot of folks who would like to be able to access abstraction arguments programmatically. Though some Pd extensions seem to support this (e.g. `$@` in Purr Data), Pd Vanilla does not yet have anything like this, which leads to a lot of hackery, such as is discussed here:

* https://forum.pdpatchrepo.info/topic/10892/collect-all-arguments-as-a-list
* https://lists.puredata.info/pipermail/pd-list/2009-04/069941.html

It strikes me that an `arg` abstraction that has subcommands — sort of like `list` and `array` — might fit well with the general feeling of Pd and hence be acceptable for inclusion in the main project. Straw-man suggestion:

* `arg length` — when `bang`ed outputs the number of abstraction arguments.
* `arg get <n>` — when `bang`ed outputs the `n`th argument. Second inlet lets you change `n`.
* `arg list` — when `bang`ed outputs all arguments as a list.

**Comment by porres** [comment]
>  Pd Vanilla does not yet have anything like this

but it does, see [pdcontrol].

please close issue, thanks

**Comment by danfuzz** [comment]
Thanks, and sorry for the noise! I browsed the top-level help and (alas) the name `pdcontrol` didn't jump out at me as a potential solution to my problem.
