### ISSUE TITLE
Feature request: Allow arbitrary message output from `expr`

### ISSUE THREAD

**Issue by danfuzz** [pure-data/pure-data#783]
I find myself wanting to do stuff like emit a `bang` or a more complicated message like `set 10` from an `expr`, and right now I have to build that by chaining an extra object off of an `expr` outlet. It strikes me as a useful extension to allow `expr` outlets to send arbitrary messages, not just numbers.

**Comment by porres** [comment]
that could be easily done with a [select] object in the output

**Comment by danfuzz** [comment]
Something like `bang` is easy, but if I want to do anything more complex, to my taste at least, the extra objects start to feel burdensome, especially if I want to (say) vary the symbol being sent.

**Comment by Spacechild1** [comment]
`[expr]` is meant for mathematical expressions. if you want to construct messages based on the results, you can do this with seperate objects. there's no need to do this within the `[expr]` object itself.

**Comment by porres** [comment]
seems you want expr to be more like a script language, I just don't see that happening according to previous discussions on the pd list :/

**Comment by danfuzz** [comment]
I don't know that I want a textual scripting language per se, but I'll certainly say I find it frustrating how Pd specifically chooses to draw some semantic distinctions.

In any case, thanks for the responses to this and my other recent issues.

**Comment by porres** [comment]
I'm also gonna go ahead and close this as "out of the scope of the object"
