### ISSUE TITLE
Feature request: tail call recursion elimination

### ISSUE THREAD

**Issue by danfuzz** [pure-data/pure-data#785]
I found myself recently writing a patch with a connection loop, in a fairly straightforward way, and — perhaps unsurprisingly — I ended up blowing the stack. It wasn't terrible in this particular case to restructure the patch to use `until` and stored variables / values, but really, what I was doing was just a natural tail-recursive loop.

It would be great if Pd actually supported tail call recursion elimination so one could actually write these sorts of straightforward loops, without having to rewrite them using stored variables and `until` as a trampoline.

**Comment by Spacechild1** [comment]
unfortunately, tail call elimination is impossible in Pd. at least I don't know how I would implement it.

**Comment by Spacechild1** [comment]
For tail call elimination you need a function definition to be able to reuse the call frame. In Pd you only have loose connections between objects and the stack is really just the C call stack, so there's no way to achieve this without adding an additional parsing step of the object graph. This is not going to happen, so I'm closing this for now. 

Generally, Pd is not good at deep recursion (like many other languages!), so an iterative approach is always preferable.
