### ISSUE TITLE
Feature request: Allow arbitrary message input to `expr`

### ISSUE THREAD

**Issue by danfuzz** [pure-data/pure-data#786]
I'd love to be able to perform computation on arbitrary messages coming into an `expr`. E.g. maybe I could have an inlet which takes messages of the form `get X Y` or `set X Y V`, and I could use functions in `expr` to extract the symbol, and count / extract arguments.

Or, if nothing else, I could send an incoming message as-is onward to an outlet.

Related issue: #783

**Comment by Spacechild1** [comment]
again, [expr] is meant for computing mathematical expressions, it's not a general purpose scripting language. just use regular Pd objects.
