### ISSUE TITLE
Feature request: Symbol functions in `expr`

### ISSUE THREAD

**Issue by danfuzz** [pure-data/pure-data#787]
It's great that `expr` allows symbols to be used as inlet values. It's unfortunate, though, that you can't actually do much with them. It'd be great if there were a set of functions which could operate on symbols, and if the comparison operators could process symbols in the expected manner.

Straw-man suggestions for functions:

* symbol length (in characters)
* extract nth character of symbol
* extract range of characters from symbol
* append / prepend character to symbol
* concatenate symbols

**Comment by Spacechild1** [comment]
again, `[expr]` is meant for mathematical expressions. there are other objects for symbol manipulation, e.g. `[list fromsymbol], [list tosymbol]` + various list methods.

**Comment by porres** [comment]
this is your lucky day @danfuzz see https://github.com/pure-data/pure-data/commit/cad91dc791c7b17972d4d508f6bf6a93f1ff0613
