### ISSUE TITLE
Feature request: positive-zero filter in `expr`

### ISSUE THREAD

**Issue by danfuzz** [pure-data/pure-data#789]
It's a little thing, I know, but I found myself unexpectedly getting both positive and negative zeros out of a calculation, and for consistency in this particular context I want to only ever get positive zeros. It's not _terrible_ to use a separate `expr` object with `if($f1 == 0, 0, $f1)` as a filter, but it'd still be nice if there were a built-in function to perform this operation.

Related issue: #788 (because with that, I could at least define the function myself and then use it in my main `expr`, instead of having to have a _separate_ `expr` object)

**Comment by Spacechild1** [comment]
what is `if($f1 == 0, 0, $f1)` supposed to do? looks like a no-op to me...

if you want to filter positive values, you can just use `[moses 0]`.

**Comment by danfuzz** [comment]
>what is if($f1 == 0, 0, $f1) supposed to do? looks like a no-op to me...

It's not, because IEEE754 floating point (a) defines both positive and negative zeros, and (b) positive and negative zero are considered `==` to each other. That is, this function filters out negative zeros, turning them into positive zeros.

**Comment by danfuzz** [comment]
Quick demo, ICYC:

![negative-zero-whee](https://user-images.githubusercontent.com/1090235/68825485-1b64df00-064f-11ea-9609-11fec355c19a.png)

**Comment by Spacechild1** [comment]
OK, but what's your actual use case? *Why* do you need to bash negative zero to positive zero? I'd say the cases where you ever have to care about the destinction between positive and negative zero are very rare.

Anyway, `expr if($f1 == 0, 0, $f1)` does what you need. Do you really think we need some sort of built-in function for that?

**Comment by danfuzz** [comment]
>Do you really think we need some sort of built-in function for that?

It would have been nice, in that it would have kept the overall logic of my patch just a little bit cleaner. As I said at the top, "It's a little thing, I know."

In any case, here's where I'm using it: <https://github.com/danfuzz/fuzz-synth/blob/master/Infiknob/vanilla/infiknob.pd> TLDR: I want to guarantee only positive zeros getting emitted from the object so that client code always sees consistent behavior; as demonstrated here if the downstream code uses `copysign` it will get inconsistent results if I don't fold zeros down.

**Comment by Spacechild1** [comment]
The vast majority of floating point calculations don't care about the sign of 0. I'd say if downstream code depends on the sign of 0 (e.g. by using copysign), then it's *their* responsibility to handle it appropiately. In your example, I don't see why you need to care about negative zeroes at all...

If you really think it's worth adding this feature, make a PR!

**Comment by danfuzz** [comment]
> it's _their_ responsibility to handle it appropiately

Fair, though in this case I'm both upstream and downstream, and the way I operate is to (approximately) minimize surprise. I in fact noticed the unexpected negative zero coming out of my patch, and it struck me that, in the end, I would be best served by making my upstream more consistent than let it linger in inconsistency and end up with a more nasty surprise down the line once I forgot about the quirk.

And FWIW while trying to track down what was going wrong I got misled due to the bug I filed as #790, so I figured might as well file that too.

**Comment by danfuzz** [comment]
> if you really think it's worth adding this feature, make a PR!

FWIW I DL'ed the source and poked around a bit in it and the wiki, and unfortunately could not find up-to-date instructions for building on macOS.

**Comment by Spacechild1** [comment]
https://github.com/pure-data/pure-data/blob/master/INSTALL.txt

**Comment by Spacechild1** [comment]
> than let it linger in inconsistency and end up with a more nasty surprise down the line once I forgot about the quirk.

I still don't understand what's your problem with negative zeros. It won't affect computations, unless you explicitly ask for it (e.g. with copysign) - and that's the place where you actually have to handle it.

Also, by bashing -0 to 0 you only hide the symptom instead of tackling the root cause (which is underflow).

**Comment by danfuzz** [comment]
> Also, by bashing -0 to 0 you only hide the symptom instead of tackling the root cause (which is underflow).

Underflow 100% definitely wasn't the problem in my actual case where I noticed the problem: It was instead that, depending on previous inputs to the object, when it should output "zero" it would sometimes output a negative zero and sometimes a positive zero. There was no underflow. I'm pretty sure it boiled down to the fact that I'm in fact using `copysign` as part of the abstraction's definition (in a very useful way! I'm very happy that function exists!), and it dutifully produced a negative zero under appropriate-to-it circumstances.

So, this is not a case of "masking a problem," it's more like "creating a consistent abstraction."

**Comment by danfuzz** [comment]
> https://github.com/pure-data/pure-data/blob/master/INSTALL.txt

Thanks, I found that but the `autogen` script fails for me with an error (missing `aclocal`). I figured there's something I needed to install beyond autoconf and whatever else I already had lying around, but didn't see any obvious candidates.

**Comment by Spacechild1** [comment]
> I'm pretty sure it boiled down to the fact that I'm in fact using copysign as part of the abstraction's definition

well, then the root cause is that you use `copysign` without filtering 0s first. the point I'm trying to make is that the occurrence of -0 itself is a red flag and usually points to some problem in the code.

anyway, since Pd already gives you the means you need and IMHO this issue is too niche to warrant adding a function to [expr], you might consider closing this feature request.

**Comment by danfuzz** [comment]
I understand your position, though I disagree with it. Specifically, if something like #788 existed, then I'd be 100% with you that this is a niche function etc etc etc, but then I could just add it to my own library, and then use it in `expr`* in a fairly natural way. Instead, I now have to code it in "long form" and in a separate `expr` object any time I want to use it.

But — hey! — I know I'm a n00b Pd user, and I know this isn't my project. So, no offense taken. Closing.
