### ISSUE TITLE
Number box with a zero won't update when given a zero of opposite sign.

### ISSUE THREAD

**Issue by danfuzz** [pure-data/pure-data#790]
If you have a number box which shows a positive or negative zero, and you then send a zero of the opposite sign to it, the value stored by and transmitted through the box is properly updated, but the display is not. Here's a quick demo:

![number-box-zero-display](https://user-images.githubusercontent.com/1090235/68825954-df327e00-0650-11ea-8a92-fc18b215cc0f.png)

Note that when you hit the bang for the positive and negative zeros, the value gets propagated correctly, but neither of the intermediate number boxes ever changes its display. And when you hit the bang to resend the value of the top number box, the correct stored value is sent.

This was observed on Pd 0.50.0.

**Comment by Spacechild1** [comment]
as optimization, graphics are only updated if the new value is different from the old one, and as you've mentioned in another issue, positive and negative zero compare equal. we could add additional logic, but I'm not sure it's worth it...

BTW, since you're an experienced software engineer, many of your feature requests could be pull requests ;-)

**Comment by danfuzz** [comment]
>many of your feature requests could be pull requests ;-)

I'm certainly up for submitting PRs, but it hasn't been clear to me whether the project would actually be receptive. (Same goes with the other issue you commented on similarly, though I think that one was perhaps using "PRs gladly accepted" more in the euphemistic sense :-p .)

**Comment by Spacechild1** [comment]
>  whether the project would actually be receptive.

it certainly is! if you make a good PR, the chances for the feature to get included is much higher than just making a feature request and wait for someone to implement it ;-) I'm just telling you this because I know you're an experienced software developer

**Comment by Spacechild1** [comment]
Pd needs more developers, so you're highly welcome to dive into the source code! if you have any questions, you can always ask me.

**Comment by danfuzz** [comment]
BTW I just tested the new-style number box, and in addition to not changing its display when presented with a zero of opposite sign, it also fails to store or propagate the new value (that is, not just a display bug). E.g., if it stores a positive zero and you send a negative zero to it, it will re-output a positive zero.

**Comment by porres** [comment]
This has been fixed, we can close this!!!

**Comment by umlaeute** [comment]
i think so
