### ISSUE TITLE
Get pure data to output the graph view of the objects without having the user do a screenshot

### ISSUE THREAD

**Issue by muziker** [pure-data/pure-data#793]
In other languages, users can show examples of their work by simply showing them the text file. In pure data, we need to take a screen shot or do fancy ascii art to show what the patches look like.

I propose that pd should be able to output a jpeg of the patch without opening the patch itself. This will facilitate users exchanging examples without resorting to mental ascii gymnastics. 

So: pd --pic <patchname> generates a jpeg of the patch

**Comment by umlaeute** [comment]
it is impractical to do that without *opening* the patch: a visual representation of a patch depicts the "API" of each object ( that is: the number and type of each iolet) which is only known at runtime (eg: do *you* know, how many iolets the `[limiter~ 1 2 3]` object has?)

for loaded objects, we already have the "patch2svg" plugin that generates SVGs ( somewhat cooler than JPGs), which comes with an example on how to automate taking snapshots.

**Comment by umlaeute** [comment]
regarding "exchange of examples": an image (whether JPG or SVG or whatelse) is never going to be a meaningful transportation medium (this is also true for text-based languages - eg cf how stackoverflow frowns upon screenshots).

share your patches, not your screenshots.. .

i think a gui-plugin that interfaces with an online-renderer like https://pastie.iem.at/ might be handy though

**Comment by muziker** [comment]
Right, i was too enduser about the description, but in general, without actually starting the gui or the audio system, convert the patch into a jpeg. Yes svg is great if you're going to change resolution and watch it scale effortlessly, but in the use case of: in a small group of people, showing snippets of the patch, it invariably means they'll have to edit and convert the .svg into .jpeg

In terms of the user experience, let's say i'd like to show a patch to somebody, i need to open pd, take a screenshot and trim it to the section and upload it to a sharing application like fb or as a forum post. If i can do this `pd --pic patch.pd`, and check patch.pd.jpg, upload as a photo to fb, that would be awesome. With patches that people put on github, if as a last step before commiting, all the patches are automatically converted into a picture and uploaded, then someone could look at the patch instead of downloading and loading up the patch.

**Comment by umlaeute** [comment]
i fail to see any advantages in your post:
- everyone (with a browser) can open SVG files. upload the SVG file to fb (if fb doesn't support SVG, then file a bugreport with them; same if fb only supports XLS files).
- did you check out the patch2svg plugin? did you check out the example that allows you to create a "screenshot" of a patch without user-interaction (merely by *typing a few runes on the cmdline*). how is it different from your `pd --pic` example? (btw, Pd uses single-dash args ;-))
- what is wrong with opening the GUI? (on a conceptual level); the GUI does large parts of the the graphical representation of a patch; why would you want to keep it out?

**Comment by muziker** [comment]
Actually, you're kind of right, can2svg piped through imagemagick to convert to jpeg might be the thing. This feature request was prompted by my frustration looking through github at pd patches and having to download the patches to open in the gui to see what it was doing. But can2svg would work fine.
