### ISSUE TITLE
Filing PD issues here?

### ISSUE THREAD

**Issue by ssfrr** [pure-data/pure-data#8]
Is this a reasonable place to file general PD issues? Seems like @millerpuckette is paying some attention to this repo despite it's unofficial status so it would be great if this were a place people could file issues in a way that doesn't get lost into the mists of pd-users. Also the sourceforge "issue tracker" link [here](http://puredata.info/downloads/pure-data) is a 404.

EDIT: clarify which link I'm referring to

**Comment by umlaeute** [comment]
The link you gave points to puredata.info and is not a 404

**Comment by ssfrr** [comment]
the "issue tracker" link on that page is what I was referring to. Edited for more clarity.

**Comment by umlaeute** [comment]
thanks.
updated the links to the issue-tracker and the repository.

can this ticket be closed then? (aka: please don't file multiple issues in one ticket)

**Comment by ssfrr** [comment]
Thanks for fixing the links. I take it the answer is that the sourceforge tracker is the preferred place to file issues.

**Comment by umlaeute** [comment]
the final word about the preferred tracker ha of course miller.

both have drawbacks:
- sourceforge has this very strange privacy/advertising/... policy
- github requires you to sign-up before being able to submit a bug-report
