### ISSUE TITLE
label misaligned when moving numberbox object with Zoom In

### ISSUE THREAD

**Issue by mariobuoninfante** [pure-data/pure-data#802]
MacOS High Sierra 10.13.1 - Pd 0.50.2

**STEPS**
1. launch Pd
2. open a new patch
3. create a number box
4. assign a label to the object
5. zoom in (CMD+=)
6. move the numberbox object

**RESULTS**
- the label doesn't follow _properly_ the object
- when zooming out (and also when zooming in again after that) the label is properly displayed

**Comment by mariobuoninfante** [comment]
<img width="453" alt="Screen Shot 2019-12-02 at 13 46 08" src="https://user-images.githubusercontent.com/20879405/69964425-4f267c80-150a-11ea-8b62-0ce8fc5eb896.png">

**Comment by jyg** [comment]
I proposed a pull request to fix this
https://github.com/pure-data/pure-data/pull/753#issuecomment-535850452

**Comment by mariobuoninfante** [comment]
@jyg  Do you reckon I should close this though?

**Comment by jyg** [comment]
No I don't think so. However, the PR should be merged with the new pd release.

**Comment by danomatika** [comment]
I'm checking this.

**Comment by danomatika** [comment]
#753 is now merged into the running bugfix `update/0.50` branch.

**Comment by porres** [comment]
is this merged and can be closed?

**Comment by jyg** [comment]
Yed

**Comment by porres** [comment]
@Spacechild1 , please close this :)
