### ISSUE TITLE
[clone] weird behaviour when inlet~ connects to outlet~

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#809]
Hi, I'm finding this weird bug were a signal input is not distributed properly inside clone.

In this test, all abstractions should receive "1" and a total output should have been "6", but weirdly enough, it gets exponentially higher as the number of abstraction increases and the total output is 32.

<img width="594" alt="Screen Shot 2019-12-03 at 17 07 55" src="https://user-images.githubusercontent.com/5360142/70085842-d13ca100-15ef-11ea-80a9-86b9776fec1b.png">

**Comment by porres** [comment]
BTW, it still happens with recent changes to inlet~ and clone - up to commit https://github.com/pure-data/pure-data/commit/8b825f7b9f662ca27cd5a8dad396caf2db57da02

**Comment by Spacechild1** [comment]
I've noticed this, too. It happens when there's no other DSP object between the inlet~ and outlet~

**Comment by porres** [comment]
ok, less crazy and not that bad then

**Comment by millerpuckette** [comment]
I think this is fixed in commit 8802377997632d90ee3a116e3291f58e108a20b5

**Comment by porres** [comment]
I actually had tested with the latest commits, so not really :/

**Comment by porres** [comment]
like I said, I tested with up to commit https://github.com/pure-data/pure-data/commit/8b825f7b9f662ca27cd5a8dad396caf2db57da02

**Comment by millerpuckette** [comment]
sure enough.  I had that 'fixed' but it came back somehow.  will look again.

**Comment by millerpuckette** [comment]
tried again.

**Comment by porres** [comment]
Yup! Fixed :D
