### ISSUE TITLE
oscformat doesn't accept lists that start with a symbol

### ISSUE THREAD

**Issue by jmmmp** [pure-data/pure-data#813]
To find this bug:
- open the oscformat help patch
- in any of the messages going to [oscformat cat horse pig], put a symbol string before the numbers
- the message "oscformat: no method for ..." will appear

It works if a list is declared as "list ....", but then the word list is also in the output.

**Comment by umlaeute** [comment]
> To find this bug:
>     * in any of the messages going to [oscformat cat horse pig], put a symbol string before the numbers

if you do that, you are changing the message selector from the (implicit) `list` to whatever you put there...

> 
>     * the message "oscformat: no method for ..." will appear

..., so no wonder. to send data to `[oscformat]` you *must* send it a `list`-message.
you can send other messages as well, e.g.  `[set ...(` message for changing the OSC-path.

> It works if a list is declared as "list ....", 

this is the only way of declaring a "list" (as opposed to non-list messages)

> but then the word list is also in the output.

it doesn't happen here, but i don't know what you mean: what is "the output"?

`[oscparse]` will *always* output `[list(` messages (which is arguably annoying), no matter what the input data.

e.g. `[4 5 weasel 6 7 rat( -> [oscformat cat horse pig] -> [oscparse]` will create a message `[list cat horse pig 4 5 weasel 6 7 rat(`
similarily `[list cheetah 4 5 weasel 6 7 rat( -> [oscformat cat horse pig] -> [oscparse]` will create a message `[list cat horse pig cheetah 4 5 weasel 6 7 rat(`

**Comment by jmmmp** [comment]
Checking list-help, I guess the issue is rather that lists without 
"list" declaration are legal if they start with a float, but illegal if 
they start with a symbol. Since this is an ancient "Pd-standard", 
probably it won't be solved, as many won't see a problem here (and 
probably lots has already been written about it, of which I'm too lazy 
to search now).

So, no bug to report.

**Comment by Spacechild1** [comment]
> probably lots has already been written about it, of which I'm too lazy
to search now).

@umlaeute just recently summed it up pretty nicely in this e-mail: https://lists.puredata.info/pipermail/pd-list/2019-11/126398.html
