### ISSUE TITLE
[intelligent patching]: Automatically connect [bang] or [toggle] to first outlet of previous object when created with keyboard shortcut

### ISSUE THREAD

**Issue by virusys** [pure-data/pure-data#826]
I like the fact that I can quickly chain a bunch of objects together by typing into an object box, and then instead of pressing enter I can press the keyboard shortcut to create another object right away that's automatically connected to it. 

However, I’ve noticed that this behaviour is not consistent when you try to create [bang] or [toggle] boxes in this way. It works if you create a [bang] or [toggle] as your first object, and then use keyboard shortcuts to chain additional objects; but not the other way around. If I try to create a [metro] object and then type the keyboard shortcut to create a [bang] instead of pressing enter, the bang will appear but will be disconnected from the [metro] object.

Attached is a video for reference.

![pd-linking-objects](https://user-images.githubusercontent.com/393711/70452496-31f72e00-1a75-11ea-832c-503e8e668132.gif)

**Comment by umlaeute** [comment]
you can simply create an object (<kbd>Ctrl</kbd>-<kbd>1</kbd>) and type `bng` to get an autoconnected gui-bang

**Comment by Ant1r** [comment]
there's also PR  #756 for doing this.

**Comment by virusys** [comment]
Ok, thank you for the tip! I had it working for the toggle but I did not
know how to get the gui-bang. Feel free to close this issue.
