### ISSUE TITLE
request, load creation values (or 'arguments') in [savestate]

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#832]
The issue I see here is that you cannot load default values given by the user with savestate when you first create an abstraction.

Surely you'd normally do this with arguments, but even though closely related, at least in concept, arguments have nothing to do with what savestate currently does. The problem if you try to use arguments, they'll override the output of [savestate].

I'm not 100% sure about the mechanism behind savestate in order to have a clear picture that would lead me to a clear solution or idea on how to address this. One way I see is to have a flag in savestate so it deals with reading and rewriting arguments. But I see that is quite a drastic change of purpose and structure of this object. Not only that, but it would make the args method in [pdcontrol] obsolete.

So yeah other than that, I'm not sure it is possible for savestate to load values when it's created for the first time. Maybe someone else will find a hack here ;)

**Comment by Spacechild1** [comment]
> at least in concept, arguments have nothing to do with what savestate currently does. 

yes, because they are not really related

> The problem if you try to use arguments, they'll override the output of [savestate].

you can simply solve that with a [spigot], see [savestate-args-test.zip](https://github.com/pure-data/pure-data/files/3947628/savestate-args-test.zip)

**Comment by porres** [comment]
> you can simply solve that with a [spigot], see savestate-args-test.zip

well, I hadn't seen it, and still haven't, but I came here to show my solution :) 

![Screen Shot 2019-12-10 at 20 35 01](https://user-images.githubusercontent.com/5360142/70578460-93f68700-1b8c-11ea-95ec-93ad95572c18.png)

so yeah, I bet it's a similar idea, anyway, I'll just close this.

**Comment by porres** [comment]
> they are not really related

at least in concept I could argue they are, cause it's just a list of parameters that are stored with the abstraction in the patch. I actually find confusing that we had another mechanism that seems to achieve the same goal.

How would it be any different, in practice?

**Comment by Spacechild1** [comment]
Take a GUI abstraction where the canvas args might only be used for send/receive names and the GUI state is saved with `[savestate]`.

**Comment by porres** [comment]
yeah, I can see I can use both independently, and I hadn't thought of this... and well, that can be useful and abused. But in practical terms, they both work the same way, although independently. You could pretty much do the opposite (use args for the state and use savestate to set send/receive names. Or set both GUI states and send/receive names with either arguments or savestate
