### ISSUE TITLE
request: make pd ask if I want to save changes in the patch when I altered an abstraction

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#833]
So, we have the savestate object, but we can accidentally close the patch without saving something cool we wanted.

Not sure how's the best way to do this, if [savestate] could receive a message for that, or if we could have another functionality in another object (a new object just for this would be silly). As for the second option, maybe a way to abuse dynamic patching and make the abstraction talk to the parent patch (and send it a "dirty 1" message) could do the trick, but it's a rather low level solution. Something like that could be achieved with the same request as https://github.com/pure-data/pure-data/issues/794 - where an object like [pdcontrol] could give us the filename of a parent patch.

The advantage of having a functionality built in somehow in savestate is that it'd be easir. The advantage of the second option is that people could use this to abuse it in other ways.

**Comment by porres** [comment]
For instance, changing parameters in inemguis (color, size, etc) makes pd asks if the user wants to save changes. It'd be interesting if you could have a way to do that for abstractions as well

**Comment by Spacechild1** [comment]
> So, we have the savestate object, but we can accidentally close the patch without saving something cool we wanted.

? Pd already asks if you want to save changes made to an abstraction... what are you missing?

**Comment by porres** [comment]
> ? Pd already asks if you want to save changes made to an abstraction... what are you missing?

I meant like changing parameters, like when it receives data that can be stored. Currently if you mess with your abstraction's parameters, [savestate] won't bother to ask you if you want to save it before closing.

**Comment by porres** [comment]
> For instance, changing parameters in inemguis (color, size, etc) makes pd asks if the user wants to save changes. 

I just saw that this is not true when you change these parameters via messages (say, a "size" message for instance). It feels weird that it asks you if you want to save changes if you altered via the properties but not from messages - but that'd be a separate issue

**Comment by Spacechild1** [comment]
Because the dialog sets the dirty flag, while sending a message to an object doesn't. The rationale is that whenever you change something from the GUI, the canvas gets dirty. On the other hand, changing the internal state of an object with a message obviously doesn't do that. Imagine that changing the value of `[float]` would always set the dirty flag...

If you want to make the canvas dirty when the user changes a certain value, just send `[dirty 1( `to the abstraction itself and you're done.

**Comment by porres** [comment]
I can see it makes no sense for [float] but not for GUIs, but for that I opened a new issue - https://github.com/pure-data/pure-data/issues/834

> If you want to make the canvas dirty when the user changes a certain value, just send [dirty 1( to the abstraction itself and you're done.

that would ask to save the abstraction, not the parent patch containing it, and therefore it wouldn't trigger [savestate] or save things in the parent patch

**Comment by Spacechild1** [comment]
ah yes, it should rather be the parent patch.

**Comment by Spacechild1** [comment]
can you close this PR? this one is confusing and https://github.com/pure-data/pure-data/issues/834 is more on point.

**Comment by porres** [comment]
well, this issue - not a 'PR' :) - is for a generic way for us to manage this in Pd.

The other one just discusses whether we want changes to GUIs via messages to trigger a "dirty 1" (I'm not sure, even though I brought it up).

**Comment by Spacechild1** [comment]
> is for a generic way for us to manage this in Pd.

It's impossible. Pd objects are black-boxes. There's no general way for a patch to know whether one of its objects have changed state.

**Comment by porres** [comment]
> It's impossible.

Thus far it is. But I can see ways to make it possible. I designed an external just for this in my last update of the ELSE library. I think it is silly on its own, and I could probably have used another already existing low level object. The trick would be to manage if certain parameters changed in the abstraction, then the parent gets a 'dirty 1' message.

We have another feature request here - see https://github.com/pure-data/pure-data/issues/794 - it asks for a functionality to get the parent patch file name. Now, if you had that, you could manually send to the patch called "my-main-awesome-live-coding-and-live-changing-patch.pd" that carries the abstraction a "dirty 1" message.

**Comment by Spacechild1** [comment]
> Thus far it is. But I can see ways to make it possible. 

No, not in the general sense as your issue title and description suggests. You have to manually track changing parameters in your abstraction.

> The trick would be to manage if certain parameters changed in the abstraction, then the parent gets a 'dirty 1' message.

So what we *actually* need is a way to send a message to the parent canvas. (iemguts already has such an object). Please close this issue and make a new one.

**Comment by porres** [comment]
> So what we actually need is a way to send a message to the parent canvas.

that's one of the options I enlisted in the description of this issue, in a lower level way, by getting the filename of the parent patch as requested in https://github.com/pure-data/pure-data/issues/794 for a whole other purpose. But I don't know, maybe this could also be part of [savestate].

I could go ahead and make a PR to get the filename with a new [pdcontrol] method.

> Please close this issue and make a new one.

what would this new issue be like? I think the one I opened was pretty on it :/

**Comment by Spacechild1** [comment]
> But I don't know, maybe this could also be part of [savestate].

why?

> I think the one I opened was pretty on it :/

I don't think so because in the issue description you talk a lot about [savestate] and *automatic* notifications (which are not possible, as I've tried to explain). I thought we've agreed that the only way to achieve your goal is to *manually* set the dirty flag, so we need a way to do this. This should be topic of your issue. https://github.com/pure-data/pure-data/issues/794 is not a solution to this.

**Comment by porres** [comment]
> #794 is not a solution to this.

sorry, but how is it not? If I get the parent canvas name, I can send messages to it...

**Comment by porres** [comment]
> If I get the parent canvas name

or if I set the parent's name, with a new functionality to [namecanvas] I proposed

**Comment by porres** [comment]
> why?

why including this in [savestate]? Feels like a higher level solution as this objects manages saving abstractions and all... but lookng at the code, it has nothing to do with this functionality, you'd need to add a whole bunch of code to introduce this thing, so yeah, maybe a lower level function, and more maleable, somehwere else, is better

**Comment by Spacechild1** [comment]
> sorry, but how is it not? If I get the parent canvas name, I can send messages to it...

because of the reasons I've tried to explain 100 times now.

> or if I set the parent's name, with a new functionality to [namecanvas] I proposed

seriously, why do you want to jump through various hoops to achieve a simple thing? I don't get it... the aim is to send a message to a *specific* canvas, and [sendcanvas] offers exactly this functionality, so we should look how we can integrate this *functionality* into Pd vanilla.

**Comment by umlaeute** [comment]
as @Spacechild1 explained, this doesn't seem to be actable in any reasonable way.
closing this until a more thought-thru proposal occurs (although i doubt there is one)

**Comment by porres** [comment]
> this doesn't seem to be actable in any reasonable way.

But why? The reasonable idea is that we can manage the data input to an abstraction and make it trigger the parent patch to ask you if you want to save changes (a.k.a. send a "dirty 1" message to it). The issue is if we can propose this in Vanilla with a new object or with a new functionality into an existing object. I can see many options and different ways.
