### ISSUE TITLE
iemguis make pd ask to save changes with parameters but not messages.

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#834]
When you change iemgui parameters via the properties, Pd asks if you want to save the patch when you try to close it without having saved the changes. But if you change the same parameters with messages, this doesn't happen. I don't know if there's any reasoning behind this or if that happened by mistake.

It feels to me that both changes should require Pd to ask you if you want to save changes.Therefore I'd propose that this also happens when you change parameters via messages.

**Comment by Spacechild1** [comment]
Generally, changing the internal state of an object doesn't affect the dirty state. It's certainly debatable whether this also holds for GUI objects. A simple workaround is to manually send a `[dirty 1(` message to your abstraction.

**Comment by Spacechild1** [comment]
Note that many patches rely on the fact that setting iemgui parameters *doesn't* set the dirty flag. A simple example is setting the label of a canvas as a reaction to some event. In this case you certainly don't want the patch become dirty...

**Comment by porres** [comment]
> It's certainly debatable whether this also holds for GUI objects. 

cool, that's why I brought it up :) 

Lots of these issues came up to me while designing abstraction GUIs (as I can't yet deal with tcl/tk). 

See [else/slider2d] for instance. My last update included a [savechange] external just for this.

[else/slider2d] is based on data structures but has a background [cnv] object

> A simple workaround is to manually send a [dirty 1( message to the canvas which should become dirty.

The deal is that I might want to save changes on the parent, when these parameters are supposed to be saved in the abstraction. Now, [savechange 1] basically sends a 'dirty 1' to the parent. But that's a separate discussion I'm leaving to https://github.com/pure-data/pure-data/issues/833 (which is how to do this in Pd without an external).

Now, here we might think we can always have changes to the GUI trigger a "dirty 1" to the patch. I think it makes sense! But what if we change this and make it always bug you if you want to save the abstraction? Then you can easily manage it by sending a 'dirty 0' message to the abstraction alright...

I actually already do this (send 'dirty 0' to the abstraction) in [else/slider2d]  because of the changes I do in graph on parent and everything, and I thought that's what made changes to the [cnv] GUI object not trigger Pd to ask me if I wanted to save. To my surprise, I now see this never happens.

**Comment by Spacechild1** [comment]
As I've said, you suggestion would break many existing patches...

**Comment by porres** [comment]
> Note that many patches rely on the fact that setting iemgui parameters doesn't set the dirty flag. A simple example is setting the label of a canvas as a reaction to some event. In this case you certainly don't want the patch become dirty...

oops, hadn't read this before my last reply... 

well, one way or another, I think we can leave with this. Either by setting 'dirty 1' or the opposite if things change. But I can see how much of a hassle we'd have to impose on people that relied on this behaviour (which would probably make miller implement another 'compatibility' flag as IOhannes loves so much).

**Comment by porres** [comment]
> As I've said

you reply faster than me :)

**Comment by umlaeute** [comment]
btw this is not about "compatibility" (no matter how much i despise these flags). it's a plain *regression*
