### ISSUE TITLE
disable interaction with Data Structures arrays

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#839]
We now have a way to disable mouse interaction with data structures, but it seems this is not yet possible with arrays and I also think it'd be useful

**Comment by umlaeute** [comment]
related: it would often be handy to have a read-only view ( or multiples thereof) of an array (while maintaining a separate read-write view)

**Comment by porres** [comment]
this has been merged, right @Spacechild1 ? we can close this then

**Comment by porres** [comment]
I'm closing this
