### ISSUE TITLE
"Font" dialog only opens once

### ISSUE THREAD

**Issue by Ant1r** [pure-data/pure-data#85]
On current state (0e32313952953f16a6bb50eb18a087cd92b5cb7c) built for Linux, after Font dialog is closed, the Font entry in the Edit menu is then greyed (for every window).

edit: actually opening most dialogs (preferences, help browser, Find, ...) then disables the Font entry.

**Comment by danomatika** [comment]
This should be fixed in PR #88. The intended behavior is to only allow the Font dialog to be created from the main Pd window or from a canvas dialog, not from any other dialog where it has no effect... at least that's what I've gathered. I can double check.

**Comment by danomatika** [comment]
Whoops, ignore the commit reference above.

**Comment by danomatika** [comment]
Ok, I think I see it. The menu entry is not being re-enabled when the Pd window comes back into focus.

**Comment by danomatika** [comment]
Fixed in 9b49abb. Please test.

**Comment by Ant1r** [comment]
Excellent, this works, thanks !
