### ISSUE TITLE
bug in [jmmmp/matrixctrl] - only one object per pd session allowed

### ISSUE THREAD

**Issue by jmmmp** [pure-data/pure-data#850]
This is the first time I see something like this: the object [jmmmp/matrixctrl] can only be created once in a pd session. After the first time, any other instance will appear as text (no gui); if something is sent to it, it behaves as [zexy/lister] - including opening its help patch when requested. (Btw, lister isn't used in this abstraction)

I installed many pd versions, and found out that the last version where this works is pd-0.46-7 - in windows 7.

Is it possible to track down what changed? This object uses zexy, iemmatrix and list-abs.

(matrixctrl is a pd abstraction emulating the same object in max/msp, to control mtx_*~)

**Comment by umlaeute** [comment]
this sounds like some memory corruption.
which libraries are loaded? what happens if you don't load any libraries? ...

**Comment by jmmmp** [comment]
> this sounds like some memory corruption.
> which libraries are loaded? what happens if you don't load any libraries?
> ...
>
there's only [declare -stdlib iemmatrix -stdlib zexy], and there was also a
[iemmatrix] object (I guess I had to put it there for some reason).

After trying different combinations, the issue is with -stdlib zexy. When
that isn't loaded in the abstractions, the GUI is ok. If zexy is loaded
before opening of the abstractions, everything works.

I'm using the current version, 2.2.8.



Another small bug, probably already noticed:
- open matrixctrl-help
- in [pd SIZE+CELLSIZE], click on [size 2 4(, and then [size 2 3( . The
structs outside of the GOP canvas will still be visible, until the subpatch
is redrawn (minimize+maximize, etc.)

**Comment by umlaeute** [comment]
please do not add "other small bugs" to this bug-report (unless you are very confident that they are indeed the *same* bug)

**Comment by umlaeute** [comment]
note to myself: it seems that the problem is, that `class_loadsym` ought to be pushed to a stack rather instead of a single global variable: https://github.com/pure-data/pure-data/blob/628a8d3464a45f25ea3bbd4fbd76655f28ce825e/src/m_class.c#L898-L907

and then: https://github.com/pure-data/pure-data/blob/628a8d3464a45f25ea3bbd4fbd76655f28ce825e/src/m_class.c#L458-L469

**Comment by jmmmp** [comment]
Any prediction on when that zexy issue will be solved? I might release a new version of jmmmp soonish, if it's worth waiting I can do it.

**Comment by jmmmp** [comment]
This issue is marked as solved, but I just updated zexy, and [matrixctrl] doesn't work. Tested on windows 32b+64b.

**Comment by umlaeute** [comment]
that's because the issue is really an issue in Pd and not in zexy.
and Pd-0.51 (which has the fix) is not yet released.

the ticket was closed automatically when the fix was merged into the `master` branch of the repository.

**Comment by Ant1r** [comment]
It seems the bug was in Pd, so you have to wait next Pd release is out, or
to compile latest sources by yourself.
