### ISSUE TITLE
create (or adapt) [value] for other data types

### ISSUE THREAD

**Issue by jmmmp** [pure-data/pure-data#852]
[value] is useful in some specific contexts. It would also be interesting to have an object that does the same with lists and symbols (maybe even gpointers).
One idea could be to extend [value] to accept all those data types; another would be to create new objects that are specific to each data type.

**Comment by porres** [comment]
see https://github.com/pure-data/pure-data/pull/817 and https://github.com/pure-data/pure-data/pull/827

**Comment by porres** [comment]
you don't have to close it :)
