### ISSUE TITLE
[drawnumber] keyboard interaction

### ISSUE THREAD

**Issue by jmmmp** [pure-data/pure-data#854]
On [drawnumber]'s help file it's mentioned "Keyboard entry isn't supported yet."
Only, keyboard entry has been available for a long time, only with integers >= 0. Improving the keyboard interaction to be similar to an atom would make the behaviour more coherent:
- click + keyboard entry allowed for any float (also < 0)
- click+drag+shift would move the value in the 0.0x of a number. (click+drag is already allowed for integers including < 0)

Keyboard entry for symbols drawn with this object would also be nice (same behaviour as a symbol atom).

**Comment by porres** [comment]
> On [drawnumber]'s help file it's mentioned "Keyboard entry isn't supported yet." Only, keyboard entry has been available for a long time

this has been fixed in the documentation. Other than this, we can maybe close this issue and keep this one instead? => https://github.com/pure-data/pure-data/issues/1489

**Comment by porres** [comment]
closing in favor of https://github.com/pure-data/pure-data/issues/1489
