### ISSUE TITLE
Tcl error bad screen distance "88.000000"

### ISSUE THREAD

**Issue by mxa** [pure-data/pure-data#859]
I have something strange going on with Pd (0.50 on Linux kubuntu 19.10) It was working before, but now when I open the Test Audio MIDI patch it shows an empty canvas with just one numberbox in it and this error:

```

(Tcl) UNHANDLED ERROR: bad screen distance "88.000000"
    while executing
"$tkcanvas create text $x $y -tags $tags  -text [::pdtk_text::unescape $text]  -fill $color -anchor nw -font [get_font_for_size $font_size]"
    (procedure "pdtk_text_new" line 2)
    invoked from within
"pdtk_text_new .x5627d7726b80.c {.x5627d7726b80.t5627d7783760 atom text} 88.000000 276.000000 {0 } 12 black"
    ("uplevel" body line 9)
    invoked from within
"uplevel #0 $docmds"
```

I then cloned the git version and compiled and installed it to see if that would change anything but it's the same error. I have also tried `pd -noprefs`

**Comment by clwe** [comment]
![puredata_tcl](https://user-images.githubusercontent.com/9591738/71771374-13803780-2f3a-11ea-8068-b61f86eca7b4.gif)

**Comment by umlaeute** [comment]
unable to reproduce.
what's the window-manager, X-server,...?
what did you change on your system to make the problem appear?

**Comment by clwe** [comment]
The window manager is KWin, X-server is Xorg. Unfortunately I don't know if i changed anything to the system that could have caused the issue.

**Comment by clwe** [comment]
solved by removing old fontconfig!
