### ISSUE TITLE
Move to more modern defaults for compile configuration

### ISSUE THREAD

**Issue by mxa** [pure-data/pure-data#860]
On Linux, Pd still configures by default with support for legacy backends like OSS MIDI (Rumor has it Miller is the last user) but no Jack support. I would argue that it adds to the ease of use if we would not compile support for legacy backends but add more modern ones like Jack by default.

**Comment by umlaeute** [comment]
> OSS MIDI (Rumor has it Miller is the last user)

so? even if miller *is* the last user, this is a valid use-case to *do* support such old backends (and even a valid argument for selecting this as the default).

> but add more modern ones like Jack by default.

which ones?


PS: could you make the title more specific? "configuration" made me think of run-time configuration (aka `.pdsettings`), but the body drifted towards very specific compile-time configurations.

**Comment by mxa** [comment]
It's just that I see a lot of users being confused by OSS MIDI like here: https://community.blokas.io/t/pure-data-midi-ports-issue/450 and questions about Jack support on the Pd list.
Anyway, the more I think about it maybe it can also be solved by the tabbed preferences redesign.

**Comment by umlaeute** [comment]
> the more I think about it maybe it can also be solved by the tabbed preferences redesign.

how? why would users be less confused about compile-time configurations if the midi-preferences were in a tabbed window?

it seems like you are mixing up two different problems (even though they might be related)

**Comment by mxa** [comment]
They are related but I am not mixing them up.

**Comment by umlaeute** [comment]
closing this until it becomes clear what this issue is about (i'm not trying to dismiss this issue, but with itscurrent description i dont think its actionable...)
