### ISSUE TITLE
bug in 'dir' method in [pdcontrol], macOS

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#863]
Hi on mascOS 10.14.6, I get  _"symbol /Applications/Pd-0.51-0.app/Contents/Resources/Scripts/../doc/5.reference"_ when trying the 'dir' method in the help file of [pdcontrol].

This should actually be  symbol _/Applications/Pd-0.51-0.app/Contents/Resources/doc/5.reference_ and I don't understand why it goes into 'Scripts/' and then out of it to the right place

**Comment by umlaeute** [comment]
where is the bug?

from a file-system perspective, `/Applications/Pd-0.51-0.app/Contents/Resources/Scripts/../doc/5.reference` and `/Applications/Pd-0.51-0.app/Contents/Resources/doc/5.reference` are equivalent.
