### ISSUE TITLE
horizontal slider shortcut is not consistent (Linux)

### ISSUE THREAD

**Issue by Ant1r** [pure-data/pure-data#87]
In the Add menu, the shortcut for horizontal slider is said to be Shift-Ctrl-G (which is actually Graph's shortcut), while it's still (fortunately...) Shift-Ctrl-H.

**Comment by danomatika** [comment]
Good catch. The menu key accelerator is showing the wrong hotkeys. Fix coming...

**Comment by danomatika** [comment]
Fixed in 752e27b.
