### ISSUE TITLE
[netreceive] OSC crash

### ISSUE THREAD

**Issue by oliverstotz** [pure-data/pure-data#877]
hi,

i just experienced crash-scenario with [netreceive-u -b]

it happens when i send lots of OSC data (from MAX in that case) too fast to PD with the vanilla [netreceive] object as receiver. "too fast" means that i dumped a huge list of camera formats (~ 50 symbols) all at once to OSC.

there's no crash when i use IEMNET's [udpreceive] instead !

tested on PD 0.48 - 0.50 on a Windows 7 / 64bit system

best

oliver

**Comment by Spacechild1** [comment]
Hey, can you try with the latest master branch? Dan and I have rewritten all the network objects, so maybe this has already been fixed. If not, I'll make a PR.

**Comment by Spacechild1** [comment]
@oliverstotz what's the state of this, could you test already?

**Comment by Spacechild1** [comment]
The latest networking updates seemed to have fixed this issue, as @oliverstotz confirmed in a private message.
