### ISSUE TITLE
weird characters like "[" (as label) hang iemgui properties

### ISSUE THREAD

**Issue by SynchromaAE** [pure-data/pure-data#880]
It seems that this arrangement causes problems:

a canvas, with a label far outside (to the top-right) but with a really large font size - or is it to do with the use of '[' as a label?
Right-click on the canvas object handle and select properties, pd freezes completely and you cannot do anything, and have to kill Pd.

Pd-0.50.2, Linux, Debian 9, 64 bit, intel
![largeFontCanvasBug](https://user-images.githubusercontent.com/38653642/73366365-bf9d1000-42a5-11ea-87e7-ec98ece402e0.png)

[largeFontCanvasBug.pd.zip](https://github.com/pure-data/pure-data/files/4128587/largeFontCanvasBug.pd.zip)

**Comment by umlaeute** [comment]
the problem is really only about using  `[` in the iemgui labels.
(the size and offset has nothing to do with it).

the fix itself is trivial (just put curly-braces around symbols when sending a message to the GUI to create the iemgui dialog).
but to get it properly done, iemgui's would need a real refactoring...

**Comment by porres** [comment]
> the fix itself is trivial (just put curly-braces around symbols when sending a message to the GUI to create the iemgui dialog).
> but to get it properly done, iemgui's would need a real refactoring...

please elaborate, what kind of refactoring?

**Comment by porres** [comment]
> just put curly-braces

do you mean using curly-braces in the patch itself? Cause that is not yet possible, though desirable (see https://github.com/pure-data/pure-data/issues/505 ). Or do you mean inside the code?

**Comment by umlaeute** [comment]
no

**Comment by porres** [comment]
> no

which question exactly is this answer for? Is it for "do you mean using curly-braces in the patch itself?"

**Comment by umlaeute** [comment]
updated my comment

**Comment by porres** [comment]
is this a possible duplicate? => https://github.com/pure-data/pure-data/issues/417

**Comment by umlaeute** [comment]
not really (they are somewhat related)
