### ISSUE TITLE
Feature: A hotkey to hide all cable connections

### ISSUE THREAD

**Issue by muziker** [pure-data/pure-data#882]
Can we have a hot key that will hide all cable connections? That way it's easier to focus on just the ones to connect with.

**Comment by umlaeute** [comment]
how about: automatically graying out connections during connecting (but not hiding completely)

**Comment by muziker** [comment]
yes that would be great

**Comment by jmmmp** [comment]
this could also be solved as part of a patch modding plugin, where each user could choose its own color scheme etc.
