### ISSUE TITLE
Improve wording on "can't connect signal outlet to control inlet" and "signal outlet connect to nonsignal inlet (ignored)"

### ISSUE THREAD

**Issue by musger** [pure-data/pure-data#889]
Could these error messages be rephrased as 
"can't connect signal outlet to message inlet"
and
"signal outlet connected to message inlet (connection ignored)"
respectively (with "connect" possibly changed to "connected")?

It would make the mismatch between signals and messages easier to grasp by not introducing the terms of "control" and "non-signal" inlets. I have made the experience that novices to Pd and computer music often seem to wonder what a control or non-signal inlet is and what got ignored.

**Comment by porres** [comment]
I think this is not part of a 'documentation' tag.

I also think that 'control inlet' is a widely known term in Pd, it is used, for instance, in the help file of 'inlet'.

**Comment by musger** [comment]
* porres ***@***.***> [2021-11-17 21:34]:
> I think this is not part of a 'documentation' tag.
> 
> I also think that 'control inlet' is a widely known term in Pd, it is used, for instance, in the help file of 'inlet'.
The current wording is improvable because any inlet, also a signal
inlet, can be considered an inlet that "controls" something. And because
it takes more brain load for newcomers to Pd to understand the error
message (which they should be allowed to do without any obstacles).

**Comment by porres** [comment]
Well, again, the concept of "control" vs "signal" is something very very basic and deeply embedded in the documentation of Pd. Any basic Pd tutorial will make the distintion between 'control' objects and 'signal' objects, and we even have two separate tutorials in Pd's documentation, one that clearly states "2.control.examples", meaning "this doesn't handle audio". 

By the way, this is not only in Pd. Csound has "control rate" and "audio rate", so does SuperCollider, not to mention MAX and MAX/MSP (Control/Audio)...

If newcomers are getting thrown off by this idea, maybe it's worth explaining the concept to them...

And perhaps I should have used more examples and not only the fact that 'control' is also mentioned in the documentation of inlet.

So, anyway, I don't think we need to change or stop using 'control' for what it implies. Regarding these two messages, I think they can maybe be standardized as to not use two different terms ('control' and 'nonsignal').

**Comment by porres** [comment]
from Pd's Manual, at the very start...

--------------------------------------------

This patch mixes **control objects** (notein, stripnote, and ftom) with tilde objects osc~, *~, and dac~. **The control objects carry out their function sporadically**, as a result of one or more type of event . In this case, incoming MIDI note messages set off the control computation. The result of the computation is, when the note happens to be a "note on" (and not a "note off", to compute the frequency in cycles per second and pass it on to the oscillator ("osc~").

The second half of the patch, the osc~, *~, and dac~ objects, compute audio samples, in the same way as an analog synthesizer works. The osc~ object is acting as the interface between the two regimes, in that it takes control messages to set its frequency but talks to "*~" using an audio signal. Audio signals aren't sporadic; they are continuous streams of numbers. As a result tilde objects act under very different rules from control objects. The audio portion of the patch is always running, whether MIDI messages arrive or not. **On the other hand, the function of control computations is to insert calculations between the audio computation** which may change audio computation parameters such as the frequency of an oscillator.

**The connections in the patch (the lines between the boxes) are also of two types: control and signal.** The type of connection depends on the outlet it comes from. **Signal connections are represented by thicker lines than control connections; in the patch above, the two bottom connections are signal and the others are control. In general, a control connection may be made to a signal inlet; if numbers are sent over it they are automatically converted to signals. Signal connections may not be made to control inlets; some sort of explicit conversion must be specified.**

**Comment by porres** [comment]
I made changes to standardize the errors, instead of control, I'm using 'nonsignal' to conform with the other error. I don't agree we should use "message inlet" instead as I think 'nonsignal' is pretty clear and also because 'control' instead of message should really be fine.

I still don't agree this issue should be tagged as 'documentation' but I took care of it in a commit under my documentation updates branch.

**Comment by musger** [comment]
In Pd there is a differentiation between message and signal, not between
control and signal. This is contrary to computer music languages that
differentiate between a fixed periodical control rate, and an audio
rate. As far as I understand, Pd does not do this. In Pd people talk
about messages and signals, and the error messages should be improved to
reflect this as closely as possible. Hence this issue.

* porres ***@***.***> [2021-11-18 00:29]:

**Comment by Ant1r** [comment]
> Pd does not do this

well, "control" messages are sampled at SR/64, which is kind of a "fixed control rate" (although not "periodical")...

I agree with @porres that 'control vs signal' is a very well established terminology.

Of course they could also have been called 'message' and 'audio', which might have been more accurate, but I'm not sure it's worth changing that now.

**Comment by Spacechild1** [comment]
@musger is correct in that Pd has no control *rate*. After all, messages can be sent at any time and at any rate.

However, as @porres has shown, Miller himself speaks of control objects/inlets/outlets/connections. I think this is not really wrong. I think he word 'control'  has a slightly different meaning as, for example, in SuperCollider. I guess "message inlet" would be more appropriate, but I'm not sure if this is an established term in Pd's documentation?

**Comment by Spacechild1** [comment]
> well, "control" messages are sampled at SR/64, which is kind of a "fixed control rate" (although not "periodical")...

Not true! Messages can be sent at any time and at any rate. Many receiving DSP objects "sample" the values at each DSP tick, but not all of them, see `[vline~]` (which is even subsample accurate).

**Comment by Ant1r** [comment]
Well I don't think that [vline~] actually receives any message between block boundaries... It just schedules a waveform in the audio domain, but this waveform can only be modified at "control rate" ; Pd processes every `clock_delay()` and other "control" events only at each 64-samples tick.
But you already know all this ;-) Am I misunderstanding something?

**Comment by Spacechild1** [comment]
> Pd processes every clock_delay() and other "control" events only at each 64-samples tick.

Yes, but for each clock Pd would also set the current logical time to create the illusion of continuous time. Message receivers can query the current logical time with `clock_getlogicaltime`. So the message system itself is not bound to any kind of quantization. It is only that most DSP objects ignore the logical time and just sample the most recent value. `[vline~]`, however, takes the actual logical time in account. With `[metro]` + `[vline~]` you can build a subsample accurate oscillator! `[vline~]` can also be used for subsample accurate granular synthesis. Any many more things.

Another example: the `[param_set(` method and all the `[midi(` methods of `[vstplugin~]` take the logical time into account and are therefore sample accurate!

**Comment by Ant1r** [comment]
OK! Thanks for the clarification, I wasn't aware of `clock_getlogicaltime()`. I understand now that we cannot speak of a sampling rate for "control" messages.

**Comment by musger** [comment]
* Christof Ressi ***@***.***> [2021-11-18 12:21]:
> @musger is correct in that Pd has no control *rate*. After all, messages can be sent at any time and at any rate.
> 
> However, as @porres has shown, Miller himself speaks of control objects/inlets/outlets/connections. I think this is not really wrong. I think he word 'control'  has a slightly different meaning as, for example, in SuperCollider. I guess "message inlet" would be more appropriate, but I'm not sure if this is an established term in Pd's documentation?
I think the term "control signal" it is borrowed from modular synthesis
and denotes a signal that does not become audible per se, but controls
aspects of other modules. This is probably why it is used in the help
patches. If we want users to easily be(come) aware of illegal mixups between
messages and signals, we could simplify things by calling it message and
signal, regardless of what they carry or mean (my original suggestion
for this issue).

**Comment by Spacechild1** [comment]
> I think the term "control signal" it is borrowed from modular synthesis

I am not so sure. Originally, Max didn't have DSP objects, it only generated messages - to control things. But I guess only Miller can give a definite answer :-)

**Comment by porres** [comment]
I just wanted to say I was aware that Pd has no 'control rate' per se, but that the same terminology/distinction is present in other computer languages.

Now, it's worth noting that even though Pd has no fixed sample rate and you can do crazy things with [vline~], for instance, in practice, the behaviour of vline~ is the exception and we do have a block size restriction when using control data in tilde objects. Setting the frequency in lop~ only accounts for one value per block. The same is true for [sig~].

Now, what are we discussing anyway right now? :) I made the change so we now have consistency between the messages and I'm using signal vs nonsignal.  Is that ok? Does this settle this?

> I guess "message inlet" might be more appropriate, but I'm not sure if this is an established term in Pd's documentation?

Nope, that's what I've been saying. We do have 'control inlet' instead. 

So, do we really want to make the case that we should use the message term instead in detriment of a pretty well established and documented 'control' concept, used for things like 'control inlet', 'control connections', 'control objects', the 'control' section of Pd's tutorial?

**Comment by musger** [comment]
I think that "message inlet" is the most appropriate description, and
much less confusing than "non-signal". After all signal inlets are not
called "non-message" either. There might have been a reason for
"non-signal" which may also include OpenGL pointers, but they can also
be considered messages perhaps. We are discussing the original
suggestion of rephrasing two error messages, and my goal is to make it
as easy as possible to understand for people who start with Pd (and are
hence getting a lot of these messages).

* porres ***@***.***> [2021-11-18 16:04]:

**Comment by porres** [comment]
If 'nonsignal' is also problematic, I guess I prefer 'control inlet', which is well documented and, because of that, shouldn't really be a problem at all, despite anyone feeling bad about it. 

You're insisting that you just don't like this, despite all of the arguments and the implications that we should change Pd's documentation accordingly... simply no word about that so I don't know if you're just ignoring for the sake of stubbornness or something. Please consider the implications and suggest and propose something. We know how you feel from the start, it's not about that.

This also feels like enough bikeshedding for me. I got other priorities in tweaking and changing Pd's documentation, so I won't touch this reorganization of a pretty established 'control' concept in favour of a new **'message' vs 'signal'** paradigm... but you can go ahead and propose changes yourself. 

cheers.

**Comment by Spacechild1** [comment]
I think @porres was a bit too harsh in his last message, but I agree that "control" is a pretty established term throughout the documentation. There even is a whole section called "control" in the manual, as @porres correctly pointed out.

"control" in Pd might not mean the same as "control" in SC, but that is expected. Neither does "control" in the context of modular synthesis, where it means something entirely different.

If you learn something new, you often have to learn new vocabulary. If you start with Pd, it is a good idea to read through the manual. After that, there shouldn't be any misunderstanding about what "control" means in the context of Pd.

**Comment by musger** [comment]
Christof,

thank you. It is my experience that newcomers don't read through the
manual first but will jump into patching in some way or another.
Although the term control is used in some documentation, it is not
conceptually wrong to use "message" in error messages if it improves
understandability. I would prefer this over ultimate consistency, but
have possibly explained this one too many times already.

* Christof Ressi ***@***.***> [2021-11-18 23:17]:

**Comment by Spacechild1** [comment]
I can just repeat: the term "message inlet" is not established in the documentation and it doesn't make sense to introduce it only at one place. You would really have to change the whole documentation.

> It is my experience that newcomers don't read through the manual first but will jump into patching in some way or another.

I can totally see that. However, if a user didn't have a look at any documentation, then it probably doesn't matter if the error message says "message" or "control". How would they even know what a "message" is? ;-)

Anyway, I think "non-signal" is the most clear term. One the other hand, how would they know what a "signal" is? :-p
