### ISSUE TITLE
[list store] bug in Pd-double

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pure-data#907]
See this test patch:

[liststore-double-bug.zip](https://github.com/pure-data/pure-data/files/4328174/liststore-double-bug.zip)

![liststore-double-bug](https://user-images.githubusercontent.com/25239522/76595763-4830e200-64db-11ea-8787-7ae7260314bc.png)

**Comment by umlaeute** [comment]
confirmed

**Comment by umlaeute** [comment]
fixed in `update/0.50`

**Comment by umlaeute** [comment]
...along with some other similar issues.
