### ISSUE TITLE
replace `ANDROID` preprocessor define with `__ANDROID__`

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#909]
Pd uses the `ANDROID` define in a couple of places (*d_array.c, d_osc.c, s_file.c, s_loader.c, x_misc.c*)

However, it seems that compilers for the android platform automatically define the `__ANDROID__` macro (and the `ANDROID` macro must be manually defined).

So the question is: shouldn't `ANDROID` be replaced with `__ANDROID__`?

pinging @chr15m & @danomatika

**Comment by danomatika** [comment]
If that is the declared platform define (ala `__APPLE_`), then you should. Anyone who relies on it should update their code.

**Comment by umlaeute** [comment]
so far `ANDROID` is only used internally in Pd, so externals using it would have to define it manually anyhow (that is: we don't need to care; they should update nevertheless :-))

**Comment by umlaeute** [comment]
i just found https://stackoverflow.com/a/28240165/1169096, which suggests that `ANDROID` is indeed the define to use.
:shrug:

**Comment by danomatika** [comment]
From that link, it seems it can be both.
