### ISSUE TITLE
Can't input tilde ~ character

### ISSUE THREAD

**Issue by haugan** [pure-data/pure-data#913]
I'm on Windows 10, updated - with a Norwegian keyboard layout. When attempting to input a tilde character, I get nothing (just a blank space). What can I do to fix this?

**Comment by umlaeute** [comment]
which version of Pd is this (exactly)?

how do you type the <kbd>~</kbd> on a Norwegian keyboard layout?

see also #732

**Comment by haugan** [comment]
It's the 0.50.0 version, and the Norwegian keyboard layout looks [like this](https://en.wikipedia.org/wiki/File:Keyboard_Layout_Norwegian.png); the tilde ~ is written by holding AltGr and pressing the button you see by following the Enter arrow (directly left).

**Comment by umlaeute** [comment]
fixed with #736, so you should upgrade to **Pd-0.50-2**

(really, you should always make sure to have the last bug-fix version installed to see whether your problem has already been fixed)

**Comment by haugan** [comment]
Ok, seems like https://puredata.info/downloads/pure-data isn't updated then. Cheerio!

**Comment by porres** [comment]
> seems like https://puredata.info/downloads/pure-data isn't updated then.

it's not, but it's also noted it might be, always check: http://msp.ucsd.edu/software.html

<img width="669" alt="Screen Shot 2020-03-24 at 09 03 48" src="https://user-images.githubusercontent.com/5360142/77423676-83ba8e80-6dae-11ea-9ba7-0d5176187004.png">

**Comment by umlaeute** [comment]
> Ok, seems like https://puredata.info/downloads/pure-data isn't updated then. Cheerio!

thanks for the reminder. fixed.

**Comment by haugan** [comment]
Congrats, only took 7 months!
