### ISSUE TITLE
inlet/outlet, font and object size inconsistency for iemguis 

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#920]
The inlet/outlet for iemguis is a bit smaller 

EDIT: general height of the iemguis could also match atom boxes and objects

EDIT 2: Default font size could also be the same as Pd's default (12)

**Comment by danomatika** [comment]
I actually implemented this when I did the gui overhaul a couple of years ago, but changed it back. The main reason was that larger IOs cover up too much of the actual UI behind them.

If you want to try it, change `IEM_GUI_IOHEIGHT` to 3 in `src/g_all_guis.h`.

**Comment by porres** [comment]
I'm giving it a try, when checking the new knob GUI, it really felt unnatural, and then I realized how the others were also "small", but I haven't tested yet with the new size...

**Comment by Ant1r** [comment]
I agree with @porres . 
`IEM_GUI_IOHEIGHT = 3` doesn't hurt my eyes...

**Comment by danomatika** [comment]
Don't get me wrong, I'm not against the idea.

At the time, it seems like too much a change to push through due to all of the other updates I did, so I turned it back off but kept the define for easy switching. :)

Ideally, that line would be:

```c
#define IEM_GUI_IOHEIGHT IOHEIGHT
```

**Comment by danomatika** [comment]
For comparison's sake, here are screenshots from @Ant1r's knob PR.

IEM_GUI_IOHEIGHT = 2 (current, gem guis have slimmer IOs):

<img width="911" alt="Screen Shot 2020-04-17 at 5 45 17 PM" src="https://user-images.githubusercontent.com/480637/79587902-7fdf0b00-80d3-11ea-8fe1-453f854df0be.png">

IEM_GUI_IOHEIGHT = 3 (iem guis matching objects & atoms):

<img width="911" alt="Screen Shot 2020-04-17 at 5 46 12 PM" src="https://user-images.githubusercontent.com/480637/79587988-9dac7000-80d3-11ea-9405-d65a83ec2eea.png">

**Comment by danomatika** [comment]
One aspect, for instance, is that the radio's default size now has the selection rect touching the IOs when height = 3. I think that was one of the bigger reasons I held off before.

**Comment by porres** [comment]
> Ideally, that line would be:
> #define IEM_GUI_IOHEIGHT IOHEIGHT

done with https://github.com/pure-data/pure-data/pull/946/commits/e3864ac74a8875529f5a4f9718cf970cef8e70c1

Well, now I actually tested this myself (thanks for the image, by the way). It really doesn't hurt my eyes and looks quite good specially in sliders/vu. But anyway, truth is I'm usually bummed out by inlet/outlets and tend to insert dummy send/receive names just to hide them. radio buttons seem to suffer a bit, but only in smaller GUIs, bigger ones look good.

**Comment by porres** [comment]
> radio's default size now has the selection rect touching the IOs when height = 3

yeah, that's what I was talking about :)

**Comment by danomatika** [comment]
One approach would be to bump up the default size of some of the guis slightly, say to 18 or 20.

**Comment by porres** [comment]
> One approach would be to bump up the default size of some of the guis slightly, say to 18 or 20.

I was thinking about that and testing things. It's funny, cause if you increase it just by one (16 instead of 15), it already doesn't cause the same issue.

**Comment by porres** [comment]
> an hslider with height 18 is the same height as a default float atom.

good selling point

**Comment by porres** [comment]
> Also on my system, a number2 with height 18 and font size 12 is the same height and has a similar font size as a default float atom, although it is naturally wider.

I was thinkning if the idea was to change just the radio size... but maybe we can think about changing IEM_GUI_DEFAULTSIZE to 18 instead of 15?

**Comment by porres** [comment]
> Ideally, that line would be:
> #define IEM_GUI_IOHEIGHT IOHEIGHT

As it turns out, we don't have "IOHEIGHT", but both IHEIGHT & OHEIGHT...

Since both IHEIGHT and OHEIGHT now have the same size, maybe they should be merged into a single IOHEIGHT variable...

But now I guess I'll just go back to "IEM_GUI_IOHEIGHT = 3"

**Comment by porres** [comment]
> a number2 with height 18 and font size 12 is the same height

Side notes here: Font size only changes width (and it was probably good that height would define font size), number2 also seems to have an unnecessary wider space that is unfilled - but changing this might be drastic and compromise patches that meticulously rely on the size. Not sure how to deal with this.

Enough diversion. Now, one thing I noticed is that number2 doesn't use IEM_GUI_DEFAULTSIZE, and has a default size of "14" instead.

Anyway, here's how things look, with IEM_GUI_DEFAULTSIZE of 18 - note that number box is also set with height 18 and font size of 12 (manually)

What jumps to my eye is the sliders, that look thicker, because this just changes one of the dimensions. Perhaps it can be made longer to match the size of radio buttons (139 instead of the default of 128)

<img width="483" alt="Screen Shot 2020-04-17 at 14 08 08" src="https://user-images.githubusercontent.com/5360142/79595449-439cb200-80b5-11ea-9c44-e10a5bb80e6d.png">

**Comment by danomatika** [comment]
Sliders and radios are already a different size with a default of 15, except sliders are longer. I wouldn't worry about that as "139" is a seemingly arbitrary size. I would leave it 128.

<img width="520" alt="Screen Shot 2020-04-17 at 7 33 48 PM" src="https://user-images.githubusercontent.com/480637/79597456-96d92980-80e2-11ea-943c-a121c339e181.png">

**Comment by porres** [comment]
> I wouldn't worry about that as "139" is a seemingly arbitrary size. I would leave it 128.

Ok then, making a new commit for the new IEM_GUI_DEFAULTSIZE of 18, and also use that on number2 (plus font size being default to 12)

I guess the slider size change is just more noticeable, but it's not like you can't change it, and it might be a matter of getting used to it, and now that I think of it, I usually change sliders size all the time, and 15 actually seems too thin...

**Comment by danomatika** [comment]
>I guess the slider size change is just more noticeable, but it's not like you can't change it, and it might be a matter of getting used to it

I thought the same of your default font size to 12 form the last release, but I got used to it.

**Comment by porres** [comment]
Note this won't affect the knob PR ( https://github.com/pure-data/pure-data/pull/938 ) as it doesn't use IEM_GUI_DEFAULTSIZE - which is reasonable, as it's not like every GUI in the world should have the same size, knob should have its own.

> I thought the same of your default font size to 12 from the last release, but I got used to it.

I now realize we can change the default font size for labels in iemguis for 12 as well, let's do it

**Comment by porres** [comment]
> I now realize we can change the default font size for labels in iemguis for 12 as well, let's do it

Just did this, added a new "IEM_DEFFONT_SIZE" in g_all_guis.h, now GUI labels are the same size as Atom labels by default... I also changed the default label position a bit so it best fits the new default sizes. I also changed vu's default height so it fits better with the default font size (but I could make that one the odd one out and make it back to a default size of 10).

Here's a screenshot:

<img width="672" alt="Screen Shot 2020-04-17 at 16 59 30" src="https://user-images.githubusercontent.com/5360142/79609550-54592200-80cd-11ea-841d-b4a4f38a1a53.png">

**Comment by danomatika** [comment]
I think the vu label is too high.

>I now realize we can change the default font size for labels in iemguis for 12 as well, let's do it

This is what I meant by changing number2's font size.

**Comment by porres** [comment]
> I think the vu label is too high.

I'll change it

**Comment by porres** [comment]
> I think the vu label is too high.

how about this (-13 instead of -18)? I guess that's the limit

<img width="624" alt="Screen Shot 2020-04-17 at 20 08 15" src="https://user-images.githubusercontent.com/5360142/79620737-41ebe200-80e7-11ea-8abb-cda5d1da7304.png">

**Comment by danomatika** [comment]
-12?

**Comment by porres** [comment]
> -12?

<img width="631" alt="Screen Shot 2020-04-17 at 20 11 47" src="https://user-images.githubusercontent.com/5360142/79620837-b1fa6800-80e7-11ea-9c8b-a31b4375c3b7.png">

**Comment by porres** [comment]
Actually, I'm uploading the wrong image, the label positions I have are different and better centered for toggles and bangs with their new size....

here's also with a "-12" y offset fot the vu label. 

Approved?

<img width="630" alt="Screen Shot 2020-04-17 at 20 13 13" src="https://user-images.githubusercontent.com/5360142/79620937-043b8900-80e8-11ea-86fa-c1e58c1e5244.png">

**Comment by porres** [comment]
I still think -13 is the limit for [vu] :)

**Comment by porres** [comment]
> I still think -13 is the limit for [vu] :)

but I don't really care!

**Comment by danomatika** [comment]
I'm looking at the vertical distance between the bottom of the vu label and the top of the vu ">+12" and comparing it to the bottom of the radio label and top of the vradio.

**Comment by porres** [comment]
> I'm looking at the vertical distance between the bottom of the vu label and the top of the vu ">+12" and comparing it to the bottom of the radio label and top of the vradio.

I'll take this as "yes, -12 please"

**Comment by danomatika** [comment]
If you see what I mean and agree, then yes.

**Comment by porres** [comment]
-12 is done with https://github.com/pure-data/pure-data/pull/946/commits/cd2abda9820f7711c3334079a54e433a3f382f34

**Comment by porres** [comment]
I'm thinking now about changing the label offset so it's always on top. And this way you can set the object to any size and always have a label that doesn't collide with the object size. Most of the time we don't care much where it is and need to move it just so it doesn't collide with the object.

<img width="267" alt="Screen Shot 2020-05-07 at 18 04 52" src="https://user-images.githubusercontent.com/5360142/81344518-44f64480-908d-11ea-81ff-227553434d99.png">
