### ISSUE TITLE
Feature Request, Inteligent Patching. "Backwards" Autopatch 

### ISSUE THREAD

**Issue by abreubacelar** [pure-data/pure-data#921]
Hello all, i was just thinking, autopatch is amazing, but only works down, you can create objects going down and that's nice to go fast. But sometimes, we think from bottom up, and then we have to go and connect everything manually.

How about, if and **Only If,** there is nothing connected in first inlet, something like ctrl + shift + 1, makes auto patch up? it could work for 

ctrl + shift + 1, object up
ctrl + shift + 2, message up
ctrl + shift + 3, number box up
ctrl + shift + 4, symbol up

since this would only work If and Only if there is nothing connected up, this would only be useful if you are starting the "chain" of objects, just as fast as we already go with autopatch, but in the inverse direction

what do you think? 

and of course, this has to work just as the same as autopatch, the object you want to do this has to be selected

**Comment by umlaeute** [comment]
see #869

**Comment by abreubacelar** [comment]
oh, amazing! so i will close my issue, sorry for the noise. This new way of navigating inlets would suffice, haha. Thanks for all hard work!
