### ISSUE TITLE
When I build Pd, I get torubles that are probably realated with casting float to int.

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#927]
When I build PD from source on macOS (like the new 0.51-0 test1]), I get this error when I try had the value of 1+e16 for the line number in [text insert]. A related closed issue by thew way: https://github.com/pure-data/pure-data/issues/848

<img width="715" alt="Screen Shot 2020-04-09 at 16 21 30" src="https://user-images.githubusercontent.com/5360142/78932721-69ef9b80-7a7e-11ea-9208-615333326270.png">

And here's the patch: 
[test-text.pd.zip](https://github.com/pure-data/pure-data/files/4458198/test-text.pd.zip)

---------------------------

I'm just doing what I've been doing in order to compile Pd for a few years now, and I do:

./autogen.sh 
./configure
make
make app

**Comment by umlaeute** [comment]
unable to reproduce in both the current `update/0.50` (f5cdf67045e6ccb05ecfa35aefd75501cd33b21d) and `master` ( e2ef8158e83900734d263a3fda343a47ed0c9e3a) branches.

and no, i wouldn't call this version `0.51` already (nor `51`)
since this repository holds a few thousand "versions" of Pd, i guess the proper way to reference a given version is by using the commitish, that is the *tag name* (e.g .`0.50-2`) if one exists (since we don't have a release right now, there's no tag yet), or the "sha" hash (e.g. e2ef8158e83900734d263a3fda343a47ed0c9e3a)

**Comment by porres** [comment]
yeah, I forgot to say, I'm on macOS

**Comment by umlaeute** [comment]
well yeah, your screenshot was giving youaway :-)

are you sure that you are using the latest and greatest Pd (which commit?)? because there is code in place that is supposed to specifically handle the problem you are mentioning (4f9c85ea2)

**Comment by porres** [comment]
> are you sure that you are using the latest and greatest Pd (which commit?)?

the last very one. I saw this happening in the branch from [knob], then I downloaded the latest source and saw it happening there too... but things work fine in 0.50-2

**Comment by Lucarda** [comment]
I can't reproduce on Windows.

`master` e2ef815 or `update/0.50`(20/3/2020).

**Comment by umlaeute** [comment]
> the last very one.

so: which one?

**Comment by porres** [comment]
https://github.com/pure-data/pure-data/commit/e2ef8158e83900734d263a3fda343a47ed0c9e3a

**Comment by porres** [comment]
Now that the 0.51-0test is out, I do not see this issue anymore, it seems this is related to the other issue that I was having with one of my externals - see https://github.com/pure-data/pure-data/issues/848

So, the problem seems to be that I'm compiling Pd wrong... I will ask on the pd list what I might be doing wrong 

thanks

**Comment by Spacechild1** [comment]
-2147483647 is a typical result of signed integer overflow being undefined behavior. BUT the code of `[text insert]` has the following line

https://github.com/pure-data/pure-data/blob/15761e59cdea4d654d6cae6f2b6960ea2b7dfab2/src/x_text.c#L1018

which is supposed to prevent the potential overflow issue... TBH, I have to no idea what's going on... Do you get the same result for `[text set]`?

**Comment by porres** [comment]
Ok, I edited my 1st comment, so all comments prior to yours can be deleted.

> Do you get the same result for [text set]?

Not sure what kind of test you wanted, but this works fine... what I get is that floats are added in the order I send float values (I'm assuming this is expected).

<img width="416" alt="Screen Shot 2020-05-29 at 09 49 40" src="https://user-images.githubusercontent.com/5360142/83261529-e276fc80-a191-11ea-8f28-91cdd6c92538.png">

**Comment by claudeha** [comment]
x_f1 is float, 0x7fffffff is not representable in float, so the float result of ?: is already out of range, perhaps. I see warnings when compiling, not able to check right now...

**Comment by Spacechild1** [comment]
> x_f1 is float, 0x7fffffff

it's not *exactly* representable as a float. Floats can certainly be larger than 0x7fffffff. Also note that we cast 0x7fffffff to a double, so `x_f1` should be widened appropriately for the comparison.

**Comment by Spacechild1** [comment]
@porres I need you to compare the behavior of large onset values for both `[text set]` and `[text insert]` with the *same* Pd version (the one you compiled yourself).

**Comment by Spacechild1** [comment]
Ok, I got it.

**Comment by Spacechild1** [comment]
The bug is gone when changing
`lineno = (x->x_f1 > (double)0x7fffffff ? 0x7fffffff : x->x_f1);`
to
`lineno = (x->x_f1 > (double)0x7fffffff ? 0x7fffffff : (int)x->x_f1);`

`lineno` is already an integer, so one would think that explicitly casting `x_f1` would be redundant. To me, this looks like a bug in clang... Compiler bugs are very rare, but they do happen after all...

**Comment by Spacechild1** [comment]
I pushed this "fix" to develop, also for consistency with `[text set]`, but I would like to understand why this seemingly unnecessary cast does the trick... I probably have to look into the assembly...

**Comment by Spacechild1** [comment]
@porres please test with latest develop and report back.

**Comment by porres** [comment]
> @porres please test with latest develop and report back.

IT WORKS :) 

Ok... we can close this now I guess, but what about https://github.com/pure-data/pure-data/issues/848 ? It's also an issue that only happens when I compile Pd.

**Comment by porres** [comment]
>  what about #848 ? 

opened a new issue about it... https://github.com/pure-data/pure-data/issues/1046

**Comment by claudeha** [comment]
> > x_f1 is float, 0x7fffffff
> 
> we cast 0x7fffffff to a double, so `x_f1` should be widened appropriately for the comparison.

I meant the other one which was promoted to float by the result type of ?:. Fix looks sensible to me.

**Comment by Spacechild1** [comment]
I think you're one to something, but I still fail to see where exactly the overflow / undefined behavior occurs...

**Comment by claudeha** [comment]
`x_f1` is float, so 0x7fffffff is promoted from int as ?: has a single result type, but nearest representable float is 0x8000000 which overflows when converted back to int. This is conjecture, looking at assembly would help resolve what is going on.

**Comment by Spacechild1** [comment]
Hmmm. From what I understand, the mantissa is truncated, so the value is effectively rounded *down* to the next representable value. But I'll do some reading and look at the disassembly.

**Comment by Spacechild1** [comment]
oh, you're right! both clang und GCC decide to round up `(float)0x7fffffff` at compile time:

https://godbolt.org/z/e2mtg2

Things get more interesting for `(int)(float)0x7fffffff`:

https://godbolt.org/z/DyKj3j

GCC outputs 2147483647 (as I would have expected), while clang outputs whatever value happens to be in `esi`.

**Comment by Spacechild1** [comment]
As a follow-up, here's what happens when converting an `int` to a `float` at runtime with `cvtsi2ss`:

"When a conversion is inexact, the value returned is rounded according to the rounding control bits in the MXCSR register or the embedded rounding control bits.

https://www.felixcloutier.com/x86/cvtsi2ss
