### ISSUE TITLE
fix iemguis documentation

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#940]
As it turns out, you can set colors with hexadecimal symbols, see https://github.com/pure-data/pure-data/pull/937

This calls for a fix this in the documentation that I'm doing as of the updates I've been doing in https://github.com/pure-data/pure-data/pull/829

For this matter, I think we can just present hex-notation in the documentation. The conversion to hex-notation from RGB seems way more straight forward using [makefilename].

----------------

There are also other updates I could take into account in the documentation rewrite if the PRs get merged. See also https://github.com/pure-data/pure-data/pull/942 and https://github.com/pure-data/pure-data/pull/938

----------------

Moreover, there's just a lot going on for iemguis (see https://github.com/pure-data/pure-data/issues/947 )

**Comment by porres** [comment]
Since I think that the other format is quite confusing and that we may just start saving this as hexadecimal (again, see: https://github.com/pure-data/pure-data/pull/937 ), we can just present in the documentation the hexadecimal format. Things would still work for backwards compatibility in old patches that convert things in that old way...

the conversion seems way more straight forward with hexadecimals, something like:

<img width="536" alt="Screen Shot 2020-04-14 at 15 03 27" src="https://user-images.githubusercontent.com/5360142/79258934-45226c00-7e62-11ea-8b33-f9e7c338de38.png">

**Comment by porres** [comment]
besides #937, there are other updates I could do if PRs get merged. Just as a note to myself, there's also https://github.com/pure-data/pure-data/pull/942 and https://github.com/pure-data/pure-data/pull/938

**Comment by porres** [comment]
> besides #937, there are other updates I could do if PRs get merged. Just as a note to myself, there's also #942 and #938

There's a lot going on for iemguis and we could also open new PRs to fix yet other issues. Instead of opening a new ticket here about ienguis refactoring. I'm just gonna point to other iemguis issues and I'm gonna ping @Ant1r to see if he'd be interested in helping out with those. I'm myself eager to give some of it a try as part of my effort to also rewrite iemguis documentation.

Other issues are:

- weird characters like "[" (as label) hang iemgui properties => https://github.com/pure-data/pure-data/issues/880 / possible duplicate => https://github.com/pure-data/pure-data/issues/417

- '$/#' substitutions on iemguis https://github.com/pure-data/pure-data/issues/558

- Issues with escaping things with '\' on iemguis https://github.com/pure-data/pure-data/issues/622

**Comment by Ant1r** [comment]
@porres sorry I'm not sure I'm feeling brave enough to fix those characters issues in iemguis...

I just gave a try to removing the #/$ substitution, and it doesn't seem to be a quick fix. Actually, if '$' is not substituted by '#', it simply gets removed between the Tcl side and the C side (i.e in the network transfer): e.g "$0-foo" becomes "0-foo". I don't know why neither exactly where.
This happens currently with a non-heading $: setting the label to "bar-$0" via the properties dialog  eventually sets the label to "bar-0". You have to type "bar-#0" instead.

I'm afraid other characters issues will be similarly tricky.

And TBH those issues have never been very important to me... Or I learned how to live with it.

**Comment by porres** [comment]
> I just gave a try to removing the #/$ substitution, and it doesn't seem to be a quick fix

I tried it last night as well and also failed miserably :(

**Comment by porres** [comment]
I guess we have to look into how 'gatom' deals with this... but you're right, it's not a quick fix. I'll keep looking. I know I have dealt with this in another way in cyclone/comment - it works, but it's kind of a different process

**Comment by umlaeute** [comment]
i think the documentation updates and any refactoring are orthogonal and should not go into the same issue (nor PR).

open two tickets if you want to (but try to not conflate independent things)

**Comment by porres** [comment]
> open two tickets if you want to (but try to not conflate independent things)

Ok, I'll open a new one that groups and adresses issues and other things related to "refactoring" and edit/delete comments/rewrite this one

**Comment by porres** [comment]
> open two tickets if you want to (but try to not conflate independent things)

just did and deleted/edited comments/title here

**Comment by porres** [comment]
this issue is now pointless and just confusing, I'm closing it
