### ISSUE TITLE
`system` from `stdio.h` is not available on iOS 11

### ISSUE THREAD

**Issue by rknLA** [pure-data/pure-data#95]
I'm not 100% sure if this is a beta bug with the latest Xcode or a deliberate deprecation/removal, but in any event, when I try to build `libpd` for iOS in Xcode 9 beta 2, I am seeing a compiler error in the `sys_putpreference` [here](https://github.com/pure-data/pure-data/blob/master/src/s_file.c#L302).  (I also don't have the latest version checked out, but it looks like the [other system call in `glob_forgetpreferences`](https://github.com/pure-data/pure-data/blob/master/src/s_file.c#L651) will also generate this error.

The error is: `'system' is unavailable: not available on iOS`

I almost filed this in https://github.com/libpd/libpd or in https://github.com/libpd/pd-for-ios, but since the core of the issue is here in pd itself, I thought this would be a better place.

Unfortunately, I also haven't fully figured out the best way to solve the problem, but it does look like it should be possible to set user defaults analogous to `defaults write` [using Core Foundation](https://stackoverflow.com/a/3693392/1309238).

**Comment by danomatika** [comment]
Preference save & load should be disabled when building on iOS. Should be an easy fix.

**Comment by umlaeute** [comment]
should they be disabled on *iOS* or for *libpd*? (i tend to favour the latter)

**Comment by danomatika** [comment]
I'm thinking libpd as the preferences are more related to the gui.

**Comment by danomatika** [comment]
This might as simple as not compiling s_file.c. @rknLA, can you remove s.file.c from Pd sources in your Xcode project, clean, & rebuild?

**Comment by rknLA** [comment]
@danomatika unfortunately it's not that simple.  Removing the file causes some reasonably vague linker errors:

```
  "_sys_defeatrt", referenced from:
  "_sys_flags", referenced from:
  "_sys_loadpreferences", referenced from:
  "_glob_savepreferences", referenced from:
```

At least it tells which functions are referenced, but unfortunately it doesn't say where

**Comment by danomatika** [comment]
Ok, then we need to have some sort of define, etc to disable it from the build for libpd.

**Comment by danomatika** [comment]
@millerpuckette I will look into this later, but it seems like the preference saving needs to be modular so it can be disabled for libpd. Maybe function stubs somewhere or a define?

**Comment by rknLA** [comment]
Is stubbing out preference saving preferable to using CoreFoundation in this case?

**Comment by danomatika** [comment]
The preferences largely make no sense to a libpd context, so there's no need to use that functionality. They are mainly related to pd desktop and the pd GUI, i.e. startup flags, default audio devices, global search paths, etc.

**Comment by millerpuckette** [comment]
OK - pull request here:  https://github.com/libpd/libpd/pull/171 should get libpd up and running with ltest pd.

**Comment by danomatika** [comment]
In looking into this so far, I've run into an issue. Looks like Apple doesn't have an implementation of the thread-local storage, so building with PDINSTANCE set gives me an error on __thread:

    Thread-local storage is not supported for the current target

This may be due to a setting in the Xcode project and I will dig further.

**Comment by millerpuckette** [comment]
indeed, I made the thread-local storage depend on PDINSTANCE since I
learned that iOS doesn't allow it... this came out of a discussion about
libpd - I'm not sure where I saw it (libpd on github maybe).

So I think, yes, you have to disable PDINSTANCE there.

M

**Comment by danomatika** [comment]
Ok, that makes sense. I tried turning it on as the test app built with the default settings but didn't render any audio. Might be something else.

From what I've read, TLS support should be available in newer versions of iOs etc so it's good to have that flag instead of preprocess or detection.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by danomatika** [comment]
Ok. This should be fixed with the latest merge in libpd. Please test.
