### ISSUE TITLE
new object request: adoutput~

### ISSUE THREAD

**Issue by jmmmp** [pure-data/pure-data#954]
Having an object like adoutput~ (https://docs.cycling74.com/max7/refpages/adoutput~) would make it quite easy to monitor all outgoing channels, or make a mix of all open patches.

**Comment by Spacechild1** [comment]
That's interesting. Actually, Supercollider has something similar: every `Server` instance has a `Recorder` instance which is the last node in the graph.

Personally, I only ever have one `[dac~]` instance in a given patch (IMO, having more than one `[dac~]` in a single patch is really an anti pattern), so guess this is meant for situations where people are running several patches simultaneously and want to record the summed output?

**Comment by porres** [comment]
> guess this is meant for situations where people are running several patches simultaneously and want to record the summed output?

Seems like the only use case I can think of, but you can also use some audio routing system and record it into some DAW.

Where I'm getting is that maybe this is kind of a restricted use case and might be better as an addition to a library (i.e. cyclone)? But changes to the core to allow such an object could be required...

**Comment by Spacechild1** [comment]
> Seems like the only use case I can think of, but you can also use some audio routing system and record it into some DAW.

I guess then it's probably easier just to drop in some `[throw~]`s and `[catch~]`s... Actually, it's easy to make an abstraction which sends audio to the `[dac~]` and also to a `[catch~]` of a given name.

> But changes to the core to allow such an object could be required...

We certainly need a core change for this: currently there's no way to access the *last* DAC buffer, simply because Pd doesn't keep it around.
