### ISSUE TITLE
[declare] feature request: supress loaded libraries console output

### ISSUE THREAD

**Issue by jmmmp** [pure-data/pure-data#955]
Sidetrack from the discussion #281. Since one of the arguments is that a "didn't load" message doesn't need to appear, as a) it's redundant because it any effects will manifest on "didn't create" messages and b) it's annoying to have more text in the console, I have a different suggestion: 
can [declare] have a tag to supress the messages that appear when a library is loaded? My argmuents are:
- if it's irrelevant for an error message to appear, it's even more irrelevant a success message to appear. Specially when this message doesn't give more information than "version X by that guy, welcome" + some ascii art
- for unexperienced users, it's confusing to see lots of messages which they think it's important. As mentioned in #281, these messages probably can be accessed by peeking into loglevel 3?
- by loading 2 or 3 libraries these messages can fill up the console completely, and obfuscate any messages that might be relevant to the patch.
- as suggested in #281, this information can be accessed in a query, so it's not necessary to make it visible all the time

**Comment by Spacechild1** [comment]
> an [declare] have a tag to supress the messages that appear when a library is loaded?

That's a bit hard to implement because Pd is not really aware of those success messages at all. Many externals simply print some text with the `post()` API method. Pd *could* temporarily disable all logging while loading a library, but this is really a hack.

Ideally, all externals would rather use the `verbose()` method with loglevel 3, but this is wishful thinking.

**Comment by umlaeute** [comment]
> Ideally, all externals would rather use the `verbose()` method with loglevel 3, but this is wishful thinking.

note that suppressing splashscreens of externals might actually be a copyright/license violation.

it might be "annoying", but that's probably not a good reason to get illegal.

**Comment by Spacechild1** [comment]
haha, I didn't think of it that way. Well, those externals which need to show a splashscreen must use loglevel 0 then ;-)
