### ISSUE TITLE
[send] doesn't understand literal "\$n" from symbol in secondary inlet

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#962]
It does understand something like "a\ b" though, see picture and test patch below

[test-s.pd.zip](https://github.com/pure-data/pure-data/files/4504523/test-s.pd.zip)

<img width="458" alt="Screen Shot 2020-04-20 at 12 33 16" src="https://user-images.githubusercontent.com/5360142/79770142-63c1b080-8303-11ea-95c0-71ff3f76887b.png">

**Comment by porres** [comment]
wait...

**Comment by Ant1r** [comment]
> we've been through this already, right? :)

hmm... not sure. it should work...

**Comment by porres** [comment]
> hmm... not sure. it should work...

this is how you should do it, anyway, I'm making this clear (so I don't forget again) in my own tutorial... I could get this into the documentation somewhere, eventually

<img width="201" alt="Screen Shot 2020-04-20 at 13 09 31" src="https://user-images.githubusercontent.com/5360142/79773802-48a56f80-8308-11ea-9756-a95fb3084177.png">

**Comment by porres** [comment]
Ideally, we could have an alternative in Pd that would allow us to expand the literal $0 (aka "\$0") from a symbol... I have an external for that, and maybe it could be a functionality for [pdcontrol]? Like, a "dollarzero \$0-x" message to [pdcontrol] could give us the expanded symbol.

<img width="180" alt="Screen Shot 2020-04-20 at 13 23 57" src="https://user-images.githubusercontent.com/5360142/79775329-7390c300-830a-11ea-8bc1-c4ee8712a814.png">

**Comment by Ant1r** [comment]
I think it's better to fix the bug (if possible).

**Comment by porres** [comment]
what bug? I understand this now as expected behaviour, though it might be confusing.

**Comment by Spacechild1** [comment]
Yes, there's no bug, as your comment has shown https://github.com/pure-data/pure-data/issues/962#issuecomment-616653800

And I vaguely remember we already had this very discussion some month ago?

**Comment by porres** [comment]
> And I vaguely remember we already had this very discussion some month ago?

yeah, that's why I said "sorry, we've been through this before"... but now that we're at it again...

> what bug? I understand this now as expected behaviour

well, I'm not sure again... 

I guess the question is: should a literal "$0" symbol get expanded in the second inlet of [send]? I just went back and front with this... I'm now going back to the idea it should...

Would this break anything? 

The fact is that sending it a symbol like "\$0-x" sets a send to send information to a [receive \$0-x] object, not [r $0-x]...

For me it's quite intuitive that sending it "\$0-x" should expand... it's not the first time it throws me off

**Comment by Ant1r** [comment]
Sorry, I agree now there is no bug!

`[symbol \$0-x(` really is the symbol "$0-x", although `[symbol $0-x]` (once created) is something like "1003-x".

In your first example, you can receive what is sent to the right hand `[s]` with a `[r \$0-x]`: everything is normal.

IMO this (confusing!) thread can be actually closed.

**Comment by umlaeute** [comment]
i'm totally convinced that any arbitrary symbol you get via a message should handle this symbol as immutable.
that is, the symbol should not be expanded, whether it uses `$`, `#` or curly braces, but stay as it is.

there is *absolutely* no reason why `[send]` should behave differently than any other object.

i can see benefits of dynamic expansion of $args (any argument, not just `$0`) but this should be left to a specialized object (and while i really think that the design of `[pdcontrol]` is horrific, i agree that expanding arguments is in the same league as it's `[args(` message).

closing this as everybody agrees that there's no bug.

**Comment by porres** [comment]
> i can see benefits of dynamic expansion of $args  (any argument, not just $0)

I actually have an use case for expanding "\$0" (hence my [dollarzero] external), but not "\$1" and so on... can't think of any yet.
