### ISSUE TITLE
remove floss link from about Pd

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#966]
About Pd tells us "More extensive FLOSS documentation is available on:
    http://en.flossmanuals.net/PureData (English)
    http://fr.flossmanuals.net/PureData (Francais)
"

but these links are dead, and the floss might be really outdated anyway - maybe just remove this

**Comment by porres** [comment]
oops, only "english" is a dead link...

**Comment by Lucarda** [comment]
this is fixed in https://github.com/pure-data/pure-data/pull/720

here is the [preview](http://lucarda.com.ar/html-preview-2/x1.htm#s2)

I have to resolve one conflict in the PR.
