### ISSUE TITLE
Pd.app packaged with embedded Tcl/Tk framework crashes on launch

### ISSUE THREAD

**Issue by rnkn** [pure-data/pure-data#97]
Furthering recent chats on the mailing list, I've tried packaging Pd.app with the included scripts, specifically with an embedded Tcl/Tk framework, and the resulting Pd.app is crashing on launch.

I've removed ActiveTcl/Tk entirely from my system first, just leaving the Apple system Tcl/Tk.

Steps from git clone:
~~~
$ ./autogen.sh
[...]
$ ./configure
[...]
$ make
[...]
$ cd mac/
$ ./osx-app.sh -t 8.6.6 prod
[...]
$ open Pd-prod.app
~~~

Backtrack here:
https://gist.github.com/rnkn/0f6fafa718b164ad7ebc0a58d90e254e

**Comment by rnkn** [comment]
And the same crash with:
~~~
$ ./osx-app.sh -t 8.5.19 prod
~~~
Backtrace:
https://gist.github.com/rnkn/a72c999e9514e9b98662da374b293d51

**Comment by rnkn** [comment]
Tried building from branch `update/gui-updates` with same result.

Backtrace:
https://gist.github.com/rnkn/71ed60ace05259cd7b5676663e32fcf8

@danomatika have you successfully build Pd.app with embedded Tcl/Tk?

**Comment by danomatika** [comment]
Yes I know about this. It's not Pd as the Wish app that is being built also crashes. It's either a big in Tk or more likely something in the tcltk-wish.sh build script.

**Comment by rnkn** [comment]
Ahhh yeah I had forgotten... pretty sure a few months ago I tried downloading and building Tcl/Tk from the Tcl Developer Site (as opposed to ActiveTcl) and Wish.app crashed on launch, no matter which way I built.

You're on macOS right? Is the same happening for you or is it something funky with my system?

**Comment by danomatika** [comment]
> You're on macOS right?

Yes, hence all the work for mac builds.

> Is the same happening for you or is it something funky with my system?

Happening to me. I tried earlier versions of Tk and was getting the same result. I will have to do some investigation and try a normal, non embedded build.

**Comment by danomatika** [comment]
I just build the full, non embedded version of Tcl/TK 8.6.6 and the Wish.app still crashes. I think this is a bug in Tk on macOS 10.12 as this worked fine on 10.11.

**Comment by rnkn** [comment]
Might be an Apple-side issue... discussion here: https://github.com/git/git-scm.com/issues/853

**Comment by danomatika** [comment]
Looks like it's been fixed in current TK development: https://github.com/tcltk/tk/commit/77e0c5e9fb76f2aa4dd4f3d9545f3bf22b77cdc4

**Comment by rnkn** [comment]
Cool, I'll give it a try.

**Comment by danomatika** [comment]
@rnkn You can hold on a second. I'm adding cloning from git to the tcltk-wish.sh script.

**Comment by danomatika** [comment]
The current master is working, no crashes. Here's the overview of the new --git option:

    # build Wish-master-git.app with the latest master branch from git
    tcltk-wish.sh --git master-git 

    # build Wish-8.6.6-git.app with embedded Tcl/Tl 8.6.6
    # from git using the core_8_6_6 tag in the master branch
    tcltk-wish.sh --git 8.6.6-git -b master core_8_6_6

**Comment by danomatika** [comment]
I'm going to close this for now as it was an issue in Tk.

**Comment by rnkn** [comment]
Cool, I jumped the gun and built Wish.app from Tcl/Tk master separately.
