### ISSUE TITLE
No ASIO on Windows 7 (64-bit)

### ISSUE THREAD

**Issue by Shmalzfinger** [pure-data/pure-data#971]
My vanilla-Pd crashes (on Windows) when I try to select ASIO (via portaudio).

MMIO works, but crackles sometimes, and I would like to use ASIO as it should be the best option for audio in Windows. (?)

I'm on:

- Pd-vanilla portable, ver. 0.50-2 (tried some older versions where the same thing happens)
- Windows 7 64-bit

In the audio settings dialog, no ASIO drivers are shown. (Even though I already re-installed the newest verion of ASIO4ALL, and my interface (M-Audio C400) also has ASIO drivers of its own)

Now, when clicking ASIO (via portaudio) in Pd's menu, it crashes and I get the following dialog:

"Microsoft Visual C++ Runtime Library
This application has requested the Runtime to terminate it in an unusual way."

After this, another dialog appears, saying "Fatal Error: Failed to register menu window class."

Version 0.45-4 (and 0.45), didn't throw the Visual C++ error, but a dialog box said: "Fatal Error in Wish: Failed to register menu window class." Then Pd's window disappeared. Crashed the second time even without a dialog...

Using "-asio" via command line makes Pd crash straight away. Using only "-listdev", no ASIO devices are shown (as probably expected).

I already had trouble in other programs because of missing VSC++ runtime redistributables and since have installed a whole bunch of them (in fact, all versions that I was able to find and install). Anybody any idea which version I might specifically need?

Or, what else might be the cause of the problem?

Could it somehow be related to the portable version of Pure Data?

**Comment by porres** [comment]
hi, what is "the portable version of Pure Data"?

**Comment by Spacechild1** [comment]
@porres it's just a .zip file containing Pd, instead of the installer.

**Comment by Spacechild1** [comment]
@Shmalzfinger 

> Version 0.45-4 (and 0.45)

We're currently at Pd 0.50.2. Can you try with the latest Pd vanilla? ASIO certainly works for me (Windows 7)

**Comment by Spacechild1** [comment]
In fact, recent Pd vanilla is built entirely with MinGW and therefore doesn't depend on the VC++ runtime.

**Comment by porres** [comment]
he says he's on 0.50-2 and also tried earlier versions

**Comment by Spacechild1** [comment]
you're right, sorry.

**Comment by Spacechild1** [comment]
@Shmalzfinger what happens when you use the installer? Did you try with 32-bit or 64-bit Pd? Try both and report back.

**Comment by Shmalzfinger** [comment]
@Spacechild1 

> In fact, recent Pd vanilla is built entirely with MinGW and therefore doesn't depend on the VC++ runtime.

@Spacechild1 But why do errors pointing to them appear? Does ASIO depend on runtimes?

I just tried both installers, 64-bit and 32-bit, none of them work either. Just the messages were different. In the 32-bit version, this dialog appears again: "Fatal Error in Wish: Failed to register menu window class."

**Comment by Spacechild1** [comment]
> "Fatal Error in Wish: Failed to register menu window class."

Ok, this actually points to a problem in the GUI. What happens when you run the 32-bit version from the command line with `-asio -nogui` ?

**Comment by Shmalzfinger** [comment]
Pd.exe does nothing that is visible to me. It does not show up in the task manager either. Looks like it doesn't really want to start or something crashes before it can?

Pd.com throws a little windows dialog box saying that the program doesn't function properly anymore. (sry, I'm on a german machine, don't know what the exact error msg in english would be).

This same dialog box also lets me click on a Debug option (never done any debugging since I'm not really a coder) and just for fun I tried that. Even though Visual Studio ouptut something along the lines that the project could not be opened, it shows a tab titled "no symbols loaded" (?) 
Then, a big heading announces "AsioDriver.pdb not loaded" (again, these are translated into English by me, since my version of VS is German). It also shows information about the ASIO driver .DLL of my sound interface. It says "exception error [hope that's the right term] at 0x734E58E9 (MAudioFastTrackC400_Asio.dll) in pd.com: 0xC0000005: access violation while reading at position 0x00000008"

 - I can only guess that this means the driver can/could not be correctly loaded?
   does the access violation mean that I/Pd doesn't have the rights to load it? (thinking whether opening as admin might be of any difference?)

**Comment by Spacechild1** [comment]
Ok, this rather looks like a problem with your ASIO driver... does the same happen with ASIO4ALL?

**Comment by Spacechild1** [comment]
you can post any error dialogs, German is my native language :-)

**Comment by Shmalzfinger** [comment]
Ok, so after uninstalling the drivers and reinstalling them it works as expected! 
I can select MMIO or ASIO and all devices are shown in the configuration windows. A quick check with the audio test also worked and after adjusting the samplerate ASIO4ALL worked, too.

Thank you very much for your input. 

So, I guess I can close this thread now? (Sorry, still new to Github)

**Comment by Spacechild1** [comment]
Great to hear that things work now for you!
