### ISSUE TITLE
array name doesn't show when first inserted via the put menu

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#979]
you have to click and drag so it can appear, or close and reopen the patch window.

**Comment by sebshader** [comment]
as far as I can tell it's because garray_redraw called by graph_array only draws the scalar, not the graph (which is the "holder" of the scalar and also owns/draws the name). perhaps it should be something like graph_vis instead of garray_redraw?

**Comment by porres** [comment]
what is the thing that draws the graph then? and why doesn't it draw the name when it is first created?

this seems like a pretty easy fix when instantiating the object, but I'm still lost

**Comment by sebshader** [comment]
in glist_arraydialog a graph is made with glist_addglist() (which draws it when it calls glist_add() I think) and then the array is put in it with graph_array() (which eventually calls garray_vis(), which only calls vis on the scalar). So maybe the best solution would be to take the relevant code to draw the name from graph_vis() and put it in graph_array(). Either that or call graph_vis itself, perhaps instead of garray_redraw.

**Comment by porres** [comment]
> in glist_arraydialog a graph is made with glist_addglist() 

ok

> which draws it when it calls glist_add() I think

don't think so, glist_add() is in graph_scalar()

> and then the array is put in it with graph_array() (which eventually calls garray_vis(), which only calls vis on the scalar). 

I'm lost already, but I'll try looking... maybe you feel more prepared and encouraged to try and fix this? :)

**Comment by sebshader** [comment]
> don't think so, glist_add() is in graph_scalar()

that's for adding the scalar to the graph. I'm talking about adding the graph that holds the scalar to the parent canvas

> I'm lost already, but I'll try looking... maybe you feel more prepared and encouraged to try and fix this? :)

maybe I'll give it a shot later..

**Comment by sebshader** [comment]
I just changed garray_redraw to glist_redraw

**Comment by porres** [comment]
> I just changed garray_redraw to glist_redraw, that seemed to work

Tested here, and yeah, it's doing the job! Thanks so much!
