### ISSUE TITLE
Audio device with japanese characters causes Tcl error

### ISSUE THREAD

**Issue by Spacechild1** [pure-data/pure-data#980]
A student of mine with a Japanese laptop couldn't open the audio settings in Pd because the device names would cause a Tcl error:
```
(Tcl) UNHANDLED ERROR: extra characters after close-brace
    while executing
"lappend audio_indevlist {MMIO:Microsoft TEh }"
    ("uplevel" body line 2)
    invoked from within
"uplevel #0 $docmds"
```
The offending audio device has the name `Microsoft サウンド　マッパー`, which is `Microsoft Soundmapper` written in Katakana.

Happened with Pd 0.50-2 64-bit on Windows 8.

**Comment by umlaeute** [comment]
hmm, i tried reproducing it on a VM running WIndows10.

- original setup was US-English
- installed Pd-0.50-1
- installed the Japanesee Language Pack
- made "Japanese" the preferred language
- powered down the machine
- enabled the VMs audio device (originally it had none)
- powered the machine up
- opened Pd: the soundcard was displayed without errors, but CJK characters are rendered as question marks:

![audiosettings](https://user-images.githubusercontent.com/214034/81173551-8a891380-8fa0-11ea-95b8-12c43834ac37.png)

- installed Reaper. even there the soundcard names are shown as question marks:

![reaper](https://user-images.githubusercontent.com/214034/81173690-c3c18380-8fa0-11ea-8b69-0080241fad61.png)

this is mainly to show that it is non-trivial to trigger the problem on a system that has not been setup in japanese from the beginning.
also note, that it is non-trivial to navigate a Japanese desktop if you don't speak the language.

**Comment by Spacechild1** [comment]
I think on Windows you can only change the actual system language by reinstalling Windows with the desired language. The language packs only help with localization, like menus and dialogs, keyboard input, etc.

> also note, that it is non-trivial to navigate a Japanese desktop if you don't speak the language.

I can help with that (within certain limitations)

**Comment by Spacechild1** [comment]
I should have asked the student to open "standard MMIO" to rule out a problem in portaudio... Will try that when I meet her next time.
