### ISSUE TITLE
[netsend] documentation request

### ISSUE THREAD

**Issue by dfkettle** [pure-data/pure-data#981]
This is just a minor quibble about the help file for [netsend], but it might help others who are trying to use it for the first time (like I was). I was initializing the [netsend] in a sub-patch, but had another sub-patch for sending messages to it. In other words, I had it instantiated in two places and couldn't figure out why the send wasn't working. Eventually I guessed that it could only be instantiated in one place (for any given destination address and port), and I got it to work. Maybe you could add a comment to the help file so others won't make the same silly mistake I made.

**Comment by porres** [comment]
so we should say that two [netsend] need to have different addresses, right?

**Comment by Spacechild1** [comment]
I'm not sure I understand, `[netsend]` binds to a random port, unless you specificy the receive port with `[connect <host> <port> <receiveport>(`. Maybe you meant `[netreceive]`?

**Comment by porres** [comment]
anyway, I already made an attempt to fix this as I understood it, but I can change it of course... see 
https://github.com/porres/pure-data/commit/0c6ad9575e31c1042753deefd58ac219fa49cd7b

**Comment by Spacechild1** [comment]
> so we should say that two [netsend] need to have different addresses, right?

I don't understand what you mean by address here.

**Comment by porres** [comment]
> I don't understand what you mean by address here.

port number? But nevermind, I know very little about these objects

**Comment by dfkettle** [comment]
Obviously, I didn't explain very well. First, by "address" I mean the IP address. The [netsend] object needs to be initialized with an IP address and a port number. I most definitely mean [netsend], not [netreceive], which only needs to be initialized with a port number if you're using UDP and not TCP  (it doesn't care where the message came from, why should it?). And neither of them bind to a "random port", AFAIK. They both need a port number.

I'll post an example later of what I was trying to do, maybe it will make more sense. But this isn't urgent, I just thought the documentation in the help patch could be improved a little.

**Comment by umlaeute** [comment]
1. `[netreceive]` takes the port is *listens* to as an argument, e.g.:

        [netreceive 8888]
        |

1. `[netsend]` doesn't take any address as argument. you must set the address it *sends* to via a message, e.g.

        [connect localhost 8888(
        |
        [netsend]


3. you can only have a single application **listen** on any given port on an interface. the Pd-object `[netreceive]` (and related, e.g. `[tcpreceive]` from iemnet/mrpeach) counts as an application; so you cannot have two `[netreceive 8888]` (listening on the same port) in one patch.

4. however, you *can* have multiple `[netsend]` objects all sending **to** the same address. (these objects will *listen* on a port as well - for talkback. however, this port is *any* free port chosen by your OS - unless you override that (as @Spacechild1 mentioned); if you let the OS chose the port for you (which is the default behaviour), then you could have about 65000 simulatenously open connections; unlikely you are doing any such thing).

5. so the following patch is perfectly valid, and working on my machine (it will print "received: foo" and "received: bar" every 0.5sec to the Pd-console)

~~~
      [netreceive 8888]
      |
      [print received]


      [loadbang]
      |
      [delay 1000]
      |
      [t    b     b]
      |            |
      [metro 500]  |
      |            [connect localhost 8888(
      [send foo(   |
      |  __________/
      |/
      [netsend]


      [loadbang]
      |
      [delay 1000]
      |
      [t    b     b]
      |            |
      [metro 500]  |
      |            [connect localhost 8888(
      [send bar(   |
      |  __________/
      |/
      [netsend]

**Comment by umlaeute** [comment]
@dfkettle by the way, would you mind changing the title to something meaningful? (and just change the title; don't reply to this post, as i will remove it once done)

**Comment by dfkettle** [comment]
@umlaeute I'm not sure what you would consider meaningful, so I'll leave that up to you. I thought the title was meaningful, but I guess it's not. Also, thanks for the explanation, but it doesn't really cover what I was inadequately trying to explain.

Here's a simplified (and contrived) example of the silly mistake I was making. Keeping in mind that the two [netsend] objects were in sub-patches (because I was doing something more involved and wanted to encapsulate the logic), my mistake (due entirely to my lack of understanding) was that I had two [netsend] objects, even though my intention was to create only one connection. I was intializing one of them (the one on the left) but sending the message to the other one (the one on the right). So if you set the toggle switches so that the message is sent to the one on the left, it works, but if you send the message to the one on the right, it doesn't. This is probably obvious to anyone that's used [netsend] and [netreceive] before, but this is the first time I've used them Maybe rather than updating the help patch, a tutorial on how to use [netsend] and [netreceive] might be more appropriate. Anyway, I understand now. I just thought it might help other people who have never used these objects before. But if you think this is painfully obvious to anyone else but a dummy like me, just ignore my request and close the issue.

![Example](https://user-images.githubusercontent.com/8409615/81174625-2ea69680-8f70-11ea-8c2f-be5677e1b8b8.png)

**Comment by umlaeute** [comment]
thanks for you patch.
i wonder, how your problem is in any way specific to `[netsend]`?

e.g. replacing the networking objects with ordinary `[send]` and `[receive]` will exhibit the same problem.
(the networking makes it somewhat harder to debug, as you are probably expecting the problem to be "on the wire")

so the problem seems to be obvious to anyone who has used `[spigot]` before :-)

**Comment by dfkettle** [comment]
Well, ultimately I want to send/receive to another computer on the same LAN, so I have to use UDP or TCP, not [send]/[receive] (which I've used many times). And it has nothing to do with [spigot], I just added the [spigot] to try to explain what the problem was. So at this point, I give up. I'll just close the issue, since it seems it isn't an issue.

**Comment by umlaeute** [comment]
regarding the title:
> i'm not sure what you would consider meaningful

"documentation request" is probably *meaningful* (in the wide sense), but it is very generic.
in the same spirit, we could also use "please change the code" as the title for each and every bug *and* feature request on this tracker. but that wouldn't help anybody.

**Comment by dfkettle** [comment]
The title was "[netsend] documentation request", not "documentation request", which would be rather generic.

**Comment by umlaeute** [comment]
> Well, ultimately I want to send/receive to another computer on the same LAN, so I have to use UDP or TCP, not [send]/[receive] (which I've used many times).

i was using `[send]`/`[receive]` to illustrate the problem (as i understand it), not to suggest that you use it in the production patch.

> And it has nothing to do with [spigot], I just added the [spigot] to try to explain what the problem was. 

i really don't understand why you put the `[spigot]` in there in the first place.

but the problem is still a generic one.
e.g. if you have two `[writesf~]` objects, and send the `[open <filename>.wav, 1(` message to only one of them, then only this one will record.
or if you have two `[*~]` objects for adjusting the gain, and leave one uninitialized (at 0) and raise the gain to `1´ in the other, only one will output a non-muted signal.

in general i think it is a feature of Pd that only the object that receives a given message, changes it's internal state. makes it much easier to reason about the functionality of the patch.

> So at this point, I give up. I'll just close the issue, since it seems it isn't an issue.

i don't know. i still try to understand the problem (and it seems i'm pissing you off while doing so; which is not my intention)

**Comment by umlaeute** [comment]
> The title was "[netsend] documentation request"

indeed i missed the prefix.
sorry for the confusion.

**Comment by umlaeute** [comment]
so could your patch be simplified as follows?

![netsend](https://user-images.githubusercontent.com/214034/81177430-ed7da900-8fa6-11ea-84a0-1a3a23e3a3fb.png)

**Comment by Spacechild1** [comment]
`[iemnet/udpsend]` gives you an error message if you try to send a message without being connected, and I could see how `[netsend]` could behave the same. Sending a message to a not-connected `[netsend]` is probably always an error, so a warning could be useful.

**Comment by umlaeute** [comment]
i'm pretty sure that `[udpsend]` inherited the error-message from `[netsend]`.

it seems it has been removed in 1be72191ddc9c6b2bf27f8c69faa5fba6d9092f6 (though it's not clear to me why)

**Comment by Spacechild1** [comment]
ah! we probably should put it in again.
