### ISSUE TITLE
request: new [list save] object

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#985]
It always annoyed the hell out of me that we don't have simple object to store lists, like [float]/[symbol]. Yeah, I know there are ways of doing this, and you can adapt [list append] for that, but it's still annoying, it requires extra steps, and it's just not the same thing under the hood.

Since the name [list store] is taken, I propose a new [list save] object.

It would work as [float]. An argument stores an initial list, a right inlet replaces the list, a bang outputs the saved list, and a message into the main inlet outputs the list and saves it.

**Comment by porres** [comment]
I attempted a PR but failed miserably in trying to store the right inlet incoming list.

**Comment by fdch** [comment]
Is this not how [list] works? 
Or, does banging the 1st inlet frees the list from the 2nd inlet? I forget. 

If the latter is the case, [t a a] would not be such a terrible thing. 

Also, [list save] might be misleading, like saving to the pd patch whatever list the object has

**Comment by porres** [comment]
> Is this not how [list] works?

nope, not how [list] (short for [list append]) works. If you send a list to the left inlet, it appends the list to the right to it.

> Also, [list save] might be misleading

can't think of a better name

**Comment by umlaeute** [comment]
what's wrong with this:

~~~
[inlet]        [inlet]
|              /
[route  bang] /
|           |/
[list append]
|
[outlet]
~~~

and use a bit of `[pdcontrol]` foo if you want initial arguments as well.

there's no performance improvements when having that as a built-in.
and it's simple enough to build it as an abstraction.

**Comment by umlaeute** [comment]
and for me, `[list save]` really means "save to disk" or so.

**Comment by fdch** [comment]
I fail to understand. This is what I mean with how list works (like [f] or [symbol]):
```
[bang( 
|         [1 2 3(
|       /
[list]
|
[print]
```
If you update the second inlet, you are keeping the list internally, so you can `[bang(` and it will output the internal values.

**Comment by porres** [comment]
> I fail to understand. This is what I mean with how list works (like [f] or [symbol]):

but, as I said, the problem is in the behaviour of the left inlet, not the right one...

> what's wrong with this

Well, like I said, I know "you can adapt [list append] for that". And I can add I know people might not have a problem with it and may think it's too much of a hassle to add something else just for that since it's "simple enough to build it as an abstraction". What's "wrong" is that I just have a different opinion and think this would be worth it.

> and for me, [list save] really means "save to disk" or so.

since "store" s taken, I don't really know of a better name. Though I omitted the fact that [cyclone/zl] has a "reg" mode that does that. But I don't know, this name doesn't mean much to me...

**Comment by Spacechild1** [comment]
I agree with the others that you can already use `[list append]` for what you need. I don't see a reason to add a whole new method for that. On the other hand, you might like https://github.com/pure-data/pure-data/pull/827

**Comment by porres** [comment]
> you might like #827

nah...

well, so I'm really the only one onboard on this? Well, I thought so and had this coming I guess :) good thing I asked... 

I could at least add an example to [list]'s help file showing the adaptation of [list append] for that
